OpenNMS/opennms

- opennms-doc/guide-doc/src/asciidoc/text/introduction.adoc
- Improved module description for guide-doc
- Improved module description for guide-user
- Improved module description for guide-admin
JIRA: http://issues.opennms.org/browse/NMS-7267
Todo:
> NMS-7267: Unclear-module-description-admin-user-doc

- opennms-doc/guide-doc/src/asciidoc/configs/poller-configuration.xml
- opennms-doc/guide-doc/src/asciidoc/text/include-source.adoc
- Changed include to begin with a # instead of XML comment
JIRA: http://issues.opennms.org/browse/NMS-7330
Todo:
> NMS-7330: Fix include parts of a configuration

- opennms-doc/guide-user/src/asciidoc/index.adoc
- opennms-doc/guide-user/src/asciidoc/text/placeholder.adoc
- opennms-doc/guide-user/src/asciidoc/text/rest/CORS.adoc
- Document how to enable/configure CORS support
JIRA: http://issues.opennms.org/browse/NMS-7264
Todo: 
- [ ] Formatting and conventions
> NMS-7264: Document CORS support

- opennms-doc/asciidoctor-default.css
- opennms-doc/pom.xml
- Added asciidoctor default theme to allow creating a opennms-doc-theme.css
- Added reference to be used in all opennms-doc maven modules in the parent main pom
JIRA: http://issues.opennms.org/browse/NMS-7329
Todo:
> NMS-7329: Add asciidoctor default theme

- opennms-base-assembly/src/main/filtered/etc/eventconf.xml
- opennms-base-assembly/src/main/filtered/etc/events/Siemens-HiPath3000.events.xml
JIRA: http://issues.opennms.org/browse/NMS-7310
Todo:
> NMS-7310: Add Siemens HiPath 3000 Events

- opennms-base-assembly/src/main/filtered/etc/eventconf.xml
- opennms-base-assembly/src/main/filtered/etc/events/Siemens-HiPath3000-HG1500.events.xml
JIRA: http://issues.opennms.org/browse/NMS-7311
Todo:
> NMS-7311: Add Siemens HiPath3000 HG1500 Events

- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/ReportSelectListAppController.java
- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/presenter/CustomReportSelectListPresenter.java
- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/view/CustomReportSelectListView.java
- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/view/CustomReportSelectListViewImpl.java
- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/view/CustomReportSelectListViewImpl.ui.xml
- features/gwt-graph-resource-list/src/main/java/org/opennms/features/gwt/graph/resource/list/client/view/ReportSelectListCellTree.java
- opennms-webapp/src/main/scss/opennms-theme.scss
- opennms-webapp/src/main/webapp/graph/adhoc2.jsp
JIRA: http://issues.opennms.org/browse/NMS-7308
Todo:
- [ ] 4-eye review
> NMS-7308: Enforce selecting a single resource for Custom Resource Performance Reports

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/poller/XmpMonitor.adoc
- protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/monitor/XmpMonitor.java
- Created documentation for the XMP monitor
- Include in main index file
JIRA: http://issues.opennms.org/browse/NMS-6702
Todo:
> NMS-6702: Documentation XMP monitor

- opennms-doc/asciidoctor-default.css
- pom.xml
- Update maven plugin reference in main pom
- Asciidoctor introduced a stylesheet factory and updated to latest stylesheet
JIRA: http://issues.opennms.org/browse/NMS-7461
Todo:
> NMS-7461: Update asciidoctor plugin 1.5.0 to 1.5.2

- opennms-webapp/src/main/java/org/opennms/web/rest/TimelineRestService.java
JIRA: http://issues.opennms.org/browse/NMS-7511
Todo:
- [ ] Review code
- [ ] Merge to develop
> NMS-7511: Timeline renders very slowly with a couple hundred outages

- opennms-webapp/src/main/webapp/includes/nodeAvailability-box.jsp
JIRA: http://issues.opennms.org/browse/LTS-95
Todo:
- [ ] Merge to develop
> LTS-95: Outage graph on node page badly formatted for unmanaged IP interfaces

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareCimMonitor.java
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
Please see 
http://issues.opennms.org/browse/NMS-7213
for more information.
> Fix for issue NMS-7213

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/model/Category.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/model/ColumnDef.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/model/RowDef.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/model/SurveillanceViewConfiguration.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/model/View.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/service/SurveillanceViewService.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/dashboard/SurveillanceViewAlarmTable.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/dashboard/SurveillanceViewGraphComponent.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/dashboard/SurveillanceViewNodeRtcTable.java
- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/dashboard/SurveillanceViewNotificationTable.java
See issue
http://issues.opennms.org/browse/NMS-7570
for details.
> Fix for jira/NMS-7570

- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/CORS.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/acknowledgements.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/alarm_statistics.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/alarms.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/events.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/examples.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/foreign_sources.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/groups.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/ksc_reports.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/links.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/maps.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/nodes.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/notifications.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/outage_timeline.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/outages.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/requisitions.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/scheduled_outages.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/snmp_configuration.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/users.adoc
- Migrated ReST documentation from Wiki page to version controlled documentation
- Structured docs for each ReST component
- Documentation for Horizon 16
JIRA: http://issues.opennms.org/browse/NMS-7536
Todo:
> NMS-7536: ReST API documentation

- opennms-doc/guide-admin/src/asciidoc/text/poller/VmwareMonitor.adoc
- Created documentation for VmwareMonitor
JIRA: http://issues.opennms.org/browse/NMS-6711
Todo Review:
> NMS-6711: Documentation VmwareMonitor

- opennms-doc/guide-admin/src/asciidoc/text/poller/VmwareCimMonitor.adoc
- opennms-doc/guide-admin/src/asciidoc/text/poller/VmwareMonitor.adoc
Moved sections one level deeper for both monitors.
> NMS-7597: Fix toc depth for VmwareMonitor and VmwareCimMonitor

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/dashboard/SurveillanceViewAlarmTable.java
> jira/NMS-7542 / release-16.0.0

- opennms-doc/guide-user/src/asciidoc/text/surveillance-view.adoc
Added documentation to describe coloring of the status in the surveillance view.
> NMS-7667: Unclear color behavior in surveillance view

- opennms-webapp/src/main/scss/opennms-theme.scss
http://issues.opennms.org/browse/NMS-7699
I am not sure if this is the right target branch.
Please verify before merging.
> NMS-7699: Set line-height according to size of  mouse-over image.

- opennms-webapp/src/main/webapp/includes/categories-box.jsp
http://issues.opennms.org/browse/NMS-7713
> NMS-7713: Improve links for SLA categories on start page

- opennms-base-assembly/src/main/filtered/etc/database-reports.xml
http://issues.opennms.org/browse/NMS-7703
> NMS-7703-Database-Report-Statement-Correction

- features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java
- features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmsDashlet.java
Fix for jira/NMS-7698 / release-16.0.1
> jira/NMS-7698 for release-16.0.1

- opennms-doc/guide-all/pom.xml
- opennms-doc/guide-concepts/pom.xml
- opennms-doc/guide-concepts/src/asciidoc/index.adoc
- opennms-doc/pom.xml
Created maven module for describing OpenNMS high level architecture and concepts to build a shared common knowledge using OpenNMS.
JIRA: http://issues.opennms.org/browse/NMS-7588
Todo:
> NMS-7588: OpenNMS module for concepts and architecture

- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/datacollection/zertico.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/zertico-graph.properties
- Added MIB support for collections sensors from Zertico devices
- Added graph definition for sensor data and thresholds
JIRA: http://issues.opennms.org/browse/NMS-7131
Todo:
> NMS-7131: MIB support for Zertico devices

- opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
- opennms-base-assembly/src/main/filtered/etc/datacollection/zertico.xml
Changed from old org.opennms.netmgt.collectd.PersistAllSelectorStrategy to new org.opennms.netmgt.collection.support.PersistAllSelectorStrategy for Zertico and Juniper data collection
JIRA: http://issues.opennms.org/browse/NMS-7739
> NMS-7739: Fixed persistenceSelectorStrategy for new configs

- opennms-assemblies/http-remoting/src/test/java/org/opennms/web/HttpRemotingContextIT.java
- opennms-assemblies/pom.xml
Also added required bits to maven to turn on ITs when requested per @deejgregor.
> HttpRemotingContextTest -> HttpRemotingContextIT since it requires a temp DB

- opennms-base-assembly/src/main/filtered/etc/events/NetApp.events.xml
JIRA: http://issues.opennms.org/browse/NMS-5791
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS60/latest
> NMS-5791: New events for NetApp.

- container/karaf/src/main/filtered-resources/etc/custom.properties
- smoke-test/src/test/java/org/opennms/smoketest/AdminPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/OsgiUrlPatternResponseIT.java
* JIRA: http://issues.opennms.org/browse/NMS-7785
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS75
Please DO NOT MERGE, still WIP.
> NMS-7785: org.osgi.service.http is now provided by the system classpath.

- opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
JIRA: http://issues.opennms.org/browse/HZN-367
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS86
> HZN-367: Rationalize juniper j-routers datacollection 

- opennms-base-assembly/src/main/filtered/etc/eventconf.xml
- opennms-base-assembly/src/main/filtered/etc/events/Juniper.screen.events.xml
correct event definition file for the JUNIPER-JS-SCREENING-MIB traps
JIRA: http://issues.opennms.org/browse/NMS-5071
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS74-1
> NMS-5071: Added event definition for Juniper screening SNMP traps.

- opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cassandra21x-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/newts-cassandra21x-graph.properties
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/cassandra21x.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts.adoc
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/JmxDataCollectionConfigResourceIT.java
See issue
*  http://issues.opennms.org/browse/HZN-345 
* http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS69
Please review and merge...
> HZN-345: Define a JMX data collection package for monitoring Cassandra 2.1.x

- opennms-doc/guide-admin/src/asciidoc/text/poller/DiskUsageMonitor.adoc
in DiskUsageMonitor's documentation
JIRA: http://issues.opennms.org/browse/HZN-91
> HZN-91: Added a warning about reserved filesystem blocks 

- opennms-doc/guide-admin/src/asciidoc/text/poller/DNSResolutionMonitor.adoc
- opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/DNSResolutionMonitor.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/DNSResolutionMonitorTest.java
Issue: http://issues.opennms.org/browse/HZN-375.
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS96
This is the same as #329 but against develop.
> HZN-375: Added option to specify nameserver to DnsResolutionMonitor

- opennms-doc/guide-admin/src/asciidoc/text/operation/jmx-config-generator.adoc
Please review and merge!
Issue: http://issues.opennms.org/browse/HZN-376
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS104
> jira/HZN-376: JMX Config Generator Documentation

- features/jmx-config-generator/pom.xml
Please Review and Merge.
* Jira:  http://issues.opennms.org/browse/HZN-432
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS128
> HZN-432: Include commons-io.

- opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc
fixed some typo in the introduction part of the installation guide
> fixed some typo in guide-install

- opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc
Please make sure the URLs are correct: You are using opennms.eu here while you are using opennms.org for RHEL-based systems
> HZN-185: Review fixes for Debian installation guide

- protocols/xml/src/main/java/org/opennms/protocols/json/collector/AbstractJsonCollectionHandler.java
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS174
Issue: http://issues.opennms.org/browse/NMS-7885
> NMS-7885: Ignore missing element errors while collecting data from JSON

- dependencies/jasper/pom.xml
- dependencies/jfreechart/pom.xml
- features/measurements/api/pom.xml
- features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
- integrations/opennms-analytics-filters/pom.xml
- integrations/opennms-jasper-extensions/pom.xml
- integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/RrdLabelUtils.java
- integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/measurement/MeasurementQueryExecutorIT.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-base-assembly/src/main/filtered/etc/report-templates/AvailabilitySummary.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/ResponseTime.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/ResponseTimeCharts.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/ResponseTimeSummary.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/TotalBytesTransferredByInterface.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/95thPercentileTrafficRate_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/DiskUsageForCTXServers_subreport1.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/InterfaceAvailabilityReport_subreport1.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/PeakTraffic_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_Availability_Offenders_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_Availability_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_Response_Offenders_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTime_subreport1.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/TotalBytesTransferredByInterface_subreport1.jrxml
- opennms-doc/guide-admin/src/asciidoc/text/database-reports/database.adoc
- pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportIT.java
* Jira: http://issues.opennms.org/browse/HZN-454
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS164
Please do not merge, still work in progress.
> jira/HZN-454 Update to latest Jasper Reports version (6.1.1)

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/OutageDaoHibernate.java
- opennms-doc/guide-admin/src/asciidoc/text/webui/heatmap/introduction.adoc
Please review and merge
JIRA: http://issues.opennms.org/browse/HZN-464
BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS177
> Fix for HZN-464

- opennms-webapp/src/main/webapp/includes/categories-box.jsp
- smoke-test/src/test/java/org/opennms/smoketest/CategoriesBoxTest.java
Please review and merge:
Jira: http://issues.opennms.org/browse/NMS-7884
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS179
> Fix for NMS-7884

- opennms-doc/guide-admin/src/asciidoc/text/poller/monitors/IcmpMonitor.adoc
see here: http://www.opennms.org/wiki/Thresholding#Added_to_pollerd
I'm not sure if the default value is correct.
> Missing parameter for ICMP poller

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/cassandra21x.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/introduction.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/newts.adoc
Jira: http://issues.opennms.org/browse/HZN-472
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS187
> Document Newts configuration properties

- opennms-base-assembly/src/main/filtered/etc/examples/jvm-datacollection/snmp-graph.properties.d/CassandraBasic0.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties
- protocols/xml/src/main/etc/examples/opennms-mx4j/snmp-graph.properties.d/jmx-mx4j-graph.properties
http://issues.opennms.org/browse/NMS-7820
> NMS-7820: VerticalLabel fix for many graphs

- opennms-base-assembly/src/main/filtered/etc/examples/jvm-datacollection/snmp-graph.properties.d/CassandraBasic0.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties
- protocols/xml/src/main/etc/examples/opennms-mx4j/snmp-graph.properties.d/jmx-mx4j-graph.properties
> Revert "NMS-7820: VerticalLabel fix for many graphs"

- opennms-webapp/src/main/webapp/element/linkednode.jsp
http://issues.opennms.org/browse/NMS-7411
> NMS-7411: Fix for Fonts are too small in link detail page

- opennms-config/src/test/java/org/opennms/netmgt/config/EventTranslatorConfigFactoryTest.java
- opennms-model/src/main/java/org/opennms/netmgt/xml/event/UpdateField.java
Trivially solved by UpdateField implementing Serializable.
> NMS-7024: Fix for Event Translator cant translate events with update-…field data present"

- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/95thPercentileTrafficRate_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/PeakTraffic_subreport.jrxml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/TotalBytesTransferredByInterface_subreport1.jrxml
* JIRA : http://issues.opennms.org/browse/HZN-483
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS200
> HZN-483: Migrate existing reports to use fallback-attribute in case ifHCInOctets or ifHCOutOctets do not exist.

- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/fortinet-fortigate-system-v5.2-graph.properties
The system usage values are megabytes. not percent.
http://issues.opennms.org/browse/NMS-7901
> NMS-7901: Incorrect-Fortinet-Graph-Defintion

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-doc/guide-admin/src/asciidoc/text/webui/heatmap/introduction.adoc
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/HeatMapRestService.java
- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
Fixed mispelled properties in opennms.properties and change the
option 'managedServices' to 'monitoredServices'.
Jira: http://issues.opennms.org/browse/HZN-484
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS201-1
> HZN-484: Heatmap settings

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-doc/guide-admin/src/asciidoc/text/webui/heatmap/introduction.adoc
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/HeatMapRestService.java
- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
Fixed @Produces annotation and code to support also Xml output.
Jira: http://issues.opennms.org/browse/NMS-7930
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS209-2
> NMS-7930: Heat map ReST services just produce JSON output

- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/MBeansHelper.java
* JIRA: http://issues.opennms.org/browse/NMS-7900
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS215
> NMS-7900: Consider = in value part

- opennms-model/src/main/java/org/opennms/netmgt/model/HeatMapDTOCollection.java
- opennms-model/src/main/java/org/opennms/netmgt/model/HeatMapDTOItem.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/HeatMapRestService.java
Added wrapper classes for Xml output.
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS216-1
Jira: http://issues.opennms.org/browse/NMS-7939
> NMS-7939: HeatMap ReST XML output fails

- opennms-webapp/src/main/java/org/opennms/web/svclayer/etable/FixedRowCompact.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/statisticsReports/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/statisticsReports/report.jsp
* JIRA: http://issues.opennms.org/browse/NMS-7897
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS213
> NMS-7897: Statsd PDF export gives class not found exception

- opennms-base-assembly/src/main/filtered/bin/resourcecli
Simplified resourcecli script to avoid clumpsy classpath building.
JIRA: http://issues.opennms.org/browse/HZN-503
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS219
> HZN-503: Fixed ClassNotFound error for resourcecli command

- opennms-doc/guide-install/src/asciidoc/index.adoc
- opennms-doc/guide-install/src/asciidoc/text/r/debian.adoc
- opennms-doc/guide-install/src/asciidoc/text/r/introduction.adoc
- opennms-doc/guide-install/src/asciidoc/text/r/rhel.adoc
Jira: http://issues.opennms.org/browse/HZN-462
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS224
> HZN-462: Document how to install R on RHEL and Debian systems.

- opennms-config-model/src/main/resources/xsds/eventconf.xsd
JIRA: http://issues.opennms.org/browse/HZN-506
> HZN-506: Improved documentation of mevalue in eventconf.xsd

- opennms-webapp/src/main/webapp/admin/index.jsp
JIRA: http://issues.opennms.org/browse/NMS-7404
> NMS-7404: Inconsistent naming in Admin/System Information

- opennms-base-assembly/src/main/filtered/etc/datacollection/akcp.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/akcp-graph.properties
Add sensorProbe threshold metrics to data collection for humidity and temperature. Improve graphing to have all thresholds in temperature and humidity graph definitions.
JIRA: http://issues.opennms.org/browse/NMS-3405
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS202
> NMS-3405: Improve AKCP sensorProbe graph definition

- opennms-webapp/src/main/webapp/admin/index.jsp
Fixed up issue ID in commit message.
> NMS-7407: Inconsistent naming in Admin/System Information

- opennms-base-assembly/src/main/filtered/etc/model-importer.properties
- opennms-base-assembly/src/main/filtered/etc/provisiond-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/reportd-configuration.xml
- opennms-base-assembly/src/main/resources/contrib/qosdaemon/qos_example_configuration/opennms_fault_config/inventory/model-importer.properties
- opennms-config-model/src/main/castor/provisiond-configuration.xsd
- opennms-config-model/src/main/castor/reportd-configuration.xsd
- opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
- opennms-doc/guide-admin/src/asciidoc/text/provisioning/import-handler.adoc
- opennms-provision/opennms-provisiond/src/test/resources/importerServiceTest-provisiond-configuration.xml
- opennms-reporting/src/test/opennms-home/etc/model-importer.properties
- opennms-webapp/src/main/webapp/WEB-INF/flows/report/database/batchReport/cronExpression.jsp
- opennms-webapp/src/test/opennms-home/etc/model-importer.properties
- smoke-test/opennms-home/etc/provisiond-configuration.xml
JIRA: http://issues.opennms.org/browse/NMS-6555
> NMS-6555: Outdated Quartz URL in multiple configuration and docs files

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
JIRA: http://issues.opennms.org/browse/NMS-7945
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS233-1
> NMS-7945: Fix invalid attribute types in cassandra21x collection package.

- features/newts/pom.xml
- features/newts/src/main/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategy.java
- features/newts/src/test/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategyTest.java
- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
JIRA: http://issues.opennms.org/browse/HZN-507
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS231-2
> HZN-507: Improving concurrency model in NewtsFetchStrategy

- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/text/dev-guide.adoc
JIRA http://issues.opennms.org/browse/NMS-7950
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS240
> NMS-7950: Added instruction on how to setup a development system

- features/ticketing/otrs-integration-31/src/main/java/org/opennms/netmgt/ticketer/otrs31/Otrs31TicketerPlugin.java
- features/ticketing/otrs-integration-31/src/test/opennms-home/etc/otrs.properties
- features/ticketing/otrs-integration-common/src/main/java/org/opennms/netmgt/ticketer/otrs/common/DefaultOtrsConfigDao.java
- features/ticketing/otrs-integration/src/test/opennms-home/etc/otrs.properties
- opennms-base-assembly/src/main/filtered/etc/otrs.properties
JIRA: http://issues.opennms.org/browse/HZN-513
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS245
> HZN-513: Added support for ticket types in OTRS Integration plugin

- WHATSNEW.md
Added credits to community member and added major improvements in documentation.
JIRA: http://issues.opennms.org/browse/HZN-508
> HZN-508: Update WHATSNEW with OpenNMS 17 changes since Aug 11

- features/geocoder/google/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/geocoder/nominatim/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/mib-compiler/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/jar/nrtcollector/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/nrtbroker-jms/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/nrtbroker-local/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/nrtcollector/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/protocolcollector/snmp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/protocolcollector/tca/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/nrtg/web/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/survey-client/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/archetypes/archetype-example-operation/src/main/resources/archetype-resources/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.devutils/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.ncs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.netutils/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.ssh/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.sfree/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.simple/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-node-maps/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-snmp-events-and-metrics/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/NMS-7967
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS255
> NMS-7967: Fix wrong xmlns namespace/uri definitions

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeRestServiceIT.java
* JIra: http://issues.opennms.org/browse/NMS-7975
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS266
> NMS-7975: Change status code to 204 instead of 404

- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/AttributesTable.java
* Jira: http://issues.opennms.org/browse/NMS-7964
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS269
> NMS-7964: MBean attribute names are restricted to a specifix max length

- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/ConfirmationDialog.java
- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/DefaultNameProvider.java
- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/MBeansController.java
- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/MBeansView.java
- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/validation/UniqueAttributeNameValidator.java
- features/vaadin-jmxconfiggenerator/src/test/java/org/opennms/features/vaadin/jmxconfiggenerator/ui/mbeans/validation/UniqueAttributeNameValidatorTest.java
* Jira: http://issues.opennms.org/browse/NMS-7977
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS267
> NMS-7977: JMX Configuration Generation misbehavior on validation error

- opennms-doc/guide-development/src/asciidoc/text/rest/heatmap.adoc
Some rephrasements...
JIRA: http://issues.opennms.org/browse/NMS-7929
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS244
> NMS-7929: Document HeatMap ReST services, updated heatmap.adoc

- pom.xml
Jira issue: http://issues.opennms.org/browse/NMS-7614
> NMS-7614: Bump Spring Security Kerberos version to 1.0.1

- opennms-services/src/main/java/org/opennms/netmgt/vacuumd/AutomationProcessor.java
JIRA: http://issues.opennms.org/browse/NMS-8018
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS320/latest
> NMS-8018: Vacuumd sends automation events before transaction is closed

- opennms-doc/guide-admin/src/asciidoc/text/webui/grafana-dashboard-box.adoc
- opennms-webapp/src/main/webapp/includes/grafana-box.jsp
Jira: http://issues.opennms.org/browse/HZN-552
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS317
> HZN-552: Fixed grafana-box.jsp to use the new Grafana API

- core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Starter.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties.d/.readme
- opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/system-properties/introduction.adoc
JIRA: http://issues.opennms.org/browse/NMS-7965
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS252
> NMS-7965: Add support for setting system properties via user supplied .properties files

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/HeatMapIT.java
Jira: http://issues.opennms.org/browse/HZN-555
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS332
> HZN-555: Fixed SQL statement to include all categories

- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
JIRA: http://issues.opennms.org/browse/NMS-7123
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS338
> NMS-7123: Fix copy-paste bug in exposing SNMP4J noGetBulk property

- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/BusinessService.java
- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/OnmsMonitoredServiceHelper.java
- features/bsm/persistence/impl/src/main/resources/changelog.xml
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
- features/bsm/rest/src/main/java/org/opennms/web/rest/v2/BusinessServiceRestService.java
- features/bsm/rest/src/test/java/org/opennms/web/rest/v2/BusinessServiceRestServiceIT.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/BusinessServiceDTO.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/IpServiceDTO.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/JAXBMapAdapter.java
- features/bsm/service/api/src/test/java/org/opennms/netmgt/bsm/service/model/BusinessServiceDTOJaxbTest.java
- features/bsm/service/api/src/test/java/org/opennms/netmgt/bsm/service/model/IpServiceDTOJaxbTest.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoredService.java
This PR includes 2 of the 4 BSM-14 tasks.
BSM-84: Model changes http://issues.opennms.org/browse/BSM-84
BSM-85: Rest interface http://issues.opennms.org/browse/BSM-85
The two other tasks should be based on this PR.
After this PR is done, the results for BSM-61should be merge into BSM-14.
The Bamboo link for this PR:
http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS327
> BSM-14: Configure a Business Service to depend on a set of Alarms

- features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineTest.java
Issue BSM-87: http://issues.opennms.org/browse/BSM-87
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS340
> BSM-87: Included StateMachineTest with explicit reductionkeys.

- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/support/about.jsp
Copyright year updates in web UI
> Happy New Year 2016

- opennms-alarms/api/pom.xml
- opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/NorthboundAlarm.java
- opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/package-info.java
- opennms-alarms/api/src/main/resources/org/opennms/netmgt/alarmd/api/jaxb.properties
- opennms-alarms/api/src/main/resources/xsds/northbound-alarm.xsd
- opennms-alarms/api/src/test/java/org/opennms/netmgt/alarmd/api/NorthboundAlarmTest.java
- opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthBounderWithFiltersTest.java
- opennms-alarms/syslog-northbounder/src/test/resources/syslog-northbounder-config1.xml
JIRA: http://issues.opennms.org/browse/NMS-8068
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS368-3
> NMS-8068: Add support for marshalling NorthboundAlarms to XML

- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/BusinessService.java
- features/bsm/persistence/impl/src/main/resources/changelog.xml
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
BSM-90: Remove IpServices from BusinessServices if the providing Node is deleted.
Jira: http://issues.opennms.org/browse/BSM-90
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS389-1
> BSM-90: Cascade deletion of IpServices to BusinessServices

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/TopologySelector.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/ApplicationTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationSelectionLinkGenerator.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/resources/OSGI-INF/blueprint/blueprint.xml
JIRA: http://issues.opennms.org/browse/BSM-93
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS384
> BSM-93: Allow Applications to be selected in the Topology UI

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/JsmiMibParserTest.java
- features/mib-compiler/src/test/resources/NORTEL-GENERIC-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-NMI-CONFIG-NOTI-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-NMI-CONFORMANCE-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-NMI-GROUPS-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-NMI-NOTIFICATIONS-MIB.txt
- features/mib-compiler/src/test/resources/NORTEL-NMI-TC-MIB.txt
Ran tests locally with success. 
JIRA: http://issues.opennms.org/browse/NMS-7966
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS373-1
> NMS-7966: work around recursive TCs in MIBs.

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdTest.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
* JIRA: http://issues.opennms.org/browse/BSM-88
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS388
Please note that with this PR issue http://issues.opennms.org/browse/BSM-79 is also fixed.
> BSM-88: Implement alarm table polling functionality

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
- features/bsm/rest/src/main/java/org/opennms/web/rest/v2/BusinessServiceRestService.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceManager.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceAdminPageUI.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
- features/bsm/vaadin-adminpage/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/BSM-78
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS410
> BSM-78: Add possibility to reload the Business State Machine

- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/pom.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/test/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainerIT.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/test/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainerTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/test/java/org/opennms/features/topology/plugins/browsers/PageTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8079
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS417
> NMS-8079: Fix cache reloading issues if trying to access container and objects which are not in cache

- opennms-webapp/src/main/webapp/WEB-INF/flows/report/database/batchReport/deliveryOptions.jsp
Fixed typo from _evedntId_proceed to _eventId_proceed.
JIRA: http://issues.opennms.org/browse/NMS-8100
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS436
> NMS-8100: Unable to complete creation of scheduled reports

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/ReductionKeyHelper.java
- features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineIT.java
- opennms-doc/guide-admin/src/asciidoc/text/bsm/introduction.adoc
* JIRA: http://issues.opennms.org/browse/BSM-120
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS445
> BSM-120: Include "interfaceDown" events in status calculation of IP Service Edges

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceSearchCriteriaBuilder.java
- features/vaadin-dashlets/dashlet-bsm/pom.xml
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigHelper.java
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMDashlet.java
- features/vaadin-dashlets/dashlet-bsm/src/test/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigHelperTest.java
* JIRA: http://issues.opennms.org/browse/BSM-127
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS450
> BSM-127: Order by Severity doesn't work on the Ops Board

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithm.java
* JIRA: http://issues.opennms.org/browse/BSM-126
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS451
> BSM-126: Layouts for identical hierarchies aren't draw the same way

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceSearchCriteriaBuilder.java
- features/vaadin-dashlets/dashlet-bsm/pom.xml
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigHelper.java
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigurationWindow.java
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMDashlet.java
- features/vaadin-dashlets/dashlet-bsm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-dashlets/dashlet-bsm/src/test/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigHelperTest.java
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS449
Jira: http://issues.opennms.org/browse/BSM-128
> BSM-128: Add the ability to configure the number of columns in the BSM dashlet

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
JIRA: http://issues.opennms.org/browse/BSM-129
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS453
> BSM-129: Added sorting to lists in BSM admin page dialogs

- features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS454
Jira: http://issues.opennms.org/browse/BSM-131
> BSM-131: BSM Ops Board status elements do not use 100% height if other elements use more than 1 row

- features/bsm/persistence/impl/src/main/java/org/opennms/netmgt/bsm/persistence/impl/BusinessServiceDaoImpl.java
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/browsers/BusinessServicesContainer.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AbstractDaoHibernate.java
* JIRA: http://issues.opennms.org/browse/BSM-104
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS455
> BSM-104: The getItemsForCache method in the BusinessServiceContainer does not work

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
Jira: http://issues.opennms.org/browse/BSM-134
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS461
> BSM-134: Business Service Table does not stay sorted on table refresh

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceManager.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/BusinessServiceHierarchy.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceHierarchyImpl.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceHierarchyUtils.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/LevelAware.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithm.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/AbstractBusinessServiceVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServiceCriteria.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServiceVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServicesTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/IpServiceVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/test/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServiceVertexProviderTest.java
* JIRA: http://issues.opennms.org/browse/BSM-133
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS464
> BSM-133: Hierarchy layout breaks when two different "hierarchies" depend on the same reduction key

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/BusinessService.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceImpl.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
Jira: http://issues.opennms.org/browse/BSM-132
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS462
> BSM-132: Cannot Edit an Edge after creation

- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/WallboardConfigView.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/WallboardOverview.java
Jira: http://issues.opennms.org/browse/NMS-8123
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS467
> NMS-8123: Updating table on addition or removal of Ops-boards

- features/bsm/rest/api/pom.xml
- features/bsm/rest/api/src/assembly/xsds.xml
- features/bsm/rest/api/src/main/xsds/business-service-dto.xsd
- opennms-assemblies/xsds/pom.xml
- opennms-assemblies/xsds/src/assembly/xsds.xml
* JIRA: http://issues.opennms.org/browse/BSM-138
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS470
> BSM-138: Create XSDs for the business service DTOs

- opennms-webapp/src/main/webapp/element/snmpinterface.jsp
> NMS-8084: remove include of no-longer-existent interfaceSTP-box.jsp

- opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
replaces https://github.com/OpenNMS/opennms/pull/586
JIRA: http://issues.opennms.org/browse/NMS-8120
Bamboo: ?
> NMS-8120: Fixed a paragraph in the "Automatic Discovery" provisioning chapter

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/BSM-154
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS481
> BSM-154: Changes in the Topology UI affect all users currently browsing the Topology UI

- core/test-api/xml/src/main/java/org/opennms/core/test/xml/MarshalAndUnmarshalTest.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/functions/reduce/HighestSeverityEntity.java
- features/bsm/persistence/impl/src/main/resources/changelog.xml
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceChildEdgeIT.java
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceEdgeDaoIT.java
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/IPServiceEdgeDaoIT.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/ReduceFunctionType.java
- features/bsm/rest/api/src/main/xsds/business-service-dto.xsd
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceRequestDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/ReduceFunctionDTOMarshalTest.java
- features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/BusinessServiceRestServiceIT.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/functions/reduce/HighestSeverity.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/functions/reduce/HighestSeverityAbove.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/ReduceFunctionMapper.java
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/BambooTestHierarchy.java
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/BsmTestUtils.java
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/ReduceFunctionMapper.java
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/SimpleTestHierarchy.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/test/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServiceSearchProviderIT.java
- opennms-doc/guide-admin/src/asciidoc/text/bsm/bsm-admin.adoc
- opennms-doc/guide-development/src/asciidoc/text/bsm/bsm-development.adoc
The class was renamed to reflect the renaming request as the user output
is equal to the class name.
JIRA: http://issues.opennms.org/browse/BSM-142
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS477
> BSM-142: Renamed MostCritical to HighestSeverity

- opennms-doc/releasenotes/src/asciidoc/releasenotes/changelog-17.adoc
Added release notes for new features developed as epics and stories.
> Update release notes for 17.1.0

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
- features/vaadin-components/core/src/main/java/org/opennms/netmgt/vaadin/core/KeyValueInputDialogWindow.java
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
Jira: http://issues.opennms.org/browse/BSM-145
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS478
> BSM-145: Configure the Business Service attributes using the Admin UI

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
Jira: http://issues.opennms.org/browse/BSM-157
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS492
> BSM-157: Remove Business Service name input field on Admin page

- opennms-webapp/pom.xml
- opennms-webapp/src/main/java/org/opennms/web/controller/bsm/BusinessServicesBoxController.java
- opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
- opennms-webapp/src/main/webapp/WEB-INF/jsp/bsm/summary-box.jsp
- opennms-webapp/src/main/webapp/index.jsp
* JIRA: http://issues.opennms.org/browse/BSM-141
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS498
> BSM-141: Add Business Services with Problems to the start page

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceSearchCriteriaBuilder.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/BusinessService.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceImpl.java
- features/vaadin-dashlets/dashlet-bsm/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/BSMConfigurationWindow.java
JIRA: http://issues.opennms.org/browse/BSM-139
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS501
> BSM-139: Add support for ordering the services by level in the BSM Dashlet

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
* JIRA: http://issues.opennms.org/browse/NMS-5970
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS507
> NMS-5970: Fix missing title in Topology UI

- opennms-base-assembly/src/main/filtered/etc/chart-configuration.xml
Chart Servlet Outages model exception.
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS509
Jira: http://issues.opennms.org/browse/NMS-7936
> Fix for Bug NMS-7936

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/LayoutOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/TopologySelectorOperation.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/BSM-163
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS511
> BSM-163: Allow Graph Provider to define a preferredLayout to use this if available

- opennms-doc/guide-install/src/asciidoc/text/opennms/debian.adoc
- opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc
- opennms-doc/guide-install/src/asciidoc/text/opennms/rhel.adoc
- opennms-doc/guide-install/src/asciidoc/text/opennms/windows.adoc
Set a password to the postgres user and use this account to initialize and change the database schema.
JIRA: http://issues.opennms.org/browse/NMS-8177
> NMS-8177: Fix postgres super user in install guide

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithm.java
* JIRA: http://issues.opennms.org/browse/BSM-165
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS516
> BSM-165: HierarchyLayout does not layout vertices correctly if root element of sub-tree is not shown

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/MergingGraphProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/VEProviderGraphContainer.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/TopologySelectorOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/GCFilterableContainerTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/MergingGraphProviderTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/TopologyComponentTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/VEProviderGraphContainerTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/D3LayoutTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/FRLayoutTest.java
* JIRA: http://issues.opennms.org/browse/BSM-166
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS514
> BSM-166: Fix default graph provider selection

- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/AlarmDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/NodeDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainer.java
* JIRA: http://issues.opennms.org/browse/NMS-8079
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS519
> NMS-8079: The OnmsDaoContainer does not update its cache correctly, leading to a NumberFormatException

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- opennms-alarms/daemon/pom.xml
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
- opennms-alarms/daemon/src/main/resources/META-INF/opennms/applicationContext-alarmd.xml
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmLifecycleEventsIT.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml
- opennms-base-assembly/src/main/filtered/etc/vacuumd-configuration.xml
- opennms-services/src/main/java/org/opennms/netmgt/vacuumd/Vacuumd.java
JIRA: http://issues.opennms.org/browse/NMS-8205
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS526
> NMS-8205: Generate events for alarm lifecyle changes.

- container/branding/pom.xml
- container/jaas-login-module/pom.xml
- features/topology-map/archetypes/archetype-example-operation/src/main/resources/archetype-resources/pom.xml
- features/topology-map/poms/pom.xml
- features/vaadin-jmxconfiggenerator/pom.xml
- opennms-rrd/opennms-rrd-api/pom.xml
- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8208
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS484
> NMS-8208: Upgrade maven-bundle-plugin to v3.0.1

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
JIRA: http://issues.opennms.org/browse/NMS-8211
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS527
> NMS-8211: Add support for retrieving nodes with a filter query.

- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/Derivative.java
- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/DerivativeFactory.java
- features/measurements/impl/src/main/resources/META-INF/services/org.opennms.netmgt.measurements.api.FilterFactory
- features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/filters/impl/DerivativeTest.java
JIRA: http://issues.opennms.org/browse/NMS-8210
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS530-1
> NMS-8210: Add a new Derivative filter to the Measurements API

- opennms-webapp/src/main/webapp/element/node.jsp
JIRA: http://issues.opennms.org/browse/NMS-8182
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS531
> NMS-8182: Add HTTPS Quicklink

- container/karaf/src/main/filtered-resources/etc/custom.properties
Jira: http://issues.opennms.org/browse/BSM-167
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS533
> BSM-167: Fixed BundleException

- opennms-doc/guide-admin/src/asciidoc/text/events.adoc.orig
http://issues.opennms.org/browse/NMS-8218
> NMS-8218: External event source tweaks to admin guide

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-user/src/asciidoc/index.adoc
http://issues.opennms.org/browse/NMS-8219
> NMS-8219: Copyright bump on asciidoc docs

- opennms-config/src/main/java/org/opennms/netmgt/config/ChartConfigFactory.java
Reload Chart configuration instead of Notification configuration.
* JIRA: http://issues.opennms.org/browse/NMS-8215
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS537
> NMS-8215: Reload chart configuration instead of Notifd configuration

- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceRequestDTO.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceResponseDTO.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/ReduceFunctionType.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/edge/AbstractEdgeResponseDTO.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/edge/ChildEdgeRequestDTO.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/edge/ChildEdgeResponseDTO.java
- features/bsm/rest/api/src/main/xsds/business-service-dto.xsd
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceRequestDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/ChildEdgeResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/IpServiceEdgeResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/ReductionKeyEdgeResponseDTOMarshalTest.java
- opennms-doc/guide-development/src/asciidoc/text/bsm/bsm-development.adoc
* JIRA: http://issues.opennms.org/browse/BSM-175
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS549
> BSM-175: Fixed element naming for REST objects

- core/db-install/src/main/java/org/opennms/core/db/install/InstallerDb.java
- features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/BusinessServiceEntity.java
- features/bsm/persistence/impl/src/main/resources/changelog.xml
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
* JIRA: http://issues.opennms.org/browse/BSM-67
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS548
> BSM-67: Enforce uniqe naming of Business Services

- core/spring/pom.xml
- integrations/opennms-jasperstudio-extension/pom.xml
- opennms-base-assembly/pom.xml
- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/TotalBytesTransferredByInterface_subreport1.jrxml
* JIRA: http://issues.opennms.org/browse/NMS-8235
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS552
> NMS-8235: Fix missing dependencies

- dependencies/snmp4j-agent/pom.xml
- dependencies/snmp4j/pom.xml
- pom.xml
http://issues.opennms.org/browse/NMS-8226
Upgrade SNMP4J to 2.4.3 and SNMP4J-Agent to 2.4.2. Thanks to Martin Laercher for the suggestion and testing.
> NMS-8226: Upgrade SNMP4J to version 2.4

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/Constants.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/SearchProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/VEProviderGraphContainer.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/TopologySelectorOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/CategoryHopCriteria.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/CategoryHopCriteriaHistoryOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/SearchBox.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/DeferedNodeLeafVertex.java
* JIRA: http://issues.opennms.org/browse/BSM-189
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS563
> BSM-189: Categories in focus do not work anymore (Category Search)

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/VertexHopGraphProvider.java
* JIRA: http://issues.opennms.org/browse/BSM-190
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS565
> BSM-190: Hiding leaf elements produces Exception

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/shell-commands/src/main/java/org/opennms/netmgt/bsm/karaf/shell/DeleteGeneratedHierarchiesShellCommand.java
- features/bsm/shell-commands/src/main/java/org/opennms/netmgt/bsm/karaf/shell/GenerateHierarchiesShellCommand.java
- features/bsm/shell-commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
JIRA: http://issues.opennms.org/browse/BSM-164
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS568/latest
> BSM-164: Add shell commands for generating and deleting business service hiearchies

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/ReductionKeyVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/test/java/org/opennms/features/topology/plugins/topo/bsm/ReductionKeyVertexTest.java
JIRA: http://issues.opennms.org/browse/BSM-177
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS567/latest
> BSM-177: Alarm Label is too long

- opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/SmtpMonitor.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/SmtpMonitorIT.java
JIRA: http://issues.opennms.org/browse/NMS-7582
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS573/latest
> NMS-7582 Conform to RFC specification for line termination

- features/bsm/persistence/impl/src/main/java/org/opennms/netmgt/bsm/persistence/impl/BusinessServiceDaoImpl.java
- features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
* JIRA: http://issues.opennms.org/browse/BSM-104
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS571
> BSM-104: Fix wrong usage of Criteria.DISTINCT_ROOT_ENTITY

- features/topology-map/org.opennms.features.topology.api/pom.xml
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/browsers/OnmsVaadinContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/AlarmDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/NodeDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainerDatasource.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/test/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainerIT.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/test/java/org/opennms/features/topology/plugins/browsers/OnmsDaoContainerTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationDaoContainer.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/pom.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java
- features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashletFactory.java
- features/vaadin-dashlets/dashlet-alarms/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-node-maps/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-full-assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- smoke-test/src/test/java/org/opennms/smoketest/OsgiUrlPatternResponseIT.java
JIRA: http://issues.opennms.org/browse/BSM-150
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS566/latest
> BSM-150: Fix broken Node Maps

- opennms-base-assembly/src/main/filtered/etc/datacollection/cisco.xml
JIRA: http://issues.opennms.org/browse/NMS-8265
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS582
> NMS-8265: SNMP collection systemDefs for Cisco ASA5525-X, ASA5515-X

- opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
JIRA: http://issues.opennms.org/browse/NMS-8266
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS583
> NMS-8266: SNMP collection systemDefs for Juniper SRX210he2, SRX100h

- opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/Correlator.java
http://issues.opennms.org/browse/NMS-8271
> NMS-8271: Enable correlation engines to register for all events

- opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/Correlator.java
http://issues.opennms.org/browse/NMS-8271
> NMS-8271: Fix unexpected CorrelatorTest test failures

- core/test-api/db/src/main/java/org/opennms/core/test/db/TemporaryDatabaseExecutionListener.java
- features/newts-repository-converter/pom.xml
- features/vaadin-node-maps/src/test/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/ui/controls/search/SearchStateTest.java
- features/vaadin-node-maps/src/test/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/ui/controls/search/TestSchedulerImpl.java
- opennms-alarms/daemon/pom.xml
- opennms-provision/opennms-detector-lineoriented/src/test/java/org/opennms/netmgt/provision/detector/HttpsDetectorTest.java
- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8209
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS587-8
> NMS-8209: Upgrade junit to v4.1.2.

- opennms-webapp/src/main/scss/opennms-theme.scss
Remove bright table color and changed font color from white to black.
* JIRA: http://issues.opennms.org/browse/NMS-8198
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS597
> NMS-8198: Change Provisioning UI unsaved state indication

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/ReductionKeyVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/test/java/org/opennms/features/topology/plugins/topo/bsm/ReductionKeyVertexTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8298
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS601
> NMS-8298: Show ... when reduction key label is cut

- features/vaadin-components/extender-service/src/main/java/org/opennms/vaadin/extender/internal/servlet/VaadinOSGiServlet.java
* JIRA: http://issues.opennms.org/browse/NMS-8168
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS605
> NMS-8168: Overwrite default favicon.ico location to use /opennms/favicon.ico

- features/bsm/rest/impl/src/main/java/org/opennms/web/rest/v2/bsm/BusinessServiceRestService.java
- features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/bsm/BusinessServiceRestServiceIT.java
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
* JIRA: http://issues.opennms.org/browse/NMS-8301
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS614
> NMS-8301: v2 Rest Services are deployed twice to the WEB-INF/lib directory

- core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
This PR has a backport of improvements made in the latest Karaf code to prevent port conflicts during integration tests. It should prevent flapping of these tests. It has been running continuously in Bamboo and hasn't failed yet on a Karaf IT. Cross your fingers.
* JIRA: http://issues.opennms.org/browse/NMS-8305
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS606
> NMS-8305: Added available port checking to KarafTestCase.

- opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/ConfigTester.java
- opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/ConfigTesterDataSource.java
- opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/ConfigTesterFilterDao.java
- opennms-config-tester/src/main/resources/META-INF/opennms/applicationContext-configTester.xml
- opennms-config-tester/src/test/java/org/opennms/netmgt/config/tester/ConfigTesterTest.java
Config Tester Tool doesn't check some of the core configuration files.
I updated the JUnit tests to verify the behavior, but because the JUnit test doesn't verify the loading of the Spring Context, I verified the actual work with a real deployment. Everything seems to be working as expected.
* JIRA: http://issues.opennms.org/browse/NMS-8293
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS619
> NMS-8293: Config Tester Tool doesn't check some of the core configuration files

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/DefaultMapViewManager.java
* JIRA: http://issues.opennms.org/browse/NMS-8313
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS622
This patch should also fix the following issues:
* http://issues.opennms.org/browse/NMS-8299
* http://issues.opennms.org/browse/NMS-8300
* http://issues.opennms.org/browse/NMS-8314
> NMS-8313: Do not modify the bounding box after listener were notified

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/BusinessServiceVertexInfoPanelItem.java
* JIRA: http://issues.opennms.org/browse/NMS-8324
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS617/latest
> NMS-8324: Added friendly name to info panel for BSM IP Services

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/AutoRefreshToggleOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/RedoLayoutOperation.java
* JIRA: http://issues.opennms.org/browse/NMS-8211
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS608
> NMS-8221: Refresh now dirties the graph container

- container/features/src/main/resources/features.xml
- core/test-api/rest/src/main/java/org/opennms/core/test/rest/AbstractSpringJerseyRestTestCase.java
- core/test-api/xml/src/main/java/org/opennms/core/test/xml/JsonTest.java
- core/xml/src/main/java/org/opennms/core/xml/JacksonUtils.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceListDTO.java
- features/bsm/rest/api/src/main/java/org/opennms/web/rest/v2/bsm/model/meta/FunctionsManager.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceListDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceRequestDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/BusinessServiceResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/ChildEdgeResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/IpServiceEdgeResponseDTOMarshalTest.java
- features/bsm/rest/api/src/test/java/org/opennms/web/rest/v2/bsm/model/edge/ReductionKeyEdgeResponseDTOMarshalTest.java
- features/bsm/rest/impl/pom.xml
- features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/bsm/AbstractBusinessServiceRestServiceIT.java
- features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/bsm/BusinessServiceRestServiceJsonIT.java
- features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/bsm/BusinessServiceRestServiceXmlIT.java
- features/bsm/test-util/pom.xml
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/BsmTestUtils.java
- features/discovery/pom.xml
- features/rest-commons/pom.xml
- features/rest-commons/src/main/java/org/opennms/web/rest/api/support/JsonResourceLocationListDeserializationProvider.java
- features/rest-commons/src/main/java/org/opennms/web/rest/api/support/JsonResourceLocationListSerializationProvider.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsOutageTest.java
JIRA: http://issues.opennms.org/browse/NMS-8302
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS613
> NMS-8302: Use the same ObjectMapper as the JacksonJaxbJsonProvider

- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/BroadcastEventProcessor.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/BroadcastEventProcessorTest.java
Issue link:
http://issues.opennms.org/browse/NMS-6549
>  NMS-6549: Eventd does not honor reloadDaemonConfig event

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/SavedHistory.java
* JIRA: http://issues.opennms.org/browse/NMS-8335
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS625
> NMS-8335: Set vertices in focus after applying history operations

- opennms-base-assembly/src/main/filtered/bin/opennms
Jira: http://issues.opennms.org/browse/NMS-8125
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS618-1
> NMS-8125: Enable groovy.use.classvalue=true by default

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceManager.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- features/bsm/vaadin-adminpage/pom.xml
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceRow.java
- features/themes/onms-default-theme/src/main/java/VAADIN/themes/opennms/styles.scss
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
JIRA: http://issues.opennms.org/browse/HZN-708
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS627
Helps improve the usability of the BSM Admin UI by:
* Removing the ID column
* Using a TreeTable instead of a normal table to help visualize the hierarchy
* Adding a link to open a particular service in the Topology UI
* Using searchable combo boxes instead of list selects for adding edges
> HZN-708: BSM Admin UI Enhancements

- core/upgrade/src/main/java/org/opennms/upgrade/implementations/JmxRrdMigratorOffline.java
- core/upgrade/src/test/resources/etc/collectd-configuration.xml
* JIRA: http://issues.opennms.org/browse/NMS-7792
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS642
> NMS-7792: NPE in JmxRrdMigratorOffline

- opennms-services/src/main/java/org/opennms/netmgt/notifd/AbstractSlackCompatibleNotificationStrategy.java
- opennms-services/src/main/java/org/opennms/netmgt/notifd/MattermostNotificationStrategy.java
- opennms-services/src/main/java/org/opennms/netmgt/notifd/SlackNotificationStrategy.java
- opennms-services/src/test/java/org/opennms/netmgt/notifd/MattermostNotificationStrategyIT.java
- opennms-services/src/test/java/org/opennms/netmgt/notifd/MattermostNotificationStrategyTestServlet.java
- opennms-services/src/test/java/org/opennms/netmgt/notifd/SlackNotificationStrategyIT.java
- opennms-services/src/test/resources/MattermostNotificationStrategyTest/WEB-INF/web.xml
* JIRA: http://issues.opennms.org/browse/NMS-8346
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS647
> NMS-8346: Add Mattermost and Slack notification strategies

- features/ticketing/tsrm-integration/src/main/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPlugin.java
- features/ticketing/tsrm-integration/src/test/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPluginTest.java
- opennms-doc/guide-admin/src/asciidoc/text/ticketing/tsrm.adoc
Add Summary to Description Mapping 
* JIRA: http://issues.opennms.org/browse/HZN-645
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS655-1
> HZN-645 Add description mapping

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/functions/reduce/HighestSeverityAbove.java
- features/bsm/service/api/src/test/java/org/opennms/netmgt/bsm/service/model/functions/reduce/HighestSeverityAboveTest.java
- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/HudDisplayState.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/HudDisplay.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/BusinessServiceVertexInfoPanelItem.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/SimulationModeReductionKeyInfoPanelItem.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/operations/AbstractAnalysisOperation.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/operations/ImpactAnalysisOperation.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/operations/RootCauseAnalysisOperation.java
- integration-tests/config/src/test/java/org/opennms/netmgt/config/WillItUnmarshalIT.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/AlarmData.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/descriptors/AlarmDataDescriptor.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/descriptors/UpdateFieldDescriptor.java
- opennms-doc/guide-admin/src/asciidoc/text/bsm/bsm-admin.adoc
- opennms-model/src/main/castor/event.xsd
This PR addresses a number of outstanding issues related to BSM:
- [HZN-713](http://issues.opennms.org/browse/HZN-713)
- [HZN-711](http://issues.opennms.org/browse/HZN-711)
- [HZN-666](http://issues.opennms.org/browse/HZN-666)
- [NMS-8330](http://issues.opennms.org/browse/NMS-8330)
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS644
> A bucket of fixes for BSM

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
* JIRA: http://issues.opennms.org/browse/NMS-8371
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS656
> NMS-8371: Fix info panel not updated on (auto) refresh

- opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
Incorrect documentation for org.opennms.newts.query.heartbeat
* JIRA: http://issues.opennms.org/browse/NMS-8361
> NMS-8361: Incorrect documentation for org.opennms.newts.query.heartbeat

- features/newts/src/main/java/org/opennms/netmgt/newts/NewtsWriter.java
Add metric counter for drop counts when the ring buffer is full
* JIRA: http://issues.opennms.org/browse/NMS-8365
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS668-1
> NMS-8365: Add metric counter for drop counts when the ring buffer is full

- features/ticketing/tsrm-integration/src/main/java/org/opennms/netmgt/ticketer/tsrm/TsrmConstants.java
- features/ticketing/tsrm-integration/src/main/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPlugin.java
- features/ticketing/tsrm-integration/src/main/resources/SHSIMPINC.xsd
- features/ticketing/tsrm-integration/src/test/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPluginTest.java
- opennms-doc/guide-admin/src/asciidoc/text/ticketing/tsrm.adoc
Add more fields to TSRM Ticketing Incident
* JIRA: http://issues.opennms.org/browse/hzn-645
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS670-2
> HZN-645:  TSRM Ticketing Add more fields 

- opennms-webapp/src/main/webapp/admin/ng-requisitions/.jshintrc
- opennms-webapp/src/main/webapp/admin/ng-requisitions/Gruntfile.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Detector.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/ForeignSource.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Node.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Policy.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/QuickAddNode.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisition.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisitions.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/directives/requisitionConstraints.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/model/QuickNode.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/model/Requisition.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/model/RequisitionInterface.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/model/RequisitionNode.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/model/RequisitionsData.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/services/Requisitions.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/package.json
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/controllers/Asset.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/controllers/Detector.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/controllers/Policy.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/model/Requisition.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/model/RequisitionNode.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/test/spec/services/Requisitions.js
Applying some organizational changes on the Requisitions UI (Grunt, JSHint, Dist)
* JIRA: http://issues.opennms.org/browse/NMS-8377
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS673
**IMPORTANT: There are no significant changes on the JavaScript files or the HTML Templates of the Angular Code for Requisitions. Only the changes required to make JSHint happy have been applied.**
> NMS-8377: Applying some organizational changes on the Requisitions UI (Grunt, JSHint, Dist)

- opennms-base-assembly/src/main/filtered/etc/log4j2.xml
JIRA: http://issues.opennms.org/browse/NMS-8379
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS681
> NMS-8379: Sluggish performance with Cassandra driver

- core/daemon/pom.xml
- core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml
- features/discovery/blueprint-discovery.xml
- features/discovery/src/main/resources/META-INF/opennms/applicationContext-discovery.xml
- features/discovery/src/test/java/org/opennms/netmgt/discovery/DiscoveryBlueprintIT.java
- features/events/syslog/blueprint-syslog-handler-default.xml
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdHandlerDefaultIT.java
Add base activemq component for OpenNMS
* JIRA: http://issues.opennms.org/browse/hzn-720
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS649-12
> HZN-720: Add common activemq component

- opennms-webapp/src/main/webapp/WEB-INF/web.xml
Cleanup introduced white spaces on new lines and before line breaks which makes diffs harder during updates.
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS693
> Cleanup spaces and tabs in new lines to reduce merge conflicts

- opennms-config/src/main/java/org/opennms/netmgt/config/NotificationManager.java
* JIRA: http://issues.opennms.org/browse/NMS-8395
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS695
> NMS-8395: Logging improvements to Notifd

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/SimpleSearchProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServiceSearchProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLSearchProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/internal/GraphMLTopologyFactory.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
JIRA: http://issues.opennms.org/browse/HZN-735
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS690
> HZN-735: Add a SearchProvider for the GraphMLTopologyProvider

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServicesStatusProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/browsers/BusinessServicesTableCellStyleGenerator.java
- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/BSMTopologyIT.java
JIRA: http://issues.opennms.org/browse/HZN-732
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS679
> HZN-732: Add smoke tests for the Topology UI

- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties
There are errors on the graph definitions for OpenNMS JMX statistics
* JIRA: http://issues.opennms.org/browse/NMS-8401
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS698-1/
> NMS-8401: There are errors on the graph definitions for OpenNMS JMX statistics

- opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
Fixed to follow one line per sentence convention to identify easily changes with line diffs introduced by using git.
> NMS-8403: Formatting fixes

- opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
Also tweaked one example in Measurements API section to cut confusion.
* JIRA: http://issues.opennms.org/browse/NMS-8403
> NMS-8403: Document styles of identifying nodes in resource IDs

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpStrategy.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalkCallback.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalker.java
- core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpStrategy.java
- core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategy.java
- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
- core/snmp/integration-tests/pom.xml
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpTableResultTest.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpUtilsIT.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategyTest.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategyIT.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4jTrapReceiverIT.java
JIRA: http://issues.opennms.org/browse/HZN-745
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS706
> HZN-745: Add support for asynchronous SNMP requests in SnmpUtils

- opennms-doc/guide-admin/src/asciidoc/text/bsm/business-service-definition.adoc
Just a small typo in business-service-definition.adoc
Cyrille
> typo in business-service-definition.adoc

- opennms-doc/guide-admin/src/asciidoc/text/bsm/map-functions.adoc
> small typo in map-functions.adoc

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpInstIdXmlAdapter.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpObjId.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpResult.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpValueXmlAdapter.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolver.java
- core/snmp/integration-tests/pom.xml
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpResultXmlTest.java
- core/test-api/xml/src/main/java/org/opennms/core/test/xml/XmlTest.java
JIRA: http://issues.opennms.org/browse/HZN-746
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS707
> HZN-746: Marshal/Unmarshal SnmpResult objects to/from XML.

- features/ticketing/tsrm-integration/src/main/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPlugin.java
tsrm: Add check for null fields when saving/updating ticket.
* JIRA: http://issues.opennms.org/browse/hgtm-23
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS712-3
> tsrm: check for null fields

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/VEProviderGraphContainer.java
* JIRA: http://issues.opennms.org/browse/HZN-759
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS720
> HZN-759: Switching to a layer which defines a non existing preferredLayout throws NPE

- features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
JIRA: http://issues.opennms.org/browse/NMS-8423
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS726
> NMS-8423: Add business service attributes to the generated events.

- features/topology-map/themes/default-theme/src/main/java/VAADIN/themes/topo_default/styles.css
* JIRA: http://issues.opennms.org/browse/NMS-8433
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS730
> NMS-8433: Add styling for icon-remove and icon-location-arrow

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLMetaTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/model/GraphMLReader.java
JIRA: http://issues.opennms.org/browse/HZN-778
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS734
> HZN-778: Allow duplicate node ids or edge ids in a GraphML document

- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
JIRA: http://issues.opennms.org/browse/NMS-8429
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS733-1
> NMS-8429: Add a new control to open graphs in their own window.

- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8392
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS742-1
> NMS-8392: Upgrade slf4j to 1.7.21 and upgrade log4j2 to 2.5

- features/newts-repository-converter/src/main/java/org/opennms/features/newts/converter/NewtsConverter.java
- features/newts-repository-converter/src/test/java/org/opennms/features/newts/converter/NewtsConverterTest.java
JIRA: http://issues.opennms.org/browse/NMS-8363
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS750
> NMS-8363: Newts converter: Skip values that fall outside the supported ranges.

- features/newts/src/main/java/org/opennms/netmgt/dao/support/NewtsResourceStorageDao.java
- features/newts/src/main/java/org/opennms/netmgt/newts/NewtsWriter.java
- features/newts/src/main/java/org/opennms/netmgt/newts/SampleBatchEvent.java
JIRA: http://issues.opennms.org/browse/NMS-8437
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS745
> NMS-8437: Use the NewtsWriter to persist string attributes

- features/newts/pom.xml
- features/newts/src/main/java/org/opennms/netmgt/newts/NewtsWriter.java
JIRA: http://issues.opennms.org/browse/NMS-8430
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS743
> NMS-8430: Fixed issue where the number of ring buffer entries exceeds the capacity

- container/features/pom.xml
- container/features/src/main/resources/features.xml
- core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml
- features/activemq/component/pom.xml
- features/activemq/component/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/activemq/pom.xml
- features/events/syslog/blueprint-syslog-handler-default.xml
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdHandlerDefaultIT.java
- features/events/traps/blueprint-trapd-handler-default.xml
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerDefaultIT.java
activemq component to be used by osgi services.
* JIRA: http://issues.opennms.org/browse/nms-8400
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS746/
> NMS-8400: add common activemq component

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
* JIRA: http://issues.opennms.org/browse/NMS-8450
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS754
> NMS-8450: Use getRequestURI() instead of getRequestURL()

- features/activemq/component/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/nms-8400
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS746
> NMS-8400: Modify Broker URL

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/FocusStrategy.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/FocusStrategyImplementation.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/VertexHopGraphProvider.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/GraphProvider.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/SimpleGraphProvider.java
- features/topology-map/org.opennms.features.topology.api/src/test/java/org/opennms/features/topology/api/support/FocusStrategyTest.java
- features/topology-map/org.opennms.features.topology.api/src/test/java/org/opennms/features/topology/api/topo/AbstractTopologyProviderTest.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/MergingGraphProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/VEProviderGraphContainer.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/NoContentAvailableWindow.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/GCFilterableContainerTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/TestTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/ApplicationTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/BusinessServicesTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/AbstractLinkdTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/NodeACLVertexProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.sfree/src/main/java/org/opennms/features/topology/plugins/topo/sfree/internal/SFreeTopologyProvider.java
- smoke-test/src/test/java/org/opennms/smoketest/FocusedVertexTest.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
- smoke-test/src/test/resources/topology/graphml/test-topology.xml
* JIRA: http://issues.opennms.org/browse/HZN-785
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS759
> HZN-785: Navigating to the "regions" layer should show all of the regions by default

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/icons/IconResetOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/icons/IconSelectionOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IconRepositoryManager.java
* JIRA: http://issues.opennms.org/browse/HZN-736
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS761
> HZN-736: Prevent icon manipulation for unknown icon repositories

- container/features/src/main/resources/features.xml
- core/db/pom.xml
- core/db/src/main/java/org/opennms/core/db/C3P0ConnectionFactory.java
- core/db/src/main/java/org/opennms/core/db/XADataSourceFactory.java
- core/schema/pom.xml
- core/test-api/db/pom.xml
- opennms-base-assembly/pom.xml
- opennms-base-assembly/src/main/filtered/etc/opennms-datasources.xml
- opennms-dao/pom.xml
- pom.xml
Upgrade PostgreSQL Driver and C3P0
* JIRA: http://issues.opennms.org/browse/NMS-8438
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS748
> NMS-8438: Upgrade PostgreSQL Driver and C3P0

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/SearchBox.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/pom.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLSearchProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLSearchProviderTest.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
* JIRA: http://issues.opennms.org/browse/HZN-788
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS758
> HZN-788: Enhance the GraphMLSearchProvider to search all  layers

- container/features/pom.xml
- container/features/src/main/resources/features.xml
- core/db/pom.xml
- core/db/src/main/java/org/opennms/core/db/HikariCPConnectionFactory.java
- core/db/src/test/java/org/opennms/core/db/HikariCPConnectionFactoryIT.java
- opennms-base-assembly/src/main/filtered/etc/opennms-datasources.xml
- pom.xml
Implement a Datasource Factory based on Hikari CP
* JIRA: http://issues.opennms.org/browse/NMS-8455
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS763
Tested locally, and it is working as expected.
> NMS-8455: Implement a Datasource Factory based on Hikari CP

- core/schema/src/main/liquibase/19.0.0/changelog.xml
- features/minion/dominion/src/main/java/org/opennms/features/minion/dominion/MinionListener.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoringSystem.java
* JIRA: http://issues.opennms.org/browse/hzn-719
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS782-1
> HZN-719: Remove lastCheckedIn from minion

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/VertexHopGraphProvider.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/AbstractTopologyProvider.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/GraphProvider.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/SimpleGraphProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/MergingGraphProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/VEProviderGraphContainer.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/NavigateToOperation.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLProperties.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLMetaTopologyProviderTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/resources/test-graph.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/NodeACLVertexProvider.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
- smoke-test/src/test/resources/topology/graphml/test-topology.xml
JIRA: http://issues.opennms.org/browse/HZN-786
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS780/latest
> HZN-786: Add support for specifying the default SZL via GraphML

- opennms-base-assembly/src/main/filtered/etc/org.opennms.features.topology.app.icons.list
- opennms-webapp/src/main/webapp/svg/atlas_icons.svg
JIRA: http://issues.opennms.org/browse/HZN-724
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS778
> HZN-724: Add topology icons for geographical areas and microwave links.

- opennms-webapp/src/main/webapp/graph/nrtg.jsp
* JIRA: http://issues.opennms.org/browse/NMS-8477
> NMS-8477: NRT graph interval should default to > 1s

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
Trouble ticket link template in opennms.properties accidentally filtered
* JIRA: http://issues.opennms.org/browse/NMS-8256
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS803
> NMS-8256: Trouble ticket link template in opennms.properties accidentally filtered

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
* JIRA: http://issues.opennms.org/browse/HZN-757
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS807
> HZN-757: Show node/alarm data in browsers tab if available

- features/ticketing/tsrm-integration/src/main/resources/SHSIMPINC.xsd
Provide more suitable default XSD for TSRM integration
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS818
> Update default XSD for TSRM integration

- features/events/traps/blueprint-trapd-handler-default.xml
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapNotificationHandlerDefaultImpl.java
- features/events/traps/src/main/resources/META-INF/opennms/applicationContext-trapDaemon.xml
This should fix the duplicated varbinds when parsing traps.
* JIRA: http://issues.opennms.org/browse/NMS-8508
* Bamboo: TBD
> NMS-8508: Use a new EventCreator for each trap message

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/GraphPainter.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/GWTVertex.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/SharedVertex.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/VTopologyComponent.java
- features/topology-map/themes/default-theme/src/main/java/VAADIN/themes/topo_default/styles.css
- opennms-webapp/src/main/webapp/svg/atlas_icons.svg
- opennms-webapp/src/main/webapp/svg/legacy_icons.svg
- opennms-webapp/src/main/webapp/svg/opennms_icons.svg
- opennms-webapp/src/main/webapp/svg/vmware_icons.svg
* JIRA: http://issues.opennms.org/browse/HZN-823
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS824
> HZN-823: Show indicator on vertex if a "Navigate To" target exist

- features/ticketing/tsrm-integration/src/main/java/org/opennms/netmgt/ticketer/tsrm/TsrmTicketerPlugin.java
* JIRA: http://issues.opennms.org/browse/nms-8520
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS819
> NMS-8520: Add changeDate for updating incident

- features/graphml/src/main/java/org/opennms/features/graphml/model/GraphMLReader.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/DefaultStatus.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/pom.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLVertexStatusProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/internal/AlarmSummaryWrapper.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/internal/GraphMLMetaTopologyFactory.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLVertexStatusProviderTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/resources/test-graph.xml
* JIRA: http://issues.opennms.org/browse/HZN-826
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS831
> HZN-826: Implement a VertexStatusProvider for the GraphMLTopologyProvider

- core/profiler/src/main/java/org/opennms/core/profiler/ProfilerAspect.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/model/graph/internal/GraphAlgorithms.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceContainer.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceRow.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceTreeTable.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/BusinessServiceVertexStatusInfoPanelItem.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/operations/ImpactAnalysisOperation.java
* JIRA: http://issues.opennms.org/browse/NMS-8501
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS827
@indigo423 I assigned the issue to you, please verify that this fixes the problems described in http://issues.opennms.org/browse/NMS-8501
> NMS-8501: Cancel dialog is slow and Topology Map crashes if vertex has many edges (20+)

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/jvm-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/JmxDataCollectionConfigResourceIT.java
JIRA: http://issues.opennms.org/browse/NMS-8495
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS792
> NMS-8495: Improve built-in Newts graphs for easier diagnostics

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/BusinessServiceVertexInfoPanelItem.java
* JIRA: http://issues.opennms.org/browse/NMS-8541
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS841
> NMS-8541: Consider blank friendly names as not set

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/VTopologyComponent.java
* JIRA: http://issues.opennms.org/browse/NMS-8588
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS842
> NMS-8588: Only send physical bounds if changed.

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/WidgetManager.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/MapWidgetComponent.java
- features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapsApplication.java
- features/vaadin-node-maps/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/NMS-8589
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS845
> NMS-8589: Fix Memory Leak and Thread Leak for TopologyUI and NodeMapsApplication

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: http://issues.opennms.org/browse/NMS-8474
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS840
All info pannel providers are wrapped in a single transaction to ensure
consistent values shown in all pannels.
> NMS-8474: Run info pannels in single transaction

- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Value.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/processor/EventExpanderTest.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Parameter.java
- opennms-config-model/src/main/resources/xsds/eventconf.xsd
Make custom event parameters expandable.
* JIRA: http://issues.opennms.org/browse/NMS-8590
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS849
> NMS-8590:  Make custom event parameters expandable.

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/GridLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/GridLayoutOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/GridLayoutAlgorithmTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLProperties.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLVertex.java
- opennms-doc/guide-development/src/asciidoc/text/topology/graphml.adoc
JIRA: http://issues.opennms.org/browse/HZN-834
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS846
> HZN-834: Add a new "Grid Layout"

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/RemoveFocusOtherVerticesOperation.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS847/latest
There's no JIRA issue for this, but I found this particular useful when trying to isolate a vertex when many vertices were already in focus.
> Add a new command that removes all of the _other_ vertices from focus.

- integrations/opennms-vmware/pom.xml
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/vmware/VmwareViJavaAccessTest.java
The original PR https://github.com/OpenNMS/opennms/pull/686 was opened against `develop` but should be merged to `foundation-2016` instead. 
* JIRA: http://issues.opennms.org/browse/NMS-8187
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS853
> NMS-8187: VMware-ManagedEntity does not work with VMware 6

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
* JIRA: http://issues.opennms.org/browse/NMS-8370
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS848
> NMS-8370: Re-Attach BusinessServiceEntities before updating

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/graphml/GraphmlRepository.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/graphml/GraphmlRepositoryImpl.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/GraphMLRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/graphml/GraphmlRepositoryImplTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8481
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS854
> NMS-8481: GraphMLRestService now checks for file existence

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/SaveOrUpdateOperation.java
* JIRA: http://issues.opennms.org/browse/NMS-8593
> NMS-8593: Requisitioned IP interfaces never have ipHostName set

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/GraphPainter.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyComponent.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/TopologyViewImpl.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/VTopologyComponent.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/d3/D3.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/d3/D3Events.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/handler/MarqueeSelectHandler.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/handler/PanHandler.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/view/TopologyView.java
This pull request contains changes for jira issues:
* http://issues.opennms.org/browse/NMS-8331 and 
* http://issues.opennms.org/browse/NMS-8332
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS855
> NMS-8331/NMS-8332: Fix vertex selection behaviour

- opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc
Hello,
I don't think this PR deserves a JIRA issue: It just fixes 2 typo in the doc
* JIRA: http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}
> Fixed 2 typos in the measurement ReST API doc

- container/features/src/main/resources/features.xml
- opennms-icmp/opennms-icmp-api/pom.xml
* JIRA: http://issues.opennms.org/browse/hzn-821
> hzn-821:  Fix ICMP detector loading on minion side

- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/AbstractJsr160Detector.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/Jsr160DetectorFactory.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/MX4JDetectorFactory.java
- opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/JBossDetectorTest.java
- opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/Jsr160DetectorTest.java
- opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/MX4JDetectorTest.java
- opennms-provision/opennms-detector-jmx/src/test/resources/test-jmx-config.xml
- opennms-provision/opennms-detector-jmx/src/test/resources/test-spring-jmxconfig.xml
- opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/SnmpDetectorFactory.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/BgpSessionDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/CiscoIpSlaDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/DiskUsageDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/HostResourceSWRunDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/OmsaStorageDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/OpenManageChassisDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/PercDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/SnmpDetectorTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/Win32ServiceDetectorTest.java
- opennms-provision/opennms-detectorclient-common/src/main/java/org/opennms/netmgt/provision/detector/common/DetectorRequestBuilderImpl.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/AbstractServiceDetectorFactory.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/ServiceDetectorFactory.java
* JIRA: http://issues.opennms.org/browse/hzn-838
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS867/latest
> hzn-838: Add runtimeAttribute support for Jsr160detector

- container/features/src/main/resources/features-minion.xml
- container/features/src/main/resources/features.xml
- features/events/syslog/blueprint-syslog-handler-kafka-default.xml
- features/events/syslog/blueprint-syslog-handler-kafka.xml
- features/events/syslog/pom.xml
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogHandlerKafkaDefaultIT.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdHandlerKafkaIT.java
- pom.xml
* JIRA: http://issues.opennms.org/browse/HZN-742
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS873
> HZN-742: Added blueprints and tests for Syslogd Kafka handler and listener

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyComponent.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/TopologyComponentConnector.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/TopologyComponentState.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/VTopologyComponent.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/InfoPanel.java
- features/topology-map/themes/default-theme/src/main/java/VAADIN/themes/topo_default/styles.css
* JIRA: http://issues.opennms.org/browse/NMS-8592
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS858
Please note: This also fixes issue http://issues.opennms.org/browse/NMS-8297
> NMS-8592: Topology UI refreshes many times when performing various actions

- features/topology-map/features/runtime-base/pom.xml
- features/topology-map/org.opennms.features.topology.app/pom.xml
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/InfoPanel.java
- features/vaadin-components/graph/src/main/java/org/opennms/features/vaadin/components/graph/InlineGraphContainer.java
- features/vaadin-components/graph/src/main/java/org/opennms/features/vaadin/components/graph/InlineGraphContainerState.java
- features/vaadin-components/graph/src/main/resources/org/opennms/features/vaadin/components/graph/graphcontainer-connector.js
- opennms-doc/guide-development/src/asciidoc/text/topology/infopanel.adoc
* JIRA: http://issues.opennms.org/browse/HZN-755
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS866
> HZN-755: Add backshift support to custom info panel

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
Reverts PR OpenNMS/opennms#907
* JIRA: http://issues.opennms.org/browse/NMS-8370
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS878
> Revert "NMS-8370: Re-Attach BusinessServiceEntities before updating"

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java
* JIRA: http://issues.opennms.org/browse/NMS-8421
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS877
> NMS-8421: Check for positive number

- features/discovery/src/main/java/org/opennms/netmgt/discovery/Discovery.java
- features/discovery/src/main/java/org/opennms/netmgt/discovery/IpAddressFilter.java
- features/discovery/src/main/java/org/opennms/netmgt/discovery/UnmanagedInterfaceFilter.java
- features/discovery/src/main/java/org/opennms/netmgt/discovery/actors/RangeChunker.java
- features/discovery/src/main/resources/META-INF/opennms/applicationContext-discovery.xml
- features/discovery/src/test/java/org/opennms/netmgt/discovery/UnmanagedInterfaceFilterIT.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/NodeDaoIT.java
We need to handle overlapping address ranges in different network locations by making the Discovery IP address filter location-aware.
* JIRA: http://issues.opennms.org/browse/HZN-833
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS885
> HZN-833: Changed IP address filter in Discovery to be location-aware

- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkdServiceImpl.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/Node.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscovery.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryCdp.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryIpNetToMedia.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryIsis.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryLldp.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryOspf.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CdpCacheTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CdpInterfacePortNameGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/Dot1dBasePortIfIndexGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocPortGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpRemTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIfTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIpAddrTableGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/SnmpGetter.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdSnmpIT.java
NMS-8624: Make enlinkd location aware
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS904-3
> NMS-8624: Make enlinkd location aware

- container/karaf/src/main/filtered-resources/features/features.xml
- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8618
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS799
> NMS-8618: Upgrade Mina to 2.0.13.

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/daemon-config-files/notifd.adoc
Describe which configuration files are related to Notifd and if changes require restart, reload or get immediately applied.
* JIRA: http://issues.opennms.org/browse/NMS-8551
* Bamboo:
> NMS-8551: Notifd configuration file

- smoke-test/src/main/java/org/opennms/smoketest/utils/RestClient.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsCommandTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsOnMinionTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/ProvisionTest.java
* JIRA: http://issues.opennms.org/browse/hzn-838
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS867-SMOKE-14
> hzn-838: Add smoke tests for provision on minion

- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsCommandTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsOnMinionTest.java
* JIRA: http://issues.opennms.org/browse/hzn-838
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS867-SMOKE-16
> hzn-838: Update tests

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AssetSuggestionsRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/AssetSuggestionsRestServiceIT.java
Create ReST end-point for assets suggestions
* JIRA: http://issues.opennms.org/browse/NMS-8649
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS908
> NMS-8649: Create ReST end-point for assets suggestions

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/KscRestService.java
- opennms-webapp-rest/src/test/resources/v1/ksc.json
Normalize the KSC ReST end point to show consistent content in XML an JSON
* JIRA: http://issues.opennms.org/browse/NMS-8648
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS906-2
> NMS-8648: Normalize the KSC ReST end point to show consistent content in XML an JSON

- features/discovery/src/main/java/org/opennms/netmgt/discovery/actors/EventWriter.java
- features/discovery/src/test/java/org/opennms/netmgt/discovery/DiscoveryBlueprintIT.java
- features/discovery/src/test/java/org/opennms/netmgt/discovery/DiscoveryIntegrationIT.java
- features/discovery/src/test/java/org/opennms/netmgt/discovery/helper/LocationAwareTestRouteBuilder.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NewSuspectScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
JIRA: http://issues.opennms.org/browse/HZN-613
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS924
> HZN-613: Make Discovery consider locations other than localhost

- core/daemon/src/main/java/org/opennms/netmgt/daemon/ConditionalActiveMQContext.java
- core/daemon/src/main/resources/META-INF/opennms/applicationContext-activemq.xml
- core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml
- core/daemon/src/test/java/org/opennms/netmgt/daemon/ConditionalActiveMQContextTest.java
- features/activemq/component/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
JIRA: http://issues.opennms.org/browse/HZN-860
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS927
> HZN-860: Allow the embedded ActiveMQ broker to be disabled

- core/camel/src/main/java/org/opennms/core/camel/JmsQueueNameFactory.java
- core/lib/src/main/java/org/opennms/core/utils/SystemInfoUtils.java
JIRA: http://issues.opennms.org/browse/HZN-861
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS928
> HZN-861: Update the queue name format to support multliple OpenNMS instances

- dependencies/drools/pom.xml
- features/ncs/ncs-drools/src/main/opennms-home/etc/drools-engine.d/ncs/dependencyLoadingRules.drl
- features/ncs/ncs-drools/src/main/opennms-home/etc/drools-engine.d/ncs/eventMappingRules.drl
- features/ncs/ncs-drools/src/main/opennms-home/etc/drools-engine.d/ncs/impactPropagationRules.drl
- features/ncs/ncs-drools/src/test/java/org/opennms/netmgt/correlation/ncs/CorrelationRulesITCase.java
- features/ncs/ncs-drools/src/test/java/org/opennms/netmgt/correlation/ncs/DependencyLoadingRulesIT.java
- features/ncs/ncs-drools/src/test/java/org/opennms/netmgt/correlation/ncs/DependencyRulesIT.java
- features/ncs/ncs-drools/src/test/java/org/opennms/netmgt/correlation/ncs/EventMappingRulesIT.java
- features/ncs/ncs-drools/src/test/java/org/opennms/netmgt/correlation/ncs/ImpactProgagationRulesIT.java
- features/ticketing/drools-integration/src/main/java/org/opennms/netmgt/ticketd/DroolsTicketerConfigDao.java
- features/ticketing/drools-integration/src/main/java/org/opennms/netmgt/ticketd/DroolsTicketerServiceLayer.java
- opennms-correlation/drools-correlation-engine/pom.xml
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/CorrelationExample.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/CorrelationRulesTestCase.java
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/FusionRulesTest.java
- opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/AbstractCorrelationEngine.java
- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8676
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS932
> NMS-8676: Upgrade Drools to 6.4.0.Final (from 6.0.1.Final)

- dependencies/jasper/pom.xml
- features/reporting/jasper-reports-compiler/pom.xml
- features/reporting/jasper-reports-compiler/src/main/java/org/opennms/reporting/jasperreports/compiler/CustomJRJdtCompiler.java
- features/reporting/jasper-reports/pom.xml
- features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/DefaultParameterFilter.java
- features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
- features/reporting/pom.xml
- opennms-base-assembly/pom.xml
- pom.xml
JIRA: http://issues.opennms.org/browse/NMS-8677
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS933-2
> NMS-8677: Upgrade JasperReports to 6.3.0.

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/KscRestService.java
Reload KSC Configuration through the ReST API
* JIRA: http://issues.opennms.org/browse/NMS-8701
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS950
This is required for NMS-8647 (which is almost done).
> NMS-8701: Reload KSC Configuration through the ReST API

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/service/DefaultSurveillanceViewService.java
* JIRA: http://issues.opennms.org/browse/NMS-8705
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS953
> NMS-8705: Fixed negative availability bug in dashboard

- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/GenericJMXDetectorFactory.java
* JIRA: http://issues.opennms.org/browse/NMS-8709
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS956
> NMS-8709: Add null check for JMX agent

- opennms-web-api/pom.xml
- opennms-web-api/src/main/java/org/opennms/web/servlet/ServletInitializer.java
- opennms-web-api/src/test/java/org/opennms/web/servlet/ServletInitializerTest.java
JIRA: http://issues.opennms.org/browse/NMS-8406
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS954/latest
> NMS-8406: Don't override existing system properties when initializing the webapp.

- opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
Just removed a character from guide-admin
> small typo in guide-admin doc 

- opennms-webapp/src/main/java/org/opennms/web/outage/OutageUtil.java
- opennms-webapp/src/main/java/org/opennms/web/outage/filter/AssetFilter.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/siteStatus.jsp
View current Site outages does not filter for "building"
* JIRA: http://issues.opennms.org/browse/NMS-8702
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS948
Note: the solution should be similar for Meridian 2015, but I'll cherry-pick it manually after merging this PR.
> NMS-8702: View current Site outages does not filter for "building"

- features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/ui/dashboard/DashboardBody.java
* JIRA: http://issues.opennms.org/browse/NMS-8035
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS952
> NMS-8035: Fixed second scrollbar in IE/FF bug

- opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultAdminCategoryService.java
This seems like a more reliable way to do the comparison.
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS959
> Changed node type comparison to enumeration

- core/ipc/sink/camel-impl/src/main/java/org/opennms/core/ipc/sink/camel/CamelSinkServerProcessor.java
- features/minion/heartbeat/consumer/pom.xml
- features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
- features/minion/heartbeat/producer/src/main/java/org/opennms/minion/heartbeat/producer/HeartbeatProducer.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
- opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/MinionHeartbeatMonitor.java
- opennms-webapp/src/main/webapp/minion/main.html
- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsOnMinionTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/MinionHeartBeatTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8688
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS946
> NMS-8688: Create a node representing each Minion for monitoring

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventSubscriptionService.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImpl.java
- features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockEventIpcManager.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/MinionHeartBeatTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8735
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS976
> NMS-8735: Race condition in Minion provisioning

- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapQueueProcessor.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/Trapd.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/jmx/Trapd.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/jmx/TrapdMBean.java
* JIRA: https://issues.opennms.org/browse/NMS-8744
> NMS-8744: Trapd JMX trap counters don't count traps

- opennms-doc/guide-admin/src/asciidoc/text/provisioning/getting-started.adoc
Just 2 typos.
No need for a JIRA issue in my opinion.
Cyr
> Fixed 2 typos in guide-admin

- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
- opennms-webapp/src/main/webapp/heatmap/index.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8136
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS982
This PR also includes the JavaScript/requirejs fix. Due to the changes in 
NMS-8640 the Heatmap was not working anymore.
> NMS-8136: Using requirejs for Heatmap, fixed footer sizing

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MinionRestService.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/RestClient.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/MinionRestServiceTest.java
Events being sent whenever new Minion connects or it changes location.
* JIRA: http://issues.opennms.org/browse/hzn-872
* JIRA: http://issues.opennms.org/browse/hzn-873
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS966/latest
> HZN-872 : monitoringSystem Updates as events

- opennms-base-assembly/src/main/filtered/etc/opennms-datasources.xml
- pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/JmxConfigurationGeneratorIT.java
JIRA: https://issues.opennms.org/browse/NMS-8747
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS991
HikariCP is ready for prime time!
> NMS-8747: Use HikariCP as the default connection factory

- smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/TrapTest.java
> Remove unnecessary brokerUri configs from the Minion smoke tests

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/AbstractVertex.java
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/Vertex.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/GraphPainter.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/GWTEdge.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/GWTVertex.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/SharedVertex.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/VTopologyComponent.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/gwt/client/GWTEdgeTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLProperties.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/AlarmStatusProviderTest.java
- opennms-doc/guide-development/src/asciidoc/text/topology/graphml.adoc
JIRA: https://issues.opennms.org/browse/NMS-8663
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS934-3
See the JIRA issue for before and after screenshots.
> NMS-8663: Improve algorithm used to draw the edge paths between vertices

- opennms-webapp/src/main/webapp/js/onms-requisitions/views/foreignsource.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-panels.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/requisition.html
Replace the X with back button in the Angular provisioning WebUI.
The icon used is: http://fontawesome.io/icon/reply/
* JIRA: http://issues.opennms.org/browse/NMS-7908
> NMS-7908: Replace the X with back button in the Angular provisioning WebUI.

- tools/packages/minion/minion.init
One-liner to add the Java flag for dumping heap on OOM.
* JIRA: http://issues.opennms.org/browse/HZN-898
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1011
> HZN-898: dump heap on OOM

- features/events/syslog/blueprint-syslog-handler-default.xml
- features/events/syslog/blueprint-syslog-handler-kafka-default.xml
- features/events/traps/blueprint-trapd-handler-default.xml
- features/events/traps/blueprint-trapd-handler-kafka-default.xml
* JIRA: http://issues.opennms.org/browse/nms-8760
> NMS-8760: Override shutdown strategy

- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DefaultRrdDao.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/support/DefaultRrdDaoTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8775
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1014
This affects /opennms/summary/results.htm (the old API to retrieve summary data from RRD/JRB files).
> NMS-8775: RRDtool 1.6 doesn't like vames called ds

- core/daemon/src/main/java/org/opennms/netmgt/activemq/auth/JaasSecurityContext.java
- core/daemon/src/main/java/org/opennms/netmgt/activemq/auth/OpenNMSJaasAuthenticationBroker.java
- core/daemon/src/main/java/org/opennms/netmgt/activemq/auth/OpenNMSJaasBrokerPlugin.java
- core/daemon/src/test/java/org/opennms/netmgt/activemq/auth/OpenNMSJaasBrokerPluginTest.java
- dependencies/activemq/pom.xml
- opennms-base-assembly/src/main/filtered/etc/magic-users.properties
- opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml
- opennms-doc/guide-install/src/asciidoc/text/minion/configure.adoc
- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
JIRA: https://issues.opennms.org/browse/HZN-445
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS993-4
> HZN-445: Use JAAS to authenticate ActiveMQ connections

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/kafka.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/kafka-graphs.properties
This PR contains JMX collections and graph definitions for all of the key Kafka metrics mentioned in the Kafka operations documentation:
https://kafka.apache.org/090/ops.html
* JIRA: http://issues.opennms.org/browse/NMS-8545
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1022
> NMS-8545: Apache Kafka JMX collections and graph definitions

- features/events/traps/blueprint-trapd-listener.xml
Add shutdown strategy to Trapd listener
* JIRA: http://issues.opennms.org/browse/nms-8760
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1015
> NMS-8760: Add shutdown strategy to Trapd listener

- core/schema/src/main/java/org/opennms/core/schema/Migrator.java
- pom.xml
Cherry-pick of the commits from PR #1053 to foundation-2016.
* JIRA: http://issues.opennms.org/browse/NMS-8779
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1027
> NMS-8779: Installer script doesn't work with PostgreSQL 9.6 (foundation-2016)

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/InfoPanel.java
* JIRA: http://issues.opennms.org/browse/755
* Bamboo: http://bamboo.internal.opennms.com:8085/chain/result/viewChainResult.action?planKey=OPENNMS-ONMS1030&buildNumber=1
> HZN-755: Fixed resource graph redndering in info panels

- smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogTest.java
* JIRA: http://issues.opennms.org/browse/8707
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1007
> NMS-8707: Fixed syslog IT for changed event time handling

- core/jmx/impl/src/main/java/org/opennms/netmgt/jmx/impl/connection/connectors/Jsr160ConnectionFactory.java
* JIRA: http://issues.opennms.org/browse/NMS-8327
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1034
> NMS-8327: Add log for task completion

- features/opennms-es-rest/main-module/pom.xml
* JIRA: http://issues.opennms.org/browse/NMS-8783
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1039
> NMS-8783: Skipping elasticsearch startup if tests are skipped

- opennms-webapp/src/main/webapp/includes/eventlist.jsp
The "Recent Events" in the node page, shows HTML tags on the message
* JIRA: http://issues.opennms.org/browse/NMS-8794
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1041
> NMS-8794: The "Recent Events" in the node page, shows HTML tags on the message

- opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitorIT.java
- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
- smoke-test/src/test/java/org/opennms/smoketest/AdminSnmpConfigForIpPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-8789
> NMS-8789: SNMP web configurator does not allow zero retries

- core/schema/src/main/liquibase/19.0.0/changelog.xml
- core/schema/src/main/liquibase/create-sequences.xml
- core/test-api/db/src/test/java/org/opennms/core/test/db/InstallerDbIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapDTOMapperTest.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerDefaultIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerKafkaIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerMinionIT.java
- opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounder.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoringLocationDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockDistPollerDao.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/DistPollerDaoIT.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/support/JdbcFilterDaoIT.java
- opennms-model/src/main/java/org/opennms/netmgt/model/NetworkBuilder.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsDistPoller.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-webapp-rest/src/test/resources/v1/remotelocations.json
- tests/mock-elements/src/main/java/org/opennms/netmgt/mock/MockNode.java
Pretty self-explanatory, I'm also cleaning up some unused sequences since I have to write a Liquibase migration anyway.
JIRA:
* http://issues.opennms.org/browse/NMS-8749
* http://issues.opennms.org/browse/NMS-8261
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1026
> NMS-8749, NMS-8261: Change default location ID from 'localhost' to 'Default', remove unused sequences

- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/AddressSnmpConfigVisitor.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigManager.java
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpEventInfoTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpPeerFactoryTest.java
* JIRA: http://issues.opennms.org/browse/nms-8812
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1044
> NMS-8812: Fix default location handling in SNMP Config

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ClassBasedStrategyResolver.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolver.java
- core/snmp/integration-tests/pom.xml
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolverTest.java
JIRA: https://issues.opennms.org/browse/NMS-8620
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1043
> NMS-8620: Fallback to using the ClassBasedStrategyResolver

- opennms-icmp/opennms-icmp-jni6/src/test/java/org/opennms/netmgt/icmp/jni6/Jni6PingTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8838
> NMS-8838: respect runPingTests system property in JNI ICMP6 tests

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
* JIRA: https://issues.opennms.org/browse/HZN-790
* BAMBOO: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1060
> HZN-790: Make the 'browser tab' section toggleable

- opennms-icmp/commands/src/main/java/org/opennms/netmgt/icmp/commands/PingCommand.java
- opennms-icmp/commands/src/main/java/org/opennms/netmgt/icmp/commands/PingSweepCommand.java
- opennms-icmp/commands/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-icmp/opennms-icmp-api/pom.xml
- opennms-icmp/opennms-icmp-api/src/main/java/org/opennms/netmgt/icmp/proxy/LocationAwarePingSweepClient.java
- opennms-icmp/opennms-icmp-api/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepRequestBuilder.java
- opennms-icmp/opennms-icmp-api/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepSummary.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/pom.xml
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/IPRangeDTO.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/LocationAwarePingSweepClientImpl.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepRequestBuilderImpl.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepRequestDTO.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepResponseDTO.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepResultDTO.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepRpcModule.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/resources/META-INF/opennms/applicationContext-rpc-icmp.xml
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/test/java/org/opennms/netmgt/icmp/proxy/LocationAwarePingSweepClientIT.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/test/java/org/opennms/netmgt/icmp/proxy/PingSweepRequestDTOTest.java
- opennms-icmp/opennms-icmp-proxy-rpc-impl/src/test/java/org/opennms/netmgt/icmp/proxy/PingSweepResponseDTOTest.java
* JIRA: http://issues.opennms.org/browse/NMS-8824
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1048
> NMS-8824:  Add Ping Sweep RPC module

- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
This allows the send a GET request to ```/opennms//j_spring_security_check?j_username=$MYUSERNAME&j_password=$MYPASSWORD``` and returns a logged in session.
This is useful for Auto-Login.
* JIRA: https://issues.opennms.org/browse/HZN-930
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1054
> HZN-930: Allow login via GET requests

- features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css
* JIRA: http://issues.opennms.org/browse/NMS-8855
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1069
Be sure to lock background-size with target branch's width and height when merging.
> NMS-8855: Wallboard / Ops board renders product logo strangely

- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/discovery.adoc
- opennms-webapp-rest/pom.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/DiscoveryRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/DiscoveryRestServiceIT.java
JIRA: https://issues.opennms.org/browse/HZN-915
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1063-4
> HZN-915: Added ReST service for invoking one-time discovery scans

- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editExpression.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editThreshold.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8826
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1068
> NMS-8826: Threshold editor help text unclear about comparison operators

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpEventInfo.java
- opennms-web-api/src/main/java/org/opennms/web/svclayer/model/SnmpInfo.java
- opennms-webapp/src/main/java/org/opennms/web/admin/nodeManagement/SnmpConfigServlet.java
- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
- JIRA: http://issues.opennms.org/browse/HZN-925
- Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1064
> HZN-925: Add location to Configure SNMP page

- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/HttpPostMonitor.java
* JIRA: https://issues.opennms.org/browse/NMS-8864
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1077
Original pull request: https://github.com/OpenNMS/opennms/pull/1041.
As soon as bamboo goes green, this is ready to merge.
> NMS-8864: Handle cases when banner is not specified, or an empty string.

- features/topology-map/features/runtime-browsers/pom.xml
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/MetaTopologySelectorOperation.java
* JIRA: https://issues.opennms.org/browse/NMS-8865
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1078
> NMS-8865: Make feature "opennms-topology-runtime-linkd" uninstallable

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/CdpElementDaoHibernate.java
* JIRA: https://issues.opennms.org/browse/NMS-8863
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1085
> NMS-8863: NonUniqueResultException when retrieving CDP links

- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/services/Requisitions.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/interface.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-categories.html
Provisioning UI: Improve the suggestions for categories and services while editing requisitions.
* JIRA: http://issues.opennms.org/browse/NMS-8848
The solution has been verified on my testing environment.
> NMS-8848: Provisioning UI: Improve the suggestions for categories and services while editing requisitions

- opennms-webapp/src/main/webapp/element/linkednode.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8808
> NMS-8808: Gather all data before filling output stream

- opennms-webapp/src/main/webapp/admin/nodemanagement/instrumentationLogReader.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8858
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1101
> NMS-8858: Make the ILR put the node label alongside the package/IPADDR/Service tuple

- container/karaf/src/main/filtered-resources/etc/org.opennms.features.geocoder.google.cfg
- container/karaf/src/main/filtered-resources/etc/org.opennms.features.topology.app.cfg
- features/geocoder/google/src/main/java/org/opennms/features/geocoder/google/GoogleGeocoderService.java
- features/geocoder/google/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/info/CoordinateResolver.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/info/LocationInfoPanelItemProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/geocoder.adoc
- opennms-doc/guide-admin/src/asciidoc/text/topology/topology.adoc
* JIRA: https://issues.opennms.org/browse/NMS-8875
> NMS-8875: Topology is slow due to geocoding failures

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
This PR makes sure that we compare against location name when determining whether a node already exists upon a `newSuspect` call (specifically, `createUndiscoveredNode` in `Provisiond`).
* JIRA: http://issues.opennms.org/browse/NMS-8883
> NMS-8883: handle duplicate IPs in separate locations cleanly

- core/ipc/rpc/camel-impl/src/main/java/org/opennms/core/rpc/camel/CamelRpcClientPreProcessor.java
- core/ipc/rpc/camel-impl/src/test/java/org/opennms/core/rpc/camel/EchoRpcIT.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: https://issues.opennms.org/browse/HZN-946
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1115
> HZN-946: Allow the default RPC TTL to be increased

- features/ticketing/daemon/src/main/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayer.java
- features/ticketing/daemon/src/test/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayerTest.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
JIRA: https://issues.opennms.org/browse/NMS-8866
> NMS-8866: Add flags to support ignoring create/close ticket events

- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/MinionHeartbeatMonitor.java
JIRA: https://issues.opennms.org/browse/NMS-8890
> NMS-8890: Minion Heartbeat fails when OpenNMS is restarted

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
* JIRA: http://issues.opennms.org/browse/NMS-8851
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1094/latest
> NMS-8851: Allow filtering by severity in alarm list

- opennms-webapp/src/main/java/org/opennms/web/filter/NormalizedQueryParameters.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
* JIRA: http://issues.opennms.org/browse/NMS-8852
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1098/latest
> NMS-8852: Expose alarm-list limit parameter as a UI control

- opennms-webapp/src/main/webapp/js/onms-resources/app.js
- smoke-test/src/test/java/org/opennms/smoketest/ChooseResourcesPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-8886
> NMS-8886: Fix broken "Graph All" functionality

- core/upgrade/src/main/java/org/opennms/upgrade/implementations/DiscoveryConfigurationLocationMigratorOffline.java
- core/upgrade/src/main/java/org/opennms/upgrade/implementations/DiscoveryConfigurationMigratorOffline.java
- core/upgrade/src/test/java/org/opennms/upgrade/implementations/DiscoveryConfigurationLocationMigratorOfflineTest.java
- core/upgrade/src/test/resources/etc3/discovery-configuration.xml
- core/upgrade/src/test/resources/etc3/opennms.properties
- core/upgrade/src/test/resources/etc3/rrd-configuration.properties
* JIRA: https://issues.opennms.org/browse/HZN-940
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1120
> HZN-940: Create upgrade task for updating 'localhost' to 'Default' in discovery-configuration.xml

- features/amqp/event-forwarder/src/main/java/org/opennms/features/amqp/eventforwarder/internal/DefaultEventForwarder.java
- features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/internal/DefaultEventForwarder.java
- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventForwarder.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImpl.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImplTest.java
- features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/JsonDeserializationTest.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerDefaultIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdHandlerKafkaDefaultIT.java
- features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventForwarderImpl.java
- features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventForwarderQueueImpl.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/AbstractMockDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockEventIpcManager.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/TransactionAwareEventForwarder.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/EventAccumulator.java
JIRA: https://issues.opennms.org/browse/HZN-934
> HZN-934: Add support for synchronous event forwarding.

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/BasicTrapProcessor.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpObjId.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapDTO.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapDTOToObjectProcessor.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapObjectToDTOProcessor.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapDTOMapperTest.java
* JIRA: http://issues.opennms.org/browse/HZN-919
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1134
> HZN-919: Added missing trap identity fields to TrapDTO

- features/bsm/vaadin-adminpage/pom.xml
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceTreeTable.java
- features/topology-map/features/runtime-base/pom.xml
- features/topology-map/org.opennms.features.topology.app/pom.xml
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopoMapNavEntry.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/ToolbarPanel.java
- features/topology-map/org.opennms.features.topology.app/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/org.opennms.features.topology.link/pom.xml
- features/topology-map/org.opennms.features.topology.link/src/main/java/org/opennms/features/topology/link/Layout.java
- features/topology-map/org.opennms.features.topology.link/src/main/java/org/opennms/features/topology/link/TopologyLinkBuilder.java
- features/topology-map/org.opennms.features.topology.link/src/main/java/org/opennms/features/topology/link/TopologyProvider.java
- features/topology-map/org.opennms.features.topology.link/src/test/java/org/opennms/features/topology/link/TopologyLinkBuilderTest.java
- features/topology-map/pom.xml
- features/vaadin-dashlets/dashlet-features/src/main/resources/features.xml
- features/vaadin-dashlets/dashlet-topology/pom.xml
- features/vaadin-dashlets/dashlet-topology/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/TopologyDashlet.java
- features/vaadin-dashlets/dashlet-topology/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/event/NodeMarkerClusterCallback.java
- opennms-webapp/src/main/webapp/element/node.jsp
- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/BSMTopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-8510
> NMS-8510: Introduce TopologyLinkBuilder to relieably create links

- features/ticketing/daemon/src/main/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayer.java
- features/ticketing/daemon/src/test/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayerTest.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
JIRA: https://issues.opennms.org/browse/NMS-8866
Flip the default value for the system properties from `false` to `true` for 19.0.0.
> NMS-8866: Change the default value of skipCreateWhenCleared and skipCloseWhenNotCleared

- opennms-doc/guide-install/src/asciidoc/text/minion/configure.adoc
* JIRA: http://issues.opennms.org/browse/NMS-8902
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1144
> NMS-8902: Removed manual install of syslog listener from Minion docs

- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/akcp-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/checkpoint-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cisco-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/dell-openmanage-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/ericsson-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/fortinet-fortigate-explicitProxy-v5.2-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/foundry-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/ipunity-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/jboss-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/liebert-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/mcast-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/microsoft-wmi-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/nortel-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/novell-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/sofaware-embeddedngx-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/sun-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware5-cpu-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware5-datastore-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware5-disk-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware5-memory-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware5-system-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/wmi-memory-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/xmp-graph.properties
Invalid graph templates
* JIRA: http://issues.opennms.org/browse/NMS-8907
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1154
The changes have been verified with a custom script attached to the Jira
issue that executes a "rrdtool graph" command using the templates.
> NMS-8907: Invalid graph templates

- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
- opennms-webapp/src/main/java/org/opennms/web/event/DaoWebEventRepository.java
- opennms-webapp/src/main/java/org/opennms/web/event/Event.java
- opennms-webapp/src/main/java/org/opennms/web/event/EventFactory.java
- opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java
- opennms-webapp/src/main/java/org/opennms/web/event/EventUtil.java
- opennms-webapp/src/main/java/org/opennms/web/event/SortStyle.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/LocationFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeLocationFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeSystemIdFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/SystemIdFilter.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
- opennms-webapp/src/main/webapp/includes/event-advquerypanel.jsp
- opennms-webapp/src/test/java/org/opennms/web/event/filter/WebEventRepositoryFilterIT.java
* JIRA: https://issues.opennms.org/browse/HZN-315
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1149
> HZN-315: Add system/location column to event list in UI

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8914
> NMS-8914: Only allow update if Ticket Id and Ticket State are set

- opennms-assemblies/minion/src/main/filtered/etc/minion.init
* JIRA: http://issues.opennms.org/browse/HZN-952
> HZN-952: Ensure minion has stopped completely

- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-19.adoc
* JIRA: N/A
Noting configuration and major version changes.
> Add additional upgrade notes for 19.0.0.

- features/elasticsearch/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/CustomSyslogParser.java
* JIRA: http://issues.opennms.org/browse/NMS-8937
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1185
> NMS-8937: Reduce logging of event body in Elasticsearch forwarder

- opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java
* https://issues.opennms.org/browse/HZN-967
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1190
> HZN-967: Fixed Location filter to use exact string matching

- features/wsman/src/main/java/org/opennms/netmgt/collectd/WsManCollector.java
- features/wsman/src/test/java/org/opennms/netmgt/collectd/WSManCollectorTest.java
JIRA: https://issues.opennms.org/browse/NMS-8924
This patch fixes the support for indexed resource types. Tested against a system running Windows Server 2012.
> NMS-8924: WS-Man collection with resource-type only store last resource

- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/PeakTraffic_subreport.jrxml
This commit just backports the PeakTraffic_subreport.jrxml fix from NMS-8926 to the foundation branch.
* JIRA: http://issues.opennms.org/browse/NMS-8926
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1199
> NMS-8926: Backport the PeakTraffic_subreport.jrxml fix to foundation

- core/api/src/main/java/org/opennms/core/network/IPAddress.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/adaptors/tcp/TcpStreamHandler.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogParser.java
These optimizations were uncovered while testing the Minion syslog code.
* JIRA: http://issues.opennms.org/browse/NMS-8726
> NMS-8726: Optimizations uncovered with Minion syslog test

- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/snmp/SnmpCollector.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/configuration.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/introduction.adoc
No JIRA issues for these changes; They are all related to correcting typos in opennms-doc
> HZN-370: Typo fixes in SNMP collector and collectd docs

- core/lib/src/main/java/org/opennms/core/utils/StringUtils.java
- core/lib/src/test/java/org/opennms/core/utils/StringUtilsTest.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Event.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/ExpandableParameterResolverRegistry.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/processor/expandable/ExpandableParameter.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/processor/expandable/ExpandableParameterResolver.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilIT.java
JIRA: https://issues.opennms.org/browse/HZN-977
Optimize expanding tokens of the form `%parm[PARAM_NAME]%`
> HZN-977: Optimize named parameter expansion

- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventconfFactoryIT.java
JIRA: https://issues.opennms.org/browse/HZN-978
Optimize find the matching eventconf for a given UEI.
> HZN-978: Optimize event configuration lookup by UEI

- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-19.adoc
- opennms-webapp/src/main/java/org/opennms/web/utils/ExceptionUtils.java
- opennms-webapp/src/main/webapp/errors/alarmidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/categorynotfound.jsp
- opennms-webapp/src/main/webapp/errors/elementidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/eventidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/eventproxyexception.jsp
- opennms-webapp/src/main/webapp/errors/missingparam.jsp
- opennms-webapp/src/main/webapp/errors/nomanagedinterfaces.jsp
- opennms-webapp/src/main/webapp/errors/noticeidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/outageidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/sealingviolation.jsp
- opennms-webapp/src/main/webapp/errors/statisticsreportidnotfound.jsp
- opennms-webapp/src/test/java/org/opennms/web/utils/ExceptionUtilsTest.java
- pom.xml
JIRA: https://issues.opennms.org/browse/NMS-8674
Jetty 9.4.x has been released and the 9.3.x tree won't be maintained anymore.
This patch updates Jetty to the latest 9.4.x release.
> NMS-8674: Upgrade Jetty to 9.4.0.v20161208.

- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkdServiceImpl.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscovery.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridgeTopology.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/scheduler/Scheduler.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIpAddrTableGetter.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdIT.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/Nms7918EnIT.java
This pull request is create for fixing the following bugs for enhanced linkd so that 18.0.3 is released:
NMS-8964: Enlinkd Not Performing Bridge Topology Discovery
https://issues.opennms.org/browse/NMS-8964
NMS-8639: Concurrent Modification Exception Bridge Discovery Topology
https://issues.opennms.org/browse/NMS-8639
NMS-8067: ConstraintViolationException in Enlinkd for OSPF
https://issues.opennms.org/browse/NMS-8067
> NMS-8964 / NMS-8639 / NMS-8067: EnhancedLinkd fixes

- features/elasticsearch/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
- features/elasticsearch/event-forwarder/src/test/java/org/opennms/netmgt/elasticsearch/eventforwarder/ElasticsearchNorthbounderIT.java
This will prevent the SEDA queues from growing to unlimited size.
* JIRA: http://issues.opennms.org/browse/NMS-8777
> NMS-8777: Added size and blockWhenFull attributes to the ES 1.X forwarder

- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/StressCommand.java
Make the RRAs tunable for the metrics:stress command when using for
RRDtool.
As a bonus, improve the name of the metric names to be unique, and avoid
issues on ds.properties when testing RRDtool.
* JIRA: http://issues.opennms.org/browse/NMS-8972
> NMS-8972: Make the RRAs tunable for the metrics:stress command when using for RRDtool.

- core/ipc/rpc/camel-impl/src/main/resources/META-INF/opennms/applicationContext-rpc-client-camel.xml
- core/ipc/rpc/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-server.xml
- core/ipc/sink/camel-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-camel.xml
- core/ipc/sink/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-ipc-client.xml
- opennms-base-assembly/src/main/filtered/etc/log4j2.xml
JIRA: https://issues.opennms.org/browse/HZN-984
> HZN-984: Avoid logging JMS message contents by default

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java
Changed the Hibernate Query to use
equals instead of LIKE
* JIRA: http://issues.opennms.org/browse/NMS-8756
> NMS-8756: Exception in LatencyStoringServiceMonitorAdaptor

- features/elasticsearch/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
* JIRA: http://issues.opennms.org/browse/HZN-986
> HZN-986: Make Elasticsearch ports configurable in ES forwarder

- features/resource-cli/src/main/java/org/opennms/features/resourcemgnt/commands/ShowCommand.java
JIRA: https://issues.opennms.org/browse/NMS-8055
> NMS-8055: The resourcecli tool shows metrics as graph

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
JIRA: https://issues.opennms.org/browse/NMS-8019
> NMS-8019: Nodes with invalid NodeTypes can be created via the Nodes Rest-API

- opennms-webapp/src/main/webapp/element/linkednode.jsp
Fix typo in panel title in linkednode.jsp.
* JIRA: http://issues.opennms.org/browse/NMS-8981
> NMS-8981: Fix typo in panel title in linkednode.jsp

- container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.logging.cfg
* JIRA: https://issues.opennms.org/browse/NMS-6284
> NMS-6284: Make karaf log to ${opennms.home}/logs

- features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/AlarmProvider.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/AlarmProviderImpl.java
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineIT.java
- features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineTest.java
* JIRA: https://issues.opennms.org/browse/NMS-8978
> NMS-8978: Improve reduction key lookup

- features/ticketing/jira-integration/pom.xml
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPlugin.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/commands/VerifyCommand.java
- features/ticketing/jira-integration/src/test/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPluginTest.java
- features/ticketing/jira-integration/src/test/opennms-home/etc/jira.properties
- features/ticketing/jira-integration/src/test/resources/opennms-home/etc/jira.properties
* JIRA: https://issues.opennms.org/browse/NMS-8947
> NMS-8947: Close HttpConnection after usage

- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventUtil.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventUtilDaoImpl.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilHibernateIT.java
- features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilIT.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.ncs/src/test/java/org/opennms/features/topology/plugins/ncs/MockNodeDao.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/NodeDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockNodeDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
- opennms-services/src/test/java/org/opennms/netmgt/mock/EventUtilJdbcImpl.java
JIRA: https://issues.opennms.org/browse/NMS-8995
> NMS-8995: Added nodelocation event expansion token

- smoke-test/src/test/java/org/opennms/smoketest/ProvisioningIT.java
This is a backport of my changes to the smoke tests to make them handle timing issues more cleanly.
* JIRA: http://issues.opennms.org/browse/NMS-8544
> NMS-8544: use new APIs in ProvisionIT to avoid timing issues

- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
- smoke-test/src/test/java/org/opennms/smoketest/JmxConfigurationGeneratorIT.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/BSMTopologyIT.java
* JIRA: http://issues.opennms.org/browse/NMS-8544
> NMS-8544: fix smoke tests that were failing from timing issues

- features/topology-map/themes/default-theme/src/main/java/VAADIN/themes/topo_default/styles.css
* JIRA: https://issues.opennms.org/browse/NMS-9022
> NMS-9022: Add content for collapse/expand links

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/minion.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-minion-graph.properties
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/JmxDataCollectionConfigResourceIT.java
* JIRA: http://issues.opennms.org/browse/HZN-904
* JIRA: http://issues.opennms.org/browse/HZN-905
* JIRA: http://issues.opennms.org/browse/HZN-992
> HZN-904, HZN-905, HZN-992: JMX collections and graph definitions for RPC endpoints

- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
JIRA: https://issues.opennms.org/browse/NMS-9026
> NMS-9026: Fixed JavaScript error in Heatmap

- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/support/about.jsp
- Update copyright year in web UI footer
- Tweaks to trademark presentation in support/about.jsp
* JIRA: http://issues.opennms.org/browse/NMS-9060
> NMS-9060: Copyright bump 2017

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/ToolbarPanel.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoringLocationUtils.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/PathOutageManagerDaoImpl.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/ResponseTimeResourceType.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/ScanManager.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/LatencyCollectionResource.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9019
> NMS-9019: Bundle "Topology :: Plugins :: Net Utils" fails to start

- opennms-webapp/src/main/webapp/svg/atlas_icons.svg
* JIRA: https://issues.opennms.org/browse/NMS-9069
> NMS-9069: Bring back missing icon

- opennms-webapp/src/main/webapp/asset/modify.jsp
- opennms-webapp/src/main/webapp/asset/nodelist.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9065
> NMS-9065: Fixed the Asset pages JSPs to handle ACL filtering

- opennms-webapp/src/main/webapp/asset/modify.jsp
- opennms-webapp/src/main/webapp/asset/nodelist.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9065
> NMS-9065: Fixed the Asset pages JSPs to handle ACL filtering for release-19.0.0

- opennms-webapp/src/main/webapp/geomap/js/geomap.js
* JIRA: https://issues.opennms.org/browse/NMS-9081
Even if the issue is NMS-9081, I decided to mark each commit with HZN-911.
This makes an eventual cherry-pick or backport of HZN-911 easier, as we will not forget NMS-9081 in that case.
> NMS-9081: Fix geolocation cluster status calculation

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/CommandManager.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/DefaultOperationContext.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/MenuBarBuilder.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyMenuBar.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/HudDisplayState.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/HudDisplay.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/TestMenuBarBuilder.java
* JIRA: https://issues.opennms.org/browse/NMS-8330
Can somebody please verify this?
> NMS-8330: Fix Deadlock when clicking Menu Item in Topology UI

- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/FieldMapperRegistry.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPlugin.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/commands/ListFieldsCommand.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/AbstractModifyableOptionKeyFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/ArrayWrapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/CascadingSelectFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/ComponentFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/DefaultFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/FieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/GroupFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/IssueTypeFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/LabelsFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/MultiSelectFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/NumberFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/PriorityFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/ProjectFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/SingleSelectFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/StringFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/UserFieldMapper.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/fieldmapper/VersionFieldMapper.java
- features/ticketing/jira-integration/src/test/java/org/opennms/netmgt/ticketer/jira/FieldMapperRegistryTest.java
- features/ticketing/jira-integration/src/test/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPluginTest.java
- opennms-doc/guide-admin/src/asciidoc/text/ticketing/jira.adoc
* JIRA: https://issues.opennms.org/browse/NMS-9023
> NMS-9023: Rework the attribute to jira field mapping

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEditWindow.java
* JIRA: https://issues.opennms.org/browse/NMS-9002
> NMS-9002: Added height computation for BSM edit window

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: https://issues.opennms.org/browse/HZN-1013
> HZN-1013: Fixed opennms.properties centerUrl description

- opennms-doc/guide-admin/src/asciidoc/text/provisioning/scalability.adoc
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/StringIntervalAdapter.java
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/StringIntervalPropertyEditor.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
This PR makes it so you can set a scan interval of "0" on a foreign source, so that scans only occur if performed manually.
* JIRA: http://issues.opennms.org/browse/HZN-614
> HZN-614: handle a 0 scan-interval

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/gwt/client/HudDisplayState.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/HudDisplay.java
When fixing NMS-8330 (see PR https://github.com/OpenNMS/opennms/pull/1274 for `release-18.0.4`), we broke the navigation from the node detail page to the topology view functionality. This patch brings it back. 
* JIRA: https://issues.opennms.org/browse/NMS-8330
Just waiting for bamboo.
> NMS-8330: The missing pieces

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-webapp/src/main/webapp/geomap/map-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9076
> NMS-9076: Refine Geomap on start page

- features/collection/collectors/pom.xml
- features/collection/collectors/src/main/java/org/opennms/netmgt/collectd/HttpCollector.java
- features/collection/collectors/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/collection/collectors/src/test/java/org/opennms/netmgt/collectd/HttpCollectorComplianceTest.java
- features/collection/collectors/src/test/java/org/opennms/netmgt/collectd/HttpCollectorIT.java
- opennms-config-model/pom.xml
- opennms-config/src/main/java/org/opennms/netmgt/config/HttpCollectionConfigFactory.java
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/http.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/snmp/SnmpCollector.adoc
- smoke-test/src/test/java/org/opennms/smoketest/minion/CollectorListTest.java
JIRA: https://issues.opennms.org/browse/HZN-1003
This allows the HttpCollector to be be invoked at alternate locations.
> HZN-1003: HttpCollector support for Minion

- core/lib/src/main/java/org/opennms/core/utils/InetAddressUtils.java
- opennms-provision/opennms-detector-jmx/pom.xml
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/ConnectionWrapper.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/IsolatingClassLoader.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/JBossConnectionFactory.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/JBossConnectionWrapper.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/Jsr160ConnectionFactory.java
- opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/support/jmx/connectors/Jsr160ConnectionWrapper.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/ConnectionWrapper.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/IsolatingClassLoader.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/JBossConnectionFactory.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/JBossConnectionWrapper.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/JMXSecureConnectionFactory.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/Jsr160ConnectionFactory.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/Jsr160ConnectionWrapper.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/MX4JConnectionFactory.java
- opennms-services/src/main/java/org/opennms/protocols/jmx/connectors/MX4JConnectionWrapper.java
This fixes JMX polling and collections against IPv6 addresses.
* JIRA: http://issues.opennms.org/browse/NMS-9071
> NMS-9071: Fixed IPv6 handling in Jsr160ConnectionFactory

- features/minion/container/karaf/src/main/filtered-resources/etc/system.properties
* JIRA: http://issues.opennms.org/browse/NMS-8505
> NMS-8505: Minion system property to enable SNMP4J Log4j logging

- opennms-webapp/src/main/webapp/WEB-INF/jsp/trend/trend.jsp
- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
- opennms-webapp/src/main/webapp/js/global.js
JIRA: https://issues.opennms.org/browse/HZN-1023
> HZN-1023: Fixed HeatMap and Trend charts for front page

- opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java
- smoke-test/src/test/java/org/opennms/smoketest/RestInfoIT.java
JIRA: https://issues.opennms.org/browse/NMS-9103
> NMS-9103: Fix blank version strings

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/activemq-graph.properties
- opennms-doc/releasenotes/src/asciidoc/releasenotes/changelog-19.adoc
- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-19.adoc
* JIRA: http://issues.opennms.org/browse/HZN-626
> HZN-626: Fixed ActiveMQ counters and graph definitions

- features/internal-plugins-descriptor/pom.xml
* JIRA: http://issues.opennms.org/browse/NMS-9123
> NMS-9123: Mark org.opennms.core.ipc.sink.xml bundle as provided

- core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/aggregation/Aggregator.java
- core/ipc/sink/common/src/test/java/org/opennms/core/ipc/sink/aggregation/AggregationTest.java
JIRA: https://issues.opennms.org/browse/NMS-9114
> NMS-9114: Prevent NPEs while flushing buckets (Sink API)

- core/jmx/api/pom.xml
- core/jmx/api/src/main/java/org/opennms/netmgt/config/jmx/MBeanServer.java
- core/jmx/api/src/main/java/org/opennms/netmgt/jmx/JmxCollector.java
- core/jmx/impl/src/main/java/org/opennms/netmgt/jmx/impl/DefaultJmxCollector.java
- features/collection/collectors/src/main/java/org/opennms/netmgt/collectd/JMXCollector.java
- features/collection/collectors/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/collection/collectors/src/test/java/org/opennms/netmgt/collectd/JMXCollectorComplianceTest.java
- features/collection/collectors/src/test/java/org/opennms/netmgt/collectd/JMXCollectorTest.java
- opennms-config-jaxb/pom.xml
- opennms-config/src/main/java/org/opennms/netmgt/config/JMXDataCollectionConfigDao.java
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/jmx.adoc
- smoke-test/src/test/java/org/opennms/smoketest/minion/CollectorListTest.java
JIRA: https://issues.opennms.org/browse/HZN-1005
Here we add support for loading the JMXCollector (and friends) in the Minion container.
> HZN-1005: JMXCollector support for Minion

- container/features/src/main/resources/features-minion.xml
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/nsclient.adoc
- protocols/nsclient/pom.xml
- protocols/nsclient/src/main/java/org/opennms/protocols/nsclient/NSClientAgentConfig.java
- protocols/nsclient/src/main/java/org/opennms/protocols/nsclient/collector/NSClientCollector.java
- protocols/nsclient/src/main/java/org/opennms/protocols/nsclient/config/NSClientPeerFactory.java
- protocols/nsclient/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- protocols/nsclient/src/test/java/org/opennms/protocols/nsclient/NSClientAgentConfigTest.java
- protocols/nsclient/src/test/java/org/opennms/protocols/nsclient/collector/NsclientCollectorComplianceTest.java
- protocols/nsclient/src/test/java/org/opennms/protocols/nsclient/collector/NsclientCollectorTest.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/CollectorListTest.java
JIRA: https://issues.opennms.org/browse/HZN-1006
Here we add support for the NSClientCollector on Minion.
> HZN-1006: NSClientCollector support for Minion

- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java
- features/events/syslog/src/test/resources/etc/syslogd-nms5984-configuration.xml
* JIRA: http://issues.opennms.org/browse/NMS-5984
> NMS-5984: Added test to check syslog hostname parsing

- opennms-doc/guide-admin/src/asciidoc/text/poller/monitors/JDBCQueryMonitor.adoc
https://issues.opennms.org/browse/NMS-9141
> NMS-9141: wrong statement in jdbcquerymonitor docs

- features/eif-adapter/src/main/java/org/opennms/features/eifadapter/EifParser.java
- features/eif-adapter/src/main/resources/OSGI-INF/blueprint/blueprint-eif-adapter.xml
- opennms-base-assembly/src/main/filtered/etc/eventconf.xml
- opennms-base-assembly/src/main/filtered/etc/events/IBM.EIF.events.xml
- opennms-base-assembly/src/main/filtered/etc/org.opennms.features.eif-adapter.cfg
- opennms-doc/guide-admin/src/asciidoc/text/events/eif-adapter.adoc
Addressing the remaining requests in PR 992.
> NMS-8704: Add documentation and default configuration.

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceTreeTable.java
* JIRA: http://issues.opennms.org/browse/NMS-8370
> NMS-8370: Keep object tree intact while editing business services in admin-ui

- integration-tests/config/src/test/java/org/opennms/netmgt/config/WillItUnmarshalIT.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/eventd/EventdConfiguration.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/eventd/package-info.java
- opennms-config-model/src/main/resources/xsds/eventd-configuration.xsd
- opennms-config-model/src/test/java/org/opennms/netmgt/config/eventd/EventdConfigurationTest.java
- opennms-config/src/main/java/org/opennms/netmgt/config/EventdConfigManager.java
* JIRA: http://issues.opennms.org/browse/NMS-9134
> NMS-9134: convert eventd-configuration.xsd to JAXB

- opennms-base-assembly/src/main/filtered/etc/datacollection/cisco.xml
* JIRA: http://issues.opennms.org/browse/NMS-9094
> NMS-9094: SNMP data collection definitions for Cisco ASA5585-SSP-60

- features/events/traps/pom.xml
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdConfigReloadIT.java
- features/minion/core/api/src/main/java/org/opennms/minion/core/api/RestClient.java
- features/minion/core/features/src/main/resources/features.xml
- features/minion/core/impl/pom.xml
- features/minion/core/impl/src/main/java/org/opennms/minion/core/impl/ScvEnabledRestClientImpl.java
- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
JIRA: https://issues.opennms.org/browse/NMS-9157
Grants ROLE_MINION access to `/rest/info` and updates the `minion:ping` command to validate the response.
> NMS-9157: Verify the HTTP response when running minion:ping

- opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java
This minor enhancement lets you set datestamp fields (year, month, day of month, hour of day, minute, second, millisecond, and time zone) individually on the EventBuilder. This change is in preparation for the syslog parser enhancements.
> Added Calendar.Builder support to EventBuilder

- container/features/src/main/resources/features.xml
- core/daemon/src/main/resources/META-INF/opennms/applicationContext-activemq.xml
- core/db/src/main/java/org/opennms/core/db/DataSourceFactory.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/InetAddrUtils.java
- core/test-api/rest/src/main/java/org/opennms/core/test/rest/AbstractSpringJerseyRestTestCase.java
- features/discovery/src/main/java/org/opennms/netmgt/discovery/RangeChunker.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
- features/reporting/core/src/main/java/org/opennms/reporting/core/svclayer/support/DefaultReportWrapperService.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockEventIpcManager.java
- opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
- opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
- opennms-services/pom.xml
- opennms-services/src/test/java/org/opennms/netmgt/poller/PathOutageManagerDaoIT.java
I cleaned up a bunch of stashes and sandboxes a week ago and found a handful of minor changes worth committing.
> Minor cleanup

- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/CustomSyslogParser.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/Rfc5424SyslogParser.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogMessage.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogNGParser.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogClient.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java
- features/events/syslog/src/test/resources/syslogMessages.txt
* JIRA: http://issues.opennms.org/browse/NMS-9188
> NMS-9188: Don't return blank process values in CustomSyslogParser

- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/LocationMonitorRules.drl
- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/NodeParentRules.drl
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngineBuilderExamplesIT.java
- opennms-correlation/drools-correlation-engine/src/test/resources/test-context-examples.xml
JIRA: https://issues.opennms.org/browse/NMS-9186
This fixes the example configs and add a test to validate them.
> NMS-9186: Validate that the Drools examples load correctly.

- opennms-webapp/src/main/webapp/includes/grafana-box.jsp
NMS-9165: log entry in uncategorized.log
This pull request updates /include/grafana-box.jsp to use the newer 4.3 HttpComponents HttpClient interface and ensures that any open I/O streams are closed after use.
* JIRA: http://issues.opennms.org/browse/NMS-9165
> NMS-9165: Make sure all closeable objects are closed after use.

- core/schema/src/main/liquibase/19.0.2/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/SaveOrUpdateOperation.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-provision/opennms-provisiond/src/test/resources/import_dummy-empty.xml
- opennms-provision/opennms-provisiond/src/test/resources/import_dummy-foobar.xml
- opennms-provision/opennms-provisiond/src/test/resources/import_dummy-null.xml
- opennms-webapp/src/main/webapp/js/angular-onmsList-monitoringLocation.js
* JIRA: https://issues.opennms.org/browse/NMS-9146
> NMS-9146: Added fix for changing location to blank value

- features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
* JIRA: http://issues.opennms.org/browse/NMS-9062
> NMS-9062: Fixed another HTTP code log message

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/operations/SetFocusVertexOperation.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/BSMTopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-8542
> NMS-8542: Do not clear criteria on 'Set As Focus'

- opennms-webapp/src/main/scss/opennms-theme.scss
- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/ForeignSource.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/Node.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/Requisitions.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/services/Synchronize.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/detector.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/foreignsource.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/interface.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/move.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-assets.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-categories.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-interfaces.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-panels.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/node.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/policy.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/requisition.html
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/requisitions.html
- smoke-test/src/test/java/org/opennms/smoketest/ProvisioningNewUIIT.java
* JIRA: https://issues.opennms.org/browse/NMS-8601
> NMS-8601: Changed links in requisition UI to buttons and made them right-aligned

- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceFilter.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java
- features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceTreeTable.java
- features/themes/onms-default-theme/src/main/java/VAADIN/themes/opennms/styles.scss
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
* JIRA: https://issues.opennms.org/browse/HZN-699
> HZN-699: Added search filter for BSM admin page

- opennms-provision/opennms-provision-geolocation/pom.xml
- opennms-provision/opennms-provision-geolocation/src/main/java/org/opennms/netmgt/provision/GeolocationProvisioningAdapter.java
- opennms-provision/opennms-provision-geolocation/src/test/java/org/opennms/netmgt/provision/GeolocationProvisioningAdapterIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9187
> NMS-9187: Fix NPE in GeolocationProvisioningAdapter

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AcknowledgmentRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AlarmRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/AcknowledgmentRestServiceIT.java
* JIRA: http://issues.opennms.org/browse/NMS-9140
> NMS-9140: Check permissions on ACKing through ReST

- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/DNSResolutionMonitor.java
* JIRA: http://issues.opennms.org/browse/NMS-9238
> NMS-9238: Disable caching inside DNSResolutionMonitor

- opennms-webapp/src/main/webapp/js/angular-onmsList-monitoringLocation.js
- opennms-webapp/src/main/webapp/js/angular-onmsListEditInPlace.html
- opennms-webapp/src/main/webapp/locations/main.html
Various validation and behavior updates for the monitoring locations GUI.
JIRA:
* http://issues.opennms.org/browse/NMS-8713
* http://issues.opennms.org/browse/NMS-8715
* http://issues.opennms.org/browse/NMS-9028
* http://issues.opennms.org/browse/NMS-9167
> NMS-8713, NMS-8715, NMS-9028, NMS-9167: Monitoring locations UI bugfixes

- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JAgentConfig.java
- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
JIRA: https://issues.opennms.org/browse/NMS-9223
Optimize the way SNMP4J sessions are created, avoid unnecessary calls to `SecurityProtocols.getInstance().addDefaultProtocols()`.
> NMS-9223: Optimize SNMP4J session creation.

- opennms-base-assembly/src/main/filtered/bin/provision.pl
JIRA: https://issues.opennms.org/browse/HZN-1028
> HZN-1028: Minor update to provision.pl to show the node location when printing the node details.

- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8961
> NMS-8961: Added tooltip for HeatMap

- opennms-services/src/main/java/org/opennms/netmgt/poller/Poller.java
NMS-9247: Pollerd takes too much time scheduling polling when OpenNMS starts
This change reduces the amount of transactions against the database performed when the Poller is initializes (i.e. when OpenNMS is starting).
On a test VM using the dame DB when the problem was identified, the initialization time was drastically reduced.
* JIRA: http://issues.opennms.org/browse/NMS-9247
> NMS-9247: Pollerd takes too much time scheduling polling when OpenNMS starts

- pom.xml
* JIRA: http://issues.opennms.org/browse/NMS-9296
> NMS-9296: Bump Apache CXF version to 3.1.9

- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/Affliction.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/Cause.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/EventParameter.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/Flap.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/FlapCount.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/Impact.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/PossibleCause.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/RootCause.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/TimerExpired.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/config/EngineConfiguration.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/config/Global.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/config/RuleSet.java
- opennms-correlation/drools-correlation-engine/src/main/resources/xsds/drools-engine.xsd
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngineBuilderIT.java
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/PersistStateIT.java
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistState/PersistState.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistState/drools-engine.xml
- opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/Correlator.java
- opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/CorrelatorTest.java
- opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/MultiEngineBuilder.java
- opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/TestEngine.java
Persist Drools working memory to disk when stopping and starting OpenNMS
* JIRA: http://issues.opennms.org/browse/NMS-9143
> NMS-9143: Persist Drools working memory to disk when stopping and starting OpenNMS

- features/vaadin-dashlets/dashlet-rrd/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/RrdDashlet.java
* JIRA: https://issues.opennms.org/browse/NMS-7562
> NMS-7562: Fixed CSS for RrdDashlet

- features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/support/DefaultRrdDaoIntegrationTest.java
- opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/MultiOutputRrdStrategy.java
- opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/NullRrdStrategy.java
- opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/QueuingRrdStrategy.java
- opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/RrdMetaDataUtils.java
- opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/RrdStrategy.java
- opennms-rrd/opennms-rrd-jrobin/src/main/java/org/opennms/netmgt/rrd/jrobin/JRobinRrdStrategy.java
- opennms-rrd/opennms-rrd-jrobin/src/test/java/org/opennms/netmgt/rrd/jrobin/JRobinRrdStrategyTest.java
- opennms-rrd/opennms-rrd-rrdtool/opennms-rrdtool-api/src/main/java/org/opennms/netmgt/rrd/rrdtool/JniRrdStrategy.java
- opennms-rrd/opennms-rrd-rrdtool/opennms-rrdtool-api/src/main/java/org/opennms/netmgt/rrd/rrdtool/MultithreadedJniRrdStrategy.java
- opennms-rrd/opennms-rrd-tcp/src/main/java/org/opennms/netmgt/rrd/tcp/QueuingTcpRrdStrategy.java
- opennms-rrd/opennms-rrd-tcp/src/main/java/org/opennms/netmgt/rrd/tcp/TcpRrdStrategy.java
- opennms-rrd/opennms-rrd-tcp/src/test/java/org/opennms/netmgt/rrd/tcp/TcpRrdStrategyTest.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/JUnitCollector.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/JUnitCollectorExecutionListener.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpAttributeTest.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorIT.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptorPersistenceTest.java
This changes the RRD persistence to update the (cached) .meta files on each write.
* JIRA: http://issues.opennms.org/browse/NMS-8908
> NMS-8908: Always update .meta files

- core/lib/src/main/java/org/opennms/core/utils/StringUtils.java
- core/lib/src/test/java/org/opennms/core/utils/StringUtilsTest.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/HostResourceSwRunMonitor.java
- opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/HostResourceSWRunDetector.java
Includes a test to verify that the behavior of the new function matches the antlr.StringUtils behavior.
* JIRA: http://issues.opennms.org/browse/NMS-5646
> NMS-5646: Replaced weird antlr.StringUtils call with regex

- opennms-webapp/src/main/webapp/geomap/includes/map.jsp
- opennms-webapp/src/main/webapp/geomap/js/geomap.js
- opennms-webapp/src/main/webapp/geomap/standalone.jsp
- opennms-webapp/src/main/webapp/includes/bootstrap.jsp
- opennms-webapp/src/main/webapp/index.jsp
- opennms-webapp/src/main/webapp/js/global.js
* JIRA: https://issues.opennms.org/browse/NMS-9342
> NMS-9342: Make geomap a requirejs module to avoid requirejs conflicts

- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableElement.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableNode.java
Replaces a homegrown Lock class with java.util.concurrent.locks.ReentrantLock.
* JIRA: http://issues.opennms.org/browse/NMS-9347
> NMS-9347: Replace Lock with ReentrantLock

- opennms-web-api/src/main/java/org/opennms/web/svclayer/model/RelativeTimePeriod.java
NMS-6118 : Add additional relative time periods to choose from.
* Last Hour
* Last 2 Hours
* Last 4 Hours
* Last 8 Hours
* Last 12 Hours
* JIRA: http://issues.opennms.org/browse/NMS-6118
> NMS-6118 : Add additional relative time periods to choose from.

- core/schema/src/main/liquibase/19.1.1/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- features/geolocation/service/src/main/java/org/opennms/features/geolocation/services/DefaultGeolocationService.java
* JIRA: https://issues.opennms.org/browse/NMS-9338
> NMS-9338: Remove invalid long/lat values

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAssetRecord.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsGeolocation.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsGeolocationMergeTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9316
> NMS-9316: Merge geolocations correctly to allow geolocation resolution to update long/lat afterwards

- opennms-config/src/main/java/org/opennms/netmgt/config/KSC_PerformanceReportFactory.java
- opennms-webapp-rest/TODO
Calculation of KSC reports timespans "Last Week" and "This Week" broken due to Locale.
* JIRA: http://issues.opennms.org/browse/NMS-9325
> NMS-9325: Calculation of KSC reports timespans "Last Week" and "This Week" broken

- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoredServiceDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockMonitoredServiceDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/UnimplementedMonitoredServiceDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/MonitoredServiceDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/MonitoredServiceDaoIT.java
NMS-9346: BSM Admin add Edge BSM service is slow
Check:
* JIRA: http://issues.opennms.org/browse/NMS-9346
> NMS-9364: "Add Edge" in BSM configuration interface is slow

- opennms-base-assembly/src/main/filtered/bin/provision.pl
JIRA: https://issues.opennms.org/browse/NMS-9345
Small update to fix a regression from NMS-9269.
> NMS-9345: Remove extraneous space in URL used to add interfaces.

- opennms-webapp/src/main/webapp/js/onms-requisitions/views/quick-add-node-standalone.html
* JIRA: http://issues.opennms.org/browse/NMS-9386
> NMS-9386: Breadcrumb for requisitions has extra "/app" in path

- opennms-tools/centric-troubleticketer/src/main/rpm/opennms-plugin-ticketer-centric.spec
- pom.xml
JIRA: https://issues.opennms.org/browse/HZN-1079
A few version bumps to help us get further in compiling under Java 9.
> HZN-1079: Upgrade the jar, source and assembly Maven plugins

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithmTest.java
JIRA: https://issues.opennms.org/browse/NMS-9379
See JIRA for before and after screenshots.
> NMS-9379: Improved visualization for large trees with the Hierarchy Layout

- opennms-assemblies/minion/pom.xml
* JIRA: https://issues.opennms.org/browse/HZN-1055
> HZN-1055: Adopt changes from HZN-950.

- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editApplication.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/summary-box.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/chooseresource.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/servicesdown-box.jsp
- opennms-webapp/src/main/webapp/element/node.jsp
- opennms-webapp/src/main/webapp/errors/elementidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/elementnotfound.jsp
- opennms-webapp/src/main/webapp/graph/index.jsp
JIRA: https://issues.opennms.org/browse/NMS-9353, https://issues.opennms.org/browse/NMS-9354, https://issues.opennms.org/browse/NMS-9355
> NMS-9353: NMS-9354: NMS-9355: Escape additional fields to help prevent XSS

- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/app-quickaddnode.js
- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/QuickAddNode.js
JIRA: https://issues.opennms.org/browse/NMS-9353
> NMS-9353: Escape  the node label in the Growl message

- core/daemon/pom.xml
JIRA: https://issues.opennms.org/browse/HZN-1081
> HZN-1081: Avoid depending on tools.jar in Java 9+

- features/springframework-security/pom.xml
- features/springframework-security/src/main/java/org/opennms/web/springframework/security/JettyUserIdentityFilter.java
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/operation/request-logging.adoc
- opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
JIRA: https://issues.opennms.org/browse/HZN-1050
> HZN-1050: Add support for Jetty request logging (NSCA format)

- opennms-web-api/src/main/java/org/opennms/web/svclayer/model/NodeListCommand.java
- opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java
- opennms-webapp/src/main/webapp/includes/quicksearch-box.jsp
- smoke-test/src/test/java/org/opennms/smoketest/IndexPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9419
> NMS-9419: Fix 'BAD REQUEST (400)' error response when node id search is not an integer

- opennms-base-assembly/src/main/filtered/etc/events/opennms.config.events.xml
- opennms-base-assembly/src/main/filtered/etc/events/opennms.discovery.events.xml
- opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
- opennms-base-assembly/src/main/filtered/etc/events/opennms.provisioning.events.xml
- opennms-base-assembly/src/main/filtered/etc/events/opennms.reportd.events.xml
- opennms-base-assembly/src/main/filtered/etc/events/opennms.ticketd.events.xml
I found another events with that problem. I hope I got them all...
https://issues.opennms.org/browse/HZN-1054
> HZN-1054: Some (other) events have Log Messages that are more verbose than Description

- opennms-webapp/src/main/scss/geomap.scss
* JIRA: https://issues.opennms.org/browse/NMS-9424
> NMS-9424: Make status indicators 100% round

- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/SSLCertMonitor.adoc
* JIRA: http://issues.opennms.org/browse/HZN-1056
> HZN-1056: Fixed SNI related docs for SSLCertMonitor

- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/configuration.adoc
This commit adds documentation for the various resource types, and the persistence selector and storage strategies used in performance data collection.
* JIRA: http://issues.opennms.org/browse/NMS-9403
> NMS-9403 : Add documentation for Resource Types.

- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
- smoke-test/src/test/java/org/opennms/smoketest/AdminSnmpConfigForIpPageIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1080
> HZN-1080: Convert location input field to select box

- opennms-webapp/src/main/java/org/opennms/web/nodelabel/NodeLabelChangeServlet.java
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
* JIRA: https://issues.opennms.org/browse/NMS-9414
> NMS-9414: Revert deletion of NodeLabelChangeServlet to allow manually change of node label

- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
* JIRA: https://issues.opennms.org/browse/HZN-1089
> HZN-1089: Added missing include statement

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IPAddressTableTracker.java
See https://github.com/OpenNMS/opennms/pull/1533.
> NMS-9415: Check if ipAddressIfIndex contains any data

- core/ipc/rpc/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-server.xml
- core/ipc/sink/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-ipc-client.xml
- core/test-api/camel/src/main/resources/blueprint-empty-camel-context.xml
- features/activemq/component/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/amqp/alarm-northbounder/src/main/resources/OSGI-INF/blueprint/blueprint-alarm-northbounder.xml
- features/amqp/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
- features/amqp/event-receiver/src/main/resources/OSGI-INF/blueprint/blueprint-event-receiver.xml
- features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.ncs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.ncs/src/test/resources/blueprint/camelContext.xml
- pom.xml
- smoke-test/pom.xml
Upgrade to the latest version of Camel. Hurrah!
* JIRA: http://issues.opennms.org/browse/HZN-1094
> HZN-1094: Upgrade to Camel 2.19.1

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/index.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9421
> NMS-9421: Escape favorite tooltip correctly

- opennms-base-assembly/src/main/filtered/bin/vmwarecimquery
- opennms-base-assembly/src/main/filtered/bin/vmwareconfigbuilder
* JIRA: https://issues.opennms.org/browse/NMS-9456
> NMS-9456: Fixed missing jar in shell scripts

- opennms-model/src/main/java/org/opennms/netmgt/model/ResourceId.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsResourceIdTest.java
* JIRA: https://issues.opennms.org/browse/NMS-9427
> NMS-9427: Fixed NPE in Vaadin dashboard

- integrations/opennms-rancid-provisioning-adapter/src/main/java/org/opennms/netmgt/config/RancidAdapterConfigManager.java
- integrations/opennms-rancid-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/RancidProvisioningAdapter.java
- opennms-model/src/main/java/org/opennms/netmgt/model/topology/BridgePort.java
- opennms-model/src/main/java/org/opennms/netmgt/model/topology/BroadcastDomain.java
- opennms-model/src/main/java/org/opennms/netmgt/model/topology/SharedSegment.java
NMS-9471: Null Pointer Exception in SharedSegment
* JIRA: http://issues.opennms.org/browse/NMS-9471
NMS-9477:RancidAdapter type mismatch
* JIRA: http://issues.opennms.org/browse/NMS-9477
> NMS-9471: Fix NPE in shared Segment

- container/features/src/main/resources/features.xml
- features/events/api/pom.xml
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/AlarmData.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Autoacknowledge.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Autoaction.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Correlation.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Event.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/EventReceipt.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Events.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Forward.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Header.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Log.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Logmsg.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Mask.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Maskelement.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/OnmsStringBuilder.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Operaction.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Parm.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Parms.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Script.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Snmp.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Tticket.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Value.java
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImpl.java
- opennms-javamail/opennms-javamail-api/pom.xml
- opennms-webapp-rest/TODO
- pom.xml
* JIRA: http://issues.opennms.org/browse/NMS-9452
The new format is going to be an automatically generated version of all the members of the event related classes using JSON , skipping the null fields and empty collections.
> NMS-9452: Improve logging for EventIpcManagerDefaultImpl

- core/criteria/src/main/java/org/opennms/core/criteria/CriteriaBuilder.java
- core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restrictions.java
- core/criteria/src/main/java/org/opennms/core/criteria/restrictions/SqlRestriction.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/HibernateCriteriaConverter.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
Add a safe, parameterized version of CriteriaBuilder.sql().
* JIRA: http://issues.opennms.org/browse/NMS-9480
> NMS-9480: Added support for parameterized SQL to CriteriaBuilder.sql()

- core/lib/src/main/java/org/opennms/core/utils/LocationUtils.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/AddressSnmpConfigVisitor.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigAccessService.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigManager.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpPeerFactoryTest.java
JIRA: https://issues.opennms.org/browse/NMS-9462
Enhance the SNMP agent configuration to fallback to the definitions specified at the Default location if no specific entry for the requested location is found.
> NMS-9462: Improve SNMP configuration handling when dealing with locations

- core/criteria/src/main/java/org/opennms/core/criteria/CriteriaBuilder.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/HibernateCriteriaConverter.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
Addressed review comments from previous PR #1573.
* JIRA: http://issues.opennms.org/browse/NMS-9480
> NMS-9480: Addressed review comments

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/ErrorResponseProvider.java
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-common.xml
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v1.xml
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/RequisitionRestServiceIT.java
- smoke-test/src/test/java/org/opennms/smoketest/ErrorResponseIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1108
> HZN-1108: Map un-catched Exceptions to JAXRS Response

- opennms-webapp/src/main/webapp/WEB-INF/web.xml
Pretty straightforward. :)
* JIRA: http://issues.opennms.org/browse/NMS-9133
> NMS-9133: Added RESTv2 API URL to CORS filter configuration

- opennms-doc/guide-development/src/asciidoc/text/rest/alarms.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
* JIRA: http://issues.opennms.org/browse/NMS-9478
> NMS-9478: Remove docs for query parameter

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/service/DefaultSurveillanceViewService.java
* JIRA: http://issues.opennms.org/browse/NMS-9476
> NMS-9476: Use parameterized SQL inside DefaultSurveillanceViewService

- container/features/pom.xml
- container/features/src/main/resources/features.xml
Added a bundle that contains the missing package.
* JIRA: http://issues.opennms.org/browse/NMS-9341
> NMS-9341: Fixed ClassNotFoundException for OSGi DataSourceFactory

- opennms-webapp/src/main/java/org/opennms/web/rest/OnmsRestService.java
- opennms-webapp/src/test/java/org/opennms/web/rest/AlarmRestServiceTest.java
* JIRA: http://issues.opennms.org/browse/NMS-9478
> NMS-9478: Remove query parameter from OnmsRestService

- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/LazyChildResourceLoader.java
ConcurrentModificationException thrown by Statsd
* JIRA: http://issues.opennms.org/browse/NMS-9511
The solution suggested by @j-white was validated by the customer who reported the problem.
> NMS-9511: ConcurrentModificationException thrown by Statsd

- opennms-dao/src/main/java/org/opennms/netmgt/dao/BridgeTopologyDaoInMemory.java
- opennms-model/src/main/java/org/opennms/netmgt/model/topology/BroadcastDomain.java
- opennms-model/src/main/java/org/opennms/netmgt/model/topology/SharedSegment.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkdServiceImpl.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscovery.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridgeTopology.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryCdp.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryIpNetToMedia.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryIsis.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryLldp.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryOspf.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CdpCacheTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CdpInterfacePortNameGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/Dot1dBasePortIfIndexGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/IsisCircTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/IsisISAdjTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocPortGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocalGroupTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpRemTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIfTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIpAddrTableGetter.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfNbrTableTracker.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/SnmpGetter.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdIT.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdSnmpIT.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java
NMS-9505: Enlinkd blocks servce startup
* JIRA: http://issues.opennms.org/browse/NMS-9505
> NMS-9505: EnLinkd blocks service startup

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-doc/src/asciidoc/index.adoc
- opennms-doc/guide-install/src/asciidoc/index.adoc
- opennms-doc/guide-user/src/asciidoc/index.adoc
- opennms-doc/releasenotes/src/asciidoc/common/copyright.adoc
- opennms-doc/releasenotes/src/asciidoc/common/preface.adoc
- opennms-doc/releasenotes/src/asciidoc/index.adoc
* JIRA: http://issues.opennms.org/browse/NMS-9516
> Copyright bump in docs

- opennms-webapp/src/main/webapp/status/index.jsp
- opennms-webapp/src/main/webapp/status/js/angular-status.js
* JIRA: https://issues.opennms.org/browse/NMs-9563
> NMS-9563: Adjust module names and includes

- opennms-dao/src/main/java/org/opennms/netmgt/dao/BridgeTopologyDaoInMemory.java
- opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridgeTopology.java
Print topology is expensive operation avoid calculation if unless log level is appropriate
* JIRA: http://issues.opennms.org/browse/NMS-9561
> NMS-9561: check log for printtopology

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/ticketing/remedy.adoc
* JIRA: http://issues.opennms.org/browse/NMS-9538
> NMS-9538: Document supported products and versions for Remedy integration

- features/minion/core/impl/src/main/java/org/opennms/minion/core/impl/ScvEnabledRestClientImpl.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/InfoDTO.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/InfoRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/config/TicketerConfig.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java
- smoke-test/src/test/java/org/opennms/smoketest/RestInfoIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9569
> NMS-9569: Add ticketer config information to info endpoint

- debian/rules
- dependencies/jradius/pom.xml
- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/RadiusAuthMonitor.adoc
- protocols/radius/src/main/java/org/opennms/protocols/radius/detector/RadiusAuthDetector.java
- protocols/radius/src/main/java/org/opennms/protocols/radius/detector/client/CompositeAttributeLists.java
- protocols/radius/src/main/java/org/opennms/protocols/radius/detector/client/RadiusDetectorClient.java
- protocols/radius/src/main/java/org/opennms/protocols/radius/monitor/RadiusAuthMonitor.java
- protocols/radius/src/main/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProvider.java
- protocols/radius/src/main/java/org/opennms/protocols/radius/utils/RadiusUtils.java
- protocols/radius/src/test/java/org/opennms/protocols/radius/detector/RadiusAuthDetectorTest.java
- protocols/radius/src/test/java/org/opennms/protocols/radius/monitor/RadiusAuthMonitorTest.java
- tools/packages/opennms/opennms.spec
This is a rebase to resolve the conflicts in this branch. It replaces PR #1546.
https://github.com/jm-k/opennms/tree/NMS-9416
* JIRA: http://issues.opennms.org/browse/NMS-9416
> NMS-9416: EAP-TTLS tunneling protocol for RADIUS poller/detector

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/ErrorResponseProvider.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/NoSuchElementProvider.java
* JIRA: https://issues.opennms.org/browse/NMS-9598
> NMS-9598: Set media type in ExceptionMappers

- core/upgrade/src/main/java/org/opennms/upgrade/implementations/EventParameterMigratorOffline.java
* JIRA: https://issues.opennms.org/browse/NMS-9602
> NMS-9602: Fixed EventParameterMigratorOffline to nullify eventParms correctly

- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
- opennms-webapp/src/main/webapp/graph/forecast.jsp
Resource graph forecast page lacks header
* JIRA: http://issues.opennms.org/browse/NMS-8856
> NMS-8856: Resource graph forecast page lacks header

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/user-management/security-roles.adoc
- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
- opennms-doc/guide-install/src/asciidoc/index.adoc
* JIRA: https://issues.opennms.org/browse/LTS-209
> LTS-209: Hide Minion-related documentation if opennms-prime is used

- opennms-webapp/src/main/java/org/opennms/web/event/EventFactory.java
* JIRA: http://issues.opennms.org/browse/NMS-9605
> NMS-9605: Fixed wrong event column name

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsOutage.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsOutageTest.java
- opennms-webapp-rest/src/test/resources/v1/outages.json
- opennms-webapp/src/main/webapp/element/indexNew.jsp
- opennms-webapp/src/main/webapp/element/main.html
- opennms-webapp/src/main/webapp/js/angular-onms-elementList-node.js
- opennms-webapp/src/main/webapp/js/angular-onms-elementList-notification.js
- opennms-webapp/src/main/webapp/js/angular-onms-elementList-outage.js
- opennms-webapp/src/main/webapp/js/angular-onms-restresources.js
- opennms-webapp/src/main/webapp/notification/indexNew.jsp
- opennms-webapp/src/main/webapp/notification/main.html
- opennms-webapp/src/main/webapp/outage/indexNew.jsp
- opennms-webapp/src/main/webapp/outage/main.html
This PR contains changes so that the Angular list pages for outages and notifications will use the new metadata endpoints. Now you can choose any metadata property when filtering and autocomplete works for each property value.
It also contains a first pass at a node list implemented with Angular.
* JIRA: http://issues.opennms.org/browse/HZN-427
> HZN-427: Use RESTv2 metadata for outage and notification lists

- core/upgrade/src/test/resources/etc2/opennms.properties
- features/rest/mapper/src/main/java/org/opennms/web/rest/mapper/v2/AlarmMapper.java
- features/rest/mapper/src/test/java/org/opennms/web/rest/mapper/v2/AlarmMapperTest.java
- features/rest/mapper/src/test/resources/alarm.34.dto.json
- features/rest/mapper/src/test/resources/alarm.34.dto.xml
- features/rest/model/src/main/java/org/opennms/web/rest/model/v2/AlarmDTO.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-doc/guide-admin/src/asciidoc/text/ticketing/introduction.adoc
- opennms-doc/releasenotes/src/asciidoc/index.adoc
- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-21.adoc
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
- opennms-webapp/src/test/resources/WEB-INF/configuration.properties
- smoke-test/opennms-home/etc/opennms.properties
* JIRA: https://issues.opennms.org/browse/NMS-9587
> NMS-9587: Expose troubleTicketerLink via rest

- opennms-assemblies/remote-poller-standalone/src/main/filtered/remote-poller.sh
* JIRA: https://issues.opennms.org/browse/NMS-9606
> NMS-9606: Fixed path for remote-poller.jar in script

- integrations/opennms-vmware/pom.xml
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlConnection.java
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareCimQuery.java
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/vmware/VmwareViJavaAccessTest.java
* JIRA: https://issues.opennms.org/browse/NMS-9611
> NMS-9611: Fix timeout and paralellize

- container/features/src/main/resources/features.xml
- dependencies/jna/pom.xml
This aligns our JNA version with the version newly included in Karaf 4.1.1.
* JIRA: http://issues.opennms.org/browse/HZN-1156
> HZN-1156: Upgrade to JNA 4.3.0

- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JUtils.java
JIRA: https://issues.opennms.org/browse/NMS-9620
This fixes a few corner cases where the snmp4j session is not be properly closed.
We have yet to confirm whether or not the situation in NMS-9620 is fully resolved with this patch, but we should include these fixes either way.
> NMS-9620: Ensure the SNMP session is always closed.

- container/features/src/main/resources/features.xml
- dependencies/jna/pom.xml
- pom.xml
Another JNA upgrade to track with the latest version of Apache Karaf.
* JIRA: http://issues.opennms.org/browse/HZN-1157
> HZN-1157: Upgrade to JNA 4.4.0

- integration-tests/config/src/test/java/org/opennms/netmgt/config/SnmpDataCollectionTest.java
- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
JIRA: https://issues.opennms.org/browse/NMS-9643
Reorder the includes in alphabetical order, and add a test to enforce this structure going forward.
> NMS-9643: Re-order some of the includes in the default (SNMP) data collection configuration

- opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
* JIRA: https://issues.opennms.org/browse/NMS-9372
> NMS-9372: Added other Juniper router models

- core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml
Lint cleanup from #1491.
* JIRA: http://issues.opennms.org/browse/HZN-1071
> HZN-1071: Remove org.apache.activemq.SERIALIZABLE_PACKAGES

- features/collection/collectors/src/main/java/org/opennms/netmgt/collectd/HttpCollector.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitor.java
- pom.xml
- protocols/selenium-monitor/pom.xml
Upgrade Apache httpcore and httpclient
* JIRA: http://issues.opennms.org/browse/NMS-9661
> NMS-9661: Upgrade Apache httpcore and httpclient

- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/support/VertexHopGraphProvider.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/NoContentAvailableWindow.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9423
This PR is based on the work from @pdzaccone. See PR https://github.com/OpenNMS/opennms/pull/1602 for more details.
> NMS-9423: An empty collapsible vertex is not shown properly when collapsed

- opennms-base-assembly/src/main/filtered/etc/resource-types.d/wsman-microsoft-windows.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/microsoft-winrm-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/microsoft-wmi-graph.properties
- opennms-base-assembly/src/main/filtered/etc/wsman-datacollection.d/microsoft-windows.xml
Also made a few small enhancements and fixes along the way.
* JIRA: http://issues.opennms.org/browse/NMS-9649
> NMS-9649: Align WS-Management collection definitions with WMI ones

- opennms-webapp/src/main/java/org/opennms/web/event/SortStyle.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
* JIRA: https://issues.opennms.org/browse/NMS-8445
> NMS-8445: Display AlarmId on Event page

- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9671
> NMS-9671: Fixing cross-site vulnerability in heatmap (foundation-2016)

- opennms-webapp/src/main/webapp/heatmap/heatmap-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9671
> NMS-9671: Fixing cross-site vulnerability in heatmap

- features/telemetry/config/pom.xml
- features/telemetry/config/src/assembly/xsds.xml
- features/telemetry/config/src/main/java/org/opennms/netmgt/telemetry/config/model/package-info.java
- features/telemetry/config/src/main/resources/xsds/telemetryd-config.xsd
- features/telemetry/config/src/test/java/org/opennms/netmgt/telemetry/config/model/TelemetrydConfigTest.java
- opennms-assemblies/xsds/pom.xml
- opennms-assemblies/xsds/src/assembly/xsds.xml
HZN-1162: Create an XSD for telemetryd-configuration.xml
* JIRA: https://issues.opennms.org/browse/HZN-1162
> HZN-1162: Create Telemetryd config xsd

- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-21.adoc
Fix major version numbers from Horizon 20 or Horizon 21.
> Fix major version number in whatsnew-21

- opennms-webapp/src/main/webapp/geomap/includes/map.jsp
* JIRA: http://issues.opennms.org/browse/NMS-9700
> Fix NMS-9700: Typo in regional status geo map: Unacknowledges (for unacknowledged)

- opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Interface.js
* JIRA: http://issues.opennms.org/browse/NMS-9701
> Fix NMS-9701: Typo: "not elegible" for SNMP primary N enumeration

- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/minion/TelemetryIT.java
- smoke-test/src/test/resources/telemetryd-configuration.xml
Add system tests for handling JTI payloads both at OpenNMS and Minion side.
* JIRA: https://issues.opennms.org/browse/HZN-1164
> HZN-1164: System tests for handling JTI payloads

- opennms-webapp/src/main/webapp/admin/nodemanagement/instrumentationLogReader.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9672
> NMS-9672: Fixed XSS vulnerability in instrumentationLogReader.jsp

- core/lib/src/main/java/org/opennms/core/utils/WebSecurityUtils.java
- core/lib/src/test/java/org/opennms/core/utils/WebSecurityUtilsTest.java
* JIRA: http://issues.opennms.org/browse/NMS-9645
> NMS-9645: Also sanitize for xml attribute characters

- opennms-webapp/src/main/webapp/js/angular-onmsList.js
This isn't as critical in the foundation branches because not many pages use the Angular list code.
* JIRA: http://issues.opennms.org/browse/NMS-9694
> NMS-9694: Fix typo in typeof comparison to fix FIQL search encoding

- opennms-doc/guide-admin/src/asciidoc/text/asset-topology/graphml-asset-topology-provider.adoc
- opennms-doc/guide-admin/src/asciidoc/text/telemetryd/telemetryd.adoc
Fixed capitalization on Additional Notes section.
JIRA: https://issues.opennms.org/browse/NMS-9707
> NMS-9707: Admin Guide 12.8 Typo

- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowException.java
- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowRepositoryProvider.java
- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/QueryException.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/pom.xml
- features/flows/rest/pom.xml
- features/flows/rest/src/main/java/org/opennms/web/rest/v1/FlowRepositoryProvider.java
- features/flows/rest/src/main/java/org/opennms/web/rest/v1/FlowRestService.java
- features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java
- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/DefaultFlowRepositoryProvider.java
- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5Adapter.java
- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5Converter.java
- features/telemetry/adapters/netflow/src/main/resources/META-INF/opennms/component-dao.xml
- opennms-base-assembly/pom.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/ServiceUnavailableResponseProvider.java
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-common.xml
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v1.xml
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/flow/FlowStackIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1171
> HZN-1171: Implement Flow ReST API to query for flows

- core/db-install/src/main/java/org/opennms/core/db/install/InstallerDb.java
- opennms-install/src/main/java/org/opennms/install/Installer.java
* JIRA: https://issues.opennms.org/browse/NMS-9448
> NMS-9448: Verify that database and system time match

- features/topology-map/themes/default-theme/pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-9716
Is not critical, just a cleanup, therefore based against develop.
> NMS-9716: Remove unnecessary dependencies

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/NMS9718Test.java
- features/mib-compiler/src/test/resources/GWMONITOR-MIB.mib
Unexpected errors while generating event definitions from TRAP-TYPE without a DESCRIPTION field
* JIRA: http://issues.opennms.org/browse/NMS-9718
> NMS-9718: Unexpected errors while generating event definitions from TRAP-TYPE without a DESCRIPTION field

- core/xml/src/main/java/org/opennms/core/xml/StringListTrimAdapter.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/groups/Group.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/users/User.java
- opennms-config-model/src/test/java/org/opennms/netmgt/config/groups/GroupsTest.java
This PR makes duty schedule (and other group) parsing more forgiving, trimming strings down.
* JIRA: http://issues.opennms.org/browse/NMS-9709
> NMS-9709: clean up duty schedule parsing

- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/xmp.adoc
Description for the Collector Parameters table referenced WmiCollector
* JIRA: https://issues.opennms.org/browse/NMS-9726
> NMS-9726: XmpCollector Documentation Typo

- container/features/src/main/resources/features.xml
- core/xml/src/main/java/org/opennms/core/xml/NumberAdapter.java
- features/collection/api/src/test/java/org/opennms/features/collection/dto/CollectionSetDTOTest.java
- features/wsman/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- smoke-test/src/test/java/org/opennms/smoketest/minion/MonitorsListCommandIT.java
JIRA: https://issues.opennms.org/browse/NMS-9711
Here we fix a few issues related to WsMan on Minion:
* Expose the WsManMonitor
* Add support for handling NaN values in the CollectionSet
* Load Xalan bundles when using WsMan to fix issues parsing certain payloads
> NMS-9711: WsMan fixes for Minion

- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryInitializer.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: https://issues.opennms.org/browse/HZN-1184
> HZN-1184: Defer initialization until needed and try indefinately

- features/telemetry/adapters/netflow/pom.xml
- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5Adapter.java
- features/telemetry/adapters/netflow/src/test/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5AdapterTest.java
- features/telemetry/adapters/netflow/src/test/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5AdapterTestConfig.java
* JIRA: https://issues.opennms.org/browse/HZN-1188
> HZN-1188: Cache NodeInfo objects instead of re-fetching them all the time

- dependencies/jmx/pom.xml
- features/jmx-config-generator/pom.xml
- pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-8596
> NMS-8596: Add jmxmp protocol implementation to classpath by default

- opennms-webapp/pom.xml
- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editExpression.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editGroup.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editThreshold.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/roles/editDetails.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/roles/editSpecific.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/roles/list.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/roles/view.jsp
JIRA: https://issues.opennms.org/browse/NMS-9673
JIRA: https://issues.opennms.org/browse/NMS-9674
> NMS-9673: NMS-9674: Fix XSS issues in thresholds and userGroupView

- opennms-webapp/src/main/java/org/opennms/web/services/FilterFavoriteService.java
- opennms-webapp/src/test/java/org/opennms/web/services/FilterFavoriteServiceIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9670
This may also be worth back porting to `foundation-2016` as well.
> NMS-9670: Prevent XSS attacks when creating a filter

- features/flows/rest/pom.xml
- features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/OnmsJestClient.java
- features/jest/feature/pom.xml
- features/jest/jest-complete-osgi/pom.xml
- pom.xml
- protocols/selenium-monitor/pom.xml
* JIRA: https://issues.opennms.org/browse/HZN-1183
> HZN-1183: Update Jest library to version 5.3.3

- opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/Requisitions.js
- opennms-webapp/src/main/webapp/js/onms-requisitions/views/clone-foreignsource.html
The content of the clone foreign source definition dialog is misleading
* JIRA: http://issues.opennms.org/browse/NMS-9749
I verified the solution with the customer who reported the problem.
> NMS-9749: The content of the clone foreign source definition dialog is misleading

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImportRequest.java
JIRA: https://issues.opennms.org/browse/NMS-9681
> NMS-9681: Import all VMs when importVMAll is set.

- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-21.adoc
Bumped PostgreSQL version to minimal supported version.
> Update PostgreSQL compatibility version

- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JexlEvaluateFunctions.java
- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/SampleArrayFunctions.java
- features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineEnhancedTest.java
- opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc
https://issues.opennms.org/browse/NMS-9743 Jexl Measurements API enhancements
incorporated changes following  Jessi's comments on previous pull request 
https://github.com/OpenNMS/opennms/pull/1770 (now closed)
on new branch NMS-9743-v2 
https://github.com/OpenNMS/opennms/tree/jira/NMS-9743-v2
which targets origin/release-21.0.2  (not foundation 2017)
and bamboo
https://bamboo.opennms.org/browse/OPENNMS-ONMS1940
>  jira/NMS-9743-v2 Jexl Measurements API enhancements - revised

- features/flows/elastic/pom.xml
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryInitializer.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/CachingTemplateLoader.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/DefaultTemplateLoader.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/IndexSettings.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/MergingTemplateLoader.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/TemplateLoader.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/template/TemplateMerger.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/CachingTemplateLoaderTest.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/DefaultTemplateLoaderTest.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/IndexSettingsTest.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/MergingTemplateLoaderTest.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/TemplateMergerTest.java
- features/flows/elastic/src/test/resources/netflow-template-merged.json
- opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5/interface.adoc
* JIRA: https://issues.opennms.org/browse/HZN-1197
> HZN-1197: Provide functionality to define settings.index values

- features/remote-poller-jnlp/src/main/jnlp/scan-report.vm
- features/remote-poller/src/main/java/org/opennms/poller/remote/Main.java
Here's a couple of minor Remote Poller installer changes that needed to be done from foundation-2016 to foundation-2017.
* JIRA: http://issues.opennms.org/browse/NMS-9721
> NMS-9721: Minor merge fixes

- core/schema/src/main/liquibase/foundation-2017/changelog.xml
- features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/browsers/OnmsVaadinContainer.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
* JIRA: https://issues.opennms.org/browse/NMS-9742
> NMS-9742: Prevent duplicate reduction key entries and fix already wrong memos

- opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java
* JIRA: https://issues.opennms.org/browse/NMS-9767
> NMS-9767: Consider opennmsHome when adding version.properties

- container/features/pom.xml
- container/features/src/main/resources/features.xml
- opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
This is _partial_ work on HZN-1203. This PR adds new/missing features to the Karaf ITs and fixes problems detected by the ITs.
* JIRA: http://issues.opennms.org/browse/HZN-1203
> HZN-1203: Updated Karaf features and integration tests

- features/ifttt/src/main/java/org/opennms/features/ifttt/config/TriggerPackage.java
- features/ifttt/src/test/java/org/opennms/features/ifttt/config/IfTttConfigTest.java
- opennms-base-assembly/src/main/filtered/etc/ifttt-config.xml
* JIRA: https://issues.opennms.org/browse/NMS-9781
> NMS-9781: Attribute categoryFilter missing in default ifttt-config.xml

- core/lib/src/main/java/org/opennms/core/collections/JdbcSet.java
- core/lib/src/main/java/org/opennms/core/collections/LazyList.java
- core/lib/src/main/java/org/opennms/core/collections/LazySet.java
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolver.java
- features/collection/api/pom.xml
- features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerAttributeDTO.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/poller/Parameter.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/poller/PollerClassObjectAdapter.java
- opennms-config/src/main/resources/META-INF/opennms/applicationContext-commonConfigs.xml
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DistributedStatusResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DomainResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/GenericIndexResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceSnmpResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/LazyChildResourceLoader.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/LazyResourceAttributeLoader.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/NodeResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/NodeSnmpResourceType.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/ResponseTimeResourceType.java
- opennms-services/src/main/java/org/opennms/netmgt/passive/PassiveStatusKeeper.java
- opennms-services/src/main/java/org/opennms/netmgt/passive/PassiveStatusKey.java
- opennms-services/src/main/java/org/opennms/netmgt/passive/PassiveStatusValue.java
- opennms-services/src/test/java/org/opennms/netmgt/passive/PassiveStatusTest.java
This is some minor cleanup work in preparation for loading the DAOs in Karaf. Please do not delete the branch after merging since I'm still working on that branch.
* JIRA: http://issues.opennms.org/browse/HZN-1202
> HZN-1202: OSGi cleanup for loading DAOs in Karaf

- opennms-webapp/src/main/webapp/js/onms-search/app.js
* JIRA: https://issues.opennms.org/browse/NMS-9776
> NMS-9776: Filter report list after querying

- features/geocoder/api/src/main/java/org/opennms/features/geocoder/Coordinates.java
- features/geocoder/google/src/main/java/org/opennms/features/geocoder/google/GoogleCoordinates.java
- features/geolocation/api/src/main/java/org/opennms/features/geolocation/api/Coordinates.java
- features/geolocation/service/src/main/java/org/opennms/features/geolocation/services/DefaultGeolocationService.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.asset/src/main/java/org/opennms/features/topology/plugins/topo/asset/layers/Layers.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.asset/src/test/java/org/opennms/features/topology/plugins/topo/asset/filter/FilterParserTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.asset/src/test/java/org/opennms/features/topology/plugins/topo/asset/util/AssetBuilder.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAssetRecord.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsGeolocation.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsGeolocationMergeTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1219
> HZN-1219: Read coordinates as double instead of float

- opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
I missed a couple of DefaultCollectionAgent calls that needed to be updated after my recent refactoring in Collectd.
* JIRA: http://issues.opennms.org/browse/HZN-1202
> HZN-1202: Fix DefaultSnmpCollectionAgent calls

- features/telemetry/adapters/collection/src/main/java/org/opennms/netmgt/telemetry/adapters/collection/AbstractPersistingAdapter.java
- opennms-config/src/main/java/org/opennms/netmgt/filter/JdbcFilterDao.java
- opennms-dao/pom.xml
- opennms-dao/src/test/java/org/opennms/netmgt/dao/support/JdbcFilterDaoIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1161
> HZN-1161: Improve check of isValid(String, String)

- opennms-webapp/src/main/webapp/WEB-INF/jsp/support/index.jsp
* JIRA: http://issues.opennms.org/browse/NMS-9832
> NMS-9832: Change links in support page to use https instead of http

- container/features/src/main/resources/features.xml
- core/db/src/main/java/org/opennms/core/db/DataSourceFactory.java
Also cleaned up unnecessary `wrap:` for HikariCP inside our `features.xml`.
> Changed DataSourceFactory to use HikariCP by default

- features/flows/classification/engine/pom.xml
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/CachingClassificationEngine.java
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/DefaultClassificationEngine.java
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/TimingClassificationEngine.java
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/classifier/CombinedClassifier.java
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/value/PortValue.java
- features/flows/classification/engine/src/main/java/org/opennms/netmgt/flows/classification/value/RangedValue.java
- features/flows/classification/engine/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/classification/engine/src/test/java/org/opennms/netmgt/flows/classification/DefaultClassificationEngineTest.java
- features/flows/classification/engine/src/test/java/org/opennms/netmgt/flows/classification/provider/StaticClassificationRuleProviderTest.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java
* JIRA: https://issues.opennms.org/browse/HZN-1237
> HZN-1237: Improve classification and gather more statistics

- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/IndexStrategyFactoryTest.java
* JIRA: https://issues.opennms.org/browse/HZN-1240
> HZN-1240: Fix case-sensitive IndexStrategyFactory

- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/JmxDataCollectionConfigResourceIT.java
* JIRA: http://issues.opennms.org/browse/hzn-1220
> hzn-1220: fix failing test

- features/jdbc-collector/pom.xml
- features/poller/monitors/core/pom.xml
- opennms-provision/opennms-detector-jdbc/pom.xml
Allow any jdbc drivers to load in jdbc detector/poller/collector
* JIRA: http://issues.opennms.org/browse/nms-9829
> NMS-9829: Allow any jdbc drivers to load in jdbc detector/poller/collector

- opennms-assemblies/remote-poller-nsis/remote-poller.nsi
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-doc/src/asciidoc/index.adoc
- opennms-doc/guide-install/src/asciidoc/index.adoc
- opennms-doc/guide-user/src/asciidoc/index.adoc
- opennms-doc/releasenotes/src/asciidoc/common/copyright.adoc
- opennms-doc/releasenotes/src/asciidoc/common/preface.adoc
- opennms-doc/releasenotes/src/asciidoc/index.adoc
- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/support/about.jsp
* JIRA: http://issues.opennms.org/browse/NMS-9871
> Fix NMS-9871: Copyright dates need a bump for 2018

- opennms-base-assembly/src/main/filtered/bin/opennms-thread-dump
* JIRA: http://issues.opennms.org/browse/NMA-9872
> Fix glob-quoting problem in find invocation

- features/flows/feature/pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-9865
> NMS-9865: Add missing dependency to features.xml

- core/web-assets/src/main/assets/js/apps/onms-classifications/index.js
- core/web-assets/src/main/assets/js/apps/onms-classifications/views/index.html
- smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java
This PR addresses a few minor fixes in the Classification UI.
As they are so minor, I grouped them all together in one PR, separated by commits.
JIRA:
* https://issues.opennms.org/browse/NMS-9878
* https://issues.opennms.org/browse/NMS-9879
* https://issues.opennms.org/browse/NMS-9880
* https://issues.opennms.org/browse/NMS-9883
> NMS-9878, NMS-9879, NMS-9880, NMS-9883: Various Classification UI fixes

- opennms-webapp/src/main/resources/org/opennms/web/controller/navbar.ftl
Fix for https://issues.opennms.org/browse/NMS-9867
> NMS-9867 Inconsistent handling of keyboard navigation on top menu

- features/telemetry/common/pom.xml
- features/telemetry/listeners/flow/src/main/java/org/opennms/netmgt/telemetry/listeners/flow/ipfix/TcpListener.java
* JIRA: http://issues.opennms.org/browse/HZN-1253
> HZN-1253: Fix error setting up IPFIX / Netflow 9 listeners

- opennms-doc/guide-admin/src/asciidoc/text/minion/aws-sqs.adoc
* JIRA: http://issues.opennms.org/browse/NMS-9870
> NMS-9870: Admin guide needs updating for SQS parameters on sink and rpc queues

- integrations/opennms-jasperstudio-extension/pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-9915
> NMS-9915: Add missing dependencies

- core/web-assets/src/main/assets/js/apps/add-to-ksc/index.js
- features/flows/rest/api/src/main/java/org/opennms/netmgt/flows/rest/FlowRestService.java
- features/flows/rest/api/src/main/java/org/opennms/netmgt/flows/rest/model/FlowGraphUrlInfo.java
- features/flows/rest/impl/src/main/java/org/opennms/netmgt/flows/rest/internal/FlowRestServiceImpl.java
- features/flows/rest/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceSnmpResourceType.java
- opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5/interface.adoc
- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
Add icon whenever we have flows for the specific interface.
* JIRA: http://issues.opennms.org/browse/hzn-1227
> HZN-1227:  Drift: Flow indicator icon on MIB-2 traffic utilization graphs

- opennms-base-assembly/src/main/filtered/etc/datacollection/cisco.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cisco-graph.properties
* JIRA: http://issues.opennms.org/browse/NMS-9887
> NMS-9887: Update Cisco ASA systemDefs with Cisco remote-access group

- opennms-base-assembly/src/main/filtered/etc/events/Cisco.events.xml
* JIRA: http://issues.opennms.org/browse/NMS-9890
> NMS-9890: Pair Cisco FRU removal/insertion traps as self-clearing alarms

- core/schema/src/main/liquibase/foundation-2017/changelog.xml
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAssetRecord.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AssetRecordResource.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/rest/AbstractNodeRestServiceTest.java
- smoke-test/src/test/java/org/opennms/smoketest/rest/NodeRestServiceV1IT.java
- smoke-test/src/test/java/org/opennms/smoketest/rest/NodeRestServiceV2IT.java
* JIRA: https://issues.opennms.org/browse/NMS-9855
> NMS-9855: Fix asset record not having a node id when created via REST

- features/telemetry/listeners/flow/src/main/java/org/opennms/netmgt/telemetry/listeners/flow/AbstractUdpListener.java
- features/telemetry/listeners/flow/src/main/java/org/opennms/netmgt/telemetry/listeners/flow/ipfix/TcpListener.java
- features/telemetry/listeners/udp/src/main/java/org/opennms/netmgt/telemetry/listeners/udp/UdpListener.java
* JIRA: http://issues.opennms.org/browse/HZN-1253
> HZN-1253: Bind listeners to any IPv4/IPv6 address depending on system config

- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: https://issues.opennms.org/browse/HZN-1274
> HZN-1274: Do not expose FlowRepository to jetty classpath

- core/web-assets/src/main/assets/js/apps/add-to-ksc/index.js
- core/web-assets/src/main/assets/js/apps/angular-status/index.js
- core/web-assets/src/main/assets/js/apps/forecast/index.js
- core/web-assets/src/main/assets/js/apps/geomap-js/index.js
- core/web-assets/src/main/assets/js/apps/ksc-wizard/index.js
- core/web-assets/src/main/assets/js/apps/onms-assets/index.js
- core/web-assets/src/main/assets/js/apps/onms-elementList/lib/restResources.js
- core/web-assets/src/main/assets/js/apps/onms-interfaces/onms-interfaces-app/index.js
- core/web-assets/src/main/assets/js/apps/onms-interfaces/onms-interfaces-config/index.js
- core/web-assets/src/main/assets/js/apps/onms-requisitions/quickaddnode/main.js
- core/web-assets/src/main/assets/js/apps/onms-requisitions/requisitions-core/index.js
- core/web-assets/src/main/assets/js/apps/onms-requisitions/requisitions/main.js
- core/web-assets/src/main/assets/js/apps/onms-resources/index.js
- core/web-assets/src/main/assets/js/apps/search/index.js
- core/web-assets/src/main/assets/js/apps/status-box/index.js
- core/web-assets/src/main/assets/js/lib/onms-http/index.js
- features/springframework-security/src/main/java/org/opennms/web/springframework/security/XRequestedWithAwareBasicAuthEntryPoint.java
- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
- smoke-test/src/test/java/org/opennms/smoketest/rest/XRequestedWithRestIT.java
This is a new version of @mvrueden's PR updated to match the latest JS changes.
* JIRA: http://issues.opennms.org/browse/NMS-9783
> NMS-9783: Include X-RequestedWith header for all  requests

- opennms-webapp/src/main/webapp/includes/help-documentation.jsp
- smoke-test/src/test/java/org/opennms/smoketest/HelpPageIT.java
Add Admin guide to help page for offline and online usage.
* JIRA: http://issues.opennms.org/browse/HZN-1271
> HZN-1271: Add admin guide to help page

- features/opennms-es-rest/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
While I worked on HZN-1249, I changed the `EventToIndex` class to use the `BulkRequest` and also the same implementation as the `FlowRepository`. While changing the code, I forgot to delete some (now) unused methods. This PR does that, sorry I missed it before.
* JIRA: https://issues.opennms.org/browse/HZN-1249
> HZN-1249: Remove unused code

- features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/index/IndexStrategy.java
* JIRA: http://issues.opennms.org/browse/HZN-1277
> HZN-1277: Correct typo in IndexStrategy

- features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/executors/DefaultRequestExecutor.java
* JIRA: https://issues.opennms.org/browse/NMS-9920
Must be merged after HZN-1249 (PR https://github.com/OpenNMS/opennms/pull/1872), as it depends on those changes.
> NMS-9920: Prevent Stack Overflow by implementing retry iterative vs recursive

- features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/index/IndexStrategy.java
- features/jest/client/src/test/java/org/opennms/plugins/elasticsearch/rest/index/IndexStrategyTest.java
* JIRA: https://issues.opennms.org/browse/HZN-1278
> HZN-1278: Calculate index using UTC instead of local time

- core/web-assets/webpack.config.js
This PR fixes some Windows-specific issues with path handling in the webpack build.
* JIRA: http://issues.opennms.org/browse/NMS-9942
> NMS-9942: use path-agnostic APIs

- smoke-test/src/main/java/org/opennms/smoketest/junit/LoggingRule.java
- smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1289
> HZN-1289: Make test execution more reliable

- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowDocumentTest.java
- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/AbstractAdapter.java
* JIRA: https://issues.opennms.org/browse/HZN-1293
> HZN-1293: Remove converter from FlowRepository and do conversion before

- features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/AlarmChangeNotificationClient.java
- features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/MemosChangeNotificationClient.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Value.java
- features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
- features/opennms-es-rest/main-module/src/main/resources/OSGI-INF/blueprint/mainModuleBlueprint.xml
- features/opennms-es-rest/main-module/src/main/resources/eventsIndexTemplate.json
- features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/AlarmEventToIndexTest.java
- features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/EventToIndexTest.java
- opennms-doc/guide-admin/src/asciidoc/text/plugins/opennms-es-rest.adoc
Jira: 
* https://issues.opennms.org/browse/NMS-9831
* https://issues.opennms.org/browse/HZN-1272
When this is merged to `release-21.1.0` all changes should be dropped when `develop` is merged to `features/drift` as they have been made there already.
> NMS-9831,HZN-1272: Handle OID event parameter keys and JSON event parameter values correctly

- integrations/opennms-jasperstudio-extension/pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-9915
> NMS-9915: Add missing spring-tx jar and remove duplicate spring-aop

- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/index/IndexSelector.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/index/IndexSelectorTest.java
- features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/index/IndexStrategy.java
- features/jest/client/src/test/java/org/opennms/plugins/elasticsearch/rest/executors/DefaultRequestExecutorIT.java
- features/jest/client/src/test/java/org/opennms/plugins/elasticsearch/rest/index/IndexStrategyTest.java
- features/opennms-es-rest/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
- features/opennms-es-rest/src/test/java/org/opennms/plugins/elasticsearch/rest/ClientRecoveryTest.java
JIRA: https://issues.opennms.org/browse/HZN-1296
> HZN-1296: Fix thread safety with date formatter used by the IndexStrategy 

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-doc/guide-admin/src/asciidoc/text/webui/grafana-dashboard-box.adoc
- opennms-webapp/src/main/webapp/includes/grafana-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9916
> NMS-9916: Added org.opennms.grafanaBox.basePath property

- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/index/IndexSelector.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/index/IndexSelectorTest.java
* JIRA: https://issues.opennms.org/browse/HZN-1298
> HZN-1298 Make time padding for IndexSelector configurable

- core/web-assets/src/main/assets/js/apps/onms-interfaces/onms-interfaces-app/index.js
- core/web-assets/src/main/assets/js/apps/onms-interfaces/templates/template.main.html
- core/web-assets/src/main/assets/js/apps/onms-resources/index.js
- opennms-webapp/src/main/webapp/graph/chooseresource.jsp
- opennms-webapp/src/main/webapp/graph/index.jsp
If resources are waiting to be loaded specify that instead of showing zero resources which could be misleading
* JIRA: http://issues.opennms.org/browse/NMS-9932
> NMS-9932: Fix wrong message displayed on AngularJS based tables.

- features/ncs/ncs-northbounder/src/main/java/org/opennms/netmgt/ncs/northbounder/NCSNorthbounder.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitor.java
- opennms-alarms/http-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/http/HttpNorthbounder.java
- opennms-util/pom.xml
- opennms-util/src/main/java/org/opennms/core/utils/http/HttpResponseRange.java
* JIRA: https://issues.opennms.org/browse/NMS-9882
>  NMS-9882 PageSequenceMonitor broken in Minion

- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/DashletSpecEditor.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/WallboardConfigView.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/WallboardEditor.java
- features/vaadin-dashlets/dashlet-surveillance/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/SurveillanceDashlet.java
- smoke-test/src/main/java/org/opennms/smoketest/AbstractPage.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/DashletBuilder.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/DashletConfig.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-9678
> NMS-9678: Fix surveillance url in ops board

- opennms-model/src/main/java/org/opennms/netmgt/model/topology/BroadcastDomain.java
- opennms-services/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
* JIRA: https://issues.opennms.org/browse/NMS-9852
> NMS-9852: Fixed NPE in debug code

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
* JIRA: http://issues.opennms.org/browse/NMS-10067
> NMS-10067: Enhance AlarmPersisterImpl to support updating acknowledgment values on reduction

- opennms-webapp/src/main/webapp/geomap/includes/map.jsp
* JIRA: http://issues.opennms.org/browse/NMS-10008
> NMS-10008: Add missing IP_Address placeholder (Foundation-2017)

- opennms-webapp/src/main/webapp/geomap/js/geomap.js
* JIRA: https://issues.opennms.org/browse/NMS-9945
> NMS-9945: Set MaxZoom of Geomap to 18 (foundation-2017)

- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Conversation.java
- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java
- features/flows/rest/impl/src/main/java/org/opennms/netmgt/flows/rest/internal/FlowRestServiceImpl.java
JIRA: https://issues.opennms.org/browse/HZN-1302
Here we update the flow conversation related REST endpoint to also include the application name when returning details about the conversations.
> HZN-1302: Include the application name when rendering conversations.

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java
- opennms-model/src/main/java/org/opennms/netmgt/model/events/NodeLabelChangedEventBuilder.java
- opennms-model/src/test/java/org/opennms/netmgt/model/events/NodeLabelChangedEventBuilderTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/PollerEventProcessor.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java
- opennms-webapp/src/main/java/org/opennms/web/nodelabel/NodeLabelChangeServlet.java
- tests/mock-elements/src/main/java/org/opennms/netmgt/mock/MockNode.java
* JIRA: https://issues.opennms.org/browse/NMS-9900
* replaces: https://github.com/OpenNMS/opennms/pull/1959
Our continuous integration system will test and verify your changes.
> NMS-9900 Value of ${nodeLabel} for PSM services apparently not eagerly updated

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
* JIRA: https://issues.opennms.org/browse/NMS-9938
> NMS-9938: Fixed favorite links to provide AddRefreshHeader-30

- features/alarm-change-notifier/pg-jdbc-utils/src/main/java/org/opennms/plugins/com/impossibl/postgres/jdbc/TimestampUtils.java
- features/alarm-change-notifier/pg-jdbc-utils/src/test/java/org/opennms/plugins/com/impossibl/postgres/jdbc/TimestampUtilsTest.java
* JIRA: https://issues.opennms.org/browse/HZN-1282
> HZN-1282  AlarmChangeNotificationClient - Unable to parse time value

- features/datachoices/src/main/resources/web/modal.ftl.html
* JIRA: http://issues.opennms.org/browse/NMS-10169
> NMS-10169: Link to privacy policy from Data Choices UI elements

- opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
* https://issues.opennms.org/browse/NMS-10148
> NMS-10148: wrong statement in event description for serviceDeleted

- container/features/src/main/resources/features.xml
- core/ipc/sink/kafka-impl/pom.xml
- core/test-api/kafka/pom.xml
- opennms-doc/guide-admin/src/asciidoc/text/minion/kafka.adoc
* JIRA: http://issues.opennms.org/browse/NMS-10165
> NMS-10165: Consolidate Kafka client library versions

- core/test-api/rest/src/main/java/org/opennms/core/test/rest/AbstractSpringJerseyRestTestCase.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AssetRecordResource.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/AssetRecordResourceIT.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10087
> NMS-10087: Asset record is not being updated with user name that performed the update

- core/schema/src/main/liquibase/23.0.0/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowRepository.java
- features/flows/elastic/pom.xml
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
- features/flows/rest/api/src/main/java/org/opennms/netmgt/flows/rest/FlowRestService.java
- features/flows/rest/impl/src/main/java/org/opennms/netmgt/flows/rest/internal/FlowRestServiceImpl.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.ncs/src/test/java/org/opennms/features/topology/plugins/ncs/MockNodeDao.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-base-assembly/src/main/filtered/etc/database-schema.xml
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/NodeDao.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SnmpInterfaceDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockNodeDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockSnmpInterfaceDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java
- opennms-doc/guide-development/src/asciidoc/text/rest/flows.adoc
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsSnmpInterface.java
- opennms-webapp-rest/src/test/resources/v1/nodes.json
* JIRA: https://issues.opennms.org/browse/HZN-1280
> HZN-1280: Added cache for flow exporters and their interfaces

- core/schema/src/main/liquibase/23.0.0/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/SituationIT.java
- opennms-base-assembly/src/main/filtered/etc/create.sql
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java
- opennms-model/src/main/java/org/opennms/netmgt/model/Situation.java
* JIRA: http://issues.opennms.org/browse/HZN-1318
Situations allow for roll up or correlation of multiple alarms.
> HZN-1318: Database model for Alarm Situations

- dependencies/drools/pom.xml
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/Event.java
JIRA: https://issues.opennms.org/browse/NMS-9923
Add KIE dependencies required by the 7.x release series.
Avoid a ConcurrentModificationException in org.opennms.features.events.api.
> NMS-9923: Upgrade Drools to 7.7.0.FINAL

- features/vaadin-dashlets/dashlet-ksc/pom.xml
- features/vaadin-dashlets/dashlet-ksc/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/KscDashlet.java
- features/vaadin-dashlets/dashlet-ksc/src/test/java/org/opennms/features/vaadin/dashboard/dashlets/KscDashletTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10191
> NMS-10191: The KSC Dashlet for the Ops-Board is not working

- container/karaf/src/main/filtered-resources/etc/custom.properties
- features/poller/shell/src/main/java/org/opennms/netmgt/filters/shell/FilterCommand.java
- opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/polling-packages.adoc
* JIRA: http://issues.opennms.org/browse/NMS-10172
> NMS-10172: Add karaf shell command for filtering nodes/interfaces

- features/events/api/src/main/java/org/opennms/netmgt/xml/event/AlarmData.java
- features/rest/mapper/src/main/java/org/opennms/web/rest/mapper/v2/AlarmMapper.java
- features/rest/mapper/src/test/java/org/opennms/web/rest/mapper/v2/AlarmMapperTest.java
- features/rest/mapper/src/test/resources/situation.16.dto.json
- features/rest/mapper/src/test/resources/situation.16.dto.xml
- features/rest/model/src/main/java/org/opennms/web/rest/model/v2/AlarmDTO.java
- features/rest/model/src/main/java/org/opennms/web/rest/model/v2/AlarmSummaryDTO.java
- opennms-model/src/main/java/org/opennms/netmgt/model/AckType.java
AlarmDTO is updated and a new AlarmSummaryDTO is added to transfer related alarms  of the Situation.
* JIRA: https://issues.opennms.org/browse/HZN-1327
> HZN-1327 Expose Situations via REST API

- features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/AbstractAdapter.java
* JIRA: https://issues.opennms.org/browse/HZN-1336
> HZN-1336: Fix packet logging issue

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-webapp/src/main/java/org/opennms/web/tags/DateTimeTag.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/taglib.tld
- opennms-webapp/src/main/webapp/admin/sysconfig.jsp
- opennms-webapp/src/test/java/org/opennms/web/tags/DateTimeTagTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10229
This PR replaces https://github.com/OpenNMS/opennms/pull/2028 since the task was broken down in smaller sub tasks
> NMS-10229: write custom tag for date time formatting

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-webapp/src/main/java/org/opennms/web/tags/DateTimeTag.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/distributed/locationMonitorDetails.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/distributed/locationMonitorList.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/notification/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/interfaceOutages-box.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/nodeOutages-box.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/serviceOutages-box.jsp
- opennms-webapp/src/main/webapp/includes/eventlist.jsp
- opennms-webapp/src/main/webapp/includes/header.jsp
- opennms-webapp/src/main/webapp/notification/detail.jsp
- opennms-webapp/src/main/webapp/rtc/category.jsp
- opennms-webapp/src/test/java/org/opennms/web/tags/DateTimeTagTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10230
* part of NMS-10072: Normalize date formats across the WebUI
* replaces https://github.com/OpenNMS/opennms/pull/2037 (the code is the same but this is a clean version with only the relevant commits)
> NMS-10230: replace current formatting in JSPs by custom tag

- features/container/sentinel/src/assembly/sentinel.xml
- features/container/sentinel/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- features/sentinel/runInPlace.sh
- tools/packages/sentinel/sentinel.spec
JIRA: https://issues.opennms.org/browse/HZN-1341
> HZN-1341: Remove karaf-extender from sentinel

- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java
- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/StressCommand.java
- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/shell/adhoc-collection.adoc
* JIRA: http://issues.opennms.org/browse/NMS-10173
> NMS-10173: Optionally persist the results when calling collectors:collect

- features/distributed/dao-api/pom.xml
- features/distributed/dao-impl/pom.xml
- features/distributed/dao-test/pom.xml
- features/distributed/dao-test/src/main/java/org/opennms/netmgt/dao/DaoServiceTester.java
- features/distributed/dao-test/src/main/java/org/opennms/netmgt/dao/ServiceHolder.java
- features/distributed/dao-test/src/main/java/org/opennms/netmgt/dao/TestRegistry.java
- features/distributed/dao-test/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/distributed/pom.xml
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmStatisticsService.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/StatisticsService.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/stats/AbstractBaseStatisticsService.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/stats/DefaultAlarmStatisticsService.java
- opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
- opennms-dao/src/main/resources/META-INF/opennms/applicationContext-shared.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AlarmStatsRestService.java
- smoke-test/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/sentinel/DaoIT.java
- smoke-test/src/test/resources/sentinel/features-dao.xml
- tests/dao/src/test/java/org/opennms/netmgt/dao/stats/AlarmStatisticsServiceTest.java
* JIRA: https://issues.opennms.org/browse/HZN-1342
> HZN-1342: Verify that all exposed DAO run in sentinel container

- opennms-doc/asciidoctor-default.css
- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/LdapMonitor.adoc
- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/NtpMonitor.adoc
- pom.xml
Update the asciidoctor dependency from 1.5.6 to 1.5.7. Requires also to bump the JRuby dependency from 9.0.4.0 to 9.1.16.0. Also updated the asciidoctor default stylesheet using Roboto / Roboto Mono fonts.
* JIRA: http://issues.opennms.org/browse/NMS-10255
> NMS-10255: Updated asciidoctor 1.5.6 -> 1.5.7 and stylesheet

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehaviors.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperty.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/SearchPropertiesIT.java
This PR adds a CriteriaBehaviour to handle requests to the REST API for alarms that are situations.
It introduces a boolean type of searchPropertyType
* JIRA: https://issues.opennms.org/browse/HZN-1350
> HZN-1350: Intercept and handle requests for Alarm.isSituation

- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/Actor.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/AppInitiator.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/AppTarget.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/AsPathType.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/Context.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/CounterRecord.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/Extended80211Aggregation.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedBstEgressQueue.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedDecapsulateIngress.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedGateway.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedMplsLdpFec.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedVlantunnel.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedVniEgress.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/ExtendedVniIngress.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/FlowRecord.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/HostAdapter.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/HostAdapters.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/PortName.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/Record.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/SampleRecord.java
- features/telemetry/listeners/sflow/src/test/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/CounterRecordWriteTest.java
- features/telemetry/listeners/sflow/src/test/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/flows/FlowRecordWriteTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10240
> NMS-10240: Fixed Bson serialization and added tests

- core/lib/src/main/java/org/opennms/core/time/CentralizedDateTimeFormat.java
- core/lib/src/test/java/org/opennms/core/time/CentralizedDateTimeFormatTest.java
- opennms-taglib/pom.xml
- opennms-taglib/src/main/java/org/opennms/web/tags/DateTimeTag.java
- opennms-taglib/src/test/java/org/opennms/web/tags/DateTimeTagTest.java
- opennms-webapp/src/main/java/org/opennms/web/controller/NavBarController.java
- opennms-webapp/src/main/resources/org/opennms/web/controller/navbar.ftl
* JIRA: https://issues.opennms.org/browse/NMS-10239
replaces: https://github.com/OpenNMS/opennms/pull/2036 
> NMS-10239: apply centralized datetime rendering to freemarker template(s)

- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/SnmpConfig.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/trapd/TrapdConfiguration.java
- opennms-config-jaxb/src/main/resources/xsds/trapd-configuration.xsd
- opennms-config-jaxb/src/test/java/org/opennms/netmgt/config/snmp/SnmpConfigTest.java
- opennms-config-jaxb/src/test/java/org/opennms/netmgt/config/trapd/TrapdConfigurationTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpPeerFactoryTest.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/SnmpConfigRestServiceIT.java
* JIRA: http://issues.opennms.org/browse/NMS-10242
> NMS-10242: Add Validation for Trapd, Snmp configs.

- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/OutlierFilter.java
- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/Percentile.java
* JIRA: https://issues.opennms.org/browse/HZN-1363
Changes the max value in the descriptions of `quantile` from 100 to 1, to match the actual implementation.
> HZN-1363: fix quantile descriptions

- core/lib/src/main/java/org/opennms/core/time/CentralizedDateTimeFormat.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/users/TimeZoneIdAdapter.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/users/User.java
- opennms-config-model/src/main/resources/xsds/users.xsd
- opennms-config-model/src/test/java/org/opennms/netmgt/config/users/TimeZoneIdAdapterTest.java
- opennms-taglib/src/main/java/org/opennms/web/tags/DateTimeTag.java
- opennms-taglib/src/test/java/org/opennms/web/tags/DateTimeTagTest.java
- opennms-webapp/src/main/java/org/opennms/web/account/UserSettingsFilter.java
- opennms-webapp/src/main/java/org/opennms/web/admin/users/UpdateUserServlet.java
- opennms-webapp/src/main/java/org/opennms/web/controller/NavBarController.java
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
- opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp
* JIRA: https://issues.opennms.org/browse/NMS-10228
> NMS-10228:  use user defined time zone for date formatting

- features/flows/elastic/pom.xml
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/Direction.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DefaultDirectionIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10221
> NMS-10221: Added default direction and test

- integrations/opennms-vmware/pom.xml
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePool.java
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePoolEntry.java
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/vmware/VmwareViJavaAccessTest.java
- integrations/opennms-vmware/src/test/java/org/opennms/protocols/vmware/ServiceInstancePoolTest.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: http://issues.opennms.org/browse/NMS-8204
> NMS-8204: Reusing existing VMware session getting data

- features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationRequest.java
- features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationRequestBuilder.java
- features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineTest.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DocumentEnricherTest.java
- features/telemetry/listeners/sflow/src/main/java/org/opennms/netmgt/telemetry/listeners/sflow/proto/headers/EthernetHeader.java
* JIRA: https://issues.opennms.org/browse/HZN-1329
> HZN-1329: Fixed some SFlow exceptions

- features/telemetry/distributed/sentinel/pom.xml
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterHealthCheck.java
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterManager.java
- features/telemetry/distributed/sentinel/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- smoke-test/src/test/java/org/opennms/smoketest/health/HealthCheckIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1370
> HZN-1370: Provide simple health check mechanism for configured adapters

- opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/LdapMonitor.java
* JIRA: http://issues.opennms.org/browse/NMS-8891
> NMS-8891: Fix Ldap error log entries GLPSRV044W triggered by LdapMonitor

- opennms-doc/guide-admin/src/asciidoc/text/notifications/getting-started.adoc
Cyrille Bollu
* JIRA: https://issues.opennms.org/browse/NMS-10275
> NMS-10275: Updated notifd documentation about the match-all parameter

- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogConfigBean.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogReceiver.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogReceiverCamelNettyImpl.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogReceiverJavaNetImpl.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/Syslogd.java
- features/events/syslog/src/main/resources/META-INF/opennms/applicationContext-syslogDaemon.xml
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogClient.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogReloadDaemonIT.java
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdTestUtils.java
- features/events/syslog/src/test/resources/opennms-home-reload/etc/syslogd-configuration.xml
- features/events/syslog/src/test/resources/opennms-home/etc/syslogd-configuration.xml
- opennms-config/src/main/java/org/opennms/netmgt/config/SyslogdConfig.java
* JIRA: http://issues.opennms.org/browse/NMS-10252
> NMS-10252: Update Syslogd to respond to reload configuration events

- opennms-doc/releasenotes/src/asciidoc/releasenotes/changelog-15.adoc
- opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/radius.xml.disabled
- protocols/radius/pom.xml
- protocols/radius/src/main/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProvider.java
- protocols/radius/src/test/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProviderIT.java
- protocols/radius/src/test/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProviderTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10212
> NMS-10212: Do not reuse RadiusAuthenticator in RadiusAuthenticationProvider

- features/telemetry/distributed/minion/src/main/java/org/opennms/netmgt/telemetry/distributed/minion/ListenerManager.java
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterManager.java
* JIRA: https://issues.opennms.org/browse/HZN-1372
> HZN-1372: Fix ConcurrentModificationException

- core/schema/src/main/liquibase/foundation-2018/changelog.xml
- opennms-base-assembly/src/main/filtered/etc/create.sql
* JIRA: https://issues.opennms.org/browse/NMS-10293
> NMS-10293: use ifregainedservice to identify ongoing outages

- core/health/api/src/main/java/org/opennms/core/health/api/SimpleHealthCheck.java
- features/telemetry/distributed/minion/pom.xml
- features/telemetry/distributed/minion/src/main/java/org/opennms/netmgt/telemetry/distributed/minion/ListenerHealthCheck.java
- features/telemetry/distributed/minion/src/main/java/org/opennms/netmgt/telemetry/distributed/minion/ListenerManager.java
- features/telemetry/distributed/minion/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterHealthCheck.java
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterManager.java
- smoke-test/src/test/java/org/opennms/smoketest/health/HealthCheckIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1371
> HZN-1371: Expose HealthCheck for Listeners when starting them on Minion

- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java
- features/events/traps/src/main/java/org/opennms/netmgt/trapd/Trapd.java
- features/events/traps/src/main/resources/META-INF/opennms/applicationContext-trapDaemon.xml
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdConfigReloadIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdReloadDaemonIT.java
- features/events/traps/src/test/resources/trapd/etc/trapd-configuration.xml
* JIRA: http://issues.opennms.org/browse/NMS-10305
> NMS-10305: Handle Trapd reload daemon/config

- opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/95thPercentileTrafficRate_subreport.jrxml
* JIRA: https://issues.opennms.org/browse/NMS-9875
> NMS-9875: Added flag to ignore duplicate keys

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors/HttpDetector.adoc
- opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors/HttpsDetector.adoc
* JIRA: https://issues.opennms.org/browse/NMS-3974
> NMS-3974: maxRetCode in HttpDetector does not work

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/CompositeKey.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/CompositeKeyTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProviderTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10317
Please do not merge yet, I first want to verify that the test makes sense. Once we are happy with it we can remove the old code.
> NMS-10317 : Improve CDP topology calculation performance

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MinionRestService.java
- opennms-webapp/src/main/webapp/js/angular-onms-elementList-minion.js
- opennms-webapp/src/main/webapp/minion/main.html
* JIRA: https://issues.opennms.org/browse/NMS-10321
> NMS-10321: Added button to delete a minion

- container/features/src/main/resources/features.xml
- container/spring-extender/pom.xml
- container/spring-extender/src/main/java/org/opennms/netmgt/shared/bootstrap/Activator.java
- core/ipc/sink/camel/itests/src/test/java/org/opennms/core/ipc/sink/camel/itests/HeartbeatSinkBlueprintIT.java
- core/ipc/sink/camel/itests/src/test/java/org/opennms/core/ipc/sink/camel/itests/HeartbeatSinkPerfIT.java
- features/distributed/core/jms/pom.xml
- features/distributed/core/jms/src/main/java/org/opennms/distributed/jms/impl/JmsConnectionHealthCheck.java
- features/distributed/core/jms/src/main/java/org/opennms/distributed/jms/impl/ScvEnabledActiveMQConnectionFactory.java
- features/distributed/core/jms/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/distributed/core/shell/pom.xml
- features/distributed/dao/impl/pom.xml
- features/distributed/dao/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/distributed/datasource/pom.xml
- features/distributed/datasource/src/main/java/org/opennms/netmgt/distributed/datasource/ConfigFactory.java
- features/distributed/datasource/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/sentinel/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/telemetry/distributed/common/src/main/java/org/opennms/netmgt/telemetry/distributed/common/MapBasedProtocolDef.java
- features/telemetry/distributed/sentinel/src/main/java/org/opennms/netmgt/telemetry/distributed/sentinel/AdapterManager.java
- opennms-dao/src/main/resources/META-INF/opennms/applicationContext-shared.xml
- pom.xml
* JIRA: https://issues.opennms.org/browse/HZN-1373
> HZN-1373: Sentinel Cleanup

- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DocumentEnricherTest.java
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java
* JIRA: https://issues.opennms.org/browse/NMS-10329
> NMS-10329: DocumentEnricher will not switch directions anymore

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
* JIRA: https://issues.opennms.org/browse/NMS-9747
> NMS-9747: Added interval to service.jsp page

- opennms-webapp/src/main/webapp/js/angular-onms-elementList-minion.js
- opennms-webapp/src/main/webapp/minion/main.html
This PR adds a query to the minion status page to retrieve node information for the listed minions, and it turns the ID into a link to the node page if the minion has an associated node.
* JIRA: http://issues.opennms.org/browse/NMS-10296
> NMS-10296: link to the node page if the minion has an associated node

- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
- features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/ProtoBufMapperTest.java
* JIRA: http://issues.opennms.org/browse/HZN-1385
> HZN-1385: Extend the Kafka Producer to expose related alarms for situations

- features/collection/core/src/main/java/org/opennms/netmgt/collection/core/DefaultCollectionAgentService.java
- features/collection/core/src/main/java/org/opennms/netmgt/collection/core/OsgiCollectionAgentFactory.java
- features/telemetry/distributed/sentinel/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: https://issues.opennms.org/browse/NMS-10340
> NMS-10340: Provide OSGi-friendly CollectionAgentFactory

- features/wsman/src/main/java/org/opennms/netmgt/provision/detector/wsman/WsManWQLDetector.java
- features/wsman/src/main/java/org/opennms/netmgt/provision/detector/wsman/WsManWQLDetectorFactory.java
- features/wsman/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors/wsmanwql.adoc
- smoke-test/src/test/java/org/opennms/smoketest/minion/DetectorsCommandIT.java
* Jira: https://issues.opennms.org/browse/NMS-9899
Add a new WsMan detector that can use WQL filters against an
endpoint to detect arbitrary services.
>  NMS-9899: Add a new WsMan WQL-based detector

- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/AlarmEqualityChecker.java
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/AlarmEqualityCheckerTest.java
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
* JIRA: http://issues.opennms.org/browse/HZN-1383
> HZN-1383: Fix for an issue where kafka producer alarm suppression would not work for situation alarms

- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePool.java
* JIRA: https://issues.opennms.org/browse/NMS-10373
> NMS-10373: Changed synchronization for ServiceInstancePool

- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
- opennms-webapp/src/main/webapp/element/node.jsp
- smoke-test/src/test/java/org/opennms/smoketest/EditInRequisitionIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10364
> NMS-10364: Link Node Page to Node Requisition

- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java
* JIRA: https://issues.opennms.org/browse/NMS-10367
> NMS-10367: Fix ttl issue with collection:collect karaf command

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
- opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/VmwareMonitor.adoc
* JIRA: https://issues.opennms.org/browse/NMS-10345
> NMS-10345: Added feature to report vSphere alarms in VmwareMonitor

- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/configuration.adoc
NMS-10387: class paths out of sync in documentation
* JIRA: http://issues.opennms.org/browse/NMS-10387
> NMS-10387 - fix class path in documentation.

- opennms-base-assembly/src/main/filtered/bin/opennms
* JIRA: http://issues.opennms.org/browse/NMS-10384
> NMS-10384: Set JVM flag to start Attach listener by default

- features/vaadin/pom.xml
- pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
- smoke-test/src/test/resources/topology/graphml/test-topology.xml
* JIRA: https://issues.opennms.org/browse/HZN-1333
> HZN-1333: "Change Icon" In Topology Map Fails

- features/events/api/pom.xml
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/AlarmData.java
- features/events/api/src/main/java/org/opennms/netmgt/xml/event/ManagedObject.java
- features/events/api/src/test/java/org/opennms/netmgt/xml/event/AlarmDataXmlTest.java
- features/events/api/src/test/java/org/opennms/netmgt/xml/event/ManagedObjectXmlTest.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/AlarmData.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/ManagedObject.java
- opennms-config-model/src/main/resources/xsds/eventconf.xsd
- opennms-config-model/src/test/java/org/opennms/netmgt/xml/eventconf/AlarmDataTest.java
- opennms-model/src/main/resources/xsds/event.xsd
* JIRA: http://issues.opennms.org/browse/HZN-1406
> HZN-1406: Add managed object type field in the alarm data

- opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/xml.adoc
- protocols/xml/src/main/java/org/opennms/protocols/http/HttpUrlConnection.java
- protocols/xml/src/main/java/org/opennms/protocols/xml/config/Request.java
- protocols/xml/src/test/java/org/opennms/protocols/xml/config/RequestTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10313
> NMS-10313 : Be able to use Proxy for any Monitor or Collector that uses HttpClient via UrlFactory

- opennms-doc/guide-admin/src/asciidoc/index.adoc
- opennms-doc/guide-admin/src/asciidoc/text/alarm-correlation/situation-feedback.adoc
- opennms-doc/guide-admin/src/asciidoc/text/elasticsearch/features/introduction.adoc
- opennms-doc/guide-admin/src/asciidoc/text/elasticsearch/features/situation-feedback.adoc
- opennms-doc/guide-development/src/asciidoc/index.adoc
- opennms-doc/guide-development/src/asciidoc/text/rest/situation-feedback.adoc
This PR adds documentation of the Situation Correlation Feedback feature to the docs.
It adds the requirement on Elasticsearch to the Admin Guide and it outlines the ReSR API in the Developer guide.
* JIRA: https://issues.opennms.org/browse/HZN-1379
> HZN-1379: Initial Documentation for Situation Feedback

- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
- opennms-services/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java
also add managedObject for eventconf
* JIRA: http://issues.opennms.org/browse/HZN-1401
> HZN-1401: Support correlation of alarms triggered by thresholds

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmDao.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmRepository.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockAlarmDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmRepositoryHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java
- opennms-model/src/main/java/org/opennms/netmgt/model/alarm/SituationSummary.java
- opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java
- opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java
- opennms-webapp/src/main/java/org/opennms/web/alarm/SortStyle.java
- opennms-webapp/src/main/java/org/opennms/web/alarm/filter/SituationFilter.java
- opennms-webapp/src/main/java/org/opennms/web/controller/situation/SituationBoxController.java
- opennms-webapp/src/main/java/org/opennms/web/filter/BooleanSqlType.java
- opennms-webapp/src/main/java/org/opennms/web/filter/SQLType.java
- opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/situation/summary-box.jsp
- opennms-webapp/src/main/webapp/includes/alarm-advquerypanel.jsp
- opennms-webapp/src/main/webapp/index.jsp
- opennms-webapp/src/test/java/org/opennms/web/alarm/AlarmRepositoryIT.java
- opennms-webapp/src/test/java/org/opennms/web/alarm/filter/AlarmRepositoryFilterIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1394
> HZN-1394: Added situation UI elements

- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1333
> HZN-1333:  "Change Icon" In Topology Map Fails

- core/ipc/common/kafka/src/main/java/org/opennms/core/ipc/common/kafka/KafkaHealthCheck.java
- core/ipc/sink/kafka/server/src/main/java/org/opennms/core/ipc/sink/kafka/server/offset/KafkaOffsetProvider.java
* JIRA: http://issues.opennms.org/browse/HZN-1387
> HZN-1387: Fix  SASL Authentication for Kafka  for sentinel 

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1398
> HZN-1398: Prevent cyclic graphs with situations

- core/daemon/src/main/java/org/opennms/netmgt/daemon/DaemonTools.java
- features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/PollerBackEndEventProcessor.java
- opennms-ackd/src/main/java/org/opennms/netmgt/ackd/Ackd.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/PollerEventProcessor.java
- opennms-services/src/main/java/org/opennms/netmgt/scriptd/Executor.java
- opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPoller.java
- opennms-services/src/main/java/org/opennms/netmgt/statsd/Statsd.java
- opennms-services/src/main/java/org/opennms/netmgt/tl1d/Tl1d.java
- opennms-services/src/main/java/org/opennms/netmgt/translator/EventTranslator.java
- opennms-services/src/main/java/org/opennms/netmgt/vacuumd/Vacuumd.java
- JIRA: https://issues.opennms.org/browse/NMS-10348
On demand I did not harmonize all the daemons to use the DaemonTools, since they will be rewritten soon
> NMS-10348: Force the daemons to send Success/Fail events upon config-reload

- opennms-doc/guide-admin/src/asciidoc/text/poller/monitors/BSFMonitor.adoc
* JIRA: http://issues.opennms.org/browse/NMS-10428
> NMS-10428: Typo in BSFMonitor Documentation

- opennms-webapp/src/main/webapp/admin/discovery/edit-config.jsp
- opennms-webapp/src/main/webapp/admin/discovery/edit-scan.jsp
* JIRA: http://issues.opennms.org/browse/NMS-10400
> NMS-10400: Discovery UI should not allow selection of Minions as Foreign Source name

- features/ticketing/api/src/main/java/org/opennms/api/integration/ticketing/RelatedAlarmSummary.java
- features/ticketing/api/src/main/java/org/opennms/api/integration/ticketing/Ticket.java
- features/ticketing/daemon/src/main/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayer.java
- features/ticketing/daemon/src/test/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayerIT.java
- features/ticketing/daemon/src/test/java/org/opennms/netmgt/ticketd/TestTicketerPlugin.java
- features/ticketing/daemon/src/test/resources/META-INF/opennms/applicationContext-test-troubleTicketer.xml
* JIRA: http://issues.opennms.org/browse/HZN-1404
> HZN-1404: Modify ticketing api for Situations

- opennms-base-assembly/src/main/filtered/bin/opennms
This is really only here to remember to merge once we've confirmed tests pass.
* JIRA: http://issues.opennms.org/browse/NMS-10437
> NMS-10437: bump MaxMetaspaceSize to 512m

- features/discovery/pom.xml
- features/discovery/src/test/java/org/opennms/netmgt/discovery/NewSuspectLocationTest.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.discovery.events.xml
* JIRA: https://issues.opennms.org/browse/HZN-814
> HZN-814: Added location to event description and logmsg

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.correlation.events.xml
- opennms-config/src/test/java/org/opennms/netmgt/config/EventconfFactoryIT.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
- opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/FusionRulesTest.java
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/droolsFusion/DroolsFusion.drl
For streaming case, we reload engine.
* JIRA: http://issues.opennms.org/browse/NMS-10363
> NMS-10363: Handle exceptions while running Drools rules.

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdSearchProvider.java
* JIRA: https://issues.opennms.org/browse/NMS-10445
> NMS-10445: Improve performance of node search

- features/topology-map/plugins/org.opennms.features.topology.plugins.netutils/src/main/java/org/opennms/features/topology/netutils/internal/operations/PingOperation.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.netutils/src/main/java/org/opennms/features/topology/netutils/internal/ping/PingForm.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.netutils/src/main/java/org/opennms/features/topology/netutils/internal/ping/PingRequest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.netutils/src/main/java/org/opennms/features/topology/netutils/internal/ping/PingWindow.java
* JIRA: https://issues.opennms.org/browse/NMS-10452
> NMS-10452: Performance improvement when building menus and vertices are selected

- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/NoContentAvailableWindow.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10453
> NMS-10453: Show message if empty list or null list was returned

- opennms-base-assembly/src/main/filtered/etc/datacollection/apc.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/apc-graph.properties
* JIRA: https://issues.opennms.org/browse/NMS-10383
> NMS-10383: APCs total RPDUs energy/power metric

- core/ipc/sink/kafka/server/src/main/java/org/opennms/core/ipc/sink/kafka/server/offset/KafkaOffsetProvider.java
* JIRA: http://issues.opennms.org/browse/NMS-10464
> NMS-10464: Mode debug logs to trace

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AcknowledgmentDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AcknowledgmentDaoIT.java
This PR add functionality to procedurally Clear related Alarms when Clearing a Situation.
This is required to prevent the Drools  context from reverting the Clear on the Situation.
* JIRA: https://issues.opennms.org/browse/HZN-1439
> HZN-1439: Clear related alarms when clearing a Situation

- opennms-doc/guide-admin/src/asciidoc/text/minion/offheap.adoc
* JIRA: http://issues.opennms.org/browse/NMS-10468
> NMS-10468: Fix offheap name from .doc to .adoc

- opennms-base-assembly/src/main/filtered/etc/org.opennms.features.topology.app.icons.list
- opennms-webapp/src/main/webapp/svg/opennms_icons.svg
JIRA: https://issues.opennms.org/browse/OCE-26
A couple new icons
> OCE-26: Add situation and interface icons.

- opennms-base-assembly/src/main/filtered/bin/opennms
* JIRA: https://issues.opennms.org/browse/HZN-1391
> HZN-1391: Added ssh command to bin/opennms script

- opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml
* JIRA: http://issues.opennms.org/browse/HZN-1408
Edit: Fixed url to issue (2018-11-28, @mvrueden)
> HZN-1408: Added example for multi-port listener to config

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
* JIRA: https://issues.opennms.org/browse/NMS-10462
> NMS-10462: Fixed last event time in alarm detail view

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10463
> NMS-10463: Show only situations with severity greater NORMAL on landing page

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/cassandra30x.xml
* JIRA: http://issues.opennms.org/browse/NMS-10420
> NMS-10420: Fix data type and attribute name for Cassandra Thread Pool metrics

- features/events/shell-commands/pom.xml
- features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
- features/events/shell-commands/src/test/java/org/opennms/netmgt/events/commands/StressCommandTest.java
* JIRA: https://issues.opennms.org/browse/NMS-10475
> NMS-10475: Include nodeId and interface in JexlEventGenerator

- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/GrokParserStageSequenceBuilder.java
- features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ParserStageSequenceBuilder.java
- features/events/syslog/src/main/resources/org/opennms/netmgt/syslogd/grok-patterns.txt
- features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java
- opennms-doc/guide-admin/src/asciidoc/text/events/sources/syslog.adoc
This PR enhances syslog message parsing to handle cases that were failing to parse in the field.
* JIRA: http://issues.opennms.org/browse/HZN-1440
> HZN-1440: Support syslog message parsing for messages found during audit

- features/vaadin-dashboard/pom.xml
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaBuilderHelper.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaRestriction.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaRestrictionComponent.java
- features/vaadin-dashboard/src/test/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaBuilderTest.java
- pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-10479
> NMS-10479: Fixed broken In-restriction

- debian/rules
- protocols/dhcp/pom.xml
- protocols/dhcp/src/assembly/lib.xml
- protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Client.java
- protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Message.java
- protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Poller.java
- protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Receiver.java
- protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Receiver2.java
- protocols/dhcp/src/test/java/org/opennms/protocols/dhcp/detector/DhcpDetectorTest.java
- tools/packages/opennms/opennms.spec
* JIRA: https://issues.opennms.org/browse/NMS-10337
> NMS-10337: Replaced jdhcp with dhcp4java

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdge.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProvider.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdVertex.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdMockDataPopulator.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdTopologyProviderTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProviderTest.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/resources/META-INF/opennms/applicationContext-enhanced-mock.xml
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/TopologyEntityCache.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/TopologyEntityDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/TopologyEntityCacheImpl.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/TopologyEntityDaoHibernate.java
- opennms-model/src/main/java/org/opennms/netmgt/model/IpInterfaceTopologyEntity.java
- opennms-model/src/main/java/org/opennms/netmgt/model/NodeTopologyEntity.java
- opennms-model/src/main/java/org/opennms/netmgt/model/SnmpInterfaceTopologyEntity.java
* JIRA: https://issues.opennms.org/browse/NMS-10459
> NMS-10459: improve performance of Interface loading and mapping

- opennms-base-assembly/src/main/filtered/etc/translator-configuration.xml
- opennms-config-model/src/main/java/org/opennms/netmgt/config/translator/Assignment.java
- opennms-config-model/src/main/resources/xsds/translator-configuration.xsd
- opennms-config/src/main/java/org/opennms/netmgt/config/EventTranslatorConfig.java
- opennms-config/src/main/java/org/opennms/netmgt/config/EventTranslatorConfigFactory.java
- opennms-services/src/main/java/org/opennms/netmgt/translator/EventTranslator.java
- opennms-services/src/test/java/org/opennms/netmgt/translator/EventTranslatorIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10495
> NMS-10495: Introduced 'default' attribute for settings fall-back values in event translator assignments

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/AlarmService.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/NaggingNotificationsIT.java
- opennms-base-assembly/src/main/filtered/etc/examples/alarmd/drools-rules.d/nag.drl
JIRA: https://issues.opennms.org/browse/HZN-1450
> HZN-1450: An example of how to generate "nag" events with alarms using Drools

- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/EventMatchers.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Mask.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Parameter.java
- opennms-config-model/src/main/resources/xsds/eventconf.xsd
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfMatcherTest.java
- opennms-config/src/test/resources/matcher-test.events.xml
This PR adds the ability to configure parameter keys and their values in the event mask for matching event config.
* JIRA: https://issues.opennms.org/browse/NMS-10465
> NMS-10465: Event Config matching on Paramter key and value

- container/features/src/main/resources/features.xml
- features/api-layer/pom.xml
- features/api-layer/src/main/java/org/opennms/features/apilayer/dao/AlarmFeedbackDaoImpl.java
- features/api-layer/src/main/java/org/opennms/features/apilayer/feedback/AlarmFeedbackListenerManager.java
- features/api-layer/src/main/java/org/opennms/features/apilayer/model/AlarmFeedbackBean.java
- features/api-layer/src/main/java/org/opennms/features/apilayer/utils/ModelMappers.java
- features/api-layer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
- features/situation-feedback/api/pom.xml
- features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/AlarmFeedback.java
- features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/FeedbackRepository.java
- features/situation-feedback/elastic/src/main/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepository.java
- features/situation-feedback/elastic/src/main/java/org/opennms/features/situationfeedback/elastic/FeedbackDocument.java
- features/situation-feedback/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/situation-feedback/elastic/src/test/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepositoryIT.java
- features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
- features/situation-feedback/rest/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/DefaultSessionUtils.java
- pom.xml
This PR adds support for passing alarm feedback through the integration API.
* JIRA: http://issues.opennms.org/browse/HZN-1433
> HZN-1433: Update integration api to handle alarm feedback without Kafka

- core/lib/src/main/java/org/opennms/core/utils/InetAddressUtils.java
- opennms-icmp/opennms-icmp-best/src/main/java/org/opennms/netmgt/icmp/best/BestMatchPingerFactory.java
This PR is a cherry-pick backport of the fixes for NMS-9659 I did for `foundation-2018`.
* JIRA: http://issues.opennms.org/browse/NMS-9659
****
> NMS-9659: fix BestMatchPinger to handle initialization more gracefully

- features/rest-provider/pom.xml
- features/rest-provider/src/main/java/org/opennms/web/rest/support/ErrorResponseProvider.java
* JIRA: https://issues.opennms.org/browse/HZN-1458
> HZN-1458: Ensure exceptions are logged properly

- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/info/BusinessServiceVertexStatusInfoPanelItemProvider.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/BSMTopologyIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10529
> NMS-10529: Fix Business Service Status panel not shown

- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/ui/HeaderLayout.java
- features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/ui/WallboardUI.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10515
> NMS-10515: Fixed navigator's view handling

- container/features/src/main/resources/features.xml
- features/events/shell-commands/pom.xml
- features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/EventConfigShowCommand.java
- features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/EventUeiCompleter.java
- opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc
- opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
JIRA: https://issues.opennms.org/browse/HZN-1461
Another Karaf shell command!
> HZN-1461: Add support for showing the XML of an event config in the Karaf shell

- opennms-doc/guide-admin/src/asciidoc/text/bsm/introduction.adoc
Hi,
This is small documentation update that doesn't require a JIRA issue imho.
Cheers,
Cyrille
> Fixed a typo in the BSM introduction documentation page

- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
- smoke-test/src/test/java/org/opennms/smoketest/AdminSnmpConfigForIpPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-10514
> NMS-10514: Select Default location instead of the first alphabetically

- features/bsm/shell-commands/src/main/java/org/opennms/netmgt/bsm/karaf/shell/DeleteGeneratedHierarchiesShellCommand.java
- features/bsm/shell-commands/src/main/java/org/opennms/netmgt/bsm/karaf/shell/GenerateHierarchiesShellCommand.java
- features/graph/api/src/main/java/org/opennms/netmgt/graph/api/service/GraphContainerProvider.java
- features/graph/api/src/main/java/org/opennms/netmgt/graph/api/service/GraphProvider.java
- features/graph/provider/bsm/src/main/java/org/opennms/netmgt/graph/provider/bsm/AbstractBusinessServiceVertex.java
- features/graph/provider/bsm/src/main/java/org/opennms/netmgt/graph/provider/bsm/BusinessServiceGraphProvider.java
- features/graph/provider/bsm/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/graph/service/pom.xml
- features/graph/service/src/main/java/org/opennms/netmgt/graph/service/GraphProviderManager.java
- features/graph/service/src/main/java/org/opennms/netmgt/graph/service/SingleGraphContainerProvider.java
- features/graph/service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- smoke-test/src/test/java/org/opennms/smoketest/graph/GraphProviderIT.java
* JIRA: https://issues.opennms.org/browse/HZN-1471
> HZN-1471: Add GraphProvider (or SingleGraphContainerProvider) support
