opennms-base-assembly/src/main/filtered/etc/thresholds.xml

JIRA: http://issues.opennms.org/browse/NMS-5085
This changes the threshold value for three relative change thresholds monitoring free disk space such that the thresholds now correctly monitor for a decrease of free space.
Todo Review:

NMS-5085: Fix relative change threshold for used instead of free disk space

---

opennms-doc/guide-admin/src/asciidoc/text/poller/DhcpMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/StrafePingMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/provisioning.adoc

- Added images path for screenshot to StrafePing
- Added images path for communication schema to DhcpMonitor
- Added images path for screenshots in Provisioning
JIRA: http://issues.opennms.org/browse/NMS-7284
Todo:

NMS-7284: Fix images path in admin guide for GitHub preview

---

opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/IpNetToMediaTableTracker.java
opennms-services/src/main/java/org/opennms/netmgt/linkd/snmp/IpNetToMediaTableEntry.java

java.lang.IllegalArgumentException: Cannot decode MAC address: ''
Method normalizeMacAddress can't handle empty values.
Each function calling normalizeMacAddress must handle invalid values before calling normalizeMacAddress.
JIRA: http://issues.opennms.org/browse/NMS-7358
Todo:

NMS-7358: IllegalArgument on ipnettomediatable

---

features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPlugin.java

The id field of org.opennms.api.integration.ticketing.Ticket object is updated with the JIRA issue id obtained
from the getIssueClient().createIssue call. Seems this was linking was missed out.
This allows the JIRA Issue id to appear in the Alarm Detail page. 
Once the JIRA issue id appears in the alarm page, I found that clicking on the Issue automatically leads me to the JIRA website issue page.
JIRA: http://issues.opennms.org/browse/NMS-7470
Todo:

NMS-7470: Update ticket.id  after creating a new JIRA issue

---

opennms-doc/guide-admin/pom.xml
opennms-doc/guide-development/pom.xml
opennms-doc/guide-doc/pom.xml
opennms-doc/guide-install/pom.xml
opennms-doc/guide-user/pom.xml
opennms-doc/releasenotes/pom.xml

- Set source document name in guide-admin
- Set source document name in guide-development
- Set source document name in guide-doc
- Set source document name in guide-install
- Set source document name in guide-user
- Set source document name in releasenotes
Each maven module generates only one index.html and one index.pdf and all other HTML and PDF files are removed.
JIRA: http://issues.opennms.org/browse/NMS-7579
Todo:

NMS-7579: Remove unnecessary output from opennms-doc modules

---

opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/DiskUsageMonitor.java
opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/DiskUsageMonitorTest.java

I've added a unit test for DiskUsageMonitor with a few test cases that all pass.
I've enhanced DiskUsageMonitor with a new parameter (require-type) that you can use to flag whether ALL or  ANY matches on the disk name must pass.
JIRA: http://issues.opennms.org/browse/NMS-7551
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-NMS257
Todo:

NMS-7551: DiskUsageMonitor never fails with a non existing disk

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilTest.java

Replacing PR 235 with a patch applied to the 15.0.2 release branch.

NMS-7529: Event replacement items that contain '%' characters can result in broken notification text sometimes

---

integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/resource/ResourceQuery.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/resource/ResourceQueryCommandParser.java
integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/resource/ResourceQueryParserTest.java

- Accepting arguments "--foreignsource" and "--foreignid" in
ResourceQuery.java and ResourceQueryCommandParser.java, get and
set functions
- If "storeByForeignSource" is not enabled the constructBasePath()
function returns the same as before (for compatibility reasons)
in ResourceQuery.java
- If "storeByForeignSource" is enabled the function
getNodeLevelResourceDirectory from the JRobinDirectoryUtil class
is called to return the node level resource directory. The
resource name is then appended to it in ResourceQuery.java
The contribution is made strictly by observation, I am not in anyway experiencing problems based on the storeByForeignSource functionality with Jasper reports. 
Todo:

Adding support for the "storeByForeignSource" feature of OpenNMS

---

opennms-services/src/main/java/org/opennms/netmgt/capsd/plugins/WebPlugin.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/WebMonitor.java

This adds parity (somewhat) to the WebDetector class in that is exposes a way to disable the default TrustManager so that self-signed or untrusted CA certificates can be accepted by the WebMonitor/WebPlugin.
JIRA: http://issues.opennms.org/browse/NMS-7514
Todo:

NMS-7514: Exposed "use-ssl-filter" for self-signed certs

---

opennms-services/src/main/java/org/opennms/netmgt/notifd/BSFNotificationStrategy.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/BSFMonitor.java

BSF performance has always been terrible since scripts are compiled and executed fresh each time. These patches will allow BSF engines that cache to actually cache by making BSFManager instances long running. I've verified that it works by patching groovy's CachingGroovyEngine to store some cache hit/miss stats and taking thread dumps at various points in time. Drops the load on a host monitoring a lot of hosts each with many services monitored by a groovy script from ~3-5 to ~0.25-0.75.

Improve BSFMonitor and BSFNotificationStrategy performance

---

opennms-base-assembly/src/main/filtered/etc/rrd-configuration.properties
opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/QueuingRrdStrategy.java
opennms-rrd/opennms-rrd-api/src/main/resources/org/opennms/netmgt/rrd/rrd-configuration.xml

Queued logs should go to queued.log like they did in 1.12.
JIRA: http://issues.opennms.org/browse/NMS-7485
Todo:

NMS-7485: fix queued logging output.

---

opennms-doc/guide-admin/src/asciidoc/text/poller/BSFMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/CiscoIpSlaMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/CiscoPingMibMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/CitrixMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/DhcpMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/DiskUsageMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/HostResourceSwRunMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/JCifsMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/JDBCMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/JDBCQueryMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/JDBCStoredProcedureMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/MemcachedMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/NetScalerGroupHealthMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/OmsaStorageMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/OpenManageChassisMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/PrTableMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/SmbMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/SnmpMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/StrafePingMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/SystemExecuteMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/VmwareCimMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/VmwareMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/poller/_template-monitors.adoc
opennms-doc/guide-admin/src/asciidoc/text/provisioning.adoc
opennms-doc/guide-admin/src/asciidoc/text/webui/opsboard/dashlet/alarm-detail.adoc
opennms-doc/guide-admin/src/asciidoc/text/webui/opsboard/dashlet/alarms.adoc
opennms-doc/guide-admin/src/asciidoc/text/webui/opsboard/dashlet/criteria-builder.adoc
opennms-doc/guide-admin/src/asciidoc/text/webui/opsboard/introduction.adoc
opennms-doc/guide-user/src/asciidoc/text/surveillance-view.adoc

- Normalized tables
- Fixed file name convention to monospace
- Remove ' and replace with _ to have italic font
- Normalized file names to monospace font
- Normalized tables

NMS-7655: Documentation fixes to normalize italic and monospace fonts

---

debian/opennms-server.opennms.init

Fixed error in for loop line 46. Close for loop with "done" instead of "fi".

NMS-7658: Error debian init script

---

opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties
opennms-base-assembly/src/main/filtered/etc/threshd-configuration.xml
opennms-base-assembly/src/main/filtered/etc/thresholds.xml

Added configuration to collect, graph and threshold on Juniper SRX router's jnxJsSPUMonitoringCurrentFlowSession OID.
Background: 
When the number of tracked sessions reach the router's maximu capacity, the router starts to drop arbitrary sessions (not necessarly inactive ones) when needed to stay below the maximum. This, obviously, creates strange network issues.
This can easily happen if you forget to define a timeout for some kind of UDP sessions.
JIRA: http://issues.opennms.org/browse/NMS-7553
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-NMS258
Todo:
- [ ] Merge to develop

NMS-7553: Add Juniper SRX flow performance monitoring and default thresholds

---

opennms-doc/pom.xml
pom.xml

Adding JRuby 9000 dependency to the asciidoc maven plugin to provide a proper JRuby version.
JIRA: http://issues.opennms.org/browse/NMS-7600
Todo:

NMS-7600: Build for PDF documentation fail on FreeBSD

---

features/jmx-config-generator-webui/pom.xml

Here the missing fix for NMS-7772.
This will however only fix the "next button exception" and not fix the validation errors.
This is addressed in a different issue and will be fixed later (http://issues.opennms.org/browse/HZN-330).
* JIRA: http://issues.opennms.org/browse/NMS-7772
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS78

NMS-7772: Fix missing import package.

---

opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties

JIRA: http://issues.opennms.org/browse/HZN-372
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS90
Created a new resourceType named "jnxOperatingTable" for juniper's snmp data collection.
Also, changed the juniper-router group to make use of this resourceType.
Caution, this PR is not working atm. But, I need your help to go further.
1st: 
I wonder if changing the juniper-router group is the correct way to go. Indeed, it will probably break current data collection of this group. So, maybe I should create a brand new group for this collection, and leave both groups active for a moment. Also the jnxOperatingTable is also available for juniper switches, so the name "juniper-router" is a little bit misleading.
2nd: 
The collection simply doesn't work atm. I've traced down the …

HZN-372: jnxOperatingTable datacollection not correctly made

---

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties

because of a typo, report.juniper.jnxOpTableBuff.propertiesValues wasn't correctly set, therefore variable {jnxOpDescr} in juniper.jnxOpTableBuff title wasn't corretly resolved.

HZN-372: Fix a typo in juniper.jnxOpTableBuff title

---

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/mib2-graph.properties

The graph uses ifSpeed and give incorrect results when the interface speed is above 4Gbps.
This PR switches to ifHighSpeed.

High Speed utilization graph should use ifHighSpeed instead of ifSpeed

---

features/newts/src/main/resources/META-INF/opennms/applicationContext-newts.xml

Added a metric reporter which exposes all newts specific metrics via JMX.
Issue: http://issues.opennms.org/browse/HZN-347
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS127

HZN-347: Expose Newts metrics via JMX

---

opennms-doc/guide-install/src/asciidoc/index.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/placeholder.adoc

Create installation description to install OpenNMS on a Debian based system.
The setup describes the installation with the opennms meta package which handles
all dependencies like JICMP, PostgreSQL and Oracle Java.
Created generic introduction about the overall installation workflow and how
different releases can be installed.
JIRA: http://issues.opennms.org/browse/HZN-185
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS119/latest

HZN-185: Document Installation on Debian-based system

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cassandra21x-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/newts-cassandra21x-graph.properties

Refactored Cassandra and Newts keyspace specific attributes to be compatible with RRDtool and JRobin matching maximum 19 character limit. Refactoring covers JMX data collection configuration for Cassandra generic metrics and Newts specific metrics including the RRD graph definition templates.
JIRA: http://issues.opennms.org/browse/HZN-474
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS182-3/

HZN-474: Newts attributes RRDtool and JRobin compatible

---

features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java

Fix for issue NMS-7917: In the case an Alarm Dashlet's filter criteria returned an empty set of alarmIds the restriction was not correctly applied to the AlarmRepository instance. Now the empty set will be replaced by a set containing only the integer zero (0), so no alarms will match which is the correct expected behavior.
Jira: http://issues.opennms.org/browse/NMS-7917
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS194

Fix for issue NMS-7917

---

features/measurements/api/src/main/java/org/opennms/netmgt/measurements/model/Source.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/AbstractRrdBasedFetchStrategy.java
features/measurements/rest/src/main/java/org/opennms/web/rest/v1/MeasurementsRestService.java
features/measurements/rest/src/test/java/org/opennms/web/rest/v1/MeasurementsRestServiceITCase.java
features/newts/src/main/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategy.java
features/newts/src/test/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategyTest.java
opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc

HZN-459: Evaluate possibilities to defer between ifHcInOctets and ifInOctets
Introduced an fallback-attribute parameter in the Source model to allow to query for 
a secondary attribute if the primary one does not exist.
Jira: http://issues.opennms.org/browse/HZN-459
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS195-3

HZN-459: Evaluate possibilities to defer between ifHcInOctets and ifInOctets

---

opennms-doc/guide-install/src/asciidoc/text/newts/cassandra-debian.adoc
opennms-doc/guide-install/src/asciidoc/text/newts/cassandra-windows.adoc

Bumped version for Apache Cassandra in install guide from 2.1.8 to 2.1.10.
JIRA: http://issues.opennms.org/browse/HZN-481
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS199

HZN-481: Cassandra version bump

---

opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc

CCE occurs if you don't URL encode the plus sign when using GET.
I already fixed the Wiki.

encode the '+' character in eventAckTime example.

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cassandra21x-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/cassandra21x-newts-graph.properties
opennms-doc/guide-admin/src/asciidoc/text/operation/newts/cassandra21x.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/newts/newts.adoc

Cleaned up graph definitions for monitoring Apache Cassandra and Newts keyspace.
Changed stacking and legend colors for graph definitions and added documentation
for all specific metrics. Metric documentation is oriented on graph definitions.
JIRA: http://issues.opennms.org/browse/HZN-475
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS184-7

HZN-475: Cleanup graph definitions

---

opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounder.java

Reopening this pull request against release-17.0.0.

Fix NMS-7969: JMS alarm northbounder always indicates message sent

---

core/daemon/src/main/resources/org/opennms/netmgt/vmmgr/local-access.xml
features/poller/remote/src/main/resources/META-INF/opennms/applicationContext-exportedPollerBackEnd-rmi.xml
features/themes/onms-default-theme/.gitignore
opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java
opennms-bootstrap/src/main/java/org/opennms/bootstrap/HostRMIServerSocketFactory.java
opennms-full-assembly/src/main/filtered-resources/etc/org.apache.karaf.management.cfg

This pull implements a custom socket factory to coerce the RMI server into binding only to localhost by default.  Additionally, it provides a default karaf configuration that uses `localhost` for RMI server and client connections.
You can override the bind port by setting the `opennms.poller.server.serverHost` property in `$OPENNMS_HOME/etc/opennms.conf`:
```
ADDITIONAL_MANAGER_OPTIONS="-Dopennms.poller.server.serverHost=0.0.0.0"
ADDITIONAL_MANAGER_OPTIONS="-Dopennms.poller.server.serverHost=192.168.0.1"
```

Make RMI Bind to Localhost By Default

---

opennms-doc/guide-install/src/asciidoc/index.adoc
opennms-doc/guide-install/src/asciidoc/text/r/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/r/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/r/rhel.adoc

Backporting R installation on Debian and RHEL to release-17.0.0 by cherry-picking commit.
JIRA: http://issues.opennms.org/browse/HZN-462
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS277

HZN-462: Document how to install R on RHEL and Debian systems

---

opennms-doc/guide-install/src/asciidoc/index.adoc
opennms-doc/guide-install/src/asciidoc/text/rrdtool/installation.adoc

Created documentation how to install RRDtool and how to configure OpenNMS to enable it. The documentation covers the installation on CentOS/RHEL and Debian/Ubuntu based operation systems.
JIRA: http://issues.opennms.org/browse/NMS-7986
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS279

NMS-7986: Documentation how to use RRDtool

---

opennms-webapp/src/main/scss/opennms-theme.scss
opennms-webapp/src/main/scss/properties.scss

Add property to which represents success color and use in notification bell when Notifications are turned on. The color is based on the up indication color of outages and the availability time line for services.
JIRA: http://issues.opennms.org/browse/NMS-7997
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS289

NMS-7997: Background of notifications bell icon is too dark

---

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/AbstractForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/CachingForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/DirectoryWatcher.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/ForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/FusedForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/QueueingForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/CachingForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FastFilesystemForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FilesystemForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FusedForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/MockForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/QueueingForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/RequisitionTest.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultRequisitionAccessService.java

URL-handling changed in the ReST API in 17, most likely related to the move to CXF.
These changes add some unit tests to validate behavior across all the ForeignSourceRepository implementations, as well as handling the new %20 in URLs.  In the case where the import URL has a %20 in it, Provisiond checks if it's a valid file, and if not, tries translating it and loads that instead.
JIRA: http://issues.opennms.org/browse/HZN-523
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS284

HZN-523: Requisitions with a space in the name are no longer readable

---

container/features/src/main/resources/features.xml
container/karaf/src/main/filtered-resources/features/features.xml
pom.xml

This is test-building right now: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS291-1/
In my personal test-build of this, everything got overridden properly, the only commons-collections jar in lib is 3.2.2.  Note that we will end up with commons-collections 3.2.1 *and* 3.2.2 in the system/ tree because there are external bundle dependencies that haven't been updated, but at runtime only the 3.2.2 version is loaded:
opennms> list | grep -i collections
[ 151] [Active     ] [            ] [   80] Apache Commons Collections (3.2.2)
I don't think this can be avoided without duplicating a bunch of upstream features, which is obviously a horrible idea.

NMS-7999 bump commons-collections to 3.2.2

---

features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/OneToOnePersister.java

In preperation of being able to convert storeByGroup=false to NewTS, this must be active and in place for some time.
JIRA: http://issues.opennms.org/browse/HZN-344
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS293

HZN-344: Store the group name in the .meta if storeByGroup is false

---

core/upgrade/src/main/java/org/opennms/upgrade/implementations/ServiceConfigMigratorOffline.java
core/upgrade/src/test/java/org/opennms/upgrade/implementations/ServiceConfigMigratorOfflineTest.java
core/upgrade/src/test/resources/etc/service-configuration-1.10.14.xml
core/upgrade/src/test/resources/etc/service-configuration-1.12.9.xml
core/upgrade/src/test/resources/etc/service-configuration-1.8.17.xml
core/upgrade/src/test/resources/etc/service-configuration-14.0.3.xml
core/upgrade/src/test/resources/etc/service-configuration-15.0.2.xml
core/upgrade/src/test/resources/etc/service-configuration-16.0.4.xml
tools/packages/opennms/opennms.spec

* Put map and link provisioning adapter packages back in, but empty, for upgrading. (see [here](http://paste.opennms.eu/?3bdd8e3d42e02e3a#qLMk8MEJZz6DsuIW+kAlsrfRLmA8oTHLpZNAfqvf1h8=) for the failure)
* Make the migrator disable Linkd, Xmlrpcd, XmlrpcProvisioner, and AccessPointMonitor if they are enabled since they no longer exist in OpenNMS 17.
* Update the tests to check service-configuration.xml upgrades from 1.8 through 16.

HZN-545 upgrade tasks for 17

---

opennms-doc/guide-install/src/asciidoc/text/opennms/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/rhel.adoc

Create user for OpenNMS Postgres database and add super user permission to allow installation of C language stored procedure IPLIKE with `./install -dis`. After first start of OpenNMS the opennms user is locked down to a normal user removing super user role and removing possibility to create other databases.
JIRA: http://issues.opennms.org/browse/NMS-8004
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS294

NMS-8004: Install iplike stored procedure

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties

Allow to delete requisitioned monitoring entities by default. Otherwise you just get a scheduled for deletion event and nothing happens.
JIRA: http://issues.opennms.org/browse/NMS-7998
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS295

NMS-7998: Enable deletion of requisitioned entities by default

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/processor/EventExpanderTest.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Event.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Parameter.java
opennms-config-model/src/main/resources/xsds/eventconf.xsd
opennms-config-model/src/test/java/org/opennms/netmgt/xml/eventconf/EventsTest.java
opennms-config-model/src/test/java/org/opennms/netmgt/xml/eventconf/ParameterTest.java

A new tag has been added to eventconf.xsd, in order to add additional parameters to an event when it is received by Eventd.
The additional parameters will be added if their names are not being used by any of the current parameters of the event.
JIRA: http://issues.opennms.org/browse/HZN-551
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS314

HZN-551: Optional eventconf parameters

---

features/ncs/ncs-northbounder/src/main/java/org/opennms/netmgt/ncs/northbounder/NCSNorthbounder.java
opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/NorthboundAlarm.java
opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/Northbounder.java
opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounder.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounderManager.java
opennms-alarms/jms-northbounder/src/test/java/org/opennms/netmgmt/alarmd/northbounder/jms/JmsNorthBounderTest.java
opennms-alarms/syslog-northbounder/pom.xml
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogDestination.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogFilter.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounder.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderConfig.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderConfigDao.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderManager.java
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogConfigDaoTest.java
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogFilterTest.java
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthBounderTest.java
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthBounderWithFiltersTest.java
opennms-alarms/syslog-northbounder/src/test/resources/syslog-northbounder-config1.xml
opennms-alarms/syslog-northbounder/src/test/resources/syslog-northbounder-config2.xml

This set of code changes provide the ability to apply powerful filters over the syslog northbound destinations, as well as the ability to reload the configuration.
The reload feature has some limitations due to the way the syslog northbound interface was implemented. Because each declared destination is going to be an independent implementation of the Northbounder interface, you cannot rename, add or remove destinations without restart OpenNMS. But, you can change the internal settings of any destination like IP, port, protocol, etc.
Of course, all the filters will be reloaded properly.
The code has JUnit tests to validate all the features introduced, and all of them has been tested on a lab environment.
JIRA: http://issues.opennms.org/browse/HZN-563
Bamboo: …

HZN-563: Improve flexibility to the syslog alarm northbounder

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/configuration.adoc
opennms-doc/guide-admin/src/asciidoc/text/service-assurance/critical-service.adoc

The description and attribute pollAllIfNoCriticalServiceDefined is moved to the correct nodeOutage defintion instead of the poller configuration.
JIRA: http://issues.opennms.org/browse/NMS-8058
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS352

NMS-8058: Poll all interface w/o critical service is incorrect

---

opennms-doc/asciidoctor-default.css
opennms-doc/default-theme.yml
pom.xml

Updated the asciidoc framework dependencies to latest versions.
- asciidoctor 1.5.2.1 > 1.5.3
- asciidoctorj 1.5.2 > 1.5.3.2
- asciidoctorjpdf 1.5.0-alpha.6 > 1.5.0-alpha.10.1
- jruby 9.0.0.0 > 9.0.4.0
Default themes in CSS and PDF yaml styles are updated.
JIRA: http://issues.opennms.org/browse/NMS-8063
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS351

NMS-8063: Update asciidoc dependencies to latest 1.5.3

---

opennms-base-assembly/src/main/filtered/etc/eventconf.xml
opennms-base-assembly/src/main/filtered/etc/events/Juniper.ive.events.xml

Added compiled OpenNMS Events from JUNIPER-IVE-MIB to support SNMP traps from Junipers Instant Virtual Extranet platform.
JIRA: http://issues.opennms.org/browse/NMS-8071
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS390-2

NMS-8071: Add event definition file for JUNIPER-IVE-MIB

---

opennms-base-assembly/src/main/filtered/etc/thresholds.xml

This is a proposed patch that does the following:
1. thresholds.xml
* Add descriptions to all thresholds to add documentation on what each threshold is for
* Change whitespace and ordering to match how the OpenNMS web UI generates the file; I used the web GUI to open each threshold in the editor and then saved it WITH NO CHANGES (other than the description) to get OpenNMS just to rewrite the file formatting. The issue here is it is much easier to diff a new version of the file with the one in production if the whitespace and XML formatting match how the GUI edits the file.
2. eventconf.xml
* Added a comment about file ordering for documentation purposes
* Remove extraneous blank lines
JIRA: http://issues.opennms.org/browse/NMS-7978
Bamboo: …

NMS-7978: Add threshold description and formatting XML files

---

opennms-base-assembly/src/main/filtered/etc/events/Postfix.syslog.events.xml
opennms-base-assembly/src/main/filtered/etc/syslog/Postfix.syslog.xml

Created a TLS Disabled event and degraded the severity for obsoleteDatabase event from Minor to Warning.
JIRA: http://issues.opennms.org/browse/NMS-8028
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS407

NMS-8028: Added TLS support disabled event definition for postfix syslog message

---

opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
opennms-provision/opennms-provision-persistence/src/main/resources/org/opennms/netmgt/provision/persist/default-foreign-source.xml
opennms-webapp/src/main/webapp/element/node.jsp

The OpenNMS node page provides links for customized URL handler for example for ssh://, telnet://. The node page is extended to support also Microsoft RDP protocol with rdp://. The link is generated based on the MS-RDP service. To allow easier integration a default TCP detector and a TCP monitor for MS-RDP service is created.
JIRA: http://issues.opennms.org/browse/NMS-8044
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS402

NMS-8044: Link support for Microsoft RDP on node page

---

opennms-doc/guide-install/src/asciidoc/text/java/debian.adoc

It is not possible since Java 1.8.0 b72 to install with add-apt-repository. Updated the install guide to create source.list file manually.
JIRA: http://issues.opennms.org/browse/NMS-8097
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS435

NMS-8097: Fix Oracle Java install guide

---

opennms-base-assembly/src/main/filtered/bin/opennms

Fix return status of checkXmlFiles() in opennms init script

NMS-8104: init script checkXmlFiles() fails to pick up errors

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/wsman/detector.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/wsman/ws-management.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/introduction.adoc

Build a generic structure for performance data collection similar to "Service Assurance". The documentation describes how an OpenNMS Administrator can configure WS-Management data collection capabilities for Dell iDRAC 6 and Microsoft Windows Server 2012. The description for the WS-Management  detector is separated in a dedicated file for easier refactoring if necessary. Provided also some PowerShell commands for troubleshooting WinRM connectivity and configuration.
JIRA: http://issues.opennms.org/browse/HZN-584
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS440-5

HZN-584: Create WS-Management documentation for OpenNMS Administrator

---

opennms-base-assembly/src/main/filtered/bin/opennms

Propagate return value from checkXmlFiles() to init script exit value,
so "configtest" exits with 0 for success and non-zero for failure.

NMS-8112: init script "configtest" exit value is always 1

---

opennms-base-assembly/src/main/resources/contrib/send-event.py
opennms-doc/guide-development/src/asciidoc/text/rest/events.adoc
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/EventRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/EventRestServiceIT.java

Included a sample python script in contrib/ that can be used to generate
and publish events via REST.
JIRA: http://issues.opennms.org/browse/NMS-6404
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS466-2

NMS-6404: Add support for publishing events on the bus via REST.

---

features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css
features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/ui/HeaderLayout.java

Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS479
Jira: http://issues.opennms.org/browse/BSM-144
I did an implementation without using the OnmsHeaderProvider because 
the Ops Board/Panel has its own input fields and make no use of the original 
OpenNMS menu bar.

BSM-144: Update the header of the Ops Board to use the same styling as the rest of the application

---

opennms-dao/src/test/java/org/opennms/netmgt/dao/AuthorizationIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsOutage.java

All the tests from OnmsDaoIT are passing with this change, Bamboo doesn't complain, and the ACL feature is now fully working, after removing the {alias} reference from the @Filter defined inside OnmsOutage.
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS508
Jira: http://issues.opennms.org/browse/NMS-8165

Fix for Bug NMS-8165 - The ACL feature is broken.

---

opennms-services/src/main/java/org/opennms/netmgt/collectd/IfInfo.java

Collect data from some non-conforming IF-MIB agents, which use ifIndex >= 2^31.
JIRA: http://issues.opennms.org/browse/NMS-8179

NMS-8179: Interpret ifIndex as 32-bit unsigned ints.

---

features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/BusinessServiceEdgeEntity.java
features/bsm/persistence/api/src/main/java/org/opennms/netmgt/bsm/persistence/api/BusinessServiceEntity.java
features/bsm/persistence/impl/src/main/resources/changelog.xml
features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceDaoIT.java
features/bsm/persistence/impl/src/test/java/org/opennms/netmgt/bsm/persistence/BusinessServiceEdgeDaoIT.java
features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceManager.java
features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/BusinessService.java
features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceImpl.java
features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImpl.java
features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/edge/AbstractEdge.java
features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImplIT.java
features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java

The persistence layer is (due to an hibernate bug) not able to delete
oprhan map function instances and reduce function instances. To work
around, the service layer ensures they are deleted.
JIRA: http://issues.opennms.org/browse/BSM-114
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS543

BSM-114: Delete orphan reduce and map functions

---

integration-tests/config/src/test/java/org/opennms/netmgt/config/WillItUnmarshalCoverageMetaIT.java
opennms-base-assembly/src/main/filtered/etc/eventconf.xml
opennms-base-assembly/src/main/filtered/etc/events/OpenWrt.syslog.events.xml
opennms-base-assembly/src/main/filtered/etc/syslog/OpenWrt.syslog.xml
opennms-base-assembly/src/main/filtered/etc/syslogd-configuration.xml

This is a pull request for the addition of syslog messages and related events for OpenWrt (a Linux distribution for routers and other embedded devices) and various OpenWrt packages that also report status through syslog.
JIRA: http://issues.opennms.org/browse/NMS-8092
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS426-2

NMS-8092: Add OpenWrt syslog and related event definitions

---

integration-tests/config/src/test/java/org/opennms/netmgt/config/WillItUnmarshalCoverageMetaIT.java
opennms-base-assembly/src/main/filtered/etc/eventconf.xml
opennms-base-assembly/src/main/filtered/etc/events/NetgearProsafeSmartSwitch.events.xml
opennms-base-assembly/src/main/filtered/etc/events/NetgearProsafeSmartSwitch.syslog.events.xml
opennms-base-assembly/src/main/filtered/etc/syslog/NetgearProsafeSmartSwitch.syslog.xml
opennms-base-assembly/src/main/filtered/etc/syslogd-configuration.xml

This is a request to merge NetGear ProSafe Smart Switch SNMP traps and syslog definitions and events.
JIRA: http://issues.opennms.org/browse/NMS-8077
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS427-2

NMS-8077: Add Netgear ProSafe Smart Switch SNMP trap and syslog definitions and events

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/element/nodeList.jsp

PRELIMINARY ADVISORY: I don't know exactly why it works, but it works.
You can test the fix by modifying the corresponding .jsp file on a running OpenNMS instance (and restarting it).
JIRA: http://issues.opennms.org/browse/NMS-8146
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS586-1

NMS-8146: "show interfaces" link doesn't remember SNMP MIB-2 attribute filter.

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors/SnmpDetector.adoc
opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors/_template-detector.adoc

Create documentation for the SNMP detector with two short examples for table and scalar OID. Also created a template for new detectors to have similar structure.
* JIRA: http://issues.opennms.org/browse/NMS-8267
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS584

NMS-8267: Create documentation for SNMP detector with two examples

---

features/node-page-list/src/main/java/org/opennms/features/node/list/gwt/client/IpInterfaceTable.java
features/node-page-list/src/main/java/org/opennms/features/node/list/gwt/client/PhysicalInterfaceTable.java
opennms-webapp/src/main/scss/opennms-theme.scss

Removed striped table layout from IP interface and physical interface table which overwrite the status indication for physical interfaces and IP interfaces.
* JIRA: http://issues.opennms.org/browse/NMS-8189
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS598

NMS-8189: Fix interface status indication in node detail page

---

opennms-services/src/main/java/org/opennms/netmgt/threshd/ThresholdingSet.java

* JIRA: http://issues.opennms.org/browse/NMS-8304
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS620
An error on threshd-configuration.xml breaks Collectd when reloading
thresholds configuration.
It doesn't make sense to thrown a runtime exception if the ThresholdingSet is not able to load (or reload) the thresholds configuration. If there is an error with the config, the thresholding processor should use whatever it already has in memory, otherwise this exception will hang Collectd which is a very bad side effect.
I tested the solution on my lab and it works as expected (i.e. only an exception will be logged to collectd.log and Collectd continues to work properly).

NMS-8304: An error on threshd-configuration.xml breaks Collectd when reloading thresholds configuration

---

opennms-webapp/src/main/webapp/admin/ng-requisitions/app/index.jsp
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/ForeignSource.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Move.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/views/foreignsource.html
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/views/move.html

* JIRA: http://issues.opennms.org/browse/NMS-8296
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS621
I ended up by implementing a very simple but useful way to move elements on angular tables that have pagination and filter components.
This is intended to re-order the detectors or policies on a foreign source definition. The elements will be applied in the exact same order they are defined, so order is important, specially for policies.

NMS-8296: Be able to re-order the policies on a requisition through the UI

---

core/jmx/impl/src/main/java/org/opennms/netmgt/jmx/impl/connection/connectors/Jsr160ConnectionFactory.java
opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/AbstractJsr160Detector.java
opennms-provision/opennms-detector-jmx/src/main/java/org/opennms/netmgt/provision/detector/jmx/JMXDetector.java
opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/JBossDetectorTest.java
opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/Jsr160DetectorTest.java
opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/Jsr160DetectorWiringTest.java
opennms-provision/opennms-detector-jmx/src/test/java/org/opennms/netmgt/provision/detector/MX4JDetectorTest.java

Changed a detection failure message from ERROR to INFO. Added unit test assertions for logging levels.
* JIRA: http://issues.opennms.org/browse/NMS-8096
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS635

NMS-8096: Fixed log level of messages in JMXDetector

---

features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/DefaultPollerBackEnd.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/BSFMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/StrafePingMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/TrivialTimeMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptor.java
opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitorIT.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/LatencyThresholdingSetIT.java
protocols/selenium-monitor/src/main/java/org/opennms/netmgt/poller/monitors/SeleniumMonitor.java

The PSM was catching an httpclient exception and always returning failure message "I/O Error" even though the root cause exceptions provided more precise failure codes. I added code to unwrap the exceptions so that the failure codes are more useful.
I also added a catch(Throwable) to the main PSM poll() method so that it's more resilient to unexpected exceptions (like config typos, etc).
* JIRA: http://issues.opennms.org/browse/NMS-8098
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS646/latest

NMS-8098: Unwrapped exceptions to make nicer PSM failure reasons

---

core/web/src/main/java/org/opennms/core/web/HttpClientWrapper.java
core/web/src/main/java/org/opennms/core/web/HttpRequestRetryOnExceptionHandler.java

Because we are a network management framework, we want to retry operations even if low-level protocol exceptions have been thrown. The solution proposed by Alejandro has been incorporated into the httpclient API since this bug was opened and because Ben wrote the HttpClientWrapper class a few years ago, this retry logic will be applied in most places that we use httpclient (PSM, HttpCollector, etc).
* JIRA: http://issues.opennms.org/browse/NMS-5915
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS645

NMS-5915: Change HTTP client code to retry on any exception

---

opennms-base-assembly/src/main/filtered/bin/provision.pl
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisitions.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/directives/requisitionConstraints.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/views/node-basic.html

* JIRA: http://issues.opennms.org/browse/NMS-8129
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS643
Disallow restricted characters from foreign source and foreign ID.
In terms of the WebUI and provision.pl, you won't be able to add a
requisition or node with invalid characters on the foreign source
or the foreign id.
The only thing that is not covered is adding these kind of validation to the ReST API itself. The reason why I'm not adding this is because there is no way to know if you're adding or updating an existing entity, and some of the developers pointed out that some users might have foreign-source or foreign-id fields with invalid characters. I think this is not possible because during my tests, I cannot synchronize a requisition that has invalid characters …

NMS-8129: Disallow restricted characters from foreign source and foreign ID

---

opennms-doc/releasenotes/src/asciidoc/index.adoc
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew-18.adoc

I think we should start working on a "What's New" section for the OpenNMS 18 release.
This is a small snippet to inform users to upgrade their custom icon definitions.

Add whats new section for OpenNMS 18 (Topology UI Custom Icons)

---

opennms-config/src/main/java/org/opennms/netmgt/config/EventTranslatorConfigFactory.java

* JIRA: http://issues.opennms.org/browse/NMS-7854
Translated events with a new UEI do not receive the description, severity and alarm-data of the new event if new UEI's eventconf is present after original UEI's eventconf.
The workaround of reordering the event definitions work for non-trap events. For traps events, there are some unwanted results that are affecting other components like the Passive Status Keeper.
For this reason, several fields (specially snmp) have to be set to null when cloning the original event to avoid surprises.
I tested the proposed patch on my testing environment, and now the passive status keeper works as expected when translating SNMP traps.

Fix for Bug NMS-7854 - Event Translator Issues

---

opennms-config/src/main/java/org/opennms/netmgt/config/EventTranslatorConfigFactory.java

According to @jeffgdotorg, the Event Translator was designed to generate an enhanced copy of the original event:
_When an event is published on the event bus for which ET has configuration, it clones the event and changes the event's attributes (fields and parameters) as defined by the administrator in the translator configuration._
For this reason, the solution is against its the original design, but this mean, the Event Translator CANNOT be used to generate Passive Status Change events based on SNMP Traps. For this use case, only Scriptd can be used for now.

Revert "Fix for Bug NMS-7854 - Event Translator Issues"

---

opennms-config-model/src/main/castor/translator-configuration.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/EventTranslatorConfigFactory.java

The logic to find event definitions confuses the Event Translator when translating SNMP Traps
* JIRA: http://issues.opennms.org/browse/NMS-8374
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS665

NMS-8374:  The logic to find event definitions confuses the Event Translator when translating SNMP Traps

---

features/discovery/blueprint-discovery.xml
features/discovery/src/main/resources/META-INF/opennms/applicationContext-discovery.xml
features/discovery/src/test/java/org/opennms/netmgt/discovery/DiscoveryBlueprintIT.java
features/events/syslog/blueprint-syslog-handler-default.xml
features/events/syslog/blueprint-syslog-handler-minion.xml
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdHandlerDefaultIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdHandlerMinionIT.java
opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml
opennms-doc/guide-install/src/asciidoc/text/minion/introduction.adoc

This commit changes the OpenNMS-side JMS connections to run over the vm://localhost connector instead of TCP. The TCP port will be disabled by default. I also fixed the Syslog Minion code to use the shared JMS connection from minion-core.
* JIRA: http://issues.opennms.org/browse/HZN-726
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS669

HZN-726: Changed ActiveMQ broker to only listen for vm://localhost

---

opennms-doc/guide-install/src/asciidoc/index.adoc
opennms-doc/guide-install/src/asciidoc/text/java/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/java/environment.adoc
opennms-doc/guide-install/src/asciidoc/text/java/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/java/rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/java/windows-server.adoc
opennms-doc/guide-install/src/asciidoc/text/newts/cassandra-debian.adoc
opennms-doc/guide-install/src/asciidoc/text/newts/cassandra-rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/newts/cassandra-windows.adoc
opennms-doc/guide-install/src/asciidoc/text/newts/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/repository.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/windows.adoc
opennms-doc/guide-install/src/asciidoc/text/r/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/r/introduction.adoc
opennms-doc/guide-install/src/asciidoc/text/r/rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/rrdtool/installation.adoc

General cleanup in the install guide:
* Made language in some sections more natural.
* Made section headers more terse so that they look better and are easier to read in the table of contents.
* Made the terminology more uniform between sections.
* Got rid of excess "Installing..." and "Setup..." terms which are redundant since this is an installation guide.
* Moved the yum/apt repo instructions to a separate adoc file.
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS676

Install guide cleanup

---

core/test-api/karaf/pom.xml
integration-tests/config/pom.xml
opennms-full-assembly/pom.xml

A lot of space is taken up by Karaf feature repositories that are built for integration tests. These repositories can be removed after the `package` and `integration-test` phases. This saves several hundred megabytes of disk space when running the build.
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS685

Added post-integration-test cleanup of Karaf feature repositories

---

container/features/pom.xml
container/karaf/src/main/filtered-resources/etc/custom.properties
features/jmx-config-generator/pom.xml
features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/DashletSelector.java
features/vaadin-jmxconfiggenerator/pom.xml
opennms-full-assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg

The Syslog receiver blueprint was missing from the OpenNMS feature repository. This feature was added and also added to featuresBoot so that it's installed by default on OpenNMS.
* JIRA: http://issues.opennms.org/browse/HZN-568
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS682

HZN-568: Final changes to get Minion Syslogd working...?

---

container/features/src/main/resources/features.xml
container/karaf/src/main/filtered-resources/etc/custom.properties
features/events/syslog/blueprint-syslog-handler-default.xml
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogConnection.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java
features/events/syslog/src/test/resources/etc/syslogd-cisco-configuration.xml

The opennms-syslogd-handler-default feature on OpenNMS installed some OSGi bundles that conflicted with classes in the system classpath. These changes should resolve that problem and hopefully get the Minion system tests working.
* JIRA: http://issues.opennms.org/browse/HZN-568
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS682

HZN-568: More final changes to get Minion Syslogd working :)

---

container/features/pom.xml
container/features/src/main/resources/features.xml
core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
opennms-full-assembly/pom.xml
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/FeaturesBootKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsKarafTestCase.java

Addition of not-yet-working integration test code that runs with the OpenNMS system classpath. Also fixed a dependency monkey failure.
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS699

Partial code for Karaf ITs with the system classpath

---

debian/opennms-doc.links
opennms-webapp/src/main/webapp/WEB-INF/jsp/support/index.jsp
opennms-webapp/src/main/webapp/WEB-INF/web.xml
smoke-test/src/test/java/org/opennms/smoketest/SupportPageIT.java
tools/packages/opennms/opennms.spec

These changes will add links to the online docs to the "Help/Support" page. If you install the opennms-docs package, the links will redirect to local copies of the docs so that you don't need internet access to view them.
* JIRA: http://issues.opennms.org/browse/NMS-8076
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS675

NMS-8076: Added links to local, offline docs to webapp

---

opennms-webapp/src/main/webapp/admin/ng-requisitions/app/basehref.jsp

* JIRA: http://issues.opennms.org/browse/NMS-8386
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS689
Requisitioning UI fails to load in modern browsers if used behind a proxy.
I tested it with curl and the content-type is now reported correctly.

NMS-8386: Requisitioning UI fails to load in modern browsers if used behind a proxy

---

opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/JDBCMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/JolokiaBeanMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/WebMonitor.java
opennms-util/src/main/java/org/opennms/core/utils/DBTools.java

Fixes:
- If JDBCMonitor is configured with a mismatching JDBC driver and URL, it always returns "Available"
- WebMonitor returns "Available" when an exception (including connect exceptions, timeouts, etc) happens during polling
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS722/

Fixed status values inside JDBCMonitor and WebMonitor

---

opennms-jetty/pom.xml
opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml
pom.xml

This issue addresses a perceived cross scripting  'clickjacking' vulnerability described in  http://issues.opennms.org/browse/NMS-8393
This change is needed for an enterprise customer who has tested this patch against meridian 2015 and will be upgrading to meridian 2016
User instructions for configuring the patch are also described on the OpenNMS wiki at
https://www.opennms.org/wiki/Nessus_Security_Fixes
This patch simply adds the required jetty-rewrite jar to the opennms/lib directory and additional options in the /etc/examples/jetty.xml. This makes it easier for the user to apply this configuration but by default this feature is not turned on. The user must follow the instructions in https://www.opennms.org/wiki/Nessus_Security_Fixes to uncomment the relevant sections in jetty.xml
This …

NMS-8393: changes to address clickjacking vulnerability

---

opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results-error.jsp
opennms-webapp/src/main/webapp/element/availability.jsp
opennms-webapp/src/main/webapp/element/interface.jsp
opennms-webapp/src/main/webapp/element/linkednode.jsp
opennms-webapp/src/main/webapp/element/node.jsp
opennms-webapp/src/main/webapp/element/snmpinterface.jsp

If the persistence layer is not available or unresponsive the WebUI becomes unavailable or extremely slow and key components stop working
* JIRA: http://issues.opennms.org/browse/NMS-8360
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS740
I decided to just catch any exception thrown by GraphResultsService inside GraphResultsController and redirect the output to an error page, instead of trying to make DefaultGraphResultsService more error prone as the implementation is complicated.
I tested the solution myself and it works as expected.
The reason why I'm catching exceptions on GraphResultsController is because not necessarily all the SNMP interfaces will have graphs, and the link is now forced to appear on snmpinterface.jsp. A similar reasoning applies to …

NMS-8360: If the persistence layer is not available or unresponsive the WebUI becomes unavailable or extremely slow and key components stop working	

---

core/lib/src/main/java/org/opennms/core/utils/StringUtils.java
core/lib/src/test/java/org/opennms/core/utils/StringUtilsTest.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/DefaultRrdDaoTest.java
opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/RrdFileConstants.java
opennms-rrd/opennms-rrd-jrobin/src/main/java/org/opennms/netmgt/rrd/jrobin/JRobinRrdStrategy.java

When using storeByFS a provisioning group cannot contain whitespace
* JIRA: http://issues.opennms.org/browse/NMS-6331
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS756

NMS-6331: When using storeByFS a provisioning group cannot contain whitespace

---

smoke-test/pom.xml
smoke-test/src/test/java/org/opennms/smoketest/AlarmsPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/AssetsPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportIT.java
smoke-test/src/test/java/org/opennms/smoketest/DistributedMapIT.java
smoke-test/src/test/java/org/opennms/smoketest/EventsPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/ForecastIT.java
smoke-test/src/test/java/org/opennms/smoketest/JmxConfigurationGeneratorIT.java
smoke-test/src/test/java/org/opennms/smoketest/NRTGraphIT.java
smoke-test/src/test/java/org/opennms/smoketest/OSGIPluginManagerIT.java
smoke-test/src/test/java/org/opennms/smoketest/OsgiUrlPatternResponseIT.java
smoke-test/src/test/java/org/opennms/smoketest/ProvisioningIT.java
smoke-test/src/test/java/org/opennms/smoketest/ProvisioningNewUIIT.java
smoke-test/src/test/java/org/opennms/smoketest/QuickAddNodeIT.java
smoke-test/src/test/java/org/opennms/smoketest/UserIT.java

This pull request switches the smoke tests in foundation-2016 to use docker containers to run OpenNMS and PostgreSQL, rather than relying on a locally-installed OpenNMS when bamboo runs.
Note that by default, the tests will still run the old way (assuming 127.0.0.1:8980 is an OpenNMS system).  To enable dockerized tests, pass -Dorg.opennms.smoketest.docker=true on the maven command-line.
```
../compile.pl -Dorg.opennms.smoketest.docker=true -t verify
```
This branch uses the [newer smoke-test API branch, version 2-SNAPSHOT](https://github.com/OpenNMS/smoke-tests/blob/2/test-api/src/main/java/org/opennms/smoketest/OpenNMSSeleniumTestCase.java).
* JIRA: http://issues.opennms.org/browse/NMS-8485
* Bamboo:http://bamboo.internal.opennms.com:8085/browse/OPENNMS-DST0-17/

NMS-8485: dockerized smoke tests

---

features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/MapWidgetComponent.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapsApplication.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/NodeMapState.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/ui/NodeMapConnector.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/ui/NodeMapWidget.java
opennms-base-assembly/src/main/filtered/etc/opennms.properties

This PR adds support for making the cluster radius configurable in node geomaps.  You can set it by changing `gwt.maxClusterRadius` in `opennms.properties`.
bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS785-1/
JIRA: http://issues.opennms.org/browse/NMS-7638

NMS-7638: make node map cluster radius configurable

---

opennms-webapp/src/main/java/org/opennms/web/outage/OutageUtil.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/ForeignSourceFilter.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/NegativeForeignSourceFilter.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/list.jsp
opennms-webapp/src/test/java/org/opennms/web/outage/DaoWebOutageRepositoryIT.java

Fixed SQL for outage foreign source filters that was broken after we removed the nodeid column from the outages table. Added tests for the code (and the node ID filters while I was in there).
* JIRA: http://issues.opennms.org/browse/NMS-8275
* Bamboo: TBD

NMS-8275: Fixed SQL restriction inside outage foreign source filters

---

opennms-webapp/src/main/webapp/admin/postevent.jsp

Missing node/interface information in an event after sending an event with send-event ui.
* JIRA: http://issues.opennms.org/browse/NMS-8155
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS802
The nodeId was correct, I only found a problem with the interface (i.e. the IP address). I verified the solution with latest snapshot of Meridian-2016.

NMS-8155: Missing node/interface information in an event after sending an event with send-event ui.

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
opennms-services/src/main/java/org/opennms/netmgt/scriptd/Executor.java

Avoid LazyInitializationException by using getHierarchy() instead of get().
* JIRA: http://issues.opennms.org/browse/NMS-8294
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS820

NMS-8294: Fetch all of the node hierarchy inside Scriptd

---

features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLMetaTopologyProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLProperties.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/internal/GraphMLMetaTopologyFactory.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLEdgeStatusProviderIT.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLMetaTopologyProviderTest.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLSearchProviderTest.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLVertexStatusProviderTest.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/test/resources/test-graph2.xml

* JIRA: http://issues.opennms.org/browse/HZN-825
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS833
Please note that the related documentation changes were made in the branch jira/HZN-801.

HZN-825: Besides nodeID also support foreignSource and foreignId on a GraphMLVertex

---

features/discovery/src/main/java/org/opennms/netmgt/discovery/Discovery.java

The default Camel timeout is causing big delays when shutting down OpenNMS. This patch reduces it to a minimal value.
* JIRA: http://issues.opennms.org/browse/NMS-8471
* Bamboo: TBD

NMS-8471: Changed shutdown timeout in Discovery

---

core/camel/src/main/java/org/opennms/core/camel/JaxbUtilsUnmarshalProcessor.java
core/camel/src/test/java/org/opennms/core/camel/JaxbUtilsUnmarshalProcessorTest.java

The JaxbUtilsUnmarshalProcessor was recreating its Unmarshaller over and over again which killed the performance when unmarshalling Camel messages. By reusing one ThreadLocal Unmarshaller, we can increase the performance by a factor of 15X - 100X.
* JIRA: http://issues.opennms.org/browse/NMS-8456
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS861

NMS-8456: Improved performance of JaxbUtilsUnmarshalProcessor

---

opennms-base-assembly/src/main/filtered/bin/opennms

This patch disables the startup wait by default, and adds a new option (STOP_TIMEOUT) for checking for a clean shutdown before returning on `opennms stop`.
* JIRA: http://issues.opennms.org/browse/NMS-8232
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS863

NMS-8232: disable startup wait, make shutdown wait configurable

---

opennms-base-assembly/src/main/filtered/bin/install

This patch changes the $OPENNMS_HOME/bin/install script to only attempt a ulimit -n call to raise the ulimit if the number is higher than the current value.
* JIRA: http://issues.opennms.org/browse/NMS-8200
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS859

NMS-8200 only attempt to set ulimit if it is higher than current

---

debian/control
debian/opennms-source.dirs
debian/rules
tools/packages/opennms/opennms.spec

This package separates out the opennms source tarball (packaged for GPL-compliance) into a separate package to make the default install smaller.
* JIRA: http://issues.opennms.org/browse/NMS-8008
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS864

NMS-8008: separate opennms source tarball into separate package(s)

---

debian/control
debian/opennms-webapp-jetty.conffiles
debian/opennms-webapp-jetty.dirs
debian/opennms-webapp-jetty.overrides
debian/opennms-webapp-remoting.conffiles
debian/opennms-webapp-remoting.dirs
debian/opennms-webapp-remoting.overrides
debian/rules
tools/packages/opennms/opennms.spec

This RPM will reduce the size of the opennms-webapp-jetty RPM to speed up installations for people who are not using the Remote Poller.
* JIRA: http://issues.opennms.org/browse/NMS-8345
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS828

NMS-8345: Created opennms-webapp-remoting RPM/DEB

---

opennms-doc/guide-development/src/asciidoc/text/rest/requisitions.adoc

Documentation for the Requisition ReST API is confusing.
* JIRA: http://issues.opennms.org/browse/NMS-8521
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS917

NMS-8521: Documentation for the Requisition ReST API is confusing

---

opennms-services/src/main/java/org/opennms/netmgt/syslogd/BroadcastEventProcessor.java
opennms-services/src/main/java/org/opennms/netmgt/syslogd/SyslogProcessor.java
opennms-services/src/test/java/org/opennms/netmgt/syslogd/SyslogdBroadcastEventProcessorTest.java

This change fixes the fact that Syslogd won't associate events with nodes properly unless OpenNMS is restarted after the node is added.
* JIRA: http://issues.opennms.org/browse/NMS-7236
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS926

NMS-7236: Fixed SyslogdIPMgr call in Syslogd

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/CategoryRestService.java

The categories ReST end point returns HTTP 500 when querying it with a browser.
* JIRA: http://issues.opennms.org/browse/NMS-8637
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS916
**NOTE: For foundation/Meridian-2015 the fix has to be manually ported because the ReST API lives in opennms-webapp instead of opennms-webapp-rest. I'm planning to do this when this is merged into foundation-2016.**

NMS-8637: The categories ReST end point returns HTTP 500 when querying it with a browser.

---

core/daemon/pom.xml
dependencies/pax-exam/pom.xml
opennms-config-tester/pom.xml

This is just a small patch to make sure we're using the same (4.12) JUnit everywhere.  There were a few places in the code that used to override to a *newer* version (at the time, 4.11) back when we were forced to use an old version for historical reasons.  Now those overrides are out-of-date.  ;)
No JIRA issue since it's a small change, but it passed in Bamboo already.

remove junit version overrides, accept the parent-pom version

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSiteStatusViewService.java

Site status view gives a 400 error for aggregate view for node downs
* JIRA: http://issues.opennms.org/browse/NMS-8700
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS947
The solution has been manually verified on a VM.
Note: the solution for Meridian 2015 only requires changes on DefaultSiteStatusViewService.java, as the changes for DefaultNodeListService don't apply for this version. I'll manually cherry pick the changes in foundation after merging this branch.

NMS-8700: Site status view gives a 400 error for aggregate view for node downs

---

opennms-services/src/main/java/org/opennms/netmgt/syslogd/SyslogSeverity.java
opennms-services/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Changed 'Informational' back to 'Info'.
* JIRA: http://issues.opennms.org/browse/NMS-7934
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS958

NMS-7934: Fix it so that syslog 'Info' events match eventconf

---

opennms-base-assembly/src/main/filtered/bin/vmwarecimquery
opennms-base-assembly/src/main/filtered/bin/vmwareconfigbuilder

* JIRA: http://issues.opennms.org/browse/NMS-8718
Changed include from vijava against yavijava library and included libraries in class path for SLF4J logging.

NMS-8718: vmwarecimquery and vmwareconfigbuilder tools is not working

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/OutageRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/OutageRestServiceIT.java

Pretty self-explanatory. :)
* JIRA: http://issues.opennms.org/browse/NMS-8724
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS973

NMS-8724: Add aliases so outage REST service can filter on event properties

---

core/lib/pom.xml
core/lib/src/main/java/org/opennms/core/utils/WebSecurityUtils.java
core/lib/src/test/java/org/opennms/core/utils/WebSecurityUtilsTest.java
dependencies/owasp-encoder/pom.xml
dependencies/pom.xml
opennms-webapp/src/main/webapp/WEB-INF/jsp/notification/list.jsp
opennms-webapp/src/main/webapp/includes/eventlist.jsp
pom.xml

* JIRA: http://issues.opennms.org/browse/NMS-8722

NMS-8722: XSS vulnerability in display of SNMP sysName and trap varbind values

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultManualProvisioningService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/ForeignSourceConfigRestServiceIT.java

The ReST end point /foreignSourcesConfig/assets contains invalid fields
JIRA: http://issues.opennms.org/browse/NMS-8690
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS962

NMS-8690: The ReST end point /foreignSourcesConfig/assets contains invalid fields

---

opennms-base-assembly/src/main/filtered/etc/database-schema.xml
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/JdbcFilterDaoIT.java

The database-schema.xml file that is used by JdbcFilterDao had not been updated with the location changes. This update means that you can do ```(location == 'My Location')``` as part of a poller filter rule now.
* JIRA: http://issues.opennms.org/browse/HZN-878
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS977

HZN-878: Updated database-schema.xml to make location filterable

---

features/minion/repository/pom.xml

From @StCyr: Updated searchboxes placeholder and documentation to explicitly mention it's possible to search for IPv6 addresses.
* JIRA: http://issues.opennms.org/browse/NMS-8711
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS985

NMS-8711: Update searchboxes placeholder and documentation for IPv6

---

makerpm.sh
tools/packages/minion/minion.spec
tools/packages/opennms/opennms.spec

* JIRA: https://issues.opennms.org/browse/NMS-8412
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS990
- reuse opennms tarball from makerpm for minion build
- only build (3) assembly projects in -a minion build
- otherwise, build minion projects based on list of minion poms
- fix a bunch of RPM replacements for non-centos RPM
- exit with an error if RPM build fails

NMS-8412: fix support for ./makerpm.sh -a in minion build

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/bonus-strategies.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/concepts.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/getting-started.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/strategies/mattermost.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/strategies/slack.adoc

* JIRA: https://issues.opennms.org/browse/NMS-8742
In order to have a place to hang these docs, I wrote a (rather basic) new chapter on notifications for the admin guide.  It needs fleshing out, but it's useful in its present form.

NMS-8742: Add documentation for Mattermost/Slack notifications

---

tools/packages/minion/minion.spec

This PR makes the opennms-minion-container RPM clean out /opt/minion on uninstall.
* JIRA: http://issues.opennms.org/browse/HZN-617
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS995

HZN-617: make sure the minion RPMs clean up after themselves on uninstall

---

tools/packages/minion/minion.init
tools/packages/minion/minion.spec
tools/packages/minion/minion.sysconfig

This PR adds an `/etc/sysconfig/minion` file which mirrors the Karaf startup environment variables used for overriding various options on launch.
* JIRA: https://issues.opennms.org/browse/HZN-882
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS996

HZN-882: use /etc/sysconfig for setting Minion options

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/BasicTrapProcessor.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapInformation.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapProcessor.java
core/test-api/db/src/main/java/org/opennms/core/test/db/MockDatabase.java
features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/internal/ESHeaders.java
features/elasticsearch/event-forwarder/src/test/java/org/opennms/netmgt/elasticsearch/eventforwarder/ElasticsearchNorthbounderIT.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/EventCreator.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdListenerBlueprintIT.java
features/opennms-es-rest/main-module/pom.xml
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/RawEventToIndexTest.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmLifecycleEventsIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java
opennms-services/src/main/java/org/opennms/netmgt/scriptd/helper/AlarmEventSynchronization.java
opennms-services/src/test/java/org/opennms/netmgt/poller/mock/MockPollContext.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogTest.java
tests/mock-elements/src/main/java/org/opennms/netmgt/mock/MockEventUtil.java

This partially addresses NMS-8755 so that events generated from traps and syslogs have timestamps that correspond to the time that the event was received.
* JIRA: http://issues.opennms.org/browse/NMS-8755
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS999

Removed setCreationTime() from EventBuilder

---

tools/packages/minion/minion.init

This PR does a cleaner version of the stop/kill/kill-9 procedure that the OpenNMS init script uses for making sure `stop` really stops.
* JIRA: http://issues.opennms.org/browse/HZN-618
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS998

HZN-618: be more aggressive about stopping Karaf

---

opennms-base-assembly/src/main/filtered/bin/find-java.sh
opennms-base-assembly/src/main/filtered/bin/runjava
tools/packages/minion/minion.init
tools/packages/minion/minion.spec

This PR adds a `find-java.sh` command which will search for an appropriate JDK in any number of default places.  It also updates `runjava` to call it, as well as adding a call from `minion.init` if $JAVA_HOME is empty.
* JIRA: http://issues.opennms.org/browse/HZN-622
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1006

HZN-622: set up JAVA_HOME properly if it is not

---

opennms-services/src/main/java/org/opennms/netmgt/threshd/ThresholdingVisitor.java

Maybe we should rename that issue because the sysUpTime detection was working. The problem is only related with thresholds.
* JIRA: http://issues.opennms.org/browse/NMS-7106
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1021
The sysUpTime check was working, and that was preventing the persistence of the current collection-set if a restart was detected. This is crucial for avoiding spikes. Now, the counters cache was not reinitialized which is the reason of this change.
The fix was tested on my lab and it works as expected.

NMS-7106: If a target node is rebooted the RRD/JRB files contains spikes because the sysUpTime check is not working.

---

opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java

The search page for events is not working as expected
* JIRA: http://issues.opennms.org/browse/NMS-8790
The fix was verified on a VM running Meridian 2016.1.3

NMS-8790: The search page for events is not working as expected

---

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties

* JIRA: http://issues.opennms.org/browse/NMS-8786

NMS-8786: Fixed a typo that prevented the JnxOpTemp graph to be displayed

---

features/discovery/src/main/java/org/opennms/netmgt/discovery/actors/RangeChunker.java
features/discovery/src/main/java/org/opennms/netmgt/discovery/messages/DiscoveryJob.java
features/discovery/src/main/java/org/opennms/netmgt/discovery/messages/DiscoveryResults.java

These changes allow Discovery to generate newSuspect events without foreignSource parameters so that non-provisioned nodes can be created. It will also include an upgrade script that will convert any nodes in the "default" requisition into non-provisioned nodes.
* JIRA: http://issues.opennms.org/browse/NMS-8767
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1029

NMS-8767: Revert Discovery behavior back to create non-provisioned nodes

---

pom.xml

For reasons I don't understand, maven's not respecting MAVEN_OPTS when the property is specified in a parent POM. The workaround is to only set it to a default value when it isn't defined in MAVEN_OPTS using a profile.
* JIRA: http://issues.opennms.org/browse/NMS-8838

NMS-8838: fix ability to skip ping tests

---

core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/WalkCommand.java
features/nrtg/web/src/main/java/org/opennms/nrtg/web/internal/NrtController.java
integrations/opennms-snmp-asset-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpAssetProvisioningAdapter.java
integrations/opennms-snmp-hardware-inventory-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpHardwareInventoryProvisioningAdapter.java
opennms-config-api/src/main/java/org/opennms/netmgt/config/api/SnmpAgentConfigFactory.java
opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/AnAgentConfigFactory.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeInfoScan.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
opennms-provision/opennms-snmp-scanners/src/main/java/org/opennms/netmgt/provision/scan/snmp/AbstractSnmpScanner.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/config/AgentConfigurationResource.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/AgentConfigurationResourceTest.java

HZN-926: Deprecate the SnmpAgentConfigFactory.getAgentConfig(InetAddress) method
* JIRA: http://issues.opennms.org/browse/HZN-926
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1055

HZN-926: Deprecate the getAgentConfig without location

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AlarmRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/AlarmRestServiceIT.java

tiny patch that lets us set ticket ID and state on an alarm via REST. (Full use case: emit alarms via the JMS NBI that get processed into tickets, then use this to make a poor (wo)man's bidirectional ticket integration)
- JIRA: http://issues.opennms.org/browse/NMS-8846
- Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1072-1

NMS-8846: update ticket ID and state via REST

---

opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounder.java
opennms-alarms/jms-northbounder/pom.xml
opennms-alarms/jms-northbounder/src/test/java/org/opennms/netmgmt/alarmd/northbounder/jms/JmsNorthBounderTest.java

Some fields of NorthboundAlarm that are interesting to us are not currently available for replacement. Furthermore, Date fields are currently being converted to string via Date.toString(), which is less than ideal and especially annoying when you aren't sure of the timezone of the JVM in which OpenNMS is running.
This PR depends on/includes the patches re: ISO-8601 strings in #1084 / HZN-924. 
- JIRA: http://issues.opennms.org/browse/NMS-8837
- Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1073

NMS-8837: improve nb alarm mappings

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
features/events/daemon/src/main/resources/META-INF/opennms/applicationContext-eventDaemon.xml
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/processor/EventExpanderTest.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
opennms-dao-mock/src/main/resources/META-INF/opennms/applicationContext-mockEventd.xml
opennms-services/src/test/java/org/opennms/netmgt/mock/OpenNMSITCase.java

Here we remove the synchronized statement from expandEvent(Event) and set the EventUtil instead as a member variable instead of always accessing via the singleton, which allows for multiple events to be expanded in parallel.
As far as a I can tell, there is no need to make expandEvent(Event) synchronized, since all of the work that is being performed is thread safe.
* JIRA: https://issues.opennms.org/browse/HZN-935
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1086

HZN-935: Allow multiple events to be expanded in parallel.

---

opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/Requisition.js

Provisioning UI: The filtered list of nodes is not updated after removing a node.
* JIRA: http://issues.opennms.org/browse/NMS-8814
The solution was verified on my testing environment.

NMS-8814: Provisioning UI: The filtered list of nodes is not updated after removing a node.

---

opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc

Give users a hint to verify DNS A record settings. Wrong A record settings can prevent OpenNMS from start and a exception is shown.
- JIRA: http://issues.opennms.org/browse/NMS-8616
- Bamboo:

NMS-8616: Add caution section for wrong DNS A Resource Record

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/OutageRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/OutageRestServiceIT.java

Outage ReST service forNode use case calculates dates incorrectly
* JIRA: http://issues.opennms.org/browse/NMS-8823
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1082

NMS-8823: Outage ReST service forNode use case calculates dates incorrectly

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AggregateTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/CollectionTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ErrorStatus.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ErrorStatusException.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SingleInstanceTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolver.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpWalker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/internal/ServiceBasedStrategyResolverTest.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/AgentGenErrException.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/AgentNoSuchNameException.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/RequestPdu.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/TestAgentTest.java

This PR changes the SNMP tracker code to handle handle all known `error-status` codes from [RFC 3416](https://tools.ietf.org/html/rfc3416).
For the most part it treats the write-related responses as fatal (throwing an exception) but attempts retry for most other errors, in the hopes they may be transient.
While I have tested this with a few simple (mostly Linux-based) devices, I'd love a second set of eyes to not only look through the patches, but give this branch a shot and confirm I don't do anything heinous.
There is probably more refactoring that could be done to reduce duplicate code between the `AggregateTracker`, `ColumnTracker`, and `SingleInstanceTracker` classes, but I didn't attempt more rearranging for the sake of keeping the changes small.  The only change that touches more …

NMS-8671 - handle SNMP error-status > 5

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/daemon-config-files/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/daemon-config-files/pollerd.adoc

Initialize structure for configuration reload events. Create initial documentation for Pollerd related configuration files and if a restart is required or not.
- JIRA: http://issues.opennms.org/browse/NMS-8550
- Bamboo: Do not worry, we add a link to our continuous integration system here

NMS-8550: Pollerd configuration files

---

features/newts/src/main/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategy.java
features/newts/src/test/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategyTest.java
opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc

I've increased the minimum step size to 300 seconds when using Newts, which coincides with the default collection interval.
I've also improved the explanation of the step size handling, please comment if any of this is not clear.
JIRA: https://issues.opennms.org/browse/NMS-8498
Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1090

NMS-8498: Explain the behavior of the step size when using the Measurements API

---

features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css

* JIRA: https://issues.opennms.org/browse/NMS-8771
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1096

NMS-8771: The Alarms Details widget on the OpsBoard shows the text on green instead of black

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java

This PR changes the provisiond scan to:
1. fix rescans of nodes to update the iphostname
2. change the update to set the iphostname on _all_ interfaces, rather than just the primary
* JIRA: http://issues.opennms.org/browse/NMS-8874

NMS-8874 - fix iphostname setting on node rescan

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java

This PR fixes node label updates on rescan, when the node is temporarily unreachable or cannot be resolved.
* JIRA: http://issues.opennms.org/browse/NMS-8880

NMS-8880 do not update node labels when IP has not changed on rescan

---

features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
smoke-test/src/test/java/org/opennms/smoketest/NodeDetailPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-8872
The NPE only occurs if you navigate to the Topology Map via a link (e.g. "View in Topology") and have not been on the Topology ever before (there is no history for the user).
In that case, the base `TopologyProvider` is not initialized correctly. 
Please verify on an instance without this patch, as follows:
* Ensure you have at least one node
* Log out of OpenNMS
* Delete the user's history (see below for instructions)
* Log in
* Go to the node details page
* Click "View in Topology" (BAM, Exception)
With the patch, there is less BAM.
**Delete the user's history**
* Login to the Karaf Shell
* Install topology shell commands: `install mvn:org.opennms.features.topology/org.opennms.features.topology.shell`
* Valid commands are …

NMS-8872: Fall back to default GraphProvider before handling url parameters

---

opennms-base-assembly/src/main/filtered/bin/checknsc

Add SLF4J API and SLF4J Log4J libraries to class path call.
* JIRA: http://issues.opennms.org/browse/NMS-8885

NMS-8885: Fix checknsc NoClassDefFoundError for LoggerFactory

---

opennms-services/src/main/java/org/opennms/netmgt/poller/QueryManagerDaoImpl.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AssetRecordResource.java

Updating assets/categories through ReST affects Forced Unmanaged services.
* JIRA: http://issues.opennms.org/browse/NMS-8879
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1105
The solution has been tested on a VM running Meridian 2016.

NMS-8879: Updating assets/categories through ReST affects Forced Unmanaged services.

---

opennms-webapp/src/main/webapp/element/node.jsp
opennms-webapp/src/main/webapp/includes/nodeAvailability-box.jsp

Show availability box for the primary interface if the node has more than 10 interfaces.
* JIRA: http://issues.opennms.org/browse/NMS-8653
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1102
The solution was tested on VM running Meridian 2016.

NMS-8653: Show availability box for the primary interface if the node has more than 10 interfaces.

---

features/themes/dashboard-theme/src/main/java/VAADIN/themes/dashboard/styles.css

The title for Dashlets in Opsboard and Wallboard where color red and indicated NOC users there is a problem in this Dashlet they have to look into. The title color has no monitoring functionality and the color is neutralized.
* JIRA: http://issues.opennms.org/browse/NMS-7911
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1099

NMS-7911: Neutralize Opsboard and Wallboard Dashlet titles 

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/daemon-config-files/eventd.adoc

* JIRA: http://issues.opennms.org/browse/NMS-8552
Add daemon configuration files for Eventd and describe which files require system restart or can be reloaded with a daemon reload event.

NMS-8552: Added documentation for Eventd's configuration files

---

opennms-doc/guide-install/src/asciidoc/text/opennms/introduction.adoc

Added PostgreSQL version 9.6 as newest supported version in the install guide.
* JIRA: http://issues.opennms.org/browse/NMS-8892

NMS-8892: Add newest supported version number for PostgreSQL

---

core/logging-api/src/main/java/org/opennms/core/logging/Logging.java
opennms-jetty/src/main/java/org/opennms/netmgt/jetty/MDCHandler.java
opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

JIRA: https://issues.opennms.org/browse/NMS-8895
With the upgrade to Jetty 9.3.x, log statements from servlets, and errors from JSP pages no longer appear in web.log as they used to. 
This patch restores the behavior we've gotten used to with Jetty 8.4.x by setting the log prefix to 'web' before all of the handlers are executed.

NMS-8895: Jetty logging behavior has changed

---

opennms-base-assembly/src/main/filtered/etc/database-reports.xml
opennms-base-assembly/src/main/filtered/etc/jasper-reports.xml
opennms-base-assembly/src/main/filtered/etc/report-templates/TopIOWait.jrxml
opennms-base-assembly/src/main/filtered/etc/statsd-configuration.xml

See issue [NMS-8739](http://issues.opennms.org/browse/NMS-8739).
A simple jasper reports that shows the top 20 nodes by I/O Wait.
Works for net-snmp nodes (sorry, no windows) and requires that Store By Foreign Source is enabled.
Crafted with love in Fulda by me and @indigo423 
- JIRA: http://issues.opennms.org/browse/NMS-8739

NMS-8739: top 20 nodes by I/O wait

---

container/features/src/main/resources/features.xml
features/events/syslog/pom.xml
features/events/traps/pom.xml
opennms-full-assembly/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/TrapTest.java

Wrapped blueprints for syslog and trap listeners in JARs so that they can be loaded from featuresBoot. Fixed missing zkclient dependency from camel-karaf.
* JIRA: http://issues.opennms.org/browse/NMS-8803
* JIRA: http://issues.opennms.org/browse/HZN-811
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1142

NMS-8803, HZN-811: Load Minion listeners from featuresBoot, fix zkclient

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpV3User.java
features/events/traps/pom.xml
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapReceiverImpl.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapReceiverImplTest.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdListenerBlueprintIT.java
features/events/traps/src/test/resources/trapd-configuration-withSnmpV3Users.html
features/events/traps/src/test/resources/trapd-configuration-withoutSnmpV3Users.html

Added equals()/hashCode() and Map comparison to make sure that the collection isn't reloaded when it has not changed. There are also some additional tests for the new code.
* JIRA: http://issues.opennms.org/browse/NMS-8708
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1136

NMS-8708: Make sure Trapd config isn't reloaded unnecessarily

---

features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapQueueProcessor.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java

* JIRA: http://issues.opennms.org/browse/NMS-8900
- Consider "v2" and "v2c" equivalent when accounting for traps by version
- Update Trapd integration test to verify v2 traps received as well as v1pull/1150

NMS-8900: Spurious Trapd error logs: unknown SNMP protocol version 'v2'

---

core/test-api/services/src/main/java/org/opennms/netmgt/poller/mock/MockMonitoredService.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoringLocationDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/ResponseTimeResourceType.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/ResponseTimeResourceTypeTest.java
opennms-model/src/main/java/org/opennms/netmgt/model/ResourcePath.java
opennms-model/src/test/java/org/opennms/netmgt/model/ResourcePathTest.java
opennms-services/src/main/java/org/opennms/netmgt/poller/LatencyCollectionResource.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptor.java
opennms-services/src/main/java/org/opennms/netmgt/threshd/LatencyThresholdingSet.java
opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptorIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptorPersistenceTest.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/LatencyThresholdingSetIT.java

JIRA: https://issues.opennms.org/browse/NMS-8776
With this patch, response times for nodes in a non-default location are now stored in `$OPENNMS_HOME/share/rrd/response/$LOCATION/$IP/`. Response times for nodes in the default location continue to be stored in `$OPENNMS_HOME/share/rrd/response/$IP/`

NMS-8776: Store reponse times by location.

---

opennms-base-assembly/src/main/filtered/etc/log4j2.xml

JIRA: https://issues.opennms.org/browse/NMS-8813
Here we decrease the log level on `org.snmp4j.transport` in order to suppress the non-fatal interrupted warnings. This is a new log message added in SNMP4J 2.4.x, which we pulled in NMS-8226.
Addressing the root cause requires more code changes then I'm comfortable with doing in 2016.1.4 or 18.0.3, so I suggest we revert this and address it in 19.0.0 instead.

NMS-8813: Suppress SNMP4J's InterruptedExceptions

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalker.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpWalker.java
core/snmp/impl-snmp4j/pom.xml
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JWalker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpTrackerIT.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategyTest.java
core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java
core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/LocationAwareSnmpClientIT.java
core/test-api/lib/src/main/java/org/opennms/core/test/MockLogAppender.java
features/juniper-tca-collector/src/main/java/org/opennms/netmgt/collectd/tca/TcaCollectionSet.java
features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaDataIT.java
features/nrtg/protocolcollector/tca/src/main/java/org/opennms/nrtg/protocolcollector/tca/internal/TcaProtocolCollector.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/HostResourceSwRunMonitor.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/NetScalerGroupHealthMonitor.java
opennms-provision/opennms-snmp-scanners/src/main/java/org/opennms/netmgt/provision/scan/snmp/AbstractSnmpScanner.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorITCase.java

JIRA: https://issues.opennms.org/browse/NMS-8813
Here we address the root cause of the InterruptedException we have observed while using SNMP4J. The problem was due to the fact that we attempted to close the session within the callback thread, which prevented the SNMP4J library from cleanly closing the session, and logging the interrupted warning.
Calls to SnmpUtils.createWalker() now require an explicit close on the caller's behalf, which can be done using a `try-with-resources` block for synchronous calls, or a reaper thread when using asynchronous calls. To the best of my knowledge, all existing calls have been updated to use either of these and close the session.

NMS-8813: Address SNMP4J's InterruptedExceptions

---

features/ticketing/jira-client/dependency-reduced-pom.xml
features/ticketing/jira-client/pom.xml

* JIRA: https://issues.opennms.org/browse/NMS-8906
Please merge AFTER PR https://github.com/OpenNMS/opennms/pull/1161
To verify if this works, install the `jira-troubleticketer` plugin and afterwards type in the following command in the Karaf Shell: `jira:list-projects -h https://issues.opennms.org -a`
This should list all projects visible to an anonymous (or not logged in) user.

NMS-8906: Make the Jira Ticketer Plugin work with https secured jira instances

---

debian/control
debian/rules
tools/packages/opennms/opennms.spec

This PR merges the XML plugin into `opennms-core` in the packaging, since the new elasticsearch changes mean the default configs point to the xml plugin class.
I have confirmed that upgrades from 18 to this branch work properly even if the XML plugin is installed, on both debian and centos systems.
I'd appreciate it if someone would eyeball this and let me know if anything looks odd, but I think everything's good.
* JIRA: http://issues.opennms.org/browse/NMS-8697

NMS-8697: merge the XML collector into the core package

---

features/events/traps/blueprint-trapd-listener.xml
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapReceiverImpl.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapReceiverImplTest.java

This PR makes it so the trapdConfig SNMPv3 user update code *only* updates the SNMPv3 user list, rather than consuming all of the `TrapdConfiguration`.  This keeps the Minion from attempting to reinitialize the SNMP listener with the hostname and port coming from the OpenNMS host, rather than its own config.
* JIRA: http://issues.opennms.org/browse/HZN-931

HZN-931: only reinitialize SNMPv3 users on update

---

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/FasterFilesystemForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FasterFilesystemForeignSourceRepositoryTest.java
opennms-provision/opennms-provision-persistence/src/test/resources/org/opennms/netmgt/provision/persist/emptyContext.xml

Can't save cached requisition associated with HTTP when scheduling the import through provisiond-configuration.xml
* JIRA: http://issues.opennms.org/browse/NMS-8912
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1171
I tested the solution on a VM running Meridian 2016, and on my machine running release-19.0.0

NMS-8912: Can't save cached requisition associated with HTTP when scheduling the import through provisiond-configuration.xml

---

features/ticketing/remedy-integration/pom.xml

This should prevent the long filename failures in Bamboo.
* JIRA: http://issues.opennms.org/browse/NMS-8940
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1191

NMS-8940: Remove the urls from wsdl2java config

---

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/aix-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/ejn-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/fortinet-fortigate-application-v5.2-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/framerelay-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/juniper-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/mcast-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/pfsense-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/snmp-informant-graph.properties

Fix invalid graph templates.
* JIRA: http://issues.opennms.org/browse/NMS-8907
The only pending templates to fix are the big DS and invalid DS, as that requires changes on *datacollection-config.xml files.
Remaining errors:
* ERROR(fortinet.fgApFTPStatsEntry.connection): Invalid DS fgApFTPMaxConnections (it has more than 19 characters)
* ERROR(fortinet.fgWebChDskStsEntry): Invalid DS fgWebCacheDiskMisses (it has more than 19 characters)
* ERROR(netapp.diskio): Invalid DS naMiscLowDiskReadBytes (it has more than 19 characters)
A new PR against release-19.0.0 will be created to fix the invalid DS once this one is merged.
All the errors fixed so far have been verified against latest RRDtool 1.5.x. If someone …

NMS-8907: Fix invalid graph templates (Second Phase)

---

container/features/src/main/resources/features.xml

The version of Zookeeper that comes with Camel 2.14 has bad OSGi metadata so we need to upgrade it one micro version.
* JIRA: http://issues.opennms.org/browse/NMS-8929
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1193

NMS-8929: Upgrade Zookeeper inside camel-kafka

---

features/wsman/src/main/java/org/opennms/netmgt/collectd/WsManCollector.java

JIRA: https://issues.opennms.org/browse/NMS-8923
With this patch we now show a better error message in the alarm when the WsManCollector fail.

NMS-8923: WS-Man collection fail with unknown reason code 2

---

opennms-base-assembly/src/main/filtered/etc/report-templates/TotalBytesTransferredByInterface.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/PeakTraffic_subreport.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/TotalBytesTransferredByInterface_subreport1.jrxml

PeakTraffic_subreport.jrxml was mixing up bits and Bytes
TotalBytesTransferredByInterface_subreport1.jrxml was doing a sum of "bytes per seconds" whereas it must do a sum of "bytes"
Caution: Make sure your Bamboo stuff tests jasper reports compilation as I didn't do it (beucase too time-consuming and https://issues.opennms.org/browse/NMS-4552)
* JIRA: https://issues.opennms.org/browse/NMS-8926

NMS-8926: Fix calculation errors in 2 jasper reports

---

features/events/syslog/blueprint-syslog-handler-default.xml
features/events/syslog/blueprint-syslog-handler-kafka-default.xml
features/events/syslog/blueprint-syslog-handler-kafka.xml
features/events/syslog/blueprint-syslog-handler-minion.xml
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogConnectionHandlerDefaultImpl.java
features/events/traps/blueprint-trapd-handler-default.xml
features/events/traps/blueprint-trapd-handler-kafka-default.xml
features/events/traps/blueprint-trapd-handler-kafka.xml
features/events/traps/blueprint-trapd-handler-minion.xml
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapNotificationHandlerDefaultImpl.java

This PR limits the size of all of the SEDA queues and Executor queues to prevent OOMs under high load and it switches the Kafka producers on Minion to "async" mode to increase throughput.
Some of these changes will conflict with the sink work (since the SEDA queues have been removed) but the Kafka endpoint tweak needs to be merged over into the sink branch.
* JIRA: http://issues.opennms.org/browse/NMS-8948
* JIRA: http://issues.opennms.org/browse/NMS-8777

NMS-8948, NMS-8777: Minion performance fixes for Kafka

---

opennms-config-model/src/main/castor/enlinkd-configuration.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfig.java
opennms-config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfigManager.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridgeTopology.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/scheduler/Scheduler.java
opennms-services/src/test/java/org/opennms/netmgt/enlinkd/Nms7918EnIT.java

This is a Fix for Issue NMS-8896
Memory Leak for enhancedLinkd
Check details on https://issues.opennms.org/browse/NMS-8896
Cretaed a new configuration attribute max_bft with default value 1.
The BridgeDiscovery is done if the number of bridge forwarding table saved into memory is less then max_bft. 
This is a simple mechanism to save memory to be exausted by the bridge forwarding table.

NMS-8896: Address memory leak in Enhanced Linkd

---

opennms-base-assembly/src/main/filtered/bin/opennms

* JIRA: http://issues.opennms.org/browse/NMS-8962
Should be zero-impact, but review requested since start/stop is pretty visible and a bit fragile. Bamboo pending.

NMS-8962: Skip /var/lock/subsys actions when running as unprivileged user

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AggregateTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/CollectionTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ErrorStatus.java
opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/workarounds/snmp.adoc
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/snmp/SnmpTable.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/snmp/SystemGroup.java
opennms-services/src/main/java/org/opennms/netmgt/capsd/snmp/SnmpTable.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpIfCollector.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpNodeCollector.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CdpGlobalGroupTracker.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/CiscoVtpTracker.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/Dot1dBaseTracker.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/IsisSysObjectGroupTracker.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocalGroupTracker.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfGeneralGroupTracker.java

This PR adds a few bug fixes and enhancements on top of the previous work done for [NMS-8671](https://issues.opennms.org/browse/NMS-8671).
* Change any `SET*`-related errors to be non-fatal, but to have 0 retries.  They are basically always going to be invalid in our case since OpenNMS doesn't perform any SETs, but we will generally want to continue without bailing to see if we can get more data despite a non-compliant response from an agent.
* Add `reportFatalErr()` and `reportNonFatalErr()` log methods to the `CollectionTracker` API so that all logging happens on the thread that is processing the request.
* Change the `ErrorStatus` handling to be configurable (sane defaults, but now it is possible to override the global SNMP client behavior to handle `error-status` responses in a …

NMS-8671: SNMP `error-status` Bug Fixes and Enhancements

---

features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/ElasticsearchNorthbounder.java
features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/ForwardingEventListener.java
features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/internal/DefaultAlarmForwarder.java
features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/internal/ESHeaders.java
features/elasticsearch/event-forwarder/src/main/java/org/opennms/features/elasticsearch/eventforwarder/internal/ElMappingLoader.java
features/elasticsearch/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml

This allows you to forward events to Elasticsearch even if they aren't stored in the OpenNMS database. There are also some logging speed improvements in this commit.
* JIRA: http://issues.opennms.org/browse/NMS-8963

NMS-8963: Add logAllEvents config parameter to Elasticsearch forwarder

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersister.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/resources/META-INF/opennms/applicationContext-alarmd.xml
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java

This should make Alarmd's event listener more efficient.
* JIRA: http://issues.opennms.org/browse/NMS-8957

NMS-8957: Alarmd: Only start transactions for events with alarm data

---

features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventForwarderQueueImpl.java
features/opennms-es-rest/main-module/src/main/resources/OSGI-INF/blueprint/mainModuleBlueprint.xml

This will prevent the es-rest forwarder from dropping events when the processing queue is full.
* JIRA: http://issues.opennms.org/browse/NMS-8966

NMS-8966: Added blockWhenFull configuration parameter to es-rest forwarder

---

features/minion/repository/pom.xml
features/minion/repository/src/main/resources/features.uri
features/minion/runInPlace.sh

JIRA: https://issues.opennms.org/browse/HZN-983
This patch allows includes Hawtio in the default repository, which some in handy for debugging.
We do not enable it by default in the RPMs.
It can be installed by running `feature:install hawtio-offline` in the Karaf shell (or adding it to featuresBoot.d).

HZN-983: Make the 'hawtio-offline' feature available on the default repository for Minion

---

opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectionUnknown.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpCollectionSet.java

JIRA: https://issues.opennms.org/browse/NMS-8976
Omit changing collectd's service status and generating events if the RPC is not executed.

NMS-8976: Prevent dataCollectionFailed alarms on OpenNMS restart with Minion

---

opennms-base-assembly/src/main/filtered/etc/datacollection/fortinet-fortigate-application-v5.2.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/netapp.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/fortinet-fortigate-application-v5.2-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/netapp-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/vmware6-graph-simple.properties
opennms-base-assembly/src/main/filtered/etc/vmware-datacollection-config.xml

Fixing invalid data sources (with more than 19 characters), to make them compatible with RRDtool.
The VMWare DS were also using invalid characters. It is recommended to use only alphanumeric characters for DS names.
* JIRA: http://issues.opennms.org/browse/NMS-8907
After these changes, the Perl script I made to validate the graph templates shows no errors.

NMS-8907: Invalid graph templates (fixing large/invalid DS)

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSConfiguration.java
features/springframework-security/src/test/java/org/opennms/web/springframework/security/OpenNMSConfigurationTest.java

JIRA: https://issues.opennms.org/browse/NMS-8925
Here we update the OpenNMSConfiguration to support delegating to both the system and Karaf implementations, as opposed to only delegating to the Karaf implementation.

NMS-8925: Delegate JAAS requests to both the system and the Karaf implementations.

---

opennms-base-assembly/src/main/filtered/etc/datacollection/netsnmp.xml
opennms-base-assembly/src/main/filtered/etc/threshd-configuration.xml

Include Net-SNMP (OID 1.3.6.1.4.1.8072) devices (such as Linux sytems) in the hrstorage threshold package and collect mib2-host-resources-storage data for Net-SNMP devices as this is a more reliable way of getting disk space data than using the net-snmp-disk MIB.
This change allows disk space to be monitored successfully on more devices. Examples are given in the JIRA ticket.
JIRA: http://issues.opennms.org/browse/NMS-5069

NMS-5069: Monitor disk space on more Net-SNMP devices and include in threshold package

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/includes/nodeCategory-box.jsp

When a node is assigned to a lot of surveillance categories, important information like recent events and outages get moved out of the view and requires scrolling through the whole node detail page. A max-height is set and a scroll bar just for the surveillance box is shown.
* JIRA: http://issues.opennms.org/browse/NMS-8989

NMS-8989: Make surveillance category box scrollable in node detail page

---

core/ipc/sink/api/src/main/java/org/opennms/core/ipc/sink/api/AggregationPolicy.java
core/ipc/sink/api/src/main/java/org/opennms/core/ipc/sink/api/MessageDispatcher.java
core/ipc/sink/api/src/main/java/org/opennms/core/ipc/sink/api/SyncDispatcher.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/aggregation/AggregatingSinkMessageProducer.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/aggregation/Aggregator.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/aggregation/ArrayListAggregationPolicy.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/aggregation/SinkAggregator.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AbstractMessageDispatcherFactory.java
features/bsm/service/api/pom.xml
features/datachoices/pom.xml
features/opennms-es-rest/feature/pom.xml
features/opennms-es-rest/main-module/pom.xml
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventForwarderImpl.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventForwarderQueueImpl.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/NodeCacheImpl.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/SayHello.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/archive/OnmsRestEventsClient.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/archive/OpenNMSHistoricEventsToEs.java
features/opennms-es-rest/main-module/src/main/resources/OSGI-INF/blueprint/mainModuleBlueprint.xml
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/rest/archive/manual/OpenNMSHistoricEventsToEsTest.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/rest/archive/manual/OpenNMSRestEventsClientTest.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/AlarmEventToIndexTest.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/RawEventToIndexTest.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/manual/ClientRecoveryTest.java

This PR adds config options so that you can forward all events (including 'donotpersist' events) to Elasticsearch and also adds support for batched 'index' operations so that multiple records can be sent to Elasticsearch in one Bulk API operation.
* JIRA: http://issues.opennms.org/browse/HZN-998
* JIRA: http://issues.opennms.org/browse/NMS-8963
* JIRA: http://issues.opennms.org/browse/NMS-9015

HZN-998, NMS-8963, NMS-9015: Add batching support to es-rest forwarder

---

core/db/src/main/castor/opennms-datasources.xsd
core/db/src/main/java/org/opennms/core/db/HikariCPConnectionFactory.java
core/test-api/db/src/main/java/org/opennms/core/test/db/TemporaryDatabaseExecutionListener.java
features/alarm-change-notifier/main-module/src/test/resources/opennms-datasources.xml

Happy turkey day!
* JIRA: https://issues.opennms.org/browse/NMS-8911
* Bamboo: http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1156

NMS-8911: Update TemporaryDatabaseExecutionListener to use HikariCP during tests

---

integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/JRobinDirectoryUtil.java
integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/jrobin/RrdXportCmdTest.java
opennms-base-assembly/src/main/filtered/etc/report-templates/ResponseTimeCharts.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeAvg_subreport.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_subreport.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTime_subreport1.jrxml

Added util method to escape colons in IP addresses so that reports can access RRD files in directories with IPv6 addresses in the path.
* JIRA: http://issues.opennms.org/browse/NMS-5450

NMS-5450: Escape colons in IPv6 directory paths in Jasper reports

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/support/RrdStatisticAttributeVisitor.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/RrdStatisticAttributeVisitorTest.java

Aggregators are declared as 'enum's : this makes them static and so shared between all statsd worker threads.
This PR declares them as a class intances ;...
JIRA: https://issues.opennms.org/browse/NMS-8944

NMS-8944: Statsd aggegators not reset between workers

---

features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/ElasticSearchInitialiser.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/OnmsJestResult.java

This PR puts a simple facade on top of the `JestResult` object to handle non-200 success (like `201 CREATED`).  It also changes a few other places we were checking specifically for 200 results to use the `isSuccess()` method.
* JIRA: http://issues.opennms.org/browse/NMS-9062

NMS-9062: use a facade to JestResult to do proper success-checking

---

features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/NodeCache.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/NodeCacheImpl.java
features/opennms-es-rest/main-module/src/main/resources/OSGI-INF/blueprint/mainModuleBlueprint.xml

Use a SynchronousQueue ThreadPoolExecutor to parallelize the Elasticsearch operations inside EventToIndex.
* JIRA: http://issues.opennms.org/browse/HZN-1022

HZN-1022: Added multithreading to ES REST processing

---

core/schema/src/main/liquibase/19.0.0/changelog.xml

This PR fixes an issue with upgrades to 19 when the user has defined a `localhost` location in `monitoring-locations.xml` or equivalent.
* JIRA: http://issues.opennms.org/browse/NMS-9102

NMS-9102: fix pre-existing 'localhost' monitoring location

---

core/ipc/rpc/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-server.xml
core/ipc/sink/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-ipc-client.xml
features/events/syslog/blueprint-syslog-listener-camel-netty.xml
features/events/syslog/blueprint-syslog-listener-javanet.xml
features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml
features/minion/container/scv/blueprint-scv.xml
features/minion/core/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/scv/jceks-impl/src/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Some of the blueprint CM properties were still set to ```update-strategy="none"``` to work around issues with Karaf integration tests. These test issues have been resolved so all properties should be set to ```update-strategy="reload"``` so that properties can be dynamically reloaded.

Changed all blueprint CM properties to reload

---

smoke-test/src/test/java/org/opennms/smoketest/minion/AbstractSyslogTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearch1Test.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearch2Test.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearch5Test.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogOverlappingIpAddressTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/TrapTest.java
smoke-test/src/test/resources/service-configuration-disable-alarmd.xml

This test refactor splits up the environments so that Elasticsearch can be tested against all versions. It should also be slightly faster since not all containers (Elasticsearch, 2nd Minion) are started for every test.

Split the SyslogTest into multiple tests

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java

This might reduce/eliminate packet drops under heavy trap load.
* JIRA: http://issues.opennms.org/browse/NMS-9111

NMS-9111: Increase the socket buffer size for the SNMP4J trap listener

---

opennms-services/src/main/java/org/opennms/netmgt/poller/PollerEventProcessor.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerTest.java

JIRA: https://issues.opennms.org/browse/NMS-9112
This fixes a regression introduced in NMS-7761.
When receiving events that cause pollerd to recompute it's schedule, it can end up re-scheduling services that we already scheduled. If the node or interface is subsequently delete, the duplicate services remain scheduled.

NMS-9112: Avoid scheduling services multiple times when handling node change events.

---

core/upgrade/src/main/java/org/opennms/upgrade/implementations/MagicUsersMigratorOffline.java
core/upgrade/src/test/java/org/opennms/upgrade/implementations/MagicUsersMigratorOfflineIT.java

The upgrade task for magic.users doesn't work on RPM based upgrades.
* JIRA: http://issues.opennms.org/browse/NMS-9109

NMS-9109: The upgrade task for magic.users doesn't work on RPM based upgrades

---

opennms-base-assembly/src/main/filtered/etc/rrd-configuration.properties
opennms-rrd/opennms-rrd-api/src/main/java/org/opennms/netmgt/rrd/RrdStrategyFactory.java
opennms-rrd/opennms-rrd-api/src/main/resources/META-INF/opennms/applicationContext-rrd.xml
opennms-rrd/opennms-rrd-api/src/main/resources/META-INF/opennms/component-rrd-tcp.xml

- Add a "userrd" properties which controls whether the RRD strategy writes to the DB.  If false, only the TCP strtagy is used if usetcp is true.  If usetcp is false, the strategy is null.
JIRA: http://issues.opennms.org/browse/NMS-9120

NMS-9120: Selection of non-disk RRD strategies

---

core/ipc/rpc/camel-impl/src/test/java/org/opennms/core/rpc/camel/EchoRpcBlueprintIT.java
core/ipc/rpc/camel-impl/src/test/java/org/opennms/core/rpc/camel/EchoRpcThreadIT.java
core/ipc/sink/camel-impl/src/test/java/org/opennms/core/ipc/sink/camel/HeartbeatSinkBlueprintIT.java
core/ipc/sink/camel-impl/src/test/java/org/opennms/core/ipc/sink/camel/HeartbeatSinkPerfIT.java
core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/LocationAwareSnmpClientIT.java
opennms-icmp/opennms-icmp-proxy-rpc-impl/src/test/java/org/opennms/netmgt/icmp/proxy/LocationAwarePingClientIT.java
opennms-icmp/opennms-icmp-proxy-rpc-impl/src/test/java/org/opennms/netmgt/icmp/proxy/LocationAwarePingSweepClientIT.java
opennms-provision/opennms-detectorclient-rpc/src/test/java/org/opennms/netmgt/provision/detector/client/rpc/LocationAwareDetectorClientIT.java

Made the RPC ITs consistent so that they can run without flapping. Please merge after this runs a couple more times in Bamboo. Not a blocker for 19.0.1.
* JIRA: http://issues.opennms.org/browse/NMS-9116

NMS-9116: Fix RPC integration tests

---

opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

NMS-9084: Add missing certAlias for ssl with jetty
* JIRA: http://issues.opennms.org/browse/NMS-9084

NMS-9084: Add missing certAlias for ssl with jetty

---

tools/packages/opennms/opennms.spec

NMS-9166: Fix permissions on opennms.service file for systemd
* JIRA: http://issues.opennms.org/browse/NMS-9166

NMS-9166: Fix permissions on opennms.service file for systemd

---

features/ncs/ncs-drools/src/test/resources/test-context.xml
opennms-correlation/drools-correlation-engine/pom.xml
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngineBuilder.java
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/config/EngineConfiguration.java
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/config/RuleSet.java
opennms-correlation/drools-correlation-engine/src/main/resources/META-INF/opennms/correlation-engine.xml
opennms-correlation/drools-correlation-engine/src/test/resources/test-context.xml
opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/AbstractCorrelationEngine.java

Add JMX instrumentation for the Drools Correlator to understand the the
working memory of each rule-set (a.k.a. engine)
* JIRA: http://issues.opennms.org/browse/NMS-9145

NMS-9145: Add JMX instrumentation for the Drools Correlator to understand the the working memory of each rule-set (a.k.a. engine)

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/CustomSyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogMessage.java
features/events/syslog/src/test/resources/etc/syslogd-configuration.xml

The regex statements for the ueiMatch configs in Syslogd were being passed either the syslog message with the ```process-name[process-id]:``` stanza still at the beginning, or they were being passed a full RFC 3164 text representation of the entire message. In either case, none of the out-of-the-box regex statements would match unless they had a ```^.*``` prefix that consumed the unexpected portions of the syslog messages.
This commit fixes that problem and cleans up the ConvertToEvent class.
* JIRA: http://issues.opennms.org/browse/NMS-6539

NMS-6539: Pass correct string to Syslogd ueiMatch regex statements

---

opennms-services/src/main/java/org/opennms/netmgt/syslogd/SyslogParser.java
opennms-services/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Assuming that syslog timestamps are in UTC is not correct: timestamps without a timezone should be assumed to be in the local timezone of the machine.
* JIRA: http://issues.opennms.org/browse/NMS-9201

NMS-9201: Changed SyslogParser to use the local timezone

---

opennms-model/src/main/java/org/opennms/netmgt/model/CdpLink.java

NMS-8897: NPE in CdpLink.toString()
Added control to check if the node is not
null and also if the cache address type is not null
* JIRA: http://issues.opennms.org/browse/NMS-8897

NMS-8897: NPE in CdpLink to String

---

opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIpAddrTableGetter.java

NMS-8667: Null ospfrouterid in NodeDiscoveryOspf
* JIRA: http://issues.opennms.org/browse/NMS-8667

NMS-8667: Null ospfrouterid in NodeDiscoveryOspf

---

core/schema/src/main/liquibase/19.1.0/changelog.xml
core/schema/src/main/liquibase/changelog.xml

Since we're bumping the version to 19.1.0, this PR changes the name of the liquibase changelog accordingly.

Create 19.1.0 changelog

---

core/test-api/elasticsearch/src/main/java/org/opennms/core/test/elasticsearch/JUnitElasticsearchServer.java

This will prevent the Bamboo machines from clustering together and disrupting integration tests.
* JIRA: http://issues.opennms.org/browse/NMS-9230

NMS-9230: Randomize Elasticsearch 1 cluster.name

---

opennms-model/src/main/java/org/opennms/netmgt/model/OspfElement.java

Fixed merge method in OspfElement
NMS-9218: OsPfRouterId not properly updated
Please use the [JIRA](https://issues.opennms.org) issue number and create a link in the JIRA issue back to this pull request so we have a quick reference from the issue to the pull request.
* JIRA: http://issues.opennms.org/browse/NMS-9218

Fix NMS-9218: OsPfRouterId not properly updated

---

core/lib/src/main/java/org/opennms/core/utils/TimeoutTracker.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java
features/opennms-es-rest/main-module/src/main/resources/OSGI-INF/blueprint/mainModuleBlueprint.xml
opennms-doc/guide-admin/src/asciidoc/text/plugins/opennms-es-rest.adoc
smoke-test/src/test/java/org/opennms/smoketest/minion/AbstractSyslogTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearch5OutageTest.java

These changes fix exception handling in the ```opennms-es-rest``` feature and add ```timeout``` and ```retries``` configuration params so that ES operations can be retried if the connection to the ES cluster fails.
The commits also include an enhancement to handle multiple ES URLs by providing a comma-separated list of URLs.
* JIRA: http://issues.opennms.org/browse/NMS-9197
* JIRA: http://issues.opennms.org/browse/NMS-9210

NMS-9197, NMS-9210: Add retries, timeouts, and exception handling for Elasticsearch forwarding

---

integrations/opennms-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/DnsProvisioningAdapter.java
integrations/opennms-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/DnsRecord.java
integrations/opennms-dns-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/DnsRecordTest.java
integrations/opennms-reverse-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/DefaultReverseDnsProvisioningAdapterService.java
integrations/opennms-reverse-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/ReverseDnsProvisioningAdapter.java
integrations/opennms-reverse-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/ReverseDnsProvisioningAdapterService.java
integrations/opennms-reverse-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/ReverseDnsRecord.java
integrations/opennms-reverse-dns-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/ReverseDnsRecordTest.java

Created a POC for setting a property
import.dns.level for setting the
domain suitable level for nsupdates
The DNS update needs that the zone exists on dns server.
We should be able to check against possible zone.
for example the label 
www.ess01.arsinfo.it 
can be stored as an A record either in zone 
NSUPDATE
zone arsinfo.it
www.ess01 1.2.1.1 A
otrherwise you can say
NSUPDATE
zone ess01.arsinfo.it
www 1.2.1.1 A
The actual implementation uses the last. I'd like to set up a level to try if level=2 then you try zone arsinfo.it.f:
NMS-9222: set the domain level in dns adapter
* JIRA: http://issues.opennms.org/browse/NMS-9222
Set up property with domain level....in opennms.properties:
importer.adapter.dns.level=3 (means use level 3 domain!)
Also added a property for dns reverse adapter to use …

Fix NMS-9222: set the domain level in dns adapter

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/CustomSyslogParser.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/Nms6730Test.java

This fixes a problem where the CustomSyslogParser does not capture the processName field if there are square brackets in the syslog message. Includes a test.
* JIRA: http://issues.opennms.org/browse/NMS-6730

NMS-6730: Fixed CustomSyslogParser capture of processName

---

opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
pom.xml

JIRA: https://issues.opennms.org/browse/NMS-9252
This adds support for globally changing the behavior of counter wraps using a system property. By default, we maintain the existing behavior, but we now have the option to ignore counter wraps and replace these with NaNs, by setting a system property.
Example screenshots are available in the JIRA issue.

NMS-9252: Upgrade Newts to 1.4.3

---

opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml

JIRA: https://issues.opennms.org/browse/NMS-9257
Here we modify the default downtime model to continue polling the service once an hour after a service has been offline for >= 5 days.

NMS-9257: Poll every hour instead of deleting the service after being down for 5 days.

---

opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml

To avoid filling up the kahadb storage limit with expired messages, we should just discard them. Users can reenable the DLQ easily by commenting out the section of ```opennms-activemq.xml```.
* JIRA: http://issues.opennms.org/browse/NMS-9203

NMS-9203: Discard expired messages instead of using the DLQ

---

core/lib/src/main/java/org/opennms/core/utils/StringUtils.java
features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java
features/vaadin-dashlets/dashlet-ksc/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/KscDashlet.java
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java
opennms-reporting/src/main/java/org/opennms/report/configuration/ConfigurationReportCalculator.java
opennms-reporting/src/main/java/org/opennms/report/configuration/ConfigurationReportRunner.java
opennms-reporting/src/main/java/org/opennms/report/inventory/InventoryReportCalculator.java
opennms-reporting/src/main/java/org/opennms/report/inventory/InventoryReportRunner.java
opennms-webapp/src/main/java/org/opennms/web/element/Service.java
opennms-webapp/src/main/java/org/opennms/web/filter/DateSqlType.java

To avoid memory bloat of Events in the Eventd backlog, I've added a method that will call java.util.Date.toString() and then call java.util.Date.setTime() to clear internal fields in the Date object to reduce heap space.
The inspiration for this change was a heap dump analysis where ~ 40% of the heap was being consumed by java.util.Date instances inside the Eventd backlog.
* JIRA: http://issues.opennms.org/browse/NMS-9091

NMS-9091: Added StringUtils.toStringEfficiently(Date)

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AggregateTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/CollectionTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SingleInstanceTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TableTracker.java
core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpWalker.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategy.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpWalker.java
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JWalker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpTrackerTest.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategyTest.java
core/snmp/integration-tests/src/test/resources/snmpTestDataError.properties

This PR fixes an issue with the new SNMP error-handling code that could cause loops.  It adds support for passing retries down into the tracker(s) and they, in turn, track retries and treat non-fatal errors as fatal if they have run out of retries.
* JIRA: http://issues.opennms.org/browse/NMS-9164

NMS-9164: handle retries inside trackers

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpAgentTimeoutException.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategyTest.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpCollectionSet.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorIT.java

JIRA: https://issues.opennms.org/browse/NMS-9234
This restores the behavior before 19.0.0 where the dataCollectionFailed alarms include a message of the form:
"SNMP data collection on interface 172.23.1.1 failed with 'Timeout retrieving..."
instead of the current:
"SNMP data collection on interface 172.23.1.1 failed with 'Unexpected exception..."

NMS-9234: Show a better error message when the SNMP agents time out.

---

opennms-config/src/main/java/org/opennms/netmgt/config/DefaultResourceTypesDao.java

* JIRA: http://issues.opennms.org/browse/NMS-9205
This fixes the reloading, but one must still trigger the reload of the datacollection config by touching `datacollection-config.xml`.

NMS-9205: Reload resource types if datacollection config changes

---

opennms-webapp/src/main/webapp/js/angular-onmsList-monitoringLocation.js
opennms-webapp/src/main/webapp/js/angular-onmsList-notification.js
opennms-webapp/src/main/webapp/js/angular-onmsList-outage.js
opennms-webapp/src/main/webapp/js/angular-onmsList-scanreport.js
opennms-webapp/src/main/webapp/js/angular-onmsList.js

This prevents infinite refresh loops in the monitoring location and Minion lists when you click quickly on the Next or Previous buttons.
* JIRA: http://issues.opennms.org/browse/NMS-7829

NMS-7829: Avoid refresh()/setOffset() loop in onmsList JS

---

opennms-base-assembly/src/main/filtered/bin/liquibase
opennms-base-assembly/src/main/filtered/bin/microblog-auth
opennms-base-assembly/src/main/filtered/bin/snmp-request
opennms-base-assembly/src/main/filtered/bin/system-report

This PR removes the inclusion of `opennms.conf` from a number of scripts where it doesn't make sense.
Support folks, since you're most likely to run into them, mind looking it over and let me know if there's any reason any of these still need to include it.
* JIRA: http://issues.opennms.org/browse/NMS-9068

NMS-9068: remove opennms.conf include from secondary scripts

---

dependencies/drools/pom.xml

The correlator compiles, and all its tests are passing.
* JIRA: http://issues.opennms.org/browse/NMS-9279

NMS-9279: Upgrade Drools to 6.5.0

---

container/features/src/main/resources/features.xml
features/datachoices/pom.xml

This was causing a bundle failure in the latest OpenNMS builds.
* JIRA: http://issues.opennms.org/browse/NMS-9283

NMS-9283: Fixed missing quartz dependency in datachoices feature

---

opennms-base-assembly/src/main/filtered/etc/service-configuration.xml

Redefine the start ordering of the OpenNMS daemons during bootstrap.
* JIRA: http://issues.opennms.org/browse/NMS-9280

NMS-9280: Redefine the start ordering of the OpenNMS daemons during bootstrap

---

features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/Log4j2StringAppender.java
pom.xml

This PR updates log4j2 to 2.8.1. Also, change the dependency management to use the log4j-bom which pins all log4j2 dependencies to the same version. (From https://logging.apache.org/log4j/2.x/maven-artifacts.html)
The big list of changes since 2.5 can be seen here: https://logging.apache.org/log4j/2.x/changes-report.html
* JIRA: http://issues.opennms.org/browse/NMS-9132

NMS-9132: Upgrade log4j2 to latest release 2.8.2

---

features/nrtg/api/src/main/java/org/opennms/nrtg/api/model/DefaultCollectionJob.java

This will avoid crashing the NRTG graphs when we cannot find metrics that we expect inside the DefaultCollectionJob.
* JIRA: http://issues.opennms.org/browse/NMS-8908

NMS-8908: Added null check when NRTG metrics cannot be found

---

core/lib/src/main/java/org/opennms/core/collections/RadixTreeNodeImpl.java
core/lib/src/main/java/org/opennms/core/utils/ConfigFileConstants.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/RadixTreeParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/RadixTreeSyslogParser.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/BufferParserTest.java
opennms-doc/guide-admin/src/asciidoc/text/events/events.adoc

A customized set of patterns can be put into ```$OPENNMS_HOME/etc/syslogd-grok-patterns.txt```.
* JIRA: http://issues.opennms.org/browse/HZN-1047

HZN-1047: Added ability to override patterns for RadixTreeSyslogParser

---

features/collection/persistence-tcp/src/main/java/org/opennms/netmgt/collection/persistence/tcp/QueuingTcpOutputStrategy.java

- Allow for the queue sleep time and offer wait time to be configurable via system properties.
JIRA: https://issues.opennms.org/browse/NMS-9282
Todo Review:

NMS-9282: Make TCP output queue parameters configurable

---

integrations/opennms-vmware/pom.xml
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/AbstractVmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareCimMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/RequisitionXmlAdapter.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImportRequest.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImportRequestAttribute.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionProvider.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionTool.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlConnection.java
integrations/opennms-vmware/src/main/resources/META-INF/opennms/component-dao.xml
integrations/opennms-vmware/src/main/resources/OSGI-INF/blueprint/blueprint.xml
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/VmwareImportRequestTest.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/MonitorListTest.java

JIRA: https://issues.opennms.org/browse/HZN-1021
Here we update the Vmware requisition handler to support the new `requisition://` protocol, while maintaining backward compatibility with the existing `vmware://` protocol style URLs.
With this in place, it should now be possible to provision and monitor Vmware servers using Minion.

HZN-1021: Update the Vmware requisition handler to implement the RequisitionHandler interface

---

features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/AlarmChangeEventConstants.java
features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/AlarmChangeNotificationClient.java
features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/MemosChangeNotificationClient.java
features/internal-plugins-descriptor/pom.xml
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/resources/eventsIndexTemplate.json
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/AlarmEventToIndexTest.java
opennms-base-assembly/src/main/filtered/etc/events/AlarmChangeNotifierEvents.xml
opennms-doc/guide-admin/src/asciidoc/text/plugins/opennms-es-rest-mapping-table.adoc

* JIRA: https://issues.opennms.org/browse/NMS-9276
* bamboo http://bamboo.internal.opennms.com:8085/browse/OPENNMS-ONMS1478-COMPILE
Canged name of alarm change event parm from 'severity' (p_severity)  to 'alarmseverity' (p_alarmseverity). 
Changed Elastic search configuration in eventsIndexTemplate.json  to treat p_alarmseverity, p_initialseverity and p_oldseverity as integers instead of text so that they can be ranked in kibana
Also fixed build of internal-plugins-descriptor/pom.xml  to remove suspected compile errors. (Previously these errors were logged but in fact were not effecting build)

NMS-9276: Elasticsearch integration avoid parm name conflicts for severity as integer

---

opennms-base-assembly/src/main/filtered/bin/provision.pl
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/ForeignSource.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Node.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisition.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisitions.js
opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/services/Requisitions.js

This PR escapes foreign sources and foreign IDs in ReST calls from `provision.pl` and the Angular requisitions editor UI.
* JIRA: http://issues.opennms.org/browse/NMS-9269

NMS-9269: escape foreignSource/foreignId in ReST calls

---

core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/KafkaMessageConsumerManager.java
features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
smoke-test/src/test/java/org/opennms/smoketest/minion/MinionHeartbeatOutageKafkaTest.java
smoke-test/src/test/java/org/opennms/smoketest/minion/MinionHeartbeatOutageTest.java

Catch exceptions when receiving messages from Kafka so that the consumer thread isn't stopped. Added system tests that restart Minion and OpenNMS and verify that heartbeats resume.
* JIRA: http://issues.opennms.org/browse/NMS-9225

NMS-9225: Prevent Kafka Heartbeat consumer from failing on startup

---

opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/MonitoringLocationJsonDeserializer.java
opennms-model/src/main/java/org/opennms/netmgt/model/MonitoringLocationJsonSerializer.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AlarmRestServiceBase.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/EventRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/OutageRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/OutageRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
opennms-webapp-rest/src/test/resources/v1/nodes.json

JIRA: https://issues.opennms.org/browse/NMS-9110
* Include the location name when rendering a OnmsNode object in JSON (already there in XML).
* Add joins on the alarms, events, nodes and outages endpoints, allowing these to be filtered by location.
* Add a simple example on how to filter by location

NMS-9110: Improve REST API support for node locations

---

container/features/src/main/resources/features.xml
core/spring/pom.xml
core/spring/src/main/java/org/opennms/core/spring/BeanUtils.java
opennms-ackd/src/main/resources/META-INF/opennms/applicationContext-ackd.xml
opennms-ackd/src/main/resources/beanRefContext.xml

The beanRefContext.xml for Ackd contained an old stanza for loading component-service.xml contexts. This should be removed to prevent these contexts from being loaded twice: once by the webapp (the correct place) and again by Ackd.
* JIRA: http://issues.opennms.org/browse/NMS-8610

NMS-8610: Stop Ackd from loading component-service.xml contexts

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java

JIRA: https://issues.opennms.org/browse/NMS-9233
Use a cached thread pool, instead of a single thread, to close sessions since the call to
close can take up to 60 seconds by default (see org.snmp4j.SNMP4JSettings#threadJoinTimeout).

NMS-9233: Fix thread leak in SnmpUtils

---

core/ipc/rpc/camel-impl/src/main/java/org/opennms/core/rpc/camel/CamelRpcServerProcessor.java
core/ipc/rpc/camel-impl/src/main/java/org/opennms/core/rpc/camel/CamelRpcServerRouteManager.java
core/ipc/rpc/camel-impl/src/main/resources/META-INF/opennms/applicationContext-rpc-client-camel.xml
core/ipc/rpc/camel-impl/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-server.xml
core/ipc/rpc/camel-impl/src/test/java/org/opennms/core/rpc/camel/EchoRpcBlueprintIT.java
core/ipc/rpc/camel-impl/src/test/java/org/opennms/core/rpc/camel/EchoRpcIT.java
core/ipc/sink/camel-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-camel.xml
core/ipc/sink/camel-impl/src/test/java/org/opennms/core/ipc/sink/camel/HeartbeatSinkBlueprintIT.java
core/ipc/sink/camel-impl/src/test/java/org/opennms/core/ipc/sink/camel/SinkBlueprintMessageFailureIT.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/DispatcherState.java
core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/LocationAwareSnmpClientIT.java
core/test-api/lib/src/main/java/org/opennms/core/test/MockLogAppender.java
features/elasticsearch/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
opennms-provision/opennms-detectorclient-rpc/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-provision/opennms-detectorclient-rpc/src/test/java/org/opennms/netmgt/provision/detector/client/rpc/LocationAwareDetectorClientIT.java
pom.xml

The syslog receiver code still uses Netty 3 and cannot switch to Netty 4 without this minor Camel upgrade from 2.14.1 to 2.14.4.
This branch also contains additional fixes for the RPC code:
- Avoid starting the context manually CamelRpcServerRouteManager.
- Added tests to make sure that overriding ```CamelLogDebugBodyMaxChars``` is working.
- Fixed ConcurrentModificationException in MockLogAppender.
This code has been running in Bamboo continuously without failure.
* JIRA: http://issues.opennms.org/browse/NMS-9113
* JIRA: http://issues.opennms.org/browse/NMS-9116

NMS-9113, NMS-9116: Upgrade to Camel 2.14.4 to fix Netty4 support, RPC fixes

---

container/karaf/src/main/filtered-resources/etc/org.opennms.features.geocoder.google.cfg
features/geocoder/google/src/main/java/org/opennms/features/geocoder/google/GoogleGeocoderService.java
features/geocoder/google/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/geocoder.adoc

* JIRA: https://issues.opennms.org/browse/NMS-7148
Backports default socket timeout setting for the google geocoder service from `foundation-2017` to `foundation-2016`. The original issue was NMS-8875: https://issues.opennms.org/browse/NMS-8875

NMS-8875: Make timeout of Google Map API http client configurable i

---

core/ipc/sink/camel-impl/src/main/java/org/opennms/core/ipc/sink/camel/CamelMessageConsumerManager.java
core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AbstractMessageConsumerManager.java
core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/KafkaMessageConsumerManager.java
opennms-doc/guide-admin/src/asciidoc/text/minion/kafka.adoc
smoke-test/pom.xml
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearchBufferingTest.java
smoke-test/src/test/resources/opennms.properties.d/sink-initial-sleep-time.properties
smoke-test/src/test/resources/org.apache.karaf.features.cfg
smoke-test/src/test/resources/service-configuration-disable-alarmd.xml
smoke-test/src/test/resources/service-configuration.xml

This PR adds a ```org.opennms.core.ipc.sink.initialSleepTime``` system property that can be used to delay sink consumers from registering for messages to give the rest of the event system (ie. Elasticsearch forwarding) time to start up.
* JIRA: http://issues.opennms.org/browse/NMS-9294

NMS-9294: Add initialSleepTime to IPC sink code

---

opennms-base-assembly/src/main/filtered/etc/vacuumd-configuration.xml
opennms-model/src/main/java/org/opennms/netmgt/model/TroubleTicketState.java

This PR fixes the incorrect tt state in vacuumd, and also changes the state object to have explicit numbers associated with them to be sure that they don't change.
* JIRA: http://issues.opennms.org/browse/NMS-4648

NMS-4648: fix incorrect trouble ticket state in vacuumd

---

container/standalone/pom.xml

This cleans up the Karaf distro that is unpacked into ```target``` as an intermediate step in building the ```container/standalone``` project (to save disk space during builds).
* JIRA: http://issues.opennms.org/browse/NMS-9332

NMS-9332: Added post-integration-test cleanup to container/standalone

---

core/icmp-jna/src/main/java/org/opennms/jicmp/jna/NativeDatagramSocket.java
opennms-icmp/opennms-icmp-api/src/main/java/org/opennms/netmgt/icmp/PingerFactoryImpl.java
opennms-icmp/opennms-icmp-best/src/main/java/org/opennms/netmgt/icmp/best/BestMatchPinger.java
opennms-icmp/opennms-icmp-best/src/main/java/org/opennms/netmgt/icmp/best/BestMatchPingerFactory.java

This PR fixes the `BestMatchPinger` to handle IPv4-only systems better.  It changes the default pinger factory to the `BestMatchPingerFactory` and makes sure that when trying pingers, IPv4 and IPv6 initialization happens at the time of testing, rather than at the time of first use.
The reason for this is that on IPv4-only systems, it would try pinging the local host address using the `Jni6Pinger`, which would *only* call `initializev4()` and it would pass and accept the `Jni6Pinger` as "best", but then at runtime when full v4/v6 initialization happens, it would die.
Finally, the PR changes some of the logging to not show full stack traces without enabling TRACE debugging, as the output was kind of scary and not terribly useful for regular every day use.
* JIRA: …

NMS-9331: fix BestMatchPinger to work with IPv4-only systems

---

core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Starter.java

JIRA: https://issues.opennms.org/browse/NMS-9261
Set `org.opennms.newts.nan_on_counter_wrap=true` on startup without changing the configuration files, and creating a .rpmnew file.

NMS-9261: Make org.opennms.newts.nan_on_counter_wrap=true by default.

---

opennms-doc/guide-admin/src/asciidoc/text/notifications/strategies/mattermost.adoc
opennms-doc/guide-admin/src/asciidoc/text/notifications/strategies/slack.adoc

Reworked Mattermost and Slack sections. More basic starter example with full
enumeration of all currently supported options. Linked to incoming webhook docs
for both platforms.
* JIRA: http://issues.opennms.org/browse/NMS-9362

NMS-9362: Tweak Mattermost notification docs not to specify a channel

---

opennms-doc/guide-install/src/asciidoc/text/opennms/debian.adoc
opennms-doc/guide-install/src/asciidoc/text/opennms/rhel.adoc

This PR adds documentation on disabling automatic upgrade of OpenNMS for yum and apt users.
* JIRA: http://issues.opennms.org/browse/NMS-9127

NMS-9127: document disabling package upgrade while running

---

opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml
opennms-services/pom.xml
opennms-services/src/test/java/org/opennms/netmgt/collectd/HttpCollectorIT.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorIT.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorMinMaxValIT.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorWithMibPropertiesIT.java
opennms-services/src/test/java/org/opennms/netmgt/mock/OpenNMSIntegrationTestCaseIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/BSFNotificationStrategyIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/HttpNotificationStrategyIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/MattermostNotificationStrategyIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotificationsITCase.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/SlackNotificationStrategyIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PathOutageManagerDaoIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollContextIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerRpcTimeoutIT.java
opennms-services/src/test/java/org/opennms/netmgt/statsd/StatsdIT.java
opennms-services/src/test/java/org/opennms/netmgt/statsd/StatsdValuesIT.java
opennms-services/src/test/java/org/opennms/netmgt/utils/NodeLabelIT.java
opennms-services/src/test/java/org/opennms/netmgt/utils/TransactionAwareEventForwarderIT.java
opennms-services/src/test/resources/etc/rpctimeout-poller-configuration.xml

Moved the ```deadLetterStrategy``` tag inside the existing ```policyEntry``` tag so that it works properly. Added a test to make sure that the DLQ is not created when messages expire.
* JIRA: http://issues.opennms.org/browse/NMS-9203

NMS-9203: Fixed deadLetterStrategy config

---

container/features/src/main/resources/features.xml
dependencies/camel/pom.xml
features/alarm-change-notifier/feature/pom.xml
features/alarm-change-notifier/main-module/pom.xml
features/alarm-change-notifier/pg-jdbc-utils/pom.xml
features/alarm-change-notifier/pom.xml
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogReceiverCamelNettyImpl.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdEventdLoadIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdImplementationsIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdLoadIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdReceiverCamelNettyIT.java
features/events/traps/pom.xml
pom.xml

This will upgrade us from the deprecated ```camel-netty``` component to the newer ```camel-netty4``` component. I also updated ```SyslogReceiverCamelNettyImpl``` to support the Camel async API.
* JIRA: http://issues.opennms.org/browse/NMS-9319

NMS-9319: Upgrade from camel-netty to camel-netty4

---

opennms-assemblies/minion/src/main/filtered/debian/control
tools/packages/minion/minion.spec

This PR adds JICMP and JICMP6 as dependencies to the RPM and Debian Minion packages.  I have confirmed on both platforms that the Minion uses the BestMatchPinger properly, and ends up with the JNI version(s) of the plugins.
* JIRA: http://issues.opennms.org/browse/HZN-492

HZN-492: add jicmp* dependencies to Minion

---

features/bsm/daemon/pom.xml
features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/BusinessServiceStateMachine.java
features/bsm/service/api/src/main/java/org/opennms/netmgt/bsm/service/model/AlarmWrapper.java
features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/AlarmWrapperImpl.java
features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/mock/MockAlarmWrapper.java
features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/BsmTestUtils.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.bsm/src/main/java/org/opennms/features/topology/plugins/topo/bsm/simulate/SimulationAwareStateMachineFactory.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmLifecycleEventsIT.java
opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml
opennms-base-assembly/src/main/filtered/etc/vacuumd-configuration.xml

JIRA: https://issues.opennms.org/browse/NMS-9369
Here we introduce a new 'alarmDelete' lifecycle event and update the default automations responsible for deleting alarms to generate these. We also add support to bsmd for handling these, and making sure that deleted alarms are properly accounted for when performing the scheduled poll of the alarm table.
With these changes, if a business service references an alarm that is deleted by a vacuumd automation, it's state will be immediately updated. Similarly, if a business service references an alarm, and that alarm is deleted by some other means, the business service will be updated on the next poll.

NMS-9369: Update business service states properly when alarms are deleted

---

opennms-model/src/main/java/org/opennms/netmgt/model/OspfElement.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/OspfIpAddrTableGetter.java

NMS-9374: Insert/Update OspfElement: null value in column "ospfrouteridifindex" violates not-null constrain
* JIRA: http://issues.opennms.org/browse/NMS-9374

NMS-9374 Fixed Insert/Update OspfElement

---

features/minion/heartbeat/common/src/main/java/org/opennms/minion/heartbeat/common/MinionIdentityDTO.java
features/minion/heartbeat/common/src/test/java/org/opennms/minion/heartbeat/common/MinionIdentityDTOTest.java
features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
features/minion/heartbeat/producer/src/main/java/org/opennms/minion/heartbeat/producer/HeartbeatProducer.java

JIRA: https://issues.opennms.org/browse/NMS-9371
Improve the heartbeat generation to avoid generating floods of messages after being disconnected for a long period, and include timestamps o avoid processing stale messages.

NMS-9371: Improve heartbeat generation and handling

---

opennms-doc/guide-install/src/asciidoc/text/minion/configure-minion.adoc

JIRA: https://issues.opennms.org/browse/NMS-9382

NMS-9382: Recommend using the failover: protocol when configuring Minion.

---

opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
smoke-test/src/test/java/org/opennms/smoketest/RestSessionIT.java

This avoids creation of sessions, and thus setting a session cockie,
when using the REST APIs using basic authentication. It still uses the
session for authentication if one already exists.
* JIRA: http://issues.opennms.org/browse/NMS-8093

NMS-8093: Never create sessions in REST-APIs

---

container/karaf/pom.xml
container/karaf/src/assembly/karaf.xml
container/standalone/pom.xml
container/standalone/src/assembly/bin.xml
features/minion/core/repository/pom.xml
opennms-assemblies/minion/pom.xml
opennms-assemblies/minion/src/assembly/minion.xml
opennms-full-assembly/pom.xml
pom.xml
tools/packages/opennms/opennms.spec

This is an alternate PR to https://github.com/OpenNMS/opennms/pull/1497 which does the sha1 generation in maven rather than generating after the fact in the debian/rpm packages.
* JIRA: http://issues.opennms.org/browse/HZN-950

HZN-950: create sha1 files for Karaf repositories

---

opennms-doc/guide-install/src/asciidoc/text/java/introduction.adoc

Add a hint to ensure users install the development kit.
* JIRA: http://issues.opennms.org/browse/NMS-9327

NMS-9327: Added warning to ensure the OpenJDK development kit is installed

---

core/ipc/rpc/api/src/main/java/org/opennms/core/rpc/api/RpcExceptionHandler.java
core/ipc/rpc/api/src/main/java/org/opennms/core/rpc/api/RpcExceptionUtils.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpCollectionSet.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableServiceConfig.java

JIRA: https://issues.opennms.org/browse/NMS-9381
* Use the visitor pattern for handling different scenarios.
* Support handling InterruptedException and RejectedExecutionException either
directly or wrapped as the cause.

NMS-9381: Improve and consolidate the RPC exception handling.

---

opennms-provision/opennms-detectorclient-rpc/pom.xml
opennms-provision/opennms-detectorclient-rpc/src/main/java/org/opennms/netmgt/provision/dns/client/rpc/DnsLookupClientRpcModule.java
opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/dns/command/DnsLookup.java
opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/dns/command/DnsReverseLookup.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultHostnameResolver.java

JIRA: https://issues.opennms.org/browse/NMS-9356
Support reverse lookups without requiring an A record in provisiond. See JIRA for details.

NMS-9356: Allow provisiond to perform reverse lookups without requiring an A record

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/AbstractServiceCollector.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/api/ServiceCollector.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectionSpecification.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpCollector.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdTest.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/MockServiceCollector.java

JIRA: https://issues.opennms.org/browse/NMS-9413
Validate the agent prior to scheduling the interface in order to ensure that the SNMP collector only gets scheduled to run against the primary interfaces.

NMS-9413: Validate the agent prior to scheduling the interfaces

---

protocols/radius/pom.xml
protocols/radius/src/test/java/org/opennms/protocols/radius/detector/RadiusAuthDetectorTest.java
protocols/radius/src/test/java/org/opennms/protocols/radius/monitor/MockRadiusServer.java
protocols/radius/src/test/java/org/opennms/protocols/radius/monitor/RadiusAuthMonitorTest.java
protocols/radius/src/test/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProviderTest.java

See https://issues.opennms.org/browse/NMS-9417
Added a maven dependency on tinyradius 1.0.1 (scope test)
Defined a mock radius server as Subclass of TinyRadiusServer
Used this internal radius server in tests (did not touch springsecurity however)

NMS-9417 : use an internal radius server for radius tests

---

bin/functions.pl

JIRA: https://issues.opennms.org/browse/HZN-1082
Here we set additional JVM command line flags that are required for compilation when Java >= 9 is detected.

HZN-1082: Conditionally expose required modules, packages and types when using Java 9.

---

features/jmx-config-generator/pom.xml
features/ticketing/otrs-integration-31/pom.xml
features/ticketing/tsrm-integration/pom.xml
pom.xml

JIRA: https://issues.opennms.org/browse/HZN-1095
Switching to cxf-xjc-plugin allows us to compile these modules under Java 9.

HZN-1095: Switch from using the maven-jaxb2-plugin to the cxf-xjc-plugin

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/BridgeTopologyDaoInMemory.java
opennms-model/src/main/java/org/opennms/netmgt/model/topology/BridgePort.java
opennms-model/src/main/java/org/opennms/netmgt/model/topology/SharedSegment.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkdService.java
opennms-services/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkdServiceImpl.java
opennms-services/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdIT.java
opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java

NMS-9455: BridgeTopology Discovery Mismatch after opennms restart
JIRA: http://issues.opennms.org/browse/NMS-9455
After a restart opennms is not able to properly discovery the bridge topology
This is related to the so called forwarders. 
There are bridge forwarding table entry that cannot be assigned to a shared segment.
A bft entry is assigned to a shered segment if and only if it is on the forwarding table of every BridgePort belongng to segment.
So if I have a shared segment with Bridge(A,a) Bridge(B,b) and Bridge(C,c) the macs assigned on segment are only the macs belonging to the intersection of the forwarding tables for port a,b and c.
Nevertheless there can be interesting forwarding entry that do not belong to the intersection as for example the entries for the mac bridge mac …

NMS-9455: BridgeTopology Discovery Mismatch after opennms restart

---

opennms-base-assembly/src/main/filtered/etc/trend-configuration.xml

* JIRA: https://issues.opennms.org/browse/NMS-9473
Please note that this applies only to 20.0.1 since these color changes do not exist in foundation-2017 yet.

NMS-9473: Fixed colors in default trend chart config

---

container/features/pom.xml
container/features/src/main/resources/features.xml
features/amqp/alarm-northbounder/src/main/resources/OSGI-INF/blueprint/blueprint-alarm-northbounder.xml
features/amqp/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
features/amqp/event-receiver/src/main/resources/OSGI-INF/blueprint/blueprint-event-receiver.xml

Upgrading Camel to 2.16 broke the AMQP integration because the connection factory that we are using is no longer installed by the ```camel-amqp``` feature. This PR adds the Qpid bundle back to our features so that the connection factory is available for our blueprint to use.
I spot-checked this fix against RabbitMQ and it seems to be forwarding messages.
* JIRA: http://issues.opennms.org/browse/NMS-9472

NMS-9472: Fix connection factory in AMQP features

---

features/minion/core/shell/src/main/java/org/opennms/minion/core/shell/MinionPingCommand.java

JIRA: https://issues.opennms.org/browse/NMS-9445
Here we improve the JMS broker test by trying to create a session over the connection we've acquired.
We also add a time limit, since certain connection pools may block forever until a session is actually acquired.

NMS-9445: minion:ping does not properly validate JMS broker connectivity

---

opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/DefaultCollectionAgent.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/DefaultCollectionAgentService.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdEventHandlingTest.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/DefaultCollectionAgentTest.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpAttributeTest.java

JIRA: https://issues.opennms.org/browse/NMS-5105
This fixes a long standing bug where node, interface and service deleted events weren't being handled properly by collectd, leaving the services scheduled after deletion.

NMS-5105: Fix handling of delete related events in collectd

---

opennms-dao/src/test/java/org/opennms/netmgt/dao/MonitoredServiceDaoIT.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/NodeDaoIT.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/UpsertIT.java

This adds a couple of tests that fail with our current version of Hibernate. We should reenable them after we upgrade Hibernate to see if the behavior has been fixed.
* JIRA: http://issues.opennms.org/browse/NMS-9470

NMS-9470: Added tests for Hibernate join condition bug

---

opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/controllers/Requisitions.js

Clone foreign source requisition overwrites config of other requisition without any hint or warning.
* JIRA: http://issues.opennms.org/browse/NMS-9481
Because a customer opened a support ticket about this for Meridian, I'm applying the solution for `foundation-2016`.
The JavaScript files have been moved as part of the WebUI rework for H19, the solution has to be manually ported to `foundation-2017`. I can do that without issues as soon as this PR is merged.

NMS-9481: Clone foreign source requisition overwrites config of other requisition without any hint or warning

---

opennms-model/src/main/java/org/opennms/netmgt/model/topology/BroadcastDomain.java

Thanks for taking time to contribute!
Please read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md) and format the title of the pull request in the format of:
NMS-9464: enlinkd thread throws StackOverflowError
* JIRA: http://issues.opennms.org/browse/NMS-9464
Fixed to go down for 30 level
then return
Need to add more test and check for loops in topology to avoid this

NMS-9464: enlinkd thread throws StackOverflowError

---

container/pom.xml
core/test-api/karaf/pom.xml
dependencies/newts/pom.xml
dependencies/owasp-encoder/pom.xml
dependencies/rancid/pom.xml
dependencies/spring-security/pom.xml
features/alarm-change-notifier/pom.xml
features/minion/core/repository/pom.xml
features/minion/repository/pom.xml
features/newts/pom.xml
features/opennms-es-rest/pom.xml
features/remote-poller/pom.xml
features/topology-map/poms/pom.xml
features/vaadin-opennms-pluginmanager/pom.xml
opennms-full-assembly/pom.xml
pom.xml

This should speed up builds and make them more reliable since fewer repos will be hit when trying to look up Maven artifacts.
Most of these repos are completely unused (JBoss, Spring.io, Servicemix, Codehaus, Apache snapshots, Eclipse). We do use the Sonatype repo to fetch ```dnsjava``` but this PR removes extra references to that repo.

Removed a bunch of unnecessary Maven repositories from POMs

---

opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LockUnavailable.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableElement.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableNetwork.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableNode.java
opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/PollablesIT.java

Changed ```LockUnavailable``` to a checked exception and fixed methods that were trying to unlock a lock that they do not hold (which caused uncaught RuntimeExceptions).
* JIRA: http://issues.opennms.org/browse/NMS-9466

NMS-9466: Added tests for ReentrantLock timeouts, fixed issues

---

features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/events/EventForm.java
features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/events/EventPanel.java
features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/events/EventFormTest.java

* JIRA: http://issues.opennms.org/browse/NMS-9422
The solution has been manually verified on my test environment.
The solution will require manual merge to foundation-2017, as the Vaadin API is slightly different.
In case this is needed in foundation for Meridian 2015, the solution has to be reworked as well (same thing, because of the Vaadin API).

NMS-9422: Event Configuration Screen Requires Alarm Type

---

opennms-doc/guide-admin/src/asciidoc/text/poller/monitors/SnmpMonitor.adoc

Document the logic behind the response time value reported by the SnmpMonitor.
* JIRA: http://issues.opennms.org/browse/NMS-9475
There are several ways to improve the implementation of the `SnmpMonitor` as mentioned on Jira, but the customer who is responsible for requesting this change agreed to just include a note on the documentation about how the response time is calculated.
As a side note, this should be audited across all the monitors, as this behavior might be the case of others.

NMS-9475: Document the logic behind the response time value reported by the SnmpMonitor

---

container/features/src/main/resources/features-minion.xml
container/features/src/main/resources/features.xml
core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
features/minion/core/repository/pom.xml
features/minion/repository/pom.xml
opennms-full-assembly/pom.xml
opennms-full-assembly/src/assembly/components/osgi.xml
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/FeatureInstallKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/MinionFeatureKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
pom.xml

Now that we've upgraded to Karaf 4.0.8, reenable the Karaf feature integration tests since they seem to be stable after the many bugfixes in Karaf 4. 
* JIRA: http://issues.opennms.org/browse/NMS-8305

NMS-8305: Reenable Karaf integration tests

---

opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
opennms-config/src/test/java/org/opennms/netmgt/config/EventConfMatcherTest.java
opennms-config/src/test/resources/NMS-9496.events.xml

JIRA: https://issues.opennms.org/browse/NMS-9496
Remove event definitions from the index if any mask elements from any other event definitions match the UEI.
 This allows mask elements to be used against incoming event instances that already have a UEI set, provided that they include a UEI match. In this case the associated event definition will no longer be found in the UEI to Event definition index.

NMS-9496: Don't index events if the UEI is matched by a mask element.

---

features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapSinkModule.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapUtils.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapdConfigBean.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/trapd/TrapdConfiguration.java
opennms-config-jaxb/src/main/resources/xsds/trapd-configuration.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/TrapdConfig.java
opennms-config/src/main/java/org/opennms/netmgt/config/TrapdConfigFactory.java

JIRA: https://issues.opennms.org/browse/NMS-9449
* Pull the agent address from the snmpTrapAddress (1.3.6.1.6.3.18.1.3.0) varbind when available.
* Add a flag to trapd-configuration.xml that can be used to enable the feature.

NMS-9449: Add support for retrieving the SNMPv2 agent address from a specific varbind.

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpTableResult.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/PhysInterfaceTableTracker.java

This PR does 2 things:
1. make sure the physical interface tracker continues even if it encounters an error, rather than stopping scanning the table
2. traps errors in marking a row completed in `SnmpTableResult` so that it will continue rather than failing if an unexpected value is encountered
* JIRA: http://issues.opennms.org/browse/NMS-8046

NMS-8046: handle NoSuchInstance properly

---

opennms-webapp/src/main/webapp/admin/notification/pathOutline.jsp

initial-delay="null" when adding a new destination path.
The default should be "0s" like in older versions of OpenNMS (including Meridian 2016).
* JIRA: http://issues.opennms.org/browse/NMS-9548

NMS-9548: initial-delay="null" when adding a new destination path.

---

opennms-webapp/karma.conf.js
opennms-webapp/src/main/webapp/js/onms-interfaces/app.js
opennms-webapp/src/main/webapp/js/onms-ksc/wizard.js
opennms-webapp/src/main/webapp/js/onms-requisitions/app-requisitions.js
opennms-webapp/src/main/webapp/js/onms-requisitions/scripts/controllers/QuickAddNode.js
opennms-webapp/src/main/webapp/js/onms-resources/app.js
opennms-webapp/src/main/webapp/js/onms-search/app.js
opennms-webapp/src/test/javascript/global.js

Microsoft IE and Edge doesn't like relative path on Angular apps.
The solution is always use full URLs, which works on any browser (including IE and Edge). Tested against H20.
* JIRA: http://issues.opennms.org/browse/NMS-9542

NMS-9542: Microsoft IE and Edge doesn't like relative path on Angular apps

---

opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
opennms-config/src/test/java/org/opennms/netmgt/config/EventConfDaoReloadTest.java
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/order/1.events.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/order/2.events.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/order/eventconf.1.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/order/eventconf.21.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/order/eventconf.empty.xml

JIRA: https://issues.opennms.org/browse/NMS-9551
This fixes a bug where the order of event definitions is not respected after reloading the event configuration without restarting.

NMS-9551: Respect the order of the event file definitions when reloading

---

tools/packages/opennms/opennms.spec

In the process of fixing NMS-9493, I accidentally made it so `users.xml` is not marked as a `%config` file.  This patch fixes that, and also makes sure permissions match during `%pre` install so that an upgrade won't cause .rpmnew or .rpmsave files to be created in most cases.
* JIRA: http://issues.opennms.org/browse/NMS-9573

NMS-9573: fix RPM replacement of users.xml

---

pom.xml

This PR bumps mina to 2.0.16 to (attempt to) resolve a resource leak reported in NMS-9545.  The user has reported upgrading mina to the latest version fixed their issue.
* JIRA: http://issues.opennms.org/browse/NMS-9545

NMS-9545: bump mina version to 2.0.16

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/DefaultEventHandlerImpl.java
features/events/daemon/src/main/resources/META-INF/opennms/applicationContext-eventDaemon.xml
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventdIT.java
opennms-doc/guide-admin/src/asciidoc/text/events/events.adoc

Add foreignSource and foreignId parameters when sending events as an alternative to nodeId
Please use the [JIRA](https://issues.opennms.org) issue number and create a link in the JIRA issue back to this pull request so we have a quick reference from the issue to the pull request.
* JIRA: http://issues.opennms.org/browse/NMS-8919

NMS-8919: Add foreignSource and foreignId parameters when sending events as an alternative to nodeId

---

core/schema/src/main/liquibase/20.0.2/changelog.xml
core/schema/src/main/liquibase/changelog.xml
core/schema/src/main/liquibase/foundation-2015/changelog.xml
features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
opennms-base-assembly/src/main/filtered/etc/create.sql

The reason parameter for a nodeLostService event is limited to 255 characters.
* JIRA: http://issues.opennms.org/browse/NMS-9550

NMS-9550: The reason parameter for a nodeLostService event is limited to 255 characters

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehaviors.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java

Used ThreadLocal to fix non-threadsafe DateFormat. Added concurrency test to AlarmRestServiceIT.
* JIRA: http://issues.opennms.org/browse/NMS-9590

NMS-9590: Fixed non-threadsafe DateFormat

---

opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/IcmpDetectorIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/PollableServiceConfigIT.java

Address some build errors with unit tests enabled where JNI/JNA (particularly with root access) was needed for some unit tests. Renamed these to be integration tests.
* JIRA: http://issues.opennms.org/browse/NMS-9591

NMS-9591: Rename tests that require JNI/JNA to integration tests

---

core/criteria/src/main/java/org/opennms/core/criteria/AliasBuilder.java
core/criteria/src/main/java/org/opennms/core/criteria/CriteriaBuilder.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehavior.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehaviors.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBuilderSearchVisitor.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaValueConverters.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperty.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/README.adoc
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/SearchPropertiesIT.java

This PR fixes the aliases on the `/api/v2/nodes` endpoint and adds metadata support to it so that it has basically the same level of function that the other RESTv2 endpoints do.
* JIRA: http://issues.opennms.org/browse/NMS-9278

NMS-9278: Fix RESTv2 node service

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestServiceWithDTO.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java

This is the last feature for the RESTv2 metadata: handling a `limit` parameter for the property value endpoints so that we can limit the results when performing autocomplete queries (since many values will have hundreds or thousands of results).
* JIRA: http://issues.opennms.org/browse/HZN-1098

HZN-1098: Add limit param to the search property value endpoint

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/README.adoc
opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/SearchPropertiesToAsciidocTest.java

Added a method override that I missed in NodeRestService. This will actually expose the metadata for the node endpoint.
* JIRA: http://issues.opennms.org/browse/NMS-9278

NMS-9278: RESTv2 metadata tweaks

---

core/api/src/main/java/org/opennms/core/config/api/JaxbListWrapper.java

The `offset` property was added to the `JaxbListWrapper` at a later date.  It does the right thing in XML (which just skips the attribute), but in JSON it returns `null` rather than 0 or emitting the value.
* JIRA: http://issues.opennms.org/browse/NMS-9599

NMS-9599: make sure JaxbListWrapper always returns an offset

---

opennms-doc/guide-admin/src/asciidoc/text/user-management/security-roles.adoc
opennms-web-api/src/main/java/org/opennms/web/api/Authentication.java
opennms-webapp-rest/pom.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SecurityHelper.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/SecurityHelperTest.java

JIRA: https://issues.opennms.org/browse/HZN-1150
Here we add a new role, ROLE_DELEGATE, that allows alarms to be acknowledged on behalf of other users, without required ROLE_ADMIN.

HZN-1150: Allow users with ROLE_DELEGATE to acknowledge alarms on behalf of other users

---

core/schema/src/main/liquibase/changelog.xml
core/schema/src/main/liquibase/foundation-2017/changelog.xml
opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml

This PR sets the alarm-type on the BSM events to `3` (no possible resolution) rather than `1` (has a possible resolution) and introduces liquibase code to update existing BSM alarms to have the right type in the database.
* JIRA: http://issues.opennms.org/browse/NMS-9497

NMS-9497: fix alarm-type on BSM events to be 3 rather than 1

---

core/criteria/src/main/java/org/opennms/core/criteria/Alias.java
core/criteria/src/main/java/org/opennms/core/criteria/AliasBuilder.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/Aliases.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehavior.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehaviors.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBuilderSearchVisitor.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/IpLikeCriteriaBehavior.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NotificationRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/README.adoc
opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/SearchPropertiesToAsciidocTest.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java

Now that the event parameters are in a separate database table, we can filter based on parameters in our Criteria API and, subsequently, in the RESTv2 services.
This PR adds eventparm filtering support to the alarm, event, and notification endpoints.
* JIRA: http://issues.opennms.org/browse/HZN-1146

HZN-1146: Added eventparm search to RESTv2 endpoints

---

protocols/dhcp/pom.xml
protocols/dhcp/src/assembly/lib.xml
protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Client.java
protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Message.java
protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Poller.java
protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Receiver.java
protocols/dhcp/src/main/java/org/opennms/netmgt/dhcpd/Receiver2.java
protocols/dhcp/src/test/java/org/opennms/netmgt/config/dhcpd/DhcpdConfigFactoryTest.java
protocols/dhcp/src/test/java/org/opennms/protocols/dhcp/detector/DhcpDetectorTest.java

This PR updates the `protocols/dhcp/` DHCP implementation to use [JDHCP 1.2.0](https://github.com/OpenNMS/jdhcp), a fork of the original dhcp.org java DHCP implementation which has been updated to throw more meaningful errors when malformed packets are encountered.
* JIRA: http://issues.opennms.org/browse/NMS-9420

NMS-9420: update JDHCP to give a better error from malformed packets

---

opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-speedtest/events/Syslogd.events.xml
opennms-services/src/main/java/org/opennms/netmgt/syslogd/SyslogSeverity.java
opennms-services/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Because of some cross-commits for these two issues, `foundation-2016` and higher are not processing `INFORMATIONAL` syslog messages correctly. To avoid impacting config files, this PR reverts the NMS-7934 changes. 
Note that this should be merged through to `develop` even though it's a revert.
JIRA:
* http://issues.opennms.org/browse/NMS-7934
* http://issues.opennms.org/browse/NMS-8106

Revert changes for NMS-7934 in favor of NMS-8106

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestServiceWithDTO.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/IfServiceRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MinionRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MonitoringLocationRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeCategoriesRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeSnmpInterfacesRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ScanReportRestService.java

The `update()` function was mistakenly erased from `AbstractDaoRestServiceWithDTO` (previously known as `AbstractDaoRestService`) during the refactoring of the RESTv2 code that took place in preparation for the Helm enhancements. This was causing edits to the Minions, monitoring locations, and scan reports to fail via REST.
* JIRA: http://issues.opennms.org/browse/NMS-9608

NMS-9608: Restored update() function in AbstractDaoRestServiceWithDTO

---

features/remote-poller/src/main/resources/log4j2.xml
opennms-assemblies/remote-poller-standalone/src/main/filtered/remote-poller.init

This PR fixes the logging in the remote poller package to work no matter how it is started (it relies on a system property that wasn't set in all code paths).
Also while testing this, I found a property-replacement bug in the init script that is fixed as well.
* JIRA: http://issues.opennms.org/browse/NMS-9621

NMS-9621: fix logging in the remote poller

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultHostnameResolver.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/SaveOrUpdateOperation.java

JIRA: https://issues.opennms.org/browse/NMS-9406
This is a backport of [NMS-9356](https://issues.opennms.org/browse/NMS-9356) to foundation-2016.

NMS-9406: Allow provisiond to perform reverse lookups without requiring an A record

---

opennms-webapp/src/main/webapp/admin/ng-requisitions/app/scripts/app.js

JIRA: https://issues.opennms.org/browse/NMS-9618
Adds a missing dependency. Fixes a regression from NMS-9353.

NMS-9618: Fix the 'Quick Add Node' modal in the provisioning UI

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/processor/expandable/EventTemplate.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilHibernateIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/BroadcastEventProcessorIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotifdIT.java

Our eventconf files (and other files that use parm expansion, like the notification messages) assume that you can use '%%' as an escaped percent sign. However, this isn't supported but it was easy to add support for this that doesn't break any other parm expansion.
This probably wasn't noticed before because '%%' was evaluated as an invalid parm expansion and was simply erased in the output.
* JIRA: http://issues.opennms.org/browse/NMS-9607

NMS-9607: Allow use of %% as an escaped percent sign in eventconf

---

core/test-api/services/pom.xml
features/notifications/api/pom.xml
features/notifications/api/src/main/java/org/opennms/netmgt/model/notifd/Argument.java
features/notifications/api/src/main/java/org/opennms/netmgt/model/notifd/NotificationStrategy.java
features/notifications/pom.xml
opennms-config-model/src/main/java/org/opennms/netmgt/config/notificationCommands/Command.java
opennms-config-model/src/main/resources/xsds/notificationCommands.xsd
opennms-services/pom.xml
opennms-services/src/main/java/org/opennms/netmgt/notifd/NotificationTask.java
opennms-services/src/main/java/org/opennms/netmgt/notifd/ServiceRegistryExecutor.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/ServiceRegistryExecutorTest.java
pom.xml

JIRA: https://issues.opennms.org/browse/HZN-1155
Here create the `org.opennms.features.notifications/org.opennms.features.notifications.api` bundle with the minimal dependencies required for the `NotificationStrategy` interface and extend Notifd to support invoking implements via the service registry using commands of this form:
```
<command service-registry="true">
<execute>(type=org.opennms.netmgt.notifd.me.MyNotificationStrategy)</execute>
...
</command>
```

HZN-1155: Add support for invoking notification strategies exposed via the service registry.

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java

JIRA: https://issues.opennms.org/browse/NMS-9108
The logic for determining the effective location when handling `newSuspect` events is now:
* Use the value of the location parameter if set
* Otherwise, use the source location of the event, if it is associated
with a particular system
* Fallback to the using the default location

NMS-9108: Fix effective location when handling newSuspect events

---

opennms-assemblies/remote-poller-nsis/remote-poller.nsi

Removed extra `\` chars in log path so that escaping is correct.
* JIRA: http://issues.opennms.org/browse/NMS-9631

NMS-9631: Fixed $ escaping in appender log path

---

features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceMainLayout.java

This PR adds a visual indication (notification popup) when the reload daemon has been sent in the BSM admin UI.
* JIRA: http://issues.opennms.org/browse/NMS-9624

NMS-9624: BSM daemon reload indicator

---

tools/packages/opennms/opennms.spec

This PR fixes the RPMs to not create the drools ncs directory in the main (core) RPM, but to leave it to the NCS package.
* JIRA: http://issues.opennms.org/browse/LTS-215

LTS-215: make sure an empty ncs directory is not created in core

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp

The button to add a graph to a KSC report doesn't work.
* JIRA: http://issues.opennms.org/browse/NMS-9498
Fortunately, an easy fix. I tested the solution on my lab.

NMS-9498: The button to add a graph to a KSC report doesn't work

---

core/schema/src/main/liquibase/foundation-2017/changelog.xml
opennms-base-assembly/src/main/filtered/etc/events/opennms.events.xml

After further discussion, it was decided to set alarm-type on `uei.opennms.org/bsm/serviceProblem` and `uei.opennms.org/bsm/serviceProblemResolved` to 1 and 2, respectively.
* JIRA: http://issues.opennms.org/browse/NMS-9653

NMS-9653: undo NMS-9497 and set to 1+2 respectively

---

features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/Log4j2StringAppender.java
features/poller/remote/src/test/java/org/opennms/netmgt/poller/remote/support/Log4j2StringAppenderTest.java

This PR makes the log format for Scan Reports the same as all of the normal logging so that timestamps and logger names are included.
* JIRA: http://issues.opennms.org/browse/NMS-9604

NMS-9604: Fix Scan Report log formatting

---

opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmFilterController.java
opennms-webapp/src/main/java/org/opennms/web/controller/statisticsReports/ReportController.java
opennms-webapp/src/main/java/org/opennms/web/tags/filters/AbstractFilterCallback.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
opennms-webapp/src/main/webapp/errors/statisticsreportidnotfound.jsp

This fixes some parameter escaping on the alarm list and the statistics report list.
* JIRA: http://issues.opennms.org/browse/NMS-9457

NMS-9457: Escape some HTTP params

---

features/minion/container/extender/pom.xml
features/minion/container/karaf/pom.xml
features/minion/container/karaf/src/main/filtered-resources/etc/branding-ssh.properties
features/minion/container/karaf/src/main/filtered-resources/etc/branding.properties
features/minion/core/repository/pom.xml
features/minion/core/shell/pom.xml
features/minion/pom.xml
features/minion/repository/pom.xml
features/minion/shell/collection/pom.xml
features/minion/shell/poller/pom.xml
features/minion/shell/provision/pom.xml
features/scv/shell/pom.xml
pom.xml

This was a minor commit as part of my Karaf 4.1 upgrade branch but I think it should be merged separately since it reduces the number of files touched in the Karaf 4.1 upgrade branch.
* JIRA: http://issues.opennms.org/browse/HZN-1092

Get rid of separate minionKarafVersion in favor of karafVersion

---

features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/jmx/TrapdInstrumentation.java

JIRA: https://issues.opennms.org/browse/NMS-9660
Log any errors that occur from asynchronously sending the traps via the Sink dispatcher and update the error counters accordingly.
Also, refactored the counters to use atomics to avoid unnecessary locks.

NMS-9660: trapd may silently discard invalid traps

---

core/lib/src/main/java/org/opennms/core/time/ZonedDateTimeBuilder.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ParserStageSequenceBuilder.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/BufferParserTest.java

If two parser stages had the same pattern type but different semantic types (and therefore different handlers), the parser generator wasn't taking the different handlers into account when generating the parser tree. This has been fixed by updating the equals() method on the stages. Exceptions thrown in the handlers also cause a parse failure now.
* JIRA: http://issues.opennms.org/browse/NMS-9522

NMS-9522: Fix radix tree confusion between 2 stages of the same pattern

---

container/features/src/main/resources/features.xml
features/reporting/availability/pom.xml
opennms-base-assembly/pom.xml
opennms-config-model/pom.xml
opennms-tools/csv-address/pom.xml
opennms-tools/csv-address/src/main/java/org/opennms/model/utils/AssetsUpdater.java
opennms-webapp/pom.xml
opennms-webapp/src/main/java/org/opennms/web/asset/ExportAssetsServlet.java
opennms-webapp/src/main/java/org/opennms/web/asset/ImportAssetsServlet.java
opennms-webapp/src/main/java/org/opennms/web/rss/AbstractFeed.java
opennms-webapp/src/main/java/org/opennms/web/rss/AlarmFeed.java
opennms-webapp/src/main/java/org/opennms/web/rss/EventFeed.java
opennms-webapp/src/main/java/org/opennms/web/rss/NotificationFeed.java
opennms-webapp/src/main/java/org/opennms/web/rss/OutageFeed.java
pom.xml

This PR has some version cleanup and upgrades the version and artifactId of the following dependencies (since these deps have changed artifactId since we started using them):
- OGNL: 2.6.9 → 2.6.11
- opencsv: 2.3 → 3.9
- Rome: 1.0 → 1.7.2
Please don't mark NMS-9330 fixed after this is merged, I have more changes to commit.
* JIRA: http://issues.opennms.org/browse/NMS-9330

NMS-9330 (Part 1): Minor dependency upgrades

---

opennms-services/src/main/java/org/opennms/netmgt/notifd/MattermostNotificationStrategy.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/MattermostNotificationStrategyIT.java

This is a version of https://github.com/OpenNMS/opennms/pull/1645 cherry-picked to be against develop.

NMS-9597: Making the Mattermost plugin display the same format as slack (rebase)

---

features/collection/api/pom.xml
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/JexlIndexStorageStrategy.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/ObjectNameStorageStrategy.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/ObjectNameStorageStrategyTest.java
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/configuration.adoc

NMS-9080: Add a ObjectNameStorageStrategy that uses a JEXL template to format the resource's index.
* JIRA: http://issues.opennms.org/browse/NMS-9080

NMS-9080: Add an ObjectNameStorageStrategy with JEXL for formatting the resources index

---

container/features/src/main/resources/features.xml
core/lib/pom.xml
core/lib/src/main/java/org/opennms/core/utils/WebSecurityUtils.java
core/lib/src/test/java/org/opennms/core/utils/WebSecurityUtilsTest.java
dependencies/owasp/pom.xml
dependencies/pom.xml
opennms-base-assembly/pom.xml
opennms-full-assembly/pom.xml
pom.xml

JIRA: https://issues.opennms.org/browse/NMS-9668
JIRA: https://issues.opennms.org/browse/NMS-9669
Here we update WebSecurityUtils to use the OWASP HTML Sanitizer for safely rendering strings that we allow to contain HTML.
Our current protection is quite limited since we only filter out a few known patterns.

NMS-9668: Use OWASP HTML sanitizer

---

opennms-full-assembly/src/main/filtered-resources/etc/org.apache.karaf.command.acl.bundle.cfg

This disables the bundle ACLs in OpenNMS's Karaf container.
* JIRA: http://issues.opennms.org/browse/HZN-1175

HZN-1175: Disable bundle ACLs in Karaf

---

opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/Northbounder.java
opennms-alarms/bsf-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/bsf/BSFNorthbounderManager.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
opennms-alarms/drools-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/drools/DroolsNorthbounderManager.java
opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounderManager.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounderManager.java
opennms-alarms/snmptrap-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/snmptrap/SnmpTrapNorthbounderManager.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderManager.java

Northbounders implementation are not sending feedback events for reloadDaemonConfig.
* JIRA: http://issues.opennms.org/browse/NMS-9524
I've created the PR against `foundation-2017` due to the Drools NBI and BSF NBI. For `foundation-2016` I can cherry-pick the solution and manually remove the changes on the NBIs that don't exist there, which is easier than creating 2 separate PRs, one for each foundation branch.

NMS-9524: Northbounders implementation are not sending feedback events for reloadDaemonConfig.

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java

JIRA: https://issues.opennms.org/browse/NMS-9620
This fixes a snmp4j session leak caused by an exception thrown during the call to send().

NMS-9620: Ensure that the snmp4j session is closed

---

features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/SurveillanceViewConfigurationCategoryWindow.java
features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/SurveillanceViewConfigurationWindow.java

Since the newer JAXB code cleans out empty strings properly, the editor was NPE'ing trying to call `.trim()` on it.  This PR fixes it.
* JIRA: http://issues.opennms.org/browse/NMS-9722

NMS-9722: fix NPE in string handling

---

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/AbstractForeignSourceRepository.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/Requisition.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionAsset.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionCategory.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionInterface.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionMonitoredService.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNode.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/RequisitionRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/RequisitionRestServiceIT.java
opennms-webapp/src/test/resources/tec_dump.xml

This PR adds validation for sub-objects of the requisition, and normalizes the way validation is performed in the ReST interface.
* JIRA: http://issues.opennms.org/browse/NMS-9725

NMS-9725: improve validation of requisitions

---

container/features/src/main/resources/features.xml
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AggregateTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/CollectionTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ResponseProcessor.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SingleInstanceTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpAgentConfig.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpException.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpInstId.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpWalker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TableTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapInformation.java
core/snmp/api/src/test/java/org/opennms/netmgt/snmp/SnmpAgentConfigTest.java
core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpWalker.java
core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/V2TrapInformation.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategy.java
core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpWalker.java
core/snmp/impl-snmp4j/pom.xml
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JTrapNotifier.java
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JUtils.java
core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JWalker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/InstanceTrackerTest.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/SnmpTrackerIT.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapInformationWrapper.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/SnmpMonitorStrategy.java
opennms-base-assembly/src/main/filtered/etc/log4j2.xml

As part of the work done on diagnosing NMS-9620, I changed a number of places where a`RuntimeException` (usually `IOException`) was implicitly passed up the call chain and changed them to a new encapsulating exception `SnmpException`.
This PR also adds a session tracker that keeps track of open SNMP sessions and posts a report to an SNMP debug log with statistics on long-running threads.
The session tracker can be enabled by setting `-Dorg.opennms.core.snmp.trackSessions=true`. By default it will print a summary of the top 10 oldest threads every 60 seconds to the SNMP debug log.
The number of threads and the amount of time between summaries (in seconds) can be changed by setting `-Dorg.opennms.core.snmp.trackSummaryLimit=n` and `-Dorg.opennms.core.snmp.trackSummaryDelay=n` respectively. …

NMS-9620 update SNMP exception handling + track sessions

---

features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java

* JIRA: https://issues.opennms.org/browse/NMS-9699
@gallenc, @jeffgdotorg, @agalue this PR enables preemptive authentication when username and password is provided. Please give it a try and let me know if it works as expected.

NMS-9699: Enable preemptive auth for first host

---

features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java

JIRA: https://issues.opennms.org/browse/HZN-1190
Update the default connection limits and allow them to be configured.

HZN-1190: Allow the Jest connection pool size to be configured

---

opennms-config-model/src/main/java/org/opennms/netmgt/config/provisiond/RequisitionDef.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/CoreImportActivities.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java

Pass rescanExisting attribute of requisition-def tags in provisiond.xml to CoreImportActivities - i.e. support DNS import with rescanExisting=false
Thanks for taking time to contribute!
Please read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md) and format the title of the pull request in the format of:
${JIRA-ISSUE-NUMBER}: a-short-subject-title
Please use the [JIRA](https://issues.opennms.org) issue number and create a link in the JIRA issue back to this pull request so we have a quick reference from the issue to the pull request.
* JIRA: http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

NMS-9492: Bugfix in DNS Provisioning

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5-adapter.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5-interface.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5-troubleshooting.adoc

Describe how to install NetFlow v5 feature using Karaf Console and how to configure the Listener. Explain what configuration is required to persist date with the NetFlow v5 adapter to ElasticSearch. Add some troubleshooting hints for operation.
* JIRA: http://issues.opennms.org/browse/HZN-1178

HZN-1178: Describe installation of NetFlow v5 protocol

---

features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/Netflow5Adapter.java
opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-netflow-graph.properties
opennms-webapp-rest/pom.xml
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/RequisitionRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/JmxDataCollectionConfigResourceIT.java

JIRA: https://issues.opennms.org/browse/HZN-1193
Here we improve the performance of the Netflow adapter by working on logs instead of individual packets and expose additional metrics via JMX.
The JMX metrics are collected via the opennms-jvm collection and include associated graphs.

HZN-1193: Improve Netflow performance and metrics

---

core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategyIT.java
core/test-api/lib/src/main/java/org/opennms/core/test/LoggingEvent.java
core/test-api/lib/src/main/java/org/opennms/core/test/MockLogAppender.java
core/test-api/lib/src/main/java/org/opennms/core/test/MockLogger.java
core/test-api/lib/src/main/java/org/opennms/core/test/MockLoggerFactory.java
core/test-api/lib/src/test/java/org/opennms/core/test/MockLogAppenderTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdIT.java
integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/measurement/AbstractMeasurementQueryExecutorTest.java
integrations/opennms-snmp-asset-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/SnmpAssetProvisioningAdapterFullIT.java
integrations/opennms-snmp-asset-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/SnmpAssetProvisioningAdapterIT.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/PropertiesGraphDaoITCase.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PathOutageManagerDaoIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerQueryManagerDaoIT.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
pom.xml

This PR changes MockLoggerFactory so that it doesn't cache MockLogger instances. This means that MockLoggers will use the log level that is specified by calling static methods on MockLogAppender (as it was intended to work).
This reduces the log output of the build on Bamboo from about 3.2 million log messages down to about 1.8 million since DEBUG messages are no longer leaking into the output (from tests where DEBUG logging is not enabled).
There's also thread safety/API cleanup here for MockLogAppender. 
* JIRA: http://issues.opennms.org/browse/NMS-8905

NMS-8905: Create fresh MockLogger instances in MockLoggerFactory

---

core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/ShowConfigCommand.java

* JIRA: http://issues.opennms.org/browse/NMS-9745

NMS-9745: Karaf snmp:show-config command lists value of timeout for retries

---

pom.xml

HEAD requests to our UI are failing for static resources (preventing the Remote Poller EXE installer link and offline docs links from appearing). This Jetty micro upgrade fixes the problem.
* JIRA: http://issues.opennms.org/browse/NMS-9689

NMS-9689: Upgrade Jetty to version 9.4.2.v20170220

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/RequestHeaderPreAuthenticationProcessingFilter.java
opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/user-management/pre-authentication.adoc
opennms-doc/guide-admin/src/asciidoc/text/user-management/security-roles.adoc
opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/attribute-preauth.xml
opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/header-preauth.xml
opennms-webapp/src/test/java/org/opennms/web/report/database/SpringWebflowContextIT.java

This commit creates a new pre-authentication filter for servlets
(RequestHeaderPreAuthenticationProcessingFilter) and configures it
in applicationContext-spring-security.xml.
It also refactors the existing servlet attribute filter
(RequestAttributePreAuthenticationProcessingFilter) to look more
like the new header-based filter.
Both now require a property "enabled" to be set to "true" or else
they will silently pass control to the next filter in the chain
without authenticating.  This allows us to leave them always
configured in the spring security .xml without having to make
large/unusual config changes besides enabling the filter.
* JIRA: http://issues.opennms.org/browse/NMS-9739
Our [continuous integration system](http://bamboo.internal.opennms.com:8085) will test and verify your …

NMS-9739: allow pre-authentication through HTTP headers

---

opennms-assemblies/remote-poller-windows/src/main/filtered/install.bat
opennms-base-assembly/src/main/filtered/bin/opennms
opennms-webapp/runInPlace.sh

This PR gets rid of deprecated pre-Java5 debug flags and uses `agentlib:jdwp` instead.

Updated JVM debug flags to use agentlib:jdwp

---

checkstyle/pom.xml
features/measurements/api/pom.xml

I've been getting annoying Eclipse errors wrt source levels; this PR fixes the problems and continues to ensure that our Jasper plugin is JDK7 compatible.

Fix Eclipse compiler version errors

---

opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
smoke-test/src/test/java/org/opennms/smoketest/RestSessionIT.java

JIRA: https://issues.opennms.org/browse/NMS-8093
Here we back-port the fix for NMS-8093 to foundation-2017.
Requests made to the REST API will no longer create sessions.

NMS-8093: Backport REST API session handling fix to Foundation 2017

---

opennms-doc/guide-admin/src/asciidoc/text/provisioning/scalability.adoc

Fix typo in automatic rescan interval.
* JIRA: http://issues.opennms.org/browse/NMS-9803

NMS-9803: Fix wrong syntax for automatic rescanning

---

opennms-doc/guide-admin/src/asciidoc/text/events/events.adoc

The Alarm workflow was started to be documented in [NMS-8032](https://github.com/OpenNMS/opennms/blob/NMS-8032/opennms-doc/guide-user/src/asciidoc/text/alarms/introduction.adoc) but was never merged and is unfinished. Removed dead link.
* JIRA: http://issues.opennms.org/browse/NMS-9802

NMS-9802: There is no section which explain the Alarm life cycle

---

features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Oops, my smart year parsing inside Syslogd was too smart for one of the unit tests which still assumed that a `March` timestamp must be `March, ${currentYear}`.

Fix SyslogMessageTest after year wrap

---

opennms-config-model/src/main/java/org/opennms/netmgt/config/utils/ConfigUtils.java
opennms-config-model/src/test/java/org/opennms/netmgt/config/groups/GroupTest.java
opennms-config-model/src/test/java/org/opennms/netmgt/config/utils/ConfigUtilsTest.java

* assertNotEmpty was incorrectly checking the passed value, rather than the normalized one
* normalizeAndTrimString was not null-checking before attempting to trim (normalizeAndInternString was actually correct, though, for some reason...)
Also, added a unit test for the specific bug hit in the issue, and test coverage of all of the ConfigUtils static methods.
* JIRA: http://issues.opennms.org/browse/NMS-9785

NMS-9785: fix assertNotEmpty and normalizeAndTrimString

---

opennms-config-model/src/main/java/org/opennms/netmgt/config/notifd/NotifdConfiguration.java
opennms-config-model/src/main/resources/xsds/notifd-configuration.xsd
opennms-services/pom.xml
opennms-services/src/main/java/org/opennms/netmgt/notifd/BroadcastEventProcessor.java
opennms-services/src/main/java/org/opennms/netmgt/notifd/NotificationTask.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotificationThreadsIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/ThreadLockingNotificationStrategy.java
opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/PollableServiceConfigTest.java
opennms-services/src/test/resources/org/opennms/netmgt/notifd/destination-paths.xml
opennms-services/src/test/resources/org/opennms/netmgt/notifd/groups.xml
opennms-services/src/test/resources/org/opennms/netmgt/notifd/notification-commands.xml
opennms-services/src/test/resources/org/opennms/netmgt/notifd/notifications.xml
pom.xml

JIRA: https://issues.opennms.org/browse/NMS-9766
Here we introduce a thread pool in notifd that is used to invoke the notification tasks, and use this pool to limit the number of threads that are active at any given time. Additional notifications tasks that a waiting for threads will be kept in an unbounded queue.
By default we limit the number of threads to 100, and allow it to be configured via the notifid-configuration.xml.

NMS-9766: Limit the number of threads that can be used to send notifications

---

opennms-doc/asciidoctor-default.css
pom.xml

Update AsciiDoctor dependencies to latest stable versions from 1.5.3 -> 1.5.6 and the AsciiDoctorJ PDF plugin to latest version from 1.5.0-alpha.11 -> 1.5.0-alpha.16. Updated the AsciiDoctor default  CSS theme to the latest version.
* JIRA: http://issues.opennms.org/browse/NMS-9808

NMS-9808: Bump AsciiDoctor dependencies and update theme

---

opennms-base-assembly/src/main/filtered/etc/datacollection/netsnmp.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/netsnmp-graph.properties

Enable disk IO metrics for read/writes in bytes and operations in default system definition to get collected by default. Added metrics for disk load in percent for 1, 5 and 15-minute averages and created RRD graph definitions for each value as percentage graph and an aggregated graph with all three values similar to a load average graph.
Added 64-bit counters for reading and write bytes and if they are supported, suppress the graph with the 32-bit counter.
* JIRA: http://issues.opennms.org/browse/NMS-9816

NMS-9816: Add Disk IO monitoring capabilities with Net-SNMP

---

features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapComponent.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapsApplication.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/MapNode.java
features/vaadin-node-maps/src/test/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapComponentTest.java

JIRA: https://issues.opennms.org/browse/NMS-9777
Here we:
1) Update the default refresh rate for the geo maps from 5s to 30s and allow it to be configured via the `org.opennms.features.nodemaps.refresh` system property.
2) Avoid updating the client state after a refresh triggered if the list of nodes was not changed, avoiding unnecessary re-rendering on the client side.

NMS-9777: Geographical maps refresh tweaks

---

opennms-base-assembly/src/main/filtered/etc/rws-nbinventoryreport.xsl
opennms-base-assembly/src/main/filtered/etc/rws-rancidlistreport.xsl
opennms-webapp/src/main/resources/org/opennms/web/controller/navbar.ftl
opennms-webapp/src/main/webapp/WEB-INF/jsp/support/index.jsp
opennms-webapp/src/main/webapp/about/index.jsp
opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
opennms-webapp/src/main/webapp/includes/footer.jsp
opennms-webapp/src/main/webapp/includes/help-contact.jsp
opennms-webapp/src/main/webapp/includes/help-documentation.jsp
opennms-webapp/src/main/webapp/includes/help-software-management.jsp
opennms-webapp/src/main/webapp/includes/support-system-diagnostics.jsp
smoke-test/src/test/java/org/opennms/smoketest/AboutPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/FooterIT.java
smoke-test/src/test/java/org/opennms/smoketest/HelpPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java
smoke-test/src/test/java/org/opennms/smoketest/SupportPageIT.java

The support page contains the web form which is used by OpenNMS administrators to open commercial support tickets. The account. This page is now restricted to Admin users. Introduced a Help page which gives information where to find documentation and to get in contact with people. To give users a better visibility what version of OpenNMS is running, the version number is added to the footer page. To make it easier getting version information about the running Open "About" page in the user's menu is added. The web site components are refactored to be reusable as JSP includes.
JIRA: https://issues.opennms.org/browse/NMS-9771

NMS-9771: Restructure and improve Help/Support pages

---

core/test-api/elasticsearch/pom.xml
core/test-api/elasticsearch/src/main/java/org/opennms/core/test/elastic/ElasticSearchServerConfig.java
core/test-api/elasticsearch/src/main/java/org/opennms/core/test/elastic/EmbeddedElasticSearchServer.java
features/flows/elastic/pom.xml
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/top_n_series.ftl
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowBuilder.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java

JIRA: https://issues.opennms.org/browse/HZN-1223
Here we enhance the Elasticsearch server used in our integration tests to support loading plugins specified by the test, and update the flow module to use the Drift plugin.
We currently use snapshot artifacts for the plugin, but we'll need to issue a tagged release before merging this to develop.

HZN-1223: Include the Drift plugin when running Elasticsearch in our integration tests.

---

container/features/pom.xml
container/features/src/main/resources/features-experimental.xml
container/features/src/main/resources/features-minion.xml
container/features/src/main/resources/features.xml
core/ipc/common/aws-sqs/src/main/resources/OSGI-INF/blueprint/blueprint.xml
core/ipc/rpc/aws-sqs-impl/src/main/resources/META-INF/opennms/applicationContext-rpc-client-sqs.xml
core/ipc/rpc/aws-sqs-impl/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-server.xml
core/ipc/rpc/jms-impl/src/main/resources/META-INF/opennms/applicationContext-rpc-client-jms.xml
core/ipc/sink/aws-sqs-impl/src/main/resources/OSGI-INF/blueprint/blueprint-ipc-client.xml
core/ipc/sink/camel-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-camel.xml
core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
features/opennms-osgi-core-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/rest-provider/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/telemetry/adapters/jti/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/telemetry/adapters/nxos/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/telemetry/minion/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-full-assembly/pom.xml
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/FeatureInstallKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsExperimentalFeaturesKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java

The PR creates a `features-experimental.xml` file for Karaf features that are not used in the product because they are not yet needed or do not load correctly due to OSGi dependency issues. These features may be useful at some point, for instance for running daemon processes or the webapp inside Karaf. I'm splitting them out so that people won't be confused by unsupported features inside the main `features.xml` file.
Please do not delete the branch, I'm using it for other work that's in progress.
* JIRA: http://issues.opennms.org/browse/HZN-1203

HZN-1203: Split experimental features out into separate repo

---

container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.logging.cfg

After upgrading Karaf, I left additivity set to `false` on the `org.opennms` logger without setting an appender for it. This meant that the log messages were dropped instead of being forwarded to the root appender. This fix should restore logging for our components inside `karaf.log`.
* JIRA: http://issues.opennms.org/browse/NMS-9773

NMS-9773: Restore root logger additivity to org.opennms logger

---

features/measurements/rest/pom.xml
features/measurements/rest/src/test/java/org/opennms/web/rest/v1/MeasurementRestServiceIT.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DefaultResourceDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceSnmpByIfIndexResourceType.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceSnmpResourceType.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/ResourceDaoIntegrityIT.java

JIRA: https://issues.opennms.org/browse/HZN-1226
Here we add a new resource type alias that allows SNMP interface to be referenced by ifIndex using a resource name of the form `interfaceSnmpByIfIndex[2]` instead of the existing `interfaceSnmp[em1-74867ad4b828]`.
This makes it possible to share the same interface identifier between both the Flow REST API and the Measurements API.

HZN-1226: Measurements API: Allow SNMP interfaces to be referenced by ifIndex

---

opennms-config/src/main/java/org/opennms/netmgt/config/NotificationManager.java
opennms-dao/src/test/java/org/opennms/netmgt/config/NotificationManagerIT.java

JIRA: https://issues.opennms.org/browse/NMS-9799
Here we update notifd to reference the new event_parameters table instead of the eventparms column when performing acknowledgments.

NMS-9799: Update notifd to reference new event_parameters table

---

container/servlet/src/main/java/org/opennms/container/web/WebAppListener.java

Removing this old workaround fixes the `ClassNotFoundException` inside `output.log`. I don't think there was any real effect on the logging: it seems to work identically regardless of the `log4j.ignoreTCL` setting (except for the `ClassNotFoundException` stack trace).
Right now, we have identical versions of log4j2 inside Karaf and in the OpenNMS system classpath (2.8.2). We'll have to keep an eye on this in case we ever have mismatched versions and then run into problems.
* JIRA: http://issues.opennms.org/browse/NMS-9695

NMS-9695: Fix ClassNotFoundException by removing log4j.ignoreTCL=true

---

container/features/pom.xml
container/features/src/main/resources/features-experimental.xml
container/features/src/main/resources/features-minion.xml
container/features/src/main/resources/features.xml
core/ipc/sink/aws-sqs-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-aws.xml
core/ipc/sink/camel-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-camel.xml
core/ipc/sink/kafka-impl/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-server-kafka.xml
core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
features/datachoices/pom.xml
features/telemetry/daemon/src/main/resources/META-INF/opennms/applicationContext-telemetryDaemon.xml
opennms-dao/pom.xml
opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
opennms-full-assembly/pom.xml
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/MinionFeatureKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsExperimentalFeaturesKarafIT.java
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
opennms-services/src/main/resources/META-INF/opennms/applicationContext-collectd.xml

This PR:
* Cleans up and reenables a bunch of Karaf integration tests
* Creates Karaf features for `opennms-collection-core` and `opennms-telemetry-daemon`
* Exposes the sink API and `CollectionAgentFactory` services in the `onmsgi` registry (which will be used by Telemetryd)
Please do not delete the branch after merging.
JIRA:
* http://issues.opennms.org/browse/HZN-1202
* http://issues.opennms.org/browse/HZN-1203

HZN-1202, HZN-1203: Karaf feature cleanup, OSGi service tweaks

---

container/features/pom.xml
container/features/src/main/resources/features.xml
features/amqp/alarm-northbounder/pom.xml
features/amqp/alarm-northbounder/src/main/resources/OSGI-INF/blueprint/blueprint-alarm-northbounder.xml
features/amqp/event-forwarder/pom.xml
features/amqp/event-forwarder/src/main/resources/OSGI-INF/blueprint/blueprint-event-forwarder.xml
features/amqp/event-receiver/pom.xml
features/amqp/event-receiver/src/main/resources/OSGI-INF/blueprint/blueprint-event-receiver.xml
features/amqp/pom.xml
opennms-doc/guide-development/src/asciidoc/text/amqp/alarm_northbounder.adoc
opennms-doc/guide-development/src/asciidoc/text/amqp/custom_processors.adoc
opennms-doc/guide-development/src/asciidoc/text/amqp/event_forwarder.adoc
opennms-doc/guide-development/src/asciidoc/text/amqp/event_receiver.adoc
opennms-doc/guide-development/src/asciidoc/text/amqp/introduction.adoc
opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java

JIRA: https://issues.opennms.org/browse/NMS-9836
We were remove the calls to the legacy QPID client, and use the connection factory provided by Camel instead. This fixes compatibility with AMQP 1_0_0.
Also updated the documentation, and fixed a number of typos.
Tested against a standalone ActiveMQ 5.12.5 broker.

NMS-9836: Use the AMQP connection factory bundled with Camel

---

features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Oops, I used a Calendar value instead of a java.time value. :P This will need to be merged into all branches from `foundation-2017` and higher to fix the test.

Fix SyslogMessageTest after February wrap

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/minion.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-minion-graph.properties

Add mbeans/graphs for kafka topics ingestion rate ( rate at which records are being sent).  records/sec  where 1 record is 1 offset in topic.
* JIRA: http://issues.opennms.org/browse/hzn-1220

HZN-1220: add mbeans/graphs for kafka topics ingestion rate

---

features/bsm/daemon/pom.xml
features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java

JIRA: https://issues.opennms.org/browse/NMS-9835
This will reduce overhead on systems that have bsmd enabled (by default) but do not have any business rules defined.

NMS-9835: Avoid unecessary AlarmDao calls when no business rules are defined.

---

opennms-assemblies/minion/src/main/filtered/etc/minion.init
tools/packages/minion/minion.spec
tools/packages/opennms/opennms.spec

This PR fixes the Minion init to make sure `$MINION_HOME/data` exists.
It also changes `find -print` calls to use `-print0` to make sure there aren't issues with spaces in filenames.  Shouldn't affect anything, but it's best practice when shell scripting.  :)
* JIRA: http://issues.opennms.org/browse/NMS-9833

NMS-9833: fix startup to make sure $MINION_HOME/data exists

---

features/opennms-es-rest/main-module/pom.xml
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/test/BasicAuthTest.java

JIRA: https://issues.opennms.org/browse/NMS-9699
Here we update the `RestClientFactory` to preserve basic authentication credentials when set.

NMS-9699: Fix basic authentication with Elastisearch.

---

features/amqp/alarm-northbounder/src/main/java/org/opennms/features/amqp/alarmnorthbounder/AlarmNorthbounder.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/AnnotationBasedEventListenerAdapter.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/ThreadAwareEventListener.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImpl.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventIpcManagerDefaultImplTest.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
features/ncs/ncs-northbounder/src/main/etc/ncs-northbounder-configuration.xml
features/ncs/ncs-northbounder/src/main/java/org/opennms/netmgt/ncs/northbounder/NCSNorthbounder.java
opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/Northbounder.java
opennms-alarms/api/src/test/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounderTest.java
opennms-alarms/bsf-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/bsf/BSFNorthbounder.java
opennms-alarms/bsf-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/bsf/BSFNorthbounderManager.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersister.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/StripedExt.java
opennms-alarms/daemon/src/main/resources/META-INF/opennms/applicationContext-alarmd.xml
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
opennms-alarms/drools-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/drools/DroolsNorthbounder.java
opennms-alarms/drools-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/drools/DroolsNorthbounderManager.java
opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounder.java
opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounderManager.java
opennms-alarms/http-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/http/HttpNorthbounder.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounder.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounderManager.java
opennms-alarms/snmptrap-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/snmptrap/SnmpTrapNorthbounder.java
opennms-alarms/snmptrap-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/snmptrap/SnmpTrapNorthbounderManager.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounder.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderManager.java

JIRA: https://issues.opennms.org/browse/NMS-9846
This PR contains a number of fixes aimed at improving the processing speed of alarmd:
* Process events in parallel while use a fair striped lock on both the reduction and clear keys to continue processing events in order.
* Avoid further processing required by northbounder (NBIs) if none are enabled.
On my system, I was able to double the rate at which events were processed with these changes. The `events:stress` command has been update with an example showing how `alarmd` can be benchmarked.

NMS-9846: Improve event processing rate in alarmd

---

opennms-base-assembly/src/main/filtered/bin/opennms-thread-dump

* JIRA: http://issues.opennms.org/browse/NMS-9872
I've tested this version with Horizon 21.0.3. It may have issues with older Meridians, but I favor getting it out there and taking the bugs if they come.

NMS-9872: Add a command-line tool to create a thread dump

---

tools/packages/minion/create-minion-assembly.sh
tools/packages/minion/get-id.xsl

This PR fixes the RPM minion build to build all dependencies in `features/minion` by parsing the POM files.
* JIRA: http://issues.opennms.org/browse/NMS-9869

NMS-9869: build all projects in features/minion

---

features/vaadin-opennms-pluginmanager/src/main/filtered-resources/productSpec.xml
features/vaadin-opennms-pluginmanager/src/main/resources/OSGI-INF/blueprint/blueprint.xml
pom.xml

* JIRA: https://issues.opennms.org/browse/HZN-1260 Missing Plug-in Manager in Windows installation
This patch changes the path settings in Plugin Manager blueprint.xml files from referencing the OpenNMS etc directory using ./etc which does not appear to work in windows. As a result of these changes the Plugin Manager should now start up correctly in windows environments.
We are now referencing using
<ext:property-placeholder placeholder-prefix="$[" placeholder-suffix="]" />
and
$[karaf.etc]$[file.separator].
Similar changes have been made in the OSGI Plugin Manager which has now been updated to Version 1.0.7
Bamboo passes https://bamboo.opennms.org/browse/OPENNMS-ONMS2074-3

jira/HZN-1260 Missing Plug-in Manager in Windows installation

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java

* JIRA: https://issues.opennms.org/browse/HZN-1268

HZN-1268: Use timestamp of flow instead of current date for index creation

---

.gitignore
core/web-assets/src/main/assets/js/apps/onms-graph/index.js
core/web-assets/src/main/assets/js/vendor/bootstrap-js.js
core/web-assets/src/main/assets/js/vendor/flot-js.js
core/web-assets/src/main/assets/js/vendor/jquery-js.js
core/web-assets/webpack.config.js

This fixes how a number of scripts in `core/web-assets` reference jQuery, using the webpack `ProvidePlugin` rather than attempting to manipulate window.jQuery directly.
* JIRA: http://issues.opennms.org/browse/NMS-9927

NMS-9927: fix Backshift (and maybe others) jQuery import

---

protocols/radius/pom.xml
protocols/radius/src/main/java/org/opennms/protocols/radius/detector/RadiusAuthDetector.java
protocols/radius/src/main/java/org/opennms/protocols/radius/monitor/RadiusAuthMonitor.java
protocols/radius/src/main/java/org/opennms/protocols/radius/springsecurity/RadiusAuthenticationProvider.java
protocols/radius/src/main/java/org/opennms/protocols/radius/utils/RadiusUtils.java

* JIRA: http://issues.opennms.org/browse/NMS-9763
This is an ugly hack to get the radius stuff working again: It uses the MD4 implementation from jcifs and provides is to the security service interface, so jradius can pick it up.
The _clean_ solution would be to use BouncyCastle, but it breaks the karaf SSH shell.
Note: Having a OSGI bundle for each monitor implementation would be neat.

NMS-9763: Added MD4 provider for Radius

---

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/ConversationKey.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ConversationKeyUtils.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/SearchQueryProvider.java
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_missing.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_others.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_terms.ftl
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ConversationKeyUtilsTest.java
features/flows/elastic/src/test/resources/flow-document-netflow5.json

JIRA: https://issues.opennms.org/browse/HZN-1275
Here we rework some of the logic related to conversation tagging for flows and update it to use the actual direction (ingress vs egress) instead of the "initiator" field.

HZN-1275: Use the direction instead of the initiator field to establish conversation directionality

---

core/web-assets/src/main/assets/js/apps/onms-classifications/index.js

The original PR https://github.com/OpenNMS/opennms/pull/1893 was created against `develop` and we forgot to adapt `features/drift` as well. 
Here we apply the changes from `NMS-9783` to `features/drift`.
* JIRA: https://issues.opennms.org/browse/NMS-9783

NMS-9783: Add missing header to onms-classifications angular app

---

features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/AlarmChangeNotificationClient.java
features/alarm-change-notifier/main-module/src/main/java/org/opennms/plugins/dbnotifier/alarmnotifier/MemosChangeNotificationClient.java
features/events/api/src/main/java/org/opennms/netmgt/xml/event/Value.java
features/opennms-es-rest/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/opennms-es-rest/src/test/java/org/opennms/plugins/elasticsearch/rest/AbstractEventToIndexTest.java
features/opennms-es-rest/src/test/java/org/opennms/plugins/elasticsearch/rest/AlarmEventToIndexTest.java
features/opennms-es-rest/src/test/java/org/opennms/plugins/elasticsearch/rest/EventToIndexTest.java
opennms-doc/guide-admin/src/asciidoc/text/plugins/opennms-es-rest.adoc

Here we address some issues with the opennms-es-rest and opennms-alarm-change-notifier modules. It was easier to address it in one branch, than have the branches separated:
* JIRA: https://issues.opennms.org/browse/NMS-9831
* JIRA: https://issues.opennms.org/browse/HZN-1272
Please also note, that this change should also be merged to `release-21.x`.
As we changed the underlying structure for drift and `22.0.0` I will manually backport these changes to `21.x` as soon as this is considered okay.

NMS-9831,HZN-1272: Handle OID event parameter keys and JSON event parameter values correctly

---

opennms-model/src/main/java/org/opennms/netmgt/model/events/EventUtils.java

Alternate PR for NMS-9941 which goes to Foundation 2016 and uses `Objects.equals()` to handle null more gracefully.
* JIRA: http://issues.opennms.org/browse/NMS-9941

NMS-9941: fix eventsMatch() behavior on node IDs

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/InvalidCollectionAgentException.java
features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java
features/telemetry/itests/src/test/java/org/opennms/netmgt/telemetry/itests/JtiIT.java
features/telemetry/itests/src/test/resources/META-INF/opennms/applicationContext-collectionAgentFactory.xml
opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
opennms-services/src/main/java/org/opennms/netmgt/collectd/DefaultSnmpCollectionAgentFactory.java
opennms-services/src/main/java/org/opennms/netmgt/collectd/SnmpCollector.java
opennms-services/src/main/resources/META-INF/opennms/applicationContext-collectd.xml

JIRA: https://issues.opennms.org/browse/NMS-9885
Update the default CollectionAgentFactory implementation to create instances of the SnmpCollectionAgent as opposed to the DefaultCollectionAgent so that these work with all of the collectors.
Also improve the error message when the SnmpCollector is invoked via the collection:collection command without specifying a valid node/interface pair.

NMS-9885: collection:collect command fails with ClassCastException

---

pom.xml

JIRA: https://issues.opennms.org/browse/NMS-9948
The more recent vaadin maven plugin passes the classpath as an environment variable instead of as a command line parameter - which breaks on windows due to its length.

NMS-9948: Update vaadin maven plugin

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryInitializer.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/CachingTemplateLoaderTest.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/DefaultTemplateLoaderTest.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/template/MergingTemplateLoaderTest.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/CachingTemplateLoader.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/DefaultTemplateInitializer.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/DefaultTemplateLoader.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/MergingTemplateLoader.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/TemplateLoader.java
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/template/Version.java
features/jest/client/src/test/java/org/opennms/plugins/elasticsearch/rest/template/DefaultTemplateLoaderTest.java
features/opennms-es-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/opennms-es-rest/src/main/resources/eventsIndexTemplate.es6.json
smoke-test/src/test/java/org/opennms/smoketest/minion/AbstractSyslogTestCase.java
smoke-test/src/test/java/org/opennms/smoketest/minion/SyslogKafkaElasticsearch6IT.java

JIRA: https://issues.opennms.org/browse/HZN-1276
Here we fix the event and alarm templates for ES 6.x by adding support for version aware templates.
We also include system tests for indexing in ES 6.x similar to those that were already present for ES 5.x.

HZN-1276: Fix the event and alarm templates for Elasticsearch 6.x

---

core/lib/src/main/java/org/opennms/core/utils/DBTools.java
core/lib/src/test/java/org/opennms/core/utils/DBToolsTest.java

Fix bug caused due to replacing OPENNMS_JDBC_HOSTNAME
* JIRA: http://issues.opennms.org/browse/NMS-9952

NMS-9952: Fix jdbc-collector default host name.

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/UserGroupLdapAuthoritiesPopulator.java
opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/activeDirectory.xml.disabled
opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/ldap.xml.disabled

By adding the empty named group, one can leverage the existing group
maping by adding something like
```
"" => [ROLE_USER, ROLE_DASHBOARD]
```
which will be applied to all users.
* JIRA: http://issues.opennms.org/browse/NMS-9937

NMS-9937: Always add group with empty name

---

container/features/src/main/resources/features.xml
core/lib/pom.xml
core/lib/src/main/java/org/opennms/core/fileutils/FileUpdateCallback.java
core/lib/src/main/java/org/opennms/core/fileutils/FileUpdateWatcher.java
core/lib/src/test/java/org/opennms/core/fileutils/FileUpdateWatcherTest.java
features/telemetry/adapters/collection/src/main/java/org/opennms/netmgt/telemetry/adapters/collection/AbstractPersistingAdapter.java
features/telemetry/adapters/jti/src/main/java/org/opennms/netmgt/telemetry/adapters/jti/JtiGpbAdapter.java
features/telemetry/adapters/netflow/src/main/java/org/opennms/netmgt/telemetry/adapters/netflow/AbstractAdapter.java
features/telemetry/adapters/nxos/src/main/java/org/opennms/netmgt/telemetry/adapters/nxos/NxosGpbAdapter.java
features/telemetry/adapters/nxos/src/main/java/org/opennms/netmgt/telemetry/adapters/nxos/NxosTelemetryClient.java
features/telemetry/daemon/src/main/java/org/opennms/netmgt/telemetry/daemon/TelemetryMessageConsumer.java
features/telemetry/daemon/src/main/java/org/opennms/netmgt/telemetry/daemon/Telemetryd.java

Add generic fileUpdateWatcher,   use this watcher for groovy scripts.
When groovy script file updates, check and load updated script if it builds else use existing script.
* JIRA: http://issues.opennms.org/browse/HZN-1279

HZN-1279: Make the telemetry groovy scripts reloadable

---

core/soa/src/main/java/org/opennms/core/soa/lookup/BlockingServiceLookup.java
core/soa/src/main/java/org/opennms/core/soa/lookup/ServiceLookupBuilder.java
features/telemetry/adapters/registry/src/main/java/org/opennms/features/telemetry/adapters/registry/impl/TelemetryAdapterRegistryImpl.java

JIRA: https://issues.opennms.org/browse/HZN-1301
Fix intermittent telemetryd adapter loading when the startup process takes a long time.

HZN-1301: Improve service lookup reliability by adding a relative timeout

---

core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/offset/HostAndPort.java
core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/offset/KafkaOffsetProvider.java
core/ipc/sink/kafka-impl/src/test/java/org/opennms/core/ipc/sink/kafka/offset/HostAndPortTest.java

Support multiple brokers in kafka server configuration for offset calculation, Try other brokers in config.
If any of them doesn't connect in 1 minute, try another. Keep trying from the list
* JIRA: http://issues.opennms.org/browse/NMS-9910

NMS-9910: Update OffsetProvider to connect to alternate brokers

---

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/SSLCertMonitor.java

JIRA: https://issues.opennms.org/browse/NMS-9962
Enhance SSLCertMonitor.java warning message.
Make 'expires in X days' be 'expires within X days' and add expiry date.

NMS-9962: Enhance SSLCertMonitor.java warning message

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/downtime-model.adoc

* Documentation needed an update because of the changes in: https://issues.opennms.org/browse/NMS-9257
* Jira: https://issues.opennms.org/browse/NMS-10069

NMS-10069: replaced default downtime model config in the doc

---

opennms-base-assembly/src/main/filtered/etc/datacollection/ceragon-FA1500.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/konica.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/paloalto.xml

The sysoidMask value can cause unwanted sideffects when the sysoidMask does not end with a "." character. All sysoid defintions which match a full described sysoid are set to sysoid instead of sysoidMask.
* JIRA: http://issues.opennms.org/browse/NMS-9958

NMS-9958: Set correct sysoid definitions in datacollection

---

opennms-base-assembly/src/main/filtered/etc/datacollection/microsoft.xml

Remove Cisco Call Manager stats from all Windows Server
* JIRA: http://issues.opennms.org/browse/NMS-10144

NMS-10144: Remove Cisco Call Manager stats from all Windows Server

---

opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/hp.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/microsoft.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/ref_compaq-insight-manager.xml

Remove Compaq Insight Manager statistics data collection from all Windows servers.
* JIRA: http://issues.opennms.org/browse/NMS-10143

NMS-10143: Remove by default to collect Compaq Insight Manager stats

---

opennms-base-assembly/src/main/filtered/etc/datacollection/microsoft.xml

Remove by default Checkpoint firewall SNMP metrics from every Windows server
* JIRA: http://issues.opennms.org/browse/NMS-10142

NMS-10142: Remove checkpoint data collection from all Windows servers

---

opennms-base-assembly/src/main/filtered/etc/datacollection/cisco.xml

The sysoid for current Cisco CallManager releases has change since they moved from a hardware appliance to a virtual appliance.  This change adds a second systemDef block to catch the virtual appliance.
NMS-9936 - Datacollection for Cisco Call Manager as old OID
* JIRA: https://issues.opennms.org/browse/NMS-9936

NMS-9936 - OID for new Cisco CallManager

---

opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/mib2.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/netsnmp.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/ref_mib2-powerethernet.xml

Remove Power over Ethernet MIB data collection from all SNMP agents supporting Standard MIB-II and from Net-SNMP agents by default. For the reason they can be added to any Vendor who supports the standard PoE MIB it is added and included as a Reference file (REF_...) and can included to any vendor who supports it.
* JIRA: http://issues.opennms.org/browse/NMS-10138

NMS-10138: Remove Power over Ethernet MIB data collection by default

---

opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/legacy_mib2-interfaces.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/mib2.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/ref_mib2-interfaces.xml
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

A lot of devices add 64bit counter additional to the 32bit counter. This means the interface metrics are collected twice. Make the 64bit counter default and just allow the user to add 32bit counter on legacy devices and reduce the data collection by default.
The old 32bit MIB-II interface counter is added as a reference file which is not assigned by default to any system definition. They need to be added to legacy devices which support only 32bit counter and not 64bit counter by default.
* JIRA: http://issues.opennms.org/browse/NMS-10139

NMS-10139: Make 64bit interface counter default

---

opennms-base-assembly/src/main/filtered/etc/datacollection/cisco.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/ciscoNexus.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/extreme.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/f5.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/force10.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/foundry.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/juniper.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/netsnmp.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/paloalto.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/pfsense.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/riverbed.xml

Remove overlapping MIB-II overlapping 64bit interface counter from default, cause they are already collected by default from MIB-2 Interface configuration. More details are described in JIRA.
This PR depends on PR #1964 
* JIRA: http://issues.opennms.org/browse/NMS-10141

NMS-10141: Remove overlapping MIB-2 64bit counter configs

---

opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

Line 70: missing closing format ` tag
Line 105: missing W at "counters are no disabled by default"
NMS-10161 - Typos in Horizon 22.0.0 release notes
* JIRA: https://issues.opennms.org/browse/NMS-10161

NMS-10161 - Typos in Horizon 22.0.0 release notes

---

opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

Line 19: misspelling of "performance"
NMS-10161: Typos in Horizon 22.0.0 release notes
* JIRA: https://issues.opennms.org/browse/NMS-10161

NMS-10161: Typos in Horizon 22.0.0 release notes (part 2)

---

opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounder.java
opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounder.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounder.java
opennms-alarms/jms-northbounder/src/test/java/org/opennms/netmgmt/alarmd/northbounder/jms/JmsNorthBounderTest.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounder.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderConfig.java
opennms-alarms/syslog-northbounder/src/main/resources/xsds/syslog-northbounder-configuration.xsd
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogConfigDaoTest.java
opennms-alarms/syslog-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthBounderWithFiltersTest.java
opennms-alarms/syslog-northbounder/src/test/resources/syslog-northbounder-config1.xml
opennms-base-assembly/src/main/filtered/etc/syslog-northbounder-configuration.xml

Add  `<date-format>`  tag in  `syslog-northbounder-configuration.xml`.
It allows  date format in  FIRST and LAST occurence to be specified by users. Default formatting would be  `yyyy-MM-dd HH:mm:ss`
* JIRA: http://issues.opennms.org/browse/NMS-10158

NMS-10158: Allow configuring date format in syslog north bounder 

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-dao/pom.xml
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceToNodeCacheEventProcessor.java
opennms-dao/src/main/resources/META-INF/opennms/applicationContext-dao.xml
opennms-dao/src/test/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImplIT.java

* JIRA: https://issues.opennms.org/browse/HZN-1311
At this point I keep the existing behaviour as is, but enable the cache to refresh itself if so desired.
Shall we make it automatically refresh by default?

HZN-1311: Enable InterfaceToNodeCache to refresh itself

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/Rfc5424SyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogConfigBean.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogParser.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/Rfc5424SyslogParserTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java
opennms-base-assembly/src/main/filtered/etc/syslogd-configuration.xml
opennms-config-model/src/main/java/org/opennms/netmgt/config/syslogd/Configuration.java
opennms-config-model/src/main/resources/xsds/syslog.xsd
opennms-config-model/src/test/java/org/opennms/netmgt/config/syslogd/ConfigurationTest.java
opennms-config/src/main/java/org/opennms/netmgt/config/SyslogdConfig.java
opennms-config/src/main/java/org/opennms/netmgt/config/SyslogdConfigFactory.java

* JIRA: https://issues.opennms.org/browse/NMS-10164

NMS-10164 Support customizing the default time zone when parsing dates in syslog messages

---

opennms-doc/guide-development/src/asciidoc/text/rest/rest-api.adoc

* JIRA: https://issues.opennms.org/browse/NMS-8524

NMS-8524: The ReST API used to return XMLs with namespace, and now it doesn't

---

core/web-assets/src/main/assets/js/vendor/bootstrap-js.js
core/web-assets/src/main/assets/js/vendor/jquery-js.js

This PR fixes the heatmap when it's included on the front page (with, eg, `org.opennms.web.console.centerUrl=/heatmap/heatmap-box.jsp`).  It also very likely fixes some other race-conditions in things attempting to use jQuery UI, since there was an issue with the bootstrap js included globally that could step on the initialized jQuery.
* JIRA: http://issues.opennms.org/browse/HZN-1316

HZN-1316: fix heatmap when included on the front page

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/SituationIT.java
opennms-base-assembly/pom.xml

This PR provides support for Alarmd to create and update Situations from events received with the one or more parameters with name 'related-reductionKey'. e.g.: 
-p 'related-reductionKey uei.value1' 
Each 'related-reductionKey' that resolves to an existing Alarm will be grouped under the Situation.
* JIRA: https://issues.opennms.org/browse/HZN-1326

HZN-1326: Alarmd support for Situations

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/plugin-manager/installing-available-plugins.adoc
opennms-doc/guide-admin/src/asciidoc/text/plugin-manager/internal-plugins-repository.adoc
opennms-doc/guide-admin/src/asciidoc/text/plugin-manager/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/plugin-manager/licence-structure.adoc
pom.xml

This pull request adds enhancements to the OpenNMS Plugin Manager
Jira : https://issues.opennms.org/browse/HZN-1291 Enhancements to Plugin Manager
Enhancements include
* Improved  UI
* More functions available through ReST
* Ability for a 'manifest' of plug-in features to be downloaded by remote at start-up to control which features to install when a remote Karaf is started
* Licence can contain 'secret properties' which can only be read when the licence is decoded
*  Rolling backup licence file to prevent corruption of licences on power fail
The enhancements have actually been made in the Plugin Manager 1.1.0 project
https://github.com/OpenNMS/osgi-plugin-manager/tree/v1.1.0/
This pull request simply ups the version of the plugin manager called into OpenNMS and adds some additional …

HZN-1291: Enhancements to Plugin Manager

---

container/shared/pom.xml
features/container/sentinel/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
opennms-doc/guide-admin/src/asciidoc/text/sentinel/sentinel.adoc
smoke-test/src/test/resources/sentinel/features-jms.xml
smoke-test/src/test/resources/sentinel/features-kafka.xml

Here we make all relevant features known to the sentinel container, to not use the `karaf-extender`, as in case of minion.
* JIRA: https://issues.opennms.org/browse/HZN-1344

HZN-1344: Add all default sentinel feature repositories to cfg

---

opennms-base-assembly/src/main/filtered/etc/datacollection/microsoft.xml

The SNMP agent on Microsoft is going to be deprecated and support for 64-bit counter will probably never happen. Re-add the 32-bit counter for Microsoft Windows systems.
* JIRA: http://issues.opennms.org/browse/NMS-10247

NMS-10247: Re-add legacy 32-bit interface counter for Microsoft Windows

---

core/db-install/src/main/resources/org/opennms/core/db/install/iplike.sql
core/test-api/db/src/test/java/org/opennms/core/test/db/IPLikeCoverageIT.java
core/test-api/db/src/test/java/org/opennms/core/test/db/InstallerDbIT.java
core/test-api/db/src/test/java/org/opennms/core/test/db/InstallerDbITCase.java

These changes do a number of things to fix the behavior of matching
to more closely follow the C version of IPLIKE.  It also includes
a few "best practices" fixes.
* do simple matching of scope identifiers
* use 'if X is not true' rather than 'if not X' to avoid incorrect matches when NULL is returned
* handle wildcards in hex rule checks properly
* JIRA: http://issues.opennms.org/browse/NMS-10238

NMS-10238: match behavior of all test data from C IPLIKE

---

opennms-base-assembly/src/main/filtered/etc/datacollection/mib2.xml

This issue re-adds the MIB2 32-bit counters for interface errors. The counters were removed by NMS-10139 which removed the duplicated data collection for 32-bit and 64-bit interface counters.
* JIRA: http://issues.opennms.org/browse/NMS-10195

NMS-10195: Re-add MIB2 interface errors to default data collection

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/path-outages.adoc

in path-outage.adoc, there's a reference to a file `called pollerd-configuration.xml` instead of `poller-configuration.xml`
No JIRA issue for this PR
BR
Cyrille

corrected typo in path-outage.adoc

---

core/test-api/camel/src/main/java/org/opennms/core/test/camel/CamelBlueprintTest.java

* JIRA: https://issues.opennms.org/browse/HZN-1361
As mentioned yesterday, here we disable `isUseDebugger()` as it is causing weird issues and make some tests flap.

HZN-1361: Do not use debugger in CamelBlueprintTests

---

opennms-doc/asciidoctor-default.css

Oriented a little on a more neutral Google documentation style for text contrast and backgrounds. The removed red-brown color does not break so much with Horizon and Meridian styles. Removed shadows mainly for admonitions and used tango colors for admonitions. Removed the italic font in captions. Links in the text are dashed lined to indicate a link.
It is also going to be closer to the stylesheet used in Helm.
* JIRA: http://issues.opennms.org/browse/NMS-10278

NMS-10278: Neutralise the stylesheet

---

debian/control
debian/opennms-webapp-hawtio.conffiles
debian/opennms-webapp-hawtio.overrides
debian/rules
opennms-full-assembly/pom.xml
opennms-full-assembly/src/assembly/components/webapps.xml
pom.xml
tools/packages/opennms/opennms.spec

This PR embeds Hawtio in the webapp by unpacking it into `$OPENNMS_HOME/jetty-webapps/hawtio/` (and removing slf4j and log4j from `WEB-INF/lib/` to avoid conflicts).
* JIRA: http://issues.opennms.org/browse/NMS-9858

NMS-9858: embed Hawtio in jetty-webapps & create packages

---

opennms-correlation/opennms-correlator/pom.xml
opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/Correlator.java
opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/CorrelatorEngineAdapterTest.java

JIRA: https://issues.opennms.org/browse/NMS-10257

NMS-10257: Only refresh the event listener when handling a reloadDaemonConfig event

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java

* JIRA: http://issues.opennms.org/browse/NMS-10291

NMS-10291: DefaultProvisionService logs noisily for monitored service having state "N"

---

opennms-base-assembly/src/main/filtered/etc/log4j2.xml

back porting kafka logging to foundation-2018.
* JIRA: http://issues.opennms.org/browse/NMS-10269

NMS-10269: Set kafka logging to INFO by default

---

opennms-alarms/api/src/main/java/org/opennms/netmgt/alarmd/api/support/AbstractNorthbounder.java
opennms-alarms/jms-northbounder/src/test/java/org/opennms/netmgmt/alarmd/northbounder/jms/JmsNorthBounderTest.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderConfig.java
opennms-alarms/syslog-northbounder/src/main/resources/xsds/syslog-northbounder-configuration.xsd
opennms-base-assembly/src/main/filtered/etc/syslog-northbounder-configuration.xml

Use ISO8601 date format conversion like [here](https://github.com/OpenNMS/opennms/blob/c1cb2d3777059be9672218491b6374ee4140ded9/core/lib/src/main/java/org/opennms/core/utils/StringUtils.java#L249) instead of specifying it in `yyyy-MM-dd'T'HH:mm:ss.SSS` format.
Remove default date format in xml, it will still default to ISO8601 format.
* JIRA: http://issues.opennms.org/browse/NMS-10282

NMS-10282: Use ISO8601 date format conversion from StringUtils

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java

* JIRA: http://issues.opennms.org/browse/NMS-10272

NMS-10272: Syslog messages should default to being associated with the hosts from which they were received

---

smoke-test/src/test/java/org/opennms/smoketest/flow/FlowStackIT.java
smoke-test/src/test/java/org/opennms/smoketest/health/HealthCheckIT.java
smoke-test/src/test/java/org/opennms/smoketest/sentinel/AbstractFlowIT.java
smoke-test/src/test/java/org/opennms/smoketest/sentinel/FlowStackJmsIT.java
smoke-test/src/test/java/org/opennms/smoketest/sentinel/FlowStackKafkaIT.java
smoke-test/src/test/resources/sentinel/features-jms.xml
smoke-test/src/test/resources/sentinel/features-kafka.xml
smoke-test/src/test/resources/sentinel/org.opennms.features.telemetry.listeners-udp-50001.cfg
smoke-test/src/test/resources/sentinel/org.opennms.features.telemetry.listeners-udp-50002.cfg
smoke-test/src/test/resources/sentinel/org.opennms.features.telemetry.listeners-udp-50003.cfg

* JIRA: https://issues.opennms.org/browse/HZN-1366
Here we verify that all flow adapters run on sentinel, not just the `Netflow5Adapter`.

HZN-1366: Enable all adapters and verify them

---

opennms-tools/jrb-to-rrd-converter/pom.xml

This module's pom.xml uses the older "attached" goal, which was
deprecated in maven-assembly-plugin 2, and removed in 3, yielding this
error:
[ERROR] Could not find goal 'attached' in plugin
org.apache.maven.plugins:maven-assembly-plugin:3.0.0 among available
goals help, single -> [Help 1]
* JIRA: https://issues.opennms.org/browse/HZN-1359

HZN-1359: Fix the build of the jrb-to-rrd-converter

---

features/situation-feedback/rest/api/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestService.java
features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
features/situation-feedback/rest/impl/src/test/java/org/opennms/features/situationfeedback/rest/SituationFeedbackrestServiceIT.java

JIRA: https://issues.opennms.org/browse/HZN-1355
This PR modifies the SituationFeedback REST API to use the AlarmId as the identifier of the Situations.

HZN-1355: Use AlarmId to reference Situation

---

opennms-javamail/opennms-javamail-api/src/main/java/org/opennms/javamail/JavaMailer.java

* JIRA: https://issues.opennms.org/browse/NMS-9027

NMS-9027: Added Content-Type header to JavaMailer

---

core/upgrade/src/main/java/org/opennms/upgrade/implementations/MagicUsersMigratorOffline.java
core/upgrade/src/test/java/org/opennms/upgrade/implementations/MagicUsersMigratorOfflineIT.java
core/upgrade/src/test/resources/etc/users-2015.xml

1. It was possible for upgrade to fail if `read-only="false"` tags existed without any `true` read-only user.
2. There are cases when the `read-only` flag could fail to be parsed out on upgrade.
This version implements simple DOM parsing instead of direct string manipulation to avoid any unmarshalling issues.
* JIRA: http://issues.opennms.org/browse/NMS-9267

NMS-9267: fix some issues in users.xml handling in the migrator

---

core/schema/src/main/liquibase/23.0.0/changelog.xml
features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/AlarmService.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/MaxSeverityAccumulateFunction.java
opennms-alarms/daemon/src/main/resources/META-INF/kie.properties.conf
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdBlackboxIT.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/driver/AlarmdDriver.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/driver/Scenario.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/driver/ScenarioResults.java
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/alarmd.drl
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/situations.drl
opennms-base-assembly/src/main/filtered/etc/create.sql
opennms-base-assembly/src/main/filtered/etc/events/opennms.alarm.events.xml
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java

JIRA: https://issues.opennms.org/browse/HZN-1381
With this update, the Drools rules now automatically set the severity of the situations to be the maximum severity of the related child alarms. This improves the life-cycle of situations by ensuring that they get cleared and delete similar to alarms.

HZN-1381: Situation severity should be set to max related alarm severity

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-web-api/src/main/java/org/opennms/web/svclayer/model/RelativeTimePeriod.java
opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java

This PR fixes a long-standing regression and make the default relative time period 1 day again, rather than 1 hour.
I also add a property (`org.opennms.web.defaultGraphPeriod`) for setting the default, if you prefer the old behavior of 1 hour.
* JIRA: http://issues.opennms.org/browse/NMS-10324

NMS-10324: make the default relative time period 1 day again

---

container/features/src/main/resources/features.xml
pom.xml
protocols/xml/pom.xml

JIRA: https://issues.opennms.org/browse/NMS-10286
* Upgraded json-lib to v2.4 since ServiceMix provides
bundles for that version
* Added related dependencies to the Karaf feature definition
There are no new tests for this, but the dependency is marked as mandatory, so existing tests will catch the failure if the json-lib dependency is not met.

NMS-10286: Fix the JsonCollector on Minion

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java
opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java

JIRA: https://issues.opennms.org/browse/NMS-10331
Here we add a new flag that allows us to force alarmd to create a new alarm instead of reducing onto the existing alarm when it is already cleared.
This can be used to make sure there is a single `OnmsAlarm` entity per problem.

NMS-10331: Optionally create new alarms when a problem reoccurs

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/AlarmEqualityChecker.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/KafkaAlarmDataSync.java
features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
opennms-doc/guide-admin/src/asciidoc/text/kafka-producer/kafka-producer.adoc

HZN-1383: Added new configuration to the OpennmsKafkaProducer to suppress sending alarms that differ from an existing alarm only by the count or last event time. Also added equivalent functionality in the KafkaAlarmDataSync.
* JIRA: http://issues.opennms.org/browse/HZN-1383

HZN-1383: Kafka Producer: Don't forward alarms for every reduce

---

features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/AlarmFeedback.java
features/situation-feedback/elastic/src/test/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepositoryIT.java
features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
features/situation-feedback/rest/impl/src/test/java/org/opennms/features/situationfeedback/rest/SituationFeedbackrestServiceIT.java

This PR corrects a bug where a typo in the enum prevented negative feedback from being submitted.

OCE-REST: fix broken negative feedback submission

---

opennms-assemblies/minion/src/main/filtered/etc/minion.init
tools/packages/minion/minion.spec
tools/packages/opennms/opennms.spec

Karaf's `bin/inc` only initializes `JAVA_OPTS` if it isn't already set, so in most cases our default init scripts were ignoring most of the values set in `/etc/sysconfig/minion`.
This PR fixes that.
* JIRA: http://issues.opennms.org/browse/NMS-10332

NMS-10332: fix minion init to honor sysconfig

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ForceRescanScan.java

* JIRA: https://issues.opennms.org/browse/NMS-10370
`2018-09-25 20:46:27,735 INFO  [scanExecutor-8] o.o.n.p.s.ForceRescanScan: The node with ID OP does not have a primary interface` will no longer be printed for nodes with valid primary SNMP interfaces.
Should the node lack a primary SNMP interface, for any reason, the log message will be printed with the proper node ID:
`2018-09-25 21:04:48,939 INFO  [scanExecutor-3] o.o.n.p.s.ForceRescanScan: The node with ID 40 does not have a primary interface`

NMS-10370: fix misleading INFO log message

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/cassandra30x-newts.xml
opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/cassandra30x.xml

* JIRA: https://issues.opennms.org/browse/NMS-10352
Changes type from 'gauge' to 'counter' for MemtableSwitchCount and
the DroppedMessage attributes, to match the JMX types.

NMS-10352: Fix type for some Cassandra JMX values

---

bin/functions.pl
opennms-base-assembly/src/main/filtered/bin/find-java.sh

This PR fixes a number of bugs when handling newer OpenJDK versions (with date-stamps at the end of the version line) and JDK 9+

NMS-10401: Handle new JDK versions

---

core/db-install/src/main/java/org/opennms/core/db/install/InstallerDb.java

This PR fixes a mismatch between integer types in PostgreSQL vs. the `InstallerDb` code.  It is causing build failures on anything that runs on `ncstate` at the moment because apparently oids have gotten past the 2^31 limit there.
I went ahead and made this against `foundation` since the 2015 branch is still technically supported for 2 more years for Powered By customers.  Plus, it makes sure that pretty much any build will pass again.
* JIRA: http://issues.opennms.org/browse/NMS-10402

NMS-10402: convert int types to long to handle 32-bit unsigned values

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/minion.xml

* JIRA: https://issues.opennms.org/browse/NMS-10372
This pull requests updates the MBeans in minion.xml to work with minions running on 22.0.4.
(NB: I have used foundation-2018 as the base, but I'm not sure if this could create problems for Meridian, if they still use the old object names.)

NMS-10372: Update MBeans to work with Horizon 22

---

core/schema/src/main/liquibase/24.0.0/changelog.xml
opennms-base-assembly/src/main/filtered/etc/create.sql
opennms-dao/src/test/java/org/opennms/netmgt/dao/ReportingSqlViewTestIT.java

Created four views to simplify SQL based reporting which also denormalise the data:
* node_categories: Nodes with categories
* node_alarms: Alarm status from nodes and allow filtering on categories
* node_outages: Outages of nodes and allow filtering on categories
* node_ip_services: Denormalise Nodes and IP services
JIRA: http://issues.opennms.org/browse/NMS-10418

NMS-10418: Create views for SQL based reporting

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdBlackboxIT.java
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/situations.drl

This PR changes the behaviour of the Alarmd Situation rules such that the Situation will be escalated in severity to one level higher than the Max Severity of the related alarms if the Max Severity is greater than NORMAL.
* JIRA: https://issues.opennms.org/browse/HZN-1417

HZN-1417: Escalate Situation Severity 

---

core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/KafkaRemoteMessageDispatcherFactory.java
core/ipc/sink/kafka-impl/src/test/java/org/opennms/core/ipc/sink/kafka/HeartbeatSinkIT.java
core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java

Allow Kafka dispatcher to retry infinitely till it delivers the message.
* JIRA: http://issues.opennms.org/browse/NMS-10395

NMS-10395: Fix Sink API drops messages when there is no connectivity with Kafka 

---

container/features/src/main/resources/features.xml
features/kafka/producer/pom.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/AlarmFeedback.java
features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/AlarmFeedbackListener.java
features/situation-feedback/elastic/src/main/java/org/opennms/features/situationfeedback/elastic/FeedbackDocument.java
features/situation-feedback/elastic/src/test/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepositoryIT.java
features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
features/situation-feedback/rest/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/situation-feedback/rest/impl/src/test/java/org/opennms/features/situationfeedback/rest/SituationFeedbackrestServiceIT.java
opennms-doc/guide-admin/src/asciidoc/text/kafka-producer/kafka-producer.adoc

This PR causes all situation feedback received via the rest API to be sent to a new alarm feedback topic in Kafka.
I'm assuming we don't need any mechanism to sync alarm feedback since we aren't persisting to the Opennms DB.
* JIRA: http://issues.opennms.org/browse/HZN-1431

HZN-1431: Update OpennmsKafkaProducer to handle alarm feedback

---

core/schema/src/main/java/org/opennms/core/schema/Migrator.java

This PR just bumps the accepted postgresql version to < 12, now that 11 is out.
* JIRA: http://issues.opennms.org/browse/NMS-10450

NMS-10450: allow postgresql 11

---

features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
features/situation-feedback/rest/impl/src/test/java/org/opennms/features/situationfeedback/rest/SituationFeedbackrestServiceIT.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java

This PR addresses the changes required to prevent OpenNMS from persisting situation changes when feedback is submitted and instead rely on OCE to update the situation via an event.
I have a few questions that I need to answer before this PR is merged which I've added as TODO comments.
* JIRA: http://issues.opennms.org/browse/HZN-1435

HZN-1435: Remove feedback submission actions from Opennms so that OCE is the authoritative source of situation changes

---

core/test-api/alarms/src/main/java/org/opennms/core/test/alarms/driver/AlarmdDriver.java
core/test-api/alarms/src/main/java/org/opennms/core/test/alarms/driver/ScenarioResults.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/AlarmAssociationAndFact.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/integration-tests/src/test/java/org/opennms/netmgt/alarmd/itests/AlarmdBlackboxIT.java
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/situations.drl
opennms-model/src/main/java/org/opennms/netmgt/model/AlarmAssociation.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java

This PR addresses the use case where an existing, un-acknowledged alarm is correlated to a Situation that is acknowledged. Previously, only the acknowledgment time of the alarm would be checked and the Situation would remain Acknowledged. Now, we additionally compare the time the Alarm is correlated to the situation and if that is later than the time at which the Situation was acknowledged, we un-acknowledge the Situation.
* JIRA: https://issues.opennms.org/browse/HZN-1426

HZN-1426 Make Older Alarms Un-Acknowledge Situations

---

checkstyle/src/main/resources/nms_checks.xml
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/FlapCount.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
opennms-tools/access-point-monitor/src/main/java/org/opennms/netmgt/model/OnmsAccessPoint.java

This PR adds a Checkstyle rule that will prevent contributors from using the SpringFramework's ToStringCreator
JIRA: http://issues.opennms.org/browse/NMS-10455

NMS-10455: Add checkstyle rule to enforce MoreObjects.toStringHelper

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java

This PR adds an interim collection to store the alarms to be removed in order to prevent a CME.
* JIRA: https://issues.opennms.org/browse/HZN-1426

HZN-1426: Use an interim collection for removed related alarms

---

features/api-layer/src/main/java/org/opennms/features/apilayer/dao/AlarmDaoImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/dao/NodeDaoImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/dao/SnmpInterfaceDaoImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/NodeBean.java
features/api-layer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SessionUtils.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/DefaultSessionUtils.java

JIRA: https://issues.opennms.org/browse/OCE-27
Here we extend the ` org.opennms.netmgt.dao.api.SessionUtils` interface to include a new `withReadOnlyTransaction` method that performs the call within read-only transaction with auto-flush disabled.
All of the existing calls in the `api-layer` module are updated to use this call, which solves the exception that was reported in the issue.

OCE-27: Fix transaction related issues when performing managed object tagging

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/AlarmDataStore.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/KafkaAlarmDataSync.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/shell/SyncAlarms.java
features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml
opennms-doc/guide-admin/src/asciidoc/text/kafka-producer/kafka-producer.adoc

JIRA: https://issues.opennms.org/browse/NMS-10474
Here we add extra synchronization to the Kafka producer to help prevent the synchronization process from processing stale data.
We also add the ability to clean the state held by the Kafka Stream API.

NMS-10474: Sync timing issues cause erroneous deletes (f18)

---

opennms-webapp/src/main/webapp/admin/index.jsp

When the link says "Wiki", it should lead there imho :)

Changed Link on the Admin page, to lead to the wiki

---

opennms-doc/guide-install/src/asciidoc/text/time-series-storage/newts/introduction.adoc

The links to Cassandra doc in the setting up section were obsolete. I've fixed them.
* JIRA: https://issues.opennms.org/browse/NMS-10481

NMS-10481: Fixed broken links in Cassandra install docs

---

features/rest/mapper/pom.xml
features/rest/mapper/src/main/java/org/opennms/web/rest/mapper/v2/AlarmMapper.java
features/rest/mapper/src/test/resources/situation.16.dto.json
features/rest/mapper/src/test/resources/situation.16.dto.xml
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/AlarmSummaryDTO.java

This PR adds the node label to the alarm summary object, used by Helm.
Additional changes will be needed in opennms.js and Helm to display this data.
* JIRA: http://issues.opennms.org/browse/HELM-121

HELM-121: add nodeLabel to alarm summary

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java

This PR changes the behaviour so that Incoming clears are checked against other clears with the if no matching problem alarm exists. Prior to this, multiple clears before the matching problem alarm would result in attempting to add the subsequent clears instead off reducing on the existing and the creates would fail at the DB level with duplicate reduction keys.
* JIRA: http://issues.opennms.org/browse/NMS-10473

NMS-10473: Reduce incoming Clears against other clears

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/DefaultServiceCollectorRegistry.java
features/poller/api/src/main/java/org/opennms/netmgt/poller/support/DefaultServiceMonitorRegistry.java
features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IconRepositoryManager.java
opennms-provision/opennms-detector-registry/src/main/java/org/opennms/netmgt/provision/detector/registry/impl/ServiceDetectorRegistryImpl.java
opennms-provision/opennms-requisition-service/src/main/java/org/opennms/netmgt/provision/service/requisition/DefaultRequisitionProviderRegistry.java

I noticed a few instances of OSGI service binding where we can be vulnerable to a CME due to either explicitly iterating a non-thread-safe collection or exposing a reference to a non-thread-safe collection that a client could then iterate.
The chance of one of these actually generating a CME is probably near zero but still possible so might as well make it correct.
* JIRA: http://issues.opennms.org/browse/HZN-1451

HZN-1451: Prevent CME during OSGI service binding

---

features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

This PR changes the Test Expectations to approximate the logic in the syslog parser in that the message will be assumed to be in the past year and not the current if the month is later in the year than the current month.
* JIRA: https://issues.opennms.org/browse/NMS-10523

NMS-10523: Set the expected year to be in line with parser behaviour

---

core/test-api/alarms/src/main/java/org/opennms/core/test/alarms/driver/Scenario.java
opennms-alarms/integration-tests/src/test/java/org/opennms/netmgt/alarmd/itests/AlarmdBlackboxIT.java
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/situations.drl

This PR fixes an issues where Situation Severity is not adjusted downward as related alarms clear if the related alarms have varrying severity
* JIRA: https://issues.opennms.org/browse/NMS-10522

NMS-10522: de-escalate situation severity

---

core/lib/src/main/java/org/opennms/core/utils/InetAddressUtils.java
opennms-icmp/opennms-icmp-best/src/main/java/org/opennms/netmgt/icmp/best/BestMatchPingerFactory.java

This PR creates a new method for specifically detecting a loopback address, and the `BestMatchPingerFactory` uses that to determine whether ping works.
* JIRA: http://issues.opennms.org/browse/NMS-9659

NMS-9659: change BestMatchPingerFactory to use loopback address for testing

---

features/measurements/api/src/main/java/org/opennms/netmgt/measurements/api/DefaultMeasurementsService.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/api/FetchResults.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/model/QueryMetadata.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/model/QueryNode.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/model/QueryResource.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/model/QueryResponse.java
features/measurements/api/src/main/java/org/opennms/netmgt/measurements/utils/Utils.java
features/measurements/api/src/test/java/org/opennms/netmgt/measurements/model/FetchResultsTest.java
features/measurements/api/src/test/java/org/opennms/netmgt/measurements/model/QueryResponseTest.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/AbstractRrdBasedFetchStrategy.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JRrd2FetchStrategy.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JrobinFetchStrategy.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/RrdtoolXportFetchStrategy.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineEnhancedTest.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
features/measurements/rest/src/test/java/org/opennms/web/rest/v1/MeasurementRestServiceIT.java
features/newts/src/main/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategy.java
features/newts/src/test/java/org/opennms/netmgt/measurements/impl/NewtsFetchStrategyTest.java
integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/measurement/CustomSpringConfiguration.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/RrdStatisticAttributeVisitorTest.java
opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/ResourceId.java
opennms-model/src/main/java/org/opennms/netmgt/model/ResourceTypeUtils.java
opennms-services/src/test/java/org/opennms/netmgt/statsd/ReportDefinitionTest.java

This PR adds the metadata necessary to implement HELM-84.  It does so by enhancing the query response from measurements requests to include a `metadata` block that contains info about nodes and resources related to the query.
* JIRA: http://issues.opennms.org/browse/HELM-84

HELM-84: add metadata to measurements queries

---

opennms-base-assembly/src/main/filtered/bin/opennms
opennms-base-assembly/src/main/filtered/bin/runjava

This is a precursor to work required to get OpenNMS running under Java 9.  It's a major refactor/cleanup of the internals of the `runjava` and `opennms` shell scripts.
* fix all shellcheck errors
* convert all variables to arrays where appropriate (things that will be passed on command lines)
* common legacy variables people include in `opennms.conf` should get auto-upgraded to arrays for internal use
* fix java 9+ support in runjava
* JIRA: http://issues.opennms.org/browse/NMS-10518

NMS-10518: some modernization/fixes for runjava and opennms

---

core/web-assets/src/main/assets/style/opennms-theme.scss
opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
opennms-webapp/src/main/webapp/login.jsp

The bootstrap 4 card introduce a strong padding in the card components in the Web UI which leads to a blown up UI. This commit reduces the padding around the card / box components to make the UI layout more compact.
Additionally I try to use the SVG logo first and fallback to the PNG. The old version uses PNGs in both cases and add some space on the new login page for the GitHub and docs icon.
A before/after screenshot is attached.

Bootstrap4: Make the Card layout more compact

---

core/schema/src/main/liquibase/foundation-2018/changelog.xml
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/processor/HibernateEventWriterIT.java
opennms-base-assembly/src/main/filtered/etc/create.sql

JIRA: https://issues.opennms.org/browse/NMS-10525
Here we convert the type of the event parameter column from `varchar(256)` to `text`.
Since this column is part of the primary key, there still is a limit on size which is up to 2712 characters.

NMS-10525: Event parameters table have strong limits for the columns

---

opennms-webapp/pom.xml
pom.xml

This PR upgrades to the latest Jetty 9.4, which is a prerequisite for moving to Java 9+
* JIRA: http://issues.opennms.org/browse/HZN-1466

HZN-1466: upgrade to Jetty 9.4.14

---

debian/control

This PR fixes the `perl` dependency to not get translated on our (ubuntu 18) machines, since it's a) not backwards-compatible, and b) not necessary.
This will make generated packages compatible with older Debian/Ubuntu installs that don't support virtual dependencies again.
* JIRA: http://issues.opennms.org/browse/NMS-10541

NMS-10541: fix debian install

---

opennms-webapp/src/main/java/org/opennms/web/event/SortStyle.java
opennms-webapp/src/test/java/org/opennms/web/event/EventFactoryIT.java

JIRA: https://issues.opennms.org/browse/NMS-10506
Include the eventtime in the ORDER BY clause to the query planner.
Add an IT that validates the list of returned events.
With these changes, the query for the events on the node page now loads in 0.5 milliseconds
instead of 6 seconds on a database with 16 million+ events.

NMS-10506: Optimize default event query on node page

---

core/schema/src/main/liquibase/24.0.0/changelog.xml
features/measurements/api/src/test/java/org/opennms/netmgt/measurements/model/FetchResultsTest.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
opennms-base-assembly/src/main/filtered/etc/create.sql
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AcknowledgmentDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockAcknowledgmentDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AcknowledgmentDaoHibernate.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/AcknowledgmentDaoIT.java

JIRA: https://issues.opennms.org/browse/HZN-1449
Add an index to acks table to speed up grouping by refId.
Also limit the findLatestAcks query by time to avoid loading/returning unnecessary entries.

HZN-1449: Optimize implementation of  findLatestAcks() for systems with lots of acks

---

pom.xml

This PR bumps the Maven-War-Plugin version to 3.2.2 (was 2.6)
* https://issues.opennms.org/browse/HZN-1231

Update maven-war-plugin to 3.2.2

---

opennms-webapp/src/main/webapp/includes/bootstrap.jsp
opennms-webapp/src/main/webapp/includes/header.jsp

Added encoding for the HTTP request locale in our JSPs.
* JIRA: http://issues.opennms.org/browse/NMS-10546

NMS-10546: Encoding for HTTP request locale

---

container/features/src/main/resources/features.xml

Standalone sentinel-core feature doesn't install because of missing dependency.
* JIRA: http://issues.opennms.org/browse/NMS-10561

NMS-10561: Fix sentinel-core feature dependency issue

---

pom.xml

This PR updates to the latest PostgreSQL JDBC driver, which has support for Java 9+ modules.
* JIRA: http://issues.opennms.org/browse/NMS-10543

NMS-10543: bump PostgreSQL JDBC driver to the latest version

---

opennms-base-assembly/src/main/filtered/etc/syslogd-configuration.xml
opennms-doc/guide-admin/src/asciidoc/text/events/sources/syslog.adoc
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

JIRA: https://issues.opennms.org/browse/NMS-10566
Use the `RadixTreeSyslogParser` by default, since it can successfully parse many more formats than the current `CustomSyslogParser`.

NMS-10566: Make the RadixTreeSyslogParser the default syslog parser.

---

opennms-alarms/bsf-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/bsf/BSFNorthbounderManager.java
opennms-alarms/drools-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/drools/DroolsNorthbounderManager.java
opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounderManager.java
opennms-alarms/jms-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/jms/JmsNorthbounderManager.java
opennms-alarms/snmptrap-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/snmptrap/SnmpTrapNorthbounderManager.java
opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogNorthbounderManager.java

While debugging functionality of the Syslog Northbounder, I've ran in a typo issue in the method names. This typo fix requires to pass CI/CD tests.
* JIRA: http://issues.opennms.org/browse/NMS-10549

NMS-10549: Fix typo in registerNorthnounders method

---

features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

This modifies the test assertion which would otherwise fail between March 01 and March 14.
* JIRA: https://issues.opennms.org/browse/NMS-10596

NMS-10596: Change test assertion to be inline with test

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java

JIRA: https://issues.opennms.org/browse/NMS-10593
Rely on the snapshot handling to update the context if acquiring the lock fails.

NMS-10593: Add a timeout when trying to acquire the locks in order to prevent deadlocks.

---

features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/TopologySettings.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/Protocol.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/OnmsTopologyAbstractRef.java
features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/OnmsTopologyEdge.java
features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/OnmsTopologyPort.java
features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/OnmsTopologyVertex.java
features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/TopologyVisitor.java
features/topologies/service/impl/src/main/java/org/opennms/netmgt/topologies/service/impl/OnmsTopologyLogger.java

The purpose of this PR is to flatten the Kafka model for topology updates such that the necessary information to derive links is contained in objects belonging to a single topic (the edges topic). This will make consumption easier in OCE.
I've also cleaned up some of the way topology objects were handled by removing usage of `instance of` checks.
* JIRA: http://issues.opennms.org/browse/HZN-1483

HZN-1483: Update topology code to make the topology that is sent via Kafka more convenient for consumption

---

opennms-ackd/src/test/java/org/opennms/netmgt/ackd/AckdIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAcknowledgment.java

supporting any ack action event
NMS-10603: fix ackd event
* JIRA: http://issues.opennms.org/browse/NMS-10603
Sending uei.opennms.org/ackd/acknowledge was triggering always ACKNOWLEDGE action,
now sending parameter ackAction it is also possible to specify other actions:
UNACKNOWLEDGE
ESCALATE
CLEAR

NMS-10603: fix ackd event

---

features/enlinkd/daemon/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/TopologyGenerator.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/TopologyPersister.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/BridgeProtocol.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/Protocol.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/bridge/BridgeBuilder.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/bridge/BridgeBuilderContext.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/util/MacAddressGenerator.java
features/enlinkd/generator/src/test/java/org/opennms/enlinkd/generator/protocol/BridgeProtocolTest.java
features/enlinkd/generator/src/test/java/org/opennms/enlinkd/generator/util/MacAddressGeneratorTest.java
features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/BridgeTopologyServiceImpl.java
features/enlinkd/shell/src/main/java/org/opennms/features/enlinkd/shell/GenerateTopologyCommand.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProviderTestIT.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/resources/META-INF/opennms/applicationContext-LinkdTopologyProviderTestIT.xml

*  JIRA: https://issues.opennms.org/browse/HZN-1475
Our continuous integration system will test and verify your changes.
Replaces https://github.com/OpenNMS/opennms/pull/2368
What is in this PR?
* Enhancement of the topology generator by the protocol "bridge". The bridge protocol is a bit different in that it contains multiple node types. The generator builds a tree consisting of hosts, bridges, segments and" Mac/IpAdresses on Segment without node". The tree is repeated depending on the amount of nodes (multiple of 10).
* The generated tree is tested in LinkdTopologyProviderTestIT.testBridge()
* I introduced a "BridgeBuilder" that allows for easier generating of such topologies. It is sufficient for my use case but could be enhanced in the future. It tries to abstract the low level …

HZN-1475: Extend topology generator and test suite to support bridge topology - release 4.0.0

---

container/features/src/main/resources/features.xml
features/api-layer/pom.xml
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/CollectorRequestBuilderImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/config/EventConfExtensionManager.java
features/api-layer/src/main/java/org/opennms/features/apilayer/dao/NodeDaoImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/events/EventSubscriptionServiceImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/GeolocationBean.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/InMemoryEventBean.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/IpInterfaceBean.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/NodeAssetRecordBean.java
features/api-layer/src/main/java/org/opennms/features/apilayer/model/NodeBean.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/RequisitionProviderImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/RequisitionProviderManager.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/RequisitionRepositoryImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/InetAddressMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/PrimaryTypeMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionAssetMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionCategoryMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionInterfaceMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMonitoredServiceMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionNodeMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/utils/InterfaceMapper.java
features/api-layer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/api-layer/src/test/java/org/opennms/features/apilayer/config/CollectionSetMapperTest.java
features/api-layer/src/test/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMapperTest.java
opennms-provision/opennms-provision-persistence/src/main/resources/META-INF/opennms/component-dao.xml
opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/ShowImport.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
pom.xml

JIRA: https://issues.opennms.org/browse/OIA-6
JIRA: https://issues.opennms.org/browse/OIA-7
Many improvements to help support controller integrations:
* Add operator instruction field support to the eventconf
* Extend the node model to include asset fields
* Expose provisiond requisition providers
* Consume events by registering event listeners
This depends on https://github.com/OpenNMS/opennms-integration-api/pull/8

OIA-6: OIA-7: Many improvements to help support controller integrations

---

integrations/opennms-snmp-hardware-inventory-provisioning-adapter/pom.xml
integrations/opennms-snmp-hardware-inventory-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpHardwareInventoryProvisioningAdapter.java
integrations/opennms-snmp-hardware-inventory-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/HwEntityAliasIT.java
opennms-base-assembly/src/main/filtered/etc/create.sql

This PR fixes an issue where entitites were not mapped to the hwEntityAliases (the reverse mapping was done but both directions are required).
This bug escaped due to a bug in the create.sql code used during integration test. That issue is also addressed here.
Additionally, a configuration with hwEnetityAliases was added to an existing test and a new test with explicit hwEnetityAlias assertions is added.
* JIRA: https://issues.opennms.org/browse/NMS-10606

NMS-10606: hwEntity not mapped to hwEntityAlias

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpObjId.java
core/snmp/api/src/test/java/org/opennms/netmgt/snmp/SnmpObjIdTest.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/PhysInterfaceTableTracker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/TrackerSuccessorIT.java

JIRA: https://issues.opennms.org/browse/NMS-10621
Fix infinite request/response loop in SNMP tracking code for *bad* agents.
Verify that the response VBs are in fact successors to the requested VBs are stop processing if they are not.
Patch was tested and verified on system where the issue was encountered.

NMS-10621: Fix infinite request/response loop in SNMP tracking

---

container/features/src/main/resources/features.xml
features/minion/repository/pom.xml
features/ticketing/otrs-integration-31/pom.xml
features/ticketing/tsrm-integration/pom.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventRestService.java
pom.xml

Here we migrate to Apache CXF to 3.2.8.
Most changes were made to the osgi-jax-rs-connector project.
Technically we now require Java 9 to run. 
However I made it work temporarily with Java 8.
Before we release 24.0.0 we should make Java 9 the requirement
We should also consider upgrading the maven-bundle-plugin to the latest version. That version also determines the required java runtime environment for each bundle.
* jira: https://issues.opennms.org/browse/HZN-1478

HZN-1478: Upgrade Apache CXF to 3.2.8

---

container/karaf/src/main/filtered-resources/etc/system.properties
core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Manager.java
core/daemon/src/main/java/org/opennms/netmgt/vmmgr/ManagerMBean.java
opennms-base-assembly/src/main/filtered/etc/service-configuration.xml

Currently OpenNMS doesn't shutdown with `kill -s TERM` or `kill -s INT` 
Adding shutdown hook in Manager will allow OpenNMS to shutdown gracefully without the need for force kill.
Disable shutdown hook in karaf for OpenNMS.
* JIRA: http://issues.opennms.org/browse/NMS-10581

NMS-10581: Handle graceful shutdown for OpenNMS

---

core/web-assets/src/main/assets/js/apps/angular-status/views/applications.html
core/web-assets/src/main/assets/js/apps/angular-status/views/business-services.html
core/web-assets/src/main/assets/js/apps/angular-status/views/nodes.html
core/web-assets/src/main/assets/js/apps/onms-classifications/index.js
core/web-assets/src/main/assets/js/apps/onms-classifications/views/config.html
core/web-assets/src/main/assets/js/apps/onms-classifications/views/group.html
core/web-assets/src/main/assets/js/apps/onms-classifications/views/modals/import-modal.html
core/web-assets/src/main/assets/js/apps/onms-elementList/minion-elementList/main.html
core/web-assets/src/main/assets/js/apps/onms-elementList/monitoringLocation-elementList/main.html
core/web-assets/src/main/assets/js/apps/onms-elementList/scanreport-elementList/main.html
core/web-assets/src/main/assets/js/lib/onms-pagination/pagination-toolbar.html
opennms-webapp/src/main/webapp/KSC/index.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/KSC/customGraphEditDetails.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/KSC/customReport.jsp
opennms-webapp/src/main/webapp/admin/discovery/edit-config.jsp
opennms-webapp/src/main/webapp/admin/discovery/edit-scan.jsp
opennms-webapp/src/main/webapp/notification/detail.jsp
opennms-webapp/src/main/webapp/roles/list.jsp
opennms-webapp/src/main/webapp/roles/view.jsp

In Bootstrap 3 table columns could be spaced out using `col-*` classes.
This is no longer working without any changes.
This PR addresses those no longer working `col-*` classes and provides a suitable replacement.
In firefox and safari everything worked nicely, however in Chrome things got messy.
So to verify this patch, please verify using Chrome Browser only.
* JIRA: https://issues.opennms.org/browse/NMS-10569

NMS-10569: Address table column spreading and spacing/orientation related issues

---

opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml

Minion nodes are special nodes added by default to establish Minion device Status.
These nodes by default have `Minion-Heartbeat` `Minion-RPC` `JMX-Minion` services.
Moving them to separate package and having different `down-time` model would yield quicker results when these nodes are down.
* JIRA: http://issues.opennms.org/browse/NMS-10435

NMS-10435: Refactor poller configuration to separate minion specific services.

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/DroolsExampleIT.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/MiscExamplesIT.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/NaggingNotificationsIT.java
opennms-base-assembly/src/main/filtered/etc/examples/alarmd/drools-rules.d/misc.drl

JIRA: https://issues.opennms.org/browse/HZN-1489
Update the Drools handling for alarms so that we can refer to node category names in the LHS.
Also add an example of such a rule.

HZN-1489: Node category support & example for Drools in alarmd

---

opennms-base-assembly/src/main/filtered/bin/find-java.sh

This PR adds support for parsing JDK version strings that have " LTS" at the end, which was causing the version regex to fail.
* JIRA: http://issues.opennms.org/browse/NMS-10627

NMS-10627: handle "LTS" tag at the end of JDK 11 version

---

opennms-assemblies/minion/pom.xml
opennms-assemblies/sentinel/pom.xml
opennms-base-assembly/src/main/filtered/bin/find-java.sh

This PR fixes the issue where starting Minion or Sentinel will complain about `_lib.sh` and fail to call `__onms_convert_to_array`.
It is harmless unless you're trying to override the default java search directories with the `$JAVA_SEARCH_DIRS` environment variable, but it is annoying.  ;)
* JIRA: http://issues.opennms.org/browse/NMS-10619

NMS-10619: make sure _lib.sh exists before using it in find-java.sh

---

opennms-doc/releasenotes/src/asciidoc/releasenotes/changelog.adoc

The `users.properties` has changed and should contain the role `ssh`. If not, user's will no longer be able to log in to the karaf shell. This should only affect users, who upgrade from a previous version and don't see the `ssh` role at the end of `users.properties`.
No jira issue.

Fix indentation and hint for users.properties

---

debian/rules
opennms-assemblies/minion/src/main/filtered/debian/rules
opennms-assemblies/sentinel/src/main/filtered/debian/rules
opennms-base-assembly/src/main/filtered/bin/runjava
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

This PR bumps the allowed/detected JDK to versions `1.8.0` through `11.9999`.
* JIRA: http://issues.opennms.org/browse/NMS-10638

NMS-10638: bump allowed JDK to 8 through 11

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/ColumnTracker.java
core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpObjId.java
core/snmp/api/src/test/java/org/opennms/netmgt/snmp/SnmpObjIdTest.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/PhysInterfaceTableTracker.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/TrackerSuccessorIT.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/TrackerSuccessorTest.java

JIRA: https://issues.opennms.org/browse/NMS-10622
Here we backport the first for NMS-10621 to `foundation`.
The only change to the original patch is that we're using JUnit asserts instead of Hamcrest in the tests.

NMS-10622: Backport SNMP successor validation

---

opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/ConfigTester.java
opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/checks/ConfigCheckValidationException.java
opennms-config-tester/src/main/resources/META-INF/opennms/applicationContext-configTester.xml
opennms-config-tester/src/test/java/org/opennms/netmgt/config/tester/ConfigTesterTest.java

This PR adds checking of imports and foreign-sources configuration to the config-tester.
* JIRA: https://issues.opennms.org/browse/NMS-10426

NMS-10426: Added checks for imports and foreign-sources configuration files

---

opennms-assemblies/minion/pom.xml
opennms-assemblies/minion/src/main/filtered/etc/minion.init
opennms-base-assembly/src/main/filtered/bin/ensure-user-ping.sh

This PR backports the changes made post-foundation-2018 to the minion scripts to enable sentinel stuff.  It includes a number of fixes for user-mode running including a better/cleaner script for ensuring ping is set up.
* JIRA: http://issues.opennms.org/browse/LTS-231

LTS-231: backport usermode ping fixes from the 24 branch

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultAdminCategoryService.java

Added sort to Available nodes list box in the Manage Surveillance Categories form. In Edit, the lists of nodes (both member and available) are unsorted. They should be sorted by node label. Change was made to sort list of Available nodes.
https://issues.opennms.org/browse/NMS-10654
Thanks for taking time to contribute!
Please read our Contribution Guidelines and format the title of the pull request in the format of:
NMS-10654: Added sort for Edit Categories
Please use the JIRA issue number and create a link in the JIRA issue back to this pull request so we have a quick reference from the issue to the pull request.
JIRA: http://issues.opennms.org/browse/NMS-10654
Our continuous integration system will test and verify your changes.

Added sort for Edit Categories NMS-10654

---

features/ifttt/src/main/java/org/opennms/features/ifttt/IfTttDaemon.java
features/ifttt/src/main/java/org/opennms/features/ifttt/config/IfTttConfig.java
features/ifttt/src/main/java/org/opennms/features/ifttt/config/TriggerPackage.java
features/ifttt/src/main/resources/xsds/ifttt-config.xsd
features/ifttt/src/test/java/org/opennms/features/ifttt/IfTttDaemonTest.java
features/ifttt/src/test/java/org/opennms/features/ifttt/config/IfTttConfigTest.java
features/ifttt/src/test/resources/etc/ifttt-config.xml
opennms-base-assembly/src/main/filtered/etc/ifttt-config.xml
opennms-doc/guide-admin/src/asciidoc/text/ifttt/ifttt-integration.adoc

Currently the IFTTT-integration only filters based on categories which will only allow alarms with associated nodes. A new reductionKeyFilter allows to filter also for reduction keys, so it is possible now to trigger IFTTT events for BS alarms.
* JIRA: https://issues.opennms.org/browse/NMS-10640

NMS-10640: Introduced reduction key filter for IFTTT trigger packages

---

debian/control
opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/debian/step-1-install-opennms.adoc
opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/rhel/step-1-install-opennms.adoc
opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/windows/installing-on-windows.adoc
opennms-doc/guide-install/src/asciidoc/text/java-environment.adoc
smoke-test/debian-shunt/debian-shunt.spec
tools/packages/minion/minion.spec
tools/packages/opennms/jdk.spec
tools/packages/opennms/opennms.spec
tools/packages/sentinel/sentinel.spec

* change all java dependencies to OpenJDK 11
* move the java dependency to the minion meta-package
* remove the java dependency from sentinel since it doesn't
have a meta-package
* JIRA: http://issues.opennms.org/browse/NMS-10639

NMS-10639: change dependencies to OpenJDK 11

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Interface.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/model/RequisitionInterface.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/model/RequisitionMetaData.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/model/RequisitionNode.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/model/RequisitionService.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/requisitions-core/index.js
core/web-assets/src/test/javascript/ng-requisitions/model/RequisitionNode.test.js

This does not add any UI elements, but makes the model driving the UI aware of the meta-data. It also includes the split-up between the "requisition" context and all other contexts.
By adding the meta-data to the model, this preserves existing meta-data while editing other things in the UI.
* JIRA: http://issues.opennms.org/browse/HZN-1511

HZN-1511: Added meta-data to models of requisitioning UI.

---

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/DNSResolutionMonitor.java

jira/NMS-10642: DNSResolutionMonitor incorrectly sets port number 
* JIRA: http://issues.opennms.org/browse/NMS-10642

Fix for jira/NMS-10642: DNSResolutionMonitor incorrectly sets port number

---

opennms-base-assembly/src/main/filtered/bin/runjava
opennms-base-assembly/src/test/shell/spec/runjava.spec.sh

This PR cleans up the error messages in `runjava`, including better messages when a JVM is missing entirely.
* JIRA: http://issues.opennms.org/browse/NMS-10663

NMS-10663: better handling of missing JVMs and normalize error messages

---

features/minion/repository/pom.xml
integrations/opennms-vmware/pom.xml

Here are some small changes to actually compile with JDK 9. 
This will only get it to compile, but not the tests run with JDK 9.

Changes to compile under Java 9

---

tools/packages/minion/minion.spec
tools/packages/opennms/opennms.spec
tools/packages/sentinel/sentinel.spec

This PR changes it so that the following config files will overwrite their existing counterparts by default, creating an `.rpmsave` file:
* `custom.properties`
* `jmx.*.cfg`
* `org.apache.*.cfg`
* `org.ops4j.*.cfg`
* `profile.cfg`
Anything that matches `org.opennms.*.cfg` will _not_ be replaced by default, instead creating an `.rpmnew` file.
*feedback wanted:* should I exclude `org.ops4j.pax.logging.cfg` since it's a reasonably common thing to override?  Or leave it in the "create `.rpmsave` by default" category?
* JIRA: http://issues.opennms.org/browse/NMS-10677

NMS-10677: custom.properties and karaf *.cfg files should be %config

---

core/health/api/src/main/java/org/opennms/core/health/api/Health.java
core/health/impl/pom.xml
core/health/impl/src/main/java/org/opennms/core/health/impl/DefaultHealthCheckService.java
core/health/impl/src/test/java/org/opennms/core/health/impl/DefaultHealthCheckServiceTest.java

* JIRA: https://issues.opennms.org/browse/NMS-10667
Tested this by providing a dummy health check blocking for 5 Minutes and not implementing Thread interrupts properly.

NMS-10667: Fix health:check getting stuck

---

pom.xml

This PR bumps c3p0 to the latest version.  This will apply to Foundation 2016 and up.
* JIRA: http://issues.opennms.org/browse/NMS-10694

NMS-10694: upgrade to latest c3p0

---

debian/control

This PR makes sure OpenJDK11 is chosen by default on Debian/Ubuntu (by listing it first).
It also defaults to the headless version.
* JIRA: http://issues.opennms.org/browse/NMS-10680

NMS-10680: put openjdk 11 first so it is chosen by default

---

container/shared/src/main/resources/etc/container.init
debian/opennms-server.opennms.default
debian/opennms-server.opennms.init
debian/opennms-server.postinst
opennms-base-assembly/src/main/filtered/bin/find-java.sh
opennms-base-assembly/src/main/filtered/bin/opennms
opennms-base-assembly/src/main/filtered/bin/runjava
opennms-base-assembly/src/test/shell/spec/opennms.spec.sh

This PR fixes exit-code handling in a few of the functions and adds test coverage for `.rpmnew`/`.rpmsave`/`.dpkg-dist` checking.
* JIRA: http://issues.opennms.org/browse/NMS-10676

NMS-10676: fix shell exit codes for stop/start

---

core/schema/src/main/liquibase/24.1.0/changelog.xml
core/schema/src/main/liquibase/changelog.xml
opennms-base-assembly/src/main/filtered/etc/create.sql

This replaces PR https://github.com/OpenNMS/opennms/pull/2484 in order to cleanly base off 24.1.0 and also use the correct bug ID from the start...
- Updated 'create.sql' to set delete cascade on fk_ipnettomedia_nodeid constraint
- Created new 24.1.0 changelog.xml for Liquibase and added a changeset to recreate the  fk_ipnettomedia_nodeid constraint with onDelete=CASCADE
Edit by mvrueden: 
- JIRA: https://issues.openns.org/browse/NMS-10674

NMS-10674: Added missing 'ON DELETE CASCADE' statement to ipNetToMedia table

---

container/features/src/main/resources/features.xml
core/ipc/common/kafka/pom.xml
core/ipc/sink/kafka/server/src/main/java/org/opennms/core/ipc/sink/kafka/server/offset/KafkaOffsetProvider.java
core/test-api/kafka/pom.xml
features/kafka/producer/pom.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/KafkaAlarmDataSync.java
pom.xml
smoke-test/pom.xml

This PR will upgrade kafka components to 2.2.0 from 1.0.1
The major changes were to KafkaOffsetProvider which used deprecated Scala functions, these were changed to the newer API. Impact should be minimal as this is only used by the test KafkaOffsetIT
Main code changes were minor to KafkaAlarmDataSync which moved the import path of Consumed
* JIRA: http://issues.opennms.org/browse/NMS-10624

NMS-10624: Upgrade kafka components to 2.2.0

---

features/flows/elastic/pom.xml
features/jest/jest-complete-osgi/pom.xml
features/opennms-es-rest/pom.xml
features/vaadin-components/widgetset/pom.xml
opennms-base-assembly/pom.xml

This PR fixes most of these warning when building OpenNMS.
The only warning not fixed in this PR is the ${jetstVersion} warning from below
```
[WARNING] Some problems were encountered while building the effective model for org.opennms.features.flows:org.opennms.features.flows.elastic:bundle:25.0.0-SNAPSHOT
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.opennms:opennms-dao-mock:jar -> duplicate declaration of version (?) @ org.opennms.features.flows:org.opennms.features.flows.elastic:[unknown-version], /Users/roskens/Documents/OpenNMS/devjam2018.git/features/flows/elastic/pom.xml, line 264, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.opennms:opennms-dao-mock:jar -> duplicate declaration …
```

NMS-10690: Fix maven pom warnings

---

opennms-base-assembly/pom.xml

HZN-1520 removed a dependency on net.simon04.jelementtree:jelementtree but it wasn't removed from opennms-base-assembly/pom.xml.

HZN-1520: Remove unused dependency net.simon04.jelementtree:jelementtree

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/JettyUserIdentityFilter.java
pom.xml

A Jetty version bump.  Also, we were not changing Karaf to match our embedded Jetty.  I've changed it to use `${jettyVersion}` instead.
* JIRA: http://issues.opennms.org/browse/NMS-10701

NMS-10701: make sure all Jetty code is using 9.4.18

---

smoke-test/src/test/java/org/opennms/smoketest/EditInRequisitionIT.java

A small PR to attempt to fix the EditInRequisition test to not flap.
* JIRA: http://issues.opennms.org/browse/NMS-10698

NMS-10698: attempt to be more forgiving in timing of requisition tests

---

smoke-test/src/test/java/org/opennms/smoketest/MetadataPageIT.java

This PR fixes the MetadataPageIT which fails on some branches when the calculated attributes are attempted to be de-serialized as there is no setter for these properties.

MetadataPageIT: fix test

---

container/features/src/main/resources/features.xml
dependencies/rancid/pom.xml
pom.xml

dependencies/rancid/pom.xml has a dependency on org.opennms/rancid-api/1.0.4 while container/features/src/main/resources/features-experimental.xml has a dependency on org.opennms/rancid-api/1.0.3.
This PR introduces a new property, rancidApiVersion, and updates the two xml files to use that property.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10716

NMS-10716: Introduce rancidApiVersion property

---

opennms-container/version-tags.sh

Remove CircleCI build number from published DockerHub tags.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12098

NMS-12098: Remove CircleCI build number from published DockerHub tags

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/configuration.adoc

The wording describing serviceUnresponsive was worded oddly, and this should make it a little more clear.
Yes, I know I didn’t make a JIRA issue for this change.

Clean up serviceUnresponsive wording

---

core/test-api/collection/src/main/java/org/opennms/core/collection/test/JUnitCollectorExecutionListener.java

This PR changes the behavior to simply print a stack trace on Windows if there is an error cleaning up after the test.
* https://issues.opennms.org/browse/NMS-12102

Windows is failing tests due to spurious cleanup errors

---

container/features/src/main/resources/karaf/spring-legacy.xml
container/features/src/main/resources/karaf/spring.xml
container/features/src/main/resources/karaf/standard.xml
container/karaf/src/main/filtered-resources/etc/config.properties
container/karaf/src/main/filtered-resources/etc/org.apache.karaf.command.acl.bundle.cfg
container/karaf/src/main/filtered-resources/etc/org.apache.karaf.command.acl.config.cfg
container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.logging.cfg
container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.url.mvn.cfg
container/karaf/src/main/filtered-resources/etc/startup.properties
container/karaf/src/main/filtered-resources/etc/system.properties
container/shared/src/main/filtered-resources/etc/startup.properties
core/test-api/karaf/pom.xml
core/test-api/karaf/src/main/java/org/opennms/core/test/karaf/KarafTestCase.java
opennms-full-assembly/pom.xml
pom.xml
smoke-test/pom.xml

This PR upgrades Karaf from 4.2.3 -> 4.2.6. As of 4.2.5 the behaviour of the karaf maven plugin is to omit the timestamps by default. This fixes the issue we were having on sentinel where OIA artifacts would not get resolved when using snapshots (since they were suffixed by timestamps).
I followed the instructions in container/karaf/README.markdown. Let me know if there is additional work that is required for the upgrade.
Tested locally using runInPlace.sh that the minion and sentinel containers come up. Also tested that the Opennms container comes up.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-11766

NMS-11766: Sentinel container does not contain integration API in maven repository (Karaf Upgrade)

---

.gitignore
opennms-container/horizon/Dockerfile
opennms-container/horizon/tarball/.gitkeep
smoke-test/README.md

Add capability to install OpenNMS Horizon OCI based on a tarball artifact. The logic to install from different sources is implemented as the following:
1. Try to install from a tar.gz file in horizon/tarball
2. Try to install from local RPM files in horizon/rpms
3. Try to install from public remote mirrors
For the reason a tarball assembly doesn't have etc-pristine, we create it from a plain install so we can use the same principle to initialize configurations. Additionally the path to deal with persisted files is normalized to the /opt/opennms directory instead of using the linked ones.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12133

NMS-12133: Allow to install Horizon from a tarball

---

debian/opennms-server.opennms.init

Changed the Debian init script to find Java 8 and Java 11 installations. On systems which have just Java 11 installed, it is otherwise not possible to start OpenNMS.
JIRA: https://issues.opennms.org/browse/NMS-12161

NMS-12161: Find Java 8 and 11

---

core/ipc/sink/api/src/main/java/org/opennms/core/ipc/sink/api/SinkModule.java
core/ipc/sink/camel/client/src/main/java/org/opennms/core/ipc/sink/camel/client/CamelRemoteMessageDispatcherFactory.java
core/ipc/sink/camel/common/src/main/java/org/opennms/core/ipc/sink/camel/CamelSinkConstants.java
core/ipc/sink/kafka/client/src/main/java/org/opennms/core/ipc/sink/kafka/client/KafkaRemoteMessageDispatcherFactory.java
core/ipc/sink/kafka/itests/src/test/java/org/opennms/core/ipc/sink/kafka/itests/KafkaLargeBufferSinkIT.java
features/telemetry/common/src/main/java/org/opennms/netmgt/telemetry/common/ipc/TelemetrySinkModule.java

This allows each sink module to derive a routing key for every message. Messages with the same routing key are then routed to the same consumer.

NMS-10721: Route flow messages depending on exporter

---

core/web-assets/src/main/assets/js/apps/onms-elementList/templates/angular-onms-elementList-editListInPlace.html

Here we fix minion label handling.
This probably never worked.
So it might be worth backporting to `foundation-2018` or even `foundation-2017`.
JIRA: https://issues.opennms.org/browse/NMS-12164

NMS-12164: Fix minion label handling

---

core/web-assets/package.json

This PR changes the eslint command to use (escaped) doub le-quotes instead of single quotes.
The single quotes are not handled properly in the windows shell and so ./compile.pl currently fails
With the change, I was successfully able to run 'yarn lint' in both windows shell and in WSL.

Use double quotes for ESLINT command in order to build cross platform

---

opennms-container/horizon/Dockerfile
opennms-container/horizon/assets/entrypoint.sh
opennms-container/horizon/assets/trapd-configuration.xml.tpl

Refactored the container image to run as non-root by default and runs with an arbitrary user id to be compatible to run in Open Shift. The following things are changed on a high level:
* cap_net_raw is set for the Java binary
* support [Arbitrary User IDs](https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html)
* Unify the directory structure so we don't have different situations when we install from RPM vs. tarball installation
JIRA: https://issues.opennms.org/browse/NMS-11720
As requested, I've uploaded an image to DockerHub with opennms/horizon:nms-11720.

NMS-11720: Run as non-root

---

.circleci/config.yml
opennms-container/version-tags.sh

Add possibility to use an arbitrary branch name as OCI tag so it can be pushed to a Docker registry like DockerHub. The behavior can be controlled using the branch filter directive for the publish OCI jobs in CircleCI's config.yml. The behavior for tagging is implemented as the following for the branches:
* master: Uses the version number as a tag from the root pom.xml
* develop: tagged as "bleeding" and overwrites previous ones
* otherwise: Use the branch name as tag and replace `/` with `-` in the name
There is a separate commit which renames our build jobs to be easier identified in the CircleCI build workflow view. The jobs are renamed like `package-build-<name>` to `<name>-package-build` and `publish-oci-<name>` to `<name>-publish-oci`. …

NMS-12187: Allow arbitrary branches to be pushed to DockerHub

---

features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/HeaderUtil.java
features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
features/vaadin-dashlets/dashlet-map/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/MapDashlet.java
features/vaadin-dashlets/dashlet-topology/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/TopologyDashlet.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapsApplication.java
smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12166
The code for hiding the header is still in place and works for normal pages. Our Vaadin UIs include the html/script code in a CustomLayout but Vaadin strips script-tags so the JavaScript-stuff is never executed. I added an AttachListener to execute the JavaScript-Code. The Topology UI uses the @PreserveOnRefresh annotation which means that a page reload will not fire detach/attach listeners. So, I added a custom refresh-method that invokes the JS-code manually on page reload.

NMS-12166: Hide Vaadin Apps headers inside iFrames

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSchedulerService.java
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12189
Here we fix an issue that the cron expression is only shown if the report was scheduled with the new UI. As reports may already have been scheduled, the cron expression should also be visible for those.

NMS-12189: Use cron expression from cron trigger instead of persisting it

---

debian/opennms-server.opennms.init
tools/infrastructure/java_lint.sh

NMS-12183: check for `javac` rather than tools.jar to detect JDK

---

opennms-provision/opennms-requisition-dns/pom.xml

This fixes https://issues.opennms.org/browse/NMS-11748:
When in Karaf, issuing provision:show-import with type=dns
and a location specified, the command fails on missing libs.

NMS-11748: Add JAXB imports to requisition-dns pom.xml

---

.circleci/scripts/sonar.sh

Change invalid call from `generate_names` to `generate_report_names`
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of …

NMS-12196: Fix typo in sonar.sh

---

container/features/src/main/resources/features.xml
dependencies/drools/pom.xml
features/collection/persistence-tcp/pom.xml
features/collection/persistence-tcp/src/test/java/org/opennms/netmgt/collection/persistence/tcp/TcpOutputStrategyTest.java
features/kafka/producer/pom.xml
features/telemetry/protocols/jti/adapter/pom.xml
features/telemetry/protocols/nxos/adapter/pom.xml
opennms-alarms/drools-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/drools/DroolsNorthbounderIT.java
opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/NodeParentRules.drl
opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/nodeParentRules/NodeParentRules.drl
pom.xml

JIRA: https://issues.opennms.org/browse/NMS-12191
Here we upgrade Drools to the latest stable release.
Protobuf 2 in the root classpath has been upgrade to Protobuf 3 - existing code that we generated for Protobuf 2 continues to work though.

NMS-12191: Upgrade Drools from 7.7.0.Final to 7.24.0.Final

---

container/features/src/main/resources/features.xml

The sentinel-flows feature depends on `opennms-thresholding-api` which was recently updated and now depends on `opennms-kvstore-api`. However the feature definition was not updated to include that dependency. This PR updates that feature definition to include the new dependency. The `sentinel-flows` feature now installs correctly.
Test manually in sentinel container.
- No Jira

Fix for sentinel-flows feature not installing

---

opennms-assemblies/webapp-full/pom.xml

This PR updates the dependency version of opennms-warmerge-plugin to fix some build issues that were present with 0.4.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12194

NMS-12194: Update warmerge plugin dependency to 0.5

---

container/shared/src/main/resources/etc/container.init

Set max version in find-java script from OpenJDK from 1.8 to 11.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12206

NMS-12206: Set max version for OpenJDK to 11

---

opennms-assemblies/minion/src/main/filtered/debian/opennms-minion-container.postinst
opennms-assemblies/sentinel/src/main/filtered/debian/opennms-sentinel.postinst
tools/packages/minion/minion.spec
tools/packages/sentinel/sentinel.spec

With OpenSSH 7.8+ the default format for RSA key pairs has been changed and writes by default the OpenSSH format. This file can't be processed correctly from our current Karaf version. The key needs to be generated with the old PEM format which is here enforced by adding the "-m PEM" as arguments.
* JIRA: http://issues.opennms.org/browse/NMS-12211

NMS-12211: Set format to PEM for SSH host key generation for Karaf

---

integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/ExceptionToPngRenderer.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java
integrations/opennms-jasper-extensions/src/test/java/org/opennms/netmgt/jasper/ExceptionRendererTest.java

JIRA: https://issues.opennms.org/browse/NMS-12170
Render exceptions that may occur while rendering the panels as images instead of aborting the report altogether.
Example PDF is available here:
[error_as_image.pdf](https://github.com/OpenNMS/opennms/files/3477315/error_as_image.pdf)

NMS-12170: Render exceptions in images instead of aborting.

---

opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngineBuilderIT.java
opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/PersistStateIT.java
opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistStateStreaming/PersistStateStreaming.drl
opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistStateStreaming/drools-engine.xml

JIRA: https://issues.opennms.org/browse/NMS-12201
Add a test case that reproduces a problem where a Drools session blocks
indefinitely when being shut down and add a workaround to the engine.
Problem has been reported upstream in DROOLS-4413.

NMS-12201: Don't block me Drools!

---

core/web-assets/src/main/assets/js/apps/onms-endpoints/grafana/grafana-modal.html
core/web-assets/src/main/assets/js/apps/onms-endpoints/index.js
features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientFactoryImpl.java
features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java
features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaServerConfiguration.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaQueryExecutor.java

Here we fix some UI related issues which were introduced with the upgrade to bootstrap 4.3.1 as well as some other minor issues (i) icons instead of (?) as well as typo fixes and we apply a default connect and read timeout of 30 seconds instead of 120.

Database Reports/Grafana Endpoints: Fix small UI related issues, address some TODOs and get it closer for merging back

---

features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaBuilderHelper.java
features/vaadin-dashboard/src/test/java/org/opennms/features/vaadin/dashboard/config/ui/editors/CriteriaBuilderTest.java
opennms-doc/guide-admin/src/asciidoc/text/webui/opsboard/criteria-builder.adoc

* JIRA: https://issues.opennms.org/browse/NMS-12223
You can now use "+seconds" and "-seconds" for relative values and absolute value can be given in ISO format, e.g. "2019-06-20T20:45:15.123-05:00".

NMS-12223: Fixed date handling in Ops board criteria builder component

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/introduction.adoc
opennms-services/pom.xml
opennms-services/src/main/java/org/opennms/netmgt/poller/DefaultPollContext.java
opennms-services/src/main/java/org/opennms/netmgt/poller/QueryManager.java
opennms-services/src/main/java/org/opennms/netmgt/poller/QueryManagerDaoImpl.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollContext.java
opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableServiceConfig.java
opennms-services/src/test/java/org/opennms/netmgt/mock/MockQueryManager.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/mock/MockPollContext.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

JIRA: https://issues.opennms.org/browse/NMS-12225
Here we update the poller to store the lastgood & lastfail timestamps in the ifservices table and update the UI to display these.
Good with no failures:
After an outage:

NMS-12225: Set the lastgood & lastfail columns on ifservices after a poll

---

container/features/src/main/resources/features.xml
features/dnsresolver/netty/pom.xml
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/CaffeineCache.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/CaffeineDnsCache.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/ExtendedDnsCache.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/ExtendedDnsCacheEntry.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/NettyDnsHealthCheck.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/NettyDnsResolver.java
features/dnsresolver/netty/src/main/java/org/opennms/netmgt/dnsresolver/netty/NettyResolverContext.java
features/dnsresolver/netty/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/dnsresolver/netty/src/test/java/org/opennms/netmgt/dnsresolver/netty/CaffeineDnsCacheTest.java
features/dnsresolver/netty/src/test/java/org/opennms/netmgt/dnsresolver/netty/NettyDnsResolverTest.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/RecordEnricher.java
opennms-doc/guide-admin/src/asciidoc/text/dnsresolver/introduction.adoc
pom.xml

JIRA: https://issues.opennms.org/browse/NMS-12157
Here we update the NettyDnsResolver to use a new custom cache based on Caffeine. This allows us to limit the cache size and expose resolution statistics.
While adding tests for this I found that the previous implementation didn't actually cache any of the reverse lookups that were being performed - only the standard A and AAAA lookups were cached 🤦‍♂

NMS-12157: Update the Netty resolver to use a cache based on Caffeine

---

core/web-assets/src/main/assets/js/apps/onms-reports/ReportDetails.js
core/web-assets/src/main/assets/js/apps/onms-reports/report-details.html
features/endpoints/grafana/api/src/main/java/org/opennms/netmgt/endpoints/grafana/api/GrafanaClient.java
features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java
features/endpoints/grafana/client/src/test/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImplIT.java
features/reporting/api/src/main/java/org/opennms/api/reporting/ReportParameterBuilder.java
features/reporting/api/src/main/java/org/opennms/api/reporting/parameter/ReportParameters.java
features/reporting/api/src/main/java/org/opennms/api/reporting/parameter/ReportTimezoneParm.java
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportDetails.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportDetailsBuilder.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaQuery.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/TimezoneHelper.java
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-1ppp.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-2ppp.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-4ppp.jrxml
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSchedulerService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/UserRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/WhoamiRestService.java

Here we add the capability to add timezone parameters to reports.
The UI shows all supported java timezones. However I am not sure if that is the best implementation as there are a lot of them.
* Jira: https://issues.opennms.org/browse/NMS-12148
Should be merged after PR https://github.com/OpenNMS/opennms/pull/2649

NMS-12148: Allow defining timezones

---

core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcClientFactory.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/MockEchoClient.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaConsumerAsyncIT.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaIT.java

Currently  all the responses are handled by one thread which may slow down and cause lag.
Use newCachedThreadPool to handle each response (unmarshalling and module specific response processing).
Also re-enable consumer thread if it gets closed by any error.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12232
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12236

NMS-12232: Make RPC response handling asynchronous.

---

opennms-webapp/src/main/webapp/js/onms-requisitions/views/node-basic.html

typeahead select won't make form dirty. Trigger this explicitly with typeahead-on-select
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12217

NMS-12217: Fix node location change in Requisition UI

---

features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/ScriptedCollectionSetBuilder.java
features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/JtiGpbAdapter.java
features/telemetry/protocols/nxos/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/nxos/adapter/NxosGpbAdapter.java
features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowTelemetryAdapter.java

This PR updates telemetry processing to use the collected time included in a telemetry packet as the timestamp rather than `System.currentTimeMillis()`. Previously we could end up with a time that was incorrect because the message could have been sitting in Kafka for a long time for instance.
Now we only use the current time if we couldn't find a timestamp in the packet itself.
I couldn't find a convenient spot to add test coverage for this, however I did verify that it is getting set correctly by tracing an IT.
* [] If this is new code, …

NMS-12242: Invalid timestamps used for CollectionSets generated by telemetryd

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/model/GraphResults.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultGraphResultsService.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp

This is an extension of #2669 where applying custom time ranges may still throw `Request Header Fields Too Large` error.  This will handle those cases.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-8712

NMS-8712: Handle time ranges in graphs page when rendering graphAll

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/CollectionSet.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/dto/CollectionSetDTO.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/CollectionSetBuilder.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/CollectionResourceWrapper.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorState.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingServiceImpl.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSessionImpl.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSetImpl.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingVisitorImpl.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/CollectionResourceWrapperIT.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/MockCollectionResourceWrapper.java
features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java
features/distributed/kv-store/blob/no-op/src/main/java/org/opennms/features/distributed/kvstore/blob/noop/NoOpBlobStore.java
features/telemetry/itests/src/test/java/org/opennms/netmgt/telemetry/itests/ThresholdingIT.java
opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/junos-telemetry-interface.groovy
opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/sflow-host.groovy

This PR updates thresholding to take into account the sequence number of collections sets derived from JTI messages. Using the sequence number in a distributed thresholding environment, we can determine if we were the instance that thresholded the previous sequence and in this case we can avoid retrieving the thresholding state from the KV store since we know we are up to date.
With this in place, the number of reads from the KV store that will be required by thresholding in a distributed deployment should be greatly reduced, resulting in better performance. In a steady state scenario we would expect that the same instance will receive the metrics for a given agent/resource and this should represent that majority of incoming messages. In an outage/Kafka partition rebalancing scenario the …

NMS-12243: Leverage telemetry sequencing for better thresholding performance

---

integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePool.java

The ServiceInstancePool housekeeping timer wasn't declared as daemon thread.
* JIRA: https://issues.opennms.org/browse/NMS-12265

NMS-12265: Fixed ServiceInstancePool housekeeping timer

---

opennms-base-assembly/src/main/filtered/bin/opennms

Spawn the java process directly instead of using the runCmd wrapper function as a background subshell process to fetch the correct PID for the PID file.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12226

NMS-12226: Spawn the java process directly to fetch the correct PID

---

core/health/api/src/main/java/org/opennms/core/health/api/Status.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/RequireConfigurationElasticHealthCheck.java

Here we make the `health:check` pass the `ElasticHealthCheck` (for feature `opennms-flows`) if it is not configured. I went with `Success` over `Unknown` as anything besides `Success` is considered not awesome.
JIRA: https://issues.opennms.org/browse/NMS-10498

NMS-10498: Don't make health:check fail if elastic is not configured (opennms-flows only)

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DefaultDirectionIT.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java

Here I remove all `TransactionOperations` references and use `SessionUtils` instead (module `features/flows/elastic`). 
This removes the issue when sometimes the dependency to `TransactionOperations` is no longer resolvable after e.g. a bundle refresh (most likely caused by a manual `bundle:watch *`)

Cleanup: Use SessionUtils instead of TransactionOperations in module features/flows/elastic

---

opennms-base-assembly/src/main/filtered/etc/notifd-configuration.xml

Tested the notification for nodeDown/nodeLostService and interfaceDown successfully.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10662

NMS-10662: Map the notifd autoacknowledgement to alarms

---

features/telemetry/protocols/common/src/main/java/org/opennms/netmgt/telemetry/protocols/common/utils/BsonUtils.java
features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowConverter.java
features/telemetry/protocols/sflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowConverterTest.java
features/telemetry/protocols/sflow/adapter/src/test/resources/sflow.json

SFlow is capable of sending samples about other network layers beside
IP. To make a usefull flow out of the sample, the IP data is required.
Flows not containing IP related information are silently ignored now.
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12185

NMS-12185: Ignore SFlow messages without IP data

---

opennms-container/horizon/Dockerfile
opennms-container/horizon/build_container_image.sh
opennms-container/minion/Dockerfile
opennms-container/minion/build_container_image.sh
opennms-container/sentinel/Dockerfile
opennms-container/sentinel/build_container_image.sh

Added the network capabilities to the Java process similar as in the Horizon image to allow sending ICMP packets with Java. Additionally, the OpenJDK version is bumped to the latest available version 11.0.4.11 in the CentOS 7 repositories. We have also removed `gettext` and added `jq` which was a request to make things easier from @agalue. The 3 changes are separate commits so they can be reverted individually if necessary.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12283
* Bamboo (Continuous Integration): …

NMS-12283: Be able to execute ICMP requests through Java when running as non-root
