OpenNMS/opennms

container/features/src/main/resources/features.xml
features/graph/persistence/hibernate/src/main/java/org/opennms/netmgt/graph/persistence/hibernate/DefaultGraphRepository.java
features/graph/persistence/hibernate/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/graph/persistence/hibernate/src/test/resources/META-INF/opennms/component-dao.xml

* JIRA: https://issues.opennms.org/browse/HZN-1472

HZN-1472: Expose GraphRepository to OSGi registry

---

opennms-config-model/src/main/castor/notifications.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/NotificationManager.java
opennms-dao/src/test/java/org/opennms/netmgt/config/NotificationManagerIT.java
opennms-doc/guide-admin/src/asciidoc/text/notifications/getting-started.adoc
opennms-services/src/test/java/org/opennms/netmgt/notifd/BroadcastEventProcessorIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotificationsITCase.java
opennms-services/src/test/resources/org/opennms/netmgt/notifd/notifications.xml
opennms-webapp/src/main/java/org/opennms/web/admin/notification/noticeWizard/NotificationWizardServlet.java

* JIRA: http://issues.opennms.org/browse/NMS-10486

NMS-10486: Configure rule to discard notifications when there is no node associated

---

features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/TopologyGenerator.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/TopologyPersister.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/CdpProtocol.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/IsIsProtocol.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/LldpProtocol.java
features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/OspfProtocol.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/TopologyEntityCache.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/TopologyEntityCacheImpl.java
features/enlinkd/shell/src/main/java/org/opennms/features/enlinkd/shell/DeleteTopologyCommand.java
features/enlinkd/shell/src/main/java/org/opennms/features/enlinkd/shell/GenerateTopologyCommand.java
features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/topo/AbstractTopologyProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProviderTestIT.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/resources/META-INF/opennms/applicationContext-LinkdTopologyProviderTestIT.xml

* JIRA: https://issues.opennms.org/browse/HZN-1469

HZN-1469: Leverage new topology generator to test the LinkdTopologyProvider

---

opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

Changed default X-Frame-Options header to deny.
* JIRA: http://issues.opennms.org/browse/NMS-10547

NMS-10547: Default X-Frame-Options

---

features/collection/core/src/main/java/org/opennms/netmgt/collection/core/CollectionSpecification.java

Add specific exception message to  event "reason" and in turn "description"
* JIRA: http://issues.opennms.org/browse/NMS-9633

NMS-9633: Add more details to CollectionException

---

opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectionSpecification.java

* JIRA: http://issues.opennms.org/browse/NMS-9633

NMS-9633: Add more details to CollectionException.

---

features/newts/src/main/java/org/opennms/netmgt/newts/support/CassandraPoolConfiguration.java
features/newts/src/main/resources/META-INF/opennms/applicationContext-newts.xml
opennms-doc/guide-admin/src/asciidoc/text/operation/newts/configuration.adoc
pom.xml

JIRA: https://issues.opennms.org/browse/NEWTS-108

NEWTS-108: Expose connection pooling options

---

features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/CollectionSetMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/CollectorRequestBuilderImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/ServiceCollectorClientImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/ServiceCollectorImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/ServiceCollectorManager.java
features/api-layer/src/main/java/org/opennms/features/apilayer/pollers/ServicePollerManager.java
features/api-layer/src/main/java/org/opennms/features/apilayer/utils/InterfaceMapper.java
features/api-layer/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/api-layer/src/test/java/org/opennms/features/apilayer/config/CollectionSetMapperTest.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/DefaultServiceCollectorRegistry.java
features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorRequestBuilderImpl.java
features/collection/client-rpc/src/main/resources/META-INF/opennms/applicationContext-rpc-collector.xml
features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
pom.xml

* JIRA: http://issues.opennms.org/browse/OIA-4

OIA-4: Map collectors from integration api

---

core/web-assets/src/main/assets/js/apps/notifications/index.js

* JIRA: http://issues.opennms.org/browse/NMS-10567

NMS-10567: Avoid leaking websockets if server is down

---

features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java

* JIRA: http://issues.opennms.org/browse/HZN-1480

HZN-1480: Do not print false log message

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-development/src/asciidoc/index.adoc
opennms-doc/guide-install/src/asciidoc/index.adoc
opennms-doc/releasenotes/src/asciidoc/common/copyright.adoc
opennms-doc/releasenotes/src/asciidoc/common/preface.adoc
opennms-doc/releasenotes/src/asciidoc/index.adoc
opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
opennms-webapp/src/main/webapp/includes/footer.jsp
opennms-webapp/src/main/webapp/support/about.jsp

* JIRA: http://issues.opennms.org/browse/NMS-10591

NMS-10591: Update webapp copyright dates to 2019

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp

* JIRA: http://issues.opennms.org/browse/HZN-1481

HZN-1481: Add Managed object type/instance to alarm detail.

---

opennms-webapp/src/main/webapp/admin/bsm/adminpage.jsp
opennms-webapp/src/main/webapp/admin/jmxConfigGenerator.jsp
opennms-webapp/src/main/webapp/admin/manageEvents.jsp
opennms-webapp/src/main/webapp/admin/manageSnmpCollections.jsp
opennms-webapp/src/main/webapp/admin/mibCompiler.jsp
opennms-webapp/src/main/webapp/admin/surveillanceViewsConfig.jsp
opennms-webapp/src/main/webapp/admin/wallboardConfig.jsp
opennms-webapp/src/main/webapp/includes/bootstrap.jsp
opennms-webapp/src/main/webapp/surveillance-box.jsp
opennms-webapp/src/main/webapp/surveillance-view.jsp

* https://issues.opennms.org/browse/NMS-10601

NMS-10601: Fix @PreserveOnRefresh for Vaadin UIs

---

opennms-ackd/src/test/java/org/opennms/netmgt/ackd/AckdIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAcknowledgment.java

Revert "NMS-10603: fix ackd event"

---

features/measurements/api/src/main/java/org/opennms/netmgt/measurements/api/FetchResults.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/filters/impl/PercentilePerfTest.java

JIRA: https://issues.opennms.org/browse/NMS-10589
Handle the conversion column by column instead of row by row.

NMS-10589: Handle fetch result conversion more efficiently when filters are in use.

---

features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java

Port syslog test changes to foundation-2018
* JIRA: http://issues.opennms.org/browse/NMS-10596

NMS-10596: Change test assertion to be inline with test

---

opennms-assemblies/minion/src/main/filtered/debian/opennms-minion-container.postinst
tools/packages/minion/minion.spec

* JIRA: http://issues.opennms.org/browse/HZN-1485

HZN-1485: Fix cleaning out  .m2 directory

---

core/xml/src/main/java/org/opennms/core/xml/DoubleAdapter.java
core/xml/src/main/java/org/opennms/core/xml/NumberAdapter.java
core/xml/src/test/java/org/opennms/core/xml/NumberAdapterTest.java
features/collection/api/src/test/java/org/opennms/features/collection/dto/CollectionResourceDTOTest.java
features/collection/api/src/test/java/org/opennms/features/collection/dto/CollectionSetDTOTest.java
opennms-config-model/src/test/java/org/opennms/netmgt/config/discovery/DiscoveryConfigurationTest.java

* JIRA: http://issues.opennms.org/browse/NMS-10516

NMS-10516: Fix NumberAdapter which limits values to MAX_INT

---

opennms-ackd/src/test/java/org/opennms/netmgt/ackd/AckdIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAcknowledgment.java

NMS-10603:  Support AckAction Escalate and Clear
* JIRA: http://issues.opennms.org/browse/NMS-10603
The only supported action for ack event is Acknowledge.
Let ack event support also Escalate, Clear and Unacknowledge
Added tests

Fix ack event: supporting ackAction

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-webapp/src/main/webapp/element/node.jsp
smoke-test/src/test/java/org/opennms/smoketest/NodeDetailPageIT.java

* JIRA: https://issues.opennms.org/browse/HZN-1487

HZN-1487: Added property to configure maximum number of interfaces

---

opennms-base-assembly/src/main/filtered/bin/opennms
opennms-base-assembly/src/main/filtered/etc/provisiond-configuration.xml
opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java

JIRA: https://issues.opennms.org/browse/HZN-1455

HZN-1455: Update startup script to support bootstrapping with Java 9

---

core/schema/src/main/liquibase/24.0.0/changelog.xml

* JIRA: https://issues.opennms.org/browse/HZN-1499

HZN-1499: Added "ON DELETE CASCADE" to metadata liquibase changelog

---

opennms-webapp/src/main/webapp/KSC/customGraphChooseResource.jsp

* JIRA: https://issues.opennms.org/browse/NMS-10623
Please verify with Safari or Firefox AND Chrome.

NMS-10623: Fix class on selection for KSC reports

---

container/features/src/main/resources/features.xml
features/minion/repository/pom.xml
features/ticketing/otrs-integration-31/pom.xml
features/ticketing/tsrm-integration/pom.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventRestService.java
pom.xml

JIRA: https://issues.opennms.org/browse/HZN-1478
Original [PR](https://github.com/OpenNMS/opennms/pull/2399) was reverted in the `release-24.0.0` branch.
It looks like this affected the stability of the system tests - we'll need to to investigate this further before merging again.

HZN-1478: Upgrade CXF to 3.2.x or greater

---

opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java
opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java
opennms-webapp/src/main/java/org/opennms/web/alarm/filter/AlarmTextFilter.java
opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java
opennms-webapp/src/main/java/org/opennms/web/event/EventUtil.java
opennms-webapp/src/main/java/org/opennms/web/event/filter/EventTextFilter.java
opennms-webapp/src/main/webapp/includes/alarm-advquerypanel.jsp
opennms-webapp/src/main/webapp/includes/alarm-querypanel.jsp
opennms-webapp/src/main/webapp/includes/event-advquerypanel.jsp
opennms-webapp/src/main/webapp/includes/event-querypanel.jsp
smoke-test/src/test/java/org/opennms/smoketest/AlarmsPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/EventsPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-8444

NMS-8444: Search in logMessage and description in events/alarms

---

opennms-base-assembly/src/main/filtered/bin/opennms

* JIRA: https://issues.opennms.org/browse/HZN-1500

HZN-1500: Removed references to Java modules in OpenNMS start script

---

core/web-assets/src/main/assets/style/opennms-theme.scss
opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp

* JIRA: https://issues.opennms.org/browse/NMS-10632
Please verify with Safari, Chrome and Firefox.

NMS-10632: Make side navigation activate on scroll

---

core/ipc/rpc/utils/pom.xml
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderImpl.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/MapScope.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/ObjectScope.java
core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderIT.java
core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/RpcMetaDataUtilsTest.java
opennms-doc/guide-admin/src/asciidoc/text/meta-data.adoc

* JIRA: http://issues.opennms.org/browse/NMS-10598

NMS-10598: Add scope for node/interface/service details

---

features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
opennms-doc/guide-development/src/asciidoc/text/rest/measurements.adoc

JIRA: https://issues.opennms.org/browse/NMS-10633
Expose the step as a constant in the JEXL expression engine.

NMS-10633: Expose the step as a constant in the JEXL engine.

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpV3User.java
features/events/traps/pom.xml
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapdConfigBean.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdConfigConfigUpdater.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java
opennms-config/src/main/java/org/opennms/netmgt/config/TrapdConfigFactory.java

JIRA: https://issues.opennms.org/browse/NMS-10630
Improve test coverage of SNMPv3 traps and informs.
This was developed while testing https://opennms.discourse.group/t/forwarding-events-from-one-opennms-server-to-another-using-snmpv3/346/2

NMS-10630: Improve test coverage of SNMPv3 traps and informs.

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/GrokParserStageSequenceBuilder.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ParserStageSequenceBuilder.java
features/events/syslog/src/main/resources/org/opennms/netmgt/syslogd/grok-patterns.txt
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/RadixTreeSyslogParserTest.java

Created new CHAR token usable in GROK patterns.
* JIRA: https://issues.opennms.org/browse/HZN-1504

HZN-1504: Introduced CHAR token to parse single characters

---

features/alarms/history/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/RestClientFactory.java
features/opennms-es-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-doc/guide-admin/src/asciidoc/text/elasticsearch/introduction.adoc

This PR will add functionality to allow for HTTP compression within the JestClient
* JIRA: https://issues.opennms.org/browse/HZN-1517

HZN-1517: Support compression in JestClient for Elasticsearch

---

features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/jest/client/pom.xml
features/jest/client/src/main/java/org/opennms/plugins/elasticsearch/rest/ElasticHealthCheck.java
features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/AlarmFeedback.java
features/situation-feedback/api/src/main/java/org/opennms/features/situationfeedback/api/FeedbackRepository.java
features/situation-feedback/elastic/pom.xml
features/situation-feedback/elastic/src/main/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepository.java
features/situation-feedback/elastic/src/main/java/org/opennms/features/situationfeedback/elastic/FeedbackDocument.java
features/situation-feedback/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/situation-feedback/elastic/src/main/resources/feedback-template.json
features/situation-feedback/elastic/src/test/java/org/opennms/features/situationfeedback/elastic/ElasticFeedbackRepositoryIT.java
features/situation-feedback/rest/api/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestService.java
features/situation-feedback/rest/impl/src/main/java/org/opennms/features/situationfeedback/rest/SituationFeedbackRestServiceImpl.java
features/situation-feedback/rest/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml

This PR adds support for tags and root cause in the situation feedback.
Additionally, existing tags can be querired from the datasource to assist front end work.
Health Check implementation is added that simply pings the ElasticSearch rest api.
* JIRA: https://issues.opennms.org/browse/HZN-1492

HZN-1492: Add Tags and RootCause to Feedback

---

features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/CollectionSetMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/collectors/CollectorRequestBuilderImpl.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionAssetMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionInterfaceMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMetaDataMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMonitoredServiceMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/requisition/mappers/RequisitionNodeMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/ticketing/TicketingMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/topology/UserDefinedLinkDaoImpl.java
features/api-layer/src/test/java/org/opennms/features/apilayer/config/CollectionSetMapperTest.java
features/api-layer/src/test/java/org/opennms/features/apilayer/requisition/mappers/RequisitionMapperTest.java
pom.xml

Changes to OpenNMS to be compatible with version 0.1.0 of the integration API.
Tested against the api-layer tests.
Jira: https://issues.opennms.org/browse/OIA-13

OIA-13: Replace bean implementations with immutables

---

core/ipc/rpc/api/src/main/java/org/opennms/core/rpc/api/RpcRequest.java
core/ipc/rpc/camel/src/main/java/org/opennms/core/rpc/camel/CamelRpcClientFactory.java
core/ipc/rpc/camel/src/main/java/org/opennms/core/rpc/camel/CamelRpcServerProcessor.java
core/ipc/rpc/common/src/main/java/org/opennms/core/rpc/echo/EchoRequest.java
core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcClientFactory.java
core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcServerManager.java
core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/AbstractSNMPRequestBuilder.java
core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpRequestDTO.java
features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorRequestBuilderImpl.java
features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorRequestDTO.java
features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestBuilderImpl.java
features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestDTO.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/MinionRpcMonitor.java
opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingRequestBuilderImpl.java
opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingRequestDTO.java
opennms-icmp/opennms-icmp-proxy-rpc-impl/src/main/java/org/opennms/netmgt/icmp/proxy/PingSweepRequestDTO.java
opennms-provision/opennms-detectorclient-rpc/src/main/java/org/opennms/netmgt/provision/detector/client/rpc/DetectorRequestBuilderImpl.java
opennms-provision/opennms-detectorclient-rpc/src/main/java/org/opennms/netmgt/provision/detector/client/rpc/DetectorRequestDTO.java
opennms-provision/opennms-detectorclient-rpc/src/main/java/org/opennms/netmgt/provision/dns/client/rpc/DnsLookupRequestDTO.java
opennms-provision/opennms-requisition-service/src/main/java/org/opennms/netmgt/provision/persist/rpc/RequisitionRequestDTO.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerRpcTimeoutIT.java

Tags like nodeId, nodeLabel, className, ipAddress are added to tracing when available.
* JIRA: http://issues.opennms.org/browse/HZN-1519

HZN-1519: Add more context to tracing by adding custom tags

---

opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc
opennms-webapp/src/main/webapp/WEB-INF/web.xml

* JIRA: https://issues.opennms.org/browse/NMS-10511

NMS-10511: Disabled session timeout for browser notifications

---

opennms-base-assembly/src/main/filtered/bin/find-java.sh
opennms-base-assembly/src/main/filtered/bin/opennms

This PR fixes some tmp file droppings that get left around.
* JIRA: http://issues.opennms.org/browse/HZN-1533

HZN-1533: clean up after $$ temp files

---

features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventdIT.java

NMS-10644: EventdIT test failure
* JIRA: http://issues.opennms.org/browse/NMS-10644

NMS-10644: EventdIT test failure

---

opennms-dao/src/test/java/org/opennms/netmgt/dao/MonitoredServiceDaoIT.java

NMS-10643: Fix MonitoredServiceDaoIT test failure
* JIRA: http://issues.opennms.org/browse/NMS-10643

NMS-10643: MonitoredServiceDaoIT test failure

---

opennms-webapp/src/main/webapp/KSC/index.jsp
opennms-webapp/src/main/webapp/js/onms-ksc/wizard.js

Search on KSC Reports page in WebUI does not work
* JIRA: http://issues.opennms.org/browse/NMS-10416

NMS-10416: Search on KSC Reports page in WebUI does not work

---

opennms-services/src/test/java/org/opennms/netmgt/collectd/DuplicatePrimaryAddressIT.java

NMS-10645: Fix flaky DuplicatePrimaryAddressIT tests
* JIRA: http://issues.opennms.org/browse/NMS-10645

Fix flaky DuplicatePrimaryAddressIT tests

---

features/bsm/daemon/src/main/java/org/opennms/netmgt/bsm/daemon/Bsmd.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/dto/InterfaceLevelResourceDTO.java
features/enlinkd/adapters/collectors/bridge/src/main/java/org/opennms/netmgt/enlinkd/DiscoveryBridgeDomains.java
features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/DiscoveryBridgeTopology.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/GraphMLTopologyProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/src/main/java/org/opennms/features/topology/plugins/topo/graphml/internal/GraphMLMetaTopologyFactory.java
features/vaadin-components/extender-service/src/main/java/org/opennms/vaadin/extender/internal/extender/ApplicationFactoryServiceTracker.java
features/wsman/src/main/java/org/opennms/netmgt/collectd/WsManCollector.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/SnmpInformantOidResolver.java
opennms-services/src/main/java/org/opennms/netmgt/rtc/datablock/RTCNodeSvcTimesList.java
opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPollInterfaceMonitor.java
opennms-webapp/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactory.java

NMS-10651: Fix "Not enough arguments." bugs
* JIRA: http://issues.opennms.org/browse/NMS-10651

NMS-10651: Fix "Not enough arguments." bugs

---

features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/OnmsProblemEventHandler.java
features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/services/NMS10647Test.java
features/mib-compiler/src/test/resources/G6-NOTIFICATION-MIB_0.20.mib

* JIRA: https://issues.opennms.org/browse/NMS-10647
Fixed error handling code to use and display the complete localized message in the case the Mib can't be extracted from the source string.

NMS-10647: Fixed ArrayIndexOutOfBoundsException in error handling code

---

opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

* JIRA: http://issues.opennms.org/browse/NMS-10576

NMS-10576: Document breaking changes to telemetryd

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/model/NodeListCommand.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java
opennms-webapp/src/main/webapp/element/index.jsp
smoke-test/src/test/java/org/opennms/smoketest/NodeListPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/SearchPageIT.java

* JIRA: https://issues.opennms.org/browse/HZN-1540

HZN-1540: Added option to search for nodes with or without flow data

---

core/jmx/impl/pom.xml
core/jmx/impl/src/main/java/org/opennms/netmgt/jmx/impl/connection/connectors/DefaultJmxConnector.java
core/jmx/impl/src/test/java/org/opennms/netmgt/jmx/connection/DefaultJmxConnectorTest.java
core/jmx/impl/src/test/java/org/opennms/netmgt/jmx/connection/test/ClientProvider.java

JIRA: https://issues.opennms.org/browse/NMS-10684

NMS-10684: Close the JMXConnector if an exception occurs when connecting

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/requisition.html
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/requisitions.html

* JIRA: https://issues.opennms.org/browse/NMS-10675

NMS-10675: Fix missing isModified indicator

---

opennms-webapp/src/main/webapp/errors/elementnotfound.jsp
smoke-test/src/test/java/org/opennms/smoketest/NodeDetailPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-10679

NMS-10679: Fix exception detection

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestServiceWithDTO.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/MinionRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MinionRestServiceIT.java

* JIRA: https://issues.opennms.org/browse/NMS-10670

NMS-10670: Table in "Manage Minions" page fails to load

---

opennms-correlation/drools-correlation-engine/pom.xml
opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/DroolsReloadFactsTest.java
opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/FusionRulesTest.java
opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/ReloadConfigurationIT.java
opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/droolsFusion/drools-engine.xml
opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/AbstractCorrelationEngine.java
opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/CorrelationEngine.java
opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/Correlator.java
opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/MultiEngineBuilder.java
opennms-correlation/opennms-correlator/src/test/java/org/opennms/netmgt/correlation/TestEngine.java

Fix the case where there is possibility of sending facts(events) while
the state being marshalled.
* JIRA: http://issues.opennms.org/browse/NMS-10678

NMS-10678: Fix reload when drools engine encounters exception

---

opennms-webapp/src/main/java/org/opennms/web/controller/outage/OutageDetailController.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/detail.jsp
opennms-webapp/src/main/webapp/notification/detail.jsp

* JIRA: http://issues.opennms.org/browse/NMS-10707

NMS-10707: Sanitize strings in a couple of additional places.

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editCategory.jsp

* JIRA: http://issues.opennms.org/browse/NMS-10654

NMS-10654: When editing a surveillance category from Admin flow, lists of nodes are not sorted by node label (reopened)

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore

This PR updates the PR template to do some basic checkbox stuff and describe our current review process.

Update PR Template

---

dependencies/asterisk/pom.xml

NMS-10718: org.asteriskjava:asterisk-java: 1.0.0-preview-20090427 -> 1.0.0-final
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10718

NMS-10718: use org.asteriskjava:asterisk-java from maven-central

---

pom.xml

NMS-10717: sevntu-checkstyle-maven-plugin: 1.23.1 -> 1.25.0 from maven-central
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10717

NMS-10717: use sevntu-checkstyle-maven-plugin from maven-central

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HZN-1582

HZN-1582: Increase logging clarity for flow processing

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpAgentConfig.java
core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/ShowConfigCommand.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/AddressSnmpConfigVisitor.java
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/Configuration.java
opennms-config-jaxb/src/main/resources/xsds/snmp-config.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/MergeableDefinition.java
opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigManager.java
opennms-config/src/main/java/org/opennms/netmgt/config/SnmpEventInfo.java
opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java
opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/minion/ttl.adoc
opennms-web-api/src/main/java/org/opennms/web/svclayer/model/SnmpInfo.java
opennms-webapp/src/main/java/org/opennms/web/admin/nodeManagement/SnmpConfigServlet.java
opennms-webapp/src/main/webapp/admin/snmpConfig.jsp

Add ttl to be specificied in snmp config page.
Add doc that explains how ttl  can be configured for RPC requests
* JIRA (Issue Tracker): http://issues.opennms.org/browse/HZN-1518

HZN-1518: Add ttl in snmp config 

---

features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlow.java
features/telemetry/protocols/sflow/parser/pom.xml
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/Array.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/Opaque.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/Address.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/ExtendedGateway.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/ExtendedRouter.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/ExtendedSwitch.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/FlowRecord.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/FlowSample.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/Interface.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/IpV4.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/IpV6.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/NextHop.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/Record.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/SFlowDataSource.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/SampleDatagramV5.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/SampledHeader.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/SampledIpv4.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/SampledIpv6.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/headers/EthernetHeader.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/headers/Inet4Header.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/headers/Inet6Header.java
features/telemetry/protocols/sflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/BsonDocumentTest.java

* JIRA: https://issues.opennms.org/browse/HZN-1581

HZN-1581: Fixed type mismatch for VLAN value

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/TimelineRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/TimelineRestServiceIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12097

NMS-12097: Timeline missing for service names including slashes

---

pom.xml

NMS-11760: Fix typo in plugin version for root pom.xml

---

opennms-base-assembly/src/main/filtered/etc/wsman-asset-adapter-configuration.xml

* JIRA: http://issues.opennms.org/browse/NMS-10682

NMS-10682: Fix mscluster resourceUri in wsman asset adapter config

---

core/web-assets/src/main/assets/js/lib/onms-http/index.js
opennms-webapp/src/main/webapp/login.jsp
smoke-test/src/test/java/org/opennms/smoketest/AngularLoginRedirectIT.java

NMS-10719: Forward user to login page if 401 Unauthorized

---

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixUdpParser.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow9UdpParser.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpParserBase.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ie/values/NullValue.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ie/values/OctetArrayValue.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ipfix/proto/DataRecord.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/DataRecord.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/OptionsTemplateRecord.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/ScopeFieldSpecifier.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/TcpSession.java
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java
features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpSessionManagerTest.java

* JIRA: https://issues.opennms.org/browse/NMS-10721

NMS-10721: Fixed session handling for Netflow v9

---

container/bridge/proxy/src/main/java/org/opennms/container/web/bridge/proxy/ProxyFilter.java

JIRA: https://issues.opennms.org/browse/NMS-12116
No explicit test coverage was added for this, but this code path is covered by the system tests (which is how it was detected in the first place).

NMS-12116: Synchronize access to the list of handlers to avoid CMEs.

---

debian/control
opennms-assemblies/minion/src/main/filtered/debian/control
opennms-assemblies/sentinel/src/main/filtered/debian/control

This fixes the behavior of the Debian packages to (somewhat) match that of the RPMs for 24.
* OpenNMS & Minion (which have "wrapper" packages):
* main package:
* `Depends: sub-packages`
* `Recommends: openjdk-11, oraclejdk-8, openjdk-8`, etc.
* core sub-package:
* `Suggests: openjdk-11, oraclejdk-8, openjdk-8`, etc.
* Sentinel (no "wrapper"):
* `Recommends: openjdk-11, oraclejdk-8, openjdk-8`, etc.
This means that for OpenNMS and Minion, if you install the "wrapper" package, it will install a JDK/JRE by default _unless_ you've configured apt to not install `Recommends`. (By default, apt treats a `Recommends` as if it were `Depends`, and basically no one changes this default behavior unless they're explicitly building minimalist systems.)
If you install the core sub-package, it will _not_ …

NMS-12119: fix Debian package dependencies for JDK 11

---

features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/BufferUtilsTest.java

Some more tests for the BufferUtils used to parse netflow packets which I've forgot to commit.

Added more tests for buffer utils

---

opennms-base-assembly/src/main/filtered/bin/config-diff.sh

Added a config diff script which helps to analyze config diffs when doing upgrades or backups from 
running OpenNMS instances.
* JIRA: https://issues.opennms.org/browse/NMS-12129
[![asciicast](https://asciinema.org/a/253768.svg)](https://asciinema.org/a/253768)

NMS-12129: Add a bash tool to help analysing config diffs

---

core/web-assets/package.json
core/web-assets/src/main/assets/js/apps/onms-reports/details.html
core/web-assets/src/main/assets/js/apps/onms-reports/index.js
core/web-assets/src/main/assets/js/lib/onms-datetimepicker/index.js
core/web-assets/src/main/assets/js/lib/onms-datetimepicker/template.html
core/web-assets/yarn.lock
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/UserRestService.java

* JIRA: https://issues.opennms.org/browse/NMS-12147
This does not consider time zone handling.
There is [another](https://issues.opennms.org/browse/NMS-12148) issue for that.

NMS-12147: Add better datetime selection

---

opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java
opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java
opennms-webapp/src/main/java/org/opennms/web/alarm/filter/CategoryFilter.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
opennms-webapp/src/main/webapp/includes/alarm-advquerypanel.jsp
opennms-webapp/src/test/java/org/opennms/web/alarm/filter/AlarmRepositoryFilterIT.java

* JIRA: https://issues.opennms.org/browse/NMS-10695

NMS-10695: Filter alarm list by surveillance categories

---

smoke-test/README.md

This Pull request came out of ticket: https://issues.opennms.org/browse/NMS-11985 but is not really related to it.
It tries to clarify the smoke test documentation. In order to avoid merge conflicts I reopened a separate pull request against develop.
Once the reviewer(s) accept the PR …

NMS-11985 improved documentation for smoke test

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/modifyGroup.jsp
opennms-webapp/src/main/webapp/js/onms-requisitions/views/requisition.html
opennms-webapp/src/main/webapp/js/onms-search/app.js

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12137
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12156
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12155

NMS-12137: Fix KSC Report search box in home page 

---

core/web-assets/src/main/assets/js/apps/onms-reports/index.js
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/WhoamiRestService.java
smoke-test/src/test/java/org/opennms/smoketest/rest/WhoamiRestIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12159
Tested this with an active directory provided by @indigo423.

NMS-12159: Fix external authenticated users not properly handled

---

core/web-assets/src/main/assets/js/apps/timeline-resize/index.js
smoke-test/src/test/java/org/opennms/smoketest/NodeDetailPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12160

NMS-12160: Outage timeline is empty

---

core/web-assets/src/main/assets/js/apps/onms-reports/details.html
core/web-assets/src/main/assets/js/apps/onms-reports/index.js
core/web-assets/src/main/assets/js/apps/onms-reports/templates.html
core/web-assets/src/main/assets/style/opennms-theme.scss
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/ReportRestService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java
opennms-base-assembly/src/main/filtered/etc/availability-reports.xml

Here we merge all of the database report actions into one single page.
I did not create an issue as we have to iterate over this a bunch more times and it is tedious to have an issue everytime stating the same. We can however assign these commits to issue https://issues.opennms.org/browse/NMS-11723 or create a consolidating new one if required.
I think we have to iterate over this some more, but this is how it looks now:
This is the list of templates
This shows a selected template
This shows a selected template, running in scheduled mode

Unify Database Report Actions

---

core/web-assets/src/main/assets/js/apps/onms-elementList/lib/elementList.js
core/web-assets/src/main/assets/js/apps/onms-elementList/templates/angular-onms-elementList-editListInPlace.html

* JIRA: https://issues.opennms.org/browse/NMS-12164
My fix for this issue in PR https://github.com/OpenNMS/opennms/pull/2583 was actually not fixing it.
This is now the proper fix, which also includes the revert of the wrong commits.

NMS-12164: Actually fix minion label issue

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/modifyGroup.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12155

NMS-12155: Group Duty Schedules Formatting Issues

---

features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/event/NodeMarkerClusterCallback.java
smoke-test/src/test/java/org/opennms/smoketest/NodeMapIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12171

NMS-12171: Fixed client-side NPE in node-map

---

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Flow.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/FlowDocument.java
features/flows/elastic/src/main/resources/netflow-template.json
features/flows/elastic/src/test/resources/netflow-template-merged.json
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpfixFlow.java
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/Netflow5Flow.java
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9Flow.java
features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/SrcDstAsTestIpFix.java
features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/SrcDstAsTestV5.java
features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/SrcDstAsTestV9.java
features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlow.java
features/telemetry/protocols/sflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SrcDstAsTestSFLow.java
features/telemetry/protocols/sflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/BsonDocumentTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12105
Please double check whether this will break any existing installation 
since the Elasticsearch template was also changed.

NMS-12105: Changed AS to type long

---

features/wsman/src/main/java/org/opennms/netmgt/provision/detector/wsman/WsManWQLDetector.java
features/wsman/src/main/java/org/opennms/netmgt/provision/detector/wsman/WsManWQLDetectorFactory.java
opennms-provision/opennms-detector-jms/src/main/java/org/opennms/netmgt/provision/detector/jms/ActiveMQDetectorFactory.java

* JIRA: https://issues.opennms.org/browse/NMS-12175

NMS-12175: WsManWQLDetectorFactory missing setBeanProperties

---

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventUtil.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventUtilDaoImpl.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilHibernateIT.java
opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc
opennms-services/src/test/java/org/opennms/netmgt/mock/EventUtilJdbcImpl.java

* JIRA: https://issues.opennms.org/browse/NMS-10657

NMS-10657: Added %primaryinterface% to events

---

core/web-assets/src/main/assets/js/apps/onms-reports/persisted.html
core/web-assets/src/main/assets/js/apps/onms-reports/schedules.html
core/web-assets/src/main/assets/js/lib/onms-schedule-editor/templates/schedule-editor.tpl.html
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Button.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/CheckBox.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/DeleteAllButton.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Select.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/TextInput.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Toggle.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/UiElement.java
smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/GeocoderServiceConfigurationPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/GrafanaEndpointPageIT.java

Here we bring back the smoke tests for the database reports.
Should be merged after PR https://github.com/OpenNMS/opennms/pull/2600.

Drift2: Bring back smoke tests for database reports

---

opennms-base-assembly/src/main/filtered/etc/resource-types.d/nxos-cpu-resource.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/nxos-resource.xml
opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/cisco-nxos-telemetry-interface.groovy

Improve the sample content for the NXOS GPB Parser Groovy Script.
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of …

NMS-11759: Improve the sample content for the NXOS GPB Parser Groovy Script

---

opennms-base-assembly/src/main/filtered/bin/find-java.sh
opennms-base-assembly/src/main/resources/bin/_lib.sh
opennms-base-assembly/src/test/shell/spec/_lib.spec.sh
opennms-base-assembly/src/test/shell/spec/link.txt

NMS-12176: recursively resolve links in find-java.sh

---

features/topology-map/org.opennms.features.topology.api/src/main/java/org/opennms/features/topology/api/HeaderUtil.java
features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
features/vaadin-dashlets/dashlet-map/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/MapDashlet.java
features/vaadin-dashlets/dashlet-topology/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/TopologyDashlet.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/NodeMapsApplication.java
features/vaadin-node-maps/src/main/java/org/opennms/features/vaadin/nodemaps/internal/gwt/client/event/NodeMarkerClusterCallback.java
smoke-test/src/test/java/org/opennms/smoketest/NodeMapIT.java
smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12171
* JIRA: https://issues.opennms.org/browse/NMS-12166

NMS-12171/NMS-12166: Smoke test fixes for develop

---

.circleci/config.yml

NMS-12199: Fix CircleCI Test Gathering for Smoke Tests
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green …

NMS-12199: Fix CircleCI Test Gathering for Smoke Tests

---

core/ipc/sink/camel/client/src/main/java/org/opennms/core/ipc/sink/camel/client/CamelRemoteMessageDispatcherFactory.java
core/ipc/sink/camel/server/src/main/java/org/opennms/core/ipc/sink/camel/server/CamelSinkServerProcessor.java
core/ipc/sink/kafka/client/src/main/java/org/opennms/core/ipc/sink/kafka/client/KafkaRemoteMessageDispatcherFactory.java
core/ipc/sink/kafka/server/src/main/java/org/opennms/core/ipc/sink/kafka/server/KafkaMessageConsumerManager.java
core/tracing/api/src/main/java/org/opennms/core/tracing/api/TracerConstants.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java

NMS-12195: Enhance Jaeger OpenTracing Logging with additional tags
This PR will add the thread name to the tracing to help provide additional tracing capabilities.
At …

NMS-12195: Enhance Jaeger OpenTracing Logging with additional tags

---

features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java
smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
smoke-test/src/main/java/org/opennms/smoketest/selenium/ExpectedConditions.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Element.java
smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Page.java
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportIT.java
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java

Here we bring back the DatabaseReportIT.
The Grafana Reports are not tested at the moment, as we either need to mock the Grafana Endpoint Requests or also start a Grafana Container with pre-configured Dashboards

Bring back DatabaseReportIT

---

opennms-web-api/src/main/java/org/opennms/web/api/Authentication.java
opennms-webapp/src/main/java/org/opennms/web/controller/NavBarController.java
opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl

Jira: https://issues.opennms.org/browse/NMS-12065
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) …

NMS-12065: Flow classification role

---

features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java
features/vaadin-dashlets/dashlet-ksc/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/KscDashlet.java
features/vaadin-dashlets/dashlet-rrd/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/RrdDashlet.java
features/vaadin-dashlets/dashlet-summary/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/SummaryDashlet.java

* JIRA: https://issues.opennms.org/browse/NMS-8283

NMS-8283: Changed the way styles are injected

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerTest.java

* JIRA: https://issues.opennms.org/browse/NMS-9535

NMS-9535: Strip credentials from resource URLs

---

opennms-doc/guide-admin/src/asciidoc/text/minion/ttl.adoc
opennms-doc/guide-admin/src/asciidoc/text/opentracing/setup.adoc

JIRA: https://issues.opennms.org/browse/NMS-10376

NMS-10376: Document RPC TTL tuning

---

opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/snmp/SnmpCollector.adoc

The SNMP collector works not just with an SNMP Proxy.

Remove SNMP proxy hint

---

core/web-assets/src/main/assets/js/apps/onms-reports/index.js
core/web-assets/src/main/assets/js/apps/onms-reports/persisted.html
core/web-assets/src/main/assets/js/apps/onms-reports/schedules.html
features/reporting/core/src/main/java/org/opennms/reporting/core/svclayer/ReportStoreService.java
features/reporting/core/src/main/java/org/opennms/reporting/core/svclayer/support/DefaultReportStoreService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/ReportRestService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java
opennms-web-api/src/main/java/org/opennms/web/utils/ResponseUtils.java

Here we add pagination for Report Schedules and already persisted Reports.

Database Reporting: Add pagination

---

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Flow.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/FlowDocument.java
features/flows/elastic/src/main/resources/netflow-template.json
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/filter_time_range.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_missing.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_others.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_terms.ftl
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowBuilder.java
features/flows/elastic/src/test/resources/flow-document-netflow5.json
features/flows/elastic/src/test/resources/netflow-template-merged.json
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/common/UpdatingFlow.java
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpfixFlow.java
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/Netflow5Flow.java
features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9Flow.java
features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/FlowTimeoutTest.java
features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/FlowTimeoutTest.java
features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlow.java

This is another shot in trying to fix flows with timeouts.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10721

NMS-10721: Respect flow timeout

---

container/features/pom.xml
container/features/src/main/resources/features.xml
container/karaf/src/main/filtered-resources/etc/custom.properties
core/daemon/pom.xml
core/daemon/src/main/resources/META-INF/opennms/applicationContext-activemq.xml
core/ipc/rpc/api/src/main/java/org/opennms/core/rpc/api/RequestRejectedException.java
core/ipc/rpc/camel/src/main/java/org/opennms/core/rpc/camel/CamelRpcClientFactory.java
core/lib/src/main/java/org/opennms/core/utils/StringUtils.java
features/activemq/broker-api/pom.xml
features/activemq/broker-api/src/main/java/org/opennms/features/activemq/broker/api/ManagedBroker.java
features/activemq/broker-api/src/main/java/org/opennms/features/activemq/broker/api/ManagedDestination.java
features/activemq/broker-api/src/main/java/org/opennms/features/activemq/broker/impl/ManagedBrokerImpl.java
features/activemq/broker-api/src/main/java/org/opennms/features/activemq/broker/impl/ManagedDestinationImpl.java
features/activemq/pom.xml
features/activemq/shell/pom.xml
features/activemq/shell/src/main/java/org/opennms/features/activemq/shell/PurgeQueue.java
features/activemq/shell/src/main/java/org/opennms/features/activemq/shell/QueueNameCompleter.java
features/activemq/shell/src/main/java/org/opennms/features/activemq/shell/Stats.java
opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/minion/jms.adoc

JIRA: https://issues.opennms.org/browse/NMS-12222
In this we PR:
1) Make it possible/easy to diagnose issues related to ActiveMQ flow control using the Karaf shell
2) Ensure that RPC producer threads are not blocked forever when (ActiveMQ) flow control kicks in
3) Improve/add documentation around JMS RPC

NMS-12222: Improve diagnostics and resiliency of JMS RPC 

---

opennms-base-assembly/src/main/filtered/etc/events/Dlink.events.xml
opennms-base-assembly/src/main/filtered/etc/events/Websense.events.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-speedtest/events/Websense.events.xml
opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc

NMS-12227 : add missing trailing e to interfaceresolv

---

opennms-alarms/email-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/email/EmailNorthbounder.java
opennms-base-assembly/src/main/filtered/etc/javamail-configuration.properties
opennms-config-model/src/main/java/org/opennms/netmgt/config/javamail/SendmailMessage.java
opennms-enterprise-reporting/opennms-reportd/src/main/java/org/opennms/netmgt/reporting/service/JavaMailDeliveryService.java
opennms-javamail/opennms-javamail-api/src/main/java/org/opennms/javamail/JavaMailer.java
opennms-javamail/opennms-javamail-api/src/main/java/org/opennms/javamail/JavaSendMailer.java
opennms-javamail/opennms-javamail-api/src/test/java/org/opennms/javamail/JavaMailerTest.java
opennms-javamail/opennms-javamail-api/src/test/java/org/opennms/javamail/JavaSendMailerTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12224

NMS-12224: added replyTo field

---

core/web-assets/src/main/assets/js/apps/onms-reports/ReportDetails.js
core/web-assets/src/main/assets/js/apps/onms-reports/index.js
core/web-assets/src/main/assets/js/apps/onms-reports/report-details.html
features/endpoints/grafana/api/src/main/java/org/opennms/netmgt/endpoints/grafana/api/GrafanaClient.java
features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java
features/endpoints/grafana/client/src/test/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImplIT.java
features/reporting/api/src/main/java/org/opennms/api/reporting/ReportParameterBuilder.java
features/reporting/api/src/main/java/org/opennms/api/reporting/parameter/ReportParameters.java
features/reporting/api/src/main/java/org/opennms/api/reporting/parameter/ReportTimezoneParm.java
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportDetails.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportDetailsBuilder.java
features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaQuery.java
integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/TimezoneHelper.java
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-1ppp.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-2ppp.jrxml
opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-4ppp.jrxml
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSchedulerService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/UserRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/WhoamiRestService.java

* JIRA: https://issues.opennms.org/browse/NMS-12149
Should be merged after PR https://github.com/OpenNMS/opennms/pull/2654

NMS-12149: Allow multiple recipients

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-doc/guide-admin/src/asciidoc/text/database-reports/database.adoc
opennms-webapp/src/main/resources/org/opennms/web/svclayer/applicationContext-svclayer.xml

* JIRA: https://issues.opennms.org/browse/NMS-12240

NMS-12240: Allow disabling the report scheduler

---

smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/UiPageTest.java

Here we fix the flapping `DatabaseReportPageIT`.
JIRA: https://issues.opennms.org/browse/NMS-12241

NMS-12241: Fix flapping DatabaseReportPageIT

---

core/web-assets/package.json
core/web-assets/src/main/assets/js/apps/onms-reports/index.js
core/web-assets/src/main/assets/js/apps/onms-reports/report-details.html
core/web-assets/yarn.lock

Here we add the capability to search the grafana endpoint, grafana dashboard and timezone select boxes.
* JIRA: https://issues.opennms.org/browse/NMS-12152
Should be merged after PR https://github.com/OpenNMS/opennms/pull/2654

NMS-12152: Add search capabilities for select boxes

---

opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
smoke-test/src/test/java/org/opennms/smoketest/ScheduledOutageIT.java

* JIRA: https://issues.opennms.org/browse/LTS-233

LTS-233: Fixed broken text for scheduled outages

---

smoke-test/src/test/java/org/opennms/smoketest/ScheduledOutageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12264

NMS-12264: Fixed ScheduleOutageIT for new UI

---

features/vaadin-dashboard/src/main/java/org/opennms/features/vaadin/dashboard/ui/wallboard/WallboardBody.java

* JIRA: https://issues.opennms.org/browse/NMS-12237

NMS-12237: using UI.access() method

---

opennms-config-model/src/main/java/org/opennms/netmgt/config/poller/outages/BasicSchedule.java
opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
smoke-test/src/test/java/org/opennms/smoketest/ScheduledOutageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12255

NMS-12255: Fixed deletion of outage type

---

opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
opennms-webapp/src/main/webapp/element/node.jsp
smoke-test/src/test/java/org/opennms/smoketest/ScheduledOutageIT.java

* JIRA: https://issues.opennms.org/browse/LTS-234

LTS-234: Allow special characters in scheduled outage name

---

opennms-container/fetch-build-rpms.sh

This PR just makes some minor adjustments to the fetch script to fix output and also add a missing package that's normally copied into the VMs.
At that time, if you …

NMS-12271: fix fetch script help

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestServiceWithDTO.java

This PR fixes a reflected file download vulnerability in the v2 rest API. An uncaught exception was causing the request payload to be reflected back in the response body. The fix was to catch a broader Exception class (we were previously catching one of its sub-classes). There was already logging in place where the exception was caught.
~~The response is now an HTTP 204: NO-CONTENT which is the intended behaviour in this case. Previously the response was a 500 error with an error message including the reflected payload.~~
The response will now yield a HTTP 500 error without the payload being reflected. …

NMS-10703: Reflected file download vulnerability in /api/v2/scanreports

---

features/wsman/pom.xml

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12235

NMS-12235: Fix WS-Man issues in Java11

---

opennms-doc/guide-admin/src/asciidoc/text/flows/classification-engine.adoc

Jira: https://issues.opennms.org/browse/NMS-12278
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) …

NMS-12278: Add documentation about classification rule & group sorting

---

features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java

Jira: https://issues.opennms.org/browse/NMS-12258
At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) …

NMS-12258: Use correct parameters in report created by cron job

---

core/web-assets/src/main/assets/js/vendor/flot-js.js

NMS-10635: fix graph zooming in backshift graphs

---

core/schema/src/main/liquibase/25.0.0/changelog.xml
smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java

JIRA: https://issues.opennms.org/browse/NMS-12286

NMS-12286: Fix position values for classification groups

---

features/enlinkd/adapters/collectors/bridge/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfig.java
features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfigManager.java
features/enlinkd/config/src/main/java/org/opennms/netmgt/config/enlinkd/EnlinkdConfiguration.java
features/enlinkd/config/src/main/resources/xsds/enlinkd-configuration.xsd
features/enlinkd/config/src/test/java/org/opennms/netmgt/config/enlinkd/EnlinkdConfigurationTest.java
features/enlinkd/daemon/src/main/java/org/opennms/netmgt/enlinkd/EnhancedLinkd.java
opennms-base-assembly/src/main/filtered/etc/enlinkd-configuration.xml

* JIra: https://issues.opennms.org/browse/NMS-10582

NMS-10582: snmp authentication error traps with Enhanced Linkd / bridge discovery

---

core/lib/src/main/java/org/opennms/core/time/YearGuesser.java
core/lib/src/main/java/org/opennms/core/time/ZonedDateTimeBuilder.java
core/lib/src/test/java/org/opennms/core/time/YearGuesserTest.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/RadixTreeSyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogTimeStamp.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogYearCompleter.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogYearCompleterTest.java

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-10605

NMS-10605: Syslog incorrect dates being parsed into database

---

opennms-config-model/src/main/java/org/opennms/netmgt/config/scriptd/ScriptdConfiguration.java
opennms-config-model/src/main/resources/xsds/scriptd-configuration.xsd
opennms-config/src/main/java/org/opennms/netmgt/config/ScriptdConfigFactory.java
opennms-services/src/main/java/org/opennms/netmgt/scriptd/Executor.java
opennms-services/src/main/java/org/opennms/netmgt/scriptd/Scriptd.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-8294

NMS-8294: Run Scriptd event scripts in a Hibernate transaction

---

opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10073

NMS-10073: Move Telephone PIN to Notification  Information

---

opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMetaData.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMetaDataList.java
opennms-model/src/test/java/org/opennms/netmgt/model/OnmsMetaDataListTest.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MetadataRestIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12272

NMS-12272: Fixed Metadata ReST API

---

opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10073

NMS-10073: Move Telephone PIN to Notification Information

---

opennms-base-assembly/src/main/filtered/etc/notifd-configuration.xml

Reverts OpenNMS/opennms#2699
Details in: https://issues.opennms.org/browse/NMS-10662

Revert "NMS-10662: Map the notifd autoacknowledgement to alarms"

---

opennms-webapp/src/main/webapp/includes/interfaceAvailability-box.jsp
opennms-webapp/src/main/webapp/includes/serviceAvailability-box.jsp

* JIRA: https://issues.opennms.org/browse/NMS-12321
See PR https://github.com/OpenNMS/opennms/pull/2747 for more details

NMS-12321: Fix styling for availability columns (M2015-M2018)

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/node-panels.html

* JIRA: https://issues.opennms.org/browse/NMS-12273
Here we add the Meta-Data editor to the vertical layout.

NMS-12273: Add missing meta-data panel to vertical layout

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.snmp.trap.translator.events.xml

* JIRA: https://issues.opennms.org/browse/NMS-10564

NMS-10564: Logmsg formatting for SNMP trap event definitions

---

core/ipc/sink/kafka-impl/src/main/java/org/opennms/core/ipc/sink/kafka/KafkaRemoteMessageDispatcherFactory.java

This will fix issues when there are exceptions from kafka other than timeout exception and Sink keeps trying to send message.
This brings bug fix part of `NMS-11126`  
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-11126

NMS-11126: Don't buffer unless it is timeout exception

---

container/features/src/main/resources/features.xml
features/distributed/kv-store/api/src/main/java/org/opennms/features/distributed/kvstore/api/KeyValueStore.java
features/distributed/kv-store/blob/blob-shell/pom.xml
features/distributed/kv-store/blob/blob-shell/src/main/java/org/opennms/features/distributed/kvstore/blob/shell/BlobStoreBenchmark.java
features/distributed/kv-store/blob/cassandra/src/main/java/org/opennms/features/distributed/kvstore/blob/cassandra/CassandraBlobStore.java

This PR addresses some issues with Cassandra blobstore async operations. I didn't end up addressing this the way I originally planned, see comment in Jira: https://issues.opennms.org/browse/NMS-12274?focusedCommentId=55979#comment-55979
The benchmark shell command now has retry logic so it does not outright fail when it overwhelms the C* connection pool.
Also updated the C* blobstore impl so that `truncateContextAsync()` doesn't use async deletes. It will likely be a bit slower now, but it won't fail due to connection pool size issues.
Tested manually on Sentinel w/Cassandra.
3. prefix your commit …

NMS-12274: Improve robustness of CassandraBlobStore for async operations

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.bsm.events.xml
smoke-test/src/test/java/org/opennms/smoketest/bsm/BsmEventsIT.java

* JIRA: https://issues.opennms.org/browse/NMS-10578

NMS-10578: Update severity for BSM alarms

---

opennms-doc/guide-admin/src/asciidoc/text/user-management/users.adoc

Also mentioned RADIUS by name.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12339

NMS-12339: Clarify that LDAPS is supported for external authentication

---

features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorAbsoluteChange.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorHighLow.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRearmingAbsoluteChange.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRelativeChange.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorState.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdStateIT.java
features/collection/thresholding/itests/pom.xml
features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java
features/distributed/kv-store/api/src/main/java/org/opennms/features/distributed/kvstore/api/SerializingBlobStore.java
features/distributed/kv-store/blob/in-memory/src/main/java/org/opennms/features/distributed/kvstore/blob/inmemory/InMemoryMapBlobStore.java

This PR fixes a bug where certain thresholds would have key collisions when getting persisted to the threshold state store. This is because we weren't using enough information in the key to make it unique. The effect of this is that upon restart multiple thresholds would retrieve the same state causing them to be out of sync with their true state from before the restart (that state was lost).
If you know that a particular person is subject matter expert in the area your PR affects, feel …

NMS-12329: Threshold state keys do not incorporate the collected resource's instance label

---

core/web-assets/src/main/assets/js/apps/onms-reports/index.js
smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java

JIRA: https://issues.opennms.org/browse/NMS-12342

NMS-12342: Fix email reg exp issue

---

features/enlinkd/adapters/collectors/bridge/src/main/java/org/opennms/netmgt/enlinkd/NodeDiscoveryBridge.java
features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms4930EnIT.java

Jira: https://issues.opennms.org/browse/NMS-10582

NMS-10582: fix problem with not writable map

---

opennms-doc/guide-development/src/asciidoc/text/rest/ifservices.adoc

Documentation typo for /rest/ifservices on the developers guide
* [ x Have you updated the JIRA link at the bottom of this comment to link to your issue?
At that time, …

NMS-9842 - Documentation typo for /rest/ifservices on the developers guide

---

core/test-api/services/src/main/resources/minimal-eventconf.xml
opennms-base-assembly/src/main/resources/contrib/qosdaemon/qos_example_configuration/opennms_fault_config/eventconf.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-speedtest/eventconf.xml
opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-wildcard/eventconf.xml
opennms-dao-mock/src/main/resources/minimal-eventconf.xml
opennms-services/src/test/resources/org/opennms/netmgt/mock/eventconf.xml

* Jira: https://issues.opennms.org/browse/NMS-10346

NMS-10346: default event description is incorrect

---

opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/InterfaceToNodeCache.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockInterfaceToNodeCache.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/InterfaceToNodeCacheEventProcessor.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImplIT.java

If node not present, find node and delete all corresponding interfaces
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12338

NMS-12338: Delete interfaces in cache for node deletion

---

opennms-doc/guide-install/src/asciidoc/text/r-statistical-computing.adoc

Fix installation instructions to install R on CentOS 8.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12352

NMS-12352: Fix R installation for CentOS 8

---

debian/control
tools/packages/opennms/opennms.spec

NMS-12341: update PostgreSQL package deps to match code requirements

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Requisition.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Requisitions.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/requisition.html
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/requisitions.html

When the user changes the page size, the value will be stored on a cookie, so subsequent access to the page will use the saved value.
At that time, if you have commit …

NMS-9793: Be able to change the number of rows for the pagination control on the Requisitions UI.

---

opennms-base-assembly/src/main/filtered/etc/events/Cisco.events.xml

NMS-12362: Update CISCO-ENTITY-SENSOR-MIB threshold trap events to include alarm-data

---

opennms-config-tester/pom.xml
opennms-config-tester/src/main/java/org/opennms/netmgt/config/tester/ConfigTester.java
opennms-config-tester/src/main/resources/META-INF/opennms/applicationContext-configTester.xml
opennms-config-tester/src/test/java/org/opennms/netmgt/config/tester/ConfigTesterTest.java

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-10396

NMS-10396: Config tester doesn't detect missing xml datacollection file

---

opennms-container/horizon/Dockerfile
opennms-container/minion/Dockerfile
opennms-container/minion/assets/entrypoint.sh
opennms-container/sentinel/Dockerfile
opennms-container/sentinel/assets/entrypoint.sh

NMS-12384: backport some missing commits to foundation-2019

---

.circleci/config.yml
opennms-container/pom2version.py

Use new base image for our build environment with Python2 and Python3 support. Update shebang in our python script to fetch the version number to python3.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12380

NMS-12380: Use python3 and add build-env with python support

---

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/ImmutableGraph.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraph.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/transformer/SemanticZoomLevelTransformer.java
features/graph/api/src/test/java/org/opennms/netmgt/graph/api/generic/GenericGraphTest.java
features/graph/provider/graphml/src/main/java/org/opennms/netmgt/graph/provider/graphml/GraphmlGraphContainerProvider.java
features/graph/rest/src/main/java/org/opennms/netmgt/graph/rest/api/GraphRestService.java
features/graph/rest/src/main/java/org/opennms/netmgt/graph/rest/api/Query.java
features/graph/rest/src/main/java/org/opennms/netmgt/graph/rest/impl/GraphRestServiceImpl.java
features/graph/rest/src/main/java/org/opennms/netmgt/graph/rest/impl/renderer/JsonGraphRenderer.java
features/graph/simple/src/main/java/org/opennms/netmgt/graph/simple/AbstractDomainGraph.java
smoke-test/src/main/java/org/opennms/smoketest/graphml/GraphmlDocument.java
smoke-test/src/test/java/org/opennms/smoketest/graph/GraphRestServiceIT.java
smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
smoke-test/src/test/resources/topology/graphml/test-topology-2.xml

Here we allow fetching a "view" of a given graph.
The view is calculated by a given set of vertices and focus and the semantic zoom level (szl).
The returned graph contains all vertices and edges which are in focus and have a connection with hops lesser or equal the number of the szl parameter.
In case the vertices in focus do not exist in the graph, they are ignored.
JIRA: https://issues.opennms.org/browse/NMS-12376

NMS-12376: Allow fetching graphs with SZL and Vertices in Focus (or apply default focus)

---

.circleci/config.yml
.circleci/scripts/configure-signing.sh
.circleci/scripts/makerpm.sh

This enables signing RPMs when building in CircleCI.  It adds a small script that sets up `.rpmmacros` and `gpg.conf` to build compatible RPMs without needing text input.
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for …

ITREFIT-270: enable RPM signing

---

features/wsman/src/main/java/org/opennms/netmgt/poller/monitors/WsManMonitor.java
features/wsman/src/test/java/org/opennms/netmgt/poller/monitors/WSManMonitorTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12365

NMS-12365: Fixed WS-MAN poller and test

---

.circleci/config.yml
.circleci/scripts/makedeb.sh
debian/rules
features/wsman/src/test/java/org/opennms/netmgt/poller/monitors/WSManMonitorTest.java
makedeb.sh

This PR adds support for building (and signing) Debian packages in CircleCI.
A few notes:
* `makedeb.sh` has been modified to split up building opennms/minion/centinel, like `makerpm.sh` was
* I put the Debian package runs _after_ integration tests not because they depend on it (while testing, I only depended on `build`), but because we shouldn't bother spending CPU cycles making them unless everything passes, since they're not required for anything other than being artifacts.
* This PR includes an `@Ignore` for the `WSManMonitorTest` test that's currently failing just so I could get everything to go green, but I can remove it once it passes/is approved.
2. update the JIRA link at the …

ITREFIT-272: add Debian build support

---

opennms-base-assembly/src/main/filtered/bin/send-event.pl

This PR applies a patch from attached to the issue to fix our send-event.pl script which got busted when we introduced time zone changes.
With all the kudos to the contributor: @jb4415🏅
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12392

NMS-12392: Fix send-event.pl with time zone support

---

opennms-container/horizon/build_container_image.sh
opennms-container/minion/build_container_image.sh
opennms-container/sentinel/build_container_image.sh

Bump OpenJDKs to 11.0.5.10 to address [JDK-8226667](https://bugs.openjdk.java.net/browse/JDK-8226667)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12387

NMS-12387: Bump OpenJDKs to 11.0.5.10

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp

* JIRA: https://issues.opennms.org/browse/NMS-12379

NMS-12379: Use absolute URL instead of partial URL

---

opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/snmp/AddressSnmpConfigVisitor.java
opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java
opennms-config/src/test/java/org/opennms/netmgt/config/SnmpEventInfoTest.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12413

NMS-12413: Fix SNMP Remove from definitions

---

core/lib/src/main/java/org/opennms/core/time/YearGuesser.java
core/lib/src/main/java/org/opennms/core/time/ZonedDateTimeBuilder.java
core/lib/src/test/java/org/opennms/core/time/YearGuesserTest.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/RadixTreeSyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogParser.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogTimeStamp.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogYearCompleter.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogMessageTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogYearCompleterTest.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/main-module/src/main/java/org/opennms/plugins/elasticsearch/rest/archive/OpenNMSHistoricEventsToEs.java
features/opennms-es-rest/main-module/src/test/java/org/opennms/plugins/elasticsearch/rest/EventToIndexTest.java

NMS-12390: do not modify the existing event when processing parameters

---

features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/TopologyUI.java
features/topology-map/org.opennms.features.topology.link/src/main/java/org/opennms/features/topology/link/TopologyLinkBuilder.java
smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java

JIRA: https://issues.opennms.org/browse/NMS-12431

NMS-12431: Allow selecting the layer via URL parameter in topology ui

---

features/flows/classification/engine/impl/pom.xml
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/PortValue.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineTest.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/value/PortValueTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12429

NMS-12429: Reuse rules when defining port ranges

---

features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/PortValue.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/validation/RuleValidatorTest.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/value/PortValueTest.java
features/flows/classification/persistence/api/src/main/java/org/opennms/netmgt/flows/classification/persistence/api/Rule.java

JIRA: https://issues.opennms.org/browse/NMS-12433
Should be merged after PR https://github.com/OpenNMS/opennms/pull/2840

NMS-12433: Fix ranged port values

---

opennms-doc/guide-development/src/asciidoc/text/graph/graph.adoc

NMS-12441 Minor text changes

---

core/web-assets/src/main/assets/js/apps/onms-classifications/index.js
core/web-assets/src/main/assets/js/apps/onms-classifications/views/modals/new-rule-modal.html

* JIRA: https://issues.opennms.org/browse/NMS-12432

NMS-12432: Fix error handling in classification ui 

---

core/schema/src/main/liquibase/26.0.0/changelog.xml
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericEdge.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericElement.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraph.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraphContainer.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericProperties.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/info/DefaultGraphContainerInfo.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/persistence/GraphRepository.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/search/SearchCriteria.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/updates/ChangeSet.java
features/graph/api/src/main/java/org/opennms/netmgt/graph/api/updates/ContainerChangeSet.java
features/graph/api/src/test/java/org/opennms/netmgt/graph/api/updates/ChangeSetTest.java
features/graph/api/src/test/java/org/opennms/netmgt/graph/api/updates/ContainerChangeSetTest.java
features/graph/dao/api/src/main/java/org/opennms/netmgt/graph/GraphContainerEntity.java
features/graph/domain/src/main/java/org/opennms/netmgt/graph/domain/AbstractDomainGraph.java
features/graph/domain/src/main/java/org/opennms/netmgt/graph/domain/AbstractDomainGraphContainer.java
features/graph/provider/graphml/src/main/java/org/opennms/netmgt/graph/provider/graphml/GraphmlToGraphConverter.java
features/graph/provider/legacy/src/main/java/org/opennms/netmgt/graph/provider/legacy/LegacyGraph.java
features/graph/rest/api/src/main/java/org/opennms/netmgt/graph/rest/api/GraphSearchRestService.java
features/graph/rest/impl/src/main/java/org/opennms/netmgt/graph/rest/impl/GraphSearchRestServiceImpl.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/enrichment/NodeEnrichmentProcessor.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/persistence/DefaultGraphRepository.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/persistence/converter/CollectionConverter.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/persistence/mapper/GenericToEntityMapper.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/search/NodeSearchProvider.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/service/DefaultGraphService.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/updates/DefaultGraphNotificationService.java
features/graph/service/src/test/java/org/opennms/netmgt/graph/search/NodeSearchProviderIT.java
features/graph/shell/src/main/java/org/opennms/netmgt/graph/shell/GraphSearchCommand.java
smoke-test/src/test/java/org/opennms/smoketest/graph/GraphRestServiceIT.java

Here we clean up the last bits, mostly rewording/reorganisation of code and also removing/addressing of TODOs.

Final cleanup of Graph-Service branch

---

opennms-webapp/src/main/webapp/includes/help-contact.jsp
opennms-webapp/src/main/webapp/includes/help-documentation.jsp
smoke-test/src/test/java/org/opennms/smoketest/HelpPageIT.java
smoke-test/src/test/java/org/opennms/smoketest/SupportPageIT.java

Remove link to Mailing lists and replaced StackOverflow with Discourse.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12418

NMS-12418: Remove Mailing list and StackOverflow link

---

opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/AlarmdTestUtil.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/alarmd.drl

NMS-12439: Ticket-creating automations are incorrectly enabled by default

---

.circleci/config.yml
.circleci/scripts/makedeb.sh
.circleci/scripts/makerpm.sh
.circleci/scripts/publish-cloudsmith.sh

This PR updates the CircleCI build to publish packages [to CloudSmith](https://cloudsmith.io/~opennms/repos/) for `foundation-*`, `release-*`, and `develop` branches to the `opennms/foundation-*`, `opennms/testing`, and `opennms/develop` repositories, respectively.
The idea is to enable builds for a live test/evaluation of CloudSmith to potentially replace our existing RPM/Debian infrastructure.
Currently they don't support noarch/"any" repositories for packages that are targeted to multiple releases of a distro, so I am currently using `el5` and `etch` for distros until this feature is implemented (due in January).
I still have some work to get distro-specific packages up there, but this is a start.
1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of …

NMS-12464: publish packages to CloudSmith

---

.circleci/scripts/lib.sh
.circleci/scripts/makedeb.sh
.circleci/scripts/makerpm.sh

This PR changes `makerpm.sh` and `makedeb.sh` to include the branch name and CircleCI build number in the package revision, to ease upgrades and make it clearer where packages come from.
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is …

NMS-12467: package revision should come from branch & build number

---

features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/NMS12459Test.java
features/mib-compiler/src/test/resources/K2-MIB.mib

* JIRA: https://issues.opennms.org/browse/NMS-12459

NMS-12459: Fixed NPE

---

features/enlinkd/adapters/common/src/main/java/org/opennms/netmgt/enlinkd/common/TopologyUpdater.java
features/enlinkd/adapters/updaters/nodes/pom.xml
features/enlinkd/adapters/updaters/nodes/src/test/java/org/opennms/netmgt/enlinkd/TopologyUpdaterIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12443

NMS-12443: Fix getTopology() is blocking when discovery is in progress

---

CONTRIBUTING.md

I have not created JIRA request for this trivial fix. Please consider my contribution to be too trivial to be under any copyright law in the world.

Community Welcome Guide is now on discourse

---

opennms-doc/guide-install/src/asciidoc/text/minion-custom-messaging-system/setup-kafka/tuning-kafka.adoc

Doc changes
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12479

Review of Using Single Topic documentation

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Node.js
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/node-panels.html
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/node.html

NMS-12292: Add a "Delete" button on the Node page of the Requisition UI

---

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/downtime-model.adoc

Add documentation for the downtime model change introduced in NMS-12442. We describe valid delete values for never, managed,always and when it is not set.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12520

NMS-12520: Add documentation for downtime model delete attribute

---

opennms-webapp/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java

Here we backport the security issue described in the jira issue all the way back to `foundation`.
JIRA: https://issues.opennms.org/browse/NMS-12513

NMS-12513: Fix HQL injection issue

---

features/graph/provider/graphml/src/main/java/org/opennms/netmgt/graph/provider/graphml/GraphmlToGraphConverter.java
features/graph/provider/legacy/src/main/java/org/opennms/netmgt/graph/provider/legacy/LegacyGraphProvider.java

JIRA: https://issues.opennms.org/browse/NMS-12540

NMS-12540: Enrich with status by default

---

core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AsyncDispatcherImpl.java
core/ipc/sink/common/src/test/java/org/opennms/core/ipc/sink/common/AsyncDispatcherTest.java

This PR fixes a race condition and memory leak in the AsyncDispatcherImpl class. The race condition was on enqueing a message where another thread may dequeue and process the message before the result of the enqueue was persisted to the Map of futures. This resulted in the future never getting completed, never getting removed from the map and a warning log message being printed.
I added a trivial synchronization strategy around the enqueue process to guarantee the enqueue+record future to map is completed atomically before any other thread could dequeue the message.
The behavior is non-deterministic since it is a race condition, however the test case should catch the problem virtually all of the time since the race was really likely to happen. I decided to use a simple test rather than …

NMS-12565: "No future found for message" warnings in telemetryd log

---

container/features/src/main/resources/features-sentinel.xml
container/features/src/main/resources/features.xml
core/test-api/kafka/pom.xml
core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java
features/distributed/coordination/zookeeper/pom.xml
pom.xml
smoke-test/pom.xml

NMS-12582: Upgrade Kafka components to version 2.4.0

---

opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/setting-up-opennms.adoc

Updated requirements and added information on what to do if trying to run current ONMS version with CentOS 7.
At that time, if you have commit access (are an OpenNMS …

NMS-12604: Updated requirements

---

features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpTelemetryAdapter.java

* JIRA: https://issues.opennms.org/browse/NMS-12553

NMS-12553: Added per Afi/Safi statistics

---

features/telemetry/itests/src/test/java/org/opennms/netmgt/telemetry/itests/BmpAdapterIT.java
features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/openbmp/BmpIntegrationAdapter.java
features/telemetry/protocols/bmp/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/openbmp/BmpIntegrationAdapterTest.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParser.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/InformationElement.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/LocRibFlags.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/PeerHeader.java
features/telemetry/protocols/bmp/transport/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/transport/Transport.java
features/telemetry/protocols/bmp/transport/src/main/resources/transport.proto

* JIRA: https://issues.opennms.org/browse/NMS-12570
Implemented flags, new peer type and TLV. Reason code's value isn't defined yet (see https://tools.ietf.org/html/draft-ietf-grow-bmp-local-rib-06#section-5.3).

NMS-12570: Added Loc-Rib peer type

---

features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java

NMS-12438 : for calendar xml reports, return rendered html.

---

container/shared/pom.xml
container/shared/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
smoke-test/src/test/java/org/opennms/smoketest/minion/JolokiaRestIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12533

NMS-12533: Add Jolokia features to Minion & Sentinel

---

opennms-webapp/src/main/java/org/opennms/web/controller/RedirectRestricter.java
opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AcknowledgeAlarmByFilterController.java
opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AcknowledgeAlarmController.java
opennms-webapp/src/main/java/org/opennms/web/controller/notification/AcknowledgeNotificationController.java
opennms-webapp/src/test/java/org/opennms/web/controller/RedirectRestricterTest.java

This Pull Request removes open redirect vulnerabilities by restricting the redirect to a whitelist.
To be tested: I hope I found all links for the whitelist but I might have missed some.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12612

NMS-12513 Open Redirect security issue

---

opennms-base-assembly/src/main/filtered/etc/log4j2.xml

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12475

NMS-12475: remove threshd entry in log4j2.xml

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.collectd.events.xml

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12474

NMS-12474: invert auto-clean option in dataCollectionSucceeded/Failed events

---

opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc

Enhanced documentation for expandable event parameters.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12228

NMS-12228: document additional expandable event parameters

---

opennms-container/minion/container-fs/confd/conf.d/disable-jms.boot.toml
opennms-container/minion/container-fs/confd/templates/disable-jms.boot.tmpl

JIRA: https://issues.opennms.org/browse/NMS-12631

NMS-12631: Disable JMS when using Kafka.

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.internal.events.xml

* JIRA: http://issues.opennms.org/browse/NMS-9754

NMS-9754: RTC subscription events should not be persisted to DB

---

core/web-assets/src/main/assets/static/load-assets.jsp
opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
opennms-webapp/src/main/webapp/includes/notification-box.jsp
opennms-webapp/src/main/webapp/includes/resultsIndex.jsp
opennms-webapp/src/main/webapp/includes/resultsIndexNoCount.jsp

This PR addresses xss issues in jsp includes.
Replaces: https://github.com/OpenNMS/opennms/pull/2943
* Jira:  https://issues.opennms.org/browse/NMS-12617

NMS-12617: XSS security issues - PR2

---

opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoredService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/OnmsMonitoredServiceResource.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeRestServiceIT.java

This Pull Request allows the creation of a monitored-service via JSON in api v1 and v2
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12625

NMS-12625: Cannot create monitored-service with JSON via ReST

---

features/graph/service/src/main/java/org/opennms/netmgt/graph/service/DefaultGraphService.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12637

NMS-12637: Fix NPE on graph service

---

features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParser.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/UpdatePacket.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/AsPath.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/ExtendedCommunities.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/ExtendedV6Communities.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/Origin.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/InformationElement.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/TLV.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/PeerDownPacket.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/RouteMirroringPacket.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/StatisticsReportPacket.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/TerminationPacket.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/mirroring/Information.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12641

NMS-12641: Implement deprecated OSPF attrs and silence warnings

---

features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/TcpListener.java
features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java
features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParserFactory.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12644

NMS-12644: Fix loading of BMP bulkhead config

---

features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/KafkaFlowForwarderIT.java
features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/FlowDocumentBuilder.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12660

NMS-12660: Fix NPE in KafkaFlowForwarder

---

pom.xml

* JIRA: https://issues.opennms.org/browse/NMS-12541

NMS-12541: Bumped version for io.netty

---

features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
opennms-base-assembly/src/main/filtered/etc/events/opennms.provisioning.events.xml
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/DragonWaveNodeSwitchingIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/InvalidRequisitionDataIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12658

NMS-12658: Add nodeScanStarted event for scheduled node scans

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/LatencyTypeResource.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaPersisterIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12661

NMS-12661: Fix collection set building for ResponseTime resources

---

opennms-base-assembly/src/main/filtered/bin/opennms

NMS-12672: return appropriate exit code for status inquiries

---

smoke-test/src/main/java/org/opennms/smoketest/containers/ElasticsearchContainer.java

NMS-12648: Update ES version used for smoketests to v7.6.1
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, …

NMS-12648: Update ES version used for smoketests to v7.6.1

---

opennms-services/src/main/java/org/opennms/netmgt/poller/Poller.java
opennms-services/src/main/java/org/opennms/netmgt/poller/PollerEventProcessor.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerQueryManagerDaoIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12681

NMS-12681: Fix  Reloading the Pollerd daemon causes multiple nodeDown messages

---

core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AbstractMessageConsumerManager.java

Without using the custom thread pool, the thread that is going to run `CompletableFuture.runAsync` seems to be coming from thread pool that is using different classloader (may be custom classloader from osgi ? ) than default class loader which is causing class loader issues while running telemetry adapters.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12688

NMS-12688: Use custom thread pool to run the Startup of consumers

---

opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/datacollection/netscaler-vserver.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/netscaler-vserver-graph.properties

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12269

NMS-12269: Netscaler vServer SNMP collection and graph definitions

---

opennms-doc/guide-admin/src/asciidoc/text/alarms/history.adoc
opennms-doc/guide-admin/src/asciidoc/text/minion/jms.adoc
opennms-doc/guide-admin/src/asciidoc/text/provisioning/detectors.adoc
opennms-doc/guide-admin/src/asciidoc/text/service-assurance/configuration.adoc
opennms-doc/guide-admin/src/asciidoc/text/service-assurance/polling-packages.adoc
opennms-doc/guide-admin/src/asciidoc/text/thresholds/thresholding.adoc
opennms-doc/guide-development/src/asciidoc/text/rest/meta-data.adoc

NMS-12702: Fix warning in documentation builds

---

features/alarms/history/elastic/src/main/resources/alarm-template.es7.json

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12718

NMS-12718: Update index_patterns for Alarms History

---

core/schema/src/main/liquibase/27.0.0/changelog.xml
opennms-base-assembly/src/main/filtered/etc/create.sql

* JIRA: https://issues.opennms.org/browse/NMS-12710
This branch is based on NMS-12679, so please merge this PR after NMS-12679 (#3006) has been merged.

NMS-12710: Create SQL index for optimizing poll result lookups

---

container/features/src/main/resources/features.xml
core/daemon/src/main/java/org/opennms/netmgt/daemon/DaemonTools.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12723

NMS-12723: Events forwarded by Kafka Producer doesn't have any parameters set

---

.circleci/config.yml
opennms-container/horizon/Dockerfile

Update the following dependencies:
* OpenJDK 1.8.0.232.b09 -> 1.8.0.252.b09
* Apache Maven 3.6.2 -> 3.6.3
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12699

NMS-12699: Maintenance Docker build environment

---

features/kafka/producer/pom.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/ProtoBufMapperTest.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12725

NMS-12725: Add trouble ticket info to alarms forwarded by Kafka

---

features/remotepollerng/daemon/pom.xml
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePolledService.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java
features/remotepollerng/daemon/src/test/resources/META-INF/opennms/applicationContext-testRemotePollerDaemon.xml
features/remotepollerng/daemon/src/test/resources/poller-configuration-1.xml
features/remotepollerng/daemon/src/test/resources/poller-configuration-2.xml

* JIRA: https://issues.opennms.org/browse/NMS-12678

NMS-12678: added RemotePollerd configuration reloading

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/CollectionResource.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/RemoteLatencyResource.java
features/remotepollerng/daemon/pom.xml
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/main/resources/META-INF/opennms/applicationContext-remotePollerDaemon.xml
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12698

NMS-12698: Use modern collection API for response times

---

.circleci/config.yml
.circleci/scripts/merge-poweredby.sh

This PR configures merging foundation-XXXX to poweredby-XXXX.  Note that poweredby is not yet configured to do any building yet.
JIRA: https://issues.opennms.org/browse/BP-8

BP-8: add poweredby merging

---

features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java

NMS-12740: Update query syntax issue to return expected results
* ~~[ ] If this is a new or updated feature, is there documentation for the new behavior?~~
* ~~[ ] If this is new code, are there unit and/or integration tests?~~
* ~~[ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?~~
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this …

NMS-12740: The ReST end-point for the Flow Exporter details is returning invalid content

---

features/remotepollerng/daemon/pom.xml
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePolledService.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/main/resources/META-INF/opennms/applicationContext-remotePollerDaemon.xml
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java
features/remotepollerng/daemon/src/test/resources/META-INF/opennms/applicationContext-testRemotePollerDaemon.xml
features/remotepollerng/daemon/src/test/resources/poller-configuration-1.xml
features/remotepollerng/daemon/src/test/resources/poller-configuration-2.xml
features/remotepollerng/daemon/src/test/resources/threshd-configuration.xml
features/remotepollerng/daemon/src/test/resources/thresholds.xml

* JIRA: https://issues.opennms.org/browse/NMS-12721

NMS-12721: Apply thresholding for remote poller response times

---

core/upgrade/src/main/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOffline.java
core/web-assets/src/main/assets/js/apps/onms-assets/config.json
features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeAssetSearchProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.vmware/src/main/java/org/opennms/features/topology/plugins/topo/vmware/internal/VmwareTopologyProvider.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCimCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/AbstractVmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareCimMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCimCollectorComplianceTest.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCollectorComplianceTest.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AssetRecordDaoHibernate.java
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAssetRecord.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/README.adoc
opennms-webapp-rest/src/test/resources/v1/nodes.json

cpape/vmware-metadata: Migrated asset data to metadata entries

---

features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java
features/remotepollerng/daemon/src/test/resources/poller-configuration-1.xml
features/remotepollerng/daemon/src/test/resources/poller-configuration-2.xml
opennms-base-assembly/src/main/filtered/etc/events/opennms.remote.poller.events.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/MonitoringLocationsRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MonitoringLocationRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/MonitoringLocationRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MonitoringLocationRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MonitoringLocationsServiceIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12677

NMS-12677: Handle package association

---

container/shared/src/main/resources/etc/org.ops4j.pax.logging.cfg

The purpose of this PR is to add a new logging appender to Minion that can be easily enabled/configured by adding properties to Karaf's system properties file. In containerized Minion configured via confd arbitrary system properties can be added to custom.system.properties and to enable this logging appender the following is expected to be added there:
```
karaf.log.container.threshold=TRACE
karaf.log.container.layout=PatternLayout
karaf.log.container.pattern = {"date": "%date{HH:mm:ss\.SSS}}","level": "%level","thread": "%thread","logger": "%logger","message": "%enc{%msg}{JSON}"%notEmpty{,\"exception": "%enc{%throwable}{JSON}"}}%n
```
I'm not documenting this anywhere as the only intended use case is internally by Dominion presently.
1. update the title of this PR to be of the format: …

CLOUD-74: Access minion logs

---

opennms-base-assembly/src/main/filtered/etc/examples/opennms.conf

Update Java configuration examples which work with JKD 9+ which depecrates a few things especially around logging.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12468

NMS-12468: Update examples for Java configuration for JDK 9+

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/listener/tcp.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/listener/udp.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/bmp.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/ipfix.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/jti.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow9.adoc
opennms-doc/guide-development/src/asciidoc/index.adoc
opennms-doc/guide-development/src/asciidoc/text/dev-guide.adoc
opennms-doc/guide-development/src/asciidoc/text/docs/cheat-sheets.adoc
opennms-doc/guide-development/src/asciidoc/text/docs/images.adoc
opennms-doc/guide-development/src/asciidoc/text/docs/include-source.adoc
opennms-doc/guide-development/src/asciidoc/text/docs/writing.adoc

NMS-12736: Add documentation for TcpListener

---

features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12785

NMS-12785: Only schedule services that are referenced by applications

---

opennms-doc/guide-admin/src/asciidoc/text/elasticsearch/introduction.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12768

NMS-12768: Update doc for elastic configuration

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java

NMS-12776: Update tree to only skip flow processing when boolean set
* ~~[ ] If this is a new or updated feature, is there documentation for the new behavior?~~
* ~~[ ] If this is new code, are there unit and/or integration tests?~~
* ~~[ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?~~
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create …

NMS-12776: Flow last seen db columns not being updated when raw records disabled

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedFlowQueryService.java

* ~~[ ] If this is a new or updated feature, is there documentation for the new behavior?~~
* ~~[ ] If this is new code, are there unit and/or integration tests?~~
* ~~[ ] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?~~
If you have made …

NMS-12761: Correct NPE when no results are found per direction

---

opennms-doc/guide-admin/src/asciidoc/text/events/events.adoc

* ~~[ ] If this is a new or updated feature, is there documentation for the new behavior?~~
* ~~[ ] If this is new code, are there unit and/or integration tests?~~
If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please …

NMS-12795: Support for optional snmpTrapAddress varbind needs documenting

---

opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/configuration.adoc

I've backported the fix the threshold numbering from develop to the next 26.1.3 release. Here is what I did for the backport:
1. Branch from release-26.x
2. `git cherry-pick a6f7fc2fa43357f446636a631f9ff9e37e918e74`
3. Set a PR to release-26.x branch
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12770

NMS-12770: Fix section title sequence for resource-types

---

opennms-doc/guide-admin/src/asciidoc/text/database-reports/database.adoc
opennms-doc/guide-admin/src/asciidoc/text/operation/ssl/ssl.adoc
opennms-doc/guide-admin/src/asciidoc/text/thresholds/thresholding.adoc

NMS-12804: Broken link to Standalone HTTPS with Jetty (docs)
NMS-12803: Missing dashboard to PDF graphic (docs)
NMS-12807: updated thresholding TOC numbering (docs)
If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please …

NMS-12804/NMS-12803/NMS-12807: docs update - Broken link to Standalone HTTPS with Jetty

---

core/db-install/src/main/java/org/opennms/core/db/install/InstallerDb.java
core/test-api/db/src/test/java/org/opennms/core/test/db/InstallerDbIT.java

NMS-12819: Update DBInstaller and Tests to support Postgresql 12
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this …

NMS-12819: Update DBInstaller and Tests to support Postgresql 12

---

opennms-assemblies/xsds/src/assembly/xsds.xml

NMS-12813: include WSMan related config XML schema files in packages

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/support/PropertiesGraphDao.java

* JIRA: https://issues.opennms.org/browse/NMS-10526

NMS-10526: Added better error handling and more helpful error message

---

features/api-layer/src/main/java/org/opennms/features/apilayer/model/mappers/NodeMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/utils/ModelMappers.java
features/api-layer/src/test/java/org/opennms/features/apilayer/utils/ModelMappersTest.java
pom.xml

Expose a few additional properties on the OIA model objects.
Depends on https://github.com/OpenNMS/opennms-integration-api.
Changes are trivial, no JIRA created. DevJam!

OIA: Add some additional properties to the alarm & node objects.

---

core/web-assets/src/main/assets/js/apps/onms-classifications/index.js
core/web-assets/src/main/assets/js/apps/onms-classifications/views/group.html

This PR splits rules in the flow classification UI so they are legible in the group list.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12806

NMS-12806: split comma-separated rules for legibility

---

core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/Interpolator.java
opennms-doc/guide-admin/src/asciidoc/text/meta-data.adoc
opennms-services/src/main/java/org/opennms/netmgt/notifd/BroadcastEventProcessor.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotifdMetaDataIT.java
opennms-webapp/src/main/webapp/admin/notification/noticeWizard/choosePath.jsp

* JIRA: https://issues.opennms.org/browse/NMS-12827

NMS-12827: Allow the use of meta-data in notifications

---

core/commands/pom.xml
core/commands/src/main/java/org/opennms/core/commands/IpAddressRangeCommand.java
core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/FitProfileCommand.java
core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/GetCommand.java
core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/SnmpRequestCommand.java
core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/WalkCommand.java
features/events/shell-commands/pom.xml
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/AlarmListCommand.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/EventListCommand.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/EventSendCommand.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/ReloadDaemonCommand.java
features/events/sink/shell-commands/src/main/java/org/opennms/features/events/sink/dispatcher/EventSendCommand.java
opennms-doc/guide-admin/src/asciidoc/text/provisioning/snmp-profile.adoc
opennms-icmp/commands/src/main/java/org/opennms/netmgt/icmp/commands/PingCommand.java
opennms-icmp/commands/src/main/java/org/opennms/netmgt/icmp/commands/PingSweepCommand.java

* [N/A] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?
At that time, if you have commit access (are an OpenNMS Group employee or a member of …

NMS-12833: Polish Karaf shell commands, add a few new ones

---

features/events/sink/shell-commands/src/main/java/org/opennms/features/events/sink/dispatcher/EventSendCommand.java
smoke-test/src/test/java/org/opennms/smoketest/minion/EventSinkIT.java

* [N/A] If this is new code, are there unit and/or integration tests?
* [N/A] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?
At that time, if you have commit access (are an OpenNMS Group employee or a member …

NMS-12833: Moved send-event Karaf shell command back to correct bundle

---

core/schema/src/main/liquibase/27.0.0/changelog.xml
opennms-base-assembly/src/main/filtered/etc/create.sql
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsApplication.java

* JIRA: https://issues.opennms.org/browse/NMS-12841

NMS-12841: fixed case in broken column names

---

features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogSinkConsumer.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogSinkConsumerNewSuspectIT.java
features/events/syslog/src/test/resources/etc/syslogd-new-suspect-enable-configuration.xml

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12824

NMS-12824: Don't send new suspect events for events with no interface.

---

protocols/xml/src/main/java/org/opennms/protocols/xml/collector/AbstractXmlCollectionHandler.java
protocols/xml/src/test/java/org/opennms/protocols/xml/collector/AbstractXmlCollectionHandlerTest.java

1. Be more strict on the pattern for parameter names we expect to expand. (.* -> \w+)
2. Add test for json content …

NMS-12812: AbstractXmlCollectionHandler.parseString() doesn't handle json content

---

core/web-assets/src/main/assets/js/apps/onms-elementList/monitoringLocation-elementList/index.js
core/web-assets/src/main/assets/js/apps/onms-elementList/monitoringLocation-elementList/main.html

* JIRA: https://issues.opennms.org/browse/NMS-12821

NMS-12821: Removed poller and collection packages from the locations web-ui

---

opennms-base-assembly/src/main/filtered/etc/eventconf.xml
opennms-model/src/main/java/org/opennms/netmgt/model/monitoringLocations/OnmsMonitoringLocation.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/AdminApplicationService.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultAdminApplicationService.java
opennms-webapp/src/main/java/org/opennms/web/controller/ApplicationController.java
opennms-webapp/src/main/resources/org/opennms/web/svclayer/applicationContext-svclayer.xml
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/applications.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editApplication.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/showApplication.jsp

* JIRA: https://issues.opennms.org/browse/NMS-12822

NMS-12822: Modified application UI to reflect model changes

---

opennms-webapp/src/main/java/org/opennms/web/filter/EqualsFilterNullAware.java
opennms-webapp/src/main/java/org/opennms/web/filter/Filter.java
opennms-webapp/src/main/java/org/opennms/web/filter/NotEqualsFilterNullAware.java
opennms-webapp/src/main/java/org/opennms/web/outage/DaoWebOutageRepository.java
opennms-webapp/src/main/java/org/opennms/web/outage/Outage.java
opennms-webapp/src/main/java/org/opennms/web/outage/OutageUtil.java
opennms-webapp/src/main/java/org/opennms/web/outage/SortStyle.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/NegativePerspectiveLocationFilter.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/PerspectiveLocationFilter.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/detail.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/list.jsp
opennms-webapp/src/main/webapp/includes/search-constraints-box.jsp

This PR adds "Perspective" to outage and outage detail view.
Open TODOs:
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12842

NMS-12842: Remote Poller: add remote outages to UI

---

features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultAdminApplicationService.java
opennms-web-api/src/test/java/org/opennms/web/svclayer/support/DefaultAdminApplicationServiceTest.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/MonitoringLocationsRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ApplicationEventUtil.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ApplicationRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/IfServiceRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/ApplicationRestServiceTest.java
opennms-webapp/src/main/resources/org/opennms/web/svclayer/applicationContext-svclayer.xml

Adds events for creation, changing and deletion of an application.
Removes POLLER_PACKAGE_LOCATION_ASSOCIATION_CHANGED_EVENT_UEI
* JIRA: https://issues.opennms.org/browse/NMS-12838

NMS-12838: Add events for new Application Model

---

opennms-doc/guide-admin/src/asciidoc/text/user-management/security-roles.adoc
opennms-web-api/src/main/java/org/opennms/web/api/Authentication.java

* JIRA: https://issues.opennms.org/browse/NMS-12849

NMS-12849: Removed role ROLE_REMOTING

---

opennms-doc/guide-admin/src/asciidoc/text/rmi.adoc
opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/AvailabilityMonitor.adoc
opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/SnmpMonitor.adoc
opennms-doc/guide-install/src/asciidoc/text/minion/introduction.adoc

* JIRA: https://issues.opennms.org/browse/NMS-12850

NMS-12850: removed references to old remote poller from documentation

---

opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdTest.java

NMS-12828: CollectdTest: Add more mocking's so exceptions don't get thrown.

---

features/jmx-config-generator/src/test/java/org/opennms/features/jmxconfiggenerator/jmxconfig/JmxDatacollectionConfiggeneratorTest.java

Update JMX DataCollection Config Generator unit test to build the list of garbage collectors mbeans programmatically. Call System.gc() once to ensure all GC mbean attributes have data. 
[ERROR] testGenerateJmxConfigModelUsingMbeanFilter(org.*******.features.jmxconfiggenerator.jmxconfig.JmxDatacollectionConfiggeneratorTest)  Time elapsed: 0.046 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
at org.*******.features.jmxconfiggenerator.jmxconfig.JmxDatacollectionConfiggeneratorTest.testGenerateJmxConfigModelUsingMbeanFilter(JmxDatacollectionConfiggeneratorTest.java:137)
[ERROR] testGenerateJmxConfigModelUsingMbeanFilter(org.*******.features.jmxconfiggenerator.jmxconfig.JmxDatacollectionConfiggeneratorTest)  Time elapsed: 0.01 s  <<< FAILURE!
java.lang.AssertionError: …

NMS-12829: Fix JMX datacollection config generator test 

---

features/telemetry/protocols/common/src/main/java/org/opennms/netmgt/telemetry/protocols/common/utils/BsonUtils.java

NMS-12830: Remove unused import in BsonUtils

---

features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilHibernateIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ImportSchedulerIT.java

EventUtilHibernateIT and ImportSchedulerIT have dependencies on temporary databases, so add @JUnitTemporaryDatabase to all test methods.
If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a technical writer …

EventUtilHibernateIT and ImportSchedulerIT temp db dependencies

---

pom.xml

Only use jdk tools.jar for java 1.7 up to 9.

---

opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/openconfig.adoc

* [X ] Have you made a comment in that issue which points back to this PR?
* [ X] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [X ] If this is a new or updated feature, is there documentation for the new behavior?
If you have made additions or …

NMS-12857: Add documentation for OpenConfig feature

---

opennms-container/minion/CONFD_README.md
opennms-container/minion/container-fs/confd/conf.d/org.opennms.minion.process-env.toml
opennms-container/minion/container-fs/confd/templates/org.opennms.minion.process-env.tmpl
opennms-container/minion/container-fs/entrypoint.sh

CLOUD-435: configure Java options for Minion process

---

features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/poller/Package.java
opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfig.java
opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java
opennms-services/src/main/java/org/opennms/netmgt/poller/Poller.java
opennms-services/src/test/java/org/opennms/netmgt/mock/MockPollerConfig.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java
opennms-services/src/test/java/org/opennms/netmgt/poller/PollerQueryManagerDaoIT.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12861

NSM-12861: Fix the remote flag

---

opennms-webapp/src/main/java/org/opennms/web/controller/outage/InterfaceOutagesController.java
opennms-webapp/src/main/java/org/opennms/web/controller/outage/NodeOutagesController.java
opennms-webapp/src/main/java/org/opennms/web/controller/outage/ServiceOutagesController.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12866

NMS-12866: Show only native outages in detail pages

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/CollectionResource.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/PerspectiveResponseTimeResource.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
opennms-base-assembly/src/main/filtered/etc/response-graph.properties
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DefaultResourceDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/PerspectiveResponseTimeResourceType.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/ResponseTimeResourceType.java
opennms-tools/groovy-tools/src/main/groovy/fastProvisioner.groovy
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ApplicationStatusRestService.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12868

NMS-12868: Add resource type for perspective response times

---

core/upgrade/src/test/resources/etc/examples/jetty.xml
opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

Otherwise, a reviewer can merge it for you.
Thanks for taking time to contribute! …

NMS-12847: SslContextFactory needs to be changed to SslContextFactory.Server in jetty.xml

---

features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollJob.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/main/resources/META-INF/opennms/applicationContext-remotePollerDaemon.xml
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12869

NMS-12869: Add distributed tracing

---

.circleci/config.yml
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollJob.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePolledService.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/ServiceTracker.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/MonitoringLocationRestServiceIT.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MonitoringLocationRestServiceIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12864

NMS-12864: Remote Poller Cleanup

---

opennms-base-assembly/src/main/filtered/etc/report-templates/subreports/ResponseTimeSummary_subreport.jrxml

NMS-12837: Fix missing calculation to rescale raw latency metric to ms

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.remote.poller.events.xml

* JIRA: https://issues.opennms.org/browse/NMS-12871

NMS-12871: Fixed event definitions for remote poller

---

opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/OutageDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockOutageDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/OutageDaoHibernate.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
opennms-webapp/src/main/java/org/opennms/web/services/ServiceJspUtil.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

This PR adds information about the perspectives (remote polling to the details page of a service) 
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12843

NMS-12843: Remote Poller: add remote polling details to service page

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JAgentConfig.java
core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4jTrapReceiverIT.java
opennms-config-jaxb/src/main/resources/xsds/snmp-config.xsd
opennms-config-jaxb/src/main/resources/xsds/trapd-configuration.xsd
opennms-config/src/test/java/org/opennms/netmgt/config/SnmpEventInfoTest.java
opennms-doc/guide-development/src/asciidoc/text/rest/snmp_configuration.adoc
opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
smoke-test/src/main/resources/opennms-overlay/etc/trapd-configuration.xml
smoke-test/src/test/java/org/opennms/smoketest/SnmpV3IT.java
smoke-test/src/test/java/org/opennms/smoketest/minion/TrapIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12782

NMS-12782: Add SHA2 authentication support for SnmpV3

---

features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePolledService.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/test/resources/poller-configuration-1.xml

* JIRA: https://issues.opennms.org/browse/NMS-12877
Altered the config file in the test-resources, so that the tests also cover this issue now.

NMS-12877: Null-safe handling of rrdRepository

---

container/features/src/main/resources/features-minion.xml
features/minion/dominion/grpc-client/pom.xml

Resolve guava conflicts.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12880

NMS-12880: Fix dominion-grpc-client installation

---

features/timeseries/src/main/resources/META-INF/opennms/applicationContext-timeseries-integration.xml
opennms-doc/guide-admin/src/asciidoc/text/operation/timeseries/configuration.adoc

NMS-12862: updated incorrect TSS setting for ring_buffer_size
* [x ] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [x ] Have you made a comment in that issue which points back to this PR?
* [x ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a …

NMS-12862: Incorrect TSS settings

---

features/remotepollerng/daemon/pom.xml
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/PerspectiveServiceTracker.java
features/remotepollerng/daemon/src/main/java/org/opennms/netmgt/remotepollerng/RemotePollerd.java
features/remotepollerng/daemon/src/test/java/org/opennms/netmgt/remotepollerng/RemotePollerdIT.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SessionUtils.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/DatabasePopulator.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12881

NMS-12881: Clear outages after unscheduling services

---

features/perspectivepoller/src/main/java/org/opennms/netmgt/perspectivepoller/PerspectiveServiceTracker.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/ApplicationDaoHibernate.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12887

NMS-12887: Fix NPE and make updates more resilient

---

features/perspectivepoller/src/test/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerdIT.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/ServicePerspective.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/ApplicationDaoHibernate.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12889

NMS-12889: Fix duplicated key for multi-app services

---

opennms-webapp/src/main/java/org/opennms/web/outage/OutageUtil.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/NegativePerspectiveLocationFilter.java
opennms-webapp/src/main/java/org/opennms/web/outage/filter/PerspectiveLocationFilter.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/detail.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12865

NMS-12865: Use 'native' to clarify 'not remote'

---

opennms-webapp/src/main/java/org/opennms/web/controller/outage/InterfaceOutagesController.java
opennms-webapp/src/main/java/org/opennms/web/controller/outage/NodeOutagesController.java
opennms-webapp/src/main/java/org/opennms/web/controller/outage/ServiceOutagesController.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/interfaceOutages-box.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/serviceOutages-box.jsp
opennms-webapp/src/main/webapp/element/interface.jsp

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12866
This filters out the non-perspective outages from the recent outages view and added some minor improvements/fixes to the outages lists.

NMS-12866: Only show non-perspective outages in recent outages

---

opennms-doc/guide-admin/src/asciidoc/text/application-perspective-monitoring/application-perspective-monitoring.adoc

* [X ] Have you made a comment in that issue which points back to this PR?
* [ X] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a particular person is subject matter expert in the area your PR …

NMS-12893: Additions to Application Perspective Monitoring docs

---

features/api-layer/src/main/java/org/opennms/features/apilayer/model/mappers/NodeMapper.java
features/api-layer/src/main/java/org/opennms/features/apilayer/utils/ModelMappers.java
features/api-layer/src/test/java/org/opennms/features/apilayer/utils/ModelMappersTest.java
pom.xml

No JIRA
Backport OIA version bump commited to release-26.x branch

Backport OIA bump to foundation-2020

---

core/ipc/sink/camel/server/src/main/java/org/opennms/core/ipc/sink/camel/server/CamelMessageConsumerManager.java
core/ipc/sink/camel/server/src/main/java/org/opennms/core/ipc/sink/camel/server/CamelSinkServerProcessor.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12896

NMS-12896: Register JmxReporter only once

---

opennms-base-assembly/src/main/filtered/etc/log4j2.xml

Allow configuring the log level for the Perspective Poller daemon.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12910

NMS-12910: Add perspectivepollerd logging entry

---

opennms-doc/guide-admin/src/asciidoc/text/operation/timeseries/introduction.adoc

NMS-12912: link for In Memory TS plugin was incorrect. Updated it.
* [x ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [x ] Have you made a comment in that issue which points back to this PR?
* [x ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that …

NMS-12912: Update link for In Memory TS plugin

---

features/minion/status/src/test/java/org/opennms/minion/status/MinionStatusTrackerTest.java
opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
opennms-model/src/main/java/org/opennms/netmgt/model/events/DeleteEventVisitor.java
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventUtils.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java

* JIRA: https://issues.opennms.org/browse/NMS-10554

NMS-10554: Added more information to nodeDeleted event

---

opennms-webapp/src/main/webapp/application/index.jsp

Make the node, IP interface, and service a link which opens in a new tab.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12913

NMS-12913: Add links in application status page

---

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/TimeseriesFetchStrategy.java
features/timeseries/src/test/java/org/opennms/netmgt/timeseries/sampleread/TimeseriesFetchStrategyTest.java

Jira: https://issues.opennms.org/browse/NMS-12914

NMS-12914: Nullpointer in Time Series Integration Layer

---

opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
opennms-config/src/test/java/org/opennms/netmgt/config/EventConfMatcherTest.java
opennms-config/src/test/resources/matcher-test.events.xml
opennms-config/src/test/resources/matcher-test.include.events.xml
opennms-config/src/test/resources/matcher-test.override.events.xml

JIRA: https://issues.opennms.org/browse/NMS-12755

NMS-12755: Fix event matching when events for a given UEI are defined across multiple files.

---

opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPoller.java
opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/pollable/PollableInterface.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12902

NMS-12902: Use location when getting snmp config in SnmpInterfacePoller

---

opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/rhel/installing-on-rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/rhel/step-1-install-opennms.adoc
opennms-doc/guide-install/src/asciidoc/text/basic-setup-opennms/rhel/step-2-postgresql.adoc
opennms-doc/guide-install/src/asciidoc/text/compatibility.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/rhel/installing-on-rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/rhel/step-2-install-minion.adoc
opennms-doc/guide-install/src/asciidoc/text/r-statistical-computing.adoc
opennms-doc/guide-install/src/asciidoc/text/sentinel/rhel/rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/sentinel/rhel/step2-install-on-rhel.adoc

* [x ] Have you made a comment in that issue which points back to this PR?
* [ x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a particular person is subject matter expert in the area your PR …

NMS-12891: Install guide RHEL instructions are invalid on RHEL 7 

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/application/summary-box.jsp

Added a link to the Application with pending problems box showing the Application Status.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12921

NMS-12921: Add link in application with pending problems header

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java

Jira https://issues.opennms.org/browse/NMS-12814

NMS-12814: Interfaces incorrectly marked as having flows resulting in no data via Helm

---

opennms-doc/guide-admin/src/asciidoc/text/provisioning/examples.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsIpInterface.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/InterfaceMetadataSettingPolicy.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/NodeMetadataSettingPolicy.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/InterfaceMetadataPolicyTest.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/NodeMetadataPolicyTest.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java

* JIRA: https://issues.opennms.org/browse/NMS-12918
Updates: 
- added policy to add also interface-level metadata.
- changed key and value to required parameters
- changed naming so that metadata parameters are grouped together

NMS-12918: Added policy to add metadata on node-level

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/support/RrdResourceAttributeUtils.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/support/RrdResourceAttributeUtilsTest.java

Customer issue for sorting the list of custom resource graphs alphabetically (accounting for numerical sort in substrings).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/BS-55

BS-55: sort attributes alphanumerically

---

opennms-webapp/src/main/webapp/graph/adhoc2.jsp

Identify Graph All and issue proper error.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12939

NMS-12939: custom resource graph -> graph all -> not supported

---

opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp

NMS-12933: Update copyright date in bootstrap-footer.jsp

---

opennms-base-assembly/src/main/filtered/bin/vmwarecimquery

* JRA: https://issues.opennms.org/browse/NMS-12919

NMS-12919: Fixed vmwarecimquery script

---

features/container/sentinel/src/main/filtered-resources/etc/system.properties

Add support for custom.system.properties on Sentinel
Once the reviewer(s) accept the PR and the branch passes …

NMS-12700: Add support for custom.system.properties on Sentinel

---

opennms-base-assembly/src/main/filtered/bin/opennms

START_TIMEOUT != 0
Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is …

NMS-12966: populate OPENNMS_PID so start works cleanly when START_TIMEOUT != 0

---

opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/installing-on-debian.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/step-1-install-minion.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/step-2-starting-minion.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/rhel/installing-on-rhel.adoc
opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/rhel/step-2-starting-minion.adoc

* [x ] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [x ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a particular person is subject matter expert in the area your PR …

NMS-12917: Update Minion installation documentation

---

features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutage.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/resources/OSGI-INF/blueprint/blueprint.xml

Jira: https://issues.opennms.org/browse/NMS-12897
This PR adds the column Foreign ID to the outage table:

NMS-12897: Filter outages table in Application Topology View

---

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/SSLCertMonitor.java

NMS-12948: SSLCertMonitor should include more details about the expir(ing|ed) certificate in reason codes

---

features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/LegacyApplicationTopologyProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutageDaoContainer.java

* https://issues.opennms.org/browse/NMS-12970
Clicking on a service displays now it's outages:

NMS-12970: Topology Application Map: Outage Table: Clicking on a service should show the outages of the service

---

opennms-services/src/main/java/org/opennms/netmgt/translator/EventTranslator.java

NMS-12956: Event Translator debug logging is incorrect

---

opennms-webapp/pom.xml
opennms-webapp/src/main/webapp/about/index.jsp

NMS-12971: Identify message broker strategies in web "about" page

---

features/topology-map/plugins/org.opennms.features.topology.plugins.topo.vmware/src/main/java/org/opennms/features/topology/plugins/topo/vmware/internal/VmwareTopologyProvider.java
integrations/opennms-vmware/pom.xml
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCimCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/AbstractVmwareMonitor.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCimCollectorComplianceTest.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCollectorComplianceTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12986

NMS-12986: Fixed VMware polling and datacollection

---

core/upgrade/pom.xml
core/upgrade/src/main/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOffline.java
core/upgrade/src/test/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOfflineIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12985
No test included yet. At the moment I have no idea how a test could look like, because the Migrator needs a certain database structure.

NMS-12985: Fixed another typo in VmwareAssetsMigratorOffline

---

core/schema/src/main/liquibase/27.0.1/changelog.xml
core/schema/src/main/liquibase/changelog.xml
core/upgrade/src/test/java/org/opennms/upgrade/implementations/VmwareAssetsMigratorOfflineIT.java

* JIRA: https://issues.opennms.org/browse/NMS-12985

NMS-12985: Added additional liquibase changeset for the VMware asset migration

---

container/features/src/main/resources/features-sentinel.xml
opennms-doc/guide-admin/src/asciidoc/text/opentracing/setup.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12998

NMS-12998: Fix tracing dependency

---

opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/bmp.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/ipfix.adoc
opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/jti.adoc

NMS-13002: Update typo in BMP docs - removed extra 0 from paramaters.port to be consistent with alias.
* [x ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
One or more reviewers should be …

NMS-13002: Update typo in BMP docs

---

features/telemetry/protocols/common/src/main/java/org/opennms/netmgt/telemetry/protocols/common/utils/BsonUtils.java
features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlow.java
features/telemetry/protocols/sflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/BsonDocumentTest.java

NMS-12955: sFlow Ingress / Egress

---

core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AsyncDispatcherImpl.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13015

NMS-13015: Fix NPE while dequeing

---

opennms-container/horizon/CONFD_README.md
opennms-container/horizon/container-fs/confd/conf.d/slack.properties.toml
opennms-container/horizon/container-fs/confd/templates/slack.properties.tpl

NMS-12982: Add Slack confd templates

---

opennms-container/horizon/CONFD_README.md
opennms-container/horizon/container-fs/confd/conf.d/mattermost.properties.toml
opennms-container/horizon/container-fs/confd/templates/mattermost.properties.tpl

NMS-13004: Add Mattermost confd templates

---

features/opennms-es-rest/src/main/java/org/opennms/plugins/elasticsearch/rest/EventToIndex.java
features/opennms-es-rest/src/main/resources/eventsIndexTemplate.es7.json
features/situation-feedback/elastic/src/main/resources/feedback-template.json

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13017

NMS-13017: Use index patterns for events / situation feedback

---

features/reporting/api/src/main/java/org/opennms/api/reporting/parameter/ReportDateParm.java

quick PR to address a serialization issue in Meridian 2020.1.2 and Horizon 27.0.1
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13037

NMS-13037: go back to old serial UID, fix potential ordering issue

---

pom.xml

see https://github.com/AgNO3/jcifs-ng/issues/250#issuecomment-706700044
for details
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13035

NMS-13035: revert to bouncycastle 1.66 for now, 1.67 broke things

---

features/collection/persistence-rrd/src/main/java/org/opennms/netmgt/collection/persistence/rrd/RrdPersistOperationBuilder.java
features/collection/persistence-rrd/src/test/java/org/opennms/features/collection/persistence/rrd/RrdPersistOperationBuilderTest.java

… counter datasources
Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is …

NMS-13007: PrometheusCollector tries to persist non-integer values

---

core/web-assets/package-lock.json
core/web-assets/package.json
core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/services/Synchronize.js
opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/ImportRequisition.java

NMS-13040: updated text for rescan options prompt in UI
* [ x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ x] If this is a new or updated feature, is there documentation for the new …

NMS-13040: updated text for rescan options prompt in UI

---

opennms-container/minion/MINION_CONFIG_SCHEMA_README.md
opennms-container/minion/container-fs/confd/templates/aws-sqs.boot.tmpl
opennms-container/minion/container-fs/confd/templates/confd-telemetry-feature.xml.tmpl
opennms-container/minion/container-fs/confd/templates/custom.system.properties.tmpl
opennms-container/minion/container-fs/confd/templates/disable-jms.boot.tmpl
opennms-container/minion/container-fs/confd/templates/dominion-scv.boot.tmpl
opennms-container/minion/container-fs/confd/templates/grpc.boot.tmpl
opennms-container/minion/container-fs/confd/templates/instance-id.properties.tmpl
opennms-container/minion/container-fs/confd/templates/jaeger.boot.tmpl
opennms-container/minion/container-fs/confd/templates/kafka-rpc.boot.tmpl
opennms-container/minion/container-fs/confd/templates/kafka-sink.boot.tmpl
opennms-container/minion/container-fs/confd/templates/org.apache.karaf.management.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.apache.karaf.shell.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.core.ipc.aws.sqs.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.core.ipc.grpc.client.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.core.ipc.rpc.kafka.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.core.ipc.sink.kafka.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.core.ipc.sink.offheap.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.features.minion.dominion.grpc.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.minion.controller.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.minion.process-env.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.minion.server-certificates.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.netmgt.syslog.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.opennms.netmgt.trapd.cfg.tmpl
opennms-container/minion/container-fs/confd/templates/org.ops4j.pax.web.cfg.tmpl
opennms-container/minion/minion-config-schema.yml

This PR adds a configuration schema document which acts as a source of documentation for the various configuration options that apply to the Minion container. The primary intent of this document is to be used to feed data-driven UI in MaaS but additionally going forward we could also use it to generate some useful documentation.
In this iteration of the document only the keys and labels are described along with their types. Future enhancements will be made to provide descriptions, additional validation, as well as examples.
This PR also enhances the confd template for configuring telemetry allowing additional configuration to be easily supplied in the case of single port listener configuration.
As an FYI, this document is expected to evolve in the following ways in the short to medium …

CLOUD-602: Create schema document describing Minion configuration

---

pom.xml

NMS-13049: PostgreSQL JDBC driver update

---

features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JrobinFetchStrategy.java

* [ Y] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ Y] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [ Y] Have you made a comment in that issue which points back to this PR?
* [Y ] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ N/A] If this is a new or updated feature, is there documentation for the new behavior?
* [ N/A] If this is new code, are there unit …

JRB-32 Limit ds names to 19 chars per RRD spec

---

opennms-container/horizon/Dockerfile
opennms-container/minion/Dockerfile
opennms-container/sentinel/Dockerfile
opennms-doc/guide-install/src/asciidoc/text/r-statistical-computing.adoc

* CentOS 8 base image security update for Horizon and Sentinel
* Update Horizon OpenJDK 11.0.7 -> 11.0.9
* Update Sentinel base image from OpenJDK 11.0.5 -> 11.0.9
* Update Minion Ubuntu base image from Eoan to Focal (LTS) 20201106
* Update Minion OpenJDK from 11.0.7 -> 11.0.9
I've split the build environment updates from the Docker container image updates to make it easier to back port or revert :)

Update Container Base Images

---

core/schema/src/main/liquibase/27.0.4/changelog.xml
core/schema/src/main/liquibase/changelog.xml

* [ Y] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ Y] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [ Y] Have you made a comment in that issue which points back to this PR?
* [ Y] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ NA] If this is a new or updated feature, is there documentation for the new behavior?
* [ NA] If this is new code, are there unit …

NMS-12976: Alter column snmpifdescr to 'text'

---

pom.xml

* JIRA: https://issues.opennms.org/browse/NMS-13079

NMS-13079: Changed version for frontend-maven-plugin to 1.11.0 to fix compilation 404 error

---

opennms-base-assembly/src/main/filtered/bin/vmwareconfigbuilder

* JIRA: https://issues.opennms.org/browse/NMS-13084

NMS-13084: Fixed vmwareconfigbuilder script

---

tools/packages/opennms/opennms.spec

NMS-13083: Update opennms.spec to use maven smart builder plugin
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this …

NMS-13083: Update opennms.spec to use maven smart builder plugin

---

core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Starter.java

* [ Y] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ Y] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [ Y] Have you made a comment in that issue which points back to this PR?
* [ Y] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ NA] If this is a new or updated feature, is there documentation for the new behavior?
* [ NA] If this is new code, are there unit …

NMS-13081: Optionally silence warnings for JRRD,JICMP not found

---

opennms-base-assembly/src/main/filtered/bin/checkwmi
opennms-wmi/src/main/java/org/opennms/netmgt/collectd/WmiCollector.java
opennms-wmi/src/main/java/org/opennms/netmgt/collectd/wmi/WmiResourceTypeListWrapper.java
opennms-wmi/src/test/java/org/opennms/netmgt/collectd/WmiCollectorComplianceTest.java

* JIRA: https://issues.opennms.org/browse/NMS-12944

NMS-12944: Make WmiCollector work on the Minion

---

container/features/src/main/resources/features.xml
core/test-api/kafka/pom.xml
features/flows/itests/pom.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/KafkaAlarmDataSync.java
pom.xml
smoke-test/pom.xml
smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java

NMS-12704: Upgrade Kafka components and dependencies to 2.7.0
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, …

NMS-12704: Upgrade Kafka components and dependencies to 2.7.0

---

features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/SampleDatagramEnricher.java

NMS-13093: fix sflow enrichment

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NMS12990_IT.java
opennms-provision/opennms-provisiond/src/test/resources/NMS-12990.xml

* JIRA: https://issues.opennms.org/browse/NMS-12990

NMS-12990: preserve metadata when dbonly is used

---

core/ipc/common/kafka/src/main/java/org/opennms/core/ipc/common/kafka/KafkaTopicProvider.java
core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcServerManager.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaIT.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaWithSingleTopicIT.java
core/sysprops/src/main/java/org/opennms/core/sysprops/SystemProperties.java
opennms-doc/guide-install/src/asciidoc/text/minion-custom-messaging-system/setup-kafka/tuning-kafka.adoc
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13104

NMS-13104: Enable single topic by default for Kafka RPC

---

features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/JEXL.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IpInterfaceScan.java
opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/JMXMonitor.java
opennms-services/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java
opennms-util/pom.xml
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlEngine.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlSandbox.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlUberspect.java
opennms-util/src/test/java/org/opennms/core/utils/jexl/OnmsJexlEngineTest.java
opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java
pom.xml

Fixes for foundation-2016.
* JIRA: https://issues.opennms.org/browse/NMS-13103

NMS-13103: Sandboxing Jexl2 expression engine (foundation-2016)

---

features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/JEXL.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JMXMonitor.java
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IpInterfaceScan.java
opennms-services/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java
opennms-util/pom.xml
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlEngine.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlSandbox.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlUberspect.java
opennms-util/src/test/java/org/opennms/core/utils/jexl/OnmsJexlEngineTest.java
opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java
pom.xml

Fixes for foundation-2017.
* JIRA: https://issues.opennms.org/browse/NMS-13103

NMS-13103: Sandboxing Jexl2 expression engine (foundation-2017)

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/JexlIndexStorageStrategy.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/ObjectNameStorageStrategy.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/JEXL.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JMXMonitor.java
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IpInterfaceScan.java
opennms-services/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java
opennms-services/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java
opennms-util/pom.xml
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlEngine.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlSandbox.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlUberspect.java
opennms-util/src/test/java/org/opennms/core/utils/jexl/OnmsJexlEngineTest.java
opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java

Fixes for foundation-2018.
* JIRA: https://issues.opennms.org/browse/NMS-13103

NMS-13103: Sandboxing Jexl2 expression engine (foundation-2018)

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/JexlIndexStorageStrategy.java
features/collection/api/src/main/java/org/opennms/netmgt/collection/support/ObjectNameStorageStrategy.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java
features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/StressCommand.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/filters/impl/JEXL.java
features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngine.java
features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JEXLExpressionEngineTest.java
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JMXMonitor.java
features/reporting/jasper-reports/src/main/java/org/opennms/reporting/jasperreports/svclayer/JasperReportService.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IpInterfaceScan.java
opennms-util/pom.xml
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlEngine.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlSandbox.java
opennms-util/src/main/java/org/opennms/core/utils/jexl/OnmsJexlUberspect.java
opennms-util/src/test/java/org/opennms/core/utils/jexl/OnmsJexlEngineTest.java
opennms-webapp/src/main/java/org/opennms/web/controller/GraphResultsController.java

Fixes for foundation-2019.
* JIRA: https://issues.opennms.org/browse/NMS-13103

NMS-13103: Sandboxing Jexl2 expression engine (foundation-2019)

---

opennms-services/src/main/java/org/opennms/netmgt/poller/monitors/JMXMonitor.java

The important bit is `JEXL_ENGINE.white(String.class.getName());` to allow doing something like this:
```
<service name="JMX-BeanValue-Test" interval="30000" user-defined="false" status="on">
<parameter key="port" value="18980"/>
<parameter key="retry" value="2"/>
<parameter key="timeout" value="3000"/>
<parameter key="username" value="admin"/>
<parameter key="password" value="admin"/>
<parameter key="beans.jettyServer" value="OpenNMS:Name=JettyServer"/>
<parameter key="tests.isConnected" value="jettyServer.get(&quot;ServerText&quot;).equals(&quot;RUNNING&quot;)"/>
</service>
```
I also added some logging/exceptions to make it easier to figure out why a JEXL test fails.

NMS-13103: fix ability to do .equals() comparisons of bean attributes

---

opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java
opennms-webapp/src/test/java/org/opennms/web/event/NMS12517_Test.java

* JIRA: https://issues.opennms.org/browse/NMS-12517

NMS-12517: Allow single quotes in event search

---

opennms-container/minion/minion-config-schema.yml

1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: the subject of pull request`
Adding reasonable descriptions and examples to our Minion configuration schema.
* Configuration for `/ipc/grpc/host-with-port` is split into `/ipc/grpc/host` and `/ipc/grpc/port`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/CLOUD-833

CLOUD-833: Replace todos and examples in our Minion configuration schema

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowQueryService.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedFlowQueryService.java

Backport of #3265.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13065

NMS-13065: Resolve hostname only once

---

opennms-services/src/main/java/org/opennms/netmgt/vacuumd/Vacuumd.java

Log the Vacuumd automation error.
Once the reviewer(s) accept the PR and the branch passes continuous integration, …

NMS-13098: log the Vacuumd automation error.

---

opennms-model/src/main/java/org/opennms/netmgt/model/OnmsIpInterface.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoredService.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/MetaDataIT.java
opennms-provision/opennms-provisiond/src/test/resources/NMS-13118-1.xml
opennms-provision/opennms-provisiond/src/test/resources/NMS-13118-2.xml

* JIRA: https://issues.opennms.org/browse/NMS-13118
* JIRA: https://issues.opennms.org/browse/NMS-13109

NMS-13118/NMS-13109: Modified handling of meta-data

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultPluginRegistry.java

* JIRA: https://issues.opennms.org/browse/NMS-12834

NMS-12834: Added error logging for broken policy definitions

---

opennms-web-api/src/main/java/org/opennms/web/svclayer/model/NodeListCommand.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultNodeListService.java
opennms-webapp/src/main/webapp/element/index.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13129

NMS-13129: Added CDP/LLDP search option

---

core/lib/src/main/java/org/opennms/core/daemon/DaemonReloadEnum.java
smoke-test/src/test/java/org/opennms/smoketest/ReloadDaemonIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13117

NMS-13117: Added smoke test to verify the reloading of daemons

---

opennms-webapp/src/main/java/org/opennms/web/controller/event/EventController.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
opennms-webapp/src/main/webapp/errors/eventidnotfound.jsp
smoke-test/src/test/java/org/opennms/smoketest/EventsPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13148

NMS-13148: Fixed event exception

---

core/web-assets/src/main/assets/js/apps/timeline-resize/index.js
core/web-assets/src/main/assets/style/availability.scss
core/web-assets/src/main/assets/style/opennms-theme.scss
opennms-webapp/src/main/webapp/includes/interfaceAvailability-box.jsp
opennms-webapp/src/main/webapp/includes/nodeAvailability-box.jsp
opennms-webapp/src/main/webapp/includes/serviceAvailability-box.jsp

This PR fixes timeline resizing, and also changes the table calculations a bit to maximize space.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13153

NMS-13153: fix timeline resizing to work when window changes

---

opennms-doc/guide-admin/src/asciidoc/text/bsm/operational-status.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/collectors/snmp/SnmpCollector.adoc
opennms-doc/guide-admin/src/asciidoc/text/performance-data-collection/introduction.adoc
opennms-doc/guide-admin/src/asciidoc/text/thresholds/thresholding.adoc

NMS-13107: add snmp data collection example to docs. Correcting a revert done by mistake. 
Once the reviewer(s) …

NMS-13107: add snmp data collection example to docs

---

opennms-doc/guide-admin/src/asciidoc/text/thresholds/thresholding.adoc
opennms-services/src/test/java/org/opennms/netmgt/vacuumd/TransactionTest.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/list.jsp
smoke-test/src/test/java/org/opennms/smoketest/ThresholdEditorIT.java

A minor issue. Rename button name. 
Once the reviewer(s) accept the PR and the branch passes continuous integration, …

NMS-12606: button rename

---

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionInterface.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/RequisitionRestServiceIT.java

https://issues.opennms.org/browse/NMS-12739
Once the reviewer(s) accept the PR and the branch passes continuous …

NMS-12739: Don't allow to import a requisition with same service names.

---

opennms-doc/guide-admin/src/asciidoc/text/user-management/user-config.adoc
opennms-doc/guide-admin/src/asciidoc/text/user-management/user-groups.adoc
opennms-webapp/src/main/java/org/opennms/web/admin/users/AddNewUserServlet.java
opennms-webapp/src/main/java/org/opennms/web/admin/users/RenameUserServlet.java
opennms-webapp/src/main/java/org/opennms/web/controller/admin/group/GroupController.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/list.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/newGroup.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/list.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/newUser.jsp
smoke-test/src/test/java/org/opennms/smoketest/UserIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13125

NMS-13125: user ID and group ID must not contain any HTML markup

---

opennms-webapp/src/main/webapp/includes/listSize.jsp
opennms-webapp/src/main/webapp/includes/resultsIndex.jsp
opennms-webapp/src/main/webapp/includes/resultsIndexNoCount.jsp

This PR adds a pull-down for changing the page limit on alarms, events, notifications, and outages.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13137

NMS-13137: add UI for setting page limits

---

opennms-doc/guide-admin/src/asciidoc/text/provisioning/introduction.adoc

NMS-12666: removed error in provisioning chapter.
Once the reviewer(s) accept the PR and the branch passes continuous …

NMS-12666: updating core docs

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13167

NMS-13167: Don't drop messages, resend the record for events.

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13185

NMS-13185: Add Interface instance as String attribute

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/groupDetail.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/list.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/modifyGroup.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/detail.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/list.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/userDetail.jsp
opennms-webapp/src/main/webapp/notification/detail.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13125

NMS-13125: Escape userId & groupId

---

opennms-model/src/main/java/org/opennms/netmgt/model/LldpElement.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
opennms-services/src/test/java/org/opennms/netmgt/nb/Nms0001NetworkBuilder.java
opennms-services/src/test/java/org/opennms/netmgt/nb/NmsNetworkBuilder.java

This PR fixes some NPEs we saw in CircleCI tests (example [here](https://app.circleci.com/pipelines/github/OpenNMS/opennms/9359/workflows/f706b6af-27ae-41f3-83a1-34e9f26bf620/jobs/51879))

fix NPE in linkd tests

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/CollectionSetProtos.java
features/kafka/producer/src/main/proto/collectionset.proto
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/CollectionSetMapperTest.java

Also ignore resources without instance for InterfaceResource.
This PR will correct the Interface Instance and add InterfaceLabel as String attribute.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13185

NMS-13185: Add ifIndex for InterfaceResource

---

opennms-doc/guide-admin/src/asciidoc/index.adoc
opennms-doc/guide-admin/src/asciidoc/text/events/event-sources.adoc
opennms-doc/guide-admin/src/asciidoc/text/events/event-translator.adoc

* [ x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
If you know that a particular person is subject matter expert in the area your PR …

NMS-13121: Document the Event Translator

---

opennms-config/src/main/java/org/opennms/netmgt/config/UserManager.java
opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/list.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/modifyGroup.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/userGroupView/groups/newGroup.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/roles/editDetails.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/roles/editSpecific.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/roles/list.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/roles/view.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/list.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/newPassword.jsp
opennms-webapp/src/main/webapp/admin/userGroupView/users/newUser.jsp
smoke-test/src/test/java/org/opennms/smoketest/UserIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13124

NMS-13124: Fixed user deletion by renaming bug and CSRF privilege escalation issue

---

features/wsman/src/main/java/org/opennms/netmgt/collectd/WsManCollector.java

* JIRA: https://issues.opennms.org/browse/NMS-13183

NMS-13183: Remove password-related log output in WsManCollector

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/notification/noticeWizard/eventNotices.jsp
opennms-webapp/src/main/webapp/admin/notification/noticeWizard/choosePath.jsp
smoke-test/src/test/java/org/opennms/smoketest/NotificationsPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13123

NMS-13123: Prevent HTML markup in notification wizard

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
opennms-config/src/main/java/org/opennms/netmgt/config/DefaultEventConfDao.java

JIRA: https://issues.opennms.org/browse/NMS-13211
A couple changes to improve event forwarding performance:
1) Use a threaded event listener - which allows the map from event -> protobuf to be performed in parallel
2) Leverage the event by UEI index to speed up retrieving the event labels

NMS-13211: Improve Event forwarding performance for Kafka producer

---

features/bsm/rest/impl/pom.xml
features/measurements/rest/pom.xml
features/rest/model/pom.xml
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/BridgeElementNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/BridgeLinkNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/BridgeLinkRemoteNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/CdpElementNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/CdpLinkNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/EnlinkdDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/IsisElementNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/IsisLinkNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/LldpElementNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/LldpLinkNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/OspfElementNodeDTO.java
features/rest/model/src/main/java/org/opennms/web/rest/model/v2/OspfLinkNodeDTO.java
features/status/rest/pom.xml
opennms-doc/guide-development/src/asciidoc/index.adoc
opennms-doc/guide-development/src/asciidoc/text/rest/node_links.adoc
opennms-webapp-rest/pom.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/api/NodeLinkRestApi.java
opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-svclayer.xml
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeLinkRestServiceIT.java

Hey Ben, I did cherry-pick and set to merge to release-27.x, no code conflict, all CI tests passed.  Please double-check I didn't miss something.  
If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a …

NNM-13124 backport enlinkd rest

---

container/features/src/main/resources/features.xml
features/ticketing/inmemory/pom.xml
features/ticketing/inmemory/src/main/java/org/opennms/features/ticketing/inmemory/InMemoryTicketMapper.java
features/ticketing/inmemory/src/main/java/org/opennms/features/ticketing/inmemory/InMemoryTicketerPlugin.java
features/ticketing/inmemory/src/main/java/org/opennms/features/ticketing/inmemory/InMemoryTicketerShellCommand.java
features/ticketing/inmemory/src/main/java/org/opennms/features/ticketing/inmemory/TicketMapper.java
features/ticketing/inmemory/src/main/java/org/opennms/features/ticketing/inmemory/TicketStateNameCompleter.java
features/ticketing/inmemory/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/ticketing/pom.xml
opennms-doc/guide-development/src/asciidoc/index.adoc
opennms-doc/guide-development/src/asciidoc/text/ticketing/inmemory-plugin.adoc
opennms-full-assembly/pom.xml

Add InMemory Ticketing Plugin to make it easier to debug ticketing workflow.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13218

NMS-13218: Add InMemory Ticketing Plugin

---

opennms-webapp-rest/pom.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/api/NodeLinkRestApi.java
opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/OpenApiIT.java
pom.xml

Use the URL below can get to the standard openapi doc page:
http://localhost:8980/opennms/api/v2/openapi.json
Use the URL below can get to the swagger ui page
http://localhost:8980/opennms/api/v2/api-docs/?url=/opennms/api/v2/openapi.json#/
All v2 restful endpoints are automatically scanned:
We can make rest call on the swagger UI directly:
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create …

NMS-13187 Add Open API doc and Swagger UI to v2 RESTful API

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/Win32ServiceDetector.adoc

NMS-13074: Win32ServiceDetector documentation

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/BgpSessionDetector.adoc

NMS-13076: BgpSessionDetector documenation

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/WmiDetector.adoc

NMS-13075: WmiDetector documentation

---

features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceEdgeEditWindow.java

* JIRA: https://issues.opennms.org/browse/NMS-12697

NMS-12697: Allow to edit existing BSM edges

---

opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

… 1.1 support
Once the reviewer(s) accept the PR and the branch passes continuous integration, the PR is eligible for …

NMS-10256: Change Jetty default settings to eliminate TLS 1.0 and TLS 1.1

---

opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml

NMS-13227: Change Jetty default settings to exclude vulnerable cipher suites, expose client-initiated renegotiation

---

opennms-config/src/main/java/org/opennms/netmgt/config/UserManager.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13207

NMS-13207: Improve performance for checking salted passwords

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editCategory.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editNodeCategories.jsp
opennms-webapp/src/main/webapp/WEB-INF/jsp/includes/nodeCategory-box.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13228

NMS-13228: Sanitizing category name in Web UI

---

features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/StressCommand.java

Clean up help for opennms:stress-metrics, add example for --rra

---

features/minion/heartbeat/consumer/pom.xml
features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
features/minion/heartbeat/consumer/src/main/resources/META-INF/opennms/component-service.xml
features/minion/heartbeat/consumer/src/test/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumerIT.java

Move provisioning to separate thread.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13232

NMS-13232: Fix lag in handling minion heartbeat

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java

There is a typo. It's fixed now.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13258

NMS-13258 Fix LLDP rest api miss local port info.

---

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java

Cherry-pick the changes in pull request https://github.com/OpenNMS/opennms/pull/3384  to branch release-27.x
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13258

jira/NMS-13258 fix LLDP rest api miss local port.

---

opennms-container/minion/minion-config-schema.yml

NMS-13255: updated content based on feedback. contenxt sensitive help for the feature profile screen in cloud.
Once …

NMS-13255: Provide documentation for context-sensitive help in UI form

---

core/ipc/common/kafka/src/main/java/org/opennms/core/ipc/common/kafka/KafkaTopicProvider.java
core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcServerManager.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaIT.java
core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaWithSingleTopicIT.java
core/sysprops/src/main/java/org/opennms/core/sysprops/SystemProperties.java
opennms-doc/guide-install/src/asciidoc/text/minion-custom-messaging-system/setup-kafka/tuning-kafka.adoc
opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13184

NMS-13184: Backport  Kafka Single topic RPC related changes

---

integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCimCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareCimMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java
integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePool.java
integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/ServiceInstancePoolEntry.java
integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/vmware/VmwareTimeoutTest.java
integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/vmware/VmwareViJavaAccessTest.java
integrations/opennms-vmware/src/test/java/org/opennms/protocols/vmware/ServiceInstancePoolTest.java

* JIRA: https://issues.opennms.org/browse/NMS-13234

NMS-13234: Apply timeout while connecting to VMware vCenter servers

---

opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml
opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
opennms-webapp/src/main/webapp/support/about.jsp

NMS-13160: Changing UI footers from 2020 to 2021

---

opennms-webapp/src/main/webapp/includes/help-contact.jsp
opennms-webapp/src/main/webapp/includes/help-documentation.jsp
opennms-webapp/src/main/webapp/includes/help-software-management.jsp

Backport the Antora part of NMS-13225 to the foundation-2021 branch. 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13225

NMS-13225 Update the Antora link in Help page

---

smoke-test/src/test/java/org/opennms/smoketest/HelpPageIT.java

Update the smoke test code for the help page
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13225

NMS-13225 Update the smoke test code for the help page

---

features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlow.java
features/telemetry/protocols/sflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowConverterTest.java
features/telemetry/protocols/sflow/adapter/src/test/resources/sflow.json

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13235

NMS-13235: Fix parsing of extended sflow format

---

.circleci/scripts/clean-m2.sh
.circleci/scripts/itest.sh
.circleci/scripts/smoke.sh
opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13259

NMS-13259: Fixed sidebar

---

opennms-webapp/src/main/java/org/opennms/web/admin/notification/noticeWizard/NotificationWizardServlet.java
opennms-webapp/src/main/webapp/admin/notification/noticeWizard/choosePath.jsp

* JIRA: https://issues.opennms.org/browse/NMS-8581

NMS-8581: Allow to specify parameters when configuring notifications

---

opennms-webapp/src/main/webapp/errors/eventidnotfound.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13229

NMS-13229: Escaped incorrect event Id and error message

---

container/karaf/pom.xml
container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
features/api-layer/src/main/java/org/opennms/features/apilayer/config/ConfigExtensionManager.java
features/graph/provider/topology/src/main/java/org/opennms/netmgt/graph/provider/topology/GraphContainerProviderManager.java
features/graph/service/src/main/java/org/opennms/netmgt/graph/search/DefaultGraphSearchService.java
opennms-config/src/main/resources/META-INF/opennms/applicationContext-commonConfigs.xml

* The karaf-extender feature is also included in `container/features/src/main/resources/features.xml` -> the `karaf-extensions.xml` must not be configured for OpenNMS.
* Fixes a logger class

no-jira: remove karaf-extensions repo; minor fixes

---

container/karaf/src/main/filtered-resources/features/features.xml
pom.xml

Note: this PR already passed previously as [ranger/update-commons-io-smoke](https://app.circleci.com/pipelines/github/OpenNMS/opennms/10044/workflows/87537e6d-6abd-4055-bcc6-159fc4dbed3a)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13279

bump commons-io to 2.8.0

---

opennms-container/minion/minion-config-schema.yml

Update an example - the type must be string (array of strings is not supported). Update the version.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13272

NMS-13272: minion-config-schema.yml java agent example as a string

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.internal.events.xml

NMS-13063: applicationChanged/Created events are missing

---

features/minion/runInPlace.sh
features/sentinel/runInPlace.sh

NMS-13223: fix org.opennms.netmgt.syslog.cfg reference

---

opennms-webapp/src/main/webapp/admin/userGroupView/roles/view.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13287

NMS-13287: Added required CSRF tokens to forms

---

opennms-webapp/src/main/webapp/admin/snmpInterfaces.jsp

NMS-13308: Validate query parameters in snmpInterfaces.jsp

---

opennms-webapp/src/main/java/org/opennms/web/admin/notification/DestinationWizardServlet.java

NMS-13309: Validate name parameter in DestinationWizardServlet

---

docs/modules/ROOT/pages/index.adoc

- Made reference to Meridian in Welcome section conditional on being in
a Horizon build; flip it to reference Horizon when building Meridian
- Replaced a use of "platform" by "core" when talking about the main JVM
which hosts the service daemons
If you have made additions or changes to …

NMS-13321: Docs should refer to Horizon / Meridian conditionally

---

docs/modules/operation/pages/service-assurance/monitors/PageSequenceMonitor.adoc

NMS-13260 expand <PAGE> docs for PSM

---

docs/modules/operation/pages/performance-data-collection/collectors/prometheus.adoc

Fix formatting and add suggested default URL value
Once the reviewer(s) accept the PR and the branch passes …

NMS-13267 PrometheusCollector docs fix

---

opennms-webapp/src/main/java/org/opennms/web/element/ElementUtil.java

* JIRA: https://issues.opennms.org/browse/NMS-13158

NMS-13158: Allow foreign source / foreign id to be used in ElementUtil

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/RawFlowQueryService.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/SearchQueryProvider.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedFlowQueryService.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedSearchQueryProvider.java
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/agg/all_terms.ftl
features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/field_values_for_all.ftl

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13333

NMS-13333: enumerate all dscp values (and not only 10)

---

core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java
pom.xml

NMS-13264: Upgrade Kafka components to 2.8.0
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise …

NMS-13264: Upgrade Kafka components to 2.8.0

---

docs/modules/operation/pages/elasticsearch/introduction.adoc
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-jmx-fd-graph.properties

NMS-13344 documentation typos

---

opennms-web-api/src/main/java/org/opennms/web/category/AvailabilityMonitoredService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AvailabilityRestService.java
opennms-webapp-rest/src/test/resources/v1/availability_node.json

This add the current service status to the result output of the
availability REST API.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13238

NMS-13238: Current service status in availability API

---

docs/modules/releasenotes/pages/whatsnew.adoc

NMS-13351: release notes display issue

---

docs/modules/operation/pages/service-assurance/monitors/PageSequenceMonitor.adoc

NMS-13260: Expand PSM docs

---

docs/modules/operation/pages/service-assurance/monitors/PageSequenceMonitor.adoc

This is fixing a conflict made by previous PRs on this JIRA.
Otherwise, a reviewer can merge it for you.
Thanks …

NSM-13260: merge conflict fix

---

core/health/rest/src/main/resources/health-check.yaml
core/health/rest/src/main/resources/openapi/health-check-api.yaml

Add OpenAPI doc for health-check
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13319

NMS-13319: Add OpenAPI doc for health-check

---

docs/modules/deployment/pages/sentinel/flow-processing.adoc
docs/modules/deployment/pages/sentinel/message-broker/kafka.adoc
docs/modules/operation/pages/bsm/business-service-definition.adoc
docs/modules/operation/pages/bsm/business-service-hierarchy.adoc
docs/modules/reference/nav.adoc
docs/modules/reference/pages/configuration/minion-confd/jmx-exporter.adoc
docs/modules/reference/pages/configuration/minion-confd/minion-confd.adoc
docs/modules/reference/pages/configuration/minion-confd/test-confd.adoc
docs/modules/reference/pages/configuration/minion-docker.adoc

NMS-13330: Add out of band monitoring content to main user documentation

---

pom.xml

NMS-13320: wmi dep update

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/HostResourceSWRunDetector.adoc

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13340

NMS-13340: Add HostResourceSWRunDetector docs

---

core/ipc/rpc/shell-commands/src/main/java/org/opennms/core/rpc/commands/MetaCommand.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EmptyScope.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderImpl.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/FallbackScope.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/Interpolator.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/MapScope.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/ObjectScope.java
core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/Scope.java
core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderIT.java
core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/RpcMetaDataUtilsTest.java
docs/modules/operation/pages/meta-data.adoc
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/BaseThresholdDefConfigWrapper.java
features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdStateIT.java
features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestBuilderImpl.java
features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/MetaTagDataLoader.java
opennms-services/src/main/java/org/opennms/netmgt/notifd/BroadcastEventProcessor.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13179

NMS-13179: Reworked Interpolator results

---

docs/modules/operation/pages/database-reports/database.adoc
docs/modules/releasenotes/pages/changelog.adoc

HELM-265: Cannot use grafana-image-renderer with Helm's Docker image

---

docs/modules/development/pages/rest/meta-data.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsIpInterface.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoredService.java
opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/MetaDataIT.java
opennms-provision/opennms-provisiond/src/test/resources/NMS-13118-1.xml
opennms-provision/opennms-provisiond/src/test/resources/NMS-13118-2.xml
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MetadataRestIT.java

Reverts OpenNMS/opennms#3451 due to failing tests

Revert "NMS-13314: Prevent meta-data modification"

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13365

NMS-13365: Added info icon to service.jsp

---

opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml

This fix the version part of the Jira.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13354

NMS-13354: add version to OpenAPI doc info section

---

opennms-container/minion/container-fs/entrypoint.sh
smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java
smoke-test/src/main/java/org/opennms/smoketest/stacks/StackModel.java
smoke-test/src/test/java/org/opennms/smoketest/minion/MinionStartupIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13347

NMS-13347: Fixed Minion entrypoint.sh

---

docs/modules/development/pages/docs/introduction.adoc
docs/modules/development/pages/docs/migrating-from-wiki.adoc

NMS-13335: Upate intro to Develop Documentation section of Developer guide

---

opennms-webapp/src/main/webapp/admin/notification/noticeWizard/choosePath.jsp

NMS-11790: Add additional fields to notif web UI

---

core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/Interpolator.java
core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/RpcMetaDataUtilsTest.java
core/ipc/rpc/utils/src/test/resources/page-sequence.xml
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/pagesequence/Page.java
opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/pagesequence/Parameter.java
opennms-config-jaxb/src/main/resources/xsds/page-sequence.xsd

* JIRA: https://issues.opennms.org/browse/NMS-13257

NMS-13257: Interpolate meta-data for objects

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/DnsDetector.adoc

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13338

NMS-13338: Add DnsDetector docs

---

docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
docs/modules/deployment/pages/minion/centos-rhel7/install-minion.adoc
docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
docs/modules/deployment/pages/minion/message-broker/grpc.adoc
docs/modules/deployment/pages/minion/message-broker/kafka.adoc
docs/modules/deployment/pages/repos/rhel-centos/horizon-rhel7.adoc
docs/modules/deployment/pages/repos/rhel-centos/horizon-rhel8.adoc
docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel7.adoc
docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel8.adoc
docs/modules/deployment/pages/sentinel/runtime/centos-rhel7/install-sentinel.adoc
docs/modules/deployment/pages/sentinel/runtime/centos-rhel8/install-sentinel.adoc

Adding Meridian repository description for Minion and Sentinel.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13294

NMS-13294: Add Meridian repository description for Minion and Sentinel

---

opennms-base-assembly/src/main/filtered/etc/events/opennms.bsm.events.xml

NMS-13173: Add operator instructions for graphInvalidated

---

docs/modules/deployment/pages/core/debian/install-core.adoc
docs/modules/deployment/pages/core/message-broker/kafka.adoc
docs/modules/deployment/pages/core/ubuntu/install-core.adoc
docs/modules/deployment/pages/minion/centos-rhel/secure-karaf.adoc
docs/modules/deployment/pages/minion/centos-rhel7/install-minion.adoc
docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
docs/modules/deployment/pages/minion/debian-ubuntu/secure-karaf.adoc
docs/modules/deployment/pages/minion/debian/install-minion.adoc
docs/modules/deployment/pages/minion/docker/minion.adoc
docs/modules/deployment/pages/minion/docker/secure-karaf.adoc
docs/modules/deployment/pages/minion/install.adoc
docs/modules/deployment/pages/minion/installing-jdbc-driver.adoc
docs/modules/deployment/pages/minion/introduction.adoc
docs/modules/deployment/pages/minion/message-broker/activemq.adoc
docs/modules/deployment/pages/minion/message-broker/aws-sqs.adoc
docs/modules/deployment/pages/minion/message-broker/grpc.adoc
docs/modules/deployment/pages/minion/message-broker/kafka.adoc
docs/modules/deployment/pages/minion/off-heap-storage.adoc
docs/modules/deployment/pages/minion/system-requirements.adoc
docs/modules/deployment/pages/minion/ubuntu/install-minion.adoc
docs/modules/deployment/pages/sentinel/runtime/debian/install-sentinel.adoc
docs/modules/deployment/pages/sentinel/runtime/install.adoc
docs/modules/deployment/pages/sentinel/runtime/ubuntu/install-sentinel.adoc
docs/modules/operation/pages/performance-data-collection/collectors/jdbc.adoc

NMS-13251: Proofread Minion content in deployment guide

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/FtpDetector.adoc

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13339

NMS-13339: Add FtpDetector docs

---

docs/modules/operation/pages/service-assurance/monitors/HostResourceSwRunMonitor.adoc

NMS-10538: correct capitalization of hrSWRun* in docs

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/provisioning/detectors/BsfDetector.adoc

* [] If this is new code, are there unit and/or integration tests?
Once the reviewer(s) accept the PR and the branch …

NMS-13073: BsfDetector documentation

---

features/juniper-tca-collector/pom.xml
features/juniper-tca-collector/src/main/java/org/opennms/netmgt/collectd/tca/TcaCollectionHandler.java
features/juniper-tca-collector/src/main/java/org/opennms/netmgt/collectd/tca/TcaCollector.java
features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaCollectionHandlerTest.java
features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaCollectorComplianceIT.java
features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaCollectorIT.java
features/juniper-tca-collector/src/test/resources/META-INF/opennms/junit-component-dao.xml
integrations/opennms-vtdxml-collector-handler/src/main/java/org/opennms/protocols/xml/vtdxml/Sftp3gppVTDXmlCollectionHandler.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/ResourceStorageDao.java
protocols/xml/pom.xml
protocols/xml/src/main/java/org/opennms/protocols/xml/collector/AbstractXmlCollectionHandler.java
protocols/xml/src/main/java/org/opennms/protocols/xml/collector/Sftp3gppUtils.java
protocols/xml/src/main/java/org/opennms/protocols/xml/collector/Sftp3gppXmlCollectionHandler.java
protocols/xml/src/test/java/org/opennms/protocols/xml/collector/Sftp3gppUtilsTest.java

Jira: https://issues.opennms.org/browse/NMS-13413

NMS-13413: Remove storing of string attributes at a resource path without a sample

---

opennms-container/horizon/Dockerfile

NMS-13429: diffutils missing in Horizon Docker image

---

docs/modules/reference/pages/configuration/tuning-kafka.adoc

Fix description for Kafka and the usage for instance ids. IMHO, this is nothing we need to track in the release notes so no JIRA issue :)

Fix description for Kafka and instance ids

---

core/health/rest/src/main/java/org/opennms/core/health/rest/HealthCheckRestService.java
core/health/rest/src/main/java/org/opennms/core/health/rest/internal/HealthCheckRestServiceImpl.java
core/health/rest/src/main/resources/openapi/health-check-api.yaml
smoke-test/src/test/java/org/opennms/smoketest/minion/MinionRestIT.java

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13369

NMS-13369: Add tags as query params to /health/probe Rest API

---

docs/modules/operation/pages/service-assurance/monitors/PageSequenceMonitor.adoc

NMS-13412: fix host/virtual-host descriptions

---

debian/control
debian/opennms-server.postinst
opennms-base-assembly/src/main/filtered/bin/install
opennms-base-assembly/src/main/filtered/bin/opennms
opennms-base-assembly/src/main/filtered/bin/upgrade
tools/packages/opennms/opennms.spec

This PR actually rolls up some changes for NMS-13418 and NMS-13415, and fixes a few other issues I find while working on/testing them.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13415

NMS-13415: fix various RPM issues with non-root

---

docs/modules/development/pages/rest/snmp_configuration.adoc

NMS-13426 improve readability of docs for SNMP Config REST

---

docs/modules/reference/pages/configuration/tuning-activemq.adoc

NMS-13425: Add configuration example in tuning ActiveMQ

---

docs/modules/operation/pages/provisioning/detectors/HostResourceSWRunDetector.adoc

* [] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* JIRA (Issue Tracker): No issue created

Add title to HostResourceSWRunDetector doc page

---

opennms-base-assembly/src/main/filtered/bin/vmwarecimquery
opennms-base-assembly/src/main/filtered/bin/vmwareconfigbuilder

* JIRA: https://issues.opennms.org/browse/NMS-13444

NMS-13444: Added JAR-file to VMware-related scripts

---

core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AsyncDispatcherImpl.java

Issue Tracker: https://issues.opennms.org/browse/NMS-13405

NMS-13404: fix potential race condition in AsyncDispatcherImpl

---

antora-playbook-local.yml

* JIRA (Issue Tracker): no JIRA

Update Antora ui-bundle reference for full width support

---

docs/modules/operation/pages/performance-data-collection/collectors/prometheus.adoc

NMS-12978: Add Prometheus Collectd Service configuration example

---

WHATSNEW.md

WHATSNEW still points to old location

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/performance-data-collection/collectd/collect-admin.adoc
docs/modules/operation/pages/performance-data-collection/collectd/configuration.adoc
docs/modules/operation/pages/performance-data-collection/collectors/collectors.adoc
docs/modules/operation/pages/performance-data-collection/collectors/http.adoc
docs/modules/operation/pages/performance-data-collection/collectors/jdbc.adoc
docs/modules/operation/pages/performance-data-collection/collectors/jmx.adoc
docs/modules/operation/pages/performance-data-collection/collectors/nsclient.adoc
docs/modules/operation/pages/performance-data-collection/collectors/prometheus.adoc
docs/modules/operation/pages/performance-data-collection/collectors/snmp/SnmpCollector.adoc
docs/modules/operation/pages/performance-data-collection/collectors/tca.adoc
docs/modules/operation/pages/performance-data-collection/collectors/vmware-cim.adoc
docs/modules/operation/pages/performance-data-collection/collectors/vmware.adoc
docs/modules/operation/pages/performance-data-collection/collectors/wmi.adoc
docs/modules/operation/pages/performance-data-collection/collectors/wsman.adoc
docs/modules/operation/pages/performance-data-collection/collectors/xml.adoc
docs/modules/operation/pages/performance-data-collection/collectors/xmp.adoc

This PR is review/edits to https://github.com/OpenNMS/opennms/pull/3553
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13456

NMS-13456: Collectors edits from MMahacek

---

docs/modules/operation/pages/alarms/configuring-alarms.adoc
docs/modules/operation/pages/alarms/history.adoc
docs/modules/operation/pages/bsm/map-functions.adoc
docs/modules/operation/pages/bsm/operational-status.adoc
docs/modules/operation/pages/events/sources/eif-adapter.adoc
docs/modules/operation/pages/events/sources/snmp-traps.adoc
docs/modules/operation/pages/events/sources/syslog.adoc
docs/modules/operation/pages/meta-data.adoc
docs/modules/operation/pages/notifications/strategies/mattermost.adoc
docs/modules/operation/pages/notifications/strategies/slack.adoc
docs/modules/operation/pages/thresholds/thresholding.adoc
docs/modules/operation/pages/user-management/pre-authentication.adoc
docs/modules/operation/pages/user-management/security-roles.adoc
docs/modules/reference/pages/configuration/tuning-activemq.adoc

NMS-13472: Update table formatting in docs

---

opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java

By re-building the cache without locking, the enrichment process can
continue to work while a re-build is inprocess.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13481

NMS-13481: Reload interface-to-node cache non-blocking

---

opennms-webapp/src/main/java/org/opennms/web/admin/notification/noticeWizard/NotificationWizardServlet.java
opennms-webapp/src/main/webapp/admin/notification/noticeWizard/buildPathOutage.jsp
opennms-webapp/src/main/webapp/admin/notification/noticeWizard/buildRule.jsp

NMS-13496: sanitize filter rule input in notice wizard

---

opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp

NMS-13498: Sanitize more user inputs in scheduled outage editor

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapIdentity.java
docs/modules/operation/pages/events/event-configuration.adoc
features/events/api/src/main/java/org/opennms/netmgt/events/api/model/ISnmp.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/model/ImmutableMapper.java
features/events/api/src/main/java/org/opennms/netmgt/events/api/model/ImmutableSnmp.java
features/events/api/src/main/java/org/opennms/netmgt/xml/event/Snmp.java
features/events/api/src/test/java/org/opennms/netmgt/events/api/model/ImmutableSnmpTest.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/EventCreator.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapIdentityDTO.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapDTOMapperTest.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java
features/events/traps/src/test/resources/org/opennms/netmgt/trapd/eventconf.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/events/MaskElementField.java
opennms-config-model/src/main/java/org/opennms/netmgt/eventd/datablock/EventKey.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/EventMatchers.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Maskelement.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Snmp.java
opennms-config-model/src/main/resources/xsds/eventconf.xsd
opennms-config-model/src/test/java/org/opennms/netmgt/xml/eventconf/EventTest.java
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13422

NMS-13422: Add full trapoid for snmp trap events

---

features/ifttt/src/main/java/org/opennms/features/ifttt/helper/IfTttTrigger.java
features/ifttt/src/test/java/org/opennms/features/ifttt/helper/IfTttTriggerTest.java

* JIRA: https://issues.opennms.org/browse/NMS-13501

NMS-13501: Fixed broken IFTTT triggers

---

docs/modules/operation/pages/service-assurance/monitors/HostResourceSwRunMonitor.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-8968

NMS-8968: add regex to HRSwRunMonitor docs

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/categories.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13228

NMS-13228: Escape category name for JavaScript

---

opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13219

NMS-13219: Now, time spans can only be added once

---

.circleci/config.yml
opennms-base-assembly/pom.xml
opennms-full-assembly/pom.xml

https://issues.opennms.org/browse/PE-26
make a CM-Phase1 container ready for system integration

PE-26: make sure CM-Phase1 build docker image

---

core/schema/src/main/liquibase/changelog.xml

I forgot to reference the update script in the main changelog.xml. This PR fixes that.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13356

NMS-13356: TSS 2.0: Improved Tag handling: fix database upgrade

---

features/telemetry/distributed/common/src/main/java/org/opennms/netmgt/telemetry/distributed/common/PropertyTree.java
features/telemetry/distributed/common/src/test/java/org/opennms/netmgt/telemetry/distributed/common/AdapterDefinitionParserTest.java
features/telemetry/distributed/common/src/test/java/org/opennms/netmgt/telemetry/distributed/common/ConfigurationTest.java
features/telemetry/distributed/common/src/test/java/org/opennms/netmgt/telemetry/distributed/common/PropertyTreeTest.java

* JIRA: https://issues.opennms.org/browse/NMS-13477

NMS-13477: trim property values

---

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapIdentity.java
features/events/api/src/main/java/org/opennms/netmgt/xml/event/Snmp.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/AbstractEventUtil.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/EventExpander.java
features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/EventCreator.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapIdentityDTO.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapDTOMapperTest.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java
features/events/traps/src/test/resources/org/opennms/netmgt/trapd/eventconf.xml
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java
features/kafka/producer/src/main/proto/opennms-kafka-producer.proto
features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/events/MaskElementField.java
opennms-config-model/src/main/java/org/opennms/netmgt/eventd/datablock/EventKey.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/EventMatchers.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Maskelement.java
opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Snmp.java
opennms-config-model/src/main/resources/xsds/eventconf.xsd
opennms-config-model/src/test/java/org/opennms/netmgt/xml/eventconf/EventTest.java
opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventBuilder.java

This backports #3579 and updates the fix.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13422

NMS-13422:  Add full trapoid for snmp trap events

---

opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp

* JIRA: https://issues.opennms.org/browse/NMS-13517

NMS-13517: Added pattern scope to service.jsp

---

ui/src/components/Common/Demo/Demo.vue
ui/src/components/Common/RadioButton.vue

Adding radio button component.

---

features/events/syslog/pom.xml
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/ConvertToEvent.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/HostNameWithLocationKey.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/IpAddressWithLocation.java
features/events/syslog/src/main/java/org/opennms/netmgt/syslogd/SyslogSinkConsumer.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/BufferParserTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/ConvertToEventTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/DnsCacheTest.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/Nms6730Test.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogReloadDaemonIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogSinkConsumerNewSuspectIT.java
features/events/syslog/src/test/java/org/opennms/netmgt/syslogd/SyslogdIT.java
opennms-provision/opennms-detectorclient-rpc/src/main/resources/META-INF/opennms/component-dao.xml
opennms-provision/opennms-detectorclient-rpc/src/main/resources/META-INF/opennms/provisiond-extensions.xml
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/DragonWaveNodeSwitchingIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/IfIndexNullIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ImportSchedulerIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/Nms5414IT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NodeLocationChangeIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NodeScanIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerRescanExistingFalseIT.java
opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/Spc391IT.java

This is backport of #3580 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13485

NMS-13485: Resolve hostname from Syslog Messages by doing a lookup on specific minion

---

ui/src/components/Common/DataTable.vue
ui/src/components/Common/Demo/DataTableDemo.vue
ui/src/components/Common/Demo/EditNode.vue
ui/src/components/Common/Demo/apiService.ts
ui/src/components/Common/Demo/nodeData.json
ui/src/router/index.ts

PE-35: create list of existing requisition definitions

---

docs/modules/development/pages/docs/introduction.adoc
docs/modules/development/pages/docs/writing.adoc

NMS-13516: update "Develop Documentation" section to describe table formatting

---

ui/src/components/Common/Button.vue
ui/src/components/Common/Demo/Demo.vue
ui/src/components/Common/DropDown.vue
ui/src/components/Common/InputText.vue
ui/src/components/Common/RadioButton.vue
ui/src/components/Common/RadioButtonFieldSet.vue

PE-34: Create Radio Button Fieldset.

---

container/features/src/main/resources/features.xml
container/karaf/src/main/filtered-resources/etc/custom.properties
features/config/dao/api/pom.xml
features/config/dao/api/src/main/java/org/opennms/features/config/dao/api/ConfigStoreDao.java
features/config/dao/impl/src/main/java/org/opennms/features/config/dao/impl/JsonConfigStoreDaoImpl.java
features/config/rest/api/src/main/java/org/opennms/features/config/rest/api/ConfigManagerRestService.java
features/config/rest/impl/pom.xml
features/config/rest/impl/src/main/java/org/opennms/features/config/rest/impl/ConfigManagerRestServiceImpl.java
features/config/service/api/src/main/java/org/opennms/features/config/service/api/ConfigurationManagerService.java
features/config/service/impl/pom.xml
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImpl.java
features/config/service/impl/src/test/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImplTest.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/ConfigurationmanagerServiceMock.java
opennms-dao/src/test/java/org/opennms/features/config/service/impl/ConfigurationmanagerServiceMock.java

https://issues.opennms.org/browse/PE-54

Jira/PE-54: Implement RESTful API base on PE-23

---

ui/src/components/Common/Demo/Demo.vue
ui/src/components/Common/InputNumber.vue

PE-63-InputNumber component

---

container/shared/src/main/resources/etc/container.init
features/telemetry/listeners/pom.xml
features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java

* JIRA: https://issues.opennms.org/browse/NMS-13552

NMS-13552: Added JVM option

---

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java
features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/ProtoBufMapperTest.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/ProtobufMapperIT.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/HwEntityDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockHwEntityDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/HwEntityDaoHibernate.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/HwEntityDaoIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsHwEntity.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsHwEntityAlias.java

This is backport of #3623 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13256

NMS-13256: Optimize kafka producer node generation 

---

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java
features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManagerTest.java

* JIRA: https://issues.opennms.org/browse/NMS-13539

NMS-13539: Remove options data if options template is removed

---

opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
smoke-test/src/test/java/org/opennms/smoketest/SnmpConfigPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13512

NMS-13512: Fixed proxyHost input

---

container/features/src/main/resources/features-minion.xml

https://issues.opennms.org/browse/PE-62

PE-62: Fix smoke test for CM-Phase1

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/elasticsearch/features/event-forwarder-mapping-table.adoc
docs/modules/operation/pages/events/anatomy-events.adoc
docs/modules/operation/pages/events/event-configuration.adoc
docs/modules/operation/pages/events/sources/send-event.adoc
docs/modules/operation/pages/notifications/concepts.adoc
docs/modules/operation/pages/operation/daemon-config-files/eventd.adoc
docs/modules/operation/pages/thresholds/thresholding.adoc

* [ x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ x] If this PR targets a `foundation-*` branch, does it avoid changing files in `$OPENNMS_HOME/etc/`?
One or more reviewers should be …

NMS-13428: Strings with URL arguments are truncated in the eventdescr field

---

.gitignore
package-lock.json
ui/package.json
ui/src/components/Configuration/ThreadPools.vue
ui/src/shims-vue.d.ts

PE-59: ThreadPool validations

---

features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationRequest.java
features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/IpAddr.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/Bounds.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/PreprocessedRule.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/Threshold.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/Tree.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/matcher/IpMatcher.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/IpRange.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/IpValue.java
features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/PortValue.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineTest.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/RandomClassificationEngineTest.java
features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/value/IpValueTest.java
features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DocumentEnricherTest.java

Issue: https://issues.opennms.org/browse/NMS-13577
This PR increases the performance of the flow classification engine considerably (cf. the linked issue for details).

NMS-13577: improve performance of flow classification engine

---

opennms-base-assembly/src/main/filtered/etc/examples/scriptd-configuration.xml
opennms-base-assembly/src/main/filtered/etc/examples/scriptd-event-forwarder.bsh

Once the reviewer(s) accept the PR and …

NMS-13271: Fix example configuration for Scriptd

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/performance-data-collection/data-types.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10476

NMS-10476: Document data types

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JTrapNotifier.java
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapSinkModule.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/Snmp4JTrapHandlerIT.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapDTOMapperTest.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapHandlerITCase.java
features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapNotificationSerializationTest.java
opennms-alarms/snmptrap-northbounder/src/test/java/org/opennms/netmgt/snmp/snmp4j/TrapUtils.java

* JIRA: https://issues.opennms.org/browse/NMS-13489

NMS-13489: Fixed JMX counting of SNMP traps

---

docs/modules/operation/pages/admin/geocoder.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13611

NMS-13611: Update geocoder docs

---

.circleci/scripts/itest.sh

Issue: https://issues.opennms.org/browse/NMS-13609

NMS-13609: add apt keys before adding repositories

---

opennms-base-assembly/src/main/filtered/etc/vacuumd-configuration.xml

exists
Once the reviewer(s) accept the …

NMS-13661: remove automation that references an action that no longer

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties

Once the reviewer(s) accept the PR and …

NMS-13670: clean up comments for importer.adapter.dns properties

---

opennms-base-assembly/src/main/filtered/bin/opennms

NMS-13702: respect START_TIMEOUT in systemd mode

---

docs/modules/releasenotes/pages/whatsnew.adoc

This PR updates "What's New in OpenNMS Horizon 29" with everything from JIRA and `git-release-report`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13700

NMS-13700: Update whats new with everything from JIRA

---

opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmDetailController.java

NMS-13705: prevent alarms with no node from including unrelated events in the related events box

---

opennms-webapp/src/main/webapp/admin/notification/noticeWizard/validatePathOutage.jsp

NMS-13496: Sanitize newRule and other params in validatePathOutage.jsp

---

opennms-base-assembly/src/main/filtered/bin/opennms

* JIRA: https://issues.opennms.org/browse/NMS-13703

NMS-13703: Fixed OpenNMS start script for Darwin

---

features/timeseries-evaluate/src/main/java/org/opennms/netmgt/collection/persistence/evaluate/EvaluateGroupPersister.java
features/timeseries-evaluate/src/main/java/org/opennms/netmgt/collection/persistence/evaluate/EvaluateSinglePersister.java
features/timeseries-evaluate/src/main/java/org/opennms/netmgt/collection/persistence/evaluate/EvaluateStats.java
features/timeseries-evaluate/src/main/resources/META-INF/opennms/applicationContext-timeseries-evaluate.xml
features/timeseries-evaluate/src/test/java/org/opennms/netmgt/collection/persistence/evaluate/EvaluateStatsIT.java

The node and interface counters of the Evaluation Layer are incorrect
If you have made additions or changes to the documentation, or if you _need_ documentation for these code changes, please make sure a …

NMS-13283: The node and interface counters of the Evaluation Layer are incorrect

---

debian/rules

* JIRA: https://issues.opennms.org/browse/NMS-13717

NMS-13575: Removed wrong line in debian/rules

---

features/config/dao/api/src/main/java/org/opennms/features/config/dao/api/ConfigItem.java
features/config/dao/impl/src/main/java/org/opennms/features/config/dao/impl/util/ConfigSwaggerConverter.java
features/config/dao/impl/src/main/java/org/opennms/features/config/dao/impl/util/OpenAPIBuilder.java
features/config/test/src/test/java/org/opennms/features/config/dao/util/OpenAPIBuilderTest.java

https://issues.opennms.org/browse/PE-123

PE-123: add OpenAPIBuilder and add single config support

---

docs/modules/deployment/pages/core/message-broker/kafka.adoc
docs/modules/deployment/pages/minion/message-broker/activemq.adoc
docs/modules/deployment/pages/minion/message-broker/grpc.adoc
docs/modules/deployment/pages/minion/message-broker/kafka.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13642

NMS-13642: Update docs for Twin

---

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java

* JIRA: https://issues.opennms.org/browse/NMS-13719

NMS-13719: Fixed NPE in DefaultProvisionService

---

docs/modules/releasenotes/pages/whatsnew.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13642

NMS-13642: Add breaking changes for Twin

---

docs/modules/deployment/pages/core/getting-started.adoc
docs/modules/deployment/pages/minion/install.adoc
docs/modules/deployment/pages/sentinel/runtime/install.adoc
docs/modules/deployment/pages/time-sync.adoc

NMS-13724: Add hint for time sync

---

tools/packages/opennms/opennms.spec

This PR makes sure the root and share directories are owned correctly.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13725

NMS-13725: fix permissions of roots as well

---

docs/modules/reference/pages/service-assurance/monitors/DhcpMonitor.adoc

NMS-13727: Remove DHCP plugin from docs

---

docs/modules/operation/pages/admin/webui/opsboard/dashlet/ksc.adoc

Fix ksc.adoc headings level 0 error

---

integrations/opennms-geoip-provisioning-adapter/pom.xml
integrations/opennms-geoip-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/GeoIpProvisioningAdapter.java
integrations/opennms-geoip-provisioning-adapter/src/test/java/org/opennms/netmgt/provision/GeoIpProvisioningAdapterIT.java
opennms-config-model/src/main/java/org/opennms/netmgt/config/geoip/GeoIpConfig.java
pom.xml

* JIRA: https://issues.opennms.org/browse/NMS-13728

NMS-13728: Added support for IPv6

---

core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/AbstractTwinSubscriber.java
core/ipc/twin/grpc/subscriber/src/main/java/org/opennms/core/ipc/twin/grpc/subscriber/GrpcTwinSubscriber.java
core/ipc/twin/jms/publisher/src/main/java/org/opennms/core/ipc/twin/jms/publisher/JmsTwinPublisher.java
core/ipc/twin/jms/publisher/src/main/resources/META-INF/opennms/applicationContext-twin-jms-publisher.xml
core/ipc/twin/jms/subscriber/src/main/java/org/opennms/core/ipc/twin/jms/subscriber/JmsTwinSubscriber.java
core/ipc/twin/kafka/publisher/src/main/java/org/opennms/core/ipc/twin/kafka/publisher/KafkaTwinPublisher.java
core/ipc/twin/kafka/subscriber/src/main/java/org/opennms/core/ipc/twin/kafka/subscriber/KafkaTwinSubscriber.java
opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml

Use topic for Twin Sink
Add authorization entries for Twin topics
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13726

NMS-13726: Fix JMS twin issues

---

docs/modules/operation/pages/provisioning/auto-discovery.adoc
docs/modules/operation/pages/provisioning/directed-discovery.adoc

NMS-13730: add discovery config docs from wiki

---

core/schema/src/main/java/org/opennms/core/schema/Migrator.java
core/schema/src/test/java/org/opennms/core/schema/MigratorTest.java

NMS-13715: Fixed the DB installer for Azure PostgreSQL database

---

tools/packages/opennms/opennms.spec

Simplify user-account creation.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13734

NMS-13734: don't try to force uid/gid, just make normal system accounts

---

container/features/src/main/resources/features.xml
core/ipc/common/kafka/pom.xml
core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java
features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/datasync/KafkaAlarmDataSync.java
features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
pom.xml
smoke-test/pom.xml
smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java

NMS-13716: Update Kafka dependencies to 3.0.0
* If this PR targets a `foundation-*` …

NMS-13716: Update Kafka dependencies to 3.0.0

---

container/features/src/main/resources/features.xml
core/ipc/twin/grpc/publisher/src/main/resources/OSGI-INF/blueprint/blueprint.xml

https://issues.opennms.org/browse/PE-153

PE-153: Fix CM-Phase1 rebase smoke test 

---

docs/modules/operation/pages/provisioning/directed-discovery.adoc

Fix typo in page-component-title

---

opennms-base-assembly/src/main/filtered/etc/opennms-activemq.xml

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13742

NMS-13742: Fix authorization entry for Twin

---

docs/modules/operation/pages/kafka-producer/enable-kafka.adoc

Trivial change that clarifies how to configure the Kafka producer client which was reported in our discussion chat.

Fix Kafka producer client configuration

---

ui/package.json
ui/src/components/Common/Demo/Demo.vue

PE-133: convert field set component to feathers

---

container/features/src/main/resources/features-sentinel.xml
features/events/daemon/pom.xml
features/events/daemon/src/main/resources/OSGI-INF/blueprint/blueprint.xml
findbundles.sh
opennms-alarms/daemon/pom.xml
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmLifecycleListenerManager.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/Alarmd.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/NorthbounderManager.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmTicketerService.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/ManagedDroolsContext.java
opennms-alarms/daemon/src/main/resources/META-INF/opennms/applicationContext-alarmd.xml
opennms-alarms/daemon/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/DroolsExampleIT.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java
opennms20/ALARMD.md

Add alert to sentinel

---

core/ipc/twin/kafka/common/src/main/java/org/opennms/core/ipc/twin/kafka/common/Topic.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13733

NMS-13733: Prefix Kafka twin topics with OpenNMS Instance Id

---

ui/src/components/Common/Demo/Demo.vue

removing input area to build fix

---

integrations/opennms-snmp-hardware-inventory-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpHardwareInventoryProvisioningAdapter.java
integrations/opennms-snmp-metadata-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpMetadataProvisioningAdapter.java
opennms-base-assembly/src/main/filtered/etc/events/opennms.discovery.events.xml

* JIRA: https://issues.opennms.org/browse/NMS-13735

NMS-13735: Added event parameter to distinguish hardware discovery events

---

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/alarmd.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/alec.properties

New collections and graphs for drools alarmd and ALEC

---

ui/src/components/Map/LeafletMap.vue

* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}

Set geo-map marker color to the node's highest alarm severity color.

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/SpringSecurityUserDaoImpl.java

NMS-13761: apply new user and role changes immediately

---

opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmDetailController.java
opennms-webapp/src/main/java/org/opennms/web/controller/alarm/RelatedEvent.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp

NMS-13749: improve alarm details' related events 

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/performance-data-collection/resource-types.adoc
docs/modules/operation/pages/performance-data-collection/snmp-index.adoc

NMS-13532: Migrate ResourceTypes from wiki to docs

---

integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCimCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCollector.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareCimMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/VmwareMonitor.java
integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java

* JIRA: https://issues.opennms.org/browse/NMS-13774

NMS-13774: Assure to release all VMware sessions

---

opennms-base-assembly/src/main/filtered/etc/opennms.properties
opennms-webapp/src/main/java/org/opennms/web/event/DaoWebEventRepository.java
opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp

NMS-13765: add a table of parameters to event detail

---

opennms-webapp/src/main/webapp/element/node.jsp

Case [https://issues.opennms.org/browse/NMS-13212](url)
Added check for cached node layout on the node.jsp file when opened from Info / Nodes / <node> / Edit in Requisition
When adding nodes thought Manage Provisioning Requisitions / Add Requsuition or Edit Requisition /  Add Node or Edit Node,  the edit node view use Angular routing and setup the cached layout accordingly.
Opening the node view though Info / Nodes / <node_selection> / Edit in Requisition,  opens the node from the url defined in the Node.jsp file.
2. update the JIRA link at the …

NMS-13212: Fix layout handling on 'Edit in Requisition'

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13709

NMS-13709: Added scheduler for flow thresholding and persistence

---

integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java

* JIRA: https://issues.opennms.org/browse/NMS-13781

NMS-13781: Added warning message for requisition nodes without any IP addresses assigned

---

container/shared/src/main/resources/etc/container.conf

NMS-13659: Use @NAME_DISPLAY@ instead of hard-coded product name in shared config

---

opennms-base-assembly/src/main/filtered/bin/update-package-permissions

* JIRA: https://issues.opennms.org/browse/NMS-13788

NMS-13788: Use \n as delimiter in update-package-permissions script

---

opennms-webapp/src/main/webapp/admin/discovery/edit-config.jsp

NMS-12992: Rename label to requisition in discovery config page

---

opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
opennms-base-assembly/src/main/filtered/etc/prometheus-datacollection.d/node-exporter.xml
opennms-base-assembly/src/main/filtered/etc/prometheus-datacollection.d/windows-exporter.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/prometheus-node-exporter.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/prometheus-windows-exporter.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/node-exporter.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/windows-exporter.properties

& update node-exporter graphs to use today's correct metric names
* If this PR targets …

NMS-13824: New prometheus graphs and collections ... 

---

opennms-base-assembly/src/main/filtered/etc/report-templates/TopIOWait.jrxml

* [Y ] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [Y ] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?
Don't worry if this sounds like a lot, we can help you get things set up …

NMS-13003: Replace hard-coded dir with ${install.dir}

---

opennms-assemblies/minion/pom.xml

Duh.  Thinko.  :)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13789

NMS-13789: Minion fix RUNAS=opennms -> minion

---

core/test-api/services/src/main/java/org/opennms/netmgt/config/mock/MockNotifdConfigManager.java
features/config/mock/src/main/java/org/opennms/netmgt/dao/mock/ConfigurationManagerServiceMock.java
features/config/mock/src/main/resources/META-INF/opennms/applicationContext-notifdTest.xml
features/config/mock/src/main/resources/etc/notifd-configuration.xml
features/config/upgrade/src/main/resources/changelog-cm/29.0.0/changelog-cm.xml
opennms-config-model/src/main/resources/defaults/notifd-configuration.xml
opennms-config/src/main/java/org/opennms/netmgt/config/NotifdConfigFactory.java
opennms-config/src/main/java/org/opennms/netmgt/config/NotifdConfigManager.java
opennms-dao/src/test/java/org/opennms/netmgt/config/NotificationManagerIT.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotificationsConfigTest.java
opennms-services/src/test/java/org/opennms/netmgt/notifd/NotificationsITCase.java
opennms-services/src/test/resources/META-INF/opennms/applicationContext-notifdTest.xml
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/ScheduledOutagesRestServiceIT.java

PE-145:[NotifD] - migrate notifications.xml to the new CM

---

opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionValidator.java

This PR ignores `.git` directories, as well as `lib` and `system`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13778

NMS-13778: do not validate .git directories, also skip lib and system

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/ApplicationKey.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
features/flows/itests/src/test/resources/thresholds.xml

Sessions are persistent but track update state internally. Old sessions
are removed if no data is received after some time.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13711

NMS-13711: Add housekeeping for flow thresholding

---

container/features/src/main/resources/features-sentinel.xml
opennms-alarms/rest/pom.xml
opennms-alarms/rest/src/main/java/org/opennms/web/rest/support/Aliases.java
opennms-alarms/rest/src/main/java/org/opennms/web/rest/support/MultivaluedMapImpl.java
opennms-alarms/rest/src/main/java/org/opennms/web/rest/support/SecurityHelper.java

Feature "sentinel-alarmd-rest" bundle installs into Karaf 4.3.2.

---

smoke-test/src/test/java/org/opennms/smoketest/AngularLoginRedirectIT.java

add commit to fix flaky smoke test

PE-142: make AngularLoginRedirectIT more robust.

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13790

NMS-13790: Compute sequence numbers for flow thresholding

---

features/flows/api/pom.xml
features/flows/api/src/main/java/org/opennms/netmgt/flows/api/FlowRepository.java
features/flows/api/src/main/java/org/opennms/netmgt/flows/api/ProcessingOptions.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/InitializingFlowRepository.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/AggregatedFlowQueryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/BulkingIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/DefaultDirectionIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/KafkaFlowForwarderIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
features/telemetry/protocols/flows/src/main/java/org/opennms/netmgt/telemetry/protocols/flows/AbstractFlowAdapter.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13712

NMS-13712: Add options for flow processing

---

ui/src/components/Layout/NavigationRail.vue

Adds the missing `Configuration` menu item.

add missing configuration menu item

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/DefaultServiceCollectorRegistry.java
features/poller/api/src/main/java/org/opennms/netmgt/poller/ServiceMonitorLocator.java
features/poller/api/src/main/java/org/opennms/netmgt/poller/ServiceMonitorRegistry.java
features/poller/api/src/main/java/org/opennms/netmgt/poller/support/DefaultServiceMonitorRegistry.java
opennms-config/src/main/java/org/opennms/netmgt/config/DefaultServiceMonitorLocator.java
opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java

NMS-13744: Allow monitors exposed via OIA to be scheduled with pollerd

---

docs/modules/reference/pages/provisioning/adapters/snmp-metadata.adoc
integrations/opennms-snmp-metadata-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpMetadataProvisioningAdapter.java
opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpmetadata/Config.java
opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpmetadata/Container.java
opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpmetadata/Entry.java
opennms-config-model/src/main/resources/xsds/snmp-metadata-adapter-configuration.xsd
opennms-config-model/src/test/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfigTest.java

NMS-13842: Extend SnmpMetadataProvisioningAdapter to support exact OIDs
* If this PR …

NMS-13842: Extend SnmpMetadataProvisioningAdapter to support exact OIDs

---

features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProviderTest.java
opennms-doc/guide-admin/src/asciidoc/text/kafka-producer/kafka-producer.adoc

Attempt to fix NPE while loading topology.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13851

NMS-13851: Fix NPE while loading topology

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/AggregatedFlowQueryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/BulkingIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/DefaultDirectionIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryRetryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/KafkaFlowForwarderIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java

* JIRA: https://issues.opennms.org/browse/NMS-13855
Test can be added when data collection is done.

NMS-13855: Add ifName to strings.properties

---

ui/src/Validators/CustomValidators.ts
ui/src/components/Configuration/ReqDefinitionFormModel.ts

PE-128: hostname validation

---

container/karaf/pom.xml
container/shared/pom.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProvider.java
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProviderTest.java
pom.xml

This PR fixes logging dependencies both inside and outside of Karaf.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13858

NMS-13858: fix logging dependencies (Foundation 2021)

---

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/ProcessingOptions.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
features/telemetry/protocols/flows/src/main/java/org/opennms/netmgt/telemetry/protocols/flows/AbstractFlowAdapter.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13706

NMS-13708: Implement persistence of aggregated flow applications

---

features/config/service/api/src/main/java/org/opennms/features/config/service/util/CmProperties.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/database/CmDatabase.java
features/config/upgrade/src/test/java/org/opennms/config/upgrade/LiquibaseUpgraderIT.java

Apply data choice properties immediately after a change to the properties.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/PE-182

PE-182: Apply data choice properties immediately after a change to the properties.

---

features/config/osgi/del/src/main/java/org/opennms/features/config/osgi/del/MigratedServices.java
features/config/upgrade/src/main/resources/changelog-cm/30.0.0/changelog-cm.xml

This PR migrates org.opennms.features.topology.app.icons.application.cfg to the Configuration Management System.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/PE-192

PE-192: migrate org.opennms.features.topology.app.icons.application.cfg to CM

---

features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/collectors/ServiceCollectorImpl.java
features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/collectors/ServiceCollectorManager.java

NMS-13867: Fix the RRD path for the plugin collectors

---

core/schema/src/main/java/org/opennms/core/schema/Migrator.java
core/schema/src/main/liquibase/29.0.4/changelog.xml

https://issues.opennms.org/browse/NMS-13441
Timescale changes to allow upgrades from existing postgres databases and creation of hypertables from existing tables and corresponding data migration.

NMS-13441 :  Add TimescaleDB extension on existing OpenNMS Database

---

core/ipc/osgi/src/main/resources/META-INF/opennms/applicationContext-ipc-osgi.xml
core/ipc/twin/common/pom.xml
core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/AbstractTwinPublisher.java
core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/AbstractTwinSubscriber.java
core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/LocalTwinSubscriber.java
core/ipc/twin/common/src/main/java/org/opennms/core/ipc/twin/common/LocalTwinSubscriberImpl.java
core/ipc/twin/grpc/itests/src/test/java/org/opennms/core/ipc/twin/grpc/GrpcTwinIT.java
core/ipc/twin/grpc/publisher/src/main/java/org/opennms/core/ipc/twin/grpc/publisher/GrpcTwinPublisher.java
core/ipc/twin/grpc/publisher/src/main/resources/OSGI-INF/blueprint/blueprint.xml
core/ipc/twin/grpc/subscriber/src/main/java/org/opennms/core/ipc/twin/grpc/subscriber/GrpcTwinSubscriber.java
core/ipc/twin/grpc/subscriber/src/main/resources/OSGI-INF/blueprint/blueprint.xml
core/ipc/twin/jms/publisher/src/main/java/org/opennms/core/ipc/twin/jms/publisher/JmsTwinPublisher.java
core/ipc/twin/jms/publisher/src/main/resources/META-INF/opennms/applicationContext-twin-jms-publisher.xml
core/ipc/twin/jms/subscriber/src/main/java/org/opennms/core/ipc/twin/jms/subscriber/JmsTwinSubscriber.java
core/ipc/twin/jms/subscriber/src/main/resources/OSGI-INF/blueprint/blueprint-twin-subscriber.xml
core/ipc/twin/kafka/itests/src/test/java/org/opennms/core/ipc/twin/kafka/KafkaTwinIT.java
core/ipc/twin/kafka/publisher/src/main/java/org/opennms/core/ipc/twin/kafka/publisher/KafkaTwinPublisher.java
core/ipc/twin/kafka/publisher/src/main/resources/META-INF/opennms/applicationContext-twin-kafka-publisher.xml
core/ipc/twin/kafka/subscriber/src/main/java/org/opennms/core/ipc/twin/kafka/subscriber/KafkaTwinSubscriber.java
core/ipc/twin/kafka/subscriber/src/main/resources/OSGI-INF/blueprint/blueprint-twin-subscriber.xml
features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java
opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/minion.xml
opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-minion-twin-graph.properties
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-twin-graph.properties

Add JMX metrics/graphs for IPC Twin.
Also expose them on karaf shell
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13649

NMS-13649: Add Metrics for IPC Twin

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/flows/nephron.adoc
docs/modules/releasenotes/pages/changelog.adoc

NMS-13861: Nephron chapter missing from TOC: added Nephron chapter to TOC
* If this PR …

NMS-13861: Nephron chapter missing from TOC

---

features/distributed/dao/impl/pom.xml
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13859

NMS-13859: Sync InterfaceToNode Cache asynchronously

---

features/config/dao/api/src/main/java/org/opennms/features/config/exception/ConfigRuntimeException.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/AbstractCmJaxbConfigDao.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/util/BeanFieldCopyUtil.java
features/config/test/pom.xml
features/config/test/src/test/java/org/opennms/features/config/service/util/BeanFieldCopyUtilTest.java

https://issues.opennms.org/browse/PE-183

PE-183: Enhance BeanUtils.copyProperties()

---

container/karaf/src/main/filtered-resources/etc/custom.properties
core/schema/src/main/liquibase/30.0.0/changelog.xml
core/schema/src/main/liquibase/changelog.xml
features/device-config/persistence/api/pom.xml
features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfig.java
features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java
features/device-config/persistence/impl/pom.xml
features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java
features/device-config/persistence/impl/src/main/resources/META-INF/opennms/component-dao.xml
features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java
features/device-config/persistence/pom.xml
features/device-config/pom.xml
features/distributed/dao/api/pom.xml
features/distributed/dao/impl/pom.xml
features/pom.xml
opennms-dao/src/main/resources/META-INF/opennms/applicationContext-shared.xml

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13775

NMS-13775: Add Device Config Dao layer

---

core/health/api/pom.xml
features/device-config/pom.xml
features/device-config/ssh-scripting/pom.xml
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshInteraction.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/Statement.java
features/device-config/ssh-scripting/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java
features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplTest.java
pom.xml

Issue: https://issues.opennms.org/browse/NMS-13899

NMS-13899: add SshScriptingService

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/GenericTypeResource.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/13913

NMS-13913: Replace slashes in collection resource names

---

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/ExporterKey.java
features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java

* JIRA: https://issues.opennms.org/browse/NMS-13915

NMS-13915: Added more logging

---

opennms-base-assembly/src/main/filtered/etc/resource-types.d/flows-resource.xml
opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/flows-graph.properties
opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml

* JIRA: https://issues.opennms.org/browse/NMS-13710

NMS-13710: Added simple graph definitions

---

docs/modules/development/pages/rest/health_rest.adoc

Adding Health Rest Api documentation
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13386

NMS-13386: Add docs to Health-Check Rest API

---

core/test-api/services/src/main/java/org/opennms/netmgt/config/mock/MockNotifdConfigManager.java
features/config/dao/api/src/main/java/org/opennms/features/config/dao/api/ConfigDefinition.java
features/config/dao/impl/src/main/java/org/opennms/features/config/dao/impl/JsonConfigStoreDaoImpl.java
features/config/dao/impl/src/main/java/org/opennms/features/config/dao/impl/util/XsdHelper.java
features/config/mock/src/main/java/org/opennms/netmgt/dao/mock/ConfigurationManagerServiceMock.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/AbstractCmJaxbConfigDao.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImpl.java
features/config/test/src/test/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImplTest.java
features/config/test/src/test/java/org/opennms/features/config/service/impl/ProvisiondCmJaxbConfigTestDao.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ChangeSchema.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfiguration.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/RegisterSchema.java
features/config/upgrade/src/main/resources/changelog-cm/30.0.0/changelog-cm.xml
features/config/upgrade/src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
features/config/upgrade/src/test/java/org/opennms/config/upgrade/LiquibaseUpgraderIT.java
features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfigFactory.java
integrations/opennms-vmware/src/main/java/org/opennms/netmgt/dao/vmware/jaxb/VmwareConfigDaoJaxb.java
opennms-config/src/main/java/org/opennms/netmgt/config/DiscoveryConfigFactory.java
opennms-config/src/main/java/org/opennms/netmgt/config/NotifdConfigFactory.java
opennms-config/src/main/java/org/opennms/netmgt/config/TrapdConfigFactory.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/cm/DefaultJmxConfigDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/cm/DefaultProvisiondConfigurationDao.java
protocols/xmp/src/main/java/org/opennms/netmgt/protocols/xmp/config/XmpConfigFactory.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/PE-98

PE-98: smoke

---

docs/modules/development/pages/rest/nodes.adoc
opennms-model/src/main/java/org/opennms/netmgt/model/events/EventUtils.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/NodeRestServiceIT.java
smoke-test/src/test/java/org/opennms/smoketest/NodeRestIT.java

NMS-13638: Add ReST endpoint to trigger a rescan of individual nodes

---

README.md

NMS-13213: Updated readme file content

---

container/features/src/main/resources/features-minion.xml
container/features/src/main/resources/features-sentinel.xml
container/features/src/main/resources/features.xml
features/minion/repository/pom.xml
features/sentinel/repository/pom.xml
features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java
features/telemetry/registry/pom.xml
features/telemetry/registry/src/main/java/org/opennms/netmgt/telemetry/protocols/registry/impl/TelemetryServiceRegistryImpl.java
opennms-util/pom.xml
opennms-util/src/main/java/org/opennms/core/utils/properties/DurationPropertyEditor.java

Issue: https://issues.opennms.org/browse/NMS-13926
This PR
* fixes setting `templateTimeout` on Netflow parsers
* preserves Netflow option values in case of option template updates

NMS-13926: Fix Netflow option template handling

---

opennms-container/minion/minion-config-schema.yml.in

CLOUD-1698: Feature Profile: Hide kafka bootstrap, Karaf, AWS, grpc, Web

---

features/telemetry/registry/src/main/java/org/opennms/netmgt/telemetry/protocols/registry/impl/TelemetryServiceRegistryImpl.java

Issue: https://issues.opennms.org/browse/NMS-13961

NMS-13961: Synchronize access to service factories

---

features/config/mock/src/main/java/org/opennms/netmgt/dao/mock/ConfigurationManagerServiceMock.java
features/config/osgi/cm/src/main/java/org/opennms/features/config/osgi/cm/Activator.java
features/config/osgi/cm/src/main/java/org/opennms/features/config/osgi/cm/CallbackManager.java
features/config/osgi/cm/src/main/java/org/opennms/features/config/osgi/cm/CmIdentifierUtil.java
features/config/osgi/cm/src/main/java/org/opennms/features/config/osgi/cm/CmPersistenceManager.java
features/config/osgi/cm/src/main/java/org/opennms/features/config/osgi/cm/DictionaryUtil.java
features/config/osgi/cm/src/test/java/org/opennms/features/config/osgi/cm/CmIdentifierUtilTest.java
features/config/osgi/cm/src/test/java/org/opennms/features/config/osgi/cm/DictionaryUtilTest.java
features/config/osgi/del/src/main/java/org/opennms/features/config/osgi/del/CmPersistenceManagerDelegator.java
features/config/osgi/del/src/main/java/org/opennms/features/config/osgi/del/MigratedServices.java
features/config/service/api/src/main/java/org/opennms/features/config/service/api/ConfigurationManagerService.java
features/config/service/api/src/main/java/org/opennms/features/config/service/api/EventType.java
features/config/service/api/src/main/java/org/opennms/features/config/service/util/CmProperties.java
features/config/service/impl/pom.xml
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/AbstractCmJaxbConfigDao.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImpl.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/EventHandlerManager.java
features/config/service/impl/src/test/java/org/opennms/features/config/service/impl/EventHandlerManagerTest.java
features/config/test/src/test/java/org/opennms/features/config/service/impl/ConfigurationManagerServiceImplTest.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ConfigFileUtil.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfiguration.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfigurationUtil.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfigurations.java
features/config/upgrade/src/main/java/liquibase/ext2/cm/change/Substring.java
features/config/upgrade/src/main/java/org/opennms/config/upgrade/LiquibaseUpgrader.java
features/config/upgrade/src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd
features/config/upgrade/src/test/java/liquibase/ext2/cm/change/SubstringTest.java
features/config/upgrade/src/test/java/org/opennms/config/upgrade/LiquibaseUpgraderIT.java
features/config/upgrade/src/test/resources/org/opennms/config/upgrade/LiquibaseUpgraderIT-changelog.xml
features/graphml/service/pom.xml

merge develop => CM-Phase2
* JIRA (Issue Tracker): https://issues.opennms.org/browse/PE-204

PE-204: Merge PE-204 => phase2

---

opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/datacollection/DatacollectionGroup.java
opennms-config-jaxb/src/test/java/org/opennms/netmgt/config/datacollection/DatacollectionGroupValidationTest.java

https://issues.opennms.org/browse/NMS-13723

NMS-13723: config-tester doesn't find malformed resourceTypes

---

features/system-report/src/main/java/org/opennms/systemreport/formatters/FullTextSystemReportFormatter.java

Jira issue: https://issues.opennms.org/projects/NMS/issues/NMS-13948

NMS-13948: Fix '%n%n' in 'full text' system report

---

docs/modules/releasenotes/pages/whatsnew.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13929

NMS-13929: Add a note on consolidate features

---

.circleci/config.yml

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13928

NMS-13928: fix pipefail error for grep in automation

---

features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthFailureHandler.java
features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java
features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSLoginUrlAuthEntryPoint.java
features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSlLogoutSuccessHandler.java
opennms-webapp/src/main/java/org/opennms/web/filter/HttpsRewriteFilter.java
opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
opennms-webapp/src/main/webapp/WEB-INF/web.xml

NMS-13901: Web UI redirects to http even with base-url set to https

---

docs/modules/development/pages/rest/measurements.adoc

Update source type markup for Measurements API docs

---

docs/modules/reference/pages/configuration/performance-data-collection/collectors/prometheus.adoc

Stop example link from being a hyperlink

---

docs/modules/deployment/pages/core/getting-started.adoc
docs/modules/deployment/pages/core/introduction.adoc

NMS-14030: Doc Update: Don't expose ONMS console to internet: added documentation as per Jira to explicitly state that users should not expose console to internet without appropriate isolation controls. Added to the "Install the Core instance" topic in the Deployment section of the docs.
Don't worry if this sounds …

NMS-14030: Doc Update: Don't expose ONMS console to internet

---

.circleci/main/@main.yml

* JIRA (Issue Tracker): https://issues.opennms.org/browse/CLOUD-475
Successful build, push and sign on both Azure and Docker:
https://app.circleci.com/pipelines/github/OpenNMS/opennms/16501/workflows/aef53f6a-d5a0-411e-a8d7-ceb3640bd921/jobs/114383
Please not that azurecr needs to be deployed before we can merge this commit

CLOUD-475 Push signed containers to Azure CR

---

features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/Context.java
features/telemetry/protocols/sflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/HostAdapter.java
features/telemetry/protocols/sflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/parser/proto/flows/BsonWriteTest.java

* JIRA: https://issues.opennms.org/browse/NMS-13795

NMS-13795: Fixed writeBson() methods and added test

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/flows/introduction.adoc
docs/modules/operation/pages/flows/troubleshooting.adoc

NMS-13811: Troubleshooting flows: basic

---

opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/SnmpDetector.java

* JIRA: https://issues.opennms.org/browse/NMS-13997

NMS-13997: Fixed SnmpDetector parameters

---

features/bsm/vaadin-adminpage/src/main/java/org/opennms/netmgt/bsm/vaadin/adminpage/BusinessServiceTreeTable.java

* JIRA: https://issues.opennms.org/browse/NMS-14026

NMS-14026: Added BS name to dialog

---

smoke-test/src/test/java/org/opennms/smoketest/sentinel/SentinelRestIT.java

Related to:
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14011

NMS-14011-temporary disabling sentinel smoke test until resolved issue

---

.circleci/scripts/itest.sh
.circleci/scripts/smoke.sh

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14054

NMS-14054: Set higher open file limit 

---

container/features/src/main/resources/features.xml
features/device-config/monitor-adaptor/src/main/java/org/opennms/features/deviceconfig/monitor/adaptor/DeviceConfigMonitorAdaptor.java
features/device-config/monitor/pom.xml
features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
features/device-config/monitor/src/test/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitorTest.java
features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java
opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml

* JIRA: https://issues.opennms.org/browse/NMS-13924

NMS-13924: DCB scheduling

---

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/AbstractPersister.java
features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersistOperationBuilder.java
features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersister.java
features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesRoundtripIT.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/support/RrdResourceAttributeUtils.java
opennms-web-api/src/main/java/org/opennms/web/svclayer/model/GraphResults.java

This pr fixes missing resource level string attributes.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-17

NMS-14055: String Properties / External Tags not working properly

---

.circleci/scripts/itest.sh
.circleci/scripts/smoke.sh

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14054

increasing ulimit for tests

---

pom.xml

This is resolving build issues that point to very different errors.
Should be followed up by https://issues.opennms.org/browse/NMS-14068
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14063

NMS-14063: Disable license plugin execution

---

docs/modules/deployment/pages/time-series-storage/newts/newts-repository-converter.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14073

NMS-14073: newts converter doc update

---

docs/modules/reference/nav.adoc
docs/modules/reference/pages/provisioning/detectors/TcpDetector.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14074

NMS-14074: TCP Detector docs

---

opennms-webapp/src/main/java/org/opennms/web/mail/MailerServlet.java
opennms-webapp/src/main/webapp/WEB-INF/web.xml
opennms-webapp/src/test/java/org/opennms/web/mail/MailerServletTest.java
pom.xml

NMS-14015: Update MailerServlet to use java mail

---

tools/packages/opennms/opennms.spec

* JIRA: https://issues.opennms.org/browse/NMS-14000

NMS-14000: always fix permissions for log directory

---

docs/modules/development/pages/build-from-source.adoc

NMS-14088: Build from source documentation needs a minor correction: removed incorrect  "-Dbuild.skip.tarball=true" part of command.
* If this is new …

NMS-14088: Build from source documentation needs a minor correction

---

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/SystemExecuteMonitor.java

NMS-14091: Spell check on SystemExecuteMonitor response

---

docs/modules/reference/pages/service-assurance/introduction.adoc
docs/modules/reference/pages/service-assurance/monitors/ActiveMQMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/CiscoPingMibMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/HttpMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/JmxMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/LdapMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/RadiusAuthMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/SmtpMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/SshMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/SystemExecuteMonitor.adoc
docs/modules/reference/pages/service-assurance/monitors/TcpMonitor.adoc

NMS-11747: cleanup monitor docs common parameters

---

opennms-assemblies/minion/src/main/filtered/debian/rules

NMS-14019: Clean the data directory before creating the package

---

core/web-assets/src/main/assets/js/apps/onms-resources/index.js
opennms-webapp/src/main/webapp/graph/chooseresource.jsp

OpenNMS points to the wrong URL while generating graphs
fixed the issue identifying default "null" string from jsp
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14057

NMS-14057: OpenNMS points to the wrong URL 

---

features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java
features/device-config/retrieval/src/test/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImplTest.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java

* JIRA: https://issues.opennms.org/browse/NMS-14061

NMS-14061: Always return results

---

features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfigurationUtil.java
features/config/upgrade/src/test/java/org/opennms/config/upgrade/LiquibaseUpgraderIT.java

https://issues.opennms.org/browse/PE-209

PE-209: Prevent archive config file already exist exception

---

docs/modules/operation/pages/events/sources/snmp-traps.adoc
features/events/api/src/main/java/org/opennms/netmgt/events/api/EventDatabaseConstants.java
features/events/daemon/src/test/java/org/opennms/netmgt/eventd/processor/HibernateEventWriterIT.java
opennms-model/src/main/java/org/opennms/netmgt/model/OnmsEventParameter.java

 NMS-13888: Update SNMP Trap docs and stop escaping '=' characters

---

core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategyTest.java

NMS-14045: Use the community string

---

features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/CdpElementDao.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/IpNetToMediaDao.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/IsIsElementDao.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/IsIsLinkDao.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/LldpElementDao.java
features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/OspfElementDao.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/CdpElementDaoHibernate.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/IpNetToMediaDaoHibernate.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/IsIsElementDaoHibernate.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/IsIsLinkDaoHibernate.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpElementDaoHibernate.java
features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/OspfElementDaoHibernate.java
opennms-config/src/main/java/org/opennms/netmgt/filter/JdbcFilterDao.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/IpInterfaceDao.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/NodeDao.java
opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SnmpInterfaceDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockIpInterfaceDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockNodeDao.java
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockSnmpInterfaceDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/IpInterfaceDaoHibernate.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java
opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactory.java
opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactoryInterface.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java

This PR contains a backport of Stefan's enlinkd performance improvements to `foundation-2022` -- they were originally only done in develop since it was unclear how "safe" they were, since they touch a decent bit of code.
What does everyone think? It changes a decent amount of stuff, but Stefan's changes look pretty good to me. I'm OK with sending it back.  Reviews on this one are to build consensus, it's OK to reject it if you think it's too risky.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13507

NMS-13507: backport enlinkd performance improvements to foundation-2022

---

container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
features/device-config/monitor/src/main/resources/META-INF/services/org.opennms.netmgt.poller.ServiceMonitor
features/device-config/monitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml
features/device-config/rest/src/test/resources/META-INF/services/org.opennms.netmgt.poller.ServiceMonitor
features/device-config/tftp/src/main/resources/OSGI-INF/blueprint/blueprint.xml
opennms-full-assembly/pom.xml

Also update TFTP port to 6969.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14107

NMS-14107: Run DCB Monitor  on OpenNMS through OSGi

---

docs/modules/operation/pages/device-config-backup/introduction.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14112

NMS-14013: Add device config backup documentation

---

opennms-base-assembly/pom.xml

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13833

NMS-13833: Add missing gecoder API

---

ui/src/components/Nodes/NodeAvailabilityGraph.vue

NMS-14114: Limit availability percentage to 2 decimal points

---

docs/modules/operation/pages/provisioning/getting-started.adoc
docs/modules/operation/pages/provisioning/introduction.adoc
docs/modules/operation/pages/provisioning/xml-samples.adoc
docs/modules/releasenotes/pages/changelog.adoc

NMS-14115: Broken links in docs - fixed broken links in provisioning section and heading level issue in changelog. …

NMS-14115: Broken links in docs

---

core/criteria/src/main/java/org/opennms/core/criteria/Criteria.java
core/criteria/src/main/java/org/opennms/core/criteria/CriteriaBuilder.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/AllRestriction.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restriction.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restrictions.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AbstractDaoHibernate.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/EventDaoIT.java

* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14006

NMS-14006: Support multiple parameter constraints in CriteriaBuilder

---

features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java
features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java
ui/src/components/Device/DCBTable.vue
ui/src/services/deviceService.ts
ui/src/store/device/actions.ts
ui/tests/deviceConfigBackup.test.ts

Device Config Backup: Allow triggering backup of multiple devices from UI and Rest API
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14153

NMS-14153: DCB Allow triggering backup of multiple devices

---

opennms-webapp/src/main/webapp/admin/notification/pathOutline.jsp
smoke-test/src/test/java/org/opennms/smoketest/NotificationsPageIT.java

* JIRA: https://issues.opennms.org/browse/NMS-14111

NMS-14111: Added check for valid name

---

features/vaadin-surveillance-views/pom.xml
features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/service/DefaultSurveillanceViewService.java
features/vaadin-surveillance-views/src/test/java/org/opennms/features/vaadin/surveillanceviews/service/NMS14048_IT.java

* JIRA: https://issues.opennms.org/browse/NMS-14048

NMS-14048: Fixed availability in surveillance dashboard

---

docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
docs/modules/deployment/pages/core/getting-started.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14162

NMS-14162: docs on setting capabilities

---

features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
features/device-config/monitor/src/test/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitorTest.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14146

NMS-14146: Fix initial DCB schedule

---

container/features/src/main/resources/features-minion.xml
features/minion/heartbeat/consumer/src/test/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumerIT.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/Requisition.java

https://issues.opennms.org/browse/PE-211
1 test failed out of 56352
[testProvisioningOfMinions](https://app.circleci.com/pipelines/github/OpenNMS/opennms/18206/workflows/eb58d28b-dd5d-47e8-8558-8196ed6578c5/jobs/131348/tests#failed-test-0)[]
[(https://app.circleci.com/insights/github/OpenNMS/opennms/workflows/build-deploy/tests)](https://app.circleci.com/pipelines/github/OpenNMS/opennms/18223/workflows/59bb2e28-fd34-43ef-9c81-98970446a004/jobs/131397)

PE-211: fix integration test errors

---

features/vaadin-surveillance-views/pom.xml
features/vaadin-surveillance-views/src/test/java/org/opennms/features/vaadin/surveillanceviews/service/NMS14048_IT.java

This fixes the failing smoke-test in develop.

NMS-14048: Fixed smoke test in develop

---

features/ticketing/jira-client/pom.xml

Jira Rest Java Client API version update
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13443

NMS-13443: Update Jira Rest Client 

---

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcher.java
features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesWriter.java
features/timeseries/src/main/java/org/opennms/netmgt/timeseries/util/TimeseriesUtils.java
features/timeseries/src/test/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcherTest.java
opennms-model/src/main/java/org/opennms/netmgt/model/ResourceTypeUtils.java
opennms-model/src/test/java/org/opennms/netmgt/model/ResourceTypeUtilsTest.java

* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-72

DC-72: TagMatchers: Query only on node level, not above

---

docs/modules/releasenotes/pages/changelog.adoc

fix 29.0.9 changelog headings

---

ui/.prettierrc
ui/src/components/Configuration/ConfigurationAdvancedPanel.vue
ui/src/components/Configuration/ConfigurationCronSelector.vue
ui/src/components/Configuration/ConfigurationHelper.ts
ui/src/components/Layout/NavigationRail.vue
ui/src/services/deviceService.ts

PE-208 Change nav rail Configuration title text - cleanup-work#30

---

ui/src/components/Layout/NavigationRail.vue
ui/src/composables/useRole.ts
ui/src/composables/useSnackbar.ts
ui/src/router/index.ts
ui/tests/useRole.test.ts

- Add useRole composable to be used for any role going forward
- Add DCB side nav / route access
- Display message when attempting to access route without the requisite role
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14170

NMS-14170: Add useRole composable, admin/dcb role access for side nav and routes

---

smoke-test/src/test/java/org/opennms/smoketest/UIRefreshIT.java

Fixes broken test for the back btn.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14190

NMS-14190: Fix UI test for back to main page btn

---

features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java

* JIRA: https://issues.opennms.org/browse/NMS-14127

NMS-14127: Check whether DeviceConfig service is bound to interface

---

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java
features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/NMS14130_Test.java

* JIRA: https://issues.opennms.org/browse/NMS-14169

NMS-14169: Added IEs to set input and output ifIndex

---

docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigQueryResult.java
features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java
features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigDTO.java
features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java
features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java
features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DeviceConfigTrigger.java
features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/GetDeviceConfig.java
opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
smoke-test/pom.xml
smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
smoke-test/src/main/java/org/opennms/smoketest/stacks/NetworkProtocol.java
smoke-test/src/main/java/org/opennms/smoketest/utils/HibernateDaoFactory.java
smoke-test/src/main/java/org/opennms/smoketest/utils/RestClient.java
smoke-test/src/test/java/org/opennms/smoketest/dcb/DcbEndToEndIT.java
smoke-test/src/test/resources/device-config/test.dcb

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14012

NMS-14012: DCB end-to-end smoke test

---

features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java
features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java
features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java
features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java
features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java
features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java

Device Configuration Backup, updates to Dao and Rest API to filter on backup status
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14167

NMS-14167: DCB Dao and Rest API, filter on backup status

---

docs/modules/operation/pages/alarms/alarm-notes.adoc
docs/modules/operation/pages/alarms/alarm-sound-flash.adoc
docs/modules/operation/pages/alarms/alarmd.adoc
docs/modules/operation/pages/alarms/configuring-alarms.adoc
docs/modules/operation/pages/alarms/history.adoc
docs/modules/operation/pages/alarms/ifttt-integration.adoc
docs/modules/operation/pages/alarms/introduction.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14182

NMS-14182: Clean up Alarmd doc formatting

---

container/features/src/main/resources/features-minion.xml
features/api-layer/core/src/main/java/org/opennms/features/apilayer/config/ThresholdingConfigExtensionManager.java
features/api-layer/core/src/test/java/org/opennms/features/apilayer/config/ThresholdingConfigExtensionManagerTest.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorAbsoluteChangeTest.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorHighLowTest.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRelativeChangeTest.java
features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdExpressionTestCase.java
features/minion/heartbeat/consumer/src/test/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumerIT.java
opennms-config-model/src/main/java/org/opennms/netmgt/config/threshd/Basethresholddef.java
opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/Requisition.java
opennms-webapp/src/main/java/org/opennms/web/controller/admin/thresholds/ThresholdController.java
pom.xml

https://issues.opennms.org/browse/OIA-31
This pull request need wait for OIA pull request. 
https://github.com/OpenNMS/opennms-integration-api/pull/52

OIA-31: Modify Threshold Extensions to support metadata in threshold fields

---

container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.logging.cfg

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14206

NMS-14206: Move container bridge logging to INFO

---

features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/AbstractCmJaxbConfigDao.java
features/config/service/impl/src/main/java/org/opennms/features/config/service/impl/callback/DefaultAbstractCmJaxbConfigDaoUpdateCallback.java
features/config/test/src/test/java/org/opennms/features/config/service/impl/AbstractCmJaxbConfigDaoTest.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/jaxb/DefaultProvisiondConfigurationDao.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/jaxb/callback/ConfigurationReloadEventCallback.java
opennms-dao/src/test/java/org/opennms/netmgt/dao/jaxb/callback/ConfigurationReloadEventCallbackTest.java

https://issues.opennms.org/browse/PE-218

PE-218: make sure provisiond will auto reload after save

---

docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
features/device-config/monitor/src/test/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitorTest.java
features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/api/Retriever.java
features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java
features/device-config/retrieval/src/test/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImplTest.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java
features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/14118

NMS-14118: Add SSH host key verification

---

docs/modules/development/nav.adoc
docs/modules/development/pages/development.adoc
docs/modules/development/pages/osgi/osgi-and-opennms.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14234

NMS-14234: Add howto document on Integrating OSGi modules in OpenNMS

---

ui/src/components/Configuration/ProvisionDForm.vue

PE-220 Fix External Type not reactive

---

ui/src/components/Configuration/ProvisionDForm.vue

Fix external type not reactive

---

opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/ManagedDroolsContext.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/FilesystemRestService.java
opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/LogRestService.java

https://issues.opennms.org/browse/NMS-14239
Tested locally both standalone & docker works fine.

NMS-14239: Fixing new UI list log & etc fail due to symbolic link

---

docs/modules/operation/pages/performance-data-collection/shell/adhoc-collection.adoc

* JIRA (Issue Tracker): not created

Ad-hoc collection doc fix

---

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNode.java
opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNodeTest.java

NMS-14142: Reject nodes with invalid foreign ids

---

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/HttpPostMonitor.java

NMS-14159: fix typo in ssl filter parameter for HttpPostMonitor

---

docs/modules/operation/pages/alarms/configuring-alarms.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14182

NMS-14182: more alarmd doc tweaks

---

docs/modules/operation/nav.adoc
docs/modules/operation/pages/events/perf-data.adoc

https://issues.opennms.org/browse/NMS-14171

NMS-14171: add docs for event performance data

---

docs/modules/reference/pages/configuration/performance-data-collection/collectors/xml.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14256

NMS-14256: Additional XML Collector docs

---

docs/modules/deployment/nav.adoc
docs/modules/deployment/pages/upgrade/basic.adoc
docs/modules/deployment/pages/upgrade/debian/up-debian.adoc
docs/modules/deployment/pages/upgrade/diff.adoc
docs/modules/deployment/pages/upgrade/introduction.adoc
docs/modules/deployment/pages/upgrade/rhel/up-rhel.adoc
docs/modules/operation/nav.adoc
docs/modules/operation/pages/admin/housekeeping/introduction.adoc
docs/modules/operation/pages/service-assurance/configuration.adoc

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13971

NMS-13971: Upgrade docs from v30->2022

---

ui/package.json
ui/src/components/Configuration/ConfigurationHelper.ts
ui/tests/configuration.test.ts
ui/yarn.lock

- Fix hostname validation to include domains
- FIx path input field to not append params when editing
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14272

NMS-14272: Fix path field and hostname validation

---

core/criteria/src/main/java/org/opennms/core/criteria/restrictions/BaseRestrictionVisitor.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/RegExpRestriction.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/RestrictionVisitor.java
core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restrictions.java
opennms-base-assembly/src/main/filtered/etc/categories.xml
opennms-base-assembly/src/main/filtered/etc/viewsdisplay.xml
opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/BeanWrapperRestrictionVisitor.java
opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/HibernateCriteriaConverter.java
opennms-services/src/main/java/org/opennms/netmgt/rtc/AvailabilityServiceHibernateImpl.java
opennms-services/src/test/java/org/opennms/netmgt/rtc/AvailabilityServiceIT.java
opennms-webapp-rest/src/test/resources/v1/availability.json

* JIRA: https://issues.opennms.org/browse/NMS-14244

NMS-14244: Added DCB to RTC dashboard

---

.github/workflows/auto-assign.yml

Don't run auto assign action on draft PR

---

docs/modules/reference/pages/service-assurance/monitors/BgpSessionMonitor.adoc
features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitor.java
features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/BgpSessionMonitorTest.java

* JIRA: https://issues.opennms.org/browse/NMS-14249

NMS-14249: Allow other Oids for BgpSessionMonitor

---

docs/modules/operation/pages/device-config-backup/dcb.adoc
opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
ui/src/components/Layout/NavigationRail.vue

Update labels from Device Config
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14261

NMS-14261: DCB menu items are mislabeled "Configuration Management"

---

ui/src/components/Configuration/ConfigurationTable.vue
ui/tests/configuration.test.ts

Disable editing of requisition:// URLs in external requisition editor
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14270

NMS-14270: Disable editing of requisition:// URLs

---

opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectableServiceTest.java

Set strictInterval default value to true
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14259

NMS-14259: Make org.opennms.netmgt.collectd.strictInterval true by default

---

ui/src/components/Configuration/ConfigurationHelper.ts
ui/tests/configuration.test.ts

Adds custom regex / tests for more hostnames
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14273

NMS-14273: Allow more hostnames

---

opennms-webapp/src/main/java/org/opennms/web/asset/AssetModel.java
opennms-webapp/src/main/webapp/element/index.jsp

* JIRA: https://issues.opennms.org/browse/NMS-14240

NMS-14240: Fixed asset search

---

docs/modules/deployment/pages/upgrade/debian/up-debian.adoc
docs/modules/deployment/pages/upgrade/rhel/up-rhel.adoc

Add note to remember to delete the browser's cache when upgrading - added note.
* If …

NMS-8504: Add note to remember to delete the browser's cache when upgrading

---

ui/src/components/Configuration/ConfigurationTable.vue

Removes schedule freq sort.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14286

NMS-14286: Remove schedule frequency sort

---

features/minion/repository/pom.xml
features/sentinel/repository/pom.xml
features/timeseries/pom.xml
opennms-full-assembly/pom.xml

Adding the repository required for OIA snapshots to the pom.xml files.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14295

NMS-14295 - OpenNMS build broken for release-30 and develop

---

features/scv/rest/src/main/java/org/opennms/features/scv/rest/DefaultScvRestService.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14292

NMS-14292: Fix scv edit attributes

---

opennms-base-assembly/src/main/filtered/etc/search-actions.xml
smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14290

NMS-14290 Web UI search does not find External Requisitions

---

opennms-webapp/src/main/webapp/admin/index.jsp
smoke-test/src/test/java/org/opennms/smoketest/AdminPageIT.java

* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14247

NMS-14247 Confusing web UI navigation titles

---

ui/package.json
ui/yarn.lock

Revert node types version
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14308

NMS-14308: Revert node types version

---

ui/src/components/Configuration/ConfigurationCronSelector.vue
ui/src/components/Configuration/ConfigurationHelper.ts
ui/src/components/Configuration/copy/requisitionTypes.ts
ui/tests/configuration.test.ts

release-30.x
[NMS-14296](https://issues.opennms.org/browse/NMS-14296)

NMS-14296: Disallow ? in file path

---

docs/modules/operation/pages/performance-data-collection/collectd/collection-packages.adoc

* JIRA (Issue Tracker): No JIRA Created

collection doc typo fix

---

ui/src/components/FileEditor/ConfimDialog.vue
ui/src/components/FileEditor/NewFileInput.vue

Fix file editor confim delete dialog not opening.
Fix new file input css
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14316

NMS-14316: Fix FileEditor dialog for FeatherDS v0.10.10

---

features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
features/scv/jceks-impl/src/test/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVaultTest.java

Added HashMap to cache credentials in memory
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14228:

NMS-14228: SCV:  Cache JCEKS credentials in memory

---

features/api-layer/core/src/main/java/org/opennms/features/apilayer/config/EventConfExtensionManager.java
features/api-layer/core/src/test/java/org/opennms/features/apilayer/config/VoluminousEventConfExtension.java
pom.xml

https://issues.opennms.org/browse/OIA-37

OIA-37: Update OIA eventconf to support event-sourced data collection

---

docs/modules/operation/pages/admin/geocoder.adoc

Reference GeoIP Provision adapter in Geocoder docs

---

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/requisitions.html

Trying again, as I targeted the wrong base branch originally.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14285

NMS-14285: reset Add Requisition button name

---

ui/src/components/Configuration/ConfigurationGeneratedUrl.vue
ui/src/components/Configuration/ConfigurationHelper.ts
ui/src/components/Configuration/ConfigurationTable.vue
ui/yarn.lock

NMS-14320 Obfuscate password
