opennms-container/horizon/container-fs/confd/conf.d/timeseries.properties.toml, opennms-container/horizon/container-fs/confd/templates/timeseries.properties.tpl, opennms-container/horizon/container-fs/entrypoint.sh
The strategy was set to "rrd" but the StrategyClass was still set to use JRobin. With this PR we set the defaults if no environment variable is set to use RRDTool and allow to configure different strategies to be configured through environment variables.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12290
=> NMS-12290: Set default values to use RRDTool and allow to change it with Environment variables

opennms-base-assembly/src/main/filtered/etc/events/opennms.default.threshold.events.xml
* JIRA: https://issues.opennms.org/browse/NMS-10672
Here an example based on HIGH *threshold*.
**Current logmsg:**
> High threshold exceeded for SNMP datasource ifInOctets * 8 / 1000000 / ifHighSpeed * 100 on interface 172.21.65.4, parms: ifLabel="lo" ifIndex="1" label="lo" ds="ifInOctets * 8 / 1000000 / ifHighSpeed * 100" description="Trigger an alert if incoming usage of any interface reaches or goes above 90% of its maximum speed for three consecutive measurement intervals (only for interfaces that have a maximum speed value defined)" value="2591.77" instance="1" instanceLabel="lo" resourceType="if" resourceId="nodeSource[IT:frapevh004].interfaceSnmp[lo]" threshold="90.0" trigger="3" rearm="75.0" 
**New logmsg:**
> High threshold exceeded for SNMP metric ifInOctets * 8 / 1000000 / …
=> NMS-10672: redesigned threshold default events

opennms-assemblies/minion/src/main/filtered/debian/rules, opennms-assemblies/sentinel/src/main/filtered/debian/rules
When renaming the log files for the Minion and Sentinel karaf containers, the `sed` script was accidentally changing `${karaf.log}` variables to be `${minion.log}` or `${sentinel.log}` (which are unset) rather than just changing the filename of the log file itself.
This PR fixes it.
Once …
=> NMS-12125: fix log file parsing in the .cfg setup

opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfig.java, opennms-services/src/main/java/org/opennms/netmgt/poller/Poller.java, opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java, opennms-services/src/test/java/org/opennms/netmgt/poller/PollerQueryManagerDaoIT.java
This prevents the poller package to interface cache to be rebuild on
every access during startup phase.
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12285
To be hones, I can't remember why the code was moved from `Poller` to `PollerConfig` but this reverts the move as introduced in #2445 and re-enables the test to skip the rebuild during initialization.
=> NMS-12285: Do not rebuild caches during init

core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderImpl.java, core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/Interpolator.java, features/collection/thresholding/impl/pom.xml, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/BaseThresholdDefConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/DefaultThresholdingSetPersister.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/DefaultThresholdsDao.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionThresholdValue.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdDefVisitor.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorAbsoluteChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorHighLow.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRearmingAbsoluteChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRelativeChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSetImpl.java, features/collection/thresholding/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ExpressionConfigWrapperTest.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdExpressionTestCase.java, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/LatencyThresholdingSetIT.java, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingSessionIT.java, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java, features/distributed/dao/impl/pom.xml, opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptorIT.java, smoke-test/src/test/java/org/opennms/smoketest/sentinel/AbstractAdapterIT.java, smoke-test/src/test/java/org/opennms/smoketest/sentinel/SentinelThresholdingIT.java, smoke-test/src/test/resources/sentinel-thresholding/thresholds.xml
This PR enhances expression based thresholds to allow one or more meta-data expressions to be included in the threshold expression. These will then be interpolated and cached the first time the threshold is evaluated.
With this enhancement the same threshold can be evaluated with a different expression depending on the resource and meta data configuration. For example a thresholded collection may be evaluated using different values for two nodes by giving each node a different value for the node-level meta data being used in the expression.
Note that this feature currently strictly requires all meta-data expressions that are inserted into a threshold expression to include a default value.
I've tested this manually on OpenNMS and verified on Sentinel via smoke test.
For automated testing, …
=> NMS-12247: Add support for meta-data fields in thresholding expressions

opennms-base-assembly/src/main/filtered/etc/thresholds.xml
This updates them to use "ifHCInOctets" & "ifHCOutOctets", and adds two
additional thresholds for agents that only support "ifTable" metrics.
See https://issues.opennms.org/browse/NMS-12301
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR …
=> NMS-12301: Fix the default "90% Interface Throughput" Thresholds

features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java, features/endpoints/grafana/client/src/test/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImplIT.java
JIRA: https://issues.opennms.org/browse/NMS-12297
Here we set the rendering timeout to be equal to the HTTP client's read timeout.
=> NMS-12297: Grafana report generation is timing out

runtests.sh
This PR contains fixes for running on my mac (which doesn't have `/usr/bin/bash`) and for building offline without having run tests before.
=> fix up runtest script for my environment  :)

features/container/minion/pom.xml, features/container/minion/src/main/filtered-resources/etc/org.opennms.features.telemetry.listeners.flows.cfg, opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml
JIRA: https://issues.opennms.org/browse/NMS-12190
Here we update Minion and OpenNMS to listen on UDP port 9999 for all supported flow protocols by default.
=> NMS-12190: Enable flow UDP listener by default on Minion and OpenNMS.

features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowConverter.java, features/telemetry/protocols/sflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowConverterTest.java, features/telemetry/protocols/sflow/adapter/src/test/resources/sflow.json
Depending on the transported protocols, sampled headers may no contain
IP information. These samples are ignored.
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12185
=> NMS-12185: Ignore sampled headers without IP

features/events/api/src/main/java/org/opennms/netmgt/xml/event/Event.java
JIRA: https://issues.opennms.org/browse/NMS-12306
Here we update the in-memory event objects to use CopyOnWriteArrayList to store parameters in order to help avoid CMEs.
=> NMS-12306: Use CopyOnWriteArrayLists in events in order to help avoid CMEs

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/TrafficSummary.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
This adds a test which ensures the order of flow series and summaries is
correctly sorted.
In addition, this makes some clean-ups to the used datastructures which
makes it easier for testing.
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12104
=> NMS-12104: Ensure order in flow queries

opennms-container/horizon/Dockerfile, opennms-container/minion/Dockerfile, opennms-container/minion/assets/entrypoint.sh, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/assets/entrypoint.sh
Create a user Minion and Sentinel with a bash environment and specific UIDs during Docker build. Chown the permissions for the users and set the UID instead of running as root in Sentinel.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12311
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12312
=> NMS-12311, NMS-12312: Fix Minion and Sentinel non-root environment

opennms-webapp/src/main/webapp/includes/interfaceAvailability-box.jsp, opennms-webapp/src/main/webapp/includes/serviceAvailability-box.jsp
Here we fix some Availability Box mismatches.
JIRA: https://issues.opennms.org/browse/NMS-12321
Haven't looked if other versions of OpenNMS are also affected, but suspect it will.
Maybe worth backporting as well
=> NMS-12321: Fix styling for availability columns

core/web-assets/src/main/assets/js/apps/onms-reports/persisted.html, features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java, features/reporting/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Reports generated by Reportd cannot be downloaded from the new Report UI introduced in Horizon 25.
If you want to verify this, simply add a report to your reportd-configuration (see jira issue for an example), let it generate some reports and try to download it via the Database Reports UI.
JIRA: https://issues.opennms.org/browse/NMS-12337
=> NMS-12337: Allow downloading of reports generated by Reportd in new UI

opennms-container/minion/assets/entrypoint.sh, opennms-container/sentinel/assets/entrypoint.sh
This PR just makes sure the CLDR locale setting is passed even in the minion and sentinel containers (even though they are running JDK 11 by default and, in theory, should already be getting this.)
Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, …
=> NMS-12263: pass java.locale.providers to minion and sentinel containers

opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
The JMX-Cassandra service goes down for all the cluster when a single instance is down.
At that time, if you have commit access (are an OpenNMS Group employee or a …
=> NMS-10027 - The JMX-Cassandra service goes down for all the cluster when a single instance is down

.circleci/config.yml, core/web-assets/src/main/assets/js/apps/onms-reports/report-details.html, core/web-assets/src/main/assets/js/apps/onms-reports/schedules.html, features/reporting/core/pom.xml, features/reporting/core/src/main/java/org/opennms/reporting/core/DeliveryOptions.java, features/reporting/core/src/main/java/org/opennms/reporting/core/svclayer/support/DefaultReportWrapperService.java, features/reporting/core/src/test/java/org/opennms/reporting/core/svclayer/support/DefaultReportWrapperServiceTest.java, features/reporting/rest/src/main/java/org/opennms/features/reporting/rest/internal/ReportRestServiceImpl.java, opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSchedulerService.java, opennms-webapp/src/test/java/org/opennms/web/svclayer/support/DefaultSchedulerServiceIT.java, smoke-test/src/main/java/org/opennms/smoketest/containers/WebhookEndpointContainer.java, smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java
Here we add the possibility to define a Webhook URL when delivering a Database Report.
If parameters are required, the URL can be substituted by the following parameters:
-  `format`
- `instanceId`
- `parameter_<parameterName>`
A webhook URL could look like this: `http://localhost:8080/files?instanceId=:instanceId&format=:format&option=:parameter_option`
I tested this with a Java and PHP dummy endpoint implementation. 
The PHP endpoint I used looks like this:
```PHP
<?php
foreach ($_FILES as $key => $value) {
$filename = $value["name"];
if (!file_exists("./uploads")) {
mkdir("./uploads");
}
move_uploaded_file($value["tmp_name"], "./uploads/".$filename);
}
```
A dummy Java endpoint implementation can be found [here](https://github.com/opennms-forge/dummy-http-endpoint).
I also tried …
=> NMS-12153: Provide webhook delivery option for database reports

opennms-full-assembly/pom.xml
Fix feature install `opennms-core-tracing-jaeger` on OpenNMS
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12359
=> NMS-12359: Add opennms-core-tracing-jaeger feature to full assembly

.circleci/config.yml, .circleci/scripts/jvmprocmon-start.sh, core/web-assets/pom.xml, makerpm.sh, tools/packages/minion/create-minion-assembly.sh, tools/packages/opennms/opennms.spec, tools/packages/sentinel/create-sentinel-assembly.sh
Here we update the build so that nodejs & yarn no longer run when building the RPM packages for OpenNMS/Minion/Sentinel - the artifacts are already available from the compile step.
We also add a script that will help us monitor JVM running the systems tests in order to help diagnose the intermittent "timeout due to no output" errors.
=> CircleCI stability updates

.circleci/config.yml, opennms-container/horizon/Dockerfile, opennms-container/horizon/build_container_image.sh, opennms-container/minion/Dockerfile, opennms-container/minion/build_container_image.sh, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/build_container_image.sh
Update build environment, Horizon, Minion and Sentinel to use CentOS 8 as base image. Updated Maven from 3.6.1 to 3.6.2.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12353
=> NMS-12353: Use CentOS 8 as base image for container images

opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.d/minion.xml, opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml, opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-jmx-fd-graph.properties
The graphs have been tested on a lab environment and seem to be accurate with what you can get via `/proc`.
About the location of the metrics...
Unfortunately, it is not possible to define 2 different `mbean` tag associated with the same `objectname`. For this reason, the new 2 JMX attributes were added to the appropriate `mbean` even though the name of the `mbean` is now misleading (i.e. `JVM Memory`, where it should have been named like `JVM Operating System`).
Considering some hidden flags you can add to a `service` definition for a collection package when using the JMX collector and `storeByGroup` is enabled, it can be problematic to change the name of the `mbean`. For this reason, I left it as it is right now.
I'm targeting `foundation-2019` as this PR contains changes on the `etc` …
=> NMS-12364: Collect and display file descriptor statistics via JMX for OpenNMS and Minion

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NewSuspectScanIT.java
In discovery, new suspect could be generated for the same node which has multiple interfaces. This could cause multiple nodes with same interfaces. 
This will restrict  scans that are coming from new suspect events to be single threaded.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12318
=> NMS-12318: Process newSuspect events in a single threaded fashion

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/services/Requisitions.js, core/web-assets/src/test/javascript/ng-requisitions/services/Requisitions.test.js
Fix requisition cache when accessing the Requisitions UI via "Edit in Requisition".
There is a Jest test to verify that loading a requisition without cache will retrieve the requisition statistics to avoid red nodes unless they are not on the database.
I built a test environment to verify the solution and it works.
If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise …
=> NMS-12360 - Fix requisition cache when accessing the Requisitions UI via "Edit in Requisition"

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/services/Requisitions.js
@RangerRick observed an unexpected problem when running the smoke tests with the original solution, hence the need to add some defensive code to keep the solution and avoiding side effects.
When requesting the requisition statistics for a given requisition, the end-point will return an error if the requisition doesn't exist. That is not the case when requesting all the stats, as that would return an empty array.
Because the requisition must be updated with the statistics only when they are available, the code was slightly modified to silently fail when there are errors retrieving the stats, meaning the code can continue with the requisition it already has preventing side effects.
2. update …
=> Fix for Bug NMS-12360 - Part II

opennms-container/minion/Dockerfile, opennms-container/minion/assets/health.sh, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/assets/health.sh
Using the Karaf client directly with the health check in Docker and Kubernetes doesn't work with the way the client is implemented. The output can not be correctly fetched and evaluated. A workaround would be using an SSH client and passing the credentials to the Karaf shell. This would be a) requires to install sshpass and ssh client packages in the container and b) exposing admin credentials in the health check command in Docker compose or Kubernetes.
This fix resolves the problem by creating a /tmp/file from the client command and …
=> NMS-12120: Add health wrapper for health:check

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericElement.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraph.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraphContainer.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/info/GraphInfo.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/validation/GraphContainerIdValidator.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/validation/NamespaceValidator.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/validation/exception/InvalidGraphContainerIdException.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/validation/exception/InvalidNamespaceException.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/generic/GenericEdgeTest.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/generic/GenericGraphContainerTest.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/generic/GenericGraphTest.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/validation/NamespaceValidatorTest.java
Originally the namespace was not restricted. 
With the new Graph API it is now possible to retrieve the persisted graphs or graph containers via ReST. The container is accessed via the container id and the graph via it's namespace, e.g.
```
GET /api/v2/graphs/<containerId>
GET /api/v2/graphs/<containerId>/<namespace>
```
As the namespace is an internal identifier there is no need to allow a certain amount of characters, which in return allows users to not URL encode the namespace and container id for easier access of those.
Besides restricting the namespace/containerId to certain chars/numbers we are also a bit more restrictive when adding vertices/edges to the graph to ensure the namespace actually matches.
=> Be more restrictive about namespace and container id definition

.circleci/config.yml
Code coverage is currently performed nightly and made available here:
https://sonarcloud.io/dashboard?id=OpenNMS_opennms
I don't think we use it enough to justify running nightly, I propose we switch this to weekly instead.
=> Perform code coverage weekly instead of nightly

opennms-provision/opennms-provisiond/pom.xml, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeInfoScan.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ProvisionService.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NodeInfoScanIT.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/NodeScanIT.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerTest.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/SnmpExceptionVaidatorTest.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/SnmpExceptionValidatorTest.java, opennms-provision/opennms-provisiond/src/test/resources/requisition_snmp_primary_but_no_service.xml, opennms-provision/opennms-provisiond/src/test/resources/testScanWithoutSnmpService.xml
Since SNMPDetector doesn't support SNMP profiles yet, NodeScan skips the scanning node if the default config doesn't detect SNMP service. 
This PR fixes that by always trying to detect SNMP service using config from profiles.
Also fixes a bug related to RPC exceptions.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12396
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12399
=> NMS-12396: Handle SNMP profiles by default in NodeScan

core/test-api/alarms/src/main/java/org/opennms/core/test/alarms/driver/AlarmdDriver.java, core/test-api/alarms/src/main/java/org/opennms/core/test/alarms/driver/Scenario.java, opennms-alarms/daemon/pom.xml, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmLifecycleListenerManager.java, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/AlarmService.java, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmService.java, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/ManagedDroolsContext.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmLifecycleListenerManagerIT.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmLifecycleListenerManagerSnapshotTest.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/AlarmdIT.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java, opennms-alarms/integration-tests/src/test/java/org/opennms/netmgt/alarmd/itests/AlarmdBlackboxIT.java, opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/alarmd.drl, opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml, opennms-model/src/main/java/org/opennms/netmgt/model/OnmsAlarm.java
JIRA: https://issues.opennms.org/browse/NMS-12412
JIRA for tests flapping: https://issues.opennms.org/browse/NMS-12309
Here we:
* Fix flapping between clear & unclear rules
* Limit # of queued actions - help prevent OOM
* Only add alarm facts to the Drools session once the related transacation has been succesfully flushed
* This fixes flapping tests and intermittent errors related to inconsistent database states
* Fix exception handling in fire thread
=> NMS-12412: Fix a number of problems with Drools in alarmd

features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/SmtpMonitorIT.java, features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/SshMonitorIT.java, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigFactory.java, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java, opennms-config/src/test/java/org/opennms/netmgt/config/PollerConfigReloadIT.java, opennms-config/src/test/resources/poller-configuration-valid1.xml, opennms-config/src/test/resources/poller-configuration-valid2.xml, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockFilterDao.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/ScheduledOutagesRestServiceIT.java
* JIRA: https://issues.opennms.org/browse/NMS-12400
OpenNMS will now fail to start with invalid filter rules inside poller-configuration.xml. Furthermore a reload to replace a valid with an invalid configuration will also fail. So in this case the old valid configuration will stay in place.
=> NMS-12400: Check filter rules in poller-configuration.xml

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/bmp-graph.properties
* JIRA: https://issues.opennms.org/browse/NMS-12425
Simple graph definitions for each metric. This PR is based on branch `jira/NMS-12414` and only adds the file `etc/snmp-graph.properties.d/bmp-graph.properties`.
=> NMS-12425: Added simple graph definitions

features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java, features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpPeerStatusAdapter.java, features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpPeerStatusAdapterFactory.java, features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpTelemetryAdapter.java, features/telemetry/protocols/bmp/adapter/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractAdapter.java, features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractAdapterFactory.java, features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractCollectionAdapter.java, features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractCollectionAdapterFactory.java, features/telemetry/protocols/collection/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractScriptedCollectionAdapter.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/JtiGpbAdapter.java, features/telemetry/protocols/nxos/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/nxos/adapter/NxosGpbAdapter.java, features/telemetry/protocols/sflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/sflow/adapter/SFlowTelemetryAdapter.java, opennms-base-assembly/src/main/filtered/etc/eventconf.xml, opennms-base-assembly/src/main/filtered/etc/events/opennms.bmp.events.xml
The new telemetryd adapter reacts to BMP peer up/down notifications and
creates events and alarms if a router lost or established a BGP session
with one of its peers.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12415
=> NMS-12415: Added BMP peer status adapter

features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/ClassificationEngineInitializer.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationService.java, features/flows/classification/engine/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationServiceIT.java
Here we migrate yet another module to use `SessionUtils` instead of `TransactionOperations` to get rid of weird `Dependency not resolvable` issues when refreshing a bundle and some bundles are using `TransactionOperations`
=> Use SessionUtils instead of TransactionOperations

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/JCifsMonitor.adoc, pom.xml, protocols/cifs/src/main/java/org/opennms/netmgt/poller/monitors/JCifsMonitor.java, protocols/cifs/src/test/java/org/opennms/netmgt/poller/monitors/TimeoutTest.java
* JIRA: https://issues.opennms.org/browse/NMS-12407
Updated the version of JCIFS. Poller timeouts are now applied in JCifs.
=> NMS-12407: Updated JCifs version

features/telemetry/common/build-proto.sh, features/telemetry/common/src/main/java/org/opennms/netmgt/telemetry/common/ipc/TelemetrySinkModule.java, features/telemetry/common/src/main/resources/telemetry.proto, features/telemetry/config/api/src/main/java/org/opennms/netmgt/telemetry/config/api/QueueDefinition.java, features/telemetry/config/jaxb/src/main/java/org/opennms/netmgt/telemetry/config/model/QueueConfig.java, features/telemetry/config/jaxb/src/main/resources/xsds/telemetryd-config.xsd, features/telemetry/distributed/common/src/main/java/org/opennms/netmgt/telemetry/distributed/common/MapBasedQueueDef.java, features/telemetry/distributed/common/src/main/java/org/opennms/netmgt/telemetry/distributed/common/PropertyTree.java, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/introduction.adoc
JIRA: https://issues.opennms.org/browse/NMS-12427
Here we use the queue configuration to drive the behavior of the routing key as opposed to using the listener configuration as done in: https://github.com/OpenNMS/opennms/pull/2842
This makes the solution more flexible, allow us to use different properties for different queues and avoids adding the routing-key flag to the actual messages sent.
=> NMS-12427: Allow telemetry flows to balance across Kafka partitions (alternate)

opennms-base-assembly/src/main/filtered/etc/eventconf.xml, opennms-base-assembly/src/main/filtered/etc/events/opennms.collectd.events.xml, opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
I've just moved 2 datacollection events into a separate events file since these collectd events were located in the pollerd event file.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12471
=> NMS-12471: DatacollectionFailed event definitions are located in wrong file

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/generic/GenericGraph.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/info/DefaultGraphInfo.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/info/GraphInfo.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/service/GraphProvider.java, features/graph/api/src/main/java/org/opennms/netmgt/graph/api/updates/ChangeSet.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/updates/ChangeSetTest.java, features/graph/api/src/test/java/org/opennms/netmgt/graph/api/updates/ContainerChangeSetTest.java, features/graph/domain/src/main/java/org/opennms/netmgt/graph/domain/AbstractDomainGraph.java, features/graph/domain/src/main/java/org/opennms/netmgt/graph/domain/simple/SimpleDomainGraph.java, features/graph/domain/src/test/java/org/opennms/netmgt/graph/domain/simple/SimpleDomainGraphTest.java, features/graph/provider/application/src/main/java/org/opennms/netmgt/graph/provider/application/ApplicationGraph.java, features/graph/provider/application/src/main/java/org/opennms/netmgt/graph/provider/application/ApplicationGraphProvider.java, features/graph/provider/bsm/src/main/java/org/opennms/netmgt/graph/provider/bsm/BusinessServiceGraph.java, features/graph/provider/bsm/src/main/java/org/opennms/netmgt/graph/provider/bsm/BusinessServiceGraphProvider.java, features/graph/provider/legacy/src/main/java/org/opennms/netmgt/graph/provider/legacy/LegacyGraph.java, features/graph/provider/legacy/src/main/java/org/opennms/netmgt/graph/provider/legacy/LegacyGraphProvider.java, features/graph/provider/persistence-test/src/main/java/org/opennms/netmgt/graph/provider/persistence/CustomGraph.java, features/graph/provider/persistence-test/src/main/java/org/opennms/netmgt/graph/provider/persistence/PersistenceGraphContainerProvider.java, features/graph/service/src/main/java/org/opennms/netmgt/graph/persistence/DefaultGraphRepository.java, features/graph/service/src/main/java/org/opennms/netmgt/graph/search/NodeSearchProvider.java, features/graph/service/src/main/java/org/opennms/netmgt/graph/service/GraphProviderManager.java, features/graph/service/src/test/java/org/opennms/netmgt/graph/persistence/DefaultGraphRepositoryIT.java
Here we remove the method `getVertexType()` on the `GraphInfo` object. Originally we thought this might be needed, but turns out so far we don't need it. If so, a probably better approach would be to use properties instead.
JIRA: https://issues.opennms.org/browse/NMS-12447
=> NMS-12447: Remove getVertexType()

features/flows/rest/impl/src/main/java/org/opennms/netmgt/flows/rest/internal/FlowRestServiceImpl.java, features/flows/rest/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/rest/impl/src/test/java/org/opennms/netmgt/flows/rest/internal/FlowRestServiceTest.java
Some more changes to use `SessionUtils` instead of `TransactionOperations`.
=> Refactoring: Use SessionUtils instead

core/web-assets/src/main/assets/js/apps/onms-classifications/views/modals/new-rule-modal.html, features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationEngine.java, features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationService.java, features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/error/Errors.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationService.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/ThreadSafeClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/TimingClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/matcher/IpMatcher.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/validation/RuleValidator.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/IpValue.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/value/StringValue.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineTest.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/validation/RuleValidatorTest.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/value/IpValueTest.java, features/flows/classification/shell/src/main/java/org/opennms/netmgt/flows/clazzification/shell/ClassificationListInvalidRuleCommand.java, features/flows/classification/shell/src/main/java/org/opennms/netmgt/flows/clazzification/shell/ClassificationListRuleCommand.java, opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc
Here we fix an issue with the ip src and dest fields when defining Classifcation Rules.
Somehow it was possible to define an IP-Like expression using commas. However that was a bit misleading and didn't work under the hood. Instead it is now possible to define actual IP-Ranges, e.g. `10.0.0.0-10.255.255.255`, as well as multiple definitions at once:
`192.168.0.1,10.0.0.0-10.255.255.255`
Support for wildcard entries was dropped.
A next step is to allow CIDR expressions (which is not done here)
It may be possible that invalid rules exist and when applying this patch to a system the classification engine may not load. 
~At the moment this is targeted for `develop` but should go into `foundation-2019`~
JIRA: https://issues.opennms.org/browse/NMS-12422
=> NMS-12422: Allow multiple values for ip address input

container/features/src/main/resources/features.xml, core/snmp/impl-snmp4j/pom.xml, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JAgentConfig.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java, features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdInformIT.java, opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java
Modify the way of creating session to include fixed local engine Id.
Some Snmp engines may not have ability to discover authoritative
engine id. They will need to have a fixed engine id that is
persistent across engine reboots. This is necessary for Informs
as Snmp  uses receiver's engine id as authoritative engine Id.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12473
=> NMS-12473: Add persistent local engine Id for Snmp Informs

features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParser.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/NotificationPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/UpdatePacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/AsPath.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/Attribute.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/Unknown.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/InformationElement.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/PeerDownPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/RouteMirroringPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/StatisticsReportPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/TerminationPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/mirroring/Information.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/mirroring/Mirroring.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/mirroring/Unknown.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/stats/Metric.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/stats/Unknown.java, features/telemetry/protocols/bmp/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BlackboxTest.java
Use UNKNOWN variants for most fields and use them instead of throwing
exceptions. The UNKNOWN variants are used for most types / codes where
there are IANA registered extensions which wo (currently) do not
support.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12552
=> NMS-12552: Make BMP parser more relaxed

.circleci/config.yml, .circleci/scripts/configure-signing.sh, .circleci/scripts/makedeb.sh, .circleci/scripts/makerpm.sh
* update makedeb/makerpm to not bother signing during package build
* convert to using the sign-packages orb for package signing
* configure ~/.m2/settings.xml for jar signing
If you want to see a completed run with it all enabled, see: [this CircleCI run](https://circleci.com/workflow-run/c648e3d2-3372-43d5-af65-e74c6e77a628)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12557
=> NMS-12557: enable java code signing

core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/LocalEngineIdCommand.java
Snmp Engines that don't have ability to discover authoritative engine id needs a way to get local Engine Id of OpenNMS.  We expose it through karaf shell command.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12473
=> NMS-12473: Add command to display local engine Id on Trap Engine.

opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigManager.java, opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java, opennms-config/src/test/java/org/opennms/netmgt/config/SnmpEventInfoTest.java
Using `getAgentConfig`  comes with some defaults which results in equality check failure.
Get config directly from snmp config by matching specifics and ranges.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12413
=> NMS-12413: Fix remove from definitions

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java, features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DocumentEnricherTest.java
Query the `InterfaceNodeCache` first and if there is a relavant `nodeId` query `NodeInfoCache` for the node document.
Also modify `nodeCache` settings to cache `10000` elements and set the cache to not to expire.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12580
=> NMS-12580: Improve NodeInfoCache handling

opennms-container/minion/assets/health.sh, opennms-container/sentinel/assets/health.sh
The health check script for Minion and Sentinel on Docker Images stopped working
At that time, if you have commit access (are an OpenNMS Group employee or a member of …
=> NMS-12600 - The health check script for Minion and Sentinel on Docker Images stopped working

opennms-doc/guide-admin/src/asciidoc/index.adoc, opennms-doc/guide-admin/src/asciidoc/text/operation/config-tester.adoc
Due to the [wiki cleanup project](https://opennms.discourse.group/t/project-vacu-suck) I found the config-tester wiki page that needs to be migrated to the docs.
We should add some information about the things the tool is checking.
All I know is that a XML syntax check is done.
@indigo423 Do we have information about the content the tool is checking?
@Bonrob2 Added you here because I thought it is a good idea to add the technical documentation person :man_shrugging:  Feel free to ignore me if my thoughts are completely wrong :-)
Just as reminder: After merging this PR the config-tester wiki page should be deleted and the [troubleshoot post](https://opennms.discourse.group/t/project-vacu-suck) needs an URL upgrade that points to the docs instead. …
=> NMS-12527: Migrate config-tester wiki to the docs

.circleci/config.yml
Skip doing GPG stuff if in a forked pull request.
I've pushed this branch to 2 places: the regular opennms tree (in which it should still GPG sign things), and my own personal github repo, from which this PR originates (in which it should *not* GPG sign things).
I won't merge this until both are correct.  ;) 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12615
=> NMS-12615: skip signing if run from a forked pull request

features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/openbmp/BmpKafkaProducer.java
This applies default values to the Kafka producer of the OpenBMP
Integration Adapter. The defaults are the same as the ones used in the
OpenBMP reference implementation.
This is a follow-up of #2910 and this PR should be re-targeted to `features/bmp` after merging #2910.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12574
=> NMS-12574: Apply default to OpenBMP kafka producer

opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
I've rewritten the content of nodeAdded event because the old text was a little too simplistic in my opinion.
I've also added the operator instruction field because I really like it if there are instructions for an user. But I'm pretty sure that we don't have default operator instructions right now in the default OpenNMS events. Is there any reason why we shouldn't?
Also I'm wondering why this event is stored in the poller event file. Is that correct? Which component is responsible for `uei.opennms.org/nodes/` events?
* https://issues.opennms.org/browse/NMS-12526
=> NMS-12526: Enrich content of nodeAdded event

opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java, opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/DroolsReloadFactsTest.java, opennms-correlation/drools-correlation-engine/src/test/java/org/opennms/netmgt/correlation/drools/PersistStateIT.java, opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistState/PersistState.drl
Marshal objects that are in the session before reload.
Unmarshal with specific class loader while restoring
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12586
=> NMS-12586: Fix restoring of facts on DroolsCorrelationEngine reload

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/ProtobufMapper.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java, opennms-doc/guide-admin/src/asciidoc/text/kafka-producer/kafka-producer.adoc
To balance events across partitions, change key from `uei` to `id`
Fix event createTime in ProtobufMapper
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12616
=> NMS-12616: Change key for events forwarded to kafka

features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml, opennms-container/minion/CONFD_README.md
JIRA: https://issues.opennms.org/browse/NMS-12626
From the JIRA description:
The Minion process currently binds to 127.0.0.1:1162 by default for handling SNMP traps. In most cases, this requires changing to a different interface once deployed.
The Syslog listener on the other hand bind to 0.0.0.0:1514 by default.
For consistency and simplicity, we should also bind to 0.0.0.0 for traps.
=> NMS-12626: Update trapd on Minion to bind to 0.0.0.0:1162 by default

.circleci/config.yml
Change the publish job to use a floating tag "bleeding" for develop and use the root pom.xml version number just for master branch.
This is related to pushing Minion images to [DockerHub Minion Repo](https://hub.docker.com/repository/docker/opennms/minion/tags?page=1)
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12627
=> NMS-12627: Minion Docker image for develop is tagged 27.0.0-SNAPSHOT

container/features/src/main/resources/features-sentinel.xml, core/test-api/kafka/pom.xml, features/distributed/coordination/zookeeper/pom.xml, pom.xml
zookeeper upgrade broke `sentinel-coordination-zookeeper` on the sentinel.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12619
=> NMS-12619: Revert zookeeper version to 3.4.7

.circleci/config.yml
Push Docker images to DockerHub registry for release branches with floating tag "release-candidate".
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12630
=> NMS-12630: Add release branches to push Minion to DockerHub

.circleci/config.yml
This PR duplicates recent work in the Helm project for auto-merging branches forward using templating.  It's been updated to merge `foundation-2016` to `foundation-2017`, but the original proof-of-concept was done in the `jira/NMS-12628` branch.  You can see how it worked in 2 phases:
1. [create the merge branch](https://app.circleci.com/pipelines/github/OpenNMS/opennms/5229/workflows/d448cf06-7b8f-4522-9971-7d0e1776a1f1/jobs/23014)
2. [merge the merge branch into the target branch](https://app.circleci.com/pipelines/github/OpenNMS/opennms/5231/workflows/994a70ce-3716-405d-a7dd-1779b6e3b01d/jobs/23033)
Once this is merged, all that's left to do for other branches is to change the parameters at the top of the CircleCI config.  (Also adding dependencies on additional builds, like minion or …
=> NMS-12628: implement foundation merging in foundation-2016

.circleci/config.yml, opennms-container/version-tags.sh
Changed to filter for publishing the OCI images for Horizon and Sentinel to be executed also for release-* branches. We use the floating tag "release-candidate" on DockerHub.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12630
=> NMS-12630: Push OCI for Horizon and Sentinel as release candidate

core/web-assets/src/main/assets/js/apps/status-box/index.js, core/web-assets/src/main/assets/js/vendor/c3-js.js, core/web-assets/src/main/assets/js/vendor/d3-js.js
This PR does some small changes to make sure that `d3` and `c3` are only loaded once, to avoid event errors in the topology map.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12532
=> NMS-12532: avoid double-loading d3/c3 dependencies

opennms-container/minion/Dockerfile, opennms-container/minion/Makefile, smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
Set cap_net_raw capabilities to the Java binary.
I have removed in a separate commit to run the Minion as root in our smoke test suite.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12635
=> NMS-12635: Restore CAP_NET_RAW capabilities in Minion

.circleci/config.yml
These changes make builds take anywhere from a few seconds to a few minutes less time, by reducing the amount of workspace junk that gets passed around from different caches.
In general, the major thing it does is add a level of caching based on the `<version>` tag in `pom.xml`, since dependency churn among single versions is less common.  This greatly reduces the size of the cache that's passed around between workspaces (in some cases up to 1GB!).
I also got rid of the "generic" keys for nodejs and maven dependencies since they increase the chances of passing old junk along, at the expense of the first build of a pom version being a bit slower (since it needs to download new dependencies).  This will have the side-effect of catching if upstream dependencies go away, which we're probably …
=> update CircleCI checksums to conserve space/bandwidth

opennms-container/horizon/Dockerfile
Let curl fail immediately when downloading confd dependency does not work. Otherwise, we may get an error HTML page and we fail late in when we run smoke tests.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12642
=> NMS-12642: Curl should fail when download does not work

container/features/src/main/resources/features.xml
NMS-12639: Add required dependencies to use ZSTD inside Kafka to features.xml
At that time, if you have commit access (are an OpenNMS Group employee or a member of the …
=> NMS-12639: Add required dependencies to use ZSTD inside Kafka to features.xml

features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParser.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/Header.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/Packet.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/KeepalivePacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/NotificationPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/OpenPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/UnknownPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/UpdatePacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/MultiprotocolReachableNlri.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/MultiprotocolUnreachableNlri.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/Header.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/InformationElement.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/Packet.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/PeerDownPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/PeerUpPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/RouteMirroringPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/RouteMonitoringPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/StatisticsReportPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/UnknownPacket.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/down/LocalBgpNotification.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/down/RemoteBgpNotification.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bmp/packets/mirroring/Unknown.java, features/telemetry/protocols/bmp/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BlackboxTest.java, features/telemetry/protocols/bmp/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/ParserTest.java
This makes the parser more error resilient.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12552
=> NMS-12552: Add unknown variants for BMP and BGP

core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml
JIRA: https://issues.opennms.org/browse/NMS-12673
We no longer use Java serialization for messages.
=> NMS-12673: Don't trust serialized object messages.

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/enrichment/EnrichmentGraphBuilder.java, features/graph/provider/topology/src/main/java/org/opennms/netmgt/graph/provider/topology/GraphContainerProviderManager.java, features/graph/provider/topology/src/main/java/org/opennms/netmgt/graph/provider/topology/LegacyMetaTopologyProvider.java, features/graph/provider/topology/src/main/java/org/opennms/netmgt/graph/provider/topology/LegacyTopologyProvider.java, features/graph/provider/topology/src/main/java/org/opennms/netmgt/graph/provider/topology/LegacyVertex.java, features/graph/provider/topology/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This Pull Request makes the Vertex Enrichment available to the topology map (so far it was only accessible via REST).
Note: in order to have the enrichment work the Vertex needs to have set the property: GenericProperties.NODE_CRITERIA 
Jira: https://issues.opennms.org/browse/NMS-12674
=> NMS-12674: Enable node enrichment for Topology providers coming from the Integration Api

container/features/src/main/resources/features-sentinel.xml, container/features/src/main/resources/features.xml, container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg, features/sentinel/repository/pom.xml, features/telemetry/api/src/main/java/org/opennms/netmgt/telemetry/api/adapter/TelemetryMessageLog.java, features/telemetry/itests/pom.xml, features/telemetry/protocols/graphite/adapter/pom.xml, features/telemetry/protocols/graphite/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/graphite/adapter/GraphiteAdapter.java, features/telemetry/protocols/graphite/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/graphite/adapter/GraphiteAdapterFactory.java, features/telemetry/protocols/graphite/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/graphite/adapter/GraphiteMetric.java, features/telemetry/protocols/graphite/adapter/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/telemetry/protocols/graphite/pom.xml, features/telemetry/protocols/pom.xml, opennms-base-assembly/pom.xml, opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/graphite-telemetry-interface.groovy, opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml, opennms-doc/guide-admin/src/asciidoc/index.adoc, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/graphite.adoc, opennms-full-assembly/pom.xml, opennms-full-assembly/src/test/java/org/opennms/assemblies/karaf/OnmsFeatureKarafIT.java, smoke-test/pom.xml, smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
This PR adds basic support for the Graphite `plaintext` protocol to Telemetryd.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12695
=> NMS-12695: graphite telemetry adapter

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/SystemExecuteMonitor.adoc
I got a hint from @indigo423 that should be also included in the docs. I've added an example for that.
https://issues.opennms.org/browse/NMS-12564
=> NMS-12568: Add SystemExcecuteMonitor example into docs

opennms-doc/guide-admin/src/asciidoc/text/service-assurance/monitors/JDBCQueryMonitor.adoc
The docs do not have an example of a `compare_string` method. Also it is not clear that the parameter `column` is required for `compare_string` method as @pioto described here: https://issues.opennms.org/browse/NMS-9581
I've added his example which is not in OpenNMS context. Not sure if this is a problem.
=> NMS-9581: JDBCQueryMonitor documentation

.circleci/config.yml, .circleci/scripts/itest.sh, .circleci/scripts/publish-cloudsmith.sh, features/topology-map/pom.xml, features/vaadin-components/graph/pom.xml, opennms-full-assembly/pom.xml, pom.xml, smoke-test/pom.xml
This is a rollup fix for a couple  of things, most notably attempting to do more priming of the `~/.m2/repository` cache early in the build process, rather than running into failures later down the line because of transient Maven Central errors in the middle of an expensive smoke or integration test run.
While working on this branch, I had enabled full integration tests and OCI/CloudSmith deploy (short-circuited) to make sure those changes work.  I've rebased/removed them now that it's ready to merge.
If we find more things that get (re-)downloaded during itest/smoke we can add them to the `<dynamicDependencies>` section in the `pom.xml` so they get pulled in early during the relatively cheap build phase.
* use a "go-offline" plugin to pull down all dependencies early and change it to …
=> a few more changes to attempt to optimize circleci and maven

features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/support/ParameterSubstitutingMonitor.java, features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/support/ParameterSubstitutingMonitorTest.java
This PR fixes:
* a problem in the regexp that detects the possible substitutions
* improves the error message in case a substitution is unknown
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12332
It replaces https://github.com/OpenNMS/opennms/pull/3004
=>  NMS-12556: SSLCert Monitor does not work, PR 2

opennms-container/minion/CONFD_README.md, opennms-container/minion/container-fs/confd/conf.d/org.apache.karaf.management.cfg.toml, opennms-container/minion/container-fs/confd/conf.d/org.apache.karaf.shell.cfg.toml, opennms-container/minion/container-fs/confd/conf.d/org.ops4j.pax.web.cfg.toml, opennms-container/minion/container-fs/confd/templates/org.apache.karaf.management.cfg.tmpl, opennms-container/minion/container-fs/confd/templates/org.apache.karaf.shell.cfg.tmpl, opennms-container/minion/container-fs/confd/templates/org.ops4j.pax.web.cfg.tmpl, smoke-test/src/main/resources/minion-config/minion-config.yaml
This PR adds new CONFD templates for configuring minion - specifically, the karaf SSH port and the "management" ports (RMI server and registry).
At that time, if you …
=> NMS-12687: Additional Confd templates for Minion configuration

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Interface.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Node.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/interface.html, core/web-assets/src/test/javascript/ng-requisitions/controllers/Interface.test.js, opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNode.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/InvalidRequisitionDataIT.java, opennms-provision/opennms-provisiond/src/test/resources/import_multiplePrimaryInterfaces.xml, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/RequisitionRestServiceIT.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/json/RequisitionRestServiceJsonIT.java
There should be only one primary interface allowed per node. But provisiond accepts node definitions with two primary tagged snmp interfaces.
This Pull Request addresses that problem and disallows the import of nodes with multiple primary interfaces (an error is thrown during validation phase).
This fix works also for the import via the Rest API: multiple primaries will lead to a HTTP 400 with a descriptive error message.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12605
=>  NMS-12605: Provisiond accepts multiple primary SNMP interfaces

.circleci/config.yml, opennms-container/horizon/Dockerfile
This PR resolves the merge conflict from foundation-2016 and we bump the introduced OpenJDK 11 to the latest version.
I'm not 100% sure if this is the right procedure to resolve auto-merge conflicts, here is what I did:
1. branched from foundation-2019
2. merged with foundation-2016 and resolved the merge conflict
3. bumped the OpenJDK 11
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12699
=> NMS-12699: Bump Docker image from OpenJDK 11.0.5.10 -> 11.0.7.10

core/ipc/sink/common/src/main/java/org/opennms/core/ipc/sink/common/AsyncDispatcherImpl.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/Template.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java
JIRA: https://issues.opennms.org/browse/NMS-12724
Running udpgen on against Minion with:
```
taskset -c 0 ./udpgen -x netflow9 -r 0 -p 8877
```
Performance before patch:
```
parsers.Netflow-9.recordsDispatched
count = 712561
mean rate = 3617.46 events/second
1-minute rate = 6653.68 events/second
5-minute rate = 2046.41 events/second
15-minute rate = 738.90 events/second
```
Performance after patch:
```
parsers.Netflow-9.recordsDispatched
count = 3421440
mean rate = 22088.17 events/second
1-minute rate = 21819.43 events/second
5-minute rate = 12224.38 events/second
15-minute rate = 8206.34 events/second
```
=> NMS-12724: Optimize queuing for throughput.

container/features/src/main/resources/features.xml, core/ipc/common/kafka/src/main/java/org/opennms/core/ipc/common/kafka/KafkaRpcConstants.java, core/ipc/rpc/api/src/main/java/org/opennms/core/rpc/api/RpcClientFactory.java, core/ipc/rpc/camel/src/main/java/org/opennms/core/rpc/camel/CamelRpcClientFactory.java, core/ipc/rpc/kafka/pom.xml, core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcClientFactory.java, core/ipc/rpc/kafka/src/main/java/org/opennms/core/ipc/rpc/kafka/KafkaRpcServerManager.java, core/ipc/rpc/kafka/src/main/resources/OSGI-INF/blueprint/blueprint-rpc-kafka-server.xml, core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaConsumerAsyncIT.java, core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaIT.java, core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcKafkaWithSingleTopicIT.java, core/ipc/rpc/kafka/src/test/java/org/opennms/core/ipc/rpc/kafka/RpcTestServer.java, opennms-doc/guide-admin/src/asciidoc/index.adoc, opennms-doc/guide-admin/src/asciidoc/text/minion/kafka-rpc.adoc
During node scan, one node can have 100/1000s of interfaces and those interfaces
can have 10s of services. When those nodes are on minion, OpenNMS
asynchronously sends all requests to minion. This may result in too many
concurrent requests.
Idea is to restrict number of concurrent requests at a given point.
Using bulkhead to gate requests that are incoming with tunable timeout
Default timeout is 100msecs and max concurrent calls is 1000.
So when 1000 rpc requests are processing currently, only 10 extra requests per sec
will be allowed. This will allow not having a hard limit on threads but also
gives chance to tune the system depending on the load.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12391
=> NMS-12391: Use bulkhead to restrict number of threads

pom.xml
This PR just bumps Jetty to the latest 9.4 in `foundation-2017`.  I'll merge it forward as necessary, it will conflict with the (still very outdated) bump to jetty 9.4.14 in newer branches.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12743
=> NMS-12743: update to 9.4.29

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/integration/NewtsConverterUtils.java, features/timeseries/src/main/java/org/opennms/netmgt/timeseries/integration/TimeseriesFetchStrategy.java, features/timeseries/src/main/java/org/opennms/netmgt/timeseries/integration/TimeseriesWriter.java, features/timeseries/src/main/java/org/opennms/netmgt/timeseries/integration/dao/TimeseriesResourceStorageDao.java, features/timeseries/src/main/java/org/opennms/netmgt/timeseries/integration/dao/TimeseriesSearcher.java, features/timeseries/src/test/java/org/opennms/netmgt/timeseries/integration/TimeseriesFetchStrategyTest.java, features/timeseries/src/test/java/org/opennms/netmgt/timeseries/integration/TimeseriesRoundtripIT.java, features/timeseries/src/test/java/org/opennms/netmgt/timeseries/integration/aggregation/SampleAggregatorTest.java, features/timeseries/src/test/java/org/opennms/netmgt/timeseries/integration/persistence/TimeseriesPersisterIT.java, pom.xml
Moves the constants from OpenNMS to the to the Integration API.
* Integration API PR: https://github.com/OpenNMS/opennms-integration-api/pull/28
* JIRA (Issue Tracker): https://issues.opennms.org/browse/OIA-26
=> OIA-26: Expose intrinsic tag names as constants for TSS API

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AbstractSnmpValue.java, core/snmp/api/src/test/java/org/opennms/netmgt/snmp/AbstractSnmpValueTest.java, opennms-model/src/main/java/org/opennms/netmgt/model/events/snmp/SyntaxToEvent.java, opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocalGroupTracker.java, opennms-services/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpRemTableTracker.java, opennms-services/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdSnmpIT.java
We pulled this out of the backlog this week, it's an old patch that Seth did that supposedly broke some Enlinkd tests, but we've refactored plenty of the related code and everything passes here.  I've gone ahead and made a `foundation-2019` version of it [here](https://app.circleci.com/pipelines/github/OpenNMS/opennms/6315/workflows/50ce4c23-550c-4c4c-8b2c-41bf48eed934) just to make sure it passes there too, and and as long as it does, I'd say we should hopefully be safe to merge.
JIRA: https://issues.opennms.org/browse/NMS-7547
=> NMS-7547: fix UTF-8 comparison decoding hex strings

dependencies/jradius/pom.xml, features/reporting/sdo/pom.xml, features/request-tracker/pom.xml, features/ticketing/drools-integration/pom.xml, features/ticketing/otrs-integration-31/pom.xml, features/ticketing/otrs-integration-common/pom.xml, features/ticketing/otrs-integration/pom.xml, features/ticketing/remedy-integration/pom.xml, features/ticketing/rt-integration/pom.xml, features/vaadin-node-maps/pom.xml, opennms-base-assembly/pom.xml, opennms-dao/pom.xml, opennms-provision/opennms-provision-persistence/pom.xml, opennms-webapp/src/test/resources/osgiTestWar/WEB-INF/karaf/system/org/apache/karaf/assemblies/features/standard/2.2.7/standard-2.2.7-features.xml, pom.xml
This PR updates our `commons-beanutils` dependencies to 1.9.4, including masking out `commons-beanutils-core` as necessary for dependencies, since Apache stopped splitting up the packages as of 1.9.0.
There is a `foundation-2019` version of this branch to, to make sure karaf dependency stuff pulled in properly; if this gets approved I'll merge it and make sure similar fixes are checked against dependencies up and down the line.
JIRA: https://issues.opennms.org/browse/NMS-12757
=> NMS-12757: update commons-beanutils to 1.9.4

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/OpennmsKafkaProducer.java
Chose to send events without key since number of events could be too many and this may be better way to evenly distribute these messages.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12784
=> NMS-12784: Remove key for the events sent to kafka 

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/InformationElementProvider.java
Issue: https://issues.opennms.org/browse/NMS-12783
According to https://www.iana.org/assignments/ipfix/ipfix.xhtml [95] this should be a OctetArray
=> NMS-12783: Fix application tag parsing

features/alarms/history/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/jest/client/src/main/java/org/opennms/features/jest/client/RestClientFactory.java, features/opennms-es-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/situation-feedback/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Add property to allow insecure SSL/HTTPS connections
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12768
=> NMS-12768: Add ignore certificates property for ElasticSearch

core/test-api/elasticsearch/pom.xml, pom.xml
This backports the log4j updates from `release-26.x` to `foundation-2019`.  Just belt-and-suspenders making sure everything passes.
=> NMS-12791: backport log4j update to foundation-2019

opennms-doc/guide-development/src/asciidoc/text/rest/users.adoc, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/UserRestService.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/UserRestServiceIT.java
This PR allows optionally hashing passwords upon saving when creating or updating users in the ReSTv1 interface.  I made it an optional URL parameter to make it easy to stay backwards-compatible with any existing scripts that might be interacting with the user rest service; you have to opt-in by adding `hashPassword=true` to trigger hashing before storing.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-6470
=> NMS-6470: allow hashing of password when creating or updating users

features/newts-repository-converter/src/main/java/org/opennms/features/newts/converter/NewtsConverter.java
Fix handling of RRDs where there are RRAs which have a timespan which is
also covered completely by a RRA with a higher resolution.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12722
=> NMS-12722: Handle fully overlapping RRAs

pom.xml
I've bumped Jetty to the latest stable version so we can get the wildcard SSL certificate issues fixed.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12805
=> NMS-12805: Bump Jetty to 9.4.30.v20200611 with fix for SSL ceritifcates

debian/control, opennms-base-assembly/src/main/filtered/bin/send-trap.pl
This PR removes Getopt::Mixed in favor of Getopt::Long which has been a part of Perl5's official distribution for some time now.  This fixes installation on newer ubuntu/debian distros which finally dropped the `libgetopt-mixed-perl` package.
=> NMS-12693: remove reliance on Getopt::Mixed

container/karaf/src/main/filtered-resources/etc/config.properties, core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Controller.java, core/daemon/src/main/java/org/opennms/netmgt/vmmgr/StatusGetter.java, debian/rules, makedeb.sh, opennms-base-assembly/src/main/filtered/bin/opennms, opennms-base-assembly/src/main/filtered/etc/opennms.service, opennms-bootstrap/pom.xml, opennms-bootstrap/src/main/java/org/opennms/bootstrap/Bootstrap.java, opennms-bootstrap/src/main/java/org/opennms/bootstrap/BootstrapUtils.java, opennms-bootstrap/src/test/java/org/opennms/bootstrap/BootstrapUtilsTest.java, opennms-container/horizon/container-fs/entrypoint.sh
This PR fixes 2 things:
1. writing the PID file even when running under systemd (which previously used the `-f` option to run in the foreground)
2. put `karaf.pid` back into the logs directory; I assume this got missed in a karaf upgrade/merge and reverted to writing to `$OPENNMS_HOME/karaf.pid` rather than `$OPENNMS_HOME/logs/karaf.pid`
It retrieves the PID from a supported API on Java 10+, and falls back to using the same approach as spring boot on earlier JDKs (parsing it out of `RuntimeMXBean.getName()`).
JIRA: https://issues.opennms.org/browse/NMS-12769
=> NMS-12769: fix pid file handling

core/health/impl/src/main/java/org/opennms/core/health/impl/ContainerIntegrityHealthCheck.java, core/health/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, opennms-container/minion/Dockerfile, opennms-doc/guide-install/src/asciidoc/text/minion-custom-messaging-system/setup-kafka/introduction.adoc, opennms-doc/guide-install/src/asciidoc/text/minion-custom-messaging-system/setup-kafka/steps-minion.adoc, opennms-doc/guide-install/src/asciidoc/text/minion-grpc/steps-minion.adoc, opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/docker/minion-docker.adoc, smoke-test/src/main/java/org/opennms/smoketest/utils/KarafShellUtils.java
In our the Minion documentation we used `-f` which uses the credentials from our Secure Credentials Vault and the credentials from the environment variables are ignored. To make the example work, I've changed it to use `-c`. Additionally we have referenced the old health:check command which doesn't work anymore and is renamed to `opennms:health-check`. I've found a few other spots as well and fixed them with a second commit as well.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12872
=> NMS-12872: Fix Minion startup command to use credentials from environment with health-check

opennms-services/pom.xml, opennms-services/src/main/java/org/opennms/netmgt/notifd/AbstractSlackCompatibleNotificationStrategy.java, opennms-services/src/main/java/org/opennms/netmgt/notifd/MattermostNotificationStrategy.java, opennms-services/src/test/java/org/opennms/netmgt/notifd/MattermostNotificationStrategyIT.java, opennms-services/src/test/java/org/opennms/netmgt/notifd/SlackCompatibleNotificationStrategyTest.java, opennms-services/src/test/java/org/opennms/netmgt/notifd/SlackNotificationStrategyIT.java
Fix it so leading dashes are expected. Include a warning message if we see a switch name without
a leading dash, so that people can be prompted to update their notification command definitions.
Since we have never shipped a config with such a command on by default, this warning should do
the job.
* JIRA: http://issues.opennms.org/browse/NMS-10552
=> NMS-10552: Slack-compatible notification strategies expect "url" for switch name, should be "-url"

core/web-assets/src/main/assets/js/apps/onms-resources/index.js
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12870
=> NMS-12870: Use generatedId only for Standard Resource graphs

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/search/SearchSuggestion.java, features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/AlarmDaoContainer.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/LegacyApplicationSearchProvider.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/LegacyApplicationTopologyProvider.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutage.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutageDaoContainer.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutageDatasource.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutageSelectionLinkGenerator.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/browsers/ApplicationOutageTable.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/resources/OSGI-INF/blueprint/blueprint.xml
This PR fixed the search for Appliations and adds a table "Current Outages" to the Application Topology Map.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-12823
All current (non resolved) outages of associated monitored location of the displayed applications are shown in the table:
When clicked on the outage id a popop with the outage detail information is shown:
=> NMS-12823: Application Topology Provider Status

core/test-api/services/src/test/resources/org/opennms/netmgt/config/mock/users.xml, core/upgrade/src/test/resources/etc/users.xml, features/springframework-security/src/test/java/org/opennms/web/springframework/security/SpringSecurityUserDaoImplIT.java, features/springframework-security/src/test/resources/org/opennms/web/springframework/security/users.xml, opennms-base-assembly/src/main/filtered/etc/opennms.properties, opennms-base-assembly/src/main/filtered/etc/users.xml, opennms-config/src/main/java/org/opennms/netmgt/config/UserManager.java, opennms-config/src/test/java/org/opennms/netmgt/config/UserFactoryTest.java, opennms-services/src/test/resources/org/opennms/netmgt/notifd/users.xml, opennms-webapp/src/test/opennms-home/etc/users.xml
This PR makes it so you can configure OpenNMS to disallow writing old-style unsalted passwords.
JIRA: https://issues.opennms.org/browse/NMS-12817
=> NMS-12817: allow forcing use of SHA-256 passwords

core/snmp/impl-snmp4j/pom.xml, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java, core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JWrongResponsesTest.java
Handle the case where number of responses are less than requested oids
by filling the missing responses as SNMP_NULL
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12818
=> NMS-12818: Handle Snmp response when number of responses are less than requested oids.

core/lib/src/main/java/org/opennms/core/utils/StringUtils.java, features/api-layer/src/main/java/org/opennms/features/apilayer/config/ThresholdingConfigExtensionManager.java, features/api-layer/src/test/java/org/opennms/features/apilayer/config/ThresholdingConfigExtensionManagerTest.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/BaseThresholdDefConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ExpressionThresholdValueSupplier.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdConfigWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorAbsoluteChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorHighLow.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRearmingAbsoluteChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRelativeChange.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdValuesConsumer.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdValuesSupplier.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorAbsoluteChangeTest.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorHighLowTest.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdEvaluatorRelativeChangeTest.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdExpressionTestCase.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdStateIT.java, features/collection/thresholding/impl/src/test/resources/test-thresholds-2.xml, features/collection/thresholding/impl/src/test/resources/test-thresholds-bug2746.xml, features/collection/thresholding/impl/src/test/resources/test-thresholds-bug3333.xml, opennms-config-model/src/main/java/org/opennms/netmgt/config/threshd/Basethresholddef.java, opennms-config-model/src/main/resources/xsds/thresholding.xsd, opennms-doc/guide-admin/src/asciidoc/text/thresholds/thresholding.adoc, opennms-webapp/src/main/java/org/opennms/web/controller/admin/thresholds/ThresholdController.java, opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editExpression.jsp, opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/thresholds/editThreshold.jsp
Support metadata in Threshold fields like `value` `rearm` `trigger` in Simple-DS and Expression threshold configs.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12794
=> NMS-12794: Add support for metadata for threshold fields

opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
* JIRA: https://issues.opennms.org/browse/NMS-10554
Small correction to the event definition to include also the foreignId.
=> NMS-10554: Added foreignId to the event definition

checkstyle/pom.xml, pom.xml
* JIRA: http://issues.opennms.org/browse/NMS-19690
This PR adds the maven-enforcer-plugin to ensure the version of maven used to compile the source is the same as the version bundled under the maven/ directory.
It also enforces running a specific version of java instead of an maven-ant-plugin target task.
=> NMS-10690: Update Maven & Plugins : maven enforcer plugin

features/api-layer/src/main/java/org/opennms/features/apilayer/utils/ModelMappers.java
Set the AlarmType on the Alarm, so that integrations using the Integration
API can make determinations based upon whether the alarm is one that has a
possible resolution or not.
If you have made additions or changes to the documentation, or if you _need_ documentation for these code …
=> NMS-12923: Integration API: Alarm.type is unset

opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/response/HttpStatusResponse.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/response/MultilineHttpResponse.java, opennms-provision/opennms-detector-lineoriented/src/test/java/org/opennms/netmgt/provision/detector/HttpDetectorTest.java
This changes the HTTP header regex matcher to account for missing reason phrase.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-10351
=> NMS-10351: handle HTTP servers that do not response with a reason phrase

features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Conversation.java, features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Host.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowQueryService.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/RawFlowQueryService.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedFlowQueryService.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedSearchQueryProvider.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/Types.java, features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/agg/hostname.ftl, features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/hostname_by_host.ftl, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/AggregatedFlowQueryIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
This implements hostname querying for aggregated flows processed by nephron
and fixes hostname querying for row flows.
This is accompanied by https://github.com/OpenNMS/nephron/pull/3.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12692
=> NMS-12692: Hostname resolution for flow queries

opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/installing-on-debian.adoc, opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/step-1-install-minion.adoc, opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/debian/step-2-starting-minion.adoc, opennms-doc/guide-install/src/asciidoc/text/monitor-location-minion/rhel/installing-on-rhel.adoc
NMS-12917: Removed sudo commands from document
Once the reviewer(s) accept the PR and the branch passes continuous …
=> NMS-12917: Update minion installation procedures

core/schema/src/main/java/org/opennms/core/schema/Migrator.java, debian/control, opennms-base-assembly/src/main/filtered/etc/opennms.service
A small PR that bumps the acceptable PostgreSQLs to 13.  Their release notes indicate no major changes that should break things, and I did some testing personally against the latest version and everything is behaving fine.
=> NMS-12958: change allowed PostgreSQL ranger to allow 13

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/AlarmRestService.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/AlarmRestServiceIT.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java
This PR fixes the alarm v1 & v2 ReST APIs to allow updating multiple ticket fields _and_ ack/escalate/clear.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12979
=> NMS-12979: fix Alarm ReST PUT operations

features/graph/api/src/main/java/org/opennms/netmgt/graph/api/info/StatusInfo.java, features/graph/provider/application/src/main/java/org/opennms/netmgt/graph/provider/application/ApplicationStatusEnrichment.java, features/graph/provider/application/src/test/java/org/opennms/netmgt/graph/provider/application/ApplicationStatusEnrichmentTest.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.application/src/main/java/org/opennms/features/topology/plugins/topo/application/LegacyApplicationStatusProvider.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/ApplicationDao.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoredServiceStatusEntity.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/util/ReductionKeyHelper.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/ApplicationDaoHibernate.java
This PR addresses these two issues:
-  [NMS-12969: Topology Map: Application: Color of app wrong for acknowledged alarm](https://issues.opennms.org/browse/NMS-12969)
- [NMS-12968: Display the alarm status correctly in topology map for applications](https://issues.opennms.org/browse/NMS-12969)
Background: So far we looked only at the alarms of a node now we look at the perspective alarms of a service.
This is how the map looks after the logic change:
We see that app1 has one perspective alarm on the http service. Therefor the http service is marked orange.
The other services are still green.
The alarms are acknowledged, therefor we see no numbers
The color of the app is the same color as the most severe service.
app3 shows 2 services with unacknowledged alarms. Therefor the services have …
=> NMS-12969: Topology Map: Application

opennms-container/minion/container-fs/confd/conf.d/org.opennms.minion.server-certificates.toml, opennms-container/minion/container-fs/confd/templates/org.opennms.minion.server-certificates.tmpl, opennms-container/minion/container-fs/entrypoint.sh
* copies Java's default trust store and imports configured certificates
* cherry picked from develop (`git cherry-pick 22e5990057dce49818b170c29318094ba88a8726 --no-commit -m 1`)
=> support server certificates

pom.xml
This PR updates to the latest Jetty 9.4.  I ran smoke tests against 2017, 2019, 2020, and 27.x and they all passed.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13009
=> NMS-13009: bump jetty to 9.4.34 for CVE-2020-27216

container/features/src/main/resources/features.xml, dependencies/jcifs/pom.xml, pom.xml, protocols/cifs/src/main/java/org/opennms/netmgt/poller/monitors/JCifsMonitor.java
This PR closes `SMBFile` and `CIFSContext` when finished polling, and fixes a BouncyCastle version mismatch.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13011
=> NMS-13011: close all CIFS resources

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/CoreImportActivities.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/DeleteOperation.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/ImportOperation.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/InsertOperation.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/SaveOrUpdateOperation.java
For requisitions that are synchronized with `no` or `dbonly` flags, SNMP scan is not performed in import phase.
This results SNMP service being discovered first before Node gets updated with system info.
Collectd doesn't perform any SNMP collection if `nodesysoid` is not present and it removes this from it's schedule.
Had to restart OpenNMS or reload `Collectd` to get SNMP collection working.
The solution here identifies a new node being inserted and performs SNMP scan for that node always irrespective of `rescanExisting` value.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12974
=> NMS-12974: Import Scan should be performed always for new nodes

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/KafkaFlowForwarderIT.java, features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/KafkaFlowForwarder.java, features/flows/kafka-persistence/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/telemetry/listeners/src/main/java/org/opennms/netmgt/telemetry/listeners/UdpListener.java, features/telemetry/protocols/flows/src/main/java/org/opennms/netmgt/telemetry/protocols/flows/AbstractFlowAdapter.java, features/telemetry/protocols/netflow/parser/pom.xml, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixTcpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow5UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ipfix/proto/Packet.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow5/proto/Packet.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/Packet.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/SequenceNumberTracker.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/Session.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/TcpSession.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IllegalFlowTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/SequenceNumberTrackerTest.java
This is groundwork used to analyze the situation where we maybe drop flows  during processing with hostname resolution enabled.
This enables a variety of counters related to flow processing. Mostly watching out for error situations but also adding a throughput counter to every stage.
In addition, the packet sequence numbers are check and a log message is generated if a packet is detected missing.
Oh, and it fixes a memory leak if flows are considered illegal.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12973
=> NMS-12973: Adding metrics and checking sequences

opennms-container/minion/Dockerfile
JIRA (Issue Tracker): https://issues.opennms.org/browse/CLOUD-709
=> CLOUD-709: Minion fails to start with enterprise certificate due to missing directory

container/features/src/main/resources/features.xml, core/ipc/rpc/utils/pom.xml, core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderImpl.java, core/ipc/rpc/utils/src/test/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderIT.java, opennms-doc/guide-admin/src/asciidoc/text/meta-data.adoc, pom.xml
JIRA: https://issues.opennms.org/browse/NMS-13036
This allows us to add tags to timeseries metrics that include the geohash which can be used to display metrics on a map.
OpenNMS -> gRPC -> Cortex <- PromQL <- Grafana:
=> NMS-13036: Add Geohash support to the mate-data DSL.

opennms-base-assembly/src/main/filtered/bin/opennms
At the moment it is difficult to debug code that is immediately run on startup. The suspend option helps here.
=> add -T start option for debug and suspend

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpAgentTimeoutException.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java, core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JWrongResponsesTest.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java, core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/MockSnmpStrategy.java, core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModuleTest.java, opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPollInterfaceMonitor.java
Currently Snmp4JStrategy doesn't throw specific exception for timeout and
error scenarios. This results in null response which cause ArrayIndexBound exception
This PR should handle those error scenarios.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13042
=> NMS-13042: Handle error scenarios

core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/FitProfileCommand.java, core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/GetCommand.java, core/snmp/commands/src/main/java/org/opennms/netmgt/snmp/commands/WalkCommand.java
Don't break for Timeout Exception as it's designed to be responsive to user to give output every 1 sec.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13055
=> NMS-13055: Fix Snmp karaf commands

debian/control, opennms-assemblies/minion/src/main/filtered/debian/control, opennms-assemblies/sentinel/src/main/filtered/debian/control, tools/packages/minion/minion.spec, tools/packages/opennms/opennms.spec, tools/packages/sentinel/sentinel.spec
As of RPM 4.13, it now supports `Recommends:` and `Suggests:` like Debian does.  This PR adds a `Recommends:` to both the debian and RPM packages.  Also, I have added `haveged` to the RPM repositories in stable, so it's available without requiring the EPEL repository to be enabled.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-8959
=> NMS-8959: "recommend" haveged package in OpenNMS install

opennms-webapp/src/main/webapp/locations/index.jsp, opennms-webapp/src/main/webapp/minion/index.jsp
A couple Admin pages in the UI were missing breadcrumb links back to the main Admin page. This PR updates only the `Monitoring Locations` and `Manage Minion` jsp pages to include an additional parameter to include the additional link.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13067
=> NMS-13067 Admin Breadcrumbs

.circleci/config.yml, .circleci/scripts/itest.sh, .circleci/scripts/makensis.py, debian/control, makedeb.sh, makerpm.sh, opennms-doc/guide-development/src/asciidoc/text/dev-guide.adoc
With the removal of Windows support and the remote poller installer, we should no longer need anything related to `makensis`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13069
=> NMS-13069: remove all references and deps to nsis

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/FasterFilesystemForeignSourceRepository.java
* [ Y] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ Y] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [ Y] Have you made a comment in that issue which points back to this PR?
* [ Y] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [ NA] If this is a new or updated feature, is there documentation for the new behavior?
* [ N - see note] If this is new code, are …
=> NMS-13082: Reduce log noise by catching harmless exception on cache miss

features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/Utils.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/FlowTimeoutTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpFixProtobufValidationTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/Netflow5ConverterTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/FlowTimeoutTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9ConverterTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9ProtobufValidationTest.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixTcpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixUdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow5UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow9UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/MessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow5MessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ClockSkewTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IllegalFlowTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/NMS13006_Test.java
Flows with invalid start and end values are asumed to exist in a short
timespan before the flow was exported. Therefore we accept the
inaccuracy in time but take the flow into account.
No flow is illegal!
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13088
=> NMS-13088: Adapt invalid flows instead of dropping

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowQueryService.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/agg/AggregatedFlowQueryService.java
Querying aggregated data sotred by nephron involves to resolve hostnames
for queries by host and by conversation. When querying for time-series,
the hostnames are now queryied only once by key instead of every
time-bucket.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13065
=> NMS-13065: Resolve hostname only once

opennms-container/minion/minion-config-schema.yml
The schema described flows configuration incorrectly. This PR updates the schema to the correct form. This schema is only a reference right now and isn't used directly.
This PR also updates the key paths for SSH host port as they were incorrect.
No Jira.
=> Parsers are actually children of listeners not siblings

core/web-assets/package-lock.json, core/web-assets/package.json, core/web-assets/src/main/assets/js/apps/onms-reports/ReportDetails.js, core/web-assets/src/main/assets/js/apps/onms-reports/index.js, core/web-assets/src/main/assets/js/lib/onms-schedule-editor/scripts/ScheduleOptions.js, core/web-assets/src/main/assets/js/lib/onms-schedule-editor/templates/schedule-editor.tpl.html, features/endpoints/grafana/api/src/main/java/org/opennms/netmgt/endpoints/grafana/api/GrafanaClient.java, features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java, integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java, integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/helper/TimezoneHelper.java, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-1ppp.jrxml, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-2ppp.jrxml, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-4ppp.jrxml, opennms-web-api/src/main/java/org/opennms/web/svclayer/support/DefaultSchedulerService.java
I took a two-pronged approach to handling this.
1. Always perform all operations from the point-of-view of the report time zone. Schedule reports based on that zone, render dates in the Grafana reports based on that zone, etc.
2. Give the user visibility into the time zone when scheduling the report.  This means:
* show the time zone right next to the "time" input when scheduling
* based on the schedule, show the next time it would run, in the report's time zone, the server's time zone, and the user's time zone
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13070
=> NMS-13070: fix timezone handling in scheduled reports

features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpFixProtobufValidationTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9ConverterTest.java, features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9ProtobufValidationTest.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixTcpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/SequenceNumberTracker.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/TcpSession.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/session/UdpSessionManager.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/NMS13006_Test.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/SequenceNumberTrackerTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpSessionManagerTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ipfix/BlackboxTest.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/BlackboxTest.java, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/ipfix.adoc, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow9.adoc
This allows flows to be recieved out of order, either because of network related packet reordering or parallel processing.
Flow sequence checks now are more patient. If a flow is missing, it is reported only after the flow sequence has advanced for a certain amount.
The patience of flow sequence tracking has a default of `32` which is sane for almost all use-cases. This makes the patience parameter per parser definition in telemetryd configuration allowing compensate for more paralelized receivers or crazy network.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13106
For reviewers: The first commit improves the sequence tracking mechanism while the second makes the patience parameter configurable.
=> NMS-13106: Allows flows to be received out of order

core/web-assets/src/main/assets/js/apps/onms-reports/ReportDetails.js, core/web-assets/src/main/assets/js/apps/onms-reports/index.js, core/web-assets/src/main/assets/js/apps/onms-reports/modals/schedule-edit-modal.html, core/web-assets/src/main/assets/js/apps/onms-reports/report-details.html
It turns out there were a couple of weird things going on with how this was initializing.  I've made some changes to mitigate them:
1. use a straight AJAX call rather than AngularJS `$resource` which can be problematic
2. when the upstream dashboard timezone is set to `undefined` (ie, "default") we were overwriting the already-configured zone with that undefined value
3. we weren't always updating the `parametersByName['timezone']` property -- this is probably fine, but belt & suspenders I made it happen always when updating the parameter list
4. when checking for malformed zones (like `utc` rather than `UTC`) we were accepting undefined values and overwriting it
5. bonus: when editing an existing report, we don't re-initialize the "endpoint" list; the grafana endpoint should never change …
=> NMS-13064: fix timezone editing for existing reports

core/daemon/src/main/java/org/opennms/netmgt/vmmgr/StatusGetter.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/InfoDTO.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/InfoRestService.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ServiceInfoDTO.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/InfoRestServiceIT.java, opennms-webapp/src/main/webapp/admin/sysconfig.jsp
This PR makes it possible to see OpenNMS service status in the `/info` ReST service.
Sample output:
```json
{
"displayVersion": "26.1.3-SNAPSHOT",
"version": "26.1.3",
"packageName": "opennms",
"packageDescription": "OpenNMS",
"ticketerConfig": {
"plugin": null,
"enabled": false
},
"datetimeformatConfig": {
"zoneId": "America/New_York",
"datetimeformat": "yyyy-MM-dd'T'HH:mm:ssxxx"
},
"services": {
"Eventd": "running",
"Alarmd": "running",
"Bsmd": "running",
"Ticketer": "running",
"Trapd": "running",
"Queued": "running",
"Actiond": "running",
"Notifd": "running",
"Scriptd": "running",
"Rtcd": "running",
"Pollerd": "running",
"PollerBackEnd": "running",
"EnhancedLinkd": "running",
"Collectd": "running",
"Discovery": "running",
"Vacuumd": "running",
"EventTranslator": "running", …
```
=> NMS-13135: add service status to the info ReST service

.circleci/config.yml
Use build environment based on Debian Buster instead of Debian Stretch.
=> Update Debian build environment from Debian Stretch to Buster

features/newts/src/main/java/org/opennms/netmgt/newts/support/CachePrimer.java
The setting to disable the newts cache priming is now interpreted
correctly.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13156
=> NMS-13156: Enable newts cache priming if not disabled

opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmDetailController.java, opennms-webapp/src/main/java/org/opennms/web/controller/alarm/RelatedEvent.java, opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml, opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
Disabled by default.  Enable by setting
org.opennms.web.console.alarms.relatedEvents=true
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13170
=> NMS-13170: add related event view to alarm detail page

opennms-base-assembly/src/main/filtered/bin/daemon-stats.pl, opennms-base-assembly/src/main/filtered/bin/encode-wmi-password.pl, opennms-base-assembly/src/main/filtered/bin/provision.pl, opennms-base-assembly/src/main/filtered/bin/send-event.pl, opennms-base-assembly/src/main/filtered/bin/send-trap.pl, opennms-base-assembly/src/main/filtered/bin/xml.reader.pl, pom.xml, protocols/xml/src/main/contrib/3gpp-datacollection-generator.pl, protocols/xml/src/main/contrib/3gpp-resourcetypes-generator.pl, protocols/xml/src/main/contrib/3gpp-snmpgraphs-generator.pl
Do not use a hard-coded path to perl (either specified during build time
or by using a /usr/bin/perl) but query the environment for the perl
binary to use.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13174
=> NMS-13174: Use perl from environment

opennms-container/minion/MINION_CONFIG_SCHEMA_README.md, opennms-container/minion/minion-config-schema.yml
- Remove set
- Add integer/decimal (not in use yet)
This PR has no functional impact on OpenNMS. Purely a schema update for minion configuration.
Once this PR is merged, I will manually propagate the schema change to the dev cloud to make it live in dev.
=> Update schema types in minion configuration schema

features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/BaseThresholdDefConfigWrapper.java, features/collection/thresholding/impl/src/test/resources/test-multiple-threshold-levels.xml, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java
When there are multiple levels of thresholds for a given DS, the key that is persisted to maintain threshold state is not unique enough.
To solve this, generate stable hash for threshold values and add it to key.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13120
=> NMS-13120: Make threshold state key unique for different threshold levels

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/notification/noticeWizard/chooseUeis.jsp
This fixes the UEI selection in the notice wizard to:
1. actually reset things when you hit the "Reset" button
2. always update the regular expression field whenever state changes
3. restore the full list of options if you filter the results, and then change the filter back to an empty string
4. fix the table to be wide enough to see the full events when the browser is wider
It was hard to keep myself from just rewriting this using angular or something, but I tried to do the minimal amount of changes necessary to make this work rather than replacing or cleaning up gross jQuery stuff, since it targets Meridian, and we'll probably rewrite it anyway when we start working on redoing the UI.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13149
=> NMS-13149: fix behavior of UEI selection

features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java
Small update to #3336 to take care of metadata in threshold values.
Since metadata support is only added in `27.x` for threshold values this is targetted to `release-27.x`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13120
=> NMS-13120: Consider metadata in threshold values.

pom.xml
This PR bumps our Jetty to the latest 9.4 version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13201
=> NMS-13201: upgrade Jetty dependency

.gitignore, opennms-container/minion/CONFD_README.md, opennms-container/minion/Dockerfile, opennms-container/minion/Makefile, opennms-container/minion/container-fs/confd/conf.d/prom-jmx-exporter.toml, opennms-container/minion/container-fs/confd/templates/prom-jmx-exporter.yaml.tmpl, opennms-container/minion/minion-config-schema.yml
Add Prometheus JMX exporter for out of band management of the Minion Java Virtual Machine.
Set yaml formatting and add Prometheus JMX docs.
Added JMX prometheus exporter agent which is disabled by default. It has to be explicitly enabled with the Java option `-javaagent:/opt/prom-jmx-exporter/jmx_prometheus_javaagent.jar=9299:/opt/prom-jmx-exporter/config.yaml`. The port 9299/tcp needs to be published has well.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13072
=> NMS-13072: Add JMX prometheus exporter

container/karaf/src/main/filtered-resources/etc/org.ops4j.pax.logging.cfg
This PR suppresses some logging from Kafka for config entries it doesn't known about (that are set for other things).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13208
=> NMS-13208: suppress Kafka logging for unknown config

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcher.java
* JIRA: https://issues.opennms.org/browse/NMS-13157
The issue was really tricky. The error pattern was as follows: For nodes queried directly via OpenNMS, no response graphs of IPv6 addresses appeared at all, i.e. there were no errors at all. It just seemed that they were simply not present. In the case a Minion was used the response time graphs for IPv6 interfaces were listed but the graphs gave "Query failed." error messages.
It was actually a combination of two errors. In one special case the search()-method of the TimeseriesSearcher class did only line up the path elements without escaping the colons. Furthermore, the cortex plugin did not escape the backslashes itself. This resulted to a query error sind the backslash is the escape character itself and needs to be escaped by a …
=> NMS-13157: Assure that colons are properly escaped every time

features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml
Update the `restTrapConfigurationTimer` so that the interval is configurable.
Note: as soon as I started using a property for this, the `minionproperties` placeholder broke.  I suspect it wasn't even being called at runtime previously since there were no properties referenced in the `camelContext` anyway, but it didn't actively fail until we tried to resolve dynamic values.  As far as I can tell, no minion properties are used directly in the related code, except in places where those properties are already configured/defined.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13217
=> NMS-13217: make trapd config refresh time configurable

features/ticketing/daemon/src/main/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayer.java, features/ticketing/daemon/src/test/java/org/opennms/netmgt/ticketd/DefaultTicketerServiceLayerTest.java, features/ticketing/drools-integration/src/test/java/org/opennms/netmgt/ticketd/DroolsTicketerServiceLayerTest.java, opennms-alarms/daemon/pom.xml, opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmLifecycleListenerManager.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/TestTicketerPlugin.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DefaultAlarmTicketerServiceIT.java, opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java, opennms-alarms/daemon/src/test/resources/applicationContext-test-troubleTicketer.xml, opennms-base-assembly/src/main/filtered/etc/alarmd/drools-rules.d/alarmd.drl, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmEntityListener.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmEntityNotifier.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/DefaultAlarmEntityListener.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/support/AlarmEntityNotifierImpl.java
Currently ticket state changes doesn't trigger any  `AlarmLifeCycleListener` changes needed to insert the updated alarm into drools again.
This results in some bugs in ticketing related workflow in Alarmd drools rules.
Hopefully this PR should fix those bugs.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13189
=> NMS-13189: Trigger updatedAlarm notification for Ticket state changes

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java, features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilIT.java, opennms-base-assembly/src/main/filtered/etc/opennms.properties, opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc
* JIRA: https://issues.opennms.org/browse/NMS-13210
The plan is as follows:
* add flag to clear the %dpname% in foundation-2020, default is false
* remove the flag in develop and always clear %dpname%
So, when this one is merged I'll add another PR to make the changes in develop.
=> NMS-13210: Add flag to clear %dpname% variable

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/shell/ListAlarms.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/shell/SyncAlarms.java, smoke-test/pom.xml, smoke-test/src/main/java/org/opennms/smoketest/utils/OnTimeOutLogger.java, smoke-test/src/main/java/org/opennms/smoketest/utils/SshClient.java, smoke-test/src/test/java/org/opennms/smoketest/KafkaProducerIT.java
Attempt to fix flapping KafkaProducerIT:
* Limit the amount of time we wait for the store to be ready.
* Add additional logging when the test times out - show shell output so far.
No JIRA.
=> flip flop KafkaProducerIT

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixTcpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixUdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow5UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow9UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/UdpParserBase.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Timeout.java, features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ClockSkewTest.java, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/ipfix.adoc, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow5.adoc, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/netflow9.adoc
Some routers do not send active and inactive flow timeout configuration
values even if they are configured on the exporting device. The added
settings allow to configure a fallback for these value per
listener/parser.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13215
=>  NMS-13215: Fallback config for flow timeouts

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/StandardExpandableParameterResolvers.java, features/events/daemon/src/test/java/org/opennms/netmgt/eventd/EventUtilIT.java, opennms-doc/guide-admin/src/asciidoc/text/events/event-configuration.adoc
* JIRA: https://issues.opennms.org/browse/NMS-13210
This is the follow-up for NMS-13210 for develop. %dpname% will now return an empty string.
=> NMS-13210: Clear %dpname% variable

container/features/src/main/resources/features.xml, features/telemetry/protocols/adapters/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractAdapter.java, features/telemetry/protocols/bmp/adapter/pom.xml, features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpMessagePersister.java, features/telemetry/protocols/bmp/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpMessagePersisterIT.java, features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/BmpParser.java, features/telemetry/protocols/bmp/persistence/api/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/persistence/api/BmpRouter.java, opennms-doc/guide-admin/src/asciidoc/text/telemetryd/protocols/bmp.adoc
Sometimes PeerUp notification may come up before Router initiation message.
This may result in peer not getting persisted.
Caching Peers that arrive before Router and persisting them with router should
resolve this.
Also added synchronization around persisting bmp messages.
While running multiple threads within the same session, we may have duplicates
which may result in errors.
Also add Note in doc for BMP,  When Kafka is used. `auto.offset.reset=earliest` need to be set on BMP Adapter.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13224
=> NMS-13224: Fix some timing issues with BMP

opennms-container/minion/container-fs/entrypoint.sh
Issue: https://issues.opennms.org/browse/NMS-13101
The properties files under `opennms.properties.d` are now appended to the `custom.system.properties` file that is loaded by Karaf.
=> NMS-13101: consider properties files under opennms.properties.d when starting Minion

.circleci/scripts/itest.sh, features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/JRrd2FetchStrategy.java, features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/RrdtoolXportFetchStrategy.java, features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/JRrd2FetchStrategyTest.java, features/measurements/impl/src/test/java/org/opennms/netmgt/measurements/impl/RrdtoolXportFetchStrategyTest.java
The datasource names are trimmed while storing. But queries failed if
long names where used. This truncates the datasource names for queries
in the same way as they are truncated while persisting.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13060
=> NMS-13060: Truncate long datasource names to RRD limits

opennms-container/minion/Dockerfile, opennms-container/minion/Makefile
Updating the Minion deploy base image from 1.0.0 which used OpenJDK 11.0.6 to 1.2.0 with OpenJDK 11.0.7 plus the tzdata package for handling time zones. I ran the smoke tests as well to make sure I don't break them with the JDK and base image version bump :)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13276
=> NMS-13276: Use updated deploy-base image with tzdata package

features/situation-feedback/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, opennms-doc/guide-admin/src/asciidoc/text/alarm-correlation/situation-feedback.adoc, opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc
Issue: [NMS-12767](https://issues.opennms.org/browse/NMS-12767)
* rename configuration file `org.opennms.features.situation-feedback.persistence.elastic` -> `org.opennms.features.situationfeedback.persistence.elastic`
Reason: A minus sign in filenames of configuration files that are loaded by file installer has special meaning (cf. [file install configurations](https://felix.apache.org/documentation/subprojects/apache-felix-file-install.html#configurations)).
=> NMS-12767: Situation feedback configuration not loaded

core/api/src/main/java/org/opennms/core/config/api/BeanConfigurationProvider.java, core/api/src/main/java/org/opennms/core/config/api/ConfigReloadContainer.java, core/api/src/main/java/org/opennms/core/config/api/ConfigurationProvider.java, features/api-layer/src/main/java/org/opennms/features/apilayer/config/ConfigExtensionManager.java
Issue: https://issues.opennms.org/browse/NMS-12766
* Triggers configuration reloads after configuration providers get registered/unregisterd with the `ConfigReloadContainer` (this fixes a race condition between provider registration and extension binding; cf. issue)
* Fixes subtle multi-threading issues in `ConfigReloadContainer`
* Fixes a logical error in `ConfigReloadContainer.checkForUpdates`. In case the last provider got unregistered the config object gets now set to `null`
=> NMS-12766: Fix race condition when loading event configurations

opennms-doc/guide-admin/src/asciidoc/text/provisioning/import-handler.adoc, opennms-provision/opennms-requisition-dns/src/main/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionProvider.java, opennms-provision/opennms-requisition-dns/src/main/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionRequest.java, opennms-provision/opennms-requisition-dns/src/main/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionUrlConnection.java, opennms-provision/opennms-requisition-dns/src/test/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionRequestTest.java, opennms-provision/opennms-requisition-dns/src/test/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionUrlConnectionIT.java
* JIRA: https://issues.opennms.org/browse/NMS-13278
Allow a new `location` parameter in DNS requisition Urls. You can specify a single location that will be associated with all nodes by specifying for example something like `?location=Raleigh`. Furthermore, by preceding a `~` you can specify a properly encoded regular expression to determine the location based on the host entries. This expression must have exactly on capturing group. For instance you can associate a node to a location given by their subdomain with the expression `^(?:.\.|)(.?)\.example\.com\.$`.
=> NMS-13278: Making the DNS requisition location-aware

dependencies/jcifs-shaded/pom.xml, dependencies/jcifs/pom.xml, dependencies/jinterop/pom.xml, dependencies/pom.xml, pom.xml
This allows OpenNMS to avoid bountycastle jar in default lib.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13111
=> NMS-13111: Make shaded version for jcifs-ng and bountycastle

docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc, docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc, docs/modules/deployment/pages/core/getting-started.adoc
Add Meridian repository installation instructions for CentOS 7 and CentOS 8.
Added instructions installing the Meridian repositories. The credentials for Meridian repositories are added as requirements.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13294
=> NMS-13294: Add Meridian installation guide

opennms-config-model/src/main/resources/xsds/thresholding.xsd, opennms-config-model/src/test/java/org/opennms/netmgt/config/threshd/ThresholdingConfigTest.java
Add regex validation for threshold values:
Metadata notation  OR float value for  `value` and `rearm`
Metadata notation OR positive integer for `trigger`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-12689
=> NMS-12689: Add regex to limit threshold values

features/nrtg/api/pom.xml, features/nrtg/commander/pom.xml, features/nrtg/jar/nrtcollector/pom.xml, features/nrtg/nrtbroker-jms/pom.xml, features/nrtg/nrtbroker-local/pom.xml, features/nrtg/nrtcollector/pom.xml, features/nrtg/protocolcollector/tca/pom.xml, features/nrtg/web/pom.xml, features/reporting/dao/pom.xml, features/reporting/repository/pom.xml, features/reporting/sdo/pom.xml, opennms-tools/config-normalizer/pom.xml, pom.xml
This PR bumps logback-classic to the latest 1.2 version, and also cleans up the dependency tree a bit.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13361
=> NMS-13361: bump logback-classic to 1.2.3

pom.xml
This PR bumps our Httpclient to the latest 4.5 version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13360
=> NMS-13360: bump Apache Httpclient to 4.5.13

features/collection/snmp-collector/src/main/java/org/opennms/netmgt/collectd/SnmpIfData.java, opennms-services/src/main/java/org/opennms/netmgt/collectd/DefaultSnmpCollectionAgent.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpIfCollectorIT.java
JIRA: https://issues.opennms.org/browse/NMS-11764
Change the behavior to avoid adding SNMP interfaces will null/blank labels to the CollectionSet rather than throwing an exception when these are processed.
This allows other resources in the CollectionSet to be processed.
Can backport further if we see fit.
=> NMS-11764: Don't add SNMP interfaces will null/blank labels to the CollectionSet

.circleci/config.yml, .circleci/scripts/publish-cloudsmith.sh, opennms-container/horizon/build_container_image.sh, opennms-container/launch_yum_server.sh, opennms-container/minion/Dockerfile, opennms-container/minion/Makefile, opennms-container/minion/build_container_image.sh, opennms-container/minion/minion-config-schema.yml.in, opennms-container/sentinel/build_container_image.sh
This PR publishes the `minion-config-schema.yml` to Cloudsmith, in a new project called `config-schema`.
The URLs should be guessable based on branch and version, ie, a released version of Horizon 28.0.1 will be at the URL:
https://packages.opennms.com/public/config-schema/raw/names/master-28-minion-config-schema.yml/versions/28.0.1/minion-config-schema.yml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13285
=> NMS-13285: publish minion-config-schema.yml to Cloudsmith

opennms-base-assembly/src/main/filtered/bin/opennms
Allow setting `-Xms` in `opennms.conf` without needing to add it to `ADDITIONAL_MANAGER_OPTIONS`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13367
=> NMS-13367: allow setting -Xms as well

core/ipc/rpc/utils/src/main/java/org/opennms/core/rpc/utils/mate/EntityScopeProviderImpl.java, core/web-assets/src/main/assets/js/apps/onms-central-search/quicksearch.html, features/search/api/src/main/java/org/opennms/netmgt/search/api/SearchResultItem.java, features/search/providers/pom.xml, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/FilterSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/SearchResultItemBuilder.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeAssetSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeCategorySearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeGeolocationSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeIpSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeLabelSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeMetaDataSearchProvider.java, features/search/providers/src/main/java/org/opennms/netmgt/search/providers/node/NodeServiceSearchProvider.java, features/search/providers/src/main/resources/OSGI-INF/blueprint/blueprint.xml, opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: https://issues.opennms.org/browse/NMS-13378
* Added search provider for meta-data values. 
* Introduced a new property `org.opennms.netmgt.search.info` which allows to add a custom line to search results. For instance you can define something like `org.opennms.netmgt.search.info=${node:sys-contact} (Department: ${asset:department})` to always display the sys-contact and the department below the node match.
=> NMS-13378: Added Meta-Data search and custom information

docs/modules/operation/pages/telemetryd/protocols/ipfix.adoc, docs/modules/operation/pages/telemetryd/protocols/netflow9.adoc, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixTcpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/IpfixUdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/Netflow9UdpParser.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java, features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java
Some routers do not send sampling interval configuration
values even if they are configured on the exporting device. The added
settings allow to configure a fallback for these value per
listener/parser.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13322
=> NMS-13322: Fallback config for flow sampling interval

core/ipc/rpc/shell-commands/src/main/java/org/opennms/core/rpc/commands/StressCommand.java, docs/modules/operation/pages/provisioning/import-handler.adoc, features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JDBCMonitor.java
Is this here maybe a german thing? I think milliseconds needs to have two `ll` :)
=> Fix typos for millisecond unit

opennms-assemblies/minion/src/main/filtered/etc/org.opennms.features.telemetry.listeners-single-port-flows.cfg, opennms-container/minion/Dockerfile
Issue: https://issues.opennms.org/browse/NMS-13265
=> NMS-13265: add default configuration for flow listeners to rpm/deb package but not to minion image

docs/modules/operation/pages/kafka-producer/configure-kafka.adoc, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersister.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaMetricsMaxSizeIT.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaPersisterIT.java
One protobuf size for metrics could be > 1MB which may suffer from `MessageSizeTooLargeException` errors in Kafka.
To resolve this divide collectionset into multiple resources and attributes by bisecting them recursively until max size of resulting proto is < 1MB  and send them to kafka.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13407
=> NMS-13407: Divide CollectionSet into multiple chunks

.circleci/config.yml, opennms-container/minion/Dockerfile, opennms-container/minion/Makefile
NMS-13433: We want to avoid publishing Minion images to the registry which don't pass the Minion tests. I've added an additional requirement to finish the Minion smoke tests first before building and publishing single and multi-arch Minion images. The Minion OCI image which is used in the Minion smoke tests is built very early in the Minion tarball assembly step.
NMS-13432: Move dependencies to deploy base image
* Upgrade deploy-base image to jre-1.2.0.b105
* Update JMX Prometheus exporter from 0.15 to 0.16
* Update Ubuntu base image from …
=> NMS-13432/NMS-13433: Move dependencies to deploy base image and publish OCI after smoke tests

features/config/api/pom.xml, features/config/api/src/main/java/org/opennms/features/config/api/ConfigurationManager.java, features/config/pom.xml, features/config/srv/pom.xml, features/config/srv/src/main/java/org/opennms/features/config/srv/ConfigurationManagerSrv.java, features/pom.xml
This PR adds a skeleton project to start with the implementation of the configuration manger.
JIRA: https://issues.opennms.org/browse/PE-6
=> PE-6: add skeleton for configuration manager project

docs/modules/deployment/pages/core/centos-rhel/firewall-core.adoc, docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc, docs/modules/deployment/pages/core/debian-ubuntu/firewall-core.adoc, docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc, docs/modules/deployment/pages/core/getting-started.adoc
I've created a separate section in the Installation procedure covering just the function receiving SNMP Trap/Informs which is enabled by default. I've removed the Syslogd part cause it is a) a separate feature and b) is disabled by default.  I think covering it in a documentation section that describes the Syslogd scenario would make more sense to me.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13016
=> NMS-13016: Add docs for non-privilged ports and non-root ping

pom.xml
This PR bumps our Jetty dependency to the latest version in the 9.x series.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13449
=> NMS-13449: bump jetty to 9.4.43.v20210629

features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/model/IpInterfaceTopologyEntity.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/TopologyEntityDaoHibernate.java, features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/NodeTopologyServiceImpl.java, features/topology-map/plugins/org.opennms.features.topology.plugins.browsers/src/main/java/org/opennms/features/topology/plugins/browsers/NodeDaoContainer.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/IpInterfaceDaoHibernate.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/MonitoredServiceDaoHibernate.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java, opennms-dao/src/test/java/org/opennms/netmgt/dao/IpInterfaceDaoIT.java, opennms-dao/src/test/java/org/opennms/netmgt/dao/hibernate/IpInterfaceDaoHibernateIT.java, opennms-model/src/main/java/org/opennms/netmgt/model/CharacterUserType.java, opennms-model/src/main/java/org/opennms/netmgt/model/OnmsIpInterface.java, opennms-model/src/main/java/org/opennms/netmgt/model/PrimaryType.java, opennms-model/src/main/java/org/opennms/netmgt/model/PrimaryTypeAdapter.java, opennms-model/src/main/java/org/opennms/netmgt/model/PrimaryTypeUserType.java, opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionInterface.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java, opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/DefaultPollContext.java, opennms-tools/access-point-monitor/src/main/java/org/opennms/netmgt/accesspointmonitor/DefaultPollingContext.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaBehaviors.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/CriteriaValueConverters.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/IpInterfaceRestService.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/IpInterfaceRestServiceIT.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeRestServiceIT.java, opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
This PR does a bunch of plumbing work to fix querying nodes and interfaces based on their SNMP primary status.  Note: this work is necessary to complete the work for HELM-188.
- add `OnmsIpInterface#getSnmpPrimary` and move the hibernate annotation to it to make ReST mapping happy, `#getIsSnmpPrimary` is left in place so that a bunch of code doesn't need changing (including end-user groovy code); this includes creating a `CharacterUserType` adapter for Hibernate
- change PrimaryType to not be an `Embedded` Hibernate column, instead just make it a property of `OnmsIpInterface` to avoid API changes
- refactor `PrimaryTypeAdapter` from Provisiond into `opennms-model` so it can be live with other type adapters
- fix internal HQL queries to use `.snmpPrimary` rather than `.isSnmpPrimary`
- …
=> NMS-13469: fix ReST queries for OnmsIpInterface snmpPrimary

container/features/src/main/resources/features.xml, container/karaf/pom.xml, container/shared/pom.xml, core/test-api/karaf/pom.xml, dependencies/cxf/pom.xml, dependencies/hibernate/pom.xml, dependencies/spring-web/pom.xml, features/reporting/availability/pom.xml, opennms-base-assembly/pom.xml, opennms-base-assembly/src/main/filtered/bin/runjava, opennms-full-assembly/pom.xml, opennms-services/pom.xml, opennms-webapp/pom.xml, pom.xml, smoke-test/pom.xml
This PR just fixes a couple of JDK11-related issues.
* exclude `xml-apis` from dependencies since it's included in the base JDK -- Eclipse would complain about classes being in the `jaxb` module as well as outside a module
* fix the "minimum JDK" detection in `runjava -s` now that JDK8 is disallowed
* build/run smoke tests under JDK11
There are still a few `pom.xml` files that target 1.8, it's not clear if there was a reason in @j-white's original branch to leave them that way or not. I left them alone for now.
=> JDK11 Fixes

docs/antora.yml
=> OpenNMS H28+ requires OpenJDK 11

features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java
* JIRA: https://issues.opennms.org/browse/NMS-13486
The PCAP file showed a pretty uncommon Option Template with a observation id scope (system scope) and defined values for absolute timestamps (information element 152 and 153) and the observation domain name. As far as I understand this means something like this: the system identified by the observation domain id X is named Y during the period of time between W and Z. But in this case I would expect the timestamps to be part of the scope. But something like this isn’t really defined in the RFC, since scopes are matched value by value and no intervals are checked at all. This also means that each an every flow that matches the system id will be set the two timestamps given in the option template. We now assure, that these values set by the …
=> NMS-13486: Do not alter FIRST_SWITCHED or LAST_SWITCHED by option record if already set by data record

docs/modules/operation/pages/elasticsearch/introduction.adoc, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java, features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/AggregatedFlowQueryIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/BulkingIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
The elastic flow repository now collects flow documents for batch
insertion across multiple logs. Each worker thread has its own
bulk storage.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13478
=> NMS-13478: Add bulking to elastic flow repository

opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionException.java, opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionValidator.java, opennms-container/horizon/Dockerfile, opennms-container/horizon/container-fs/entrypoint.sh, opennms-install/src/main/java/org/opennms/install/Installer.java, tools/packages/opennms/opennms.spec
This PR changes the Horizon Docker image to use `rsync` for all overlay operations, including using `--chown` to make the ownership match the container user.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13436
=> NMS-13436: fix handling of permissions/ownership when running as root

features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/AsyncReloadingClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationService.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/Tree.java, features/flows/classification/engine/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/ExampleRulesTest.java, smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java
Issue: https://issues.opennms.org/browse/NMS-13479
While editing classification rules, reloads of the classification engine are triggered repeatedly. A reload may take a couple of seconds depending on rule set sizes. In order to avoid sluggish behavior, reloading is done asynchronously. Only when the classification engine is used calls are blocked until any ongoing reloads did finish.
These changes fix the tests in `ClassificationRulePageIT`.
=> NMS-13479: Reload classification decision tree asynchronously in DefaultClassificationService

.circleci/config.yml, opennms-container/minion/Dockerfile, opennms-container/minion/Makefile, opennms-container/minion/container-fs/entrypoint.sh
This is the first half of the work to backport DCT to foundation 2021 for use in Meridian Minion.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13568
=> NMS-13568: backport docker content trust minion builds to Foundation 2021

opennms-container/horizon/CONFD_README.md, opennms-container/horizon/container-fs/confd/conf.d/newts.properties.toml, opennms-container/horizon/container-fs/confd/templates/newts.properties.tpl
This PR merges a few small commits related to cassandra and confd that didn't make it into Foundation 2021.  As far as I can tell, there's nothing else (besides the JMX prometheus work, that won't be backported).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13573
=> NMS-13573: Backporting cassandra confd config allowing arbitrary key/values pairs

opennms-container/README.md, opennms-container/set-build-environment.sh
This PR changes how $REVISION is set for docker containers.
Currently it's running `git describe --always` which goes back into history looking for a related tag to be considered "base", and then adds the short hash to the end. As of now, this usually matches `meridian-foundation-2021.1.4` which is technically not wrong, and is unique, but is not a very intuitive value for, say, develop snapshots.
This change makes it be the branch name + pom version + short hash.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13587
=> NMS-13587: change how "$REVISION" is created by default

features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationEngine.java, features/flows/classification/engine/impl/pom.xml, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/AsyncReloadingClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/ClassificationEngineInitializer.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/ClassificationEngineReloader.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationService.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/TimingClassificationEngine.java, features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/decision/Tree.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/AsyncReloadClassificationEngineTest.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/ClassificationEngineBenchmark.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineIT.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngineTest.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationServiceIT.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/ExampleRulesTest.java, features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/RandomClassificationEngineTest.java, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/DocumentEnricherTest.java, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/FlowDocumentTest.java, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepositoryIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/NodeIdentificationIT.java
Issue: https://issues.opennms.org/browse/NMS-13580
This PR cancels on-going flow classification engine reloads when another reload is requested and starts the new reload immediately. This improves responsiveness when editing classification rules.
=> NMS-13580: cancel on-going classification engine reloads

core/health/shell/src/main/java/org/opennms/core/health/shell/HealthCheckCommand.java, core/health/shell/src/main/java/org/opennms/core/health/shell/HealthCheckTagCompleter.java
issue: https://issues.opennms.org/browse/NMS-13592
For auto-completion the tags of all know health checks are collected.
=> NMS-13592: add --tag argument to health-check command

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/TrapIdentity.java, features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java, features/events/traps/src/test/resources/org/opennms/netmgt/trapd/eventconf.xml
Add  trapoid field for SNMP v1 Traps.
Always fill trapoid field by falling back to enterpriseId
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13586
=> NMS-13586: Add trapoid changes to SNMP V1 Traps

core/schema/src/main/java/org/opennms/core/schema/Migrator.java, debian/control, docs/modules/releasenotes/pages/whatsnew.adoc
This PR adds PostgreSQL 14 to the allowed/supported versions.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13714
=> NMS-13714: allow PostgreSQL 14.x

core/ipc/twin/kafka/subscriber/src/main/resources/OSGI-INF/blueprint/blueprint-twin-subscriber.xml
This should help to check if `org.opennms.core.ipc.twin.kafka.cfg` configured with right `bootstrap.servers`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13663
=> NMS-13663: Add health check for Kafka Twin

opennms-base-assembly/src/main/filtered/bin/fix-permissions, opennms-base-assembly/src/main/filtered/bin/update-package-permissions
@christianpape ran into a weird issue with "argument list too long" when running `chown` on the opennms share directory.
It turns out this comes from a strange interaction between argument limits when running `sudo` inside `xargs`, instead of the other way around.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13736
=> NMS-13736: fix xargs interaction with chown and ARG_MAX

debian/control, debian/rules
This PR splits the WSMan asset plugin into its own package, like the RPMs.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13747
=> NMS-13747: split out wsman asset plugin

core/test-api/lib/src/main/java/org/opennms/core/test/MockLogger.java
I don't think this part is going to fail, given the 17 billion times it's been run, and it sure does add junk to the logs.
=> get rid of log message initializing MockLogger

opennms-config-model/src/main/resources/xsds/snmp-metadata-adapter-configuration.xsd, opennms-config-model/src/test/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfigTest.java
Quick fix for multiple config blocks in snmp metadata config.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13752
=> NMS-13752: allow more than one <config> block

opennms-base-assembly/src/main/filtered/bin/ensure-user-ping.sh, opennms-base-assembly/src/main/filtered/bin/fix-permissions, opennms-base-assembly/src/main/filtered/bin/runjava, opennms-base-assembly/src/main/filtered/bin/update-package-permissions, opennms-base-assembly/src/main/filtered/bin/upgrade
On upgrade, there could be cases where `opennms.conf` exists but does not contain a `RUNAS=` line, which would cause it no not be set at all.  This PR fixes that, and also cleans up the logic in a couple of other files.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13748
=> NMS-13748: fix $RUNAS logic in a number of places

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/NodeDocument.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/ApplicationKey.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/ExporterKey.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java, features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java, features/flows/elastic/src/test/resources/flow-document-netflow5.json, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/NodeIdentificationIT.java, features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AbstractInterfaceToNodeCache.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/InterfaceToNodeCache.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockInterfaceToNodeCache.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java
This extends the InterfaceToNodeCache to store the actual ipInterfaceId
of the interface to be used to identify the node. In addition, the
interface ID is added to the elasticsearch document.
The ipInterfaceId ultimatively identifies an exporter and is therefor
used for per-exporter caching.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13771
=> NMS-13771: Use ipInterfaceId as exporter key

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/rancid/rancidAdmin.jsp, opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/storage/storageAdmin.jsp, opennms-webapp/src/main/webapp/admin/index.jsp
We have in our global Web UI the "Help" menu which is always available and guides you to the official documentation. I don't think we have to tell on every other place where you can go to the documentation to get more detailed information :)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13779
=> NMS-13779: Remove links to the wiki

features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/IpNetToMediaDao.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/IpNetToMediaDaoHibernate.java, opennms-config/src/main/java/org/opennms/netmgt/filter/JdbcFilterDao.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/IpInterfaceDao.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SnmpInterfaceDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockIpInterfaceDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockSnmpInterfaceDao.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/IpInterfaceDaoHibernate.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java, opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactory.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java
Issue: https://issues.opennms.org/browse/NMS-13507
The current implementation used hundreds of separate SQL selects to retrieve the information necessary to derive bridge links. On a customer database the request `http://localhost:8980/opennms/api/v2/enlinkd/bridge_links/1322` took tens of seconds.
This PR prefetches some of the required information by bulk selects and uses caches for other information that are also loaded by  bulk selects. In summary, the improvements sped up rest request to around 125 milliseconds.
=> NMS-13507: Speedup node link derivations

opennms-webapp/src/main/webapp/about/index.jsp
=> NMS-13579: Fix link for release notes in about page

features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/CdpElementDao.java, features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/LldpElementDao.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/CdpElementDaoHibernate.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpElementDaoHibernate.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/NodeDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockNodeDao.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/NodeDaoHibernate.java, opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactory.java, opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactoryInterface.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeLinkRestService.java
Issue: https://issues.opennms.org/browse/NMS-13507
This PR adds more bulk fetches and share caches for `BridgeElement` and `OnmsSnmpInterface` instances between different subtasks when all kinds of links are retrieved.
The results returned changed slightly because in the original implementation there was a bug in the `EnLinkdElementFactory.getFromCdpCacheDevicePort` method. The constructed `where` clause was not correct. The fix results in more specific cdp link information being retrieved.
=> NMS-13507: speed-up enlinkd link retrieval by bulk fetching and caching

opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml
I have targeted the PR for foundation-2021 cause this is the first release we introduced our own implementation for persisting BMP telemetry data and is a bug in our default shipped configuration. We can easily move it forward to release-29.x branch if it is not important enough to break our point release policy for Meridian and config changes.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13812
=> NMS-13812: Add default RRD package for BMP telemetry persistence

pom.xml
This PR bumps to the latest version of log4j2.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13850
=> NMS-13850: update to Log4j2 2.15.0

features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/Log4j2StringAppender.java
Foundation 2018 version of pr #3985
* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}
=> NMS-13850: update to Log4j2 2.15.0 (foundation-2018)

features/poller/remote/src/main/java/org/opennms/netmgt/poller/remote/support/Log4j2StringAppender.java, pom.xml
This PR bumps to the latest version of log4j2.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13850
=> NMS-13850: update to Log4j2 2.15.0 (foundation-2017)

container/karaf/pom.xml, container/shared/pom.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/pom.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProvider.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdEdgeStatusProviderTest.java, pom.xml
This PR fixes logging dependencies both inside and outside of Karaf.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13858
=>  NMS-13858: fix logging dependencies (Foundation 2020)

container/karaf/pom.xml, container/shared/pom.xml, pom.xml
This PR fixes logging dependencies both inside and outside of Karaf.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13858
=> NMS-13858: fix logging dependencies (Foundation 2019)

container/karaf/pom.xml, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/karaf/src/main/filtered-resources/etc/startup.properties, container/shared/pom.xml, container/shared/src/main/filtered-resources/etc/overrides.properties, container/shared/src/main/filtered-resources/etc/startup.properties, pom.xml
This PR does a number of things to deal with logging version updates:
* updates to the latest `log4j2` and `pax-logging-*` dependencies
* creates an `etc/overrides.properties` file for Karaf to make sure that it _always_ uses the newer `pax-logging-*`,
even if an external feature is pulled in
* simplifies the code to replace the latest `pax-logging-*` jars in our Karaf bundles
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13868
=> NMS-13868: update logging dependencies

features/api-layer/core/src/main/java/org/opennms/features/apilayer/dao/InterfaceToNodeCacheImpl.java, features/discovery/src/main/java/org/opennms/netmgt/discovery/UnmanagedInterfaceFilter.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AbstractInterfaceToNodeCache.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/InterfaceToNodeCache.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockInterfaceToNodeCache.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImpl.java, opennms-dao/src/test/java/org/opennms/netmgt/dao/hibernate/InterfaceToNodeCacheDaoImplIT.java, pom.xml
Issue: https://issues.opennms.org/browse/NMS-13782
This PR prevents unsynchronized access to the mutable internal data structure of `InterfaceToNodeCache`.
=> NMS-13782: fix synchronization issue in InterfaceToNodeCache

pom.xml
This is a version of https://github.com/OpenNMS/opennms/pull/4055 that is updated for pax-logging 2.x in newer embedded Karaf.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13878
=>  NMS-13878: bump pax-logging and log4j2 to latest versions

.circleci/config.yml
This PR does a few things:
1. Get rid of the alias-based `defaults:` parameters block, and just turn them into "global" parameters instead.
This makes them easier to access from anywhere in the CircleCI config.
2. Creates some new parameters used to trigger sub-builds.
3. Creates a new "pre-build" workflow that is the only thing triggered by default.
4. Disables the weekly coverage run for now, dynamic configs + triggers is not supported.
We should probably do this a different way anyway.
Note that I don't actually use the CircleCI-provided orb for path-filtering; it doesn't support caching the `.git` checkout, so it was taking an inordinate amount of time to run a full checkout on every new build.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13818
=> NMS-13818: split docs and main build in CircleCI

features/config/upgrade/src/main/java/liquibase/ext2/cm/change/ImportConfiguration.java, features/config/upgrade/src/main/resources/changelog-cm/30.0.0/changelog-cm.xml, features/config/upgrade/src/main/resources/liquibase.parser.core.xml/dbchangelog-ext.xsd, features/config/upgrade/src/test/resources/org/opennms/config/upgrade/LiquibaseUpgraderIT-changelog.xml, features/config/upgrade/src/test/resources/org/opennms/config/upgrade/LiquibaseUpgraderIT-changelog2.xml
This PR removes configId from the importConfig statement in liquibase since it is always "default".
* JIRA (Issue Tracker): https://issues.opennms.org/browse/PE-1
=> PE-1: Simplify importConfig: use default value for configId

docs/modules/development/pages/rest/resources.adoc, features/api-layer/src/main/java/org/opennms/features/apilayer/dao/InterfaceToNodeCacheImpl.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ResourceRestService.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/ResourceRestServiceIT.java
Issue: https://issues.opennms.org/browse/NMS-13863
This PR adds the `/rest/resources/select` endpoints that allows to select parts of node resources for several nodes in one go. This endpoint is meant to be used by the performance datasource when string properties are retrieved.
=> NMS-13863: Add rest endpoint to select partial node resources

opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionValidator.java, opennms-install/src/main/java/org/opennms/install/Installer.java, opennms-install/src/test/java/org/opennms/install/InstallerTest.java
Fix the permissions-testing to skip files _under_ `.git`, not just the `.git` directory itself. 😅
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13860
=> NMS-13860: fix .git-directory validation, make verifyFilesAndDirectories testable

.circleci/config.yml
This PR splits out the UI build into a separate workflow.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13819
=> NMS-13819: only build UI when UI changes

.circleci/config.yml
Since the main `build` job already does a full build, adding on the `javadoc:aggregate` costs essentially nothing. This means we don't have to go through an entire aggregate step later during the `tarball-assembly` phase.
This technically misses javadoc from anything that's in the assembly rather than compile, but we should not be publishing APIs in there anyway.  :D
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13820
=> NMS-13820: move javadoc to main build

container/features/pom.xml, container/features/src/main/resources/features-sentinel.xml, container/features/src/main/resources/features.xml, core/pom.xml
This PR add's @jeffgdotorg's handy core command stuff to our default containers
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13910
=> NMS-13910: add org.opennms.core.commands to our karaf containers

features/endpoints/grafana/rest/src/main/java/org/opennms/netmgt/endpoints/grafana/rest/internal/GrafanaEndpointRestServiceImpl.java
This PR makes sure exceptions don't leak to the error message in the UI or ReST responses.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13917
=> NMS-13917: scrub error message to be more generic if connection fails

smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java, smoke-test/src/main/java/org/opennms/smoketest/utils/RestHealthClient.java, smoke-test/src/test/java/org/opennms/smoketest/minion/MinionSshIT.java, smoke-test/src/test/java/org/opennms/smoketest/sentinel/SentinelSshIT.java
Updated ssh Health Check with Rest Health check for Minion and Sentinel.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13645
=> NMS-13645 Smoke tests should use HealthCheck Rest instead of connecting to SSH

docs/modules/development/nav.adoc
Added missing new health_rest doc to navigation
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13386
=> NMS-13386 Add docs to Health-Check Rest API

opennms-base-assembly/src/main/filtered/bin/fix-karaf-setup.sh
This PR updates the `fix-karaf-setup.sh` script to rerun itself as `$RUNAS` if possible.  It also cleans up the output a little bit to be clearer.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13881
=> NMS-13881: make the fix-karaf-setup script rerun as $RUNAS

container/features/src/main/resources/features.xml, opennms-provision/opennms-requisition-service/pom.xml
This PR fixes an issue with model objects being inaccessible on the Minion when provisioning.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13927
=> NMS-13927: fix org.opennms.netmgt.model.PrimaryTypeAdapter not found when marshalling

docs/antora.yml
Publish only docs for the major version number.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13865
=> NMS-13865: Set version number for docs to the major version

docs/modules/operation/nav.adoc, docs/modules/operation/pages/flows/data-collection.adoc, docs/modules/operation/pages/flows/setup.adoc, docs/modules/operation/pages/flows/thresholding.adoc, docs/modules/reference/pages/telemetryd/protocols/ipfix.adoc, docs/modules/reference/pages/telemetryd/protocols/netflow5.adoc, docs/modules/reference/pages/telemetryd/protocols/netflow9.adoc, docs/modules/reference/pages/telemetryd/protocols/sflow.adoc, opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml
* JIRA: https://issues.opennms.org/browse/NMS-13707
Please note: using a resource-filter in a flowApp threshold definition is currently broken (see NMS-13945). So the example configs won't work but will work when NMS-13945 is fixed.
=> NMS-13707: Added docs for Flow Thresholding

features/collection/thresholding/api/src/main/java/org/opennms/netmgt/threshd/api/ThresholdingService.java, features/collection/thresholding/api/src/main/java/org/opennms/netmgt/threshd/api/ThresholdingSessionKey.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/AbstractThresholdEvaluatorState.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/CollectionResourceWrapper.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/DefaultThresholdingSetPersister.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingServiceImpl.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSessionImpl.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSessionKeyImpl.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSetImpl.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingVisitorImpl.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/CollectionResourceWrapperIT.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/MockCollectionResourceWrapper.java, features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/MockSession.java, features/collection/thresholding/impl/src/test/resources/test-thresholds-bug3554.xml, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/LatencyThresholdingSetIT.java, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingSessionIT.java, features/collection/thresholding/itests/src/test/java/org/opennms/netmgt/threshd/ThresholdingVisitorIT.java, features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java, features/perspectivepoller/src/main/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerd.java, features/telemetry/protocols/adapters/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/AbstractCollectionAdapter.java, opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptor.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdIntegrationTest.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdTest.java, opennms-services/src/test/java/org/opennms/netmgt/mock/MockThresholdingService.java
While evaluating the thresholds resource-filter, the attribute have been
read from the RRD repository (as stored in strings.properties). This
will fail if the string is not persisted (because the collection set us
purely used for thresholding) or on the first thresholding run, if the
thresholding is executed before the persistence.
This is changed to use the values from the currently processed
collection set.
This PR is split in two commits. The first commit contains the actual (very small) change. The second commit is cleanup of the (now unused) RRD repository from the thresholding API.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13945
=> NMS-13945: Use current string attrs for threshold filters

container/shared/src/main/resources/etc/org.apache.karaf.management.cfg
* JIRA: https://issues.opennms.org/browse/NMS-13887
It seems that the behaviour was changed due to the Karaf upgrade. See this bug:
https://issues.apache.org/jira/browse/KARAF-7096
...and the corresponding code change:
https://github.com/apache/karaf/pull/1343/files#diff-f0454a3d84e6d35695bb472ec1f21305455dcf489dc891ff08044f7a29d454eaR110
Workaround is to also set the `rmiServerHost` to the same value of `java.rmi.server.hostname` in `etc/org.apache.karaf.management.cfg`.
=> NMS-13887: Altered Karaf configuration to default to java.rmi.server.hostname

.circleci/README.md, .circleci/config.yml
I will switch back
https://github.com/OpenNMS/opennms/blob/66f1da5d3253cdd43ee3c264c7e922f8bb37ad6a/.circleci/config.yml#L11
and
https://github.com/OpenNMS/opennms/blob/66f1da5d3253cdd43ee3c264c7e922f8bb37ad6a/.circleci/config.yml#L19
as well as remove the echo to actually delete the image
https://issues.opennms.org/browse/NMS-13928
=> NMS-13928: automatically prune old feature branches from dockerhub

features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/events/EventForm.java, features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/events/EventFormTest.java
Added a converter to the field so the Combobox can bind properly with an Enum
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13729
=> NMS-13729: Event configuration UI fails to persist logmsg dest changes

opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/TimelineRestService.java
- Change the "drawGreen" method to draw from where the node's createTime is, instead of just filling up the entire graphic
- Rename methods and variables to make them easier to understand
Note: If an outage exists before a node's createTime, it will appear in the non-green part of the graphic. Is this something that can happen?
Issue: https://issues.opennms.org/browse/NMS-13822
=> NMS-13822: Start node "availability" graphic from the node's createTime

docs/modules/releasenotes/pages/whatsnew.adoc
To roll back running as root requires also to set the User in the systemd unit to root as well. Additionally, fix whitespace to show NOTE annotation correctly.
=> Rollback root instruction

.circleci/README.md, .circleci/main/@main.yml
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-13947
Result from build
```
Found a cache from build 116381 at nodejs-dependencies-v3-TeS0v4mbHi8haIv8yCeudjEOHL0qYe5eJEWhFZc31QU=-+2yB_AKHtGBvqsbqWIq9Np3cJU10qRpnWpDWQSeX2WU=
Size: 191 MiB
Cached paths:
* /root/.npm/_cacache
* /root/project/core/web-assets/node_modules
```
=> NMS-13947 Cache node artifacts

container/bridge/rest/pom.xml, core/schema/src/main/liquibase/30.0.0/changelog.xml, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfig.java, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigDTO.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, features/opennms-osgi-core-rest/pom.xml, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoredServiceDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockMonitoredServiceDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/UnimplementedMonitoredServiceDao.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/MonitoredServiceDaoHibernate.java, opennms-model/src/main/java/org/opennms/netmgt/model/NetworkBuilder.java
NMS-13970: DeviceConfigBackup REST API with Schedule info
Initial version of updated REST API that gets device config backup schedule info from Service metadata. Actual parsing of cron-style schedule pattern data will occur in subsequent PR.
'DeviceConfig' entries are retrieved as per sorting/filtering parameters, then the corresponding service schedule data is retrieved and mapped to the DTOs.
A separate integration test for the schedule part only was created as the DB setup is significantly different than the IT for the sort/filter part of the REST service.
Jira: https://issues.opennms.org/browse/NMS-13970
=> NMS-13970: DeviceConfigBackup REST API with Schedule info

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionInterface.java, opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNode.java, opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/requisition/RequisitionInterfaceTest.java, opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/requisition/RequisitionNodeTest.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/RequisitionRestService.java
* Checks the other interfaces of a node to prevent duplicates
* Adds tests for RequisitionNode and RequisitionInterface validation
JIRA: https://issues.opennms.org/browse/NMS-13939
=> NMS-13939: Fix node interfaces REST API allowing creation of multiple primary SNMP interfaces

features/geolocation/rest/src/main/java/org/opennms/web/rest/v2/GeolocationRestService.java, opennms-web-api/src/main/java/org/opennms/web/api/Util.java, opennms-web-api/src/main/java/org/opennms/web/utils/QueryParametersBuilder.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/OnmsRestService.java, opennms-webapp/src/main/java/org/opennms/web/controller/admin/notifications/ChooseUeisController.java, opennms-webapp/src/main/java/org/opennms/web/controller/admin/notifications/EventNoticesController.java, opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/notification/noticeWizard/chooseUeis.jsp, opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/notification/noticeWizard/eventNotices.jsp, opennms-webapp/src/main/webapp/admin/notification/noticeWizard/buildRule.jsp, opennms-webapp/src/main/webapp/admin/notification/noticeWizard/notifsForUEI.jsp, opennms-webapp/src/main/webapp/admin/notification/noticeWizard/validateRule.jsp, opennms-webapp/src/main/webapp/graph/chooseresource.jsp
Jira: https://issues.opennms.org/browse/NMS-13835
Some notes:
1. A lot of the detected XSS vulnerabilities were actually from exception messages, and currently are not interpreted by the browser as HTML. Right now this means they aren't actually vulnerabilities, but they will be detected by pentest tools as XSS vulns regardless. If the error messages are shown to the user without being sanitized, they could trigger script execution.  I solved this by sanitizing the user's input for fields like `limit`, `orderBy`, etc. This has side effects, are they acceptable?
- The `sanitizeInteger` method strips out any non-numeric characters, so an input of `limit=<script>alert(1)</script>` will be interpreted as `1` and proceed without an error.
- Error messages will now show sanitized strings. For …
=> NMS-13835: Fix reflected XSS

core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Controller.java, core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Invoker.java, core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Manager.java, core/daemon/src/main/java/org/opennms/netmgt/vmmgr/StatusGetter.java, opennms-base-assembly/src/main/filtered/bin/opennms, opennms-base-assembly/src/main/filtered/etc/log4j2.xml
Thanks to [a bug in the JDK](https://bugs.openjdk.java.net/browse/JDK-8226919) there is literally no way to work around the attach API not working other than to do this by completely other means.
My changes are as follows:
* log service status to STDOUT or `output.log` to make it easier for debugging startup when using systemctl (the last output will show in `systemctl status opennms`)
* implement a signal handler for `SIGUSR1` to dump status to a file for consumption by CLI tools (`SIGHUP` is already taken by the thread dump listener)
* update `$OPENNMS_HOME/bin/opennms` to use `kill -USR1` to trigger the status dump, and display the output
* while I was at it, `opennms stop` has the same issue, so I changed it to just use `kill` since the `Manager` implements a shutdown handler to …
=> NMS-13900: fix `opennms status` when attach API is unavailable

container/features/src/main/resources/features.xml, features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java, features/device-config/ssh-scripting/pom.xml, features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java, features/device-config/ssh-scripting/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java, opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: https://issues.opennms.org/browse/NMS-14039
I implemented another approach. With the original code it wasn't possible to connect to any IPv6 devices, since getLocalAddress() also return "0.0.0.0" in this case.
The new idea is to establish the SSH connection and use the session's endpoint addresses. In the case the SSH session cannot be established, we also have no need for the correct TFTP address. This seems to work a lot more reliable than the original approach.
For running inside a docker container two new properties were introduced to specify the IP address for both protocols.
The minion appliance uses the host network mode. So, in this case the code will give us the right IP addresses.
=> NMS-14039: determine IP address for TFTP server

.circleci/scripts/itest.sh, .circleci/scripts/smoke.sh, container/features/src/main/resources/features.xml, features/device-config/api/pom.xml, features/device-config/api/src/main/java/org/opennms/features/deviceconfig/service/DeviceConfigUtil.java, features/device-config/api/src/test/java/org/opennms/features/deviceconfig/service/DeviceConfigUtilTest.java, features/device-config/rest/pom.xml, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, pom.xml
Rest API for downloading the actual device config backup configuration data.
Pass comma-separated `id` query parameters with the `device_config` id.
- `GET /rest/device-config/download?id=1` downloads a single file, with encoding as per the file (for now, `text/plain`)
- `GET /rest/device-config/download?id=1,2,3` downloads a single `.tar.gz` file with the configuration files for ids 1, 2 and 3 inside.
Incorporated tar/gzip helpers in `DeviceConfigUtil` class.
Jira: https://issues.opennms.org/browse/NMS-13990
* JIRA (Issue Tracker): http://issues.opennms.org/browse/13990
=> NMS-13990: DeviceConfigBackup Rest API for downloading config data

container/features/src/main/resources/features.xml, features/device-config/api/pom.xml, features/device-config/api/src/main/java/org/opennms/features/deviceconfig/service/DeviceConfigUtil.java, features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java, features/device-config/rest/pom.xml, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/CompressionUtils.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/CompressionUtilsTest.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, pom.xml
Parse cron schedule info from DCB Service metadata and return `nextScheduledBackup` and `scheduledInterval` in API.
Additionally:
- moved functions requiring Apache `commons-compress` from `DeviceConfigUtil` to `rest` module `CompressionUtils` class.
- Fixed device config download to have `Content-Disposition` of `attachment` so browser will download as file instead of inline text
Jira: https://issues.opennms.org/browse/NMS-14047
=> NMS-14047: DCB Rest API: Parse and display cron schedule info

ui/package.json, ui/src/components/Common/Toast.vue, ui/src/components/Device/DCBGroupFilters.vue, ui/src/components/Device/DCBModal.vue, ui/src/components/Device/DCBTable.vue, ui/src/components/Device/DCBTableStatusDropdown.vue, ui/src/components/Layout/NavigationRail.vue, ui/src/components/Nodes/NodeAvailabilityGraph.vue, ui/src/containers/DeviceConfigBackup.vue, ui/src/hooks/useDownload.ts, ui/src/router/index.ts, ui/src/services/deviceService.ts, ui/src/store/device/actions.ts, ui/src/store/device/state.ts, ui/src/store/notification/actions.ts, ui/src/store/notification/mutations.ts, ui/src/store/notification/state.ts, ui/src/types/deviceConfig.d.ts, ui/src/types/index.ts, ui/tests/deviceConfigBackup.test.ts, ui/tests/fileEditor.test.ts, ui/tests/map.test.ts, ui/tests/queryParameters.test.ts, ui/tests/resourceGraphs.test.ts, ui/vite.config.ts, ui/yarn.lock
- Switching the test runner here to Vitest - this is a new now officially recommended way to test with Vite. Works with @vue/test-utils.
- Grabs the Toast component from the provisiond branch, to be used as a Common component going forward.
- Use toast for backup success / fail indicator.
- Link moved to Last Backup Date.
- Added ViewDetails Feather Icon on Last Backup Date.
- Hid "Group By" panel.
- Fix display color / capitalize status
- Fix / Display Schedule info properties
- Increase min-height of DCBModal to 300px
- Fix / return resp instead of resp.data for download
- Fix backup API call parameters
- Open new tab for node name link
- Change title on nav rail to Configuration Management
- Fix device name reactivity/display in DCBModal …
=> NMS-14081: Changes based on demo feedback

docs/modules/operation/pages/user-management/pre-authentication.adoc, features/springframework-security/pom.xml, features/springframework-security/src/main/java/org/opennms/web/springframework/security/RequestHeaderPreAuthenticationProcessingFilter.java, features/springframework-security/src/test/java/org/opennms/web/springframework/security/RequestHeaderPreAuthenticationProcessingFilterTest.java, opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/header-preauth.xml
JIRA: https://issues.opennms.org/browse/NMS-14059
Set roles via HTTP header, used in conjunction with pre-authentication
=> NMS-14059: Add support for pre-authorization

features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigDTO.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
DCB: Add 'config' as a string in the 'device-config' Rest API response
- use 'encoding' if supplied
- basic handling of binary data (returns hex representation of binary data)
- updates Rest integration test to use hamcrest matchers
It's expected we will need to make additional adjustments after testing with different kinds of text encoding or binary data.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14082
=> NMS-14082: DCB Add 'config' as string in Rest API response

features/collection/api/src/main/java/org/opennms/netmgt/collection/api/ServiceCollectorRegistry.java, features/collection/api/src/main/java/org/opennms/netmgt/collection/support/DefaultServiceCollectorRegistry.java, features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorClientRpcModule.java, features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorRequestBuilderImpl.java, features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectCommand.java, features/collection/test-api/src/main/java/org/opennms/netmgt/collection/test/api/CollectorComplianceTest.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/ServiceMonitorRegistry.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/support/DefaultServiceMonitorRegistry.java, features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerClientRpcModule.java, features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestBuilderImpl.java
Small update to not use `getCollectorByClassName` and `getMonitorByClassName`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14116
=> NMS-14116:  Get monitor/collector without resolving future

container/karaf/src/main/filtered-resources/etc/org.apache.karaf.management.cfg
This merges the fix from NMS-13887 into the Horizon container.
The original fix only applied to Minion and Sentinel.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14117
=> NMS-14117: add karaf config with rmi hostname fix from NMS-13887

features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigQueryResult.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
Device Configuration Backup Rest API updates for sorting/filtering/history.
- Main API call `device-config` returns only the latest device config record per ipinterfaceid/configType combination, this is for use on main UI display
- That call can be sorted asc/desc by device name, ip address, last updated, created time based on query string params. Default is last updated desc
- Calling with `ipInterfaceId` results in a "history" search that returns *all* results for that ipinterface (i.e. that device) for all configTypes, sorted by lastUpdated desc. This is to be used for viewing device history in UI (UI will handle displaying the different configTypes)
- Fixes to return value and logic for backup status
Main call uses Postgres-specific `DISTINCT ON` and some string manipulation for …
=> NMS-14112: DCB API to get latest configs per device/config type

ui/src/components/Device/DCBTable.vue
Device Config Backup, small UI changes
- add Config Type column. Non-sortable for now
- updates to query params for Rest API calls to align with latest API updates
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14141
=> NMS-14141: DCB UI add Config Type column, update query params for API

ui/package.json, ui/src/components/Device/DCBDiff.vue, ui/src/components/Device/DCBModal.vue, ui/src/components/Device/DCBModalConfigDiffContent.vue, ui/src/components/Device/DCBModalLastBackupContent.vue, ui/src/components/Device/DCBModalViewHistoryContent.vue, ui/src/components/Device/DCBTable.vue, ui/src/directives/v-date.ts, ui/src/main.ts, ui/src/store/device/actions.ts, ui/src/types/deviceConfig.d.ts, ui/tests/deviceConfigBackup.test.ts, ui/yarn.lock
- Adds vue-diff plugin and modal content component for displaying diff
- Fixes modal position on screen, relative to parent
- Displays config in a more 'editor-like' view, with line numbers
- Fixes position of modal download btn
- Fixes view history content so that dates are within their respective tabs, as per prototype
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14089
=> NMS-14089: DCB: Create UI for comparing 2 backup configurations

opennms-assemblies/sentinel/src/main/filtered/debian/opennms-sentinel.postinst
[jira/NMS-14123](https://issues.opennms.org/browse/NMS-14123)
It is cause by the file remove earlier than fix permission. And, the file list is obtain from debian package. So chown will exit with non 0 status code.
=> NMS-14123: Sentinel debian package fail to install

features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, ui/src/services/deviceService.ts
Update Device Config Backup Rest APIs to make their purpose more clear and to clean up the code a bit.
- `device-config` with query params will return *all* records with the given query params for filter/sort/limit/offset
- `device-config/latest` will return only the latest record per ipinterface/configType (by lastUpdated) for the given query. This is the API used by the main UI table to get the latest status across all devices
- `device-config/interface/{ipInterfaceId}` returns a history of records for the given `ipInterfaceId`, basically the history for one device. UI will need to partition between config types
Also added an integration test plus cleaned test code up a bit.
In addition, this PR updates the UI with the new endpoints. …
=> NMS-14147: DCB Endpoint Renaming

features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigDTO.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, ui/src/components/Device/DCBTable.vue, ui/src/services/deviceService.ts, ui/src/store/device/actions.ts, ui/src/types/deviceConfig.d.ts, ui/tests/deviceConfigBackup.test.ts
Device Configuration backup (triggered from UI) not working correctly due to mismatch in serviceName used.
Rest APIs should return 'serviceName'. UI should use this service name in 'device-config/backup' call
UI should accept 202 response from 'backup' API call and display 'successToast'
UI should only display "Backup Now" when a single item is selected (no multiple backups at this time)
UI should display value from 'lastBackupDate' for "Last Backup" column
Fix download file issue in UI
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14151
=> NMS-14151: DCB fix backup in Rest API and UI

container/shared/src/main/resources/etc/container.init, container/shared/src/main/resources/etc/container.service
This will switch the horizon, sentinel, and minion services over to run as their non-privileged users from the start instead of dropping down from root to start the process. This allows them to use ambient capabilities defined in the service definition file.
`CAP_NET_BIND_SERVICE` allows binding to privileged ports (for syslog and snmp).
`CAP_NET_RAW` allows creating raw sockets for icmp.
`ensure-user-ping.sh` was removed from the `init.d` start script because:
1. It needs root permissions, which the script no longer has
2. With the `NET_CAP_RAW` capability, the service can now open ICMP sockets without modifying `net.ipv4.ping_group_range`
3. This script is already run when installing RPMs / debian packages. See [minion](https://github.com/OpenNMS/opennms/blob/develop/opennms-assemblies/m …
=> NMS-14016: Run as non-privileged user with ambient capabilities

docs/antora.yml, docs/modules/deployment/pages/core/docker/core.adoc, docs/modules/operation/pages/flows/sentinel/message-broker/activemq.adoc, docs/modules/operation/pages/flows/sentinel/message-broker/kafka.adoc
With running as a non-root user we have to make sure the etc directory has permissions set to a user with user id 10001. As a safe default, I've introduced a persistent volume that has automatically the correct permissions. I've created a tip that explains that you need to make sure to set the correct permission in case you want to use a bind mount from your local filesystem into the container.
I've removed the prerelease variable, we only publish docs for a released version, so we can make it less complicated here.
Fixed build warnings with missing callouts which are leftover when we removed the REST endpoint and used the Twin API instead.
=> Improve docker instructions when running as non-root with persistent config directory

features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, ui/src/components/Device/DCBTable.vue
Device Config Backup, Rest API, correctly return device count for `device-config/latest` call. This is total number of devices (i.e. ipinterface ids) that would be returned if 'limit' and 'offset' were not set.
This does an HQL query similar to `getLatestConfigForEachInterface` but simplified as we only need the count and don't need to do any sorting, grouping or 'windowing' functions. Do need to take search term into consideration.
Note, there are features in newer versions of Hibernate (i.e. `Projections.countDistinct`) that would allow this query to be done in Hibernate instead of HQL.
Also, a small update to display the device count in UI.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14165
=> NMS-14165: DCB correctly return device count for 'latest' query

core/schema/src/main/liquibase/30.0.0/changelog.xml, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfig.java, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigStatus.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
NMS-14167: DCB device_config table add 'status', drop 'last_updated', non-nullable constraint
Part of NMS-14167, database updates and minimal fixes only.
'status' is an enum, having possible values 'NONE', 'SUCCESS', 'FAILED'. 'NONE' denotes that backup has not yet been attempted. In this case, 'last_updated' would be null.
DeviceConfig class contains a helper method, 'determineBackupStatus' which can be used to determine backup status from DeviceConfig dates.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14167
=> NMS-14167: DCB device_config table add 'status', update 'last_updated'

opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionValidator.java, opennms-install/src/test/java/org/opennms/install/InstallerTest.java
This PR makes a couple of changes to how the installer does validation for writeability.
* change to using `Files.walk` and an iterator, so that it can continue even if there is an exception reading from a directory or file, as long as that directory or file is ignored
* only check `etc`, `data`, `instances`, `logs`, and `share`, since any other directories shouldn't need to be written to
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14032
=> NMS-14032: do not fail on directories that do not need write

opennms-webapp/src/main/webapp/includes/grafana-box.jsp
Seems the uri was obsolete since grafana version 5 as mentioned in the response sample
https://grafana.com/docs/grafana/latest/http_api/folder_dashboard_search/
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14184
=> NMS-14184: Grafana dashboard box links are no longer valid in Grafana 8.4

ui/src/composables/useRole.ts, ui/src/router/index.ts, ui/src/store/auth/mutations.ts, ui/src/store/auth/state.ts
Routes were loading before API response with roles was returned.
On a first load, this will wait until the roles are available until loading a protected route.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14200
=> NMS-14200:  Wait for roles to load before checking route access

container/features/src/main/resources/features-sentinel.xml, container/features/src/main/resources/features.xml, core/schema/pom.xml, core/test-api/db/pom.xml, dependencies/groovy/pom.xml, dependencies/pom.xml, features/remote-poller/pom.xml, features/remote-poller/src/main/groovy/org/opennms/groovy/poller/remote/ScanGui.groovy, features/telemetry/protocols/collection/pom.xml, features/telemetry/protocols/flows/pom.xml, features/topology-map/features/runtime-graphml/pom.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.graphml/pom.xml, opennms-provision/opennms-detector-bsf/pom.xml, opennms-provision/opennms-provision-persistence/pom.xml, pom.xml, protocols/selenium-monitor/pom.xml, protocols/selenium-monitor/src/assembly/lib.xml, protocols/selenium-monitor/src/main/java/org/opennms/netmgt/poller/monitors/SeleniumMonitor.java, smoke-test/pom.xml
This PR upgrades our embedded Groovy to the latest 2.x -- 2.5.16 -- which was recently updated in March.
2.5, in general, should be almost entirely source-compatible with the version we'd been using/embedding in OpenNMS.
The biggest changes have been structural (how the Maven project is published, some things being pulled out into "optional" dependencies, etc.)
This patch _should_ provide a version that's functionally equivalent to what we already were using.
At least, smoke tests pass... ¯\\\_(ツ)\_/¯
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14208
=> NMS-14208: upgrade Groovy to latest 2.x

container/features/pom.xml, dependencies/activemq/pom.xml, dependencies/cxf/pom.xml, dependencies/jackson1/pom.xml, dependencies/pom.xml, dependencies/spring/pom.xml, features/datachoices/pom.xml, features/rest/common/pom.xml, features/rest/model/pom.xml, pom.xml
This PR updates our version of the (old) Jackson dependencies to an Atlassian fork that includes security fixes.
As far as I can tell it's a simple drop-in replacement, all I did was add a "dependency" pom to make it easier to pull it from Atlassian's repo since their fork isn't in Maven Central.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14252
=> NMS-14252: use the Atlassian updates to jackson1

features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java, features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml, features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapListenerTest.java
If the broker is not available :  The `opennms-trapd-listener` feature would hang indefinitely while waiting for a `TwinSubscriber` to initialize, which couldn't complete until a connection to the core was made. This prevented the feature from ever attempting to listen for traps.
These updates make this dependency optional. The TrapListener will now wait 60 seconds for trapd configuration to come from the core instance. If that is not received, it uses default settings and listens anyways.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14148
=> NMS-14148: Still listen for traps without a subscribtion

ui/package.json, ui/src/components/Configuration/ConfigurationHelper.ts, ui/src/components/Configuration/copy/requisitionTypes.ts, ui/yarn.lock
- Add the predominant lib/regex for validating IP addresses, fix validation issue.
- Fix spelling: VMWare -> VMware
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14260
=> NMS-14260: Use ip-regex for validation, fix VMware case

.github/assign-by-files.yml, .github/workflows/auto-assign.yml
Cherry picking the commit from `release-30.x` to also be in `foundation-2022` for auto-approving documentation PRs. (per @Bonrob2's request)
=> auto-assign bonnie as a reviewer if docs are changed

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesWriter.java
This PR helps to free some memory but doesn't solve the problem completely.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14250
=> NMS-14250: Performance of time series integration layer: free samples as soon as possible for garbage collection

ui/src/components/Configuration/ConfigurationHelpPanel.vue, ui/src/components/Configuration/ConfigurationHelper.ts, ui/src/components/Configuration/ProvisionDForm.vue, ui/src/components/Configuration/copy/requisitionTypes.ts, ui/tests/configuration.test.ts
- Puts VMware form state invalid with error msgs, if username but no password or password but no username.
- Marks username and password fields as optional.
- Updates VMware help text to convey that those fields are optional and what happens if left blank.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14271
=> NMS-14271: Display error when VMware username or password missing

docs/modules/operation/pages/device-config-backup/dcb-requisition.adoc, docs/modules/operation/pages/user-management/security-roles.adoc, opennms-web-api/src/main/java/org/opennms/web/api/Authentication.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/FilesystemRestService.java, opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml, ui/src/components/Layout/NavigationRail.vue, ui/src/composables/useRole.ts, ui/src/router/index.ts
Add a new role, `ROLE_CONFIG_EDITOR` which allows access to view/edit configuration files via REST API and via the new UI. Only users with this role can view/editor these files via REST/UI.
This affects any REST API calls to `/rest/filesystem/**`. Even `ROLE_ADMIN` is denied access to view or edit files; however an admin can add the config editor role to themselves.
Changes include:
- updated Spring security configuration for the new role
- update Rest service code to disallow any but config editor role. May not be needed with spring XML configuration, but code was previously there an is an extra check
- update UI to only display "File Editor" navigation or allow routing for config editor users
- updates to documentation
- also a small update to DCB documentation for `retention-period` …
=> NMS-14242: Add ROLE_CONFIG_EDITOR for editing config files from REST and UI

container/features/pom.xml, dependencies/oia/pom.xml, dependencies/pom.xml, features/api-layer/pom.xml, features/distributed/coordination/common/pom.xml, features/distributed/coordination/zookeeper/pom.xml, pom.xml
This PR changes our OIA dependencies to be routed through an `oia-dependencies` package that sets the snapshot repository to always update.  This _should_ 🤞 make sure OIA is up-to-date when doing development builds.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14291
=> NMS-14291: make sure snapshot OIA is always updated when building

features/device-config/monitor-adaptor/src/main/java/org/opennms/features/deviceconfig/monitor/adaptor/DeviceConfigMonitorAdaptor.java, features/device-config/monitor-adaptor/src/test/java/org/opennms/features/deviceconfig/monitor/adaptor/DeviceConfigMonitorAdaptorIT.java, features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java, features/device-config/monitor/src/main/resources/OSGI-INF/blueprint/blueprint.xml, opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
We want to create empty entries for all devices if they have DeviceConfig
service running.
If we throw exception in run time attributes, that will prevent us
from creating these entries. So send this error to poll and throw error there
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14275
=> NMS-14725: Don't error out early when script file is missing

features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/ConfigType.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java, features/device-config/sink/consumer/src/main/java/org/opennms/features/deviceconfig/sink/consumer/DeviceConfigConsumer.java
Any config that is uploaded from device will use config type sink instead of default.
Service name for these will be null
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14297
=> NMS-14297: Use sink as config type for push based configs 

opennms-base-assembly/src/main/filtered/bin/opennms
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13991
=> NMS-13991: Pass debug flags on to opennms start from opennms restart

features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvSetCommand.java, features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvValidateCommand.java
Added scv-validate command to validate credentials username/password or key/value pair from the attributes.
using arguments -u (username/key) and -p (password/value) 
Usage : 
scv-validate -u <username/key> -p <password/value> <alias>
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14227
=> NMS-14227: SCV:  Add Shell command to validate Credentials

docs/modules/operation/pages/user-management/security-roles.adoc, opennms-web-api/src/main/java/org/opennms/web/api/Authentication.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/FilesystemRestService.java, opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml, ui/src/components/Layout/NavigationRail.vue, ui/src/composables/useRole.ts, ui/src/router/index.ts
This is a follow up to NMS-14242 (PR: https://github.com/OpenNMS/opennms/pull/4682).
We determined that `ROLE_FILESYSTEM_EDITOR` is a bit clearer than `ROLE_CONFIG_EDITOR`. This role allows user to view and edit configuration files on the OpenNMS filesystem (i.e., under `/etc`) via UI and Rest API.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14309
=> NMS-14309: Rename ROLE_CONFIG_EDITOR to ROLE_FILESYSTEM_EDITOR

features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
Device Config Backup Rest API, add ability to filter history by configType. UI will use this for History and Compare screens.
Get all configs for this device: `/rest/device-config/interface/{id}`
Get default configs for this device: `/rest/device-config/interface/{id}?configType=default`
Get running configs for this device: `/rest/device-config/interface/{id}?configType=running`
* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}
=> NMS-14317: DCB Rest API, filter history by configType

docs/modules/operation/pages/device-config-backup/dcb-requisition.adoc, docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc, opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-gz.dcb, opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-set.dcb, opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-txt.dcb, opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
For now, this is only updated for juniper devices.
Also updated default schedule to be never ( should still able to backup configs manually)
update docs.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14328
=> NMS-14328: Update scripts to use tftp binary mode

opennms-container/launch_apt_server.sh
This intermittent failure can occur when the machine executing this script is slow. As a result, I'm increasing the timeout value we compare the count variable against. 
In addition, I'm making slight modifications to how the output for this script looks.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14336
=> NMS-14336 CircleCI : Intermittent failures in horizon-deb-build

features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfig.java, features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigQueryResult.java, features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java, features/device-config/persistence/impl/src/test/java/org/opennms/features/deviceconfig/persistence/DeviceConfigDaoIT.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java, features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java, ui/src/components/Device/DCBTableStatusDropdown.vue, ui/src/store/device/actions.ts, ui/src/store/device/state.ts, ui/src/types/deviceConfig.d.ts
NMS-14324: Device Config Backup, Rest API and UI, order by Location and Backup Status.
- Update Rest API `latest` to allow `orderBy` on location and status
- Remove code to determine backup status by device config dates. Backup status is now stored in the DB and status is determine by `DeviceConfigMonitorAdaptor` during polling
- Update integration tests
- Minimal changes in UI to enable sort by location
- UI sort by status is not implemented, would need changes to `DCBTableStatusDropdown`. However, filter by status works correctly
- UI updated 'status' query params for filtering by status to be uppercase, otherwise Java server code doesn't recognize parameters and returns a 404
- FIxed small bug in `getAndMergeDeviceConfigBackups` where responses with `204 - No Content` contained just …
=> NMS-14324: DCB Order by Location and Backup Status

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/MetaData.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/views/metadata.html
NMS-14282. Enable multiline text entry for requisition Metadata values.
In Requisition UI, replaces the text input control for entering the Metadata value with a textarea. Initial it displays 1 row, but expands to up to 3 rows if user enters 3+ lines of text (then it scrolls).
For now, always has this new multiline textarea input. It's possible this is only desired for certain types of metadata, e.g. SSH keys or DCB scripts. Can add that if needed due to following issue.
One issue is that hitting 'Enter' key inside the 'value' textarea no longer saves the Metadata item, but would add another line. User would need to tab out or else click 'Save' button.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14282
=> NMS-14282: Enable multiline text entry for requisition metadata values

features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13785
Interestingly, the constructor for PersistenceException expects a List<FailedItem<FlowDocument>>, but the defect was caused because a List<FlowDocument> was passed through instead. The compiler didn't catch this, and at run time the constructor succeeds and the wrong type of list is assigned into the PersistenceException's member variable failedItems. ElasticFlowRepository.persistBulk is called in two different ways. One of which attempts to handle PersistenceExceptions by iterating through the list. This then gives the casting error as the list doesn't contain FailedItems as expected. I suspect the other method for calling persistBulk is how it is more commonly called, which won't give the casting error as the exception …
=> NMS-13785: fix casting error when flow persistence gives errors

features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgeSimpleConnection.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14322
Cleaning up a wrong condition that lead to wrong bridge topology discovery.
The Tests has been fixed accordingly.
=> Bridge Topology Discovery Mismatch

ui/src/components/Device/DCBTable.vue, ui/tests/deviceConfigBackup.test.ts
- If only one config is selected, and that config does not have a service name, the backup btn should be disabled.
- Make btn disable logic computed vars to avoid repetition
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14300
=> NMS-14300: Disable backup for single selected config w/o service name

debian/rules, tools/packages/opennms/opennms.spec
This creates a new directory `web-inf-pristine` at the same level as `etc-pristine` that contains  
- `jetty-webapps/opennms/WEB-INF/applicationContext-spring-security.xml`
- `jetty-webapps/opennms/WEB-INF/web.xml`
- `jetty-webapps/opennms/WEB-INF/spring-security.d/`
- `etc/examples/jetty.xml`
This is installed at `/var/lib/opennms/web-inf-pristine` on debian systems and at `/var/opennms/web-inf-pristine` on centos.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13834
=> NMS-13834: Modified opennms.spec and debian/rules to also create web-inf-pristine

ui/src/components/Layout/NavigationRail.vue, ui/src/components/Plugin/utils.ts, ui/src/containers/Plugin.vue, ui/src/main.ts, ui/vite.config.ts
- Gives plugin access to router
- Loads plugin js files before rendering app - this is required to be able to hit a plugin route directly from the url / refresh
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14425
=> NMS-14425: Let plugins use routing

opennms-container/horizon/container-fs/entrypoint.sh
This only affects installations running as root.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14396
=> NMS-14396: Stop appending RUNAS=root multiple times in container start script

features/rest/mapper/src/main/java/org/opennms/web/rest/mapper/v2/AlarmMapper.java
Fix null pointer exception in api/v2/alarms rest point when lasteventid in alarms are null
See: AlarmMapperImpl.alarmLastEventEventUei
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14331
=> NMS-14331: Grafana Panel Internal Server Error when lasteventid is Null for an Alarm when Using HELM

opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeAlarmTextFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeCategoryFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeDescriptionSubstringFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeIPAddrLikeFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeLogMessageSubstringFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeNodeNameLikeFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/NegativeServiceFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/ServiceOrFilter.java, opennms-webapp/src/main/java/org/opennms/web/alarm/filter/SeverityOrFilter.java, opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AcknowledgeAlarmByFilterController.java, opennms-webapp/src/main/java/org/opennms/web/filter/NegativeIPLikeFilter.java, opennms-webapp/src/main/webapp/includes/alarm-advquerypanel.jsp
Within Alarm advanced search, it is now possible to search for the negative values of Alarm Text contains, TCP/IP address like, and NodeLabel contains.
To do this the first character in the field should be a -
If you negate the nodeLabel field, currently you only get alarms that have a different node to the negated one. You don't get alarms that aren't associated to a node. I thought I would create a pull request as I was told I was moving onto Streams after today. If required I can create another jira and explain my work to somebody else, or alternatively ask them to continue working on this branch.
Example. Alarm 1 is associated with Node 1. Alarm 2 is associated with Node 2. Alarm 3 has no node associated.
You type '-2' into the node label field. Only alarm 1 is returned in the list. I …
=> NMS-14043: Negate search terms in alarms advanced search

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/SearchProperties.java
HELM-272: Hard-code values for Helm Rest API properties call for affectedNodeCount and situationAlarmCount to prevent invalid HQL query. Also fix labels to be "Affected Node Count", etc.
This needs to be done in conjunction with OpenNMS/opennms-helm HELM-272, see [PR](https://github.com/OpenNMS/opennms-helm/pull/453).
These values (cf. `OnmsAlarm.java`) are derived inside the entity Java code, not from the database directly.  This was causing HQL parsing issues in `AlarmRestService.java` and `AbstractDaoRestServiceWithDTO.getPropertyValues()`, responding to the "properties" call from Grafana/Helm when user added one of these Filter fields in a Filter Panel. Also, these SearchProperties are set to orderBy = false, which also wasn't being handled in HQL query construction (cf. …
=> HELM-272: Fixes for Helm API properties call for affectedNodeCount and situationAlarmCount

opennms-web-api/src/main/java/org/opennms/web/api/Util.java
* JIRA: https://issues.opennms.org/browse/NMS-14403
Reverted the change in the Util class, since this made the query-string get double-quoted. I also went through the code and the logic handling parameters looks fine to me. So, in my opinion this revert will not introduce any security issues.
=> NMS-14403: Fixed conversion of query string

ui/src/components/Configuration/ConfigurationHelpPanel.vue, ui/src/components/Configuration/ConfigurationHelper.ts, ui/src/components/Configuration/ProvisionDForm.vue, ui/src/components/Configuration/copy/requisitionTypes.ts, ui/tests/configuration.test.ts
In the UI Preview, External Requisitions, the Requisition Name / Foreign Source Name was not being added to the URL for the "import-url-resource" being saved in the DB via via Configuration Manager Rest API. Added a new text box input field when VMware is selected as an External Source.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14478
=> NMS-14478: External Requisition UI, add Requisition Name input for VMware

features/device-config/api/src/main/java/org/opennms/features/deviceconfig/service/DeviceConfigService.java, features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java, features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java, features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/api/Retriever.java, features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java, features/device-config/retrieval/src/test/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImplTest.java, features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java, features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DcbTriggerCommand.java, features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java, features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/DeviceConfig.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
This adds a new option (-v, --verbose) to the `dcb-trigger` karaf shell command. If the script starts executing at all during the retrieval, this captures the ssh session I/O and sends it to stdout. 
The dummy script below:
Results in something like this being seen from the karaf shell:
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14120
=> NMS-14120: DCB: Add full script output option to karaf shell command

docs/modules/operation/pages/user-management/introduction.adoc, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java, features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
Global notification enablement status (Boolean)
Destination path count (integer gauge)
On-call role count (integer gauge)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14488
=> NMS-14488: Add KPIs for notification entities to datachoices telemetry

features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/CollectionSetProtos.java, features/kafka/producer/src/main/proto/collectionset.proto, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaMetricsMaxSizeIT.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaPersisterIT.java
Protobuf cannot distinguish between an unset and a default scalar value, see https://developers.google.com/protocol-buffers/docs/proto3#default
To get around that, this adds a new `DoubleValue metric_value` to the `NumericAttribute` message that is a copy of the scalar double value that can distinguish between default and unset.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14469
=> NMS-14469: Add a double value wrapper to the NumericAttribute message

docs/modules/operation/pages/user-management/introduction.adoc, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
Reverts OpenNMS/opennms#5020
This should only target `release-30.x` and beyond.
=> Revert "NMS-14482: Add KPIs for CPU count and memory size to datachoices telemetry"

docs/modules/operation/nav.adoc, docs/modules/operation/pages/events/event-advanced-search.adoc, opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java, opennms-webapp/src/main/java/org/opennms/web/controller/event/EventController.java, opennms-webapp/src/main/java/org/opennms/web/event/EventUtil.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeDescriptionSubstringFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeEventTextFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeIPAddrLikeFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeLogMessageSubstringFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeNodeNameLikeFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/ServiceOrFilter.java, opennms-webapp/src/main/java/org/opennms/web/event/filter/SeverityOrFilter.java, opennms-webapp/src/main/java/org/opennms/web/filter/FilterUtil.java, opennms-webapp/src/main/java/org/opennms/web/tags/filters/AbstractFilterCallback.java, opennms-webapp/src/main/java/org/opennms/web/utils/filter/CheckboxFilterUtils.java, opennms-webapp/src/main/java/org/opennms/web/utils/filter/FilterTokenizeUtils.java, opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp, opennms-webapp/src/main/webapp/includes/event-advquerypanel.jsp
Negating the following terms:
Node Label Contains - negated with a `!`.
Event Text Contains - negated with a `!`.
TCP/IP Address Like - negated with a `!`.
Severity - added checkboxes to choose what to filter by.
Service - added checkboxes to choose what to filter by.
Also had to fix a bug with the Node Location and System ID, where the "Any" string was being passed as a filter instead of showing all.
I did notice there is another bug when doing an Advanced Search, that the sort and pagination doesnt work consistently. It looks like this is due to an inconsistency with how the query parameters are delimited. However this does not happen when listing all events from "All Events". I will document this in another ticket.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14476
=> NMS-14476: Negate search terms in event advanced search

opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
Update licensing link and text in OpenAPI (see new UI, Endpoints) to point to AGPL license specifically. Text and link:
[OpenNMS(R) Licensing (GNU Affero General Public License)](http://www.gnu.org/licenses/agpl.html)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14523
=> NMS-14523: Update OpenAPI license link to point to AGPL

smoke-test/src/test/java/org/opennms/smoketest/flow/BmpIT.java
Added restart of CollectD after the node has been added to the db. This was the main issue for the test to be flaky. 
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14360
=> Adding collectd restart to the test after we have added a node. 

docs/modules/operation/pages/user-management/introduction.adoc
This restores minor doc updates that were reverted along with the KPI work in #5062 .
There have been a few updates to usage statistics merged into `release-30.x` that need accompanying doc updates as well.
=> NMS-14482: Capitalization fix in docs

smoke-test/src/test/java/org/opennms/smoketest/ThresholdingIT.java
Returning back ThresholdingIT tests to the smoke test 
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14362
=> Moving threshold back to smoke test.

opennms-webapp/src/main/java/org/opennms/web/filter/FilterUtil.java, opennms-webapp/src/main/java/org/opennms/web/tags/filters/AbstractFilterCallback.java
Fixing query param issue with advanced search. 
Unsure as to how the query parameters suddenly change from `&` or `&amp;`, have seen them come through as both.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14476
=> NMS-14476: Fixing query param issue with advanced search

features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImpl.java, features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/PanelDeserializer.java, features/endpoints/grafana/client/src/test/java/org/opennms/netmgt/endpoints/grafana/client/GrafanaClientImplIT.java, features/endpoints/grafana/client/src/test/resources/__files/dashboard8.json
This PR fixes the handling of the differences between the `"panels"` response when querying dashboards in different Grafana versions.  It implements a custom Gson deserializer for the `Panel` class that handles both the single `datasource` string entry, or the `datasource` object that contains a `uri` and `type`.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14544
=> NMS-14544: fix reading panels from Grafana 8 API

opennms-container/minion/Dockerfile, opennms-container/minion/assets/entrypoint.sh, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/assets/entrypoint.sh
Change the SSH key generation used for Karaf console access to be executed on first launch.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14643
=> NMS-14643: generate SSH keypair on launch

.circleci/config.yml
This PR changes a number of places where we check out the source tree to do a "read-only" checkout for speed; we only need to update the cache once per commit.
=> only save cache during "real" build

features/collection/thresholding/api/src/main/java/org/opennms/netmgt/threshd/api/ThresholdInitializationException.java, features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/DefaultThresholdingSetPersister.java
The thresholding engine was blocking whenever the config needed to be
reloaded. This is altered to allow reloading the existing thresholding
sets while processing thresholds concurrently.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14645
=> NMS-14645: Avoid locking thresholding during changes

smoke-test/src/main/java/org/opennms/smoketest/utils/RestClient.java
No issue for this, it's just a cosmetic thing, but while debugging smoke tests, it sure is annoying to scroll through a million stack traces just because the OpenNMS REST interface isn't live yet.
The only code referencing this is `OpenNMSContainer::waitUntilReady`, which _already_ considers getting `null` back a failure, so the behavior is exactly the same.
=> don't print a giant exception while waiting for OpenNMS to start

.circleci/main/executors.yml, .circleci/scripts/itest.sh, opennms-container/horizon/Dockerfile, opennms-container/horizon/Makefile, opennms-container/minion/Dockerfile, opennms-container/minion/Makefile, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/Makefile
This PR updates our docker containers to use `deploy-base` 2.x, which has been updated to Ubuntu 22 LTS.
It required just bumping the versions pulled in our docker files, as well as a change to the containers parts of the build run in (I had to move the circle machines to ubuntu jammy as a base as well, to avoid pthread mismatches between host and container).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14675
=> NMS-14675: use new ubuntu 22 deploy base

opennms-model/src/main/java/org/opennms/netmgt/model/OnmsSnmpInterface.java
NMS-14449: added node ID to SnmpInterface json object returned by the api/v2/snmpinterfaces rest
Part of work done for HELM-334
OpenNMS/opennms-js#377
and
OpenNMS/opennms-helm#492
External References
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14449
=> NMS-14449: Rest API v2 for obtaining a list of SNMP interfaces doesn't return back node id

opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/DistPollerDaoHibernate.java
This PR allows OpenNMS to have any UUID as system id. So far it was assumed that the system id = "00000000-0000-0000-0000-000000000000" 
Since we are moving towards the cloud we want universally unique system ids.
It is unresolved how to create a UUID when installing a new system. Ideas?
* JIRA (Issue Tracker): [http://issues.opennms.org/browse/DC-266
](https://issues.opennms.org/browse/DC-266)
=> DC-266: Get Environement and OpenNMS system Id and provide to access service

container/features/src/main/resources/features.xml, container/karaf/src/main/filtered-resources/etc/blacklisted.properties, container/karaf/src/main/filtered-resources/etc/custom.properties, dependencies/hibernate/pom.xml, integrations/opennms-vmware/pom.xml, pom.xml
Turns out dom4j 2.x is (almost entirely) API-compatible with the 1.6.1 our Hibernate depends on.
Turns out updating it was pretty simple and everything is green.
Who knew?
(I have a companion branch to this against foundation 2022 and it went green as well.)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14696
=> NMS-14696: use dom4j 2.1.3

opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java, opennms-webapp/src/main/java/org/opennms/web/filter/FilterUtil.java, opennms-webapp/src/main/java/org/opennms/web/tags/filters/AbstractFilterCallback.java
There seemed to be two primary issues. 
1. We weren't handling both `&` and `&amp;` as parameter delimiters.
2. The EventQueryServlet was handling the `any` filter option correctly, but when redirecting to the EventController, it was passing that directly on to filters.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14542
=> NMS-14542: Fix event search filtering

opennms-model/src/main/java/org/opennms/netmgt/model/OnmsSnmpInterface.java
NMS-14449: adding node ID to SnmpInterface json object returned by the api/v2/snmpinterfaces rest
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14449
=> NMS-14449: back porting

.circleci/main/commands/executions/run-build.yml
`update-maven-cache` does an expanded `mvn dependency:resolve-plugins de.qaware.maven:go-offline-maven-plugin:resolve-dependencies` which, in theory, will grab extra stuff and put it in the maven cache so later build portions don't need it... BUT it takes 7 minutes, and there's no way the amount of stuff that would need a re-download justifies doing it.
=> remove `update-maven-cache` from build

.circleci/config.yml, .circleci/scripts/codecoverage-restore.sh, .circleci/scripts/smoke.sh, .circleci/scripts/sonar.sh
This PR fixes a few bugs in getting Sonar to process and submit properly. It also enables forcing Sonar builds on for branches with "sonar" in the name.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14690
=> NMS-14690: enable sonar in foundation-2022, release-X, and develop

features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java, features/device-config/service/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Changed DeviceConfig backup to have reference to PollarConfig to avoid created of a new object. 
This resolves issue with newly created node are not able to backup until a reboot. 
* JIRA (Issue Tracker): (https://issues.opennms.org/browse/NMS-14670)
=> NMS-14670 Newly created node failes on device backup

core/web-assets/ci.js, core/web-assets/package.json, core/web-assets/pom.xml
After an initial build:
```
[INFO] 
[INFO] --- maven-bundle-plugin:3.5.1:install (default-install) @ org.opennms.core.web-assets ---
[INFO] Local OBR update disabled (enable with -DobrRepository)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.978 s
[INFO] Finished at: 2022-09-20T12:19:48-04:00
[INFO] ------------------------------------------------------------------------
[INFO] finished successfully
```
20 seconds!
=> only run "npm ci" if package-lock.json has changed

core/daemon/src/main/resources/META-INF/opennms/applicationContext-daemon.xml, core/test-api/camel/src/main/resources/META-INF/opennms/applicationContext-queuingservice-mq-vm.xml
During integration test we get a TON of noise output from initializing ActiveMQ whether or not we actually use it. This should make it a bitt less crazy, and shouldn't affect runtime at all, spring will still initialize when it needs it.
We should probably look into making a _ton_ more stuff lazy-init, tbh, but this one jumped out at me while I was working on cleaning up some tests.
=> don't initialize ActiveMQ connection factory stuff unless we use it

debian/rules, opennms-base-assembly/pom.xml, opennms-base-assembly/src/assembly/daemon.xml, opennms-base-assembly/src/main/filtered/bin/opennms, pom.xml, tools/packages/opennms/opennms.spec
https://github.com/pyroscope-io/otel-profiling-java
To use:
1. Install Pyroscope server: https://pyroscope.io/docs/installing-pyroscope-overview/
2. Set PYROSCOPE_AGENT_ENABLED=1 in opennms.conf
3. Restart OpenNMS.
4. Go to http://localhost:4040/
If the Pyroscope server is hosted somewhere else or you want to call the application something other than "OpenNMS", set the PYROSCOPE_SERVER_ADDRESS or PYROSCOPE_APPLICATION_NAME variables appropriately.
You can also set other configuration options mentioned in https://pyroscope.io/docs/java/#configuration however you will also need to export those variables in your opennms.conf.
Future work:
- Unify existing profiling/debugging/etc. features in the opennms startup script once we have a better idea of what is still used/usable and remove …
=> Pyroscope agent support

features/collection/api/src/main/java/org/opennms/netmgt/collection/dto/CollectionSetDTO.java, features/collection/snmp-collector/src/main/java/org/opennms/netmgt/collectd/SnmpCollectionSet.java, features/telemetry/protocols/adapters/src/main/java/org/opennms/netmgt/telemetry/protocols/collection/ScriptedCollectionSetBuilder.java, features/telemetry/protocols/graphite/adapter/pom.xml, features/telemetry/protocols/graphite/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/graphite/adapter/GraphiteAdapter.java, features/telemetry/protocols/graphite/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/graphite/adapter/GraphiteAdapterFactory.java, features/telemetry/protocols/graphite/adapter/src/main/resources/OSGI-INF/blueprint/blueprint.xml
In `GraphiteAdapter`, allow the Groovy script to set the node for the timeseries data.
Currently, a `CollectionAgent` is created in `GraphiteAdapter` based on the IP address and node of whatever process sent the Graphite message to OpenNMS. This ultimately results in the timeseries record being saved with a resource ID of e.g. `snmp/{nodeId}/...`. This may not actually correlate to a node that the data should be correlated with, which may need additional processing to determine.
This update passes a `List<CollectionAgent>` into the Groovy script which does the processing. If the script adds a `CollectionAgent` to that list, the `GraphiteAdapter` will use that one instead of the one it created. This ultimately results in the resourceId of the saved record having the correct node id.
The …
=> NMS-14659: GraphiteAdapter, allow groovy script to set the node

features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/model/IpInterfaceTopologyEntity.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/TopologyEntityDaoHibernate.java, features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/NodeTopologyService.java, features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/SubNetwork.java, features/enlinkd/service/api/src/test/java/org/opennms/netmgt/enlinkd/service/api/SubNetworkTest.java, features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/NodeTopologyServiceImpl.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/NodeTopologyServiceIT.java
Added Netmask to IpInterfaceTopologyEntity
Created Subnetwork class
Produce suitable methods to get subnetworks
from IpInterfaceTopolgyEntity
Check if network is legal or not (verify that subnetwork has no duplicated ip addresses)
Also find PointToPoint Subnetworks and Loopbacks
Finally provide a priority map based on Sunetworks.
Priority is asigned starting from the first low legal subnetwork
All the node under the Subnetwork have the same priority.
Check connected node and increase priority
Two subnetworks are connec ted if there is at least a common node (intersection is not null).
The branch is from develop but has been merged with the following branches
ar/jira/NMS-14771 https://github.com/OpenNMS/opennms/pull/5310
ar/jira/NMS-14763 https://github.com/OpenNMS/opennms/pull/5313
* JIRA …
=>  NMS-14773 Provide SubNetwork Classes for Enhanced Linkd

docs/modules/operation/pages/admin/geocoder.adoc
Slight restructure to the geocoder doc page.  Bring the Nominatim service to the top, as it's easiest to setup.
Make the reference for the GeoIP adapter easier to see.
=> geocoder doc restructure

core/daemon/src/main/java/org/opennms/netmgt/daemon/AbstractSpringContextJmxServiceDaemon.java, core/daemon/src/main/java/org/opennms/netmgt/daemon/BaseOnmsMBean.java, core/daemon/src/test/java/org/opennms/netmgt/daemon/AbstractSpringContextJmxServiceDaemonTest.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java, opennms-correlation/opennms-correlator/src/main/java/org/opennms/netmgt/correlation/jmx/Correlator.java, opennms-services/src/main/java/org/opennms/netmgt/actiond/jmx/Actiond.java, opennms-services/src/main/java/org/opennms/netmgt/passive/jmx/PassiveStatusd.java, opennms-services/src/main/java/org/opennms/netmgt/scriptd/jmx/Scriptd.java, opennms-services/src/main/java/org/opennms/netmgt/translator/jmx/EventTranslator.java, opennms-services/src/main/java/org/opennms/netmgt/vacuumd/jmx/Vacuumd.java
Added getStartTimeMilliseconds method to BaseOnmsMBean.java to be able to track start time for any managed bean. This way we don't just track ONMS startup time but start time for every managed bean invoked during startup.
Some managed Beans don't extend core/daemon/src/main/java/org/opennms/netmgt/daemon/AbstractSpringContextJmxServiceDaemon.java
In those cases the implementation currently will throw a NotImplementedException.
Probably this could be handle with 
core/daemon/src/main/java/org/opennms/netmgt/daemon/AbstractServiceDaemon.java
But is not required for this ticket.
Not sure if this is too much for what is needed but I was thinking it would be nice to track more initialization times ...
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14622
=> NMS-14622: Add KPI for startup time

features/endpoints/grafana/client/src/main/java/org/opennms/netmgt/endpoints/grafana/client/PanelDeserializer.java
Fixed issue when Panel type row from older versions is passed (which has a datasource value of null)
Currently Panel type row is not being printed in the report. I think this should be handled on a different jira as an enhancement (see below)
https://github.com/OpenNMS/opennms/blob/07024cd96a8fee67375bd802fc55bc4802374412/integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java#L78
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14784
=> NMS-14784: Grafana Dashboard report fails on "row"

features/enlinkd/adapters/common/src/main/java/org/opennms/netmgt/enlinkd/common/TopologyUpdater.java, features/enlinkd/adapters/updaters/nodes/src/main/java/org/opennms/netmgt/enlinkd/NodesOnmsTopologyUpdater.java, features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/IpLikeSearchProvider.java, features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IpLikeHopCriteria.java, features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/ui/SearchBox.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.history/src/test/java/org/opennms/features/topology/plugins/topo/BundleContextHistoryManagerTest.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdSelectionAware.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyFactory.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProvider.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdMockDataPopulator.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdTopologyProviderTest.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/resources/META-INF/opennms/applicationContext-LinkdTopologyProviderTestIT.xml, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/resources/META-INF/opennms/applicationContext-enhanced-mock.xml
Fixed DefaultVertex in enlinkd topology updaters
Let IplikeSearchProvider be available for all nodes related namespaces
Fixed IpLikeHopCriteria getVertices getting vertices from the graph namespace
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14791
=> NMS-14791 Topology-Map Layer broken

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/HttpMenuRequestContext.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MainMenu.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuEntry.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuRequestContext.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/Notices.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/TopMenuEntry.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/xml/MenuXml.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/xml/package-info.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MenuRestService.java, opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml, opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/menu/MenuProviderTest.java, opennms-webapp-rest/src/test/resources/dispatcher-servlet.xml, opennms-webapp/src/main/java/org/opennms/web/navigate/RoleBasedNavBarEntry.java
Add a MenuRestService. This is part of the UI Preview Foldin for Horizon 31.
This service will be used by the Vue "new UI" menubar to determine how to display the menu links. Also uses mostly the same data sources as the "old" menubar so changes to `dispatcher-servlet.xml` will be picked up by both.
Does the following:
- reads parts of `dispatcher-servlet.xml` to determine most links
- Adds `RoleBasedNavBarEntry` class to allow menu items in `dispatcher-servlet.xml` to be included/excluded based on roles (works for old and new menubars)
- Rest service exposing the `MainMenu` class as Json
- 'Notices' may get removed in the future as user notifications may be handled a different way
- `MenuRequestContext` and `HttpMenuRequestContext` are abstractions so we don't have to pass around …
=> NMS-14801: Add Menu Rest Service

container/features/src/main/resources/features.xml, core/mate/shell-commands/pom.xml
NMS-14754: added changes to features.xml and pom.xml so metadata-test command shows in karaf shell
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14754
=> NMS-14754: opennms:metadata-test command is not present in Karaf shell

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java, opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java, opennms-provision/opennms-provisiond/src/test/resources/single_node.xml
NodeScan objects are reused for scheduled scans, so the flags that are tracked per-scan should be reset between each scan run.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14853
=> NMS-14853: Reset flags before NodeScans are run

opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
This PR is based on https://github.com/OpenNMS/opennms/pull/5427
Since PR from external contributors cannot be run by circle ci we need to use this workaround.
Original PR from from @FrancescoBuc86
Jira: https://issues.opennms.org/browse/NMS-10469
=> NMS-10469: Provisiond import errors don't appear as event reason

opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java, opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java, opennms-webapp/src/test/java/org/opennms/web/event/NMS12517_Test.java
Issue occurred on especific alarm/query and evnt/query servlets that only supported GET requests. 
When adding CSRF parameters the method switched to POST requests.
Also added the `_csrf` parameter to the ignored parameters in the search query generated
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14918
=> NMS-14918: Alarms and Events: filter and advanced search / method POST is not supported

docs/modules/operation/pages/deep-dive/events/perf-data.adoc
The example of snmp-property doesn't populate a graph with data because it takes data from wrong place (`bytesIn` instead of the actual column).
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14961
=> NMS-14961: fix the misuse of a metric name in an example in documentation.

integrations/opennms-jasper-extensions/src/main/java/org/opennms/netmgt/jasper/grafana/GrafanaPanelDatasource.java, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-1ppp.jrxml, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-2ppp.jrxml, opennms-base-assembly/src/main/filtered/etc/report-templates/Grafana-Dashboard-Report-4ppp.jrxml
Modified grafana jasper report templates and grafana jasper datasource  to print panels type row.
Added a new field **rowTitlte** to each grafana report template (.jrxml) and setup some rules, when the there is no row panel content it will remove the textField element from the report (see image)
Test report
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14885
=> NMS-14885: Add support for rows in Grafana Dashboard Report

core/test-api/db/src/main/java/org/opennms/core/test/db/MockDatabase.java, opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/DefaultPollContext.java, opennms-services/src/main/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPoller.java, opennms-services/src/test/java/org/opennms/netmgt/snmpinterfacepoller/SnmpPollerIT.java, opennms-services/src/test/resources/META-INF/opennms/applicationContext-snmpPollerTest.xml, opennms-services/src/test/resources/etc/snmp-interface-poller-configuration.xml, opennms-webapp/src/main/java/org/opennms/web/element/ElementUtil.java, tests/mock-elements/src/main/java/org/opennms/netmgt/mock/MockInterface.java
This adds a new option to the `pollFlag` value in SnmpInterface DB objects. 
Currently, if an interface matched a `MatchingSnmpInterfacePolicy` with the `ENABLE_POLLING` action in the foreign source definition, then it would be marked `P`/ `Polled`. This list of `Polled` interfaces is then compared against package definitions in `snmp-interface-poller.configuration.xml`, and any not matching the criteria of their respective package are not actually polled.
This change sets the flag for those ignored interfaces to `I`, and displays their polling status as `Not Polled` in the UI.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14653
=> NMS-14653: Add 'I' option to poll flag

ui/src/components/Plugin/utils.ts, ui/src/main.ts, ui/src/router/index.ts, ui/src/types/index.ts
Plugins / UI Extensions did not work properly if more than one plugin was installed in OpenNMS at a time. This PR, in conjunction with PRs for ALEC and Cloud plugins, will allow all plugins to work when multiple ones are installed.
- Plugins get `window.VRouter` which is the Vue Router object used in OpenNMS Vue UI, then add their own routes to it. However, they added their routes as children of the 'Plugins' named route. Basically whichever plugin was installed first would have their routes 'win' vs. any subsequently installed plugin. In this PR, Horizon dynamically adds unique parent routes for each installed plugins on startup and plugins should be updated to add their routes under their specific parent route
- Plugin components get stored in `window[pluginId]`, but currently plugins …
=> NMS-14996: Ensure Multiple Plugins Work

features/api-layer/core/src/main/java/org/opennms/features/apilayer/config/PollerConfExtensionManager.java, features/api-layer/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/api-layer/core/src/test/java/org/opennms/features/apilayer/config/PollerConfExtensionManagerTest.java, features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java, features/perspectivepoller/src/main/java/org/opennms/netmgt/perspectivepoller/PerspectivePollJob.java, features/perspectivepoller/src/main/java/org/opennms/netmgt/perspectivepoller/PerspectivePolledService.java, features/perspectivepoller/src/main/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerd.java, features/perspectivepoller/src/test/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerdIT.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/PollerRequestBuilder.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/ServiceMonitorLocator.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/ServiceMonitorRegistry.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/support/DefaultServiceMonitorRegistry.java, features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerClientRpcModule.java, features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestBuilderImpl.java, features/poller/shell/src/main/java/org/opennms/netmgt/poller/shell/Poll.java, opennms-config/src/main/java/org/opennms/netmgt/config/DefaultServiceMonitorLocator.java, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfig.java, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableServiceConfig.java, opennms-services/src/test/java/org/opennms/netmgt/config/PollerConfigWithPSMIT.java, opennms-services/src/test/java/org/opennms/netmgt/mock/MockNetworkTest.java, opennms-services/src/test/java/org/opennms/netmgt/mock/MockPollerConfig.java, opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java, opennms-services/src/test/java/org/opennms/netmgt/poller/PollerQueryManagerDaoIT.java, opennms-services/src/test/java/org/opennms/netmgt/poller/PollerRpcTimeoutIT.java, opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/PollableServiceConfigIT.java, opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/PollablesIT.java, opennms-services/src/test/resources/META-INF/opennms/applicationContext-serviceMonitorRegistry.xml, opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
The lookup of the service monitor implementation can not be done by class name, as there are delegate implementaions like the one used for OIA pollers. Therefor the pollers are now addressed by service locators only. This uses the registered poller class name, which can differ from the actual class in case of delegates. Thus allowing to find the correct implementations in the service monitor registry.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15001
=> NMS-15001: Use service locator key in poller client

features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/LldpTopologyServiceImpl.java, features/enlinkd/service/impl/src/test/java/org/opennms/netmgt/enlinkd/service/ServiceTest.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms0123EnIT.java
Added a match in lldp for when ifindex is -1
ifindex -1 means that there is a failure getting the localportdata
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14743
=> NMS-14743  Rework NMS0123EnIT test

core/schema/src/main/liquibase/32.0.0/changelog.xml, core/schema/src/main/liquibase/changelog.xml, features/enlinkd/adapters/collectors/lldp/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpLocPortGetter.java, features/enlinkd/adapters/collectors/lldp/src/main/java/org/opennms/netmgt/enlinkd/snmp/LldpRemTableTracker.java, features/enlinkd/adapters/collectors/lldp/src/main/java/org/opennms/netmgt/enlinkd/snmp/TimeTetraLldpLocPortGetter.java, features/enlinkd/adapters/collectors/lldp/src/main/java/org/opennms/netmgt/enlinkd/snmp/TimeTetraLldpRemTableTracker.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/BridgeProtocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/CdpProtocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/IsIsProtocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/LldpProtocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/OspfProtocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/Protocol.java, features/enlinkd/generator/src/main/java/org/opennms/enlinkd/generator/protocol/UserDefinedProtocol.java, features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/model/LldpLink.java, features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/LldpLinkDao.java, features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpLinkDaoHibernate.java, features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/LldpTopologyServiceImpl.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdSnmpIT.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms13637EnIT.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms17216EnIT.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms7563EnIT.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms8000EnIT.java, features/enlinkd/tests/src/test/java/org/opennms/netmgt/nb/Nms13637NetworkBuilder.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdMockDataPopulator.java, features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProviderTestIT.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeLinkRestServiceIT.java
Renamed LldpPortNum to be LldpRemIndex and
added lldpRemPortNum to Lldplink table
Reworked Snmp Class correlated and changed
the LldpLinkDao classes to use a new index
primary key nodeid, lldpremportnum, lldpremindex
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-7775
=> NMS-7775: Add lldpRemLocalPortNum in LldpLink Table

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java, opennms-webapp/src/main/java/org/opennms/web/controller/NavBarController.java, opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml, ui/src/router/index.ts
Display Admin "cogs" icon in Menubar for several additional items:
- File Editor - we now display admin icons for items having either `ROLE_ADMIN` or `ROLE_FILESYSTEM_EDITOR`
- External Requisition - added `ROLE_ADMIN`, user must now have this to access this page or see on menu
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15005
=> NMS-15005: Display Admin Icons in Menubar for more items

docs/modules/reference/pages/daemons/daemon-config-files/trapd.adoc
The `<pre />`  tag is not part of the configuration and was used in our Wiki to format it as a code block with a mono-spaced font.
=> fix(doc): Remove <pre /> tag around trapd configuration

smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java
Adding a smoke test which navigates from the legacy menubar to one of the new(er) Vue UI pages.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14910
=> NMS-14910: Smoke test navigating to new Vue UI page

ui/src/components/Map/SeverityFilter.vue
Vue MenuBar dropdown items were being obscured by the `SeverityIndex` component of the GeoMap.
Changed `SeverityIndex` z-index to be `$zindex-sticky` which is just below `$zindex-fixed` which is the z-index of the `FeatherAppBar` (container of MenuBar).
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15149
=> NMS-15149: Fix Vue menubar items obscured by GeoMap

.circleci/config.yml
Add a step to `trigger-path-filtering` to verify the generated 'main.yml' file
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15275
=> NMS-15275: Add step to verify the main.yml file in CircleCI

smoke-test/src/main/java/org/opennms/smoketest/containers/JaegerContainer.java, smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java, smoke-test/src/test/java/org/opennms/smoketest/JaegerTracingIT.java
Ben noticed when doing builds that the JaegerTracingIT smoke test failed if the system name wasn't OpenNMS. This fixes that and also adds some previous refactoring to pull the Jaeger container into its own JaegerContainer class.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15267
=> Jaeger smoke test fixes

.circleci/main/commands/executions/run-integration-tests.yml, .circleci/main/commands/executions/run-smoke-tests.yml
We stopped setting reportsDirectory to
`${project.build.directory}/surefire-reports-${ci.instance} in`
https://github.com/OpenNMS/opennms/commit/9d229346a2a891f3cf89ee7df42011309d01c305 and let is go back to the default. The smoke-test project wasn't affected because it doesn't inherit from the top-level pom.xml.
It is working in the latest build of foundation-2021: https://app.circleci.com/pipelines/github/OpenNMS/opennms/26734/workflows/a3b52ddf-6122-4def-ad76-3aec00854c11/jobs/213699/tests
But it isn't working in foundation-2022 (nor foundation-2023 or release-31.x or develop): https://app.circleci.com/pipelines/github/OpenNMS/opennms/26712/workflows/cee6672b-37c6-4000-b66e-0aecb6076e77/jobs/213483/tests
Gather test results output:
```
#!/bin/bash -eo pipefail
mkdir -p …
```
=> Fix integration test reports

container/features/src/main/resources/features-sentinel.xml, container/features/src/main/resources/features.xml, dependencies/spring/pom.xml, pom.xml, protocols/cifs/pom.xml
This PR bumps our embedded javassist to the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15191
=> NMS-15191: bump javassist to 3.29.2-GA

container/karaf/pom.xml, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/pom.xml, container/shared/src/main/filtered-resources/etc/overrides.properties, opennms-full-assembly/src/assembly/components/osgi.xml, pom.xml
This PR bumps xstream to the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15196
=> NMS-15196: bump xstream version to 1.4.20

pom.xml
This PR bumps quartz to version 2.3.2
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15194
=> NMS-15194: update quartz to 2.3.2

container/features/src/main/resources/features.xml, pom.xml, protocols/xml/pom.xml, smoke-test/pom.xml
The original JSCH is abandoned, this PR changes to the maintained fork, and uses the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15200
=> NMS-15200: use forked jsch, move to latest version

container/features/src/main/resources/features.xml, container/karaf/pom.xml, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/pom.xml, container/shared/src/main/filtered-resources/etc/overrides.properties, dependencies/jasypt/pom.xml, opennms-full-assembly/src/assembly/components/osgi.xml, pom.xml
This PR bumps our included jasypt to the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15197
=> NMS-15197: update jasypt to 1.9.3

container/features/src/main/resources/features.xml, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/src/main/filtered-resources/etc/overrides.properties, opennms-full-assembly/src/assembly/components/osgi.xml
This PR bumps proton-j to the latest 0.x version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15202
=> NMS-15202: update proton-j to 0.34.0

pom.xml
Not knowing how it would affect things, I only bumped to the latest 3.16.x, rather than the latest 3.x, since 3.16.3 was sufficient to avoid known CVEs.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15201
=> NMS-15201: bump protobuf to latest 3.16.x

container/features/src/main/resources/features.xml, pom.xml
This PR bumps `xmlgraphics-commons` to the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15205
=> NMS-15205: update xmlgraphics-commons and fix fop dependencies

pom.xml
This PR bumps the Kafka version to 3.3 to resolve an [issue with rebalancing](https://issues.apache.org/jira/browse/KAFKA-14024).
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15317
=> NMS-15317: bump kafka to 3.3.1

pom.xml
This PR bumps our jboss-logging dependency to 3.5.0.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15192
=> NMS-15192: bump jboss-logging to 3.5.0.Final

pom.xml
This PR bumps jdom2 to the latest version.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15198
=> NMS-15198: bump jdom2 to 2.0.6.1

pom.xml, smoke-test/pom.xml
This PR bumps our junit to the latest 4.x.
We have had problems in the past doing this, but I suspect it was because of the "vintage engine" thing I fixed in the second commit.
I have rebased to remove the commit before merging so I don't create a bunch of churn, but [the previous build](https://app.circleci.com/pipelines/github/OpenNMS/opennms/26942/workflows/2f6c25bd-46cb-4d6e-973c-f8610e94e12a) touched every single test and went green.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15074
=> NMS-15074: bump junit4 to latest

container/features/src/main/resources/features-minion.xml, container/features/src/main/resources/features.xml, container/karaf/pom.xml, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/pom.xml, container/shared/src/main/filtered-resources/etc/overrides.properties, features/minion/repository/src/assembly/repo.xml, opennms-full-assembly/src/assembly/components/osgi.xml, pom.xml
This PR updates jettison to 1.4.1. 1.5.3 is technically out but bumping it makes overriding things more complicated.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15199
=> NMS-15199: bump jettison transient feature dep to 1.4.1

smoke-test/src/main/java/org/opennms/smoketest/containers/CassandraContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/JaegerContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/KarafContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/PostgreSQLContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java, smoke-test/src/test/java/org/opennms/smoketest/OpenNMSCloudPluginIT.java, smoke-test/src/test/java/org/opennms/smoketest/OpenNMSSeleniumIT.java
This just cleans up some warnings I came across in our container classes that extend GenericContainers. It seemed easy to fix (which was *almost* true), so I cleaned them up.
The [MockCloudContainer](https://github.com/OpenNMS/opennms/pull/5678/commits/49df9f862bae8277ad15445367a0c63f1f769918) change wasn't something I expected to do, but it let me eliminate the last case of a raw type of GenericContainer being used. And overall, I like the change (I hope others agree, :grin:).
While moving MockCloudContainer into its own class, I noticed some duplication with installing KAR features, which led me to [Move installFeature into KarafContainer.](https://github.com/OpenNMS/opennms/pull/5678/commits/c2ae9e962d5f645411d013694033910333247b35) 
I also deduplicated the Jaeger Thrift HTTP while I …
=> Cleanup some GenericContainer warnings

.circleci/config.yml
This PR fixes the `docker_gc` automation to do a number of things:
1. write a `config.json` docker file to avoid having to deal with multiple levels of escaping around doing `expect` commands
2. add `minion`, `sentinel`, and `meridian-minion` to the list of images that can be cleaned up
3. add `jira` and `dependabot` to the list of branch types to clean up (also: increase strictness of _where_ these keywords get matched)
=> fixes and improvements for docker_gc

.circleci/scripts/smoke.sh, opennms-base-assembly/src/main/filtered/bin/opennms, smoke-test/pom.xml, smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/PostgreSQLContainer.java, smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java, smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
- Allow thread dumps on shutdown to be disabled.
- Add "restart-fast" option to opennms script.
- Disable code coverage collection by default in smoke tests
- Speedup thread dump collection and store in its own file
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15387
=> Smoke test improvements and tweaks to help developers

container/extender/pom.xml, container/extender/src/main/java/org/opennms/karaf/extender/KarDependencyHandler.java, container/extender/src/main/java/org/opennms/karaf/extender/KarafExtender.java, container/extender/src/main/resources/OSGI-INF/blueprint/blueprint.xml, container/features/src/main/resources/features-core.xml, container/features/src/main/resources/features-minion.xml, container/features/src/main/resources/features.xml, container/features/src/main/resources/karaf-extensions.xml, core/health/api/src/main/java/org/opennms/core/health/api/DefaultPassiveHealthCheck.java, features/minion/runInPlace.sh, smoke-test/src/test/java/org/opennms/smoketest/minion/MinionRestIT.java
With this in featuresBoot.d:
```
opennms@onms-core-0:~$ cat etc/featuresBoot.d/*
opennms-plugins-cortex-tss wait-for-kar=opennms-cortex-tss-plugin
opennms-timeseries-api
```
```
admin@opennms()> health-check
Command not found: health-check
admin@opennms()> health-check
Verifying the health of the container
Karaf extender                [ Starting ] => Installing features: [opennms-plugins-cortex-tss]
Verifying installed bundles   [ Failure  ] => Bundle 79 is resolved, but not active
=> Oh no, something is wrong
admin@opennms()> health-check
Verifying the health of the container
Karaf extender                [ Starting ] => Installing features: [opennms-plugins-cortex-tss]
Verifying installed bundles   [ Success  ]
=> Oh no, something is wrong
... snip ...
admin@opennms()> health-check …
```
=> Feature: add a KarafExtender health check

.circleci/build-triggers.override.json, .circleci/main/commands/oci/oci.yml, .circleci/main/jobs/oci/horizon-image-single-arch-linux-amd64.yml, .circleci/main/jobs/oci/horizon-image-single-arch.yml, .circleci/main/jobs/oci/minion-image-single-arch-linux-amd64.yml, .circleci/main/jobs/oci/minion-image-single-arch.yml, .circleci/main/jobs/oci/sentinel-image-single-arch-linux-amd64.yml, .circleci/main/jobs/oci/sentinel-image-single-arch.yml, .circleci/main/jobs/publish.yml, .circleci/main/workflows/workflows_v2.json, .circleci/scripts/lib-docker.sh, .circleci/scripts/publish-azure.sh, .circleci/scripts/publish-cloudsmith.sh, .circleci/scripts/publish-dockerhub.sh
This PR implements docker image signing using [cosign](https://github.com/sigstore/cosign), an alternative to Docker Content Trust that supports signing other arbitrary resources including SBOMs (Software Bill-Of-Materials).
I have implemented SBOM-signing/attestation along with image signing.
Once approved, I will remove the temporary code that allowed me to publish from my branch to dockerhub and similar.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15341
=> NMS-15341: cosign image and SBOM signing and attestation

opennms-webapp/src/main/java/org/opennms/web/controller/RrdSummaryController.java
This resolves the internal server error, but some of the concurrent curl calls fail to connect to the server. See JIRA issue for more details.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15086
=> NMS-15086: Synchronize calls to RRD summary endpoint

container/features/src/main/resources/features.xml, core/db/src/main/java/org/opennms/core/db/DataSourceFactory.java, core/db/src/main/java/org/opennms/core/db/HikariCPConnectionFactory.java, core/test-api/db/src/main/java/org/opennms/core/test/db/TemporaryDatabaseExecutionListener.java, dependencies/quartz/pom.xml, features/device-config/monitor/pom.xml, features/device-config/rest/pom.xml, features/perspectivepoller/pom.xml, opennms-base-assembly/src/main/filtered/etc/log4j2.xml, pom.xml
JIRA: https://opennms.atlassian.net/browse/NMS-15171
Revised PR for upgrading HikariCP. Updates include:
* All ITs pass cleanly now (limit # of connections in the pool)
* Make sure `HikariCP-java7` doesn't end up in `lib/` (quartz was pulling it in)
* Update log settings to suppress harmless, but possibly scary, stack trace on startup (see https://github.com/pgjdbc/pgjdbc/issues/1102 for details) (our version of Hibernate doesn't support suppress the check in the first place)
=> NMS-15171: Upgrade HikariCP to 5.x (take 2)

opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
The build process is renaming these placeholders to `OpenNMS Base Assembly` instead of leaving them as-is to act as a substitution placeholder at runtime.
=> Escape JMX resource type labels

ui/src/components/Layout/Menubar.vue
The `FeatherAppBar` adds some "elevation" using `box-shadow`. However, the "legacy" menu bar does not have this, and also it conflicts a bit with the Meridian color scheme. Just removing this box-shadow.
This was previously merged to `release-31.x` for Horizon, this PR is for Meridian.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15367
=> NMS-15367: Remove elevation from menubar

.circleci/config.yml
This PR creates (non-setup) parameters for `is_pr`, so we can decide whether to do jira notifications or not.
=> set parameters for is_pr, use them for jira notify

features/collection/api/src/main/java/org/opennms/netmgt/collection/support/PersistRegexSelectorStrategy.java, opennms-services/src/main/java/org/opennms/netmgt/collectd/PersistRegexSelectorStrategy.java
This PR moves the `PersistRegexSelectorStrategy` where it belongs, and provides a shim class for backwards compatibility.
=> NMS-15461: fix location of persist regex strategy

docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15410
1. Rename the package `opennms-cloud-plugin` to `opennms-plugin-cloud`. 
> You can use `yum` or `apt` to make sure your `opennms-cloud-plugin` package is up to date.
Was:
```
opennms@opennms:~$ apt search opennms-cloud-**plugin**
Sorting... Done
Full Text Search... Done
```
Now:
```
opennms@opennms:~$ apt search opennms-**plugin**-cloud
Sorting... Done
Full Text Search... Done
opennms-plugin-cloud/opennms-31 1.0.6-1 all
OpenNMS :: Plugins :: Cloud Plugin
```
2. Rephrase the line to avoid repetition between lines 39 and 46
> 39: To ensure that the feature is activated on future service restarts, add the feature to a file in `featuresBoot.d`:
> 46: You must configure your {page-component-title} instance to load the Cloud …
=> [NMS-15410] replace a reference to a file by its content.

container/features/src/main/resources/features.xml, features/inmemory-timeseries-plugin/pom.xml, features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/InMemoryStorage.java, features/inmemory-timeseries-plugin/src/main/java/org/opennms/features/timeseries/plugin/shell/GetMetricsCommand.java, features/inmemory-timeseries-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/pom.xml, opennms-full-assembly/pom.xml, pom.xml, smoke-test/src/test/java/org/opennms/smoketest/TimeseriesAPIIT.java
The `inmemory-timeseries-plugin` feature is a repackaged version of this: https://github.com/OpenNMS/opennms-integration-api/tree/master/test-suites/tss-tests. I pulled it into the project so I could install it as a feature for testing.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14966
=> NMS-14966: Add smoke test for dual timeseries writes

opennms-webapp/pom.xml, pom.xml
Removing POI dependency altogether. It is not anywhere in our dependencies anymore.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14589
=> NMS-14589: remove POI which is no longer needed

docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/enum-lookup.adoc
The second property didn't have the required 'enum-attribute' parameter. Let me know if I should create a jira for this.
=> Minor EnumLookupPropertyExteneder docs update

dependencies/quartz/pom.xml, pom.xml
This PR makes sure Quartz doesn't pull in an old c3p0 jar through a dependency on `c3p0:c3p0` (before it got moved to `com.mchange:c3p0`)
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15072
=> NMS-15072: fix transient old c3p0 dependency

opennms-services/src/main/java/org/opennms/netmgt/scriptd/Executor.java, opennms-services/src/main/java/org/opennms/netmgt/scriptd/Scriptd.java
@jeffgdotorg noticed that my previous "fix" would never handle the reload event, because the processor would never get registered if there were no Scriptd scripts. :D
This fixes it to process reload events separately.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-13216
=> NMS-13216: always handle reload event in Scriptd

features/collection/snmp-collector/src/main/java/org/opennms/netmgt/collectd/SnmpPropertyExtenderProcessor.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorWithMibPropertiesIT.java, opennms-services/src/test/resources/org/opennms/netmgt/config/datacollection-config-NMS15342.xml
Interface-level resources are given the resourceType `if,` which is used as a reference in thresholding config files and possibly elsewhere. Rather than changing that, this just adjusts SnmpPropertyExtender matching to allow `ifIndex` to match with `if` resources.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15342
=> NMS-15342: Allow property extenders to index by ifIndex

container/features/src/main/resources/features-experimental.xml, container/features/src/main/resources/features.xml, container/karaf/pom.xml, pom.xml
This PR bumps Xalan to our (early) deployment of the official upstream binaries.
When Xalan and the servicemix version of Xalan are in Maven Central, we can convert this to a "normal" 2.7.3 release.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15578
=> NMS-15578: bump Xalan to 2.7.3

opennms-container/core/Dockerfile, opennms-container/core/container-fs/health.sh
Basic health check script based off of similar scripts used by sentinel/minion. The documentation still has 
```
test: [ 'CMD', 'curl', '-f', '-I', 'http://localhost:8980/opennms/login.jsp' ]
```
listed for the health check in the recommended docker-compose file. 
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15291
=> NMS-15291: Add health check for core container

.circleci/config.yml, container/features/src/license/THIRD-PARTY.properties, opennms-assemblies/http-remoting/src/license/THIRD-PARTY.properties, opennms-webapp/src/license/THIRD-PARTY.properties, pom.xml
The plugin walks dependencies _anyway_, so the only time we actually need to generate these things is in the assembly stage
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15572
=> NMS-15572: reenable license maven plugin

opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
This lets us do more complex rules, to allow user/admin/etc. to ack/unack/escalate/clear alarms, but disallow readonly users.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15080
=> NMS-15080: move rest alarms to a pattern with expression support

opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
Threshd config was not being updated with the rest when outages were added.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15420
=> NMS-15420: Update threshd config on outage change

features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsMetadataDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java, features/datachoices/src/main/resources/web/datachoicesMetadata.json
Add Rest endpoints in Datachoices Rest service to return current "enabled" status along with metadata.
The metadata maps keys in the datachoices data response to names, descriptions, and any other data the UI may need to display the new Usage Statistics Sharing UI.
Metadata data is in a json resource file. It will be updated in a subsequent PR, there are just some initial values there.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15476
=> NMS-15476: Rest API for Statistics Sharing status and metadata

opennms-alarms/syslog-northbounder/src/main/java/org/opennms/netmgt/alarmd/northbounder/syslog/SyslogUtils.java
This line is not needed and is causing maxMessageSize to get overwritten, see https://github.com/graylog-labs/syslog4j-graylog2/blob/master/src/main/java/org/graylog2/syslog4j/impl/AbstractSyslogConfig.java#L64
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15606
=> NMS-15606: Remove unneeded config option to avoid side effects

features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java, features/datachoices/src/main/resources/web/datachoicesMetadata.json, ui/package.json, ui/src/components/UsageStatistics/UsageStatisticsHeader.vue, ui/src/components/UsageStatistics/UsageStatisticsModal.vue, ui/src/components/UsageStatistics/UsageStatisticsTable.vue, ui/src/containers/UsageStatistics.vue, ui/src/lib/utils.ts, ui/src/router/index.ts, ui/src/services/index.ts, ui/src/services/usageStatisticsService.ts, ui/src/store/index.ts, ui/src/store/usageStatistics/actions.ts, ui/src/store/usageStatistics/index.ts, ui/src/store/usageStatistics/mutations.ts, ui/src/store/usageStatistics/state.ts, ui/src/types/usageStatistics.d.ts
New "Usage Statistics Sharing" Vue UI screen to display current usage statistics and allow using to enable/disable statistics collection.
Basing this on `develop` since it won't be directly accessible right now and does not impact any other functionality. Future work (i.e. changes to how opt-in/opt-out works, etc.) will be done in a feature branch until it's ready to be merged to `develop` as a whole.
Adds a new "Usage Statistics Sharing" Vue page. Displays statistics in a sortable, scrollable table; items that are objects or large strings have a clickable link to display the full value in a modal popup. User can also copy entire Json to clipboard. Also displays status of whether statistics sharing is enabled, plus a button to enable/disable sharing.
Also:
- updates "Datachoices" Rest …
=> NMS-15481: Usage Stats Sharing UI: Initial UI page and API wireup

pom.xml
Develop (future Horizon 32) is already on Groovy 3, but older releases should get updated to the latest 2.x for security reasons.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15633
=> NMS-15633: bump to latest groovy 2.x

docs/modules/development/pages/rest/osgi.adoc, features/config/upgrade/src/main/resources/changelog-cm/32.0.0/changelog-cm.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/StateManager.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/AdminPageNavEntry.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/ModalInjector.java, features/datachoices/src/main/resources/web/modal.ftl.html, ui/src/components/UsageStatistics/UsageStatisticsHeader.vue, ui/src/store/usageStatistics/actions.ts, ui/src/types/usageStatistics.d.ts
NMS-15479: Usage Statistics Sharing notice dialog and support for displaying notice initially.
- Displays a new "notice" dialog / toast at bottom of screen when an Admin user logs in and has not yet acknowledged the notice
- Notice has buttons for just dismissing it or else going to Usage Stats Sharing UI page
- Clicking on either button results in boolean value being set in CM configuration to ack the notice; dialog won't be displayed any more
- If user had previously enabled/disabled stats sharing and it's in the database, that selection will be respected
- Removed old Data Choices popup and link on admin page; new link is "Usage Statistics Sharing"
- Removed old DataChoiceRestService endpoint for enable/disable sharing status, it's superceded by `rest/datachoices/status` endpoint.
- …
=> NMS-15479: Usage Stats Sharing notice dialog

core/web-assets/package-lock.json, core/web-assets/package.json
This PR bumps backshift to the version containing POW fixes as part of NMS-14779
=> NMS-14779: Update Backshift to 1.3.2

docs/modules/development/pages/rest/osgi.adoc, features/config/upgrade/src/main/resources/changelog-cm/32.0.0/changelog-cm.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/StateManager.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/AdminPageNavEntry.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/ModalInjector.java, features/datachoices/src/main/resources/web/modal.ftl.html, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/AdminPageIT.java, smoke-test/src/test/java/org/opennms/smoketest/rest/DataChoicesRestServiceIT.java, ui/src/components/UsageStatistics/UsageStatisticsHeader.vue, ui/src/store/usageStatistics/actions.ts, ui/src/types/usageStatistics.d.ts
NMS-15479: Usage Statistics Sharing notice dialog and support for displaying notice initially.
This is a redo of PR #6072 but with fixing the smoke tests.
All tests passed on CircleCI except minion smoke tests, which don't seem to be related.
- Displays a new "notice" dialog / toast at bottom of screen when an Admin user logs in and has not yet acknowledged the notice
- Notice has buttons for just dismissing it or else going to Usage Stats Sharing UI page
- Clicking on either button results in boolean value being set in CM configuration to ack the notice; dialog won't be displayed any more
- If user had previously enabled/disabled stats sharing and it's in the database, that selection will be respected
- Removed old Data Choices popup and link on admin page; new link is "Usage Statistics …
=> NMS-15479: Usage Statistics Sharing Notice dialog

features/config/upgrade/src/main/resources/changelog-cm/32.0.0/changelog-cm.xml
Enable Usage Statistics Sharing by default, but respecting any previously-made choice.
Updates CM `org.opennms.features.datachoices` `enabled` value to `true`, if it was `null` (never previously opted in or out), doesn't change it if it was `false`.
Note, CM (Configuration Management) liquibase updates run on OpenNMS application startup; this will run just once.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15485
=> NMS-15485: Enable Usage Stats Sharing by default

core/test-api/services/src/main/resources/minimal-eventconf.xml, opennms-base-assembly/src/main/filtered/etc/events/opennms.internal.events.xml, opennms-base-assembly/src/main/resources/contrib/qosdaemon/qos_example_configuration/opennms_fault_config/eventconf.xml, opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-speedtest/eventconf.xml, opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/eventconf-wildcard/eventconf.xml, opennms-dao-mock/src/main/resources/minimal-eventconf.xml, opennms-services/src/test/resources/org/opennms/netmgt/mock/eventconf.xml
fix: typo 
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15421
=> NMS-15421: Fixing typo for event uei.opennms.org/internal/schedOutagesChanged

opennms-base-assembly/src/main/filtered/etc/opennms.service
(backport to 2020)
Update the opennms.service to include:
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15596
=> NMS-15596: Update opennms.service

docs/modules/operation/pages/deep-dive/service-assurance/configuration.adoc, features/poller/shell/src/main/java/org/opennms/netmgt/poller/shell/Benchmark.java, opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml, opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties, opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/poller/PollerConfiguration.java, opennms-config-jaxb/src/main/resources/xsds/poller-configuration.xsd, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfig.java, opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java, opennms-services/pom.xml, opennms-services/src/main/java/org/opennms/netmgt/poller/AsyncPollingEngine.java, opennms-services/src/main/java/org/opennms/netmgt/poller/DefaultPollContext.java, opennms-services/src/main/java/org/opennms/netmgt/poller/jmx/Pollerd.java, opennms-services/src/main/java/org/opennms/netmgt/poller/jmx/PollerdMBean.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollConfig.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollContext.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableService.java, opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableServiceConfig.java, opennms-services/src/test/java/org/opennms/netmgt/mock/MockPollerConfig.java, opennms-services/src/test/java/org/opennms/netmgt/poller/mock/MockPollContext.java
JIRA: https://opennms.atlassian.net/browse/NMS-15623
Here's a patch that adds support for asynchronous polling to pollerd. The behaviour is optional is done in a very unobtrusive way, allowing us to vet the solution is practice without affecting existing solutions.
When enabled, polls are triggered by the thread pools, using a configurable rate-limiter for back-pressure, and then the thread is released. When the poll is complete, execution is passed to cached thread poll (implicitly bounded by the rate limit) and the node lock  is acquired before processing the results.
=> Asynchronous polling engine & benchmarking tool

features/config/upgrade/src/main/resources/changelog-cm/32.0.0/changelog-cm.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/StateManager.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/ModalInjector.java
If user already opted-out of Usage Statistics Sharing, do not display the notice.
Also fixes a bug where `initialNoticeAcknowledged` should be set to an actual `boolean` value and not `null`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15493
=> NMS-15493: Usage stats, don't display notice if opted-out

core/test-api/lib/src/main/java/org/opennms/core/test/OpenNMSJUnit4ClassRunner.java, core/test-api/pom.xml, core/test-api/ssh/pom.xml, core/test-api/ssh/src/main/java/org/opennms/core/test/ssh/JUnitSshServerExecutionListener.java, core/test-api/ssh/src/main/java/org/opennms/core/test/ssh/SshServerDataProvider.java, core/test-api/ssh/src/main/java/org/opennms/core/test/ssh/SshServerDataProviderAware.java, core/test-api/ssh/src/main/java/org/opennms/core/test/ssh/annotations/JUnitSshServer.java, core/test-api/ssh/src/main/java/org/opennms/core/test/ssh/annotations/SshLogin.java, features/poller/monitors/core/pom.xml, features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/SshMonitorIT.java, opennms-services/pom.xml, opennms-services/src/test/java/org/opennms/netmgt/protocols/SshIT.java, pom.xml
My work laptop doesn't have `sshd` running, so a few ssh-related tests fail. This PR fixes that by not relying on an external sshd, instead creating one using Apache Mina.
=> add an SSH server for junit tests

opennms-webapp-rest/pom.xml, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MainMenu.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java, ui/package.json, ui/src/App.vue, ui/src/components/Layout/Footer.vue, ui/src/types/mainMenu.d.ts
Add a footer similar to the "legacy" footer to the newer Vue UI pages.
This uses styling taken from legacy page, but alignment will be slightly different since it uses same font as Vue UI rather than old UI.
Menu Rest service updated to include the `copyrightDates` and `version` which are retrieved dynamically, Vue footer uses these.
Also added a `build:dev` `npm/yarn` script entry to build UI in non-minified mode without having to edit the `vite.config.ts` file.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15262
=> NMS-15262: Footer on Vue UI pages

opennms-config/src/main/java/org/opennms/netmgt/filter/JdbcFilterDao.java
JIRA: https://opennms.atlassian.net/browse/NMS-15696
This class doesn't use Spring/Hibernate, so injecting transaction support via AOP adds unnecessary overhead and leaves us with possible deadlock scenarios. More details in the associated JIRA.
=> NMS-15696: Remove @Transactional annotation from JdbcFilterDao

container/features/src/main/resources/features-core.xml, container/karaf/pom.xml, container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg, container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/pom.xml, container/shared/src/main/filtered-resources/etc/blacklisted.properties, container/shared/src/main/filtered-resources/etc/org.apache.karaf.features.cfg, container/shared/src/main/filtered-resources/etc/overrides.properties, features/container/sentinel/src/main/filtered-resources/etc/org.apache.karaf.features.cfg, opennms-full-assembly/pom.xml, opennms-full-assembly/src/assembly/components/osgi.xml, pom.xml
This PR cleans up our Karaf sshd upgrade/dependencies, and bumps the version to 2.10.0, which should solve some disconnect issues we've seen in the real world.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15714
=> NMS-15714: normalize Karaf sshd

features/events/api/src/main/java/org/opennms/netmgt/events/api/DateTimeAdapter.java, features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java, features/events/api/src/main/java/org/opennms/netmgt/events/api/LegacyDatetimeFormatter.java, features/events/api/src/test/java/org/opennms/netmgt/events/api/LegacyDatetimeFormatterTest.java, opennms-config/src/main/java/org/opennms/netmgt/config/DestinationPathManager.java, opennms-config/src/main/java/org/opennms/netmgt/config/GroupManager.java, opennms-config/src/main/java/org/opennms/netmgt/config/NotificationManager.java, opennms-config/src/main/java/org/opennms/netmgt/config/UserManager.java, opennms-model/src/test/java/org/opennms/netmgt/model/events/EventConstantsTest.java, opennms-services/src/main/java/org/opennms/netmgt/rtc/AvailabilityServiceHibernateImpl.java, opennms-services/src/main/java/org/opennms/netmgt/rtc/utils/LegacyEuiLevelMapper.java, opennms-services/src/main/java/org/opennms/netmgt/scriptd/helper/SnmpTrapForwarderHelper.java, opennms-services/src/main/java/org/opennms/netmgt/scriptd/helper/SnmpTrapHelper.java
Guess who should have written more unit tests the first time? \<grin>
Turns out `Boolean.parseBoolean()` != `Boolean.getBoolean()` 😅
Anyway, in the process of adding test coverage, I discovered my error in the original NMS-15471 patch.
I considered just fixing the bug, but the code is cleaner and more testable this way.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15471
=> NMS-15471: legacy formatter fixes

opennms-full-assembly/pom.xml
This PR switches the activemq broker feature we use to the version that doesn't pull in the war, since we don't use/need it.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15686
=> NMS-15686: use the activemq feature that doesn't pull in the war

ui/src/components/Layout/Menubar.vue
Clicking on the OpenNMS logo on Vue pages should navigate to same place as on legacy pages. Use `mainMenu.homeUrl` for this instead of hard-coding `'/'`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15721
=> NMS-15721: Fix Vue logo link target location

opennms-webapp/src/main/java/org/opennms/web/account/selfService/NewPasswordActionServlet.java, opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp
This PR reinstates the NMS-13981 changes to refactor the password policy code to be shared between the backend and UI.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14898
=> NMS-14898: reinstate Weak Password Policy (minor refactor)

core/jmx/api/src/main/java/org/opennms/netmgt/jmx/connection/JmxConnectionConfig.java
Documentation and default configs reference `PASSWORD-CLEAR` for JMX credentials though the code is looking for `PASSWORD_CLEAR`.  This PR updates the JmxConnectionConfig to accept either version of the setting, so users with existing configs don't need to update, so this shouldn't be a breaking change for existing Meridians.
Will follow up with a separate PR to change the docs and defaults to be consistent.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14884
=> NMS-14884: Handle JMX `PASSWORD-CLEAR` as `PASSWORD_CLEAR`

opennms-base-assembly/src/main/filtered/etc/opennms.properties, opennms-jetty/src/main/resources/org/opennms/netmgt/jetty/jetty.xml
The problem occurs on page where we use relative redirects. In the Response class these redirects are converted to absolute URLs including the scheme and since this class does not know that the current location is HTTPS it is converted to the HTTP URL. Firefox and some other browsers allow the call because it is immediatly redirected to the correspondig HTTPS page. Chrome seems more picky and does not allow to query the HTTP page. The fix is to allow relative redirects in our jetty configuration. In this case relative URLs will not be converted to absolute ones, so the scheme is not affected and stays the same. 
* JIRA: https://opennms.atlassian.net/browse/NMS-15732
=> NMS-15732: Allowing relative redirects

docs/modules/reference/pages/service-assurance/monitors/SshMonitor.adoc
Make a reflective mention to the MinaSshMonitor from the SshMonitor page.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15431
=> NMS-15431: Doc reference MinaSshMonitor on SshMonitor page

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/StringIntervalAdapter.java, opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/StringIntervalPropertyEditor.java, opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/StringIntervalAdapterTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15768
=> NMS-15768: Fixed scan-interval handling

docs/modules/deployment/pages/sentinel/introduction.adoc, docs/modules/deployment/pages/sentinel/runtime/install.adoc, docs/modules/operation/pages/deep-dive/flows/aggregation.adoc, docs/modules/operation/pages/deep-dive/flows/basic.adoc, docs/modules/operation/pages/deep-dive/flows/classification-engine.adoc, docs/modules/operation/pages/deep-dive/flows/data-collection.adoc, docs/modules/operation/pages/deep-dive/flows/distributed.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/ipfix.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/message-broker/activemq.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/message-broker/kafka.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/netflow5.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/netflow9.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/sentinel.adoc, docs/modules/operation/pages/deep-dive/flows/sentinel/sflow.adoc, docs/modules/operation/pages/deep-dive/flows/thresholding.adoc, docs/modules/reference/pages/configuration/sentinel-features.adoc
Replaces https://github.com/OpenNMS/opennms/pull/6149 to target `foundation-2023` instead of `release-32.x`.  Includes changes from that PR as well as a couple other cleanup items in the Sentinel and Flows docs.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15708
=> NMS-15708: various corrections/clarifications in Sentinel docs

docs/modules/operation/pages/deep-dive/service-assurance/configuration.adoc, opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
Turn on asynchronous polling by default.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15738
=> NMS-15738: enable asynchronous polling by default

.circleci/main/workflows/workflows_v2.json, .circleci/scripts/lib-docker.sh, opennms-container/common.mk, opennms-container/core/Dockerfile, opennms-container/core/container-fs/health.sh, opennms-container/core/plugins.sh, opennms-container/minion/Dockerfile, opennms-container/minion/plugins.sh, opennms-container/sentinel/Dockerfile, opennms-container/sentinel/plugins.sh
This PR merges our changes to the base container to use RedHat's UBI.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15788
=> NMS-15788: switch Horizon 33 to UBI

features/timeseries/src/main/java/org/opennms/netmgt/timeseries/resource/TimeseriesResourceStorageDao.java, features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/MetaTagDataLoader.java
This PR resolves an `ArrayIndexOutOfBoundException` found when enabling the `rrd-status` feature (although it's actually a general issue with reading certain kinds of metadata).
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/${JIRA-ISSUE-NUMBER}
=> NMS-15806: fix some bounds-checking on possible null values

docs/modules/operation/pages/deep-dive/service-assurance/polling-packages.adoc
Based on values per https://github.com/OpenNMS/opennms/blob/de93eea5b5609bc7c4e96ddd5007f2694f4719e2/opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptor.java#L119-L125
=> Add values to rrd-status docs

opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/JSR223ScriptCache.java, opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/ScriptPolicy.java, opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/ScriptPolicyTest.java, opennms-provision/opennms-provisiond/src/main/resources/META-INF/opennms/applicationContext-provisiond.xml
JIRA: https://opennms.atlassian.net/browse/NMS-15798
Here we create a cache for the compile Groovy scripts that is shared among different instances of the ScriptPolicy. This avoid having to recompile the script for every scan on every node, which reduces the impact of Groovy classloader leaks.
=> NMS-15798: Cache compiled scripts to avoid Groovy classloader leak

container/features/src/main/resources/features-minion.xml, container/features/src/main/resources/features-sentinel.xml, container/features/src/main/resources/features.xml, features/api-layer/dao-common/pom.xml, features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/ModelMappersTest.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/model/OpennmsModelProtos.java, features/kafka/producer/src/main/proto/opennms-kafka-producer.proto, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/model/OpennmsModelProtosTest.java, features/telemetry/protocols/jti/adapter/pom.xml, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/CpuMemoryUtilizationOuterClass.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/FirewallOuterClass.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/LogicalPortOuterClass.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/LspMon.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/LspStatsOuterClass.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/Port.java, features/telemetry/protocols/jti/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/jti/adapter/proto/TelemetryTop.java, features/topologies/service/api/src/main/java/org/opennms/netmgt/topologies/service/api/OnmsTopologyProtocol.java, pom.xml
Note: this PR looks like a lot has changed, but actually the only real difference is that I got rid of `org.opennms.netmgt.enlinkd.service.api.ProtocolSupported` and changed everything that relied upon it to use the `TopologyProtocol` from OPA (1.6 and up) instead. I also cleaned up the Karaf feature files to use a single feature that defines the `protobuf` dependency.
These changes get rid of one of the places where code is duplicated. :)
Unfortunately, the updates _also_ needed to get put into the `opennms-kafka-producer.proto` file, which is a part of both Horizon _and_ ALEC.
Long-term, we should ideally move the proto file (and its generated classes) to OPA, and let everything rely on a single copy everywhere, and just use the enum generated as part of the protobuf file instead rather …
=> NMS-15808: enlinkd enum refactor fix

debian/opennms-server.postinst, tools/packages/minion/minion.spec, tools/packages/opennms/opennms.spec, tools/packages/sentinel/sentinel.spec
JIRA: https://opennms.atlassian.net/browse/NMS-15809
If /data or /data/tmp are present but empty, find throws an error when searching 'directory/*'. Instead, increase the -maxdepth argument and add a -mindepth argument to achieve the same result without risking a 'No such file or directory' error.
=> NMS-15809: Avoid errors in postinstall scripts when directories are empty

features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java, opennms-webapp/src/main/java/org/opennms/web/account/selfService/AbstractBasePasswordChangeActionServlet.java, opennms-webapp/src/main/java/org/opennms/web/account/selfService/PasswordGateActionServlet.java, opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml, opennms-webapp/src/main/webapp/WEB-INF/web.xml, opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp, opennms-webapp/src/main/webapp/account/selfService/passwordGate.jsp, opennms-webapp/src/main/webapp/login.jsp, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
Initial implementation of a password change prompt when the default admin user logs in with username `admin`, password `admin`.
- Update login page to check for “admin/admin” and redirect to Password Gate page
- Implement Password Gate page which allows user to either change password or skip
- Clicking “skip” will respect navigating to original target page (if it wasn’t just the login page)
- Refactored password change servlets to abstract base class since they contain much of the same functionality
- Fix integration and smoke tests to click “Skip” so they all still work
- Doesn’t include smoke test for this functionality and UI/UX will need review
Target branch is a feature branch. When smoke test and any UX changes have been implemented and merge to feature branch, will open a separate …
=> NMS-15780: Admin Password Change Prompt

opennms-base-assembly/pom.xml, smoke-test/pom.xml
Developer build (on Mac) failing due to `MalformedInputException: Length = 1` error while executing the Maven `resource` or `copy-resources` goal and copying `scv.jce`, which is a binary file.
Seems to be caused by this file not being excluded from Maven filtering, probably due to trying to read this binary file using UTF-8 encoding. Solution is to exclude file from the filtering process. 
Occurring in `develop` branch; targeting `foundation-2023` since it's a bug fix.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15869
=> NMS-15869: Exclude 'scv.jce' from filtered resources

docs/modules/reference/pages/service-assurance/monitors/PageSequenceMonitor.adoc, features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitor.java, features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/PageSequenceMonitorIT.java, opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/pagesequence/Page.java, opennms-config-jaxb/src/main/resources/xsds/page-sequence.xsd
When authentication is required, the first HTTP request receives a "401 Unauthorized" response with possible authentication methods. The second request is sent using the selected authentication method.
Using the `preselect-auth` attribute allows you to use a specific authentication right on the first request.
Some servers do not tell you which authentication methods are supported. In these cases, using the `preselect-auth` attribute is the only option.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15802
=> nms-15802 Add preselect auth to page in page sequence

opennms-webapp/src/main/webapp/account/selfService/passwordGate.jsp, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/AdminPasswordGateIT.java
Smoke test for the Admin Password Gate functionality.
Put several tests within the same test method, otherwise there are issues when the `AbstractOpenNMSSeleniumHelper TestWatcher Rule` runs.
Tests:
- logging in as "admin/admin", then getting the Password Change gate.
- skipping the gate, changing password to something else
- logout/login with new password
- resetting the password back to the standard admin password using the Rest API
- logout, then attempting to go to node page, being redirected to login then passwordGate, clicking Skip, then being redirected to node page
Had to make various changes in `AbstractOpenNMSSeleniumHelper` to be able to pass in custom credentials, clicking Skip button, etc. as well as some refactoring. Adding some debug log messages to make it a bit easier to …
=> NMS-15866: Smoke test for admin password gate

features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java, opennms-webapp/src/main/java/org/opennms/web/account/selfService/AbstractBasePasswordChangeActionServlet.java, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/AdminPasswordGateIT.java
Follow-up to NMS-15866, adding `@SuppressWarnings` to suppress Sonar alerts for variables containing the word `password` in code having to do with Admin Password Gate functionality and smoke tests.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15866
=> NMS-15866: Add SuppressWarnings to suppress Sonar 'password' alerts

opennms-base-assembly/src/main/filtered/bin/opennms, opennms-container/horizon/container-fs/entrypoint.sh, opennms-container/minion/container-fs/entrypoint.sh, opennms-container/sentinel/assets/entrypoint.sh
See [the release notes for JDK 11.0.20](https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html) for details.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16034
=> NMS-16034: fix validation triggered by karaf jar(s) in newer JDKs

docs/modules/operation/pages/deep-dive/performance-data-collection/collectd/collection-packages.adoc, docs/modules/operation/pages/deep-dive/retention.adoc, docs/modules/operation/pages/deep-dive/service-assurance/polling-packages.adoc
Consolidate RRD text across poller and collect configs by reusing the same text on both.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16033
=> NMS-16033: Update docs on default RRD

opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml, ui/package.json, ui/src/components/Device/DCBTable.vue, ui/src/components/Nodes/NodeHierarchyPanel.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/containers/NodeDetails.vue, ui/src/containers/Nodes.vue, ui/src/router/index.ts, ui/src/services/categoryService.ts, ui/src/services/index.ts, ui/src/services/monitoringLocationService.ts, ui/src/store/hierarchy/actions.ts, ui/src/store/hierarchy/index.ts, ui/src/store/hierarchy/mutations.ts, ui/src/store/hierarchy/state.ts, ui/src/store/index.ts, ui/src/types/index.ts
Create initial Structured/Hierarchical Node page, for applying various hierarchical filters to a node list.
This is targeting an epic feature branch. Will put up another PR for merge to `develop` when this feature is more complete.
This task is for an initial page, additional features will be added in subsequent tasks.
- Revive the Vue Node List page
- Add to menubar as "Nodes (Preview)"
- Point node links to legacy node details page
- Add node hierarchy/filter panel
- Include Categories, Flows, Locations as initial items to filter on
- All selections within a section are "or"/unions for now
- Expansion / Accordion style components to select items, display count and allow clearing
- Node list will be filtered on hierarchy items as well as Node Label search 
Known issues to be fixed in …
=> NMS-16037: Initial Structured/Hierarchical Node page

docs/modules/operation/pages/deep-dive/provisioning/policies.adoc, docs/modules/reference/pages/provisioning/policies/metadata.adoc, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultPluginRegistry.java
This PR makes a minor change to the provisiond logging to eliminate a confusing debug model. It also updates the documentation to clarify the types of policies and where they apply.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16031
=> NMS-16031: improve provisiond logging and clarify docs

core/test-api/xml/src/main/java/org/opennms/core/test/xml/XmlTest.java, core/xml/src/main/java/org/opennms/core/xml/JaxbUtils.java
This PR backports a number of small improvements to JAXB handling to foundation 2019.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16089
=> NMS-16089: backport JAXB updates to foundation-2019

container/shared/src/main/resources/etc/container.init
Set the minimum and maximum JDK version to the same range as in Horizon Core.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16090
=> NMS-16090: fix min and max java version

docs/modules/reference/pages/configuration/core-docker.adoc, opennms-container/core/container-fs/confd/templates/newts.properties.tpl
additional property in core docker container to allow cassanrda setting of lab name
changes to tpl and adoc file to match.
See also issue in stack play https://github.com/opennms-forge/stack-play/issues/25
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16025
* https://github.com/opennms-forge/stack-play/issues/25
=> NMS-16025: modified tpl and adoc for issue

docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
The documentation regarging configuration of horizon to use newts states: Configure Horizon to Use Newts 
(Optional) If your Horizon data collection or polling intervals have been modified, set the query minimum and heartbeat rates:
org.opennms.newts.query.minimum_step=30000 
org.opennms.newts.query.heartbeat=45000 
The shortest collection interval configured for any collectable or pollable service, in milliseconds (in this case, 30 seconds).The communication interval for the Newts service, in milliseconds. Should be set to 1.5 times the minimum_step value.
This might create problems in cases where different polling intervals have been set for different services. For e.g. ICMP has polling every 60seconds while SNMP has polling set to every 300seconds(5 minutes). Following the …
=> NMS-16077: Clarify newts polling interval configuration

docs/modules/operation/pages/deep-dive/device-config-backup/dcb-accounts/aruba-os.adoc, docs/modules/operation/pages/deep-dive/device-config-backup/dcb-accounts/aruba-oscx.adoc, docs/modules/operation/pages/deep-dive/device-config-backup/dcb-accounts/cisco-ios.adoc, docs/modules/operation/pages/deep-dive/device-config-backup/dcb-accounts/juniper.adoc, docs/modules/operation/pages/deep-dive/device-config-backup/ssh.adoc, docs/modules/reference/pages/configuration/minion-confd/minion-confd.adoc
=> DP-3: Horizon/Meridian: Add tabbed block to Configure Backup Sprint

pom.xml
Backport of Jasper upgrade that went into H32
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16105
=> build(deps): bump jasperreports from 6.3.0 to 6.20.0

ui/src/components/Device/DCBGroupFilters.vue, ui/src/components/Nodes/ColumnSelectDropdown.vue, ui/src/components/Nodes/FlowTooltipCell.vue, ui/src/components/Nodes/NodeActionsDropdown.vue, ui/src/components/Nodes/NodeDetailsDialog.vue, ui/src/components/Nodes/NodeStructurePanel.vue, ui/src/components/Nodes/NodeTooltipCell.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/components/Nodes/utils.ts, ui/src/containers/Nodes.vue, ui/src/lib/utils.ts, ui/src/main.ts, ui/src/store/nodeStructure/actions.ts, ui/src/store/nodeStructure/mutations.ts, ui/src/store/nodeStructure/state.ts, ui/src/types/index.ts
NMS-16103: Node Structure UX improvements, selectable columns
- horizontal table scroll, highlight on mouseover
- added "Filtering" and "Metadata Search" headings
- dropdown to select which columns to display, and a button to reset them to the default
- start of support for ordering columns, will do rest in subsequent task
- refactored some functionality into smaller Vue components
- vertical ellipse menu for node actions (links to other pages, etc.)
- node details dialog, will add more in subsequent tasks
- using buttons instead of radio group for "Any / All" switch
- add metadata search autocomplete, even though it's non-functional for now (want this in to get UX feedback)
- truncate long text and provide tooltip
- flows icons
- title and move Search input to right
There's enough …
=> NMS-16103: Node structure UI updates, selectable columns

container/features/pom.xml, container/features/src/main/resources/features.xml
This PR cleans up the feature dependencies of `opennms-alarm-history-elastic` so it should load properly without needing to manually load other features.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16070
=> NMS-16070: update dependencies and validate the alarm history feature

ui/src/components/Nodes/ColumnSelectionPanel.vue, ui/src/components/Nodes/NodePreferencesDialog.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/containers/Nodes.vue, ui/src/services/localStorageService.ts, ui/src/stores/nodeStructureStore.ts, ui/src/types/index.ts
On the Node Structure page, add a "Save and Close" button in the Preferences dialog to save all column and filter preferences to browser local storage. When the page loads, it will attempt to load any existing preferences.
This will save preferences if browser is closed and reopened, but of course the won't be saved if the user moves to a different browser or machine, and doesn't distinguish between different users in same machine user session. If needed, we can use Config Management / CM.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16130
=> NMS-16130: Save node preferences to local storage

smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/AdminPasswordGateIT.java
[NMS-14078](https://opennms.atlassian.net/browse/NMS-14078) / [PR 6659](https://github.com/OpenNMS/opennms/pull/6659) introduced some changes that caused the `AdminPasswordGateIT` smoke test to fail. These partly have to do with the smoke test being somewhat contrived.
- removing cookies resulted in Rest API call to reset admin password to fail with a `401 Forbidden`
- issues when logged out, then navigating to a different page than the login page, logging in, then should be redirected back to original page
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14078
[NMS-14078]: https://opennms.atlassian.net/browse/NMS-14078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NMS-14078: Fix AdminPasswordGateIT smoke test

ui/src/components/Nodes/ManagementIPTooltipCell.vue, ui/src/components/Nodes/NodeDetailsDialog.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/components/Nodes/utils.ts, ui/src/services/index.ts, ui/src/services/ipInterfaceService.ts, ui/src/stores/nodeStore.ts, ui/src/stores/nodeStructureStore.ts
Add the management IP address, or at least the "best" IP address, to the node table.
Any time the node query changes (sorting, filters, search), we also launch an IP Address query for the returned nodes and update a map.
For each node, we try to use the IP interface where snmpPrimary is 'P', or else at least isManaged, or else the first or onlly IP. Tooltip displays managed and SNMP Primary status, clicking on link brings you to the 'classic' IP Interface page.
Currently cannot sort by IP Address, but you can configure whether it displays and in which column order. Also displays in the Node Details dialog, and it has a link to the legacy IP Interface page.
Updated default pagination to 20 nodes per page.
Updated Search to have an implicit start and end wildcard, e.g. typing `host` will do …
=> NMS-16126: Node structure, add management IP or best IP address

pom.xml
latest kotlin standard library, used by some dependencies
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16172
=> NMS-16172: bump to kotlin 1.9.10

pom.xml
the 3.x series is backwards-compatible with 2.x, bump to latest 3.x
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16173
=> NMS-16173: bump okio to 3.6.0

pom.xml
5.15.9 is the last version compatible with our Camel version.  We needed to be on 5.15.8 or higher to deal with CVE-2018-11775 and CVE-2019-0222.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15062
=> NMS-15062: update ActiveMQ to 5.15.9

docs/modules/deployment/pages/minion/docker/minion.adoc
Add flag to delete the temporary container used for creating the keystore.  Without this, extra containers are left behind on the system for the user to cleanup later.
=> Minion docker doc install update

opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/TileProviderItem.java, opennms-webapp/src/main/webapp/WEB-INF/web.xml, ui/src/components/Map/LeafletMap.vue, ui/src/types/mainMenu.d.ts
Allow multiple "tile providers" to be configured in the Vue Geographical Map, so users can add their own, for example if they have a local/private map server.
There are 2 hard-coded ones in the Vue code. An additional one can be configured in `opennms/etc/opennms.properties` under the `gwt.openlayers.url` and `gwt.openlayers.options.attribution` properties.
The additional provider, if configured, is included in the Menu Rest API, `userTileProviders` array. It will display in the tile layer dropdown. Currently name is hard-coded to `User-Defined`.
Will open a separate Documentation ticket as any added tile provider needs to be added to `web.xml` `Content-Security-Policy` `img-src` section, or else it will be blocked by the browser.
Also added the Open TopoMap `opentopomap.org` URL to CSP, …
=> NMS-15400: Allow multiple tile providers in Geographical Map

container/features/src/main/resources/features.xml, dependencies/hibernate/pom.xml
This PR enables the use of a patched Hibernate that includes [a few extra changes on top of the last Hibernate 3.x release](https://github.com/hibernate/hibernate-orm/compare/3.6.10.Final...opennms-forge:hibernate-orm:3.6).
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16181
=> NMS-16181: use patched Hibernate 3.6

container/features/src/main/resources/features.xml, dependencies/hibernate/pom.xml, pom.xml
This PR backports my Hibernate patch to `foundation-2020`, it also includes an additional change to make it easier to manage Hibernate dependencies across Maven and OSGi.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16181
=> NMS-16181: backport Hibernate fixes to 2020

opennms-container/minion/Dockerfile
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16212
=> NMS-16212: Create missing prom-jmx-exporter folder in Minion container

docs/modules/operation/pages/deep-dive/alarms/history.adoc
Include the Elastic Alarm History content within the Alarms section. This used to be a placeholder page that linked to the other section, and this change embeds the content so it shows up in both pages and is kept in sync with future changes.
=> Docs: Include ES alarm history under alarms

ui/src/components/Nodes/ExtendedSearchPanel.vue, ui/src/components/Nodes/NodeDetailsDialog.vue, ui/src/components/Nodes/NodeStructurePanel.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/components/Nodes/hooks/queryStringParser.ts, ui/src/components/Nodes/hooks/useNodeQuery.ts, ui/src/lib/utils.ts, ui/src/stores/nodeStructureStore.ts, ui/src/types/index.ts
Node structure panel, add search types for foreign source and id as well as "system" attributes (`sysContact`, `sysLocation`, etc.). Needed to refactor a bit to clean this up.
'system' attributes use a wildcard search. SNMP and foreign source/id attributes are exact search (due to current Rest API implementation).
Used the Feather `SwitchRender` control for Match Any / Match All for Category searches.
Added more fields to the Node Info dialog.
This is probably the last set of features for the Node Structure page for the upcoming Horizon 33 release.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16197
=> NMS-16197: Node structure, more search types, fix switch

.circleci/main/jobs/build/build-ui.yml
CircleCI `build-ui` keeps failing due to not having `node-gyp` installed, I believe it's needed for `yarn install`. This ensures that it is already installed in the build environment.
Error message in NMS ticket.
There could be a different or better way to do this, but this does work.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16242
=> NMS-16242: Install node-gyp for CircleCI build-ui

opennms-base-assembly/src/main/filtered/etc/opennms.properties, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/TileProviderItem.java, ui/src/components/Map/LeafletMap.vue, ui/src/types/mainMenu.d.ts
Previously, a user-defined geographical map tile provider was added to the end of the list of providers. So for example if a user did not want to use an Internet-based tile provider, the GeoMap page would still try to load the default `OpenStreetMap` provider tiles.
This allows setting the user-defined one as the default, which will appear first in the tile provider radio button selector, and will load by default. Also allows a name to be specified.
Configure in `etc/opennms.properties`:
```
gwt.openlayers.name=My Street Map
gwt.openlayers.url=http://192.168.0.99/{z}/{x}/{y}.png
gwt.openlayers.options.attribution=Map data &copy; <a tabindex="-1" target="_blank" href="http://192.168.0.99/copyright">My Street Map</a> contributors under <a tabindex="-1" target="_blank" …
```
=> NMS-16229: Enable setting user-defined GeoMap tile provider as default

ui/src/components/Nodes/NodesTable.vue
Previous updates resulted in breaking sorting on the Structured Node List page, the `orderBy` and `order` `QueryParameters` were being lost.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16246
=> NMS-16246: Structured node list, fix sorting

opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml, smoke-test/src/test/java/org/opennms/smoketest/ui/StructuredNodeListIT.java, ui/src/containers/Nodes.vue
A smoke test for the Structured Node List.
Navigates to the page and clicks on a node, ensures navigates to the node details page.
Also changes the menu to read "Structured Node List" instead of "Nodes (Preview)", and fixes the breadcrumb.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16061
=> NMS-16061: Structured Node List smoke test

core/upgrade/src/main/java/org/opennms/upgrade/api/OnmsUpgrade.java, core/upgrade/src/main/java/org/opennms/upgrade/implementations/ClearKarafCacheMigratorOffline.java, core/upgrade/src/main/java/org/opennms/upgrade/support/Upgrade.java, core/upgrade/src/test/java/org/opennms/upgrade/implementations/ClearKarafCacheMigratorOfflineIT.java, core/upgrade/src/test/java/org/opennms/upgrade/support/UpgradeTest.java, core/upgrade/src/test/java/org/opennms/upgrade/tests/TestUpgradeEverytime.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16226
The deletion of the files in the data directory is realized by an OnmsUpgrade task since in the script itself there is no chance to decide whether an upgrade is run or just help is displayed.
=> NMS-16226: Clear Karaf's data directory on upgrade

opennms-base-assembly/src/main/filtered/etc/opennms.properties, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeed.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeedItem.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeedProvider.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/xml/NewsFeedXml.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/xml/package-info.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NewsFeedRestService.java, opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml, opennms-webapp/src/main/java/org/opennms/web/controller/newsfeed/NewsFeedController.java, opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml, opennms-webapp/src/main/webapp/WEB-INF/jsp/newsfeed/newsFeedPanel.jsp, opennms-webapp/src/main/webapp/index.jsp
Adding News Feed UI and Rest service.
This displays a News Feed panel on the OpenNMS front page with data taken from the OpenNMS RSS feed at https://www.opennms.com/feed/.
Due to CORS and other issues, we implemented this with an OpenNMS Rest service which queries the RSS feed and does some additional processing. The UI calls this Rest service instead of directly requesting from opennms.com.
Two configuration points are available in `etc/opennms.properties`:
- `opennms.newsFeedPanel.show`: controls whether the News Feed panel is displayed. If commented-out, lef unset, or set to `true`, the panel will display. Set it to `false` to suppress display, which also suppresses making the server-side call to the RSS feed
- `opennms.newsFeedPanel.url`: Should normally be commented-out, but allows …
=> NMS-16282: News Feed UI and Rest service

features/events/api/src/main/java/org/opennms/netmgt/events/api/LegacyDatetimeFormatter.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16288
=> NMS-16288: LegacyDatetimeFormatterTest.testParse fails to parse date time when locale is set to `en_CA-UTF-8`

container/karaf/src/main/filtered-resources/etc/overrides.properties, container/shared/src/main/filtered-resources/etc/overrides.properties, features/jest/dependencies/pom.xml, features/jest/feature/pom.xml, opennms-base-assembly/pom.xml, opennms-webapp/pom.xml, pom.xml
This PR makes all apache commons packages use a top-level versioned entry in dependency management, and also updates the Karaf container(s) to use an override file that enforces using that version (or newer) in the OSGi side as well.
=> normalize all Apache Commons usage

container/features/src/main/resources/features.xml, container/karaf/src/main/filtered-resources/etc/custom.properties, dependencies/spring-security/pom.xml, pom.xml
this doesn't directly address keycloak integration, but does at least provide the APIs to try playing with them against an actual openid instance
=> NMS-9677: add spring security openid dependencies

pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16303
=> NMS-16303: bump json-smart to 2.5.0

features/config/upgrade/src/main/resources/changelog-cm/33.0.0/changelog-cm.xml, features/config/upgrade/src/main/resources/changelog-cm/changelog-cm.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/StateManager.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UserDataCollectionStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java
User Data Collection updates to Configuration Management including the liquibase schema update. Added REST endpoint for getting and changing status of whether someone acknowledged the UI notice and opted in or out.
Note, we are only keeping track of whichever user acknowledged the notice first.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16284
=> NMS-16284: User Data Collection CM, liquibase, Rest updates

container/features/src/main/resources/features.xml, features/alarms/history/elastic/pom.xml, features/flows/api/pom.xml, features/flows/elastic/pom.xml, features/jest/client/pom.xml, features/jest/feature/pom.xml, features/jest/jest-complete-osgi/pom.xml, features/opennms-es-rest/pom.xml, features/situation-feedback/elastic/pom.xml
We're getting some build failures off and on related to maven not finding the right version of things, and I think it's related to our funky custom package that acts like it's owned by the jest project but isn't.
This cleans it up to make `jest-complete-osgi` a normal OpenNMS module which provides the correct OSGi metadata to load as if it were the other bundle.
=> stop publishing our own weird jest version

opennms-container/minion/container-fs/confd/templates/disable-jms.boot.tmpl
Address an issue where configuring Kafka RPC and SINK does not fully disable the JMS IPC for Active MQ, preventing the Minion from passing a health-check.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16311
=> NMS-16311: Minion confd kafka

pom.xml
This PR bumps Zookeeper to the newest 3.7.x. 3.8 causes a deadlock in the tests, but 3.7.2 has no known CVEs open against it so it should be good enough for now.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16302
=> NMS-16302: bump zookeeper to latest 3.7.x

features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsMetadataDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionFormData.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionServiceImpl.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionStatusDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionSubmissionClient.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/userdatacollection/UserDataCollectionSubmissionData.java, features/datachoices/src/main/java/org/opennms/features/datachoices/shell/internal/DisplayUsageReportCommand.java, features/datachoices/src/main/java/org/opennms/features/datachoices/shell/internal/SendUsageReportCommand.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/DataChoiceRestService.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/DataChoiceRestServiceImpl.java, features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/ModalInjector.java, features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/datachoices/src/main/resources/web/user-data-collection.ftl.html, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java, opennms-base-assembly/src/main/filtered/etc/opennms.properties
User Data Collection: UI, REST API and CRM integration.
Displays a dialog the first time any user logs in to request some user data and send it to a CRM endpoint. User can opt-out. Notice is only displayed once.
Workflow:
- Configuration Management check done to see if notice had been previously acknowledged, only display if not
- User can opt-in or opt-out
- Either opt-in or opt-out is recorded in the CM database via a REST POST to `rest/datachoices/userdatacollection/status`
- Opt-in results in a submission to `stats.opennms.org/datachoices/user-data-collection`. Then, the `usage-stats-handler` app makes a server-side call to the CRM
This can be disabled by setting `opennms.userDataCollection.show=false` in `etc/opennms.properties`.
> **NOTE:** For this PR, this feature is disabled by …
=> NMS-16283: User Data Collection UI and API

features/datachoices/src/main/java/org/opennms/features/datachoices/web/internal/UserDataCollectionAdminPageNavEntry.java, features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/datachoices/src/main/resources/web/user-data-collection.ftl.html, opennms-webapp/src/main/webapp/admin/user-data-collection/index.jsp, smoke-test/src/test/java/org/opennms/smoketest/AdminPageIT.java
Add a link on the Admin page to a User Data Collection page which allows user to re-enable the signup dialog, even if they initially opted-out. Would also allow other users besides the initial one to sign up.
Sign up dialog also contains a link to go to this page.
UDC Admin Page:
Link on Admin page:
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16326
=> NMS-16326: User Data Collection page to re-enable the signup dialog

opennms-container/common.mk, opennms-container/core/Dockerfile, opennms-container/minion/Dockerfile, opennms-container/sentinel/Dockerfile, smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
this change bumps the deploy base to the latest version, which refactors a few things so that we can fix the poweredby capability flag on JDK upgrade
=> bump deploy base to 3.3.0.b253

docs/modules/deployment/pages/time-series-storage/newts/configuration.adoc, docs/modules/reference/pages/configuration/core-docker.adoc
v32 added the `datacenter` property to Newts, but the docs weren't updated to reference this properly.  And NMS-16346 pointed out there was a misspelling on the Newts hostname setting for confd.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16346
=> NMS-16346 Update docs for Newts configs

.circleci/main/executors.yml, .circleci/main/jobs/code-coverage.yml, .circleci/scripts/sonar.sh
JDK11 support was sunsetted Feb 2024 by Sonar upstream.
This PR bumps to the latest Sonar CLI, makes a few memory changes, and turns on verbose GC so that we get enough log output during scanning that it doesn't fail out.
=> fix code coverage to run under JDK17

integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java, integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionTool.java, integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlConnection.java, integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java, integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/NMS16320Test.java, integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionUrlTest.java, opennms-base-assembly/src/main/filtered/bin/vmwarecimquery, opennms-base-assembly/src/main/filtered/bin/vmwarereqtool, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ImportJob.java, opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ImportJobFactory.java, opennms-provision/opennms-requisition-service/src/main/java/org/opennms/netmgt/provision/persist/rpc/RequisitionRequestBuilderImpl.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16320
* VMware requisition is now location-aware when triggered by UI and not only when triggered by Karaf shell
* Meta-data interpolation is done at the correct time
* Fixed VMware tools in bin
=> NMS-16320: Fixed requisition handling

docs/modules/operation/pages/deep-dive/kafka-producer/configure-kafka.adoc, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersister.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersisterActivator.java, features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersisterFactory.java, features/kafka/producer/src/main/resources/OSGI-INF/blueprint/blueprint-kafka-producer.xml, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java, features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaMetricsMaxSizeIT.java
Provide an option to disable splitting of metric messages while forwarding to kafka
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16366
=> NMS-16366: Provide an option to disable splitting of metric messages

opennms-container/common.mk, opennms-container/core/Dockerfile, opennms-container/minion/Dockerfile, opennms-container/sentinel/Dockerfile, smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
We are not actually vulnerable to the liblzma issue but I'm taking this opportunity to make sure our images are up-to-date before release next week.
=> NMS-16396: update to latest docker deploy base

opennms-base-assembly/src/main/filtered/bin/update-package-permissions
Because the step that changes file ownership keys off of the RUNAS variable, it does not make sense to bail out when RUNAS does not equal `opennms` and it can leave the installation in an inconsistent state.
Modify the message printed to indicate that file ownership will be changed to the RUNAS user, and do not exit immediately.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16406
=> NMS-16406: Allow update-package-permissions to set ownership for customized users.

core/upgrade/src/main/java/org/opennms/upgrade/implementations/EOLServiceConfigMigratorOffline.java, core/upgrade/src/test/java/org/opennms/upgrade/implementations/EOLServiceConfigMigratorOfflineTest.java
Here we refactor the offline migrator to reuse the list of end of life services instead of re-defining them.
=> chg: re-use eol services

opennms-base-assembly/pom.xml, smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
We are using `plugingRepository` to override `jaspersoft-third-party` location in `opennms-base-assembly/pom.xml` file.
I have opened [NMS-16460](https://opennms.atlassian.net/browse/NMS-16460) to track the test case failure.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16459
[NMS-16460]: https://opennms.atlassian.net/browse/NMS-16460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> NMS-16459: Builds failing due to iText artifacts is not accessible

.circleci/main/executors.yml, pom.xml, ui/README.md, ui/package.json
Update UI to use Node 18 as it's needed by some dependencies, and we're overdue to upgrade it.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16462
=> NMS-16462: Upgrade UI to Node 18

features/springframework-security/pom.xml, features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSLoginUrlAuthEntryPoint.java, features/springframework-security/src/test/java/org/opennms/web/springframework/security/NMS16450Test.java
Normally this Host Header injection can be avoided by specifying the property opennms.web.base-url. Unfortunately, this doesn’t seem to work before login for the given page. I altered the code to also use the Util.calculateUrlBase()-method to construct the urls at this point.
* JIRA: https://opennms.atlassian.net/browse/NMS-16450
=> NMS-16450: Also use Util.calculateUrlBase() before login

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpStrategy.java, core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java, core/snmp/api/src/main/java/org/opennms/netmgt/snmp/proxy/LocationAwareSnmpClient.java, core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpStrategy.java, core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategy.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JAgentConfig.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/AbstractSNMPRequestBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/LocationAwareSnmpClientRpcImpl.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPMultiGetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSingleGetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPWalkBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPWalkWithTrackerBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpRequestDTO.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpSetRequestDTO.java, core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/MockSnmpStrategy.java, features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaCollectorIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/AbstractSnmpCollectorIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorMinMaxValIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpSetIT.java
This is part of
* JIRA: https://opennms.atlassian.net/browse/NMS-16388
Allows to invoke SNMP SET via LocationAwareSnmpClient. Since LocationAwareSnmpClient only works with Snmp4j, so I did not changed anything regarding JoeSnmp. I also altered the way the SNMP community is used in case of v1/v2c. If a SET PDU is sent the write community will be used, otherwise the read community.
=> NMS-16388: Allow set to be invoked via LocationAwareSnmpClient

core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpStrategy.java, core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java, core/snmp/api/src/main/java/org/opennms/netmgt/snmp/proxy/LocationAwareSnmpClient.java, core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpStrategy.java, core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpStrategy.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JAgentConfig.java, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/AbstractSNMPRequestBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/LocationAwareSnmpClientRpcImpl.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPMultiGetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSingleGetBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPWalkBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPWalkWithTrackerBuilder.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpRequestDTO.java, core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpSetRequestDTO.java, core/snmp/proxy-rpc-tests/src/test/java/org/opennms/netmgt/snmp/proxy/common/MockSnmpStrategy.java, features/juniper-tca-collector/src/test/java/org/opennms/netmgt/collectd/tca/TcaCollectorIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/AbstractSnmpCollectorIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpCollectorMinMaxValIT.java, opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpSetIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16489
=> NMS-16489: Backport of NMS-16388

container/features/src/main/resources/features.xml, dependencies/netty/pom.xml, features/collection/persistence-tcp/src/test/java/org/opennms/netmgt/collection/persistence/tcp/TcpOutputStrategyTest.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/AsyncLineOrientedDetectorNettyImpl.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/AsyncMultilineDetectorNettyImpl.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/LineOrientedRequestEncoder.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/LineOrientedResponseDecoder.java, opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/MultilineOrientedResponseDecoder.java, opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/AsyncBasicDetectorNettyImpl.java, opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/DetectFutureNettyImpl.java, opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/DetectorHandlerNettyImpl.java, opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/TcpDetectorHandlerNettyImpl.java, protocols/selenium-monitor/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16496
=> NMS-16496: Backport NMS-16184 to foundation-2023

opennms-webapp/src/main/webapp/account/selfService/passwordGate.jsp
The Password Gate in Meridian had incorrect, Horizon-specific values for some images and text colors. This was fixed in NMS-16484. This is to apply similar change in Horizon so that the code is the same except for the changed values in constants.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16508
=> NMS-16508: Password gate display fix to track change made in Meridian

opennms-full-assembly/src/assembly/components/osgi.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16513
=> NMS-16513: Added missing exclusion rule for jettison

opennms-services/src/main/java/org/opennms/netmgt/scriptd/Executor.java, opennms-services/src/main/java/org/opennms/netmgt/scriptd/Scriptd.java
Since [NMS-13216](https://opennms.atlassian.net/browse/NMS-13216), the logic to handle `reloadDaemonConfig` events in Scriptd has been broken.  In attempting to fix it, I also realized that Scriptd's previous behavior was also broken in that it would not refresh scripts referenced in the config that had been modified on `reloadDaemonConfig`.  Restore the previous handling of the `reloadDaemonConfig` event, and change Scriptd destroy and re-register the defined BSF engines entirely, which causes Scriptd to re-read and re-source all referenced scripts. 
1. update the title of this PR to be in the format: `${JIRA-ISSUE-NUMBER}: subject of pull …
=> NMS-16518: Fix scriptd's broken reloadDaemonConfig handling

container/features/src/main/resources/features.xml
Should fix CircleCI Sentinel smoke test errors for develop.
=> NMS-15169: Added jackson-dataformat-yaml to opennms-health-rest-service feature

docs/modules/development/pages/rest/ifservices.adoc
=> Fix doc:  -d needs to be added for cUrl to function adequately

.github/workflows/auto-assign.yml
Node 12 in 1.1.4 is deprecated and the auto-assign-reviewer action uses Node 16 with version 1.1.5.
See: https://github.com/shufo/auto-assign-reviewer-by-files/releases/tag/v1.1.5
=> chore: Update auto-assign-reviewer to use Node 16 instead of Node 12

opennms-container/common.mk, opennms-container/core/Dockerfile, opennms-container/minion/Dockerfile, opennms-container/sentinel/Dockerfile, smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
Updating the container's base image to UBI 9.4
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16587
=> NMS-16587: Update linux UBI version to 9.4

features/events/daemon/src/main/java/org/opennms/netmgt/eventd/listener/TcpListener.java
Fix the logging class to TcpListener instead of UdpListener.
I've backported the patch to fix Meridian 2022 onwards.
JIRA: https://opennms.atlassian.net/browse/NMS-16951
=> NMS-16951: Set logging to matching class TcpListener

opennms-container/core/plugins.sh, opennms-container/sentinel/Dockerfile
=> NMS-16576: Stop including ALEC in containers

opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/wsman-microsoft-windows-virtmem.properties
Add corrected graph as a new file and suppress the incorrect graph to avoid creating an rpmnew on upgrades
See https://github.com/OpenNMS/opennms/pull/7110 for previous version of this PR.
* **If this code is likely to affect the …
=> NMS-16953: Correct the WinRM Virtual Memory graph

opennms-webapp/src/main/java/org/opennms/web/controller/admin/support/FormatterView.java, smoke-test/pom.xml, smoke-test/src/test/java/org/opennms/smoketest/SystemReportPageIT.java
* NMS-16983 : Fixed issue.
* NMS-16986 : Initial data required by Technical Support [ci skip].
* Revert "NMS-16986 : Initial data required by Technical Support [ci skip]."
This reverts commit 1534f8f0d2af2b653317d9eb23aee42e409f4b24.
* NMS-16983 : File name field in System Reports is not working.
* NMS-16983: File name Fix.
* NMS-16983: File name Fix.
* NMS-16983: File name Fix.
* NMS-16983: File name Fix.
* NMS-16983: Test Fix added.
* NMS-16983: Fixed PR Comments.
2. update the Jira link at the bottom of this comment to refer to the real …
=> NMS-16983 : File name field in System Reports is not working. (#7563)

features/poller/api/pom.xml, features/poller/api/src/main/java/org/opennms/netmgt/poller/DeviceConfig.java, features/poller/api/src/main/java/org/opennms/netmgt/poller/EscapeSequenceAdapter.java, features/poller/api/src/test/java/org/opennms/netmgt/poller/DeviceConfigTest.java, features/poller/api/src/test/java/org/opennms/netmgt/poller/EscapeSequenceAdapterTest.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15717
=> NMS-15717: DeviceConfig via Minion fails if sshScript output contains control characters.

opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/support/systemReportList.jsp, smoke-test/src/test/java/org/opennms/smoketest/SupportPageIT.java
Update existing system report functionality under (Admin->Support->System Report).
There should be two groups for text file reports and Log files at the front end page.
Text File Report group should have following options with checkboxes.
Java: Java and JVM information
OS: Kernel, OS, and Distribution
OpenNMS: OpenNMS core information, version, and basic configuration
TopEvent: Top 20 most reported events
Log Files  group should have following information with radio button options.
Configuration: Append all OpenNMS configuration files (full output only)
Logs: OpenNMS log files (full output only)
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17002
=> FE: NMS-17002: System Check Utility : Grouping of System Report at front end.

ui/src/components/UsageStatistics/UsageStatisticsTable.vue, ui/src/containers/OpenAPI.vue
A new item, “CSV output of Login events for the past 60 days”, has been added to the usage stats list.
The “Latest Value” column will contain Base64-encoded file contents.
Update the column to display a download link labeled “Download CSV file”. The link should decode the Base64 content and trigger the file download.
The implementation should be generic, based on the datatype value (file|csv) provided in the metadata.
If the datatype starts with "file", split it using | to extract the file type (e.g., csv in this case) and handle the file appropriately.
Metadata:
{
"key": "loginsPast60Days",
"name": "CSV output of Login events for the past 60 days",
"description": "CSV output containing the date, username login events for the past 60 days",
"datatype": "file|csv"
}
* Jira (Issue Tracker): …
=> FE: NMS-17004: Update the login events item in Usage Stats, add link to download CSV file

opennms-container/minion/container-fs/entrypoint.sh
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17007
This is the same PR as #7588 but based off the `foundation-2024` branch
@indigo423 apologies for the mess about, if you could sign this one off again please?
=> NMS-17007: Handle if CA cert with alias already exists for Minion

features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapListener.java
Fixed some typos in the SNMP Trap listener I've spotted during troubleshooting SNMP Trapd.
=> fix: Fix typos in the log output in the SNMP Trap Listener

features/graph/jung/pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17073
=> NMS-17073: Add missing guava dependency in jung shaded

opennms-container/minion/container-fs/entrypoint.sh
Allow user to set the Java initial and maximum heap size with the [documented JAVA_MIN_MEM and JAVA_MAX_MEM](https://docs.opennms.com/horizon/32/deployment/minion/install.html#install-the-minion-package) environment variables in the docker-compose example.
There was no default set. I have set the initial and maximum heap space to 2 GB by default. It might be too high/low.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17726
=> NMS-17726: Allow user to set min and max Java heap size

features/datachoices/pom.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java, features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/datachoices/src/main/resources/web/datachoicesMetadata.json, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTOTest.java, smoke-test/src/test/java/org/opennms/smoketest/UsageStatisticsIT.java
- jira : [https://opennms.atlassian.net/browse/NMS-17082](https://opennms.atlassian.net/browse/NMS-17082)
=> NMS-17082 : Add Number of Flows per Second (Last 24 Hours) to Usage Stats

container/features/src/main/resources/features.xml, features/datachoices/pom.xml, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java, features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/system-report/pom.xml, pom.xml
The OSHI library (com.github.oshi) which we are using in datachoicesis currently on version 6.7.0, we are on 6.2.2. They added some things for Mac Sequoia among other things, we should probably update.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17737
=> NMS-17737  Update OSHI library to 6.7.1

opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/menu/MenuProviderTest.java, opennms-webapp/src/main/java/org/opennms/web/navigate/LocationBasedNavBarEntry.java
Update the `LocationBasedNavBarEntry` mechanism to not display the menu item at all if a system property check fails.
This means that the "Zenith Connect" menu entry should not appear in the legacy menu unless the feature has been enabled in the properties file.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17766
=> NMS-17766: Do not display menu item if property check fails

core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Controller.java, core/daemon/src/test/java/org/opennms/netmgt/vmmgr/ControllerTest.java, opennms-base-assembly/src/main/filtered/etc/opennms.properties
upgraded OpenNMS i from 33.1.3 to 33.1.4 and data collected in victoria metrics (via the Cortex Time Series plugin) stopped including the additional metatags that  had configured. Reverting to 33.1.3 immediately adds them back to collected data.
the config  in  ${OPENNMS_HOME}/etc/opennms.properties.d/timeseries.properties file that looks like this:
`org.opennms.timeseries.strategy=integration
org.opennms.timeseries.tin.metatags.tag.node=${node:label}
org.opennms.timeseries.tin.metatags.tag.location=${node:location}
org.opennms.timeseries.tin.metatags.tag.ifDescr=${interface:if-description}
org.opennms.timeseries.tin.metatags.tag.ifAlias=${interface:if-alias}
org.opennms.timeseries.tin.metatags.tag.ifName=${interface:if-name}
org.opennms.timeseries.tin.metatags.tag.ipAddress=${interface:ad …
=> NMS-17753  Coretex timeseries metatags broken in 33.1.4

docs/modules/development/nav.adoc, docs/modules/development/pages/rest/monitoring_systems.adoc, features/bsm/rest/impl/src/test/java/org/opennms/web/rest/v2/bsm/AbstractBusinessServiceRestServiceIT.java, features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/BusinessServiceManagerImplIT.java, features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineIT.java, features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/BsmDatabasePopulator.java, opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoringSystemDao.java, opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockMonitoringSystemDao.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/DatabasePopulator.java, opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/MonitoringSystemDaoHibernate.java, opennms-dao/src/main/resources/META-INF/opennms/applicationContext-databasePopulator.xml, opennms-dao/src/test/java/org/opennms/netmgt/dao/hibernate/MonitoringSystemDaoHibernateIT.java, opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MonitoringSystemsRestService.java, opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MonitoringSystemsRestServiceIT.java
We want to get the Meridian system ID to use in Zenith Connect to uniquely identify the system that is registering with Zenith to send data. The system ID is the MonitoringSystem id field for the `OpenNMS` `type`, a uuid.
We are providing a Rest API to get the "main" OpenNMS system.
The front end will be implemented separately.
Had to do some additional work to optionally have the `DatabasePopulator` create the original `DistPoller` (which is the `OnmsMonitoringSystem`) with a specified ID for these integration tests only. By default, the id is a uuid with all 0's, which doesn't matter for all the other integration tests.
PR includes documentation and integration tests.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17751
=> NMS-17751: Monitoring System Rest API (foundation-2024)

features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java, opennms-base-assembly/src/main/filtered/bin/opennms, opennms-container/core/Dockerfile
* JIRA: https://opennms.atlassian.net/browse/NMS-15676
I read a lot about different cloud container engine and there are not really good ways to detect whether we are running inside a container. So, I choosed a simple but bulletproof method that at least will work in every case for the containers that are built by us. The tests regarding docker and podman are still in place, so user-built containers are also detected for these two platforms.
=> NMS-15676: Detect whether OpenNMS is running inside container

ui/src/App.vue, ui/src/components/ZenithConnect/ZenithConnectRegister.vue, ui/src/services/index.ts, ui/src/services/monitoringSystemService.ts, ui/src/stores/monitoringSystemStore.ts, ui/src/types/index.ts
We added a Rest API to get the main monitoring system info. This calls that API to get the Meridian `systemId` and also the `label` to populate fields used to register the Meridian instance with Zenith.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17767
=> NMS-17767: Use systemId in Zenith Connect UI

antora-playbook-local.yml
Updating `antora-ui-opennms` reference in `antora-playbook-local.yml` in `foundation-2021`. The library was updated to remove any reference to `polyfill.js` which is a security vulnerability.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17865
=> NMS-17865: Fix antora-playbook-local.yml in foundation-2021

antora-playbook-local.yml
Fix reference to `antora-ui-opennms`.
This is part of a fix to remove references to `polyfill.js` which is a security vulnerability.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17865
=> NMS-17865: Fix antora-ui-opennms reference

opennms-container/minion/container-fs/entrypoint.sh, smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
* JIRA: https://opennms.atlassian.net/browse/NMS-17756
I have now adapted the entrypoint.sh script. It now allows the configuration of Kafka via the IPC parameter (KAFKA_IPC_BOOTSTRAP_SERVERS) as well as via the three individual features Sink, RPC and Twin (KAFKA_SINK_BOOTSTRAP_SERVERS, KAFKA_RPC_BOOTSTRAP_SERVERS and KAFKA_TWIN_BOOTSTRAP_SERVERS). In other words, as described in the installation instructions. ActiveMQ should now be deactivated in both cases.
=> NMS-17756: Modified entrypoint.sh and disabled ActiveMQ in Kafka Smoke Tests

debian/control, docs/modules/releasenotes/pages/whatsnew.adoc, tools/packages/opennms/opennms.spec
I have found that we need to adjust the RPM/DEB package dependencies. The package jrrd2 is now not a suggestion and required. The dependency for RRDTool is not required and satisfied by jrrd2 itself, see:
* https://github.com/OpenNMS/jrrd2/blob/f8a29dba62a566d6c2a043c546fe35a7ff0695a8/debian/control#L13
* https://github.com/OpenNMS/jrrd2/blob/f8a29dba62a566d6c2a043c546fe35a7ff0695a8/build-packages.sh#L38
I have also added changelog with some hints on this topic.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17883
=> NMS-17883: Add DEB/RPM package dependencies and changelog

features/zenith-connect/persistence/src/main/java/org/opennms/features/zenithconnect/persistence/api/ZenithConnectPersistenceException.java, features/zenith-connect/persistence/src/main/java/org/opennms/features/zenithconnect/persistence/api/ZenithConnectPersistenceService.java, features/zenith-connect/persistence/src/main/java/org/opennms/features/zenithconnect/persistence/impl/ZenithConnectPersistenceServiceImpl.java, features/zenith-connect/persistence/src/test/java/org/opennms/features/zenithconnect/persistence/impl/ZenithConnectPersistenceServiceImplIT.java, features/zenith-connect/rest/src/main/java/org/opennms/features/zenithconnect/rest/impl/DefaultZenithConnectRestService.java, ui/src/components/ZenithConnect/ZenithConnectRegister.vue, ui/src/components/ZenithConnect/ZenithConnectRegisterResult.vue, ui/src/components/ZenithConnect/ZenithConnectView.vue, ui/src/services/index.ts, ui/src/services/zenithConnectService.ts, ui/src/stores/zenithConnectStore.ts, ui/src/types/zenithConnect.d.ts
Update the Zenith Connect UI to use the Rest API for storing and retrieving registration info.
Update the persistence service to exclude duplicate registrations.
Clean up the UI a bit.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17749
=> NMS-17749: Zenith Connect UI, connect with Registration Rest API

bin/functions.pl, container/features/pom.xml, container/noop-jetty-extension/pom.xml, debian/control, docs/antora.yml, features/config/osgi/cm/pom.xml, features/container/sentinel/pom.xml, features/ui-extension/pom.xml, opennms-assemblies/minion/src/main/filtered/debian/control, opennms-assemblies/sentinel/src/main/filtered/debian/control, opennms-base-assembly/src/main/filtered/bin/runjava, smoke-test/pom.xml, sonar-project.properties, tools/packages/minion/minion.spec, tools/packages/opennms/jdk.spec, tools/packages/opennms/opennms.spec, tools/packages/sentinel/sentinel.spec
Removed RPM/DEB package dependencies for OpenJDK 11. Changed source and compiler target from 11 to 17.
Haveged is removed as a dependency which is obsolete on modern Kernel 5.6 forward.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17899
=> NMS-17899: Remove Java 11 dependencies

.circleci/scripts/postgres.sh, .circleci/scripts/smoke.sh, debian/control, docs/antora.yml, docs/modules/deployment/pages/core/centos-rhel7/postgresql.adoc, docs/modules/deployment/pages/core/centos-rhel9/postgresql.adoc, docs/modules/deployment/pages/core/docker/postgresql.adoc, tools/packages/opennms/opennms.spec
Removed dependencies for PostgreSQL versions reached end of life.
Updated the PostgreSQL test from 10 to the lowest maintained version 13.
Set the minimal supported version from 10 to 13 in our requirement documentation.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17900
=> NMS-17900: Remove PostgreSQL 10,11,12

container/features/src/main/resources/features.xml, features/elastic/client/pom.xml, features/elastic/client/src/main/java/org/opennms/features/elastic/client/DefaultElasticRestClient.java, features/elastic/client/src/main/java/org/opennms/features/elastic/client/ElasticRestClient.java, features/elastic/client/src/main/java/org/opennms/features/elastic/client/ElasticRestClientFactory.java, features/elastic/client/src/main/java/org/opennms/features/elastic/client/commands/TemplateCommand.java, features/elastic/client/src/main/resources/OSGI-INF/blueprint/blueprint.xml, features/elastic/client/src/test/java/org/opennms/features/elastic/client/ElasticRestClientIT.java, features/elastic/client/src/test/resources/templates/component-mappings.json, features/elastic/client/src/test/resources/templates/component-settings.json, features/elastic/client/src/test/resources/templates/index-template/index-template.json, features/elastic/client/src/test/resources/templates/test-ilm-policy.json, features/elastic/pom.xml, features/pom.xml, opennms-full-assembly/pom.xml, pom.xml
This is first part of providing composable template support for Flows
Add Elastic Rest Client that can apply templates from directory
All templates from a given directory and sub directories will be applied based on naming
ilm, policy, lifecycle - ILM
component, settings, mappings, aliases - COMPONENT
composable, index - INDEX
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17733
=> NMS-17733: Add Elastic Rest Client for composable Template support

docs/modules/deployment/pages/core/getting-started.adoc, docs/modules/operation/pages/deep-dive/admin/configuration/newsfeed-configuration.adoc, docs/modules/operation/pages/deep-dive/events/event-tokens.adoc, docs/modules/operation/pages/deep-dive/events/sources/snmp-traps.adoc, docs/modules/reference/pages/telemetryd/protocols/jti.adoc, docs/modules/releasenotes/pages/changelog.adoc, docs/modules/releasenotes/pages/whatsnew.adoc
Fixed warning while building the docs for the following errors:
* Invalid cross references in the getting started section, event definition
* Fixing HTML encoding in XML event definition in the snmp-trap event source
* Masking environment variables so they aren't tried to be evaluated as Antora variables
* Fixing wrong headline levels in change log and what's new section
=> docs: Fix links and headline inconsistencies

features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTO.java, features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java, features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTOTest.java
https://opennms.atlassian.net/browse/NMS-18022
Adds a metric to the usage report for metrics written to TSS `integration` strategies by pulling `count` from `org.opennms.timeseries:name=samples.write.integration`
=> NMS-18022: Add tss write metrics to usage report

opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
Removed the verbiage for "deleting a node if it's down for X number of days." No longer needed as we no longer include this in the downtime model in the Pollerd config.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18053
=> NMS-18053: Update the "nodeDeleted" Event in opennms.pollerd.events.xml

docs/modules/deployment/pages/minion/installing-jdbc-driver.adoc
DOCS DOCS DOCS DOCS!
Included tested and working feature file examples with currently available JDBC driver versions, download tips using Maven, fixed some token replacement issues
=> Docs: Update Minion JDBC docs with examples

docs/modules/development/pages/rest/ksc_reports.adoc
DOCS DOCS DOCS DOCS 
Usage docs for the /ksc REST endpoint were mssing; add them with some simple examples
=> Docs: Update missing KSC endpoint docs

ui/src/components/Nodes/ColumnSelectionDrawer.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/stores/nodeStructureStore.ts
Updates to the column customization feature on the Structured Node / New Node List page.
The gear button should be changed to a Feather secondary button, "Customize".
Clicking opens a drawer, "Customize the available columns".
See Figma for example.
In the drawer, user can add, remove and rearrange columns. As columns are chosen, the dropdowns to add more columns only display columns that have not yet been chosen.
When done, it should have same behavior as current, it updates the store and also stores the column preferences in localStorage.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18045
=> FE: Update Node List column customization

features/telemetry/protocols/bmp/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/parser/proto/bgp/packets/pathattr/Aggregator.java
A juniper MX240 that has a large number of IPv4 and IPv6 peers, that when connected to OpenNMS via BMP would throw the following exception and terminate the session almost immediately.
Invalid packet: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(16) exceeds writerIndex(8)
This occurred in the Aggregator path attribute parser, which incorrectly assumed that the aggregator’s IP address length depended on the peer’s address family (via PeerFlags). For IPv6 peers, it attempted to read 16 bytes instead of the correct 4 bytes.
This patch should always read 2 bytes for ASN and 4 bytes for IP address.
The patch was tested on OpenNMS Horizon 33.1.7
JIRA: https://opennms.atlassian.net/browse/NMS-18042
=> NMS-18042: Fix BMP Aggregator parser to handle IPv6 peers correctly

opennms-webapp/src/main/java/org/opennms/web/account/selfService/PasswordGateActionServlet.java, opennms-webapp/src/main/webapp/WEB-INF/menu-template-alt.json, opennms-webapp/src/main/webapp/WEB-INF/menu-template-default.json, opennms-webapp/src/main/webapp/WEB-INF/menu-template.json, opennms-webapp/src/main/webapp/admin/product-update-enrollment/index.jsp, ui/src/components/Menu/Menubar.vue, ui/src/menu/main.ts, ui/src/styles/opennms-feather-styles.scss
Menu redesign - fix font styles on legacy pages, all pages now use Feather fonts (except the Vaadin-based pages).
Menu items that go to external links now open in separate tabs. Some updates to the menus.
Opening this PR as advisory only since it's mostly cosmetic. Going to merge to the feature branch so I can prepare a PR to merge this feature to `develop`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17976
=> NMS-17976: Menu redesign fix legacy font styles

docs/modules/operation/pages/admin/housekeeping/introduction.adoc
DOCS DOCS DOCS DOCS DOCS DOCS
Redo the "Housekeeping" page with information actually relevant to housekeeping, instead of in the context of pre-upgrade or upgrading, which does not belong in this section.
=> Docs: redo the housekeeping page

docs/modules/operation/pages/deep-dive/admin/configuration/newsfeed-configuration.adoc, docs/modules/operation/pages/deep-dive/events/sources/snmp-traps.adoc
DOCS DOCS DOCS DOCS DOCS DOCS 
The event-sources/snmp-traps document contained an invalid reference starting in 2023; this fixes the reference.
Also fixes some invalid variable references because I was in there.
=> Docs: Fix incorrect xreference for trap reception

features/springframework-security/src/main/java/org/opennms/web/springframework/security/LoginModuleUtils.java, features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java, opennms-webapp/src/main/java/org/opennms/web/account/selfService/PasswordGateActionServlet.java, smoke-test/src/test/java/org/opennms/smoketest/AdminPasswordGateIT.java, smoke-test/src/test/java/org/opennms/smoketest/AngularLoginRedirectIT.java, smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportIT.java, smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java, smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java, smoke-test/src/test/java/org/opennms/smoketest/UIRefreshIT.java, ui/yarn.lock
In some cases, especially when a user changed their password, user would be redirected to an asset file (like a CSS, JS or TTF file) instead of to a real page (jsp/htm) after logging in.
This PR includes code to make sure we aren't saving any of those asset files in the Spring security Saved Request Cache.
There may be a better way to do this, but this works for the immediate problem. There are still issues about when you are not logged in and navigate to some page other than the home page; you don't redirect properly to the original requested page. There are some issues because of the Admin Password Gate page.
Reenabled some smoke tests for the login process, but the ones dealing with that redirect are still being ignored for now.
Also fixed some other smoke tests that had been ignored: …
=> NMS-18175: Ensure user is not redirected to an asset file after login

container/karaf/src/main/filtered-resources/etc/system.properties, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Slf4jLogFactory.java, core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4jTrapReceiverIT.java, core/upgrade/src/test/resources/etc2/opennms.properties, features/container/minion/src/main/filtered-resources/etc/system.properties, features/container/sentinel/pom.xml, features/container/sentinel/src/main/filtered-resources/etc/system.properties, opennms-base-assembly/src/main/filtered/etc/opennms.properties, pom.xml, tests/mock-snmp-agent/src/main/java/org/opennms/mock/snmp/MockSnmpAgent.java
Backporting to H34
* NMS-18160: Upgrade snmp4j to 2.8.15
Upgrade snmp4j-agent to 2.7.9
* NMS-18160: Add our own logger that uses slf4j
Slf4jLogFactory will be used by snmp4j.LogFactory instead of depending upon snmp4j-log4j
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18160
=> NMS-18160: Upgrade snmp4j to 2.8.15 (#7822)

ui/src/components/Nodes/ColumnSelectionDrawer.vue, ui/src/components/Nodes/NodeAdvancedFiltersDrawer.vue, ui/src/components/Nodes/NodeStructurePanel.vue, ui/src/components/Nodes/NodesTable.vue, ui/src/components/Nodes/hooks/useNodeQuery.ts, ui/src/stores/nodeStructureStore.ts, ui/src/types/index.ts
On the new Node List page, user can now search for a full IP address along with node label, in the search term input box.
Search is an `"or"` search, will match either node label or IP address.
Note, if user enters an IP address in the Extended Search, then only that will be valid and any IP in the search term input will be ignored.
Fixed an issue where the Monitoring Locations filter was not retaining values.
Added a "chip" if user adds any Extended Search items.
Renamed some methods to better show intent.
Reduced timeout on `FeatherAutocomplete` for filter selection, since values are already in memory (they are fetched prior to the filter drawer opening).
Column Customization and Filter Selection drawers now scroll vertically if needed.
Various other fixes and cleanup.
* Jira (Issue …
=> NMS-18047: Node list including IP search, fix other issues

docs/modules/development/nav.adoc, docs/modules/development/pages/menu/menu-templates.adoc, docs/modules/operation/nav.adoc, docs/modules/operation/pages/deep-dive/menu/introduction.adoc
Move the menu templates documentation from `Operation > Deep Dive > Menus` to `Development > Menus`.
While these can be edited, we are not officially supporting editing them for users, so we want to take this out of `Operation`, but still include it in documentation for reference.
Also removed reference to moving the templates to `etc`, we are holding off on that for now.
Also fixed `userTileProviders` to denote that it is a read-only field and any user edits are ignored.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18274
* * Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18276
=> NMS-18276: Move menu template docs to Development section

docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc, docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS 
...And remove the outdated info about AmbientCapabilities; the `opennms.service` unit file already ships with this set.
=> DOCS: Clarify setting heap and open file descriptors

ui/src/components/Menu/Menubar.vue
Double-pressing a shift key should focus the main search input in the menu bar.
Just needed to fix the CSS selector used to get the input element.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18269
=> NMS-18269: Fix double-shift for search input focus

opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmFilterController.java, opennms-webapp/src/main/webapp/includes/bootstrap.jsp
Menu was not showing up on some alarm pages. Partly due to local `baseHref` variable being defined differently on those pages.
Update `bootstrap.jsp` to use `__baseHref` as the base for including `ui-components`. This not only fixes these issues but is more correct.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18266
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18221
=> NMS-18266: Fix baseHref for ui-components references

opennms-webapp/src/main/webapp/WEB-INF/menu-template-default.json, opennms-webapp/src/main/webapp/WEB-INF/menu-template.json, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java, ui/src/components/Menu/UserNotificationsMenuItem.vue, ui/src/components/Menu/UserSelfServiceMenuItem.vue
Make the self service menu just an icon, remove the username from it since username could be an arbitrary length.
Include the username in the first item of the dropdown, we ellipsify it if needed. Links to main page, eventually could like to a user profile page.
Remove user profile menu from side menu since all functionality is now in the top self service menu.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18281
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18282
=> NMS-18281: Self service menu is icon-only, remove user profile menu

ui/src/components/EventConfigurationDetail/Drawer/EventConfigDetailsDrawer.vue, ui/src/components/EventConfigurationDetail/EventConfigEventTable.vue, ui/src/stores/eventConfigDetailStore.ts, ui/src/types/eventConfig.d.ts
FE: Edit an event under a specific source by event and source ID
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18265
=> FE: Edit an event under a specific source by event and source ID

container/karaf/src/main/filtered-resources/etc/system.properties, core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Slf4jLogFactory.java, core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/snmp4j/Snmp4jTrapReceiverIT.java, core/upgrade/src/test/resources/etc2/opennms.properties, docs/modules/releasenotes/pages/whatsnew.adoc, features/container/minion/src/main/filtered-resources/etc/system.properties, features/container/sentinel/src/main/filtered-resources/etc/system.properties, opennms-base-assembly/src/main/filtered/etc/opennms.properties, pom.xml, tests/mock-snmp-agent/src/main/java/org/opennms/mock/snmp/MockSnmpAgent.java
Backporting to `foundation-2022`
* NMS-18160: Upgrade snmp4j to 2.8.15
Upgrade snmp4j-agent to 2.7.9
* NMS-18160: Add our own logger that uses slf4j
Slf4jLogFactory will be used by snmp4j.LogFactory instead of depending upon snmp4j-log4j
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18160
=> NMS-18160: Upgrade snmp4j to 2.8.15 (#7822) (#7852) (#7858)

core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/QuickAddNode.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Requisition.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/controllers/Requisitions.js, core/web-assets/src/main/assets/js/apps/onms-requisitions/lib/scripts/services/Requisitions.js, smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java, smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java
On the Quick Add Node page, do not allow the user to choose the `selfmonitor` requisition to add nodes to.
User will get an error if they try to do this.
Also on the requisition edit page, display an alert and do not allow a user to add a node to the `selfmonitor` requisition.
This PR doesn't fix the popup window. We are planning on redoing the entire Quick Add Node page, so this is just a temporary fix to prevent users from adding nodes to the `selfmonitor` requisition.
Fixed an issue where when user clicked `Cancel` on the popup they were redirected to a non-existent page. Fixed a few typos.
Also: fixed smoke test for `MenuHeaderIT` for items where the top-level menu item is a direct link.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18184
=> NMS-18184: Exclude selfmonitor requisition on Quick Add Node

ui/src/components/Menu/SideMenu.vue
We were displaying the Plugins menu even when no plugins were installed.
We were displaying the fake menu items instead of just not displaying the top level Plugins menu at all.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18285
=> NMS-18285: Do not display Plugins menu if there are no plugins installed

core/lib/src/main/java/org/opennms/core/utils/TimeSeries.java
Fixed the typo in constant name.
=> fix: Typo in constant name for evaluation time series strategy

opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml, ui/src/services/whoAmIService.ts, ui/src/stores/authStore.ts
Ensure that the SCV Rest service can only be accessed by users with the admin (`ROLE_ADMIN`) role.
Also ensures that non-admin users cannot manually route to the SCV web UI screen.
This is the same as NMS-18325 and NMS-18533 but backported to `foundation-2024`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18548
=> NMS-18548: Restrict SCV Rest to admin, fix role check in UI

opennms-container/common.mk, opennms-container/core/Dockerfile, opennms-container/minion/Dockerfile, opennms-container/sentinel/Dockerfile, smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
Update the OCI deploy base image with JMX Prometheus exporter 1.4.0 which was bumped from 1.3.0.
Use deploy base image with changes from https://github.com/OpenNMS/deploy-base/commit/f5e7225eec912d4837a82457cefcc0cc05ac7be5
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18544
=> NMS-18544: Update deploy base image with JMX Prometheus exporter 1.4.0

opennms-webapp-rest/src/main/webapp/WEB-INF/menu/menu-template-alt.json, opennms-webapp-rest/src/main/webapp/WEB-INF/menu/menu-template-default.json, opennms-webapp-rest/src/main/webapp/WEB-INF/menu/menu-template-legacy.json, opennms-webapp-rest/src/main/webapp/WEB-INF/menu/menu-template.json, ui/src/components/Menu/SideMenu.vue
The Feather Sidemenu component adds a hard-coded "Menu" header item if there are no header items.
In our current configuration, we don't really need this header item at the top and it just takes up vertical space.
This PR adds a "dummy" header menu item to suppress this behavior, plus some CSS to tighten up the spacing.
See NMS-18772 for updating the Feather component itself.
Example of what we are removing, the top "Menu" line:
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18773
=> NMS-18773: Remove unwanted menu header
