- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/provisioning/detectors/WmiDetector.adoc
- docs/modules/reference/pages/service-assurance/monitors/WmiMonitor.adoc
> NMS-11065: WmiMonitor

- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/graph/GraphRestServiceIT.java
JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14326
> NMS-14326 Fix failing smoke tests

- features/device-config/monitor-adaptor/src/main/java/org/opennms/features/deviceconfig/monitor/adaptor/DeviceConfigMonitorAdaptor.java
- features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
- features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
- opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
Fix wrong cron expression getting 500 error in DCB UI
Fix `configBackupStarted` related issues.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14333
> NMS-14333: Fix cron expression/event related issues in DCB

- smoke-test/src/test/java/org/opennms/smoketest/dcb/DcbEndToEndIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14328
> NMS-14328: Fix smoke test

- ui/src/components/Configuration/ConfigurationHelper.ts
- ui/src/components/Configuration/copy/requisitionTypes.ts
> NMS-14340 Fix cron expression error message validation

- docs/modules/operation/nav.adoc
NMS-14131: DCB: UI Documentation - updated to change TOC hierarchy level so that DCB documentation is not under Service Assurance.
* If this is new …
> NMS-14131: DCB: UI Documentation

- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/test/java/org/opennms/smoketest/rest/FileEditorIT.java
FileEditor automation test that tests regular and wrong behaviour of the user. 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14267
> NMS-14267: Add smoke test for FileEditor

- docs/modules/operation/pages/device-config-backup/configuration.adoc
- docs/modules/operation/pages/device-config-backup/dcb-requisition.adoc
- docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-gz.dcb
- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-set.dcb
- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-txt.dcb
Add missing docs
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14301
> NMS-14301: Configure port for juniper devices

- ui/src/components/Configuration/ConfigurationThreadPools.vue
> NMS-14345 Change upper bound value

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/admin/scv-configuration.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14207
> NMS-14207: Add doc for SCV

- docs/modules/operation/pages/user-management/introduction.adoc
- features/datachoices/pom.xml
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
- features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/AlarmDao.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/MonitoringSystemDao.java
- opennms-dao-api/src/main/java/org/opennms/netmgt/dao/api/SnmpInterfaceDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockAlarmDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockMonitoringSystemDao.java
- opennms-dao-mock/src/main/java/org/opennms/netmgt/dao/mock/MockSnmpInterfaceDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/MonitoringSystemDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/SnmpInterfaceDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/AlarmDaoIT.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsMonitoringSystem.java
JIRA: https://issues.opennms.org/browse/NMS-14203
Add new KPIs to datachoices telemetry:
* num situations
* num locations
* num minions
* list of karaf features installed
> NMS-14203: Add new KPIs to datachoices telemetry

- features/collection/shell-commands/pom.xml
- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/StressCommand.java
- features/collection/shell-commands/src/test/java/org/opennms/netmgt/collection/commands/StressCommandTest.java
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14194
> NMS-14194: Be able to control label sizes for the stress-metrics command

- core/web-assets/src/main/assets/js/apps/geomap-js/index.js
> NMS-13918:Map Pins Missing Since Upgrade

- features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
- features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14129
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14128
> NMS-14128: Improve DCB script execution error handling

- ui/src/components/Configuration/ConfigurationHelper.ts
- ui/tests/configuration.test.ts
> NMS-14359 Modify host, zone and requisition name validation

- docs/modules/deployment/pages/time-series-storage/timeseries/time-series-storage.adoc
- docs/modules/development/nav.adoc
- docs/modules/development/pages/oia/introduction.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14154
> NMS-14154: Add OIA doc

- docs/modules/reference/pages/provisioning/handlers/introduction.adoc
NMS-14359: Modify host, zone and requisition name field validation - added valid characters as a note to the import handlers documentation.
* If this …
> NMS-14359: Modify host, zone and requisition name field validation

- opennms-base-assembly/src/main/filtered/etc/datacollection/f5.xml
> NMS-14338: fix f5 datacollection config

- docs/modules/releasenotes/pages/whatsnew.adoc
> Updating v30 release notes

- features/springframework-security/pom.xml
- features/springframework-security/src/main/java/org/opennms/web/springframework/security/RequestHeaderPreAuthenticationProcessingFilter.java
- features/springframework-security/src/test/java/org/opennms/web/springframework/security/RequestHeaderPreAuthenticationProcessingFilterTest.java
- opennms-doc/guide-admin/src/asciidoc/text/user-management/pre-authentication.adoc
- opennms-webapp/src/main/webapp/WEB-INF/spring-security.d/header-preauth.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14059
> NMS-14059: Backporting Add support for pre-authorization via HTTP header (to be used with pre-authentication)

- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/datacollection/aruba.xml
added new configuration for aruba AOS-CX switches provided by Ken Eshelby
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14056
> NMS-14056: Aruba AOS-CX datacollection config

- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
Adding a simple unit test.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14321
> NMS-14321: Add unit test

- opennms-webapp/src/main/webapp/includes/notification-box.jsp
* JIRA: https://issues.opennms.org/browse/NMS-12355
> NMS-12355: Change of the text if only one message is available

- ui/src/components/Topology/NetworkGraph.vue
> NMS-14377 Display contextmenu next to mouse

- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14374
> Fix Smoke Test for GraphMLTopologyIT

- docs/modules/reference/pages/glossary.adoc
Added Requisitions, Foreign Source, Flows, CircleCI, Discourse, Azure, Kibana, Docker, and Snaps. Updated additions as per Bonnie's comments on draft PR 4852. Updated formatting to ensure all new sentences are on separate lines.
* If …
> NMS-14347: Update formatting & add new terms to glossary.adoc

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/database-reports/database.adoc
- docs/modules/operation/pages/database-reports/template-introduction.adoc
- docs/modules/operation/pages/database-reports/templates/avail-summary.adoc
- docs/modules/operation/pages/database-reports/templates/availability.adoc
- docs/modules/operation/pages/database-reports/templates/calendar.adoc
- docs/modules/operation/pages/database-reports/templates/classic.adoc
- docs/modules/operation/pages/database-reports/templates/event.adoc
- docs/modules/operation/pages/database-reports/templates/grafana.adoc
- docs/modules/operation/pages/database-reports/templates/interface-avail.adoc
- docs/modules/operation/pages/database-reports/templates/maintenance-expired.adoc
- docs/modules/operation/pages/database-reports/templates/maintenance-stragegy.adoc
- docs/modules/operation/pages/database-reports/templates/maintenance-strategy.adoc
- docs/modules/operation/pages/database-reports/templates/morning.adoc
- docs/modules/operation/pages/database-reports/templates/response-summary.adoc
- docs/modules/operation/pages/database-reports/templates/response-time.adoc
- docs/modules/operation/pages/database-reports/templates/serial.adoc
- docs/modules/operation/pages/database-reports/templates/snmp.adoc
- docs/modules/operation/pages/database-reports/templates/standard-text-fields.adoc
- docs/modules/operation/pages/database-reports/templates/standard.adoc
- docs/modules/operation/pages/database-reports/templates/total-bytes.adoc
- docs/modules/operation/pages/database-reports/templates/traffic-rates.adoc
…dy for review.
* If this PR targets a `foundation-*` branch, does it try to avoid …
> NMS-11810: Database Reports documentation

- docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
- features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
- features/device-config/monitor/src/test/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitorTest.java
- features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/api/Retriever.java
- features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java
- features/device-config/retrieval/src/test/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImplTest.java
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
- features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14119
> NMS-14119: Implement support for SSH host key authentication

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AlarmDaoHibernate.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/HibernateUtils.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/OutageDaoHibernate.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/HeatMapRestService.java
* JIRA: https://issues.opennms.org/browse/NMS-14243
> NMS-14243: Fixed Heatmap

- docs/modules/operation/pages/topology/enlinkd/introduction.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14325
> Enlinkd Topology Map Layers Documentation

- .circleci/config.yml
Only trigger flaky tests when appropriate.
Once this is merged, we should set up a trigger to run the flaky tests weekly.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14335
> NMS-14335: parameterize flaky smoke tests

- .circleci/config.yml
- .circleci/main/@main.yml
- .circleci/main/parameters.yml
This is a version of https://github.com/OpenNMS/opennms/pull/4858 for h30 and above.
(we should set up a trigger to run this nightly, along with develop, once it's merged)
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14335
> NMS-14335: parameterize flaky smoke tests (h30+)

- docs/modules/operation/pages/service-assurance/polling-packages.adoc
> NMS-11793: Guide to monitor essential Microsoft Active Directory Services

- features/enlinkd/persistence/api/src/main/java/org/opennms/netmgt/enlinkd/persistence/api/LldpLinkDao.java
- features/enlinkd/persistence/impl/src/main/java/org/opennms/netmgt/enlinkd/persistence/impl/LldpLinkDaoHibernate.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/LldpTopologyServiceImpl.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms10205bEnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms17216EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms7563EnIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13943
> Set always ifindex for enlinkd links

- opennms-webapp/src/main/webapp/admin/index.jsp
* JIRA: https://issues.opennms.org/browse/NMS-14393
I searched through the images in the docs tree but did not found any image needing an update.
> NMS-14393: Added link to Secure Credentials Vault

- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcher.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/TimeseriesFetchStrategy.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/aggregation/NewtsConverterUtils.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/aggregation/NewtsLikeSampleAggregator.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/sampleread/TimeseriesFetchStrategyTest.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersisterIT.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesRoundtripIT.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesWriterTest.java
- pom.xml
*Blocked by: https://github.com/OpenNMS/opennms-integration-api/pull/58*
This PR implements the change in the Integration API introduced by [DC-126](https://issues.opennms.org/browse/DC-126).
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-126
> DC-126: Deduplicate the metric on the query results

- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcher.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcherTest.java
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-146
It make sure cache is only build when it is loaded.
> DC-146: Try to found the bottleneck of cloud-plugin cache get and improve it

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/NMS14314Test.java
- features/mib-compiler/src/test/resources/RFC1213-MIB.mib
fix issue parsing type ipaddress when generating datacollection using RFC-1213
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14314
> NMS-14314: MIB compiler creates datacollections that fail to validate

- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/OpaqueExt.java
- docs/modules/operation/pages/performance-data-collection/data-types.adoc
- docs/modules/reference/pages/performance-data-collection/collectors/SnmpCollector.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14382
> NMS-14382 Add documentation for OPAQUE data type support

- docs/modules/reference/pages/glossary.adoc
Added entries for BSM, Drools, Asset, Categories, Outage, MIB, and UEI.
* If this PR …
> NMS-14351: Add terms to glossary.adoc

- docs/modules/operation/pages/admin/restore/introduction.adoc
> Add RHEL backup steps tab

- features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfig.java
- features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfigFactory.java
- features/enlinkd/config/src/main/java/org/opennms/netmgt/config/EnhancedLinkdConfigManager.java
- features/enlinkd/config/src/main/java/org/opennms/netmgt/config/enlinkd/EnlinkdConfiguration.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14433
> NMS-14433 Enlinkd Clean Config Classes

- opennms-icmp/opennms-icmp-jna/src/main/java/org/opennms/netmgt/icmp/jna/JnaPinger.java
- opennms-icmp/opennms-icmp-jni/src/main/java/org/opennms/netmgt/icmp/jni/JniPinger.java
- opennms-icmp/opennms-icmp-jni6/src/main/java/org/opennms/netmgt/icmp/jni6/Jni6Pinger.java
- pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-13956
> NMS-13956: Point troubleshooting links to docs.opennms.org

- opennms-base-assembly/src/main/filtered/bin/newts-repository-converter
* JIRA: https://issues.opennms.org/browse/NMS-14079
> NMS-14079: Fixed script

- docs/modules/operation/pages/flows/classification-engine.adoc
Added descriptions of wildcards to Source and Destination IP Address table rows. Reviewed and edited page contents. …
> NMS-12421: Update classification-engine.adoc

- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdBuilderITCase.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdSnmpIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/EnLinkdTestHelper.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms0001EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms0002EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms0123EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms4930EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms6801EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms7467EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms7777DWEnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms7918EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/Nms8000EnIT.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/NodeTopologyServiceIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14432
Remove all the yellow from IntelliJ
> NMS-14432 Enlinkd clean tests warnings

- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/Bridge.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgeForwardingTable.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgeForwardingTableEntry.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgePort.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgePortWithMacs.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BroadcastDomain.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/DiscoveryBridgeTopology.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/MacPort.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/Node.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/SharedSegment.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/Topology.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/TopologyConnection.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/TopologyShared.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/UserDefinedLinkTopologyService.java
- features/enlinkd/service/api/src/test/java/org/opennms/netmgt/enlinkd/service/api/CompositeKeyTest.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/BridgeTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/CdpTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/IpNetToMediaTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/IsisTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/NodeTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/OspfTopologyServiceImpl.java
- features/enlinkd/service/impl/src/main/java/org/opennms/netmgt/enlinkd/service/impl/TopologyServiceImpl.java
- features/enlinkd/service/impl/src/test/java/org/opennms/netmgt/enlinkd/service/ServiceTest.java
Cleaned service api classes
Cleaned service impl classes
Only syntax changes. 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14435
> NMS-14435 Enlinkd Clean Service Classes

- docs/modules/development/pages/rest/graph.adoc
> Graph REST docs formatting fix

- opennms-icmp/opennms-icmp-jna/src/main/java/org/opennms/netmgt/icmp/jna/JnaPinger.java
- opennms-icmp/opennms-icmp-jni/src/main/java/org/opennms/netmgt/icmp/jni/JniPinger.java
- opennms-icmp/opennms-icmp-jni6/src/main/java/org/opennms/netmgt/icmp/jni6/Jni6Pinger.java
- pom.xml
* JIRA: https://issues.opennms.org/browse/NMS-13956
> NMS-13956: Point troubleshooting links to docs.opennms.com

- core/db/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/minion/NMS14441_IT.java
https://issues.opennms.org/browse/NMS-14441
> NMS-14441: Fixed core.db pom.xml

- features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvListCommand.java
* JIRA: https://issues.opennms.org/browse/NMS-14385
> NMS-14385: added scv-list command

- docs/modules/operation/pages/device-config-backup/dcb-requisition.adoc
- docs/modules/operation/pages/meta-data.adoc
- docs/modules/reference/pages/service-assurance/monitors/DeviceConfigMonitor.adoc
Some documentation updates for Device Configuration Backup config type.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14311
> NMS-14311: Device Config Backup doc updates for config type

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/provisioning/detectors.adoc
- docs/modules/reference/pages/provisioning/detectors/ActiveMQDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/BgpSessionDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/BsfDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/DnsDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/FtpDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/HostResourceSWRunDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/HttpDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/HttpsDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/JdbcDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/LoopDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/ReverseDNSLookupDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/SnmpDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/TcpDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/WebDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/Win32ServiceDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/WmiDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/WsmanDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/WsmanWqlDetector.adoc
Created reference/provisioning/detectors/JdbcDetector.adoc file and documented the detector's function, parameters, etc. …
> NMS-13427: Create JDBCDetector documentation

- container/features/pom.xml
- container/features/src/main/resources/features-sentinel.xml
- container/features/src/main/resources/features.xml
- features/collection/api/src/main/java/org/opennms/netmgt/collection/api/AbstractPersister.java
- features/timeseries/pom.xml
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersister.java
- features/timeseries/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14197
> NMS-14197: Get TimeSeries Persister running as separate feature

- features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/scv/SecureCredentialsVaultImpl.java
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-152
> DC-152: Imported Certificates don't survive reboot of OpenNMS

- features/flows/elastic/pom.xml
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentEnricher.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/DocumentMangler.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/MockDocumentEnricherFactory.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/MarkerCacheIT.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/NodeIdentificationIT.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14468
> NMS-14181: Add flow mangle script

- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java
- features/telemetry/protocols/netflow/parser/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/NMS14130_Test.java
JIRA: https://issues.opennms.org/browse/NMS-14467
> NMS-14467: Prefer ingressPhysicalInterface over INPUT_SNMP when processing flows

- docs/modules/deployment/pages/upgrade/restore/centos-rhel8/restore-centos-rhel8.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/No JIRA
> Fix docs markdown for restore from backup

- features/flows/api/src/main/java/org/opennms/netmgt/flows/api/Flow.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/Direction.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/ElasticFlowRepository.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/SearchQueryProvider.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
- features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/common.ftl
- features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/filter_snmp_interface.ftl
- features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_missing.ftl
- features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_others.ftl
- features/flows/elastic/src/main/resources/org/opennms/netmgt/flows/elastic/series_for_terms.ftl
- features/flows/elastic/src/test/java/org/opennms/netmgt/flows/elastic/TestFlow.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/DefaultDirectionIT.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowBuilder.java
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/FlowQueryIT.java
- features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/FlowDocumentBuilder.java
- features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/model/Direction.java
- features/flows/kafka-persistence/src/main/proto/flowdocument.proto
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/common/NetflowMessage.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/IpFixMessageBuilder.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/transport/Netflow9MessageBuilder.java
- features/telemetry/protocols/netflow/transport/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/transport/Direction.java
- features/telemetry/protocols/netflow/transport/src/main/proto/netflow.proto
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14279
> NMS-14279: Handle unknown flow direction

- opennms-base-assembly/src/main/filtered/etc/events/opennms.pollerd.events.xml
> NMS-10634: change description of nodeCategoryMembershipChanged

- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/BridgeSimpleConnection.java
- features/enlinkd/service/api/src/main/java/org/opennms/netmgt/enlinkd/service/api/DiscoveryBridgeTopology.java
- features/enlinkd/tests/src/test/java/org/opennms/netmgt/enlinkd/BroadcastDomainTest.java
Reviewed simple connection algorithm
changed also visibbility of method to calculate
the connections.
Better name and logs too
Added also a new test
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14479
> NMS-14479 Simplify BridgeSimpleConnection Class

- docs/modules/operation/pages/user-management/introduction.adoc
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
- features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
- opennms-config/src/main/java/org/opennms/netmgt/config/ServiceConfigFactory.java
* JIRA: https://issues.opennms.org/browse/NMS-14489
> NMS-14489: Added list of services to datachoice telemetry

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/provisioning/detectors.adoc
- docs/modules/reference/pages/provisioning/detectors/JdbcStoredProcedureDetector.adoc
- Added ./reference/provisioning/detectors/JdbcStoredProcedureDetector.adoc. 
- Updated ./reference/nav.adoc.
- Formatting updates.
* If this is new …
> NMS-14454: JDBCStoredProcedureDetector documentation

- docs/modules/development/pages/rest/heatmap.adoc
- docs/modules/development/pages/rest/rtc.adoc
- docs/modules/operation/pages/admin/webui/dashboard.adoc
- docs/modules/operation/pages/database-reports/database.adoc
- docs/modules/operation/pages/database-reports/templates/avail-summary.adoc
- docs/modules/operation/pages/database-reports/templates/availability.adoc
- docs/modules/operation/pages/database-reports/templates/response-summary.adoc
- docs/modules/operation/pages/database-reports/templates/response-time.adoc
- docs/modules/operation/pages/database-reports/templates/total-bytes.adoc
- docs/modules/operation/pages/database-reports/templates/traffic-rates.adoc
- docs/modules/operation/pages/elasticsearch/features/event-forwarder-mapping-table.adoc
- docs/modules/operation/pages/provisioning/fine-grained.adoc
- docs/modules/operation/pages/provisioning/policies.adoc
- docs/modules/operation/pages/topology/graphml-asset-topology-provider.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/rtcd.adoc
- docs/modules/reference/pages/service-assurance/monitors/CiscoPingMibMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/StrafePingMonitor.adoc
- Changed "surveillance category/categories" to "node tag/tags."
- Changed "node categories" to "node tags."
- Updated formatting.
Note: I couldn't find any instances of "provisioning group" or "node category" (singular) in the documentation, so those items haven't been changed.
Don't worry if this sounds like a …
> NMS-14352: Update terminology

- docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
> docs for Ubuntu install missed starting the service

- docs/modules/reference/pages/provisioning/policies.adoc
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14528
> update docs for provisioning policy matching

- features/device-config/api/src/main/java/org/opennms/features/deviceconfig/service/DeviceConfigService.java
- features/device-config/monitor/src/main/java/org/opennms/features/deviceconfig/monitors/DeviceConfigMonitor.java
- features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
- features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/api/Retriever.java
- features/device-config/retrieval/src/main/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImpl.java
- features/device-config/retrieval/src/test/java/org/opennms/features/deviceconfig/retrieval/impl/RetrieverImplTest.java
- features/device-config/service/src/main/java/org/opennms/features/deviceconfig/service/impl/DeviceConfigServiceImpl.java
- features/device-config/shell/src/main/java/org/opennms/features/deviceconfig/shell/DcbTriggerCommand.java
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/SshScriptingService.java
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
- features/poller/api/src/main/java/org/opennms/netmgt/poller/DeviceConfig.java
- features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
Just merged into `develop`, but this needs to make it into `30.0.1`. See **https://github.com/OpenNMS/opennms/pull/4933**
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14120
> NMS-14120: DCB: Get script debug output into 30.0.1

- ui/src/components/Topology/CtrlLayers.vue
- ui/src/components/Topology/NetworkGraph.vue
- ui/src/components/Topology/NoFocusMsg.vue
- ui/src/components/Topology/SideControls.vue
- ui/src/components/Topology/TopologyRightDrawer.vue
- ui/src/components/Topology/ViewSelect.vue
- ui/src/components/Topology/topology.constants.ts
- ui/src/components/Topology/topology.helpers.test.ts
- ui/src/components/Topology/topology.helpers.ts
- ui/src/containers/Map.vue
- ui/src/containers/Topology.vue
- ui/src/services/index.ts
- ui/src/services/topologyService.ts
- ui/src/store/topology/actions.ts
- ui/src/store/topology/getters.ts
- ui/src/store/topology/mutations.ts
- ui/src/store/topology/state.ts
- ui/src/types/topology.d.ts
- dynamic Display checkbox list
- generic topology graph
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14344
> NMS-14344 Topology refactoring

- features/prometheus-collector/src/main/java/org/opennms/netmgt/collectd/prometheus/PrometheusCollector.java
From this:
To this:
* If this PR targets a `foundation-*` branch, does it try to avoid …
> NMS-14534: Make PrometheusCollector's CollectionExceptions more meaningful

- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
Renaming roleCount to onCallRoleCount to avoid confusion.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14488
> NMS-14488: renaming roleCount to onCallRoleCount

- docs/modules/operation/pages/notifications/getting-started.adoc
- docs/modules/operation/pages/snmp-poller/concepts.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14412
> NMS-14412: SNMP Interface Poller doc updates

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/provisioning/detectors/JdbcDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/JdbcQueryDetector.adoc
- docs/modules/reference/pages/provisioning/detectors/JdbcStoredProcedureDetector.adoc
- Added ./reference/provisioning/detectors/JdbcQueryDetector.adoc. 
- Updated ./reference/nav.adoc.
* If this is new code, are there unit and/or …
> NMS-14453: JdbcQueryDetector documentation

- pom.xml
- smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java
> NMS-13953: Upgrade Kafka components to 3.2.0

- docs/modules/operation/pages/device-config-backup/configuration.adoc
- features/device-config/ssh-scripting/src/main/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImpl.java
- features/device-config/ssh-scripting/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14537
> NMS-14537: Add option to disable IO collection

- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/WebMonitor.java
```
admin@opennms()> poll -c org.opennms.netmgt.poller.monitors.WebMonitor 192.168.1.3 scheme=http path=/test
Monitor: org.opennms.netmgt.poller.monitors.WebMonitor
Parameter path: /test
Parameter scheme: http
Service is Up on 192.168.1.3 using org.opennms.netmgt.poller.monitors.WebMonitor:
response-time: 336.0000
```
4. once you've created this PR, please link to it in a comment in the JIRA …
> NMS-14535: WebMonitor should calculate response time

- opennms-webapp/src/main/java/org/opennms/web/account/selfService/NewPasswordActionServlet.java
- opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp
I followed the instructions of Jeff and added a gpdr based minimum recommadation of password complexity.
(minimum 12 characters, consisting of 1 special character, 1 upper case letter, 1 lower case letter and 1 number)
https://issues.opennms.org/browse/NMS-13981
Don't worry if this sounds like a lot, we can help you …
> NMS-13981 - Weak Password Policy

- features/executor-factory/cassandra/pom.xml
They aren't in Maven Central, so Intellj wasn't happy and a Maven build
of just org.opennms.features.executor-factory.cassandra was failing:
...
[INFO] Building OpenNMS :: Features :: Executor Factory :: Cassandra 31.0.0-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[WARNING] The POM for org.codehaus.jackson:jackson-core-asl:jar:1.9.13-atlassian-6 is missing, no dependency information available
[WARNING] The POM for org.codehaus.jackson:jackson-mapper-asl:jar:1.9.13-atlassian-6 is missing, no dependency information available
...
[ERROR] Failed to execute goal on project org.opennms.features.executor-factory.cassandra: Could not resolve dependencies for project org.opennms.features.executor-factory:org.opennms.features.executor-factory.cassandra:bu …
> Cassandra needs to be able to get the Atlassian updates to jackson1

- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersister.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/KafkaPersisterFactory.java
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/CollectionSetMapperTest.java
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaPersisterIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14470
> NMS-14470: Don't persist resources that are marked as such

- features/device-config/persistence/api/src/main/java/org/opennms/features/deviceconfig/persistence/api/DeviceConfigDao.java
- features/device-config/persistence/impl/src/main/java/org/opennms/features/deviceconfig/persistence/impl/DeviceConfigDaoImpl.java
- features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/api/DeviceConfigRestService.java
- features/device-config/rest/src/main/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestService.java
- features/device-config/rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceIT.java
- features/device-config/rest/src/test/java/org/opennms/features/deviceconfig/rest/impl/DefaultDeviceConfigRestServiceScheduleIT.java
> NMS-14287:DCB: Add Rest End point for deletion of Device Configs

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/activemq-queue-graph.properties
I missed an important ActiveMQ metric in my previous updates to this datacollection and am now rectifying that oversight. …
> NMS-14556: Include the ActiveMQ Queue Size metric

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/events/event-advanced-search.adoc
- opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmUtil.java
- opennms-webapp/src/main/java/org/opennms/web/controller/event/EventController.java
- opennms-webapp/src/main/java/org/opennms/web/event/EventUtil.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeDescriptionSubstringFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeEventTextFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeIPAddrLikeFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeLogMessageSubstringFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/NegativeNodeNameLikeFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/ServiceOrFilter.java
- opennms-webapp/src/main/java/org/opennms/web/event/filter/SeverityOrFilter.java
- opennms-webapp/src/main/java/org/opennms/web/filter/FilterUtil.java
- opennms-webapp/src/main/java/org/opennms/web/tags/filters/AbstractFilterCallback.java
- opennms-webapp/src/main/java/org/opennms/web/utils/filter/CheckboxFilterUtils.java
- opennms-webapp/src/main/java/org/opennms/web/utils/filter/FilterTokenizeUtils.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
- opennms-webapp/src/main/webapp/includes/event-advquerypanel.jsp
- smoke-test/src/test/java/org/opennms/smoketest/EventsPageIT.java
Fixing smoke test from reverting.
Related PR: https://github.com/OpenNMS/opennms/pull/5063
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14476
> NMS-14476: Negate search terms in event advanced search - fixing smoke test from revert

- features/flows/classification/engine/api/src/main/java/org/opennms/netmgt/flows/classification/ClassificationEngine.java
- features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/AsyncReloadingClassificationEngine.java
- features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/DefaultClassificationEngine.java
- features/flows/classification/engine/impl/src/main/java/org/opennms/netmgt/flows/classification/internal/TimingClassificationEngine.java
- features/flows/classification/engine/impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/classification/engine/impl/src/test/java/org/opennms/netmgt/flows/classification/internal/AsyncReloadClassificationEngineTest.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/FlowThresholding.java
- features/flows/elastic/src/main/java/org/opennms/netmgt/flows/elastic/thresholding/IndexKey.java
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14429
> NMS-14429: Handling flow applications without traffic

- opennms-container/launch_apt_server.sh
* Increase timeout count and tweak output messages
* creating a timeout variable
Back porting this work into release-30.x
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14336
> NMS-14336 CircleCI : Intermittent failures in horizon-deb-build (#4759)

- protocols/xml/src/main/java/org/opennms/protocols/json/collector/AbstractJsonCollectionHandler.java
- protocols/xml/src/test/java/org/opennms/protocols/json/collector/NMS14559IT.java
- protocols/xml/src/test/resources/NMS-14559-xml-datacollection-config.xml
- protocols/xml/src/test/resources/NMS-14559.json
* JIRA: https://issues.opennms.org/browse/NMS-14559
> NMS-14559: Fixed JSON handler to also respect mappings

- docs/modules/operation/pages/alarm-correlation/situation-feedback.adoc
- docs/modules/operation/pages/events/sources/eif-adapter.adoc
- docs/modules/operation/pages/events/sources/kafka.adoc
- docs/modules/operation/pages/kafka-producer/enable-kafka.adoc
- docs/modules/reference/pages/configuration/sentinel-features.adoc
- docs/modules/reference/pages/telemetryd/protocols/bmp.adoc
> NMS-14566: Features should go in featuresBoot.d (docs)

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-event-graph.properties
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14554
> NMS-14554: Datacollection for Eventd JMX metrics

- opennms-base-assembly/src/main/filtered/etc/jdbc-datacollection-config.xml
> NMS-14571: Fix outdated MySQL / MariaDB JDBC collection

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/deployment/pages/core/install-jdbc-driver.adoc
- docs/modules/deployment/pages/minion/installing-jdbc-driver.adoc
- docs/modules/reference/pages/performance-data-collection/collectors/jdbc.adoc
- Edited deployment/core/getting-started.adoc
- Documented installation steps for JDBC driver on Core
- Added entry to deployment/nav.adoc
Opening as a draft PR first for feedback on paths and commands; these were copied directly from the Minion instructions for installing a JDBC driver.
Don't worry if this sounds …
> NMS-14455: Install JDBC Driver on Core

- opennms-base-assembly/src/main/filtered/etc/jdbc-datacollection-config.xml
Should fix this failure - https://app.circleci.com/pipelines/github/OpenNMS/opennms/22323/workflows/b2afad43-a5c0-48e6-afc9-687c70e88aad/jobs/164475
* **If this code is likely to affect the UI, did you name your branch with `-smoke` …
> NMS-14571 again: s/COUNTER/counter/g && s/GAUGE/gauge/g to make the tests happy

- docs/modules/deployment/pages/upgrade/rhel/up-rhel.adoc
> fix spaces

- docs/modules/reference/pages/ticketing/ticketer/jira.adoc
Note: this PR was created because of issues with the original NMS-14447 branch. The previous PR (https://github.com/OpenNMS/opennms/pull/5118) has been closed.
------
Copy-pasted changes from original NMS-14447 branch.
- Updated and reformatted reference/ticketing/ticketer/jira.adoc
- Added requested lines to document
4. once you've created this PR, please link to it in a comment in the JIRA …
> NMS-14447: Update Jira ticketing plugin doc

- docs/modules/operation/pages/provisioning/introduction.adoc
- Updated and formatted operation/provisioning/introduction.adoc
- Updated XSD URL
* If this is a new or updated …
> NMS-14150: Update XSD URL

- docs/modules/reference/pages/configuration/tuning-kafka.adoc
> docs for minon kafka tuning

- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/jvm-graph.properties
This change may have been introduced when we moved past JDK 8.  Did not verify beyond these names being correct for current versions of JDK 11.
Tagged for `foundation-2019` because the release notes  for M2019 state "We recommend the latest version of OpenJDK 11" and in that case, these metrics are broken all the way back.  Let me know if that's not okay.
4. once you've created this PR, please …
> NMS-14041: correct G1 perm/eden/old/survivor mbean names in jmx collection

- docs/modules/deployment/pages/core/docker/core.adoc
- docs/modules/deployment/pages/core/system-requirements.adoc
- docs/modules/deployment/pages/minion/docker/minion.adoc
- docs/modules/operation/pages/admin/webui/jmx-config-generator/cli.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/event-translator.adoc
> NMS-8566: Event Translator Daemon Documentation

- docs/modules/reference/pages/service-assurance/introduction.adoc
> NMS-14423: Document allowed characters in service-names

- docs/modules/deployment/pages/core/getting-started.adoc
NMS-13057: Update PG installation documentation to use SCRAM - created new branch and PR based on work by Marcel due to rebase issue. …
> NMS-13057: Update PG installation documentation to use SCRAM

- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14490
> NMS-14490: Make ignore list mutable

- core/web-assets/src/main/assets/js/apps/onms-interfaces/onms-interfaces-config/index.js
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsSnmpInterface.java
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/MatchingIpInterfacePolicy.java
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/MatchingSnmpInterfacePolicy.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/CollectionPolicyTest.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14576
> NMS-14576: Add new 'P' prefix to m_collect field

- .circleci/main/jobs/tarball-assembly-only.yml
- .circleci/main/jobs/tarball-assembly.yml
Changing tarball job to use `./assemble.pl` command
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13821
> replace compile with assemble script in tarball job

- smoke-test/src/main/java/org/opennms/smoketest/utils/RestClient.java
- smoke-test/src/test/java/org/opennms/smoketest/UsageStatisticsIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14627
> NMS-14627: Added smoke-test for KPIs

- docs/modules/reference/pages/daemons/daemon-config-files/enlinkd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
- Updated reference/daemons/daemon-config-files/provisiond.adoc
- Minor formatting update for reference/daemons/daemon-config-files/enlinkd.adoc
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it …
> NMS-8569: Provisiond doc

- .circleci/pyscripts/process_generate.py
Enable OCI_ detection in what we want to build.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14662
> NMS-14662 Dynamic Yaml Generation, Enable running OCI jobs when changes are detected

- .circleci/pyscripts/process_generate.py
Fix a bug in the if statement
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14662
> Fix a bug delivered in NMS-14662

- opennms-config-model/src/main/java/org/opennms/netmgt/config/users/Contact.java
- opennms-config-model/src/main/java/org/opennms/netmgt/config/users/User.java
- opennms-webapp/src/main/java/org/opennms/web/admin/discovery/ActionDiscoveryServlet.java
- opennms-webapp/src/main/java/org/opennms/web/admin/roles/AdminRoleServlet.java
- opennms-webapp/src/main/webapp/admin/discovery/edit-config.jsp
- opennms-webapp/src/main/webapp/admin/discovery/edit-scan.jsp
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14591
> NMS-14591: Fix stored XSS issues

- docs/modules/reference/pages/service-assurance/monitors/JDBCQueryMonitor.adoc
* JIRA (Issue Tracker): Not created
> Fix docs format for JDBCQueryMonitor

- container/features/pom.xml
- container/features/src/main/resources/features.xml
- container/karaf/src/main/filtered-resources/etc/custom.properties
- features/datachoices/pom.xml
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
- features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
Have been added a counter for failed and successful device config backups that are stored in the database.
These counters were added to the reporting page Data Choices
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14580
> NMS-14580: Cumulative config count for DCB feature

- .circleci/main/@main.yml
- container/shared/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/MinionProfile.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/NMS14655_IT.java
* JIRA: https://issues.opennms.org/browse/NMS-14655
> NMS-14655: Removed scv-jceks-impl from featuresBoot 

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
- opennms-webapp/src/main/webapp/element/interface.jsp
- opennms-webapp/src/main/webapp/element/snmpinterface.jsp
- opennms-webapp/src/main/webapp/hardware/list.jsp
* JIRA: https://issues.opennms.org/browse/NMS-14657
> NMS-14657: Escaping some resource and node labels

- docs/modules/development/pages/rest/config_management.adoc
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14671
> NMS 14671 Add adoc documentation for partial configuration update

- bin/functions.pl
The way I did it previously with system("...") didn't work, and my testing didn't catch it. :(
We can't easily adjust the ulimit in Perl in a way that is inherited by children. See: https://stackoverflow.com/questions/2226329
So, we just fail and tell the user how to fix it.
Don't worry if this sounds like a lot, we …
> Fix ulimit check

- docs/modules/operation/pages/flows/setup.adoc
> NMS-14749: note listener on 9999 in flow docs

- container/karaf/src/main/filtered-resources/etc/custom.properties
* JIRA: https://issues.opennms.org/browse/NMS-14747
> NMS-14747: Added javax.mail packages to custom.properties

- docs/modules/deployment/pages/upgrade/backup/debian-ubuntu/backup-debian-ubuntu.adoc
> Fix incorrect doc command

- docs/modules/operation/pages/admin/webui/grafana-dashboard-box.adoc
* JIRA (Issue Tracker): No JIRA created
> Update docs for grafana-box settings filename

- opennms-dao/src/main/java/org/opennms/netmgt/dao/jaxb/DefaultProvisiondConfigurationDao.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/jaxb/callback/ProvisiondConfigurationValidationCallback.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/jaxb/callback/ProvisiondConfigurationValidationCallbackTest.java
* JIRA; https://issues.opennms.org/projects/NMS/issues/NMS-14752
> NMS-14752 Check names of requsition-def's in provisiond-configuration

- docs/modules/operation/pages/events/event-tokens.adoc
- docs/modules/operation/pages/notifications/commands.adoc
> Fix docs for notification command table formatting

- docs/modules/reference/pages/provisioning/adapters/snmp-metadata.adoc
- integrations/opennms-snmp-metadata-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpMetadataProvisioningAdapter.java
- opennms-base-assembly/src/main/filtered/etc/snmp-metadata-adapter-configuration.xml
- opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfig.java
- opennms-config-model/src/main/resources/xsds/snmp-metadata-adapter-configuration.xsd
- opennms-config-model/src/test/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfigTest.java
NMS-14729: Add new handling options for the snmp provisioning metadata adapter
* If this is a new or updated feature, …
> NMS-14729: Add new handling options for the snmp provisioning metadata adapter

- opennms-webapp/src/main/webapp/WEB-INF/jsp/siteStatus.jsp
* JIRA: https://issues.opennms.org/browse/NMS-14713
* JIRA: https://issues.opennms.org/browse/NMS-14714
> NMS-14713: Fixed XSS issue

- core/lib/src/main/java/org/opennms/core/utils/InetAddressUtils.java
- core/lib/src/test/java/org/opennms/core/utils/InetAddressUtilsTest.java
Added methods and test to identify subnetworks using ip address and netmask
Created suitable tests
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14744
> NMS-14774 Add network/netmask tools to InetAddressUtils

- docs/modules/reference/pages/daemons/daemon-config-files/trapd.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/No Jira
> Fix broken doc links

- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/detail.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/index.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/event/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/notification/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
- opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp
- opennms-webapp/src/main/webapp/admin/index.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
- opennms-webapp/src/main/webapp/asset/index.jsp
- opennms-webapp/src/main/webapp/element/index.jsp
- opennms-webapp/src/main/webapp/element/rescan.jsp
- opennms-webapp/src/main/webapp/errors/alarmidnotfound.jsp
- opennms-webapp/src/main/webapp/errors/eventidnotfound.jsp
- opennms-webapp/src/main/webapp/includes/alarm-advquerypanel.jsp
- opennms-webapp/src/main/webapp/includes/alarm-querypanel.jsp
- opennms-webapp/src/main/webapp/includes/event-advquerypanel.jsp
- opennms-webapp/src/main/webapp/includes/event-querypanel.jsp
- opennms-webapp/src/main/webapp/includes/eventlist.jsp
- opennms-webapp/src/main/webapp/notification/index.jsp
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java
- smoke-test/src/test/java/org/opennms/smoketest/SearchPageIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14716
I added CSRF handling for the mentioned pages and included the ones that had CSRF enabled before. The logout page now requires POST even it is not requiring a CSRF token. Please test everything thoroughly!
> NMS-14716: Added CSRF handling

- docs/modules/development/pages/rest/requisitions.adoc
- docs/modules/development/pages/rest/rest-api.adoc
- Update `development/rest/requisitions.adoc`, `/rest-api.adoc` …
> NMS-13938: Update Requisitions Docs

- opennms-webapp/src/main/webapp/WEB-INF/web.xml
* JIRA: https://issues.opennms.org/browse/NMS-14717
> NMS-14717: Added HttpOnly flag

- features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/CollectionSetBuilder.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/collection/KafkaPersisterIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14740
> NMS-14740: Fixed NPE

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/VmwareImporterTest.java
* JIRA: https://issues.opennms.org/browse/NMS-14450
> NMS-14450: Fixed NPE

- core/web-assets/src/main/assets/js/lib/onms-http/index.js
- smoke-test/src/test/java/org/opennms/smoketest/AngularLoginRedirectIT.java
- smoke-test/src/test/java/org/opennms/smoketest/SearchPageIT.java
Fix-up for the various security patches that got merged upwards and broke foundation-2021.
Feel free to merge as soon CircleCI went green.
> Fixed smoke-tests in foundation-2021

- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14807
> NMS-14807: Cortex plugin doc update

- opennms-base-assembly/src/main/filtered/etc/events/opennms.internal.events.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14799
> NMS-14799: Update passiveServiceStatus event description

- opennms-container/minion/minion-config-schema.yml.in
> CLOUD-2563: Adjust minion schema for Horizon 30.x

- core/criteria/src/main/java/org/opennms/core/criteria/Criteria.java
- core/criteria/src/main/java/org/opennms/core/criteria/CriteriaBuilder.java
- core/criteria/src/main/java/org/opennms/core/criteria/restrictions/AllRestriction.java
- core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restriction.java
- core/criteria/src/main/java/org/opennms/core/criteria/restrictions/Restrictions.java
- docs/modules/operation/pages/admin/webui/opsboard/criteria-builder.adoc
- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/AbstractDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/EventDaoIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14698
> NMS-14698: Back-port multi-constraint work

- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/DefaultForeignSourceService.java
NMS-14814: Fix NPE in opennms-provision-persistence module …
> NMS-14814: Fix NPE in opennms-provision-persistence module

- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14469
> NMS-14469: Set metric value

- .circleci/config.yml
- .circleci/pyscripts/generate_main.py
- .circleci/pyscripts/library/libgit.py
- .circleci/pyscripts/library/libprocess.py
- .circleci/pyscripts/process_generate.py
Back-porting `NMS-14810: Dynamic Yaml Generation, code and output clean up (#5349)` to release-30.x
* code clean up
* Update config file
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14846
> Backport NMS-14810: Dynamic Yaml Generation, code and output clean up (#5349)

- opennms-base-assembly/src/main/filtered/etc/events/opennms.collectd.events.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14744
> NMS-14744: Update dataCollectionFailed reduction key

- core/daemon/src/main/java/org/opennms/netmgt/scheduler/Schedule.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableContainer.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableElement.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableService.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/PollerIT.java
* JIRA: https://issues.opennms.org/browse/NMS-14695
> NMS-14695: do not create events when interface is covered by a scheduled outage

- opennms-webapp/src/main/java/org/opennms/web/filter/HttpsRewriteFilter.java
* JIRA: https://issues.opennms.org/browse/NMS-14805
> NMS-14805: changed redirect logic in HttpsRewriteFilter

- docs/modules/deployment/pages/time-series-storage/timeseries/configuration.adoc
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-315
> DC-315: add doc for offheap queue

- tools/packages/minion/minion.spec
- tools/packages/sentinel/sentinel.spec
https://issues.opennms.org/browse/NMS-13864
> NMS-13864: Package description for Minion and Sentinel reference the old Wiki

- core/lib/src/main/java/org/opennms/core/tracker/RequestTracker.java
Fixed spelling error
https://issues.opennms.org/browse/NMS-14757
> NMS-14757: Fixed spelling error

- core/web-assets/src/main/assets/js/apps/onms-geoservice/views/config/google.html
- core/web-assets/src/main/assets/js/apps/onms-geoservice/views/config/mapquest.html
- core/web-assets/src/main/assets/js/apps/onms-geoservice/views/config/nominatim.html
Changed width of toggle switch which was truncating Yes to Ye
https://issues.opennms.org/browse/NMS-14841
> jira/NMS-14841: Fix width of toggle switch which was truncating Yes

- opennms-webapp/src/main/java/org/opennms/web/account/selfService/NewPasswordActionServlet.java
- opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp
Its a small improvment of the ticket below which is already merged. I discussed this with Ben.
https://issues.opennms.org/browse/NMS-13981 …
> NMS-13981: Weak Password Policy

- docs/modules/deployment/pages/core/debian/install-core.adoc
- docs/modules/deployment/pages/core/ubuntu/install-core.adoc
- docs/modules/deployment/pages/minion/debian/install-minion.adoc
- docs/modules/deployment/pages/minion/ubuntu/install-minion.adoc
- docs/modules/deployment/pages/sentinel/runtime/debian/install-sentinel.adoc
- docs/modules/deployment/pages/sentinel/runtime/ubuntu/install-sentinel.adoc
Replace the apt-key deprecated way adding a GPG key for signed packages on a Debian package repository. Instead of adding the signing-key to the global apt repository, which is applied to any package for all repositories, we add a specific keyring file and use it just for repository described in the opennms.list file.
Instead of using the global trusted.gpg.d which is automatically used for any package in any repository, I've explicitly specified the key from /usr/share/keyrings/opennms.gpg just to the OpenNMS repository in the opennms.list file. It ties the key to a singular repository and fixes one of the original [security flaws in apt-key](https://blog.cloudflare.com/dont-use-apt-key/).
* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't …
> NMS-14760: Describe how to create a OpenNMS keyring for the Debian repository

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/RequisitionImport.java
* Jira: https://issues.opennms.org/browse/NMS-10469
> NMS-10469: Provisiond import errors don't appear as event reason

- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/critical-service.adoc
- docs/modules/operation/pages/quick-start/introduction.adoc
- Update `operation/quick-start/introduction.adoc`
- Update `deployment/core/getting-started.adoc`
- Update `operation/deep-dive/service-assurance/critical-service.adoc` (fixes asciidoctor warning)
* **If this code is likely to affect …
> NMS-14612: Quick Start - Overview

- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14945
> NMS-14945: Fix Cortex plugin docs

- features/enlinkd/adapters/common/src/main/java/org/opennms/netmgt/enlinkd/common/SchedulableNodeCollectorGroup.java
Fixed checking if collection has values
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14912
> NMS-14912 NoSuchElementException errors thrown by EnhancedLinkd

- opennms-container/horizon/Dockerfile
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/StackModel.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/TestContainerUtils.java
- smoke-test/src/test/java/org/opennms/smoketest/OpenShiftCompatIT.java
JIRA: https://issues.opennms.org/browse/NMS-13572
Changes to allow the Horizon container to run with a restricted profile in OpenShift
> NMS-13572: Add support for running the Horizon container in OpenShift

- features/timeseries/pom.xml
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/aggregation/NewtsConverterUtils.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersistOperationBuilder.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersistOperationBuilderTest.java
* JIRA (Issue Tracker): https://issues.opennms.org/browse/DC-371
> DC-371: Timeseries counters are being treated as gauges

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AlarmRestService.java
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14901
> jira/NMS-14901: Check alarm exists

- ui/src/components/Configuration/ConfigurationCronSelector.vue
- ui/src/components/Configuration/ConfigurationDrawer.vue
- ui/src/components/Configuration/ConfigurationEmptyTable.vue
- ui/src/components/Configuration/ProvisionDForm.vue
- ui/tests/configuration.test.ts
- ui/tests/utils.ts
FeatherSelect v0.10.17+ has issues being wrapped in an element which uses `transform`. Removed/replaced with `right` where needed.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14824
> NMS-14824: Fix broken transform with feather dropdowns

- core/test-api/rest/src/main/java/org/opennms/core/test/rest/AbstractSpringJerseyRestTestCase.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/README.adoc
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MonitoringLocationRestServiceIT.java
- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
NMS-14548: Fix for the limited location list, changes made in webapp and not rest api. No pagination at this point.
* JIRA (Issue Tracker): https://issues.opennms.org/browse/NMS-14548
> NMS-14548: Fix for the limited location list

- core/web-assets/src/main/assets/style/opennms-theme.scss
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java
- opennms-webapp/src/main/java/org/opennms/web/controller/NavBarController.java
- opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
- ui/src/components/Layout/Menubar.vue
Decorate items requiring Admin access in both 'classic' and 'new' UI menubars with a "cogs" icon.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14906
> NMS-14906: Decorate admin items in menubars

- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-gz.dcb
- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-set.dcb
- opennms-base-assembly/src/main/filtered/etc/examples/device-config/juniper-junos-config-txt.dcb
* JIRA: https://issues.opennms.org/browse/NMS-14939
> NMS-14939: Fixed Juniper DCB scripts

- opennms-base-assembly/src/main/resources/contrib/opennms.mib
> NMS-14955: Assign sysObjectID for Appliance Mini

- debian/control
- makedeb.sh
- makerpm.sh
- opennms-assemblies/minion/src/main/filtered/debian/control
- opennms-assemblies/sentinel/src/main/filtered/debian/control
- tools/packages/minion/minion.spec
- tools/packages/opennms/opennms.spec
- tools/packages/sentinel/sentinel.spec
Updating the RPM and DEB package dependences.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14920 and http://issues.opennms.org/browse/NMS-14892
> NMS-14920 and NMS-14892: Update RPM/DEB package dependencies

- .circleci/main/commands/executions/run-smoke-tests.yml
- smoke-test/pom.xml
- smoke-test/src/main/java/org/opennms/smoketest/containers/ElasticsearchContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/LocalOpenNMS.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractPage.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/StackModel.java
- smoke-test/src/main/java/org/opennms/smoketest/ui/framework/Toggle.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/OpenNMSImageNameSubstitutor.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/TestContainerUtils.java
- smoke-test/src/main/resources/testcontainers.properties
- smoke-test/src/test/java/org/opennms/smoketest/AngularLoginRedirectIT.java
- smoke-test/src/test/java/org/opennms/smoketest/BSMAdminIT.java
- smoke-test/src/test/java/org/opennms/smoketest/ClassificationRulePageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/DatabaseReportPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/GeocoderServiceConfigurationPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/GrafanaEndpointPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/IndexPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/JmxConfigurationGeneratorIT.java
- smoke-test/src/test/java/org/opennms/smoketest/MenuHeaderIT.java
- smoke-test/src/test/java/org/opennms/smoketest/OpenNMSSeleniumIT.java
- smoke-test/src/test/java/org/opennms/smoketest/ScheduledOutageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/TopologyIT.java
- smoke-test/src/test/java/org/opennms/smoketest/UiPageTest.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java
- smoke-test/src/test/resources/log4j2-test.xml
This is a replacement for #5444. but also upgrading Selenium to 4.6.0, now that it has been released and seleniarm-docker containers are also available.
This is one of these situations where “let me look into this one test failure” turned into “fix ten various things on a path to getting visibility into the original problem.” This should be review commit-by-commit.
Using native Docker images is pretty critical for the Selenium testing because testcontainers has a number of hard-coded timeouts. The timeouts combined with amd64 images that require QEMU emulation are completely unusable. Being able to use arm64 images on M1 macs is a requirement for anyone on that platform (read: me), hence working on the PR.
The versions of these Docker containers aren’t available for arm64:
1. …
> Feature smoke test improvements upgrade selenium

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/deployment/pages/time-series-storage/newts/introduction.adoc
- docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/rrdtool.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/time-series-storage.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/critical-service.adoc
- docs/modules/reference/pages/glossary.adoc
> NMS-14844: Documentation for Cloud Services Connector and Time Series DB

- docs/modules/operation/pages/deep-dive/events/perf-data.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/enlinkd.adoc
> fix doc build errors

- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/datacollection/opennms.appliance.xml
> NMS-14956: SNMP systemDef added for appliance products

- opennms-config/src/main/java/org/opennms/netmgt/config/WebSchedEntry.java
- opennms-webapp/src/main/java/org/opennms/web/admin/roles/AdminRoleServlet.java
Looks like this is part of a bigger issue. When default locale is not US, ENGLISH, ROOT SimpleDateFormat might have some parsing issues.
I fixed this particular case but I'll create a new jira for the rest of OpenNMS, since we use SimpleDateFoormat in several other places.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14739
> NMS-14739: Admin can't assign user to 'On-Call Role Schedule'

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ApplicationStatusRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/MenuRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/ProvisiondStatusRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/SnmpMetadataRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/api/EventRestApi.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/api/NodeLinkRestApi.java
https://issues.opennms.org/browse/NMS-14408
i cannot fix all issues but i can start with fixing some easy validation issues
please check
thanks, regards lars
* **If this code is likely to affect the UI, did you name your branch with …
> NMS-14408 OpenAPI Validation Errors

- opennms-full-assembly/pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/TimeseriesAPIIT.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14874
> NMS-14874: Add opennms-timeseries-api dependencies to system dir

- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14945
> NMS-14945: Cherry pick from develop to 31

- .circleci/main/commands/generic/generic.yml
- opennms-base-assembly/src/main/filtered/bin/generate-opennms-thread-dump
- opennms-base-assembly/src/main/filtered/bin/install
- opennms-base-assembly/src/main/filtered/bin/opennms
- opennms-base-assembly/src/main/filtered/bin/runjava
- opennms-base-assembly/src/main/filtered/bin/upgrade
- opennms-base-assembly/src/test/shell/spec/opennms.spec.sh
- opennms-container/horizon/Dockerfile
- opennms-container/horizon/Makefile
- opennms-container/horizon/container-fs/entrypoint.sh
- opennms-container/minion/Dockerfile
- opennms-container/minion/Makefile
- opennms-container/minion/container-fs/entrypoint.sh
- opennms-container/sentinel/Dockerfile
- opennms-container/sentinel/Makefile
- opennms-container/sentinel/assets/entrypoint.sh
This PR fixes how permissions are munged in the docker containers to make sure they don't end up creating extra (sizeable) layers.
It also contains a couple of changes I needed to pass the build that weren't necessarily related to this branch.
Don't worry if this sounds like a lot, we can help you get things set up …
> NMS-15006: fix layer size growth

- docs/modules/deployment/pages/core/docker/core.adoc
- docs/modules/deployment/pages/minion/docker/minion.adoc
> Fix doc variable for Docker image version

- .circleci/main/commands/generic/generic.yml
- opennms-container/horizon/Dockerfile
- opennms-container/horizon/Makefile
- opennms-container/minion/Dockerfile
- opennms-container/minion/Makefile
- opennms-container/sentinel/Dockerfile
- opennms-container/sentinel/Makefile
This also updates the JRE base package from jre-2.0.6 to jre-2.1.0.
The change we need is already in docker-base: https://github.com/OpenNMS/deploy-base/commit/44c95610357195ba026f07421e931707812262eb
However, its deploy failed: https://app.circleci.com/pipelines/github/OpenNMS/deploy-base
That job (or another job) needs to complete before this PR can be merged. If it's another job, this PR will need to be updated to reflect the new build number. This PR is marked as a draft until deploy-base is deployed.
2. update the JIRA link at the bottom of …
> NMS-14946: add vi-tiny and less in Docker containers

- opennms-webapp/src/main/webapp/errors/alarmidnotfound.jsp
https://issues.opennms.org/browse/NMS-14686
just a simple fix …
> NMS-14686 - Duplicated message when alarm is not found

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
* JIRA: https://issues.opennms.org/browse/NMS-14877
> NMS-14877: Fixed XSS in display of alarm reduction-key

- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java
JIRA: https://issues.opennms.org/browse/NMS-15042
> NMS-15042: Use a "read" lock instead of an "upgrade" lock

- opennms-container/horizon/container-fs/entrypoint.sh
- smoke-test/src/main/java/org/opennms/smoketest/containers/KarafContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/KarafShellUtils.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/RestHealthClient.java
- smoke-test/src/test/java/org/opennms/smoketest/minion/MinionSshIT.java
- smoke-test/src/test/java/org/opennms/smoketest/sentinel/SentinelSshIT.java
> Feature improve container debugging

- .circleci/scripts/lib.sh
- .circleci/scripts/publish-cloudsmith.sh
new set of tags:
* always set POM version (`31.0.0` for release, say, and `31.0.0-SNAPSHOT` for `release-XX.x` and develop)
* `master-*` sets `latest` to point to current version, just like RPM/deb packaging "stable" does for those, even if it disrupts things a bit
* `release-XX.x` always updates `release-candidate`
* `develop` always updates `bleeding`
4. once you've created this PR, please …
> NMS-14989: simplify docker tags for H31+

- opennms-webapp/src/main/java/org/opennms/web/admin/notification/DestinationWizardServlet.java
- opennms-webapp/src/main/webapp/admin/notification/chooseCommands.jsp
- opennms-webapp/src/main/webapp/admin/notification/chooseTargets.jsp
* JIRA: https://issues.opennms.org/browse/NMS-14845
> NMS-14845: Fixed Destination Path Wizard

- docs/modules/write-the-docs/pages/glossary.adoc
- Update `write-the-docs/glossary.adoc`
* If this is a new or updated feature, is there documentation for the new …
> NMS-14914: Add "admin" entry to Glossary

- opennms-container/horizon/Dockerfile
Small fix to the new docker containers to provide a backwards-compat symlink.
* If this is a new or updated feature, …
> NMS-14976: make sure /var/lib/opennms exists

- .circleci/main/executors.yml
- .circleci/main/jobs/build/build-docs.yml
- antora-playbook-local.yml
Update Antora and ui-build versions
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15088
> NMS-15088: Fix Antora version differences

- docs/modules/operation/pages/deep-dive/admin/webui/opsboard/introduction.adoc
- docs/modules/operation/pages/deep-dive/admin/webui/surveillance-view.adoc
- docs/modules/operation/pages/quick-start/visualize-data.adoc
- Update `operation/deep-dive/admin/webui/opsboard/introduction.adoc`
- Update `operation/deep-dive/admin/webui/surveillance-views.adoc`
- Update `operation/quick-start/visualize-data.adoc`
* **If this code is likely to affect the UI, …
> NMS-15029: Update QS Visualize chapter

- docs/modules/deployment/pages/upgrade/debian/up-debian.adoc
NMS-15087: Update Debian/Ubuntu Upgrade Instructions - removed "-get" from "apt-get" upgrade instructions and added a command to ensure correct repo gets used.
* **If this code is likely to affect the UI, did you name your branch with …
> NMS-15087: Update Debian/Ubuntu Upgrade Instructions

- opennms-container/horizon/Dockerfile
- opennms-container/horizon/Makefile
- opennms-container/minion/Dockerfile
- opennms-container/minion/Makefile
- opennms-container/sentinel/Dockerfile
- opennms-container/sentinel/Makefile
Originally merged to develop with #5459.
* If this is a new or updated feature, is there documentation for the new …
> Cherry-pick to release-31.x: Update to newer deploy-base container that has vim-tiny and less

- features/timeseries/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/KarafShell.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/KarafShellUtils.java
- smoke-test/src/test/java/org/opennms/smoketest/CortexTssPluginIT.java
- smoke-test/src/test/java/org/opennms/smoketest/CortexTssTimeseriesPluginIT.java
```
org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to find a matching constructor on class org.opennms.netmgt.timeseries.samplewrite.TimeseriesPersisterFactory for arguments [org.opennms.netmgt.timeseries.TimeseriesStorageManagerImpl@52d6a54b (class org.opennms.netmgt.timeseries.TimeseriesStorageManagerImpl), org.opennms.netmgt.timeseries.samplewrite.MetaTagDataLoader@7a278dcd (class org.opennms.netmgt.timeseries.samplewrite.MetaTagDataLoader), CacheConfig{name=timeseriesPersisterMetaTagCache, maximumSize=8192, expireAfterWrite=null, expireAfterRead=300 sec, recordStats=true} (class org.opennms.core.cache.CacheConfig), com.codahale.metrics.MetricRegistry@13c05952 (class com.codahale.metrics.MetricRegistry), …
```
> Add smoke tests for TSS parallel write feature

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpUtils.java
- core/snmp/proxy-rpc-impl/pom.xml
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpProxyRpcModule.java
- core/snmp/proxy-rpc-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/GenericSnmpDetectorFactory.java
- opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/SnmpDetector.java
- opennms-provision/opennms-detector-simple/src/main/java/org/opennms/netmgt/provision/detector/snmp/SnmpDetectorFactory.java
- opennms-provision/opennms-detector-simple/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15008
> NMS-15008: Get Minion SNMP community string from SCV

- opennms-base-assembly/src/main/filtered/etc/search-actions.xml
> NMS-15017: Remove reference to remote pollers

- features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvSetCommand.java
I added this recently to assist in local testing and figured it would be helpful. Attributes are currently configurable via the REST endpoint, but not this karaf command.
> Add karaf option to set attributes for SCV credentials

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/NMS14640Test.java
- features/mib-compiler/src/test/resources/CISCO-ENVMON-MIB.mib
- features/mib-compiler/src/test/resources/CISCO-SMI.mib
fix: treating 'bits' type as their root type octetstring
ref: https://www.webnms.com/snmp/help/snmpapi/snmpv3/using_mibs_in_applns/bits_datatype.html
* **If this code is likely to affect the UI, did you name your branch with `-smoke` …
> NMS-14640:Error compiling Cisco MIB

- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
- docs/modules/operation/pages/deep-dive/bsm/reduce-functions.adoc
NMS-15100: Change needed to a file name reference in documentation - updated the name of the file that needs to be moved as part of the TSDB set up.
NMS-14820: Documentation doesn't render asciimath properly: removed the 3 formulas that were listed. They did not add any value, and the work involved to add an asciimath renderer to the environment outweighed any benefit.
4. once you've created …
> NMS-15100: Change needed to a file name reference in documentation

- .circleci/config.yml
Enable pushing CircleCI build status to JIRA cloud
* If this is a new or updated feature, is there documentation for …
> NMS-15112: enable jira cloud notification

- .circleci/main/@main.yml
- .circleci/pyscripts/library/cci_components/workflow.py
This PR updates the `post-steps` JIRA work done for NMS-15112 to happen automatically as part of the dynamic config scripts.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke …
> NMS-15112: generate `post-steps` in all jobs in the workflow

- container/features/src/main/resources/features-sentinel.xml
- container/features/src/main/resources/features.xml
- docs/modules/operation/pages/deep-dive/flows/setup.adoc
- features/flows/itests/pom.xml
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/KafkaFlowForwarderIT.java
- features/flows/kafka-persistence/pom.xml
- features/flows/kafka-persistence/src/main/java/org/opennms/netmgt/flows/persistence/KafkaFlowForwarder.java
- features/flows/kafka-persistence/src/main/resources/OSGI-INF/blueprint/blueprint.xml
JIRA: https://issues.opennms.org/browse/NMS-15027
Allows JSON encoding to be enabled with:
```
config:edit org.opennms.features.flows.persistence.kafka
config:property-set useJson true
config:update
```
> NMS-15027: Add JSON support to the Kafka producer for flows

- docs/modules/operation/pages/quick-start/inventory.adoc
- docs/modules/operation/pages/quick-start/performance-data.adoc
- Update `operation/quick-start/inventory.adoc`, `/performance-data.adoc`
* If this is a new or updated feature, is …
> NMS-14992: Update Inventory and Performance Data Collection QS chapters

- .circleci/scripts/publish-azure.sh
- .circleci/scripts/publish-cloudsmith.sh
- .circleci/scripts/publish-dockerhub.sh
> change the tag to exclude opennms/ prefix

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java
- opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
- opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
Move 'Endpoints' menu item from 'Nodes' to 'Help  > API Documentation'.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15004
> NMS-15004: Move 'Endpoints' menu item under 'Help'

- features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerClientRpcModule.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/SnmpMonitor.java
- features/poller/monitors/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15008
> NMS-15008: Replace community string in poller requests

- features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
feat: After modifying HeartbeatConsumer.java and adding an SNMP detector and policy for minions. There was some extra data required to allow the monitoring to start OOTB.
fix: added minion detector service and monitor in poller-configuration.xml
Renamed detector and policy to something more specific
Don't worry if …
> NMS-14855: add minion detector and policy for appliance

- opennms-bootstrap/src/main/java/org/opennms/bootstrap/FilesystemPermissionValidator.java
Turns out the _validation_ code was just fine. But the top-level recursive walk didn't handle a failure that occurs from walking a skipped directory that happens to be unreadable.
This is easy to fix by checking if the failed walk is for a path it should not recurse into anyway.
Don't worry if this sounds like a …
> NMS-14919: fix top-level walker to handled excluded paths

- docs/modules/operation/pages/deep-dive/kafka-producer/configure-kafka.adoc
> Fix class name reference in Kafka Producer docs

- docs/modules/operation/pages/quick-start/baseline.adoc
- docs/modules/operation/pages/quick-start/beyond-qs.adoc
- docs/modules/operation/pages/quick-start/introduction.adoc
- docs/modules/operation/pages/quick-start/inventory.adoc
- docs/modules/operation/pages/quick-start/notification-config.adoc
- docs/modules/operation/pages/quick-start/notifications.adoc
- docs/modules/operation/pages/quick-start/performance-data.adoc
- docs/modules/operation/pages/quick-start/service-assurance.adoc
- docs/modules/operation/pages/quick-start/thresholding.adoc
- docs/modules/operation/pages/quick-start/users.adoc
- docs/modules/operation/pages/quick-start/visualize-data.adoc
- Update `operation/quick-start/baseline.adoc`, `/beyond-qs.adoc`, `/introduction.adoc`, `/inventory.adoc`, `/notification-config.adoc`, `/notifications.adoc`, `/performance-data.adoc`, `/service-assurance.adoc`, `/thresholding.adoc`, `/users.adoc`, `/visualize-data.adoc`
Don't worry if this sounds like a lot, we …
> NMS-15106: Update Quick Start style elements

- opennms-services/src/main/java/org/opennms/netmgt/notifd/BroadcastEventProcessor.java
* JIRA: https://opennms.atlassian.net/browse/NMS-13020
> NMS-13020: Added meta-data handling for 'RESOLVED:' notifications

- opennms-webapp/src/main/webapp/WEB-INF/web.xml
- smoke-test/src/test/java/org/opennms/smoketest/WebappIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-14937
> NMS-14937: Set SameSite to Strict for JSESSIONID

- opennms-webapp/src/main/webapp/admin/notification/noticeWizard/buildPathOutage.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-14934
> NMS-14934: Disable autocompletion

- core/test-api/xml/src/main/java/org/opennms/core/test/xml/XmlTest.java
- core/xml/src/main/java/org/opennms/core/xml/JaxbUtils.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/ValidatingMessageBodyReader.java
See the [OWASP cheat sheet](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#spring-framework-mvcoxm-xxe-vulnerabilities) on XEE prevention.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/${JIRA-ISSUE-NUMBER}
> NMS-14988: Set additional entity expansion options

- core/schema/src/main/liquibase/31.0.2/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- core/web-assets/src/main/assets/js/apps/onms-elementList/minion-elementList/index.js
- core/web-assets/src/main/assets/js/apps/onms-elementList/minion-elementList/main.html
- features/minion/heartbeat/common/src/main/java/org/opennms/minion/heartbeat/common/MinionIdentityDTO.java
- features/minion/heartbeat/consumer/src/main/java/org/opennms/minion/heartbeat/consumer/HeartbeatConsumer.java
- features/minion/heartbeat/producer/pom.xml
- features/minion/heartbeat/producer/src/main/java/org/opennms/minion/heartbeat/producer/HeartbeatProducer.java
- opennms-model/src/main/java/org/opennms/netmgt/model/minion/OnmsMinion.java
feat: added a version field to monitoringsystems table to allow keep track of current minion version
added version field to OnmsMinion
added version field to  MinionIdentityDTO
updated HeartbeatProducer to include Minion version in MinionIdentityDTO
updated HeartbeatConsumer to persist Minion version received from Minion (MinionIdentityDTO)
created changelog in liquibase for database change
added version in webapp   admin / managed minions
3. prefix your …
> NMS-14493: Include Minion version on "Manage Minions" page

- features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/scv/SecureCredentialsVaultImpl.java
- features/scv/api/src/main/java/org/opennms/features/scv/api/SecureCredentialsVault.java
- features/scv/dominion-grpc-impl/src/main/java/org/opennms/features/scv/dominion/grpc/DominionSecureCredentialsVault.java
- features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
- features/scv/rest/src/main/java/org/opennms/features/scv/rest/DefaultScvRestService.java
- features/scv/rest/src/main/java/org/opennms/features/scv/rest/ScvRestService.java
- features/scv/scvcli/src/main/java/org/opennms/features/scv/cli/ScvCli.java
- features/scv/scvcli/src/main/java/org/opennms/features/scv/cli/commands/DeleteCommand.java
- features/scv/shell/src/main/java/org/opennms/features/scv/shell/ScvDeleteCommand.java
- pom.xml
Depends on https://github.com/OpenNMS/opennms-integration-api/pull/76
* JIRA (Issue Tracker): http://issues.opennms.org/browse/OIA-52
>  OIA-52: Implement deletion of SCV entries 

- docs/modules/deployment/pages/core/getting-started.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-15011
> NMS-15011: Fixed scvcli commands

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java
- opennms-webapp/src/main/webapp/login.jsp
- ui/src/components/Layout/Menubar.vue
There was an issue with the new Vue menubar when clicking 'Log Out', resulting in an ugly 404 page and not actually logging out. Legacy menubar actually does a form POST to `j_spring_security_logout`, Vue Menubar was doing a GET. Updated Vue Menubar to have POST behavior.
Also fixed a small null reference issue in `login.jsp`.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15119
> NMS-15119: Logout issue with Vue Menubar

- core/schema/src/main/java/org/opennms/core/schema/Migrator.java
- docs/antora.yml
- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/releasenotes/pages/whatsnew.adoc
* update max PostgreSQL version in the migrator to allow 15.x
* PostgreSQL 15, by default, does not allow new (even super) users to modify the public schema; add code to GRANT access to the `opennms` user (I tested, and this is backwards-compatible to 10)
* update documentation references to include 15 where applicable
4. once you've created this PR, please link to it in a comment in the JIRA …
> NMS-15151: add support for PostgreSQL 15

- opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15044
> NMS-15044: Incorrect labels on OpenNMS-JMX collection resource types

- core/web-assets/src/main/assets/js/apps/onms-interfaces/onms-interfaces-config/index.js
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsSnmpInterface.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15117
[NMS-15117]: https://opennms.atlassian.net/browse/NMS-15117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NMS-15117: Fix conditional statement and js syntax

- docs/modules/operation/pages/deep-dive/flows/introduction.adoc
- Update `operation/deep-dive/flows/introduction.adoc`
* If this is a new or updated feature, is there documentation …
> NMS-15158: Add flow table

- docs/antora.yml
- docs/modules/deployment/pages/core/centos-rhel9/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel9/postgresql.adoc
- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/deployment/pages/core/system-requirements.adoc
- docs/modules/deployment/pages/minion/install.adoc
- docs/modules/deployment/pages/minion/introduction.adoc
- docs/modules/deployment/pages/minion/system-requirements.adoc
- docs/modules/deployment/pages/repos/rhel-centos/horizon-rhel9.adoc
- docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel9.adoc
- docs/modules/deployment/pages/sentinel/runtime/centos-rhel9/install-sentinel.adoc
- docs/modules/deployment/pages/sentinel/runtime/install.adoc
NMS-15147: Update docs to include RHEL 9 Install suggestions: added RHEL tab install instructions for core postgresql and core set up, Minion, and Sentinel. Added RHEL9 variable, and updated system requirements to include RHEL 9 as a supported OS.
Don't worry if this sounds like a lot, we can help you get things set …
> NMS-15147: Update docs to include RHEL 9 Install instructions

- opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14933
> NMS-14933 Prevent resubmission of editoutage.jsp

- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- features/bsm/service/impl/src/test/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachineIT.java
- features/bsm/test-util/src/main/java/org/opennms/netmgt/bsm/test/hierarchies/IpServiceAggregationHierarchy.java
when restarting or reloading bsmd.
Defer and reduce update events until the graph is completely processed.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15124
> NMS-15124: Fix possible mismatch between business service and alarm state

- docs/modules/operation/pages/deep-dive/topology/enlinkd/introduction.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/layer-2-discovery.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/layer-3-discovery.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/layer-3/ospf-discovery.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/shell/introduction.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/enlinkd.adoc
Added command to Reload Enlinkd configuration
Added command to run Enlinkd  bridge topology discovery
Added Command to Realod Enlinkd daemon
Added Command to run and persist SnmpCollection based on node and protocol
Added Command to Walk Enlinkd Snmp Collection:
LldpLocalGroupTracker
LldpLocalTableTracke
LldpRemTableTracker
MtxrNeighborTableTracker
TimeTetraLldpRemTableTracker
OspfGeneralGroup
OspfAreaTable
OspfIfTable
OspfNbrTable
IsisSysObjectGroup
IsisCircTable
IsisISAdjTable
IpNetToMediaTable
Dot1dStpPortTable
Dot1dTpFdbTable
Dot1qTpFdbTable
CdpGlobalGroup
CdpCacheTable
CiscoVtp
CiscoVtpVlanTable
Dot1dbase 
Dot1dPortTable
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-14909
> NMS-14909: Provide a method to verify topology capability

- opennms-webapp/src/main/webapp/admin/snmpConfig.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15126
> NMS-15126: Escaping community strings in snmpConfig.jsp

- docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/path-outages.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15218
> NMS-15218: Update path outage docs

- opennms-jetty/src/main/java/org/opennms/netmgt/jetty/JettyServer.java
- opennms-jetty/src/main/java/org/opennms/netmgt/jetty/OpenNMSWebAppProvider.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSProfile.java
- smoke-test/src/test/java/org/opennms/smoketest/BrokenWebappIT.java
> Try to make Jetty fail fast and bubble up errors to vmmgr

- docs/modules/operation/nav.adoc
NMS-15266: Update docs TOC to include missing notification commands file - added commands.adoc file to the nav in the operation/deep-dive/notifications section.
* **If this code is likely to affect the UI, did you name your branch …
> NMS-15266: Update docs TOC to include missing notification commands file

- docs/modules/operation/pages/deep-dive/device-config-backup/configuration.adoc
- docs/modules/reference/pages/telemetryd/protocols/netflow9.adoc
> NMS-15144:Link on Netflow9 to main Netflow doc is broken

- opennms-doc/releasenotes/src/asciidoc/releasenotes/whatsnew.adoc
- opennms-provision/opennms-detector-generic/src/main/java/org/opennms/netmgt/provision/detector/generic/client/GpClient.java
- opennms-provision/opennms-detector-generic/src/test/java/org/opennms/netmgt/provision/detector/generic/GpDetectorTest.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/ScriptUtil.java
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/policies/ScriptPolicy.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/policies/ScriptPolicyTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-14878
> NMS-14878: Limit script file locations for GpDetector and ScriptPolicy

- docs/modules/operation/pages/deep-dive/provisioning/auto-discovery.adoc
- docs/modules/operation/pages/deep-dive/provisioning/directed-discovery.adoc
- docs/modules/operation/pages/deep-dive/provisioning/foreign-source.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/application-perspective-monitoring/introduction.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/configuration.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/critical-service.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/downtime-model.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/introduction.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/path-outages.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/polling-packages.adoc
- docs/modules/operation/pages/deep-dive/thresholds/datasource.adoc
- docs/modules/operation/pages/deep-dive/thresholds/thresholding.adoc
- docs/modules/operation/pages/deep-dive/user-management/pre-authentication.adoc
- docs/modules/operation/pages/deep-dive/user-management/security-roles.adoc
- docs/modules/operation/pages/deep-dive/user-management/user-oncall.adoc
- docs/modules/operation/pages/quick-start/inventory.adoc
- docs/modules/operation/pages/quick-start/notifications.adoc
- docs/modules/operation/pages/quick-start/service-assurance.adoc
- docs/modules/operation/pages/quick-start/thresholding.adoc
- Update `operation/deep-dive/provisioning/auto-discovery.adoc`, `/directed-discovery.adoc`, `/foreign-source.adoc`
- Update `operation/deep-dive/service-assurance/application-perspective-monitoring/introduction.adoc`
- Update `operation/deep-dive/service-assurance/critical-service.adoc`, `/downtime-model.adoc`, `/introduction.adoc`, `/path-outages.adoc`, `/polling-packages.adoc`, `/configuration.adoc`
- Update `operation/deep-dive/thresholds/datasource.adoc`, `/thresholding.adoc`
- Update `operation/deep-dive/user-management/pre-authentication.adoc`, `/security-roles.adoc`, `/user-oncall.adoc`
- Update `operation/quick-start/inventory.adoc`, `/notifications.adoc`, `/service-assurance.adoc`, `/thresholding.adoc`
* Please [make an issue in the OpenNMS issue …
> NMS-14632: Add alt text to Operation (pt. 1)

- .circleci/main/aliases/general.yml
- .circleci/main/jobs/oci/horizon-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/horizon-image-single-arch.yml
- .circleci/main/jobs/oci/minion-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/minion-image-single-arch.yml
- .circleci/main/jobs/oci/sentinel-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/sentinel-image-single-arch.yml
Cleaning up duplicate properties such as:
* DOCKER_CLI_EXPERIMENTAL
* DOCKER_IMAGE_VERSION
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13583
> NMS-13583: remove image related defaults from Docker container makefile

- core/web-assets/src/main/assets/style/opennms-theme.scss
* JIRA: https://opennms.atlassian.net/browse/NMS-15172
> NMS-15172: Removed fixed width from notification badge style

- docs/modules/operation/pages/deep-dive/events/event-definition.adoc
- docs/modules/reference/pages/glossary.adoc
NMS-14658: Missing reference to logmsg dest component - added information about the dest component to the events definition documentation. …
> NMS-14658: Missing reference to logmsg dest component

- .circleci/config.yml
This is a backport of #5682 to foundation-2022.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15271
> Backport fix for integration test reports to foundation-2022

- .circleci/main/@main.yml
- .circleci/main/aliases/general.yml
- .circleci/main/jobs/oci/horizon-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/horizon-image-single-arch.yml
- .circleci/main/jobs/oci/minion-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/minion-image-single-arch.yml
- .circleci/main/jobs/oci/sentinel-image-single-arch-linux-amd64.yml
- .circleci/main/jobs/oci/sentinel-image-single-arch.yml
Small code clean up to remove unused references. 
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-13583
> NMS-13583:  remove image related defaults from Docker container makefile (Part 2)

- container/features/src/main/resources/features-core.xml
This PR backports Karaf 4.3.9's sshd feature to `foundation-2022`, so that `sshd-sftp` gets updated to a no-known-CVEs version.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke …
> NMS-15195: upgrade sshd to match Karaf 4.3.9

- container/features/src/main/resources/features.xml
- pom.xml
This PR bumps the jolokia client to a newer version
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15068
> NMS-15068: bump jolokia-client-java to latest version

- docs/modules/operation/pages/deep-dive/topology/enlinkd/layer-2-discovery.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/layer-3-discovery.adoc
- docs/modules/operation/pages/deep-dive/topology/enlinkd/shell/introduction.adoc
- features/enlinkd/shell/src/main/java/org/opennms/features/enlinkd/shell/DeleteTopologyCommand.java
Updated topology and enlinkd shell commands documentation
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15180
> NMS-15180: Review Enhanced Linkd and Topology Documentation

- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactory.java
- opennms-webapp/src/main/java/org/opennms/web/element/NetworkElementFactoryInterface.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-14578
> NMS-14578: Show resolving UEIs in alarm/detail.jsp

- core/tasks/src/main/java/org/opennms/core/tasks/DefaultTaskCoordinator.java
- opennms-base-assembly/src/main/filtered/etc/jmx-datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/resource-types.d/jmx-resource.xml
- opennms-base-assembly/src/main/filtered/etc/service-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-graph.properties
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-provisiond-graph.properties
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ForceRescanScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/MonitorHolder.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NewSuspectScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/TimeTrackerOverallMonitor.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/operations/ProvisionOverallMonitor.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/MonitorHolderTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/TimeTrackingMonitorTest.java
- opennms-services/pom.xml
- opennms-services/src/main/java/org/opennms/netmgt/provisiond/jmx/Provisiond.java
- opennms-services/src/main/java/org/opennms/netmgt/provisiond/jmx/ProvisiondMBean.java
Implemented a Provisiond jmx service to expose metrics for Provisiond and data collection and graph 
The goal is expose Thread pool metrics and Node collection metrics to be used in performance reports.
I tried to leverage Provisioner as the SpringServiceDaemon used in AbstractSpringContextJmxServiceDaemon and access this way the ExecutorService(s) thread pools for Scan, Rescan, Import and Write as defined in [applicationContext-provisiond.xml](https://github.com/OpenNMS/opennms/blob/543ab8347be058d709dd0370b209e1bc753e4b35/opennms-provision/opennms-provisiond/src/main/resources/META-INF/opennms/applicationContext-provisiond.xml)
Also Expose metrics about Provisioning time Min/Max and Avg for Node Provisioning.
With @dino2gnt collaboration added the following:
Graph definitions for …
> NMS-15018: Data collection and graph definitions for provisiond performance

- features/enlinkd/adapters/common/src/main/java/org/opennms/netmgt/enlinkd/common/TopologyUpdater.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyFactory.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/main/java/org/opennms/features/topology/plugins/topo/linkd/internal/LinkdTopologyProvider.java
Fixed using Protocol from LinkdTopologyProvider
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15131
> NMS-15131: DefaultFocus is not Working

- opennms-web-api/src/main/java/org/opennms/web/api/Util.java
- opennms-webapp/src/test/java/org/opennms/web/outage/filter/WebOutageRepositoryFilterIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15294
> NMS-15294: Escaping parameter names in generated query strings

- opennms-base-assembly/src/main/filtered/etc/log4j2.xml
This work is part of NMS-15305
> NMS-15305: Update log4j config file

- features/newts/src/main/java/org/opennms/netmgt/newts/NewtsWriter.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/TimeseriesStorageManagerImpl.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/RingBufferTimeseriesWriter.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesPersister.java
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15324
> NMS-15324: Destroy ring buffer faster and more transparently

- opennms-webapp/src/main/webapp/WEB-INF/jsp/graph/results.jsp
- smoke-test/src/test/java/org/opennms/smoketest/ChooseResourcesPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15292
> NMS-15292: Escaping parameters in graph results page

- smoke-test/src/main/java/org/opennms/smoketest/containers/CassandraContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/JaegerContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/KarafContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/PostgreSQLContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
- smoke-test/src/test/java/org/opennms/smoketest/OpenNMSCloudPluginIT.java
- smoke-test/src/test/java/org/opennms/smoketest/OpenNMSSeleniumIT.java
This was originally merged to develop in #5678, but now I can see this work being important in foundation-2023 to support some more refactoring as we prepare to improve configurability of the container and better test it for Meridian 2023.
> Cherry-pick container warning cleanup to foundation-2023

- container/features/src/main/resources/features-sentinel.xml
- features/flows/itests/src/test/java/org/opennms/netmgt/flows/elastic/ThresholdingIT.java
- features/flows/processing/src/main/java/org/opennms/netmgt/flows/processing/impl/FlowThresholdingImpl.java
- features/flows/processing/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15340
> NMS-15340: Ensure thresholding session creation is done in transaction

- docs/modules/operation/pages/deep-dive/provisioning/auto-discovery.adoc
- Update `operation/deep-dive/provisioning/auto-discovery.adoc` …
> NMS-14734: Update Auto Discovery

- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/RingBufferTimeseriesWriter.java
This is a small fix to #5738. Once we have decided to force shutdown, LMAX's `drainAndHalt` will still wait until draining is complete, so we just have `onEvent` throw away metrics at this point.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15324
> NMS-15324: fix force shutdown

- opennms-webapp/src/main/webapp/status/index.jsp
> NMS-14854: fix XSS vulnerability in status/index.jsp

- docs/modules/operation/pages/deep-dive/alarms/alarm-advanced-search.adoc
- docs/modules/operation/pages/deep-dive/bsm/business-service-map.adoc
- docs/modules/operation/pages/deep-dive/bsm/operational-status.adoc
- docs/modules/operation/pages/deep-dive/events/event-advanced-search.adoc
- docs/modules/operation/pages/deep-dive/events/event-configuration.adoc
- docs/modules/reference/pages/service-assurance/monitors/VmwareMonitor.adoc
- Update `operation/deep-dive/alarms/alarm-advanced-search.adoc`
- Update `operation/deep-dive/bsm/business-service-map.adoc`, `/operational-status.adoc`
- Update `operation/deep-dive/events/event-advanced-search.adoc`, `/event-configuration.adoc`
- Update `reference/service-assurance/monitors/VmwareMonitor.adoc` …
> NMS-15274: Move severities chart

- .circleci/main/commands/oci/oci.yml
- opennms-container/core/Dockerfile
- opennms-container/core/plugins/.gitkeep
- opennms-container/sentinel/Dockerfile
- opennms-container/sentinel/plugins/.gitkeep
Adding ALEC, Cloud and Cortex plugins to the containers.
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15012 and http://issues.opennms.org/browse/NMS-15349 and http://issues.opennms.org/browse/NMS-15350
> NMS-15012, NMS-15349 and NMS-15350: Add plugins to OpenNMS and Sentinel containers

- docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
- docs/modules/operation/pages/deep-dive/device-config-backup/configuration.adoc
Feedback on docs that there is some ambiguity if this command is required (it's not)
> update wording on DCB port config

- docs/modules/reference/pages/provisioning/handlers/vmware.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15270
> NMS-15270: update vmware import docs

- core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Invoker.java
- core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Manager.java
- core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Starter.java
- Cleanups, take care of warnings
- Cleanup warnings
- When we fail to startup, exit with a non-zero exit code.
* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15386
> NMS-15386: When we fail to startup, exit with a non-zero exit code

- docs/modules/operation/pages/deep-dive/provisioning/scalability.adoc
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/Provisioner.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15208
> NMS-15208: Scan nodes on import at least once

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Release Notes for OpenNMS Horizon 31.0.4

- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
- Update `deployment/time-series-storage/timeseries/hosted-tss.adoc` …
> NMS-14959: Document Time Series tags

- docs/modules/write-the-docs/pages/build-docs.adoc
- docs/modules/write-the-docs/pages/develop-docs.adoc
- docs/modules/write-the-docs/pages/glossary.adoc
- docs/modules/write-the-docs/pages/write-docs.adoc
- Update `write-the-docs/build-docs.adoc`, `/develop-docs.adoc`, `/glossary.adoc`, `/write-docs.adoc`
* If this is a …
> DP-8: Update Write the Docs

- docs/modules/reference/pages/service-assurance/monitors/CiscoPingMibMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/DNSResolutionMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/DhcpMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/FtpMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/HttpMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/IcmpMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/JDBCQueryMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/MailTransportMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/PageSequenceMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/SSLCertMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/StrafePingMonitor.adoc
Redo so that things can be synched with foundation-2023
* If this is a new or updated feature, is there documentation …
> NMS-15215 - Number examples in service monitor chapters

- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
- Update `reference/daemons/daemon-config-files/provisiond.adoc` …
> NMS-15019: Fix .adoc link in Provisiond

- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/opennms-provisiond-graph.properties
> Fixed invalid comma and backslash

- .circleci/config.yml
- .circleci/main/commands/cache/cache.yml
This PR is a testbed for fixing CircleCI builds from PRs outside of `github.com/OpenNMS`
> fix handling of remote PRs

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/scheduled-outages.adoc
Scheduled outages are not covered in the docs - Initial Documentation - Definitely needs some work and embellishment
* …
> JIRA/NMS-12621 - Scheduled Outages are not covered in the docs

- .github/PULL_REQUEST_TEMPLATE.md
- core/test-api/db/src/main/java/org/opennms/core/test/db/TemporaryDatabasePostgreSQL.java
- core/web-assets/src/main/assets/js/apps/onms-classifications/views/modals/new-rule-modal.html
- features/datachoices/src/main/resources/web/modal.ftl.html
- NMS-13912: Test conventions page moved to Discourse
- Update link to Jira.
* If this is a new or updated feature, is …
> NMS-13912: Test Conventions is now in Discourse and tweak Jira link

- docs/modules/deployment/pages/core/centos-rhel9/postgresql.adoc
NMS-15381:Docs: Update path reference for PostgreSQL config files - due to build errors in the original PR (https://github.com/OpenNMS/opennms/pull/5751), have recreated work in a different branch.
* **If this code is likely to affect …
> NMS-15381:Docs: Update path reference for PostgreSQL config files

- .circleci/config.yml
- .circleci/pyscripts/library/cci_components/workflow.py
this adapts the changes to only do jira notification on non-prs to the new dynamic config code
> adapt pr changes to dynamic config

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
> NMS-15429: Add collection package information to web UI

- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
- Update `deployment/time-series-storage/timeseries/hosted-tss.adoc` …
> NMS-15290: Add outgoing connection to TS DB doc

- core/sysprops/src/main/java/org/opennms/core/sysprops/SystemProperties.java
- core/sysprops/src/test/java/org/opennms/sysprops/SystemPropertiesTest.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/sampleread/LateAggregationParams.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/sampleread/LateAggregationParamsTest.java
> DC-495: make sure heartbeat will never smaller than step

- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
- opennms-webapp/src/main/webapp/admin/delete.jsp
- opennms-webapp/src/main/webapp/admin/manage.jsp
- opennms-webapp/src/main/webapp/admin/newInterface.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-14865
> NMS-14865: Fixed missing forms

- docs/modules/deployment/pages/time-series-storage/timeseries/configuration.adoc
> DC-495: TSaaS user cannot see data older than a week

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Release notes for Horizon 31.0.5

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/search.adoc
- docs/modules/operation/pages/deep-dive/visualizations/dashboard.adoc
- docs/modules/operation/pages/deep-dive/visualizations/grafana-dashboard-box.adoc
- docs/modules/operation/pages/deep-dive/visualizations/heatmap.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/boosting-behavior.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/criteria-builder.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/alarm-detail.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/alarms.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/charts.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/grafana.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/image.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/introduction.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/ksc.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/map.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/rrd.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/rtc.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/summary.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/surveillance.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/topology.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/dashlets/url.adoc
- docs/modules/operation/pages/deep-dive/visualizations/opsboard/introduction.adoc
- docs/modules/operation/pages/deep-dive/visualizations/surveillance-view.adoc
- docs/modules/operation/pages/deep-dive/visualizations/trends.adoc
- Update `operation/nav.adoc`
- Update `operation/deep-dive/search.adoc`
- Update `operation/deep-dive/visualizations/grafana-dashboard-box.adoc`, `/heatmap.adoc`, `/surveillance-view.adoc`, `/trends.adoc`
- Update `operation/deep-dive/visualizations/opsboard/boosting-behavior.adoc`, `/criteria-builder.adoc`, `/introduction.adoc`
- Update `operation/deep-dive/visualizations/opsboard/dashlets/alarm-detail.adoc`, `/alarms.adoc`, `/charts.adoc`, `/grafana.adoc`, `/image.adoc`, `/ksc.adoc`, `/map.adoc`, `/rrd.adoc`, `/rtc.adoc`, `/summary.adoc`, `/surveillance.adoc`, `/topology.adoc`, `/url.adoc`
- Remove `deep-dive/visualizations/opsboard/dashlets/introduction.adoc`
* Please [make an issue in the OpenNMS issue tracker](https://issues.opennms.org) if there isn't one already.<br />Once there …
> DP-12: Update Visualizations section & Search

- container/features/src/main/resources/features-sentinel.xml
> NMS-15502: sentinel-timeseries-api missing fst dependency

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/config-tester.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/daemon-config-files.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/data-collection.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/external-auth.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/geocoder.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/https/http-ssl.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/https/https-client.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/https/https-server.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/https/request-logging.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/rmi.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/scv-configuration.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/system-properties.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/system-proxies.adoc
- Update `operation/deep-dive/admin/configuration/config-tester.adoc`, `/daemon-config-files.adoc`, `/data-collection.adoc`, `/external-auth.adoc`, `/geocoder.adoc`, `/rmi.adoc`, `/scv-configuration.adoc`, `/system-properties.adoc`, `/system-proxies.adoc`
- Update `operation/deep-dive/admin/configuration/https/http-ssl.adoc`, `/https-client.adoc`, `/https-server.adoc`, `/request-logging.adoc`
3. prefix your commit messages with the issue number, if …
> DP-13: Update Configuration docs

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/vacuumd.adoc
- docs/modules/reference/pages/daemons/introduction.adoc
- Update `reference/nav.adoc`
- Update `reference/daemons/introduction.adoc`
- Add `reference/daemons/daemon-config-files/vacuumd.adoc` …
> NMS-15440: Document vacuumd

- opennms-config/src/main/java/org/opennms/netmgt/config/WebRoleManagerImpl.java
- opennms-webapp/src/main/java/org/opennms/web/admin/roles/AdminRoleServlet.java
- opennms-webapp/src/main/webapp/admin/userGroupView/roles/list.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15307
> NMS-15307: Fixed XSS issue

- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
> Update cortex plugin docs for featuresBoot file

- docs/modules/operation/pages/deep-dive/alarms/history.adoc
- Update `operation/deep-dive/alarms/history.adoc`
* If this is a new or updated feature, is there documentation …
> NMS-15287: Update Alarm History doc

- docs/antora.yml
- docs/modules/deployment/pages/core/system-requirements.adoc
- Update `docs/antora.yml`
- Update `deployment/core/system-requirements.adoc`
* If this is a new or updated …
> NMS-15499: Add RHEL9 to Requirements

- opennms-webapp/src/main/java/org/opennms/web/controller/RrdSummaryController.java
Back-porting to 2019, not sure how I missed that the JIRA listed 2019 as well.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15086
> NMS-15086: Synchronize calls to RRD summary endpoint

- docs/modules/releasenotes/pages/whatsnew.adoc
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-web-api/src/main/java/org/opennms/web/servlet/AddHeaderFilter.java
- opennms-web-api/src/main/java/org/opennms/web/servlet/AddStrictTransportSecurityHeaderFilter.java
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15302
> NMS-15302: Added security-related HTTP headers

- docs/modules/operation/pages/deep-dive/events/event-tokens.adoc
- Update `operation/deep-dive/events/event-tokens.adoc` …
> NMS-15045: Update Replacement Tokens doc

- features/timeseries-shell/src/main/java/org/opennms/netmgt/timeseries/shell/TimeseriesStatsCommand.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/TimeseriesStorageManager.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/TimeseriesStorageManagerImpl.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/TimeseriesStorageManagerImplTest.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/resource/TimeseriesSearcherTest.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/sampleread/TimeseriesFetchStrategyTest.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/OffheapTimeseriesWriterTest.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/RingBufferTimeseriesWriterTest.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15323
> NMS-15323: Make TimeseriesStorageManager throw exception if no impl is found

- container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- container/shared/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- core/soa/src/main/java/org/opennms/core/soa/lookup/BlockingServiceLookup.java
- core/soa/src/main/java/org/opennms/core/soa/lookup/ServiceLookupBuilder.java
- features/container/sentinel/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- smoke-test/src/main/java/org/opennms/smoketest/containers/KarafContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSProfile.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/OpenNMSStack.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/KarafShell.java
- smoke-test/src/test/java/org/opennms/smoketest/BrokenWebappIT.java
- smoke-test/src/test/java/org/opennms/smoketest/CortexTssPluginIT.java
- smoke-test/src/test/java/org/opennms/smoketest/CortexTssTimeseriesPluginIT.java
- src/assembly/source.xml
This is a version of this PR without the karaf extender additions: https://github.com/OpenNMS/opennms/pull/5748
Those will live in develop for now and wait for 32.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15326
> NMS-15326: do not refresh bundles when features get installed

- docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
- Update `deployment/time-series-storage/newts/newts.adoc` …
> NMS-10155: Document Newts settings

- docs/modules/operation/pages/deep-dive/meta-data.adoc
> NMS-12808: Document the function hiding Meta-Data password values

- docs/modules/reference/pages/service-assurance/monitors/SnmpMonitor.adoc
The second v should be capital in observedValue. and when those variables are called, the first curl bracket should not be skipped. …
> Syntax fixes

- docs/modules/deployment/pages/time-series-storage/newts/introduction.adoc
Cassandra download link was broken.
Old link: https://cassandra.apache.org/download
New link: https://cassandra.apache.org/_/download.html
This should be a quick fix.
* **If this code is likely to affect the UI, did you name your …
> Fix broken Cassandra download link

- docs/modules/reference/pages/ticketing/ticketer/jira.adoc
> Jira ticketer doc  typo

- opennms-webapp/src/main/webapp/admin/userGroupView/users/list.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/users/modifyUser.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/users/userDetail.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15306
> NMS-15306: XSS fix

- opennms-webapp/src/main/webapp/admin/delete.jsp
- opennms-webapp/src/main/webapp/admin/nodemanagement/index.jsp
- opennms-webapp/src/main/webapp/admin/nodemanagement/managenode.jsp
- opennms-webapp/src/main/webapp/admin/nodemanagement/setPathOutage.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
- opennms-webapp/src/main/webapp/element/availability.jsp
- opennms-webapp/src/main/webapp/element/node-metadata.jsp
- opennms-webapp/src/main/webapp/element/node.jsp
- opennms-webapp/src/main/webapp/element/rescan.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15308
> NMS-15308: Fixed XSS issues

- docs/modules/reference/pages/glossary.adoc
- Update `reference/glossary.adoc`
* If this is a new or updated feature, is there documentation for the new …
> DP-17: Add CLI to Glossary

- features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java
- smoke-test/src/test/java/org/opennms/smoketest/IndexPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15310
> NMS-15310: prevent Session Fixation attacks

- dependencies/drools/pom.xml
- features/ticketing/drools-integration/src/main/java/org/opennms/netmgt/ticketd/DroolsTicketerServiceLayer.java
- opennms-alarms/integration-tests/src/test/java/org/opennms/netmgt/alarmd/itests/AlarmdBlackboxIT.java
- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/LocationMonitorRules.drl
- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/NodeParentRules.drl
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/CorrelationExample.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsStreamUtils.java
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/dependencyRules/DependencyRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/droolsFusion/DroolsFusion.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/locationMonitorRules/LocationMonitorRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/nodeParentRules/NodeParentRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistState/PersistState.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistStateStreaming/PersistStateStreaming.drl
JIRA: https://opennms.atlassian.net/browse/NMS-15459
> NMS-15459: Upgrade Drools to 8.34.0.Final (from 7.31.0.Final)

- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
Maybe when LIMITER.callWithTiemout sends an InterruptedException, it doesn't
make container.execInContainer return (I haven't dug into this yet).
Here's an example:
03:48:14.126 [main] INFO  org.*******.smoketest.containers.MinionContainer - Gathering thread dump...
03:48:14.128 [dev-debug-utils-pool-1] INFO  org.*******.smoketest.utils.DevDebugUtils - kill -3 -1
Too long with no output (exceeded 30m0s): context deadline exceeded
-- https://app.circleci.com/pipelines/github/OpenNMS/opennms/27620/workflows/2a143bfa-4b63-4dcd-962e-56f2823aec1e/jobs/224973?invite=true#step-114-949
(cherry picked from commit f2ec8711bef871ad80bcc782d90fa1411f3082ff)
* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one already.<br />Once there is an issue, …
> Cherry-pick from develop: Debugging: try to see why DevDebugUtils.gatherThreadDump sometimes hangs forever

- core/upgrade/src/main/java/org/opennms/upgrade/implementations/JmxRrdMigratorOffline.java
- features/api-layer/core/src/main/java/org/opennms/features/apilayer/config/CollectorConfExtensionManager.java
- features/api-layer/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-config-api/src/main/java/org/opennms/netmgt/config/api/CollectdConfigFactory.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/collectd/CollectdConfiguration.java
- opennms-config/src/main/java/org/opennms/netmgt/config/CollectdConfigFactory.java
- opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DefaultResourceDao.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdExternalIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdMoreIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/DuplicatePrimaryAddressIT.java
- opennms-services/src/test/resources/etc/collectd-configuration.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ForeignSourceConfigRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ScheduledOutagesRestService.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/OIA-55
> OIA-55: Implement collector config extensions

- smoke-test/src/main/java/org/opennms/smoketest/containers/MinionContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/SentinelContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/utils/DevDebugUtils.java
> Add a little bit more verbosity and some await() to debug hangs in gatherThreadDump

- docs/modules/development/nav.adoc
- docs/modules/development/pages/rest/measurements.adoc
- Update `development/rest/measurements.adoc`
* If this is a new or updated feature, is there documentation for …
> NMS-8894: Add transient attribute to Measurements API

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Release notes for OpenNMS Horizon 31.0.6

- opennms-webapp/src/main/webapp/admin/manage.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15308
> NMS-15308: Fixed XSS for admin/getNodes

- core/upgrade/src/main/java/org/opennms/upgrade/implementations/JmxRrdMigratorOffline.java
- features/api-layer/core/src/main/java/org/opennms/features/apilayer/config/CollectorConfExtensionManager.java
- features/api-layer/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-config-api/src/main/java/org/opennms/netmgt/config/api/CollectdConfigFactory.java
- opennms-config-jaxb/src/main/java/org/opennms/netmgt/config/collectd/CollectdConfiguration.java
- opennms-config/src/main/java/org/opennms/netmgt/config/CollectdConfigFactory.java
- opennms-config/src/main/java/org/opennms/netmgt/config/PollerConfigManager.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/support/DefaultResourceDao.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdExternalIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdMoreIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/DuplicatePrimaryAddressIT.java
- opennms-services/src/test/resources/etc/collectd-configuration.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ForeignSourceConfigRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/ScheduledOutagesRestService.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/editoutage.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
- pom.xml
This PR backports @fooker's changes for collectd OIA support from `develop` to `foundation-2023`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15585
> NMS-15585: backport collectd config extensions

- opennms-container/core/plugins.sh
- opennms-container/minion/plugins.sh
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15592
> NMS-15592: A small typo in plugin.sh prevents artifacts from GitHub to be included in containers

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/time-series-storage.adoc
> CLOUD-3190: Doc: Portal: Time Series: Usability Adjustments

- core/snmp/api/pom.xml
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AbstractSnmpValue.java
- core/snmp/api/src/test/java/org/opennms/netmgt/snmp/AbstractSnmpValueTest.java
- core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpValue.java
- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JValue.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15498
> NMS-15498: Treat only ASCII characters between 32 and 127 as displayable

- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/UsageStatisticsReporter.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/UsageStatisticsReportDTOTest.java
- smoke-test/src/test/java/org/opennms/smoketest/UsageStatisticsIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15368
> NMS-15368: Added KPI for containerization status

- opennms-webapp/src/main/java/org/opennms/web/controller/admin/thresholds/ThresholdController.java
I was able to recreate the issue by reloading threshd config while I had the page open for editing a new threshold / expression. We don't write the new object to disk until it's fully edited, so reloading the config wipes it from memory. This fix just creates a new default object to update if the previous one has disappeared. 
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15334
> NMS-15334: Catch config reloads when editing new thresholds

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AbstractSnmpValue.java
- core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpValue.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/SnmpValueTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15599
> NMS-15599: Fixed test and changed logic

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Release Notes for OpenNMS Horizon 31.0.7

- opennms-base-assembly/src/main/filtered/etc/log4j2.xml
- opennms-web-api/src/main/java/org/opennms/web/servlet/XssRequestWrapper.java
- opennms-web-api/src/test/java/org/opennms/web/servlet/XssRequestWrapperTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15305
> NMS-15305: Prevent logging of passwords

- docs/modules/operation/pages/deep-dive/user-management/pre-authentication.adoc
Fixing a typo found by a user.
> Fix doc typo on pre-auth test command

- features/datachoices/src/main/resources/web/datachoicesMetadata.json
- ui/src/components/UsageStatistics/UsageStatisticsHeader.vue
- ui/src/components/UsageStatistics/UsageStatisticsTable.vue
Some updates to Usage Statistics Sharing UI.
- added/updated metadata names/descriptions
- fixed some datatypes
- added `boolean` datatype
- UI support for displaying `boolean` datatype plus numeric formatting
- added OpenNMS support and privacy policy links
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15476
> NMS-15476: Usage stats UI updates

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15033
> NMS-15033: Initializing asset record in the constructer since getAssetRecord() will be called anyway

- opennms-base-assembly/src/main/filtered/etc/opennms.service
Update the opennms.service to include:
AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE
* If this is a new or …
> Update opennms.service to include AmbientCapabilities=CAP_NET_RAW CAP_NET_BIND_SERVICE

- opennms-base-assembly/src/main/filtered/bin/install
fix: install script checks for equality of myuser and RUNAS before so)urcing opennms.conf
* If this is a new or …
> NMS-15610: install script checks for equality of myuser and RUNAS before sourcing opennms.conf

- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JStrategy.java
JIRA: https://opennms.atlassian.net/browse/NMS-15637
Manually register the AES-256 protocol so that it *just works*.
> NMS-15637: Fix SNMPv3 support for AES256

- docs/modules/operation/pages/deep-dive/admin/configuration/data-collection.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-15627
> NMS-15627: Updated docs

- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/operation/pages/quick-start/notifications.adoc
- docs/modules/operation/pages/quick-start/users.adoc
Brought changes from NMS-15489, excluding data choices info. Improvements on existing content for users, notifications, and getting started.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it …
> NMS-15658: DOC: Pull changes into foundation branch

- opennms-container/common.mk
- opennms-container/core/Dockerfile
- opennms-container/minion/Dockerfile
- opennms-container/sentinel/Dockerfile
**This will be in draft until after releases happen on Wednesday.** We don't want to merge this change at the last minute before releases, especially since it will go into `foundation-2023`, so we'll leave it for the next monthly releases.
https://opennms.atlassian.net/browse/NMS-15532
- NMS-15609: remove `nocap` JDK bits since they've moved to deploy base -- this is a cherry-pick from [this commit to `develop`](https://github.com/OpenNMS/opennms/pull/6019/commits/ebc46d518f2ef408b3d5c36d7f2ed5b6fdc016c0) so we can build containers with [the newer deploy-base versions that now has the `nocap` version of the JVM](https://github.com/OpenNMS/deploy-base/commit/ef2032e3cbfa27d893fd896f051fc6c432834ce3#diff-50a853c3aebfd54a95b1832fc4226abc432a51e1b6be3401bc61201bdbb297d9R81).
- Catch the case …
> NMS-15532: Upgrade to deploy-base b220 to get jattach

- core/daemon/src/main/java/org/opennms/netmgt/scheduler/LegacyScheduler.java
- core/daemon/src/main/java/org/opennms/netmgt/scheduler/Schedule.java
- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/collectd-schedule.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/shell/introduction.adoc
- docs/modules/operation/pages/deep-dive/service-assurance/shell/pollerd-schedule.adoc
- features/collection/shell-commands/src/main/java/org/opennms/netmgt/collection/commands/CollectdScheduleCommand.java
- features/poller/shell/src/main/java/org/opennms/netmgt/poller/shell/PollerdScheduleCommand.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/jmx/Collectd.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/jmx/CollectdMBean.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/jmx/Pollerd.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/jmx/PollerdMBean.java
* JIRA: https://opennms.atlassian.net/browse/NMS-14526
> NMS-14526: Karaf commands for Pollerd/Collectd scheduler

- docs/modules/deployment/pages/time-series-storage/timeseries/hosted-tss.adoc
> Cloud-3190: Doc Portal - Time Series: Usability Adjustments

- docs/modules/development/pages/source-copyright.adoc
NMS-13908: Codify code copyright conventions and guidelines - added information on how to format copyright dates in the source code header, including a matrix describing different scenarios.
* **If this code is likely to affect …
> NMS-13908: Codify code copyright conventions and guidelines

- docs/modules/troubleshooting/pages/other-issues.adoc
> Docs: Add note about firewall and tcpdump

- opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java
- opennms-webapp/src/main/java/org/opennms/web/event/EventQueryServlet.java
- opennms-webapp/src/test/java/org/opennms/web/event/NMS12517_Test.java
This PR backports some event query fixes that went into newer releases to `foundation-2020`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15679
> NMS-15679: backport event query fixes to foundation 2020

- features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java
- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
- smoke-test/src/test/java/org/opennms/smoketest/IndexPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15414
> NMS-15414: Fixed deep-links

- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/BroadcastEventProcessor.java
- opennms-config-model/src/main/java/org/opennms/netmgt/xml/eventconf/Events.java
- opennms-config/src/main/java/org/opennms/netmgt/config/DefaultEventConfDao.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfDaoReloadTest.java
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/broken/broken.events.xml
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/broken0-eventconf.xml
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/broken1-eventconf.xml
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/broken2-eventconf.xml
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/working-eventconf.xml
- opennms-config/src/test/resources/org/opennms/netmgt/config/eventd/NMS-15289/working/working.events.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15289
> NMS-15289: Check eventd config files before reload

- docs/modules/deployment/pages/minion/message-broker/kafka.adoc
> NMS-15666: improve Minion kafka config instructions

- docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15693
> NMS-15693: XML Doc updates

- features/status/api/pom.xml
- features/status/api/src/main/java/org/opennms/features/status/api/node/NodeStatusService.java
- opennms-config/src/main/resources/META-INF/opennms/applicationContext-commonConfigs.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15526
> NMS-15526: Check WebACLs in Status Overview box

- docs/modules/operation/pages/deep-dive/flows/sentinel/message-broker/activemq.adoc
- docs/modules/operation/pages/deep-dive/flows/sentinel/message-broker/kafka.adoc
> Fix doc replacement token

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/NMS15210Test.java
- features/mib-compiler/src/test/java/org/opennms/features/mibcompiler/SPC465Test.java
- features/mib-compiler/src/test/resources/BCN-DNS-MIB.mib
- features/mib-compiler/src/test/resources/BCN-TC-MIB.mib
- features/mib-compiler/src/test/resources/HCNUM-TC.mib
Added support to handle especial case CounterBasedGauge64 as. gauge
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15210
> NMS-15210: Special-case CounterBasedGauge64 in MIB compiler

- docs/modules/operation/pages/deep-dive/service-assurance/configuration.adoc
Added information for how to disable async polling, as requested in ticket.
* If this is a new or updated feature, …
> NMS-15680: Document async polling settings

- docs/modules/deployment/pages/core/getting-started.adoc
- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/startup.adoc
> NMS-15634: Docs section about startup configuration and opennms.conf

- opennms-base-assembly/src/main/filtered/bin/opennms
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15635
> NMS-15635: Review and adjust default and example startup settings

- opennms-webapp/src/main/webapp/WEB-INF/jsp/KSC/customView.jsp
This minor detail is really annoying when I want to see details of a single graph from the context of a KSC report, so I'm taking the time to change it, but not the time to create a Jira or actually follow process for it.
* **If …
> NMS-15711: KSC Report "Details" should go directly to the graph, not "all"

- features/api-layer/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/api-layer/dao-common/src/main/java/org/opennms/features/apilayer/dao/AlarmDaoImpl.java
- features/api-layer/dao-common/src/main/java/org/opennms/features/apilayer/utils/ModelMappers.java
- features/api-layer/sentinel/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- pom.xml
This PR implements the Horizon core side of https://github.com/OpenNMS/opennms-integration-api/pull/79
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15439
> NMS-15439: implement new OPA 1.5.0 alarm ticketing interfaces

- core/ipc/common/kafka-shell/src/main/java/org/opennms/core/ipc/common/kafka/shell/KafkaRpcTopics.java
- core/ipc/common/kafka-shell/src/main/java/org/opennms/core/ipc/common/kafka/shell/KafkaSinkTopics.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15664
> NMS-15664: Fixed timeout handling

- container/features/pom.xml
- container/features/src/main/resources/features.xml
- container/karaf/src/main/filtered-resources/etc/custom.properties
- container/karaf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg
- docs/modules/development/pages/rest/notifications.adoc
- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/notifications/shell.adoc
- features/notifications/api/src/main/java/org/opennms/netmgt/notifd/api/NotificationConfigProvider.java
- features/notifications/api/src/main/java/org/opennms/netmgt/notifd/api/NotificationTester.java
- features/notifications/pom.xml
- features/notifications/shell/pom.xml
- features/notifications/shell/src/main/java/org/opennms/netmgt/notifd/shell/DestinationPathNameCompleter.java
- features/notifications/shell/src/main/java/org/opennms/netmgt/notifd/shell/DestinationPathTrigger.java
- opennms-full-assembly/pom.xml
- opennms-services/src/main/java/org/opennms/netmgt/notifd/NotificationConfigProviderImpl.java
- opennms-services/src/main/java/org/opennms/netmgt/notifd/NotificationTask.java
- opennms-services/src/main/java/org/opennms/netmgt/notifd/NotificationTesterImpl.java
- opennms-services/src/main/resources/META-INF/opennms/applicationContext-notifd.xml
- opennms-webapp-rest/pom.xml
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NotificationRestService.java
- opennms-webapp/src/main/webapp/admin/notification/destinationPaths.jsp
JIRA: https://opennms.atlassian.net/browse/NMS-14692
There's a button now!
> NMS-14692: Allow destination paths to be triggered from the shell and UI

- docs/antora.yml
- docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
- docs/modules/deployment/pages/minion/centos-rhel9/install-minion.adoc
- docs/modules/deployment/pages/minion/install.adoc
- docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel7.adoc
- docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel8.adoc
- docs/modules/deployment/pages/repos/rhel-centos/meridian-rhel9.adoc
> NMS-15665: fix Meridian repo URLs for RHEL (foundation-2023)

- features/collection/snmp-collector/src/main/java/org/opennms/netmgt/collectd/EnumLookupPropertyExtender.java
> Fix comment on EnumLookupPropertyExtender

- opennms-config-model/src/main/java/org/opennms/netmgt/config/threshd/Service.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15422
> NMS-15422: Fixed equals() method in Service class

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Release notes for OpenNMS Horizon 31.0.9

- container/features/src/main/resources/features-core.xml
JIRA: https://opennms.atlassian.net/browse/NMS-15751
This improves startup time significantly when testing locally. We'll see if it also solves the issues in CI shortly...
> NMS-15751: Don't load bcprov-ext alongside bcprov

- docs/modules/operation/pages/deep-dive/service-assurance/polling-packages.adoc
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/status.properties
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptor.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptorPersistenceTest.java
This combines all three related issues into one PR:
* JIRA: https://opennms.atlassian.net/browse/NMS-15641
* JIRA: https://opennms.atlassian.net/browse/NMS-15642
* JIRA: https://opennms.atlassian.net/browse/NMS-15643
> NMS-15641 / NMS-15642 / NMS-15643: Enable Poll Status History by default

- docs/modules/deployment/pages/minion/introduction.adoc
> NMS-15620: Docs need an update on what a Minion is able to do

- ui/src/components/UsageStatistics/UsageStatisticsHeader.vue
> NMS-15740: Tweak usage statistics sharing notice copy

- docs/modules/operation/pages/deep-dive/notifications/strategies/slack.adoc
Updated the documentation to reflect that our solution for implementing channels in Slack has been deprecated. Includes workaround. …
> NMS-15652: Update documentation (or implementation) for newer Slack API

- core/jmx/api/src/main/java/org/opennms/netmgt/jmx/connection/PasswordStrategy.java
- docs/modules/reference/pages/performance-data-collection/collectors/jmx.adoc
- docs/modules/reference/pages/service-assurance/monitors/JmxMonitor.adoc
- features/collection/collectors/src/test/resources/etc/jmx-config.xml
- features/vaadin-jmxconfiggenerator/src/main/java/org/opennms/features/vaadin/jmxconfiggenerator/data/UiModel.java
- opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/examples/poller-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/foreign-sources/selfmonitor.xml
- opennms-base-assembly/src/main/filtered/etc/jmx-config.xml
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
- opennms-config-jaxb/src/test/java/org/opennms/netmgt/config/poller/PollerConfigurationTest.java
- opennms-config-jaxb/src/test/resources/org/opennms/netmgt/config/poller/poller-configuration-1.8.xml
- opennms-config-jaxb/src/test/resources/org/opennms/netmgt/config/poller/poller-configuration-NMS-6490.xml
- opennms-provision/opennms-detector-jmx/src/test/resources/test-jmx-config.xml
- opennms-provision/opennms-provision-persistence/src/main/resources/org/opennms/netmgt/provision/persist/default-foreign-source.xml
PR 2 of 2.  Replace references of `PASSWORD-CLEAR` with `PASSWORD_CLEAR` in docs and default configs.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14884
> NMS-14884: Replace PASSWORD-CLEAR with PASSWORD_CLEAR

- opennms-config/src/main/java/org/opennms/netmgt/filter/JdbcFilterDao.java
Backport the JdbcFilterDao transaction change to `foundation-2020`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15696
> NMS-15696: Remove @Transactional annotation from JdbcFilterDao

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/service-assurance/monitors/DskTableMonitoradoc
> NMS-11021: Document DskTableMonitor

- docs/antora.yml
> NMS-15777: Docs need updating to include support for Kafka 3

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/FilesystemRestService.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15702
> NMS-15702: Only members of ROLE_ADMIN can view/edit users.xml

- core/cli/src/main/resources/bin/find-java.sh
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15784
> NMS-15784: add /usr/lib64/jvm to the search criteria

- docs/modules/operation/pages/deep-dive/performance-data-collection/resource-types.adoc
Added note in the that the data collection resource types topic that PersistRegexSelectorStrategy only works on string attributes. …
> NMS-15595: PersistRegexSelectorStrategy only works on string attributes

- debian/changelog
- docs/antora.yml
- docs/modules/releasenotes/pages/changelog.adoc
- docs/modules/releasenotes/pages/whatsnew.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
Note: I will make another push with the codename put in the `changelog.adoc` once voting has closed :)
> Horizon 32 Release Notes

- docs/modules/reference/pages/service-assurance/introduction.adoc
> NMS-15642: Update docs for `rrd-status` default value for v32.

- core/db/src/main/java/org/opennms/core/db/HikariCPConnectionFactory.java
- docs/modules/troubleshooting/pages/other-issues.adoc
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
JIRA: [NMS-15816](https://opennms.atlassian.net/browse/NMS-15816)
Avoid acquiring JDBC connection while in the context of a Spring transaction transaction - process one after the other instead.
Also add code that can be used to detect these problems, default to disabled.
[NMS-15816]: https://opennms.atlassian.net/browse/NMS-15816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NMS-15816: Database deadlock triggered by NodeRestService

- docs/modules/deployment/pages/minion/install.adoc
> NMS-15618: Minion connectivity config docs start the user in the wrong directory

- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptor.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptor.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptorPersistenceTest.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptorPersistenceTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15820
> NMS-15820: Default ds-name should be lower-case service name

- core/db/src/main/java/org/opennms/netmgt/config/opennmsDataSources/JdbcDataSource.java
- core/db/src/test/java/org/opennms/core/db/PasswordEncryptionTest.java
- core/ipc/rpc/mock-impl/src/main/java/org/opennms/core/rpc/mock/MockEntityScopeProvider.java
- core/mate/api/src/main/java/org/opennms/core/mate/api/EntityScopeProvider.java
- core/mate/api/src/main/java/org/opennms/core/mate/api/Interpolator.java
- core/mate/api/src/test/java/org/opennms/core/mate/api/MetaDataUtilsTest.java
- core/mate/model/src/main/java/org/opennms/core/mate/model/EntityScopeProviderImpl.java
- core/mate/model/src/main/resources/beanRefContext.xml
- docs/modules/reference/pages/service-assurance/monitors/VmwareCimMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/VmwareMonitor.adoc
- features/collection/client-rpc/src/main/java/org/opennms/netmgt/collection/client/rpc/CollectorRequestBuilderImpl.java
- features/collection/test-api/src/main/java/org/opennms/netmgt/collection/test/api/CollectorComplianceTest.java
- features/poller/client-rpc/src/main/java/org/opennms/netmgt/poller/client/rpc/PollerRequestBuilderImpl.java
- features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
- features/scv/jceks-impl/src/main/resources/beanRefContext.xml
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCimCollector.java
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/collectd/VmwareCollector.java
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/poller/monitors/AbstractVmwareMonitor.java
- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionTool.java
- integrations/opennms-vmware/src/main/java/org/opennms/protocols/vmware/VmwareViJavaAccess.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCimCollectorComplianceTest.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/collectd/VmwareCollectorComplianceTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15753
> NMS-15753: Allow meta-data and SCV access for VMware credentials

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/FilesystemRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/FilesystemRestServiceTest.java
- opennms-webapp-rest/src/test/resources/NMS-15704/NMS-15704-1.xml
- opennms-webapp-rest/src/test/resources/NMS-15704/NMS-15704-2.xml
- opennms-webapp-rest/src/test/resources/NMS-15704/hostname_exfiltrate.dtd
* JIRA: https://opennms.atlassian.net/browse/NMS-15704
> NMS-15704: Securing Xml parser factory

- docs/modules/operation/pages/deep-dive/device-config-backup/configuration.adoc
- docs/modules/operation/pages/deep-dive/device-config-backup/dcb-requisition.adoc
- docs/modules/operation/pages/deep-dive/device-config-backup/dcb.adoc
- docs/modules/operation/pages/deep-dive/device-config-backup/introduction.adoc
- docs/modules/operation/pages/deep-dive/device-config-backup/ssh.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/collectd/collect-admin.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/collectd/collection-packages.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/collectd/configuration.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/collectors.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/data-types.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/introduction.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/resource-types.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/adhoc-collection.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/collectd-schedule.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/introduction.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/measurements.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/stress-testing.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-index.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/cisco-cbqos.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/enum-lookup.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/index-split.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/pointer-like-index.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/property-extenders.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/regex.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/snmp-interface.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-property-extenders/value-mapping.adoc
Added description tags for device configuration backup and performance management sections of the operation>deep-dive guide as part of SEO improvment.
* **If this code is likely to affect the UI, did you name your branch with …
> DP-64: Add meta descriptions to each page in the operation guide.

- docs/modules/deployment/pages/core/message-broker/kafka.adoc
- docs/modules/operation/pages/deep-dive/kafka-producer/enable-kafka.adoc
> Kafka doc updates

- debian/changelog
- docs/modules/releasenotes/pages/changelog.adoc
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Releasenotes 32.0.1

- container/features/src/main/resources/features.xml
- features/ifttt/pom.xml
- features/ifttt/src/main/java/org/opennms/features/ifttt/IfTttDaemon.java
- features/ifttt/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/ifttt/src/test/java/org/opennms/features/ifttt/IfTttDaemonTest.java
- features/ifttt/src/test/resources/etc/ifttt-config.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15763
> NMS-15763: Allow the IfTtt API key to be stored in SCV

- core/ipc/sink/kafka/server/src/main/java/org/opennms/core/ipc/sink/kafka/server/ConditionalKafkaOffsetContext.java
- core/ipc/sink/kafka/server/src/main/resources/META-INF/opennms/applicationContext-ipc-offset-provider.xml
- core/ipc/sink/kafka/server/src/main/resources/META-INF/opennms/applicationContext-ipc-sink-kafka-server.xml
- core/ipc/sink/kafka/server/src/main/resources/META-INF/opennms/component-dao.xml
- docs/modules/reference/pages/configuration/tuning-kafka.adoc
* JIRA (Issue Tracker): http://issues.opennms.org/browse/NMS-15336
> NMS-15336: provide an option to disable kafka offset provider

- features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/collectors/CollectionSetMapper.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
- opennms-model/src/main/java/org/opennms/netmgt/model/ResourceTypeUtils.java
Does what it says on the tin.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15854
> NMS-15854: handle some more possible resource exceptions

- opennms-base-assembly/src/main/filtered/etc/datacollection/f5.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15862
> NMS-15862: Fix F5 datacollection resource types

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/nodeList.jsp
- opennms-webapp/src/main/webapp/admin/discovery/add-er.jsp
- opennms-webapp/src/main/webapp/admin/discovery/add-ex-url.jsp
- opennms-webapp/src/main/webapp/admin/discovery/add-ir.jsp
- opennms-webapp/src/main/webapp/admin/discovery/add-specific.jsp
- opennms-webapp/src/main/webapp/admin/discovery/add-url.jsp
- opennms-webapp/src/main/webapp/admin/discovery/edit-config.jsp
- opennms-webapp/src/main/webapp/admin/discovery/edit-scan.jsp
- opennms-webapp/src/main/webapp/asset/index.jsp
- opennms-webapp/src/main/webapp/asset/modify.jsp
- opennms-webapp/src/main/webapp/element/index.jsp
> NMS-15782: prevent multiple XSS mishaps

- opennms-base-assembly/src/main/filtered/etc/examples/scriptd-configuration.xml
> NMS-15793: Do not start BSF server

- opennms-webapp/src/main/webapp/admin/interfaceDeleted.jsp
- opennms-webapp/src/main/webapp/admin/nodemanagement/setPathOutage.jsp
- opennms-webapp/src/main/webapp/admin/notification/noticeWizard/buildPathOutage.jsp
- opennms-webapp/src/main/webapp/admin/sysconfig.jsp
- opennms-webapp/src/main/webapp/admin/userGroupView/users/newUser.jsp
- opennms-webapp/src/main/webapp/dashboard.jsp
- opennms-webapp/src/main/webapp/element/rescan.jsp
- opennms-webapp/src/main/webapp/geomap/includes/map.jsp
- opennms-webapp/src/main/webapp/surveillance-box.jsp
- opennms-webapp/src/main/webapp/surveillance-view.jsp
> NMS-15783: prevent multiple XSS reflections

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/UserRestService.java
> NMS-15703: Do not allow ROLE_REST to modify users

- features/measurements/impl/src/main/java/org/opennms/netmgt/measurements/impl/AbstractRrdBasedFetchStrategy.java
This is the same as https://github.com/OpenNMS/opennms/pull/6336, but targeting `foundation-2023`. Repeating the description here.
The Measurements API returns metadata including information on nodes when responding to a query for resource attribute values, for example by the Grafana plugin Performance data source.
However if the requested resource is not found, for example because SNMP collection has not yet occurred on that node, then no node metadata is returned, even though the node metadata exists. When the Grafana plugin `nodeToLabel` function is used, it doesn't find the node metadata including the label name and so the label displays as the FS:FID. This causes the issue in https://opennms.atlassian.net/browse/HELM-427.
This will return metadata for the node even if the resource …
> NMS-15839: Measurements API: Include node metadata even if resource not found

- pom.xml
> NMS-15861: Backport postgresql client version bump

- docs/modules/reference/pages/performance-data-collection/collectors/wsman.adoc
- features/wsman/src/main/java/org/opennms/netmgt/collectd/WsManCollector.java
- features/wsman/src/main/java/org/opennms/netmgt/poller/monitors/WsManMonitor.java
- opennms-provision/opennms-detectorclient-rpc/src/main/java/org/opennms/netmgt/provision/detector/client/rpc/DetectorRequestBuilderImpl.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15754
> NMS-15754: Allow WSMan credentials to be stored in SCV

- docs/modules/reference/pages/service-assurance/monitors/JCifsMonitor.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-15762
Beside short doc note nothing to do, since the interpolation of poller parameters already working.
> NMS-15762: Added note to docs

- core/web-assets/src/main/assets/js/lib/onms-schedule-editor/templates/schedule-editor.tpl.html
- opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
- opennms-webapp/src/main/webapp/admin/snmpInterfaces.jsp
- opennms-webapp/src/main/webapp/element/node.jsp
- opennms-webapp/src/main/webapp/includes/bootstrap.jsp
- opennms-webapp/src/main/webapp/includes/search-box.jsp
- opennms-webapp/src/main/webapp/locations/index.jsp
- opennms-webapp/src/main/webapp/minion/index.jsp
- opennms-webapp/src/main/webapp/report/index.jsp
- opennms-webapp/src/main/webapp/status/index.jsp
Do not spawn a default app when there is no real app end prevent evaluation of angular expressions if no app is defined.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it to trigger smoke …
> NMS-15504: Prevent angular expr eval without app

- container/features/src/main/resources/features-core.xml
- core/cli/src/main/resources/bin/_module_opts.sh
- core/test-api/kafka/pom.xml
- core/web-assets/package-lock.json
- features/distributed/coordination/zookeeper/pom.xml
- features/flows/itests/pom.xml
- integrations/opennms-jasper-extensions/pom.xml
- pom.xml
This fixes some OSGi-related issues in the support bits for ALEC and Sentinel, and is the base for further work I'm doing fixing ALEC on Horizon 32.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15808
> NMS-15808: convert zookeeper to servicemix version

- docs/modules/reference/pages/performance-data-collection/collectors/xml.adoc
- protocols/xml/src/main/java/org/opennms/protocols/xml/collector/XmlCollector.java
- protocols/xml/src/test/java/org/opennms/protocols/xml/collector/NMS15757IT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15757
> NMS-15757: Allow metadata in Xml collector

- opennms-container/minion/CONFD_README.md
NMS-15901:
The kafka RPC and IPC configurations had a typo in bootstrap.servers key.
* If this is a new or updated …
> NMS-15901: Typo in Configuring Minion via confd README

- docs/antora.yml
- docs/modules/deployment/pages/core/message-broker/kafka.adoc
- docs/modules/deployment/pages/core/setup-message-broker.adoc
> NMS-15632: improve Kafka message broker setup docs

- opennms-webapp/src/main/webapp/account/selfService/passwordGate.jsp
Updated wording for Admin Password Gate page.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15867
> NMS-15867: Admin password gate, updated wording

- docs/modules/operation/pages/deep-dive/elasticsearch/introduction.adoc
- features/alarms/history/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/flows/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/jest/client/pom.xml
- features/jest/client/src/main/java/org/opennms/features/jest/client/RestClientFactory.java
- features/jest/client/src/main/java/org/opennms/features/jest/client/credentials/CredentialsParser.java
- features/jest/client/src/test/java/org/opennms/features/jest/client/credentials/CredentialsParserTest.java
- features/opennms-es-rest/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/situation-feedback/elastic/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15752
> NMS-15752: Allow Elasticsearch credentials to be stored in SCV

- features/springframework-security/src/main/java/org/opennms/web/springframework/security/OpenNMSAuthSuccessHandler.java
- opennms-webapp/src/main/java/org/opennms/web/account/selfService/AbstractBasePasswordChangeActionServlet.java
- opennms-webapp/src/main/java/org/opennms/web/account/selfService/PasswordGateActionServlet.java
- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
- opennms-webapp/src/main/webapp/WEB-INF/web.xml
- opennms-webapp/src/main/webapp/account/selfService/newPassword.jsp
- opennms-webapp/src/main/webapp/account/selfService/passwordGate.jsp
- opennms-webapp/src/main/webapp/login.jsp
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/test/java/org/opennms/smoketest/AdminPasswordGateIT.java
PR to merge the Admin Password Change Prompt work into `develop`.
Note, the SonarCloud issues were ones that were already present. Could be handled by a separate issue.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15868
> NMS-15868: Admin Password Change Prompt

- docs/modules/reference/pages/performance-data-collection/collectors/http.adoc
- features/collection/collectors/src/main/java/org/opennms/netmgt/collectd/HttpCollector.java
- features/collection/collectors/src/test/java/org/opennms/netmgt/collectd/NMS15758IT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15758
> NMS-15758: Allow metadata expressions in HTTP datacollection config

- docs/modules/reference/pages/ticketing/ticketer/jira.adoc
- features/ticketing/jira-integration/pom.xml
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPlugin.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/commands/AbstractJiraCommand.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/commands/ShowConfigCommand.java
- features/ticketing/jira-integration/src/main/java/org/opennms/netmgt/ticketer/jira/commands/VerifyCommand.java
- features/ticketing/jira-integration/src/main/resources/OSGI-INF/blueprint/blueprint-jira-ticketer.xml
- features/ticketing/jira-integration/src/test/java/org/opennms/netmgt/ticketer/jira/JiraTicketerPluginTest.java
- features/ticketing/jira-integration/src/test/resources/opennms-home/etc/jira.properties
* JIRA: https://opennms.atlassian.net/browse/NMS-15760
> NMS-15760: Allow metadata in jira.properties

- features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpPeerStatusAdapter.java
- features/telemetry/protocols/bmp/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/bmp/adapter/BmpTelemetryAdapter.java
JIRA: https://opennms.atlassian.net/browse/NMS-15853
logging++
> NMS-15853: Improve logging for node lookups in BMP message processing.

- docs/modules/reference/pages/telemetryd/protocols/bmp/bmp.adoc
- docs/modules/reference/pages/telemetryd/protocols/bmp/persisting-adapter.adoc
JIRA: https://opennms.atlassian.net/browse/NMS-15853
> NMS-15853: More BMP docs related to distributed processing.

- docs/modules/reference/pages/configuration/filters/parameters.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15842
> NMS-15842: Add `IsSnmpPrimary` to filter docs

- core/db/src/main/java/org/opennms/netmgt/config/opennmsDataSources/JdbcDataSource.java
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16029
> NMS-16029: Make metadata expression the default in opennms-datasources.xml

- docs/modules/deployment/pages/core/admin-password-reset.adoc
- docs/modules/deployment/pages/core/getting-started.adoc
- features/themes/onms-default-theme/bin/src/license/THIRD-PARTY.properties
NMS-15775: Document change in login password behaviour - updated docs to reflect new password reset behaviour upon first log in. …
> NMS-15775: Document change in login password behaviour

- docs/modules/deployment/pages/minion/docker/minion.adoc
Replaces https://github.com/OpenNMS/opennms/pull/6429
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16017
> NMS-16017: update minion docker docs

- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
- docs/modules/operation/pages/deep-dive/database-reports/templates/grafana.adoc
- docs/modules/reference/pages/glossary.adoc
> Fix doc references to Helm plugin

- opennms-base-assembly/src/main/filtered/etc/opennms-datasources.xml
As we now spawn two pools (by self monitoring DB stats collection), we exceed the psql default max connection count (of 100) easily. As a first mitigation, we reduce the number of connections to create on startup and assume that a single collector will never increase the pool size.
Don't worry if this sounds …
> NMS-15852: Reduce minimal pool size

- opennms-webapp/src/main/webapp/login.jsp
When a user requests login.jsp while being authenticated (either be default login or by external auth), do not show login page but redirect to dashboard.
* **If this code is likely to affect the UI, did you name your branch with …
> NMS-14078: Redirect from login to index for authenticated user

- docs/modules/deployment/pages/core/getting-started.adoc
> Follow-up change to Bonnie's PR for NMS-16050

- docs/modules/releasenotes/pages/changelog.adoc
> Release notes for Horizon 32.0.2

- debian/changelog
- opennms-assemblies/minion/src/main/filtered/debian/changelog
- opennms-assemblies/sentinel/src/main/filtered/debian/changelog
> Added forgotten Debian portion of Horizon 32.0.2 release notes

- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/NodeRestService.java
Prevent query details being returned in response to client for invalid `filterRule` V1 Node Rest API call. This is called by the Grafana Plugin.
See https://opennms.atlassian.net/browse/OCI-44.
If an invalid `filterRule` is sent in the query string, for example something starting like `filterRule=\*serviceName`, a `FilterParseException` is thrown by `JdbcFilterDao`. This was not being caught and bubbled up and the query details were being sent back to the client with a 500 error.
Changed to catch these exceptions and return a `400 Bad Request` with a message that does not reveal details. Note that `JdbcFilterDao` already logs a warning, so not doing any logging here.
Targeting `foundation-2023` since this is a security-related issue.
* Jira (Issue Tracker): …
> NMS-16057: Prevent query details in response to client for invalid Node filterRule

- features/api-layer/common/src/main/java/org/opennms/features/apilayer/common/collectors/CollectionSetMapper.java
- features/collection/api/src/test/java/org/opennms/netmgt/collection/support/GenericTypeResourceTest.java
- features/kafka/producer/src/main/java/org/opennms/features/kafka/producer/collection/CollectionSetMapper.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/MetaTagDataLoader.java
I failed to also check for empty arrays when doing my original bounds-checking work for this.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15806
> NMS-15806: don't just null-check, also look for empties

- ui/src/stores/appStore.ts
- ui/src/stores/authStore.ts
- ui/src/stores/configurationStore.ts
- ui/src/stores/deviceStore.ts
- ui/src/stores/eventStore.ts
- ui/src/stores/fakeMenuData.ts
- ui/src/stores/fileEditorStore.ts
- ui/src/stores/helpStore.ts
- ui/src/stores/ifServiceStore.ts
- ui/src/stores/infoStore.ts
- ui/src/stores/ipInterfacesStore.ts
- ui/src/stores/logStore.ts
- ui/src/stores/mapStore.ts
- ui/src/stores/menuStore.ts
- ui/src/stores/nodeStore.ts
- ui/src/stores/pluginStore.ts
- ui/src/stores/resourceStore.ts
- ui/src/stores/scvStore.ts
- ui/src/stores/searchStore.ts
- ui/src/stores/usageStatisticsStore.ts
- ui/src/stores/useGraphStore.ts
- ui/src/types/index.ts
Initial task for moving from Vuex to Pinia, create all the pinia stores, but do not yet wire them up.
Stores will be moved in subsequent PRs, and most likely there will be additional cleanup.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16068
> NMS-16068: Create pinia stores, but do not yet use them

- docs/modules/releasenotes/pages/changelog.adoc
> NMS-16086: Corrections to researcher names in August release notes (Horizon 32)

- core/web-assets/src/main/assets/js/lib/onms-schedule-editor/templates/schedule-editor.tpl.html
- opennms-webapp/src/main/webapp/admin/snmpInterfaces.jsp
- opennms-webapp/src/main/webapp/element/node.jsp
- opennms-webapp/src/main/webapp/includes/bootstrap.jsp
- opennms-webapp/src/main/webapp/includes/search-box.jsp
- opennms-webapp/src/main/webapp/locations/index.jsp
- opennms-webapp/src/main/webapp/minion/index.jsp
- opennms-webapp/src/main/webapp/report/index.jsp
- opennms-webapp/src/main/webapp/status/index.jsp
Do not spawn a default app when there is no real app end prevent evaluation of angular expressions if no app is defined.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16052
> NMS-15504: Prevent angular expr eval without app (backport)

- opennms-container/core/Dockerfile
- opennms-container/minion/Dockerfile
- opennms-container/sentinel/Dockerfile
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16087
> NMS-16087: Unzip command is missing from UBI images

- docs/modules/operation/pages/deep-dive/events/sources/syslog.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/syslogd.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-3552
> NMS-3552: Syslogd doc updates

- opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/ImportRequisition.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16100
> Update ImportRequisition.java help text

- docs/modules/operation/pages/deep-dive/performance-data-collection/collectd/collection-packages.adoc
Table is rendering as a list instead of a grid.
> Fix doc formatting for collectd packages

- docs/modules/operation/pages/deep-dive/events/event-definition.adoc
- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/processor/HibernateEventWriter.java
This is a follow-up of #6577.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16048
>  NMS-16048: Handle unknown log destination gracefully

- features/datachoices/src/main/resources/web/modal.ftl.html
Updated wording for Usage Statistics Sharing banner notice.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16027
> NMS-16027: Updated Usage Stats Sharing banner wording

- features/instrumentationLogReader/src/main/java/org/opennms/util/ilr/ServiceCollector.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16114
> NMS-16114: Update Instrumentation log regex for IPv6

- docs/modules/deployment/pages/core/getting-started.adoc
NMS-14811: Quick install script for first time evaluator and training - added a section about the availability of the quick install script in GitHub, with a link and some verbiage around why to use the quick install script and the scope of what it provides.
Don't worry if this sounds like a lot, we can help you …
> NMS-14811: Quick install script for first time evaluator and training

- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/SnmpProfileMapper.java
- core/snmp/profile-mapper/src/main/java/org/opennms/core/snmp/profile/mapper/impl/SnmpProfileMapperImpl.java
- core/test-api/snmp/src/main/java/org/opennms/core/test/snmp/ProxySnmpAgentConfigFactory.java
- opennms-alarms/snmptrap-northbounder/src/test/java/org/opennms/netmgt/alarmd/northbounder/snmptrap/AbstractTrapReceiverTest.java
- opennms-config-api/src/main/java/org/opennms/netmgt/config/api/SnmpAgentConfigFactory.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpConfigAccessService.java
- opennms-config/src/main/java/org/opennms/netmgt/config/SnmpPeerFactory.java
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpPeerFactoryTest.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/AnAgentConfigFactory.java
- opennms-provision/opennms-detector-simple/src/test/java/org/opennms/netmgt/provision/detector/SnmpDetectorWithProfilesTest.java
- opennms-provision/opennms-detector-simple/src/test/resources/org/opennms/netmgt/provision/detector/snmp-config-with-profiles.xml
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeInfoScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/NodeScan.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/SnmpConfigRestServiceIT.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/config/AgentConfigurationResourceTest.java
- opennms-webapp/src/main/java/org/opennms/web/admin/nodeManagement/SnmpConfigServlet.java
JIRA: https://opennms.atlassian.net/browse/NMS-16028
> NMS-16028: Allow metadata in snmp-config.xml

- opennms-webapp/src/main/webapp/login.jsp
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
When a user requests login.jsp while being authenticated (either be
default login or by external auth), do not show login page but redirect
to dashboard.### All Contributors
* **If this code is likely to affect the UI, did you …
> NMS-14078: Redirect from login to index for authenticated user.

- docs/modules/operation/pages/quick-start/inventory.adoc
- opennms-config/src/test/java/org/opennms/netmgt/config/SnmpPeerFactoryTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16028
> NMS-16028: Added doc entry and additional test

- features/container/sentinel/src/main/filtered-resources/etc/datacollection-config.xml
- features/container/sentinel/src/main/filtered-resources/etc/resource-types.d/flows-resource.xml
- opennms-config-jaxb/src/main/resources/xsds/datacollection-config.xsd
* JIRA: https://opennms.atlassian.net/browse/NMS-15695
> NMS-15695: Added missing configuration files for Sentinel

- opennms-config/src/main/java/org/opennms/netmgt/config/WmiPeerFactory.java
- opennms-config/src/test/java/org/opennms/netmgt/config/WmiPeerFactoryTest.java
- protocols/nsclient/src/main/java/org/opennms/protocols/nsclient/config/NSClientPeerFactory.java
- protocols/nsclient/src/test/java/org/opennms/protocols/nsclient/collector/NsclientCollectorTest.java
- protocols/nsclient/src/test/java/org/opennms/protocols/nsclient/config/NSClientPeerFactoryTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15765
> NMS-15765: Metadata for nsclient-config.xml and wmi-config.xml

- docs/modules/reference/pages/daemons/daemon-config-files/ackd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/alarmd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/bsmd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/collectd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/discovery.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/enlinkd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/event-translator.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/eventd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/jettyserver.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/karaf.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/karafstartupmonitor.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/notifd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/passivestatusd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/perspectivepollerd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/pollerd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/queued.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/reportd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/rtcd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/snmp-interface-poller.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/statsd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/syslogd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/telemetryd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/ticketer.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/trapd.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/vacuumd.adoc
- docs/modules/reference/pages/daemons/introduction.adoc
- docs/modules/reference/pages/glossary.adoc
> DP-82: Add meta descriptions to each page in the reference guide.

- docs/modules/operation/pages/deep-dive/kafka-producer/kafka-producer.adoc
> NMS-16133: Add language to docs for how to find schema to Kafka Producer

- docs/modules/development/pages/rest/situation-feedback.adoc
- docs/modules/operation/pages/deep-dive/events/event-definition.adoc
NMS-15603: Find a different way to render the .titles in our docs as titles - in the end, there weren't that many that were issues. Most of the .titles seem to render ok as is.
* **If this code is likely to affect the UI, did you …
> NMS-15603: Find a different way to render the .titles in our docs as titles

- ui/README.md
Updated `README` for Vue UI with developer workflow, since it may not be obvious and also changed as a result of the menu UI Preview updates.
Also updated a few other things like versions to use, pinia support.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16142
> NMS-16142: Update UI README for dev workflow, pinia, etc.

- features/poller/shell/src/main/java/org/opennms/netmgt/poller/shell/Poll.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16119
> NMS-16119: Fixed poll command to also display effective parameter values

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15766
> NMS-15766: Allow metadata evaluation in Drools rules

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/IpInterfaceScan.java
- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/ProvisionService.java
> NMS-16146: Persist detector parameters as meta data

- ui/src/components/Nodes/NodeDownloadDropdown.vue
- ui/src/components/Nodes/NodesTable.vue
- ui/src/components/Nodes/utils.ts
Add ability to export CSV and Json files for the current Node Structure search/filter configuration.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16064
> NMS-16064: Node structure CSV and Json export

- docs/modules/operation/pages/deep-dive/events/sources/tl1.adoc
- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/daemons/daemon-config-files/tl1d.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16150
> NMS-16150: Add docs on TL1d

- core/db/src/main/java/org/opennms/core/db/DataSourceFactory.java
- core/db/src/main/java/org/opennms/core/db/XADataSourceFactory.java
- core/db/src/main/java/org/opennms/netmgt/config/opennmsDataSources/ConnectionPool.java
- core/db/src/main/java/org/opennms/netmgt/config/opennmsDataSources/JdbcDataSource.java
- core/db/src/main/resources/xsds/opennms-datasources.xsd
- opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/opennms-datasources.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16143
> NMS-16143: Allow per connection pool config and split out monitoring connection

- opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
- opennms-base-assembly/src/main/filtered/etc/poller-configuration.xml
> NMS-16016: Use metadata in poller and collector config default

- opennms-container/common.mk
- opennms-container/core/Dockerfile
- opennms-container/minion/Dockerfile
- opennms-container/sentinel/Dockerfile
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16145
> NMS-16145: Container's java binary is missing cap_net_raw capability

- opennms-container/core/container-fs/confd/conf.d/opennms-datasources.xml.toml
- opennms-container/core/container-fs/confd/templates/opennms-datasources.xml.tpl
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16163
> NMS-16163: Update confd for new datasources XML schema

- tools/packages/sentinel/sentinel.spec
* JIRA: https://opennms.atlassian.net/browse/NMS-16159
> NMS-16159: Fixed SENTINEL_HOME in scripts

- opennms-container/core/container-fs/confd/templates/opennms-datasources.xml.tpl
> NMS-16170: Set database connection minpool to 25

- core/password/pom.xml
- core/password/src/main/java/org/opennms/core/password/Password.java
- core/pom.xml
- opennms-base-assembly/pom.xml
- opennms-base-assembly/src/assembly/daemon.xml
- opennms-base-assembly/src/main/filtered/bin/password
- opennms-bootstrap/src/main/java/org/opennms/bootstrap/PasswordBootstrap.java
This PR integrates @mershad-manesh's password tool into the core install
> include Morteza's password tool in the base distro

- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16174
> NMS-16174: bump scala to 2.13.12

- features/events/daemon/src/main/java/org/opennms/netmgt/eventd/processor/expandable/ExpandableParameter.java
- opennms-services/src/test/java/org/opennms/netmgt/notifd/BroadcastEventProcessorIT.java
- opennms-webapp/src/main/webapp/element/snmpinterface.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16157
> NMS-16157: Escaping event parameters and ifAlias

- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15819
> NMS-15819: Fixed typos in applicationContext-spring-security.xml

- opennms-assemblies/webapp-full/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16168
The dependency was removed by NMS-15065.
> NMS-16168: Added missing dependency

- features/vaadin-dashlets/dashlet-map/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/MapDashlet.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16044
New URL is in place, but the new map does not support searching yet.
> NMS-16044: Fixed URL to geographical map

- opennms-webapp/src/main/webapp/admin/nodemanagement/deletenode.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15746
> NMS-15746: Added CSRF token to form

- dependencies/drools/pom.xml
- features/ticketing/drools-integration/src/main/java/org/opennms/netmgt/ticketd/DroolsTicketerServiceLayer.java
- opennms-alarms/integration-tests/src/test/java/org/opennms/netmgt/alarmd/itests/AlarmdBlackboxIT.java
- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/LocationMonitorRules.drl
- opennms-base-assembly/src/main/filtered/etc/examples/drools-engine.d/nodeParentRules/NodeParentRules.drl
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/CorrelationExample.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsCorrelationEngine.java
- opennms-correlation/drools-correlation-engine/src/main/java/org/opennms/netmgt/correlation/drools/DroolsStreamUtils.java
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/dependencyRules/DependencyRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/droolsFusion/DroolsFusion.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/locationMonitorRules/LocationMonitorRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/nodeParentRules/NodeParentRules.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistState/PersistState.drl
- opennms-correlation/drools-correlation-engine/src/test/opennms-home/etc/drools-engine.d/persistStateStreaming/PersistStateStreaming.drl
Backport of the changes from NMS-15459 to `foundation-2023`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16179
> NMS-16179: Upgrade to Drools 8.34.0.Final

- ui/src/components/Nodes/ExtendedSearchPanel.vue
- ui/src/components/Nodes/hooks/queryStringParser.ts
- ui/src/components/Nodes/hooks/useNodeQuery.ts
- ui/src/lib/utils.ts
- ui/src/types/index.ts
Fixes some issues with Node Structure page query parameters and also ensuring we don't send multiple API requests when a parameter changes. Still some more work to do on this issue, but want to break it into smaller pieces.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16197
> NMS-16197: Node structure add more query params, fix search issues

- docs/modules/operation/pages/deep-dive/flows/distributed.adoc
> Fix flow doc typo

- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
- docs/modules/reference/pages/telemetryd/protocols/bmp/persisting-adapter.adoc
- ui/src/components/Configuration/ConfigurationThreadPools.vue
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14766
> NMS-14766 provisiond thread documentation updates

- opennms-base-assembly/src/main/filtered/etc/resource-types.d/postgresql-resource.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16165
> NMS-16165: (take 2) add missing JDBC resource type

- docs/modules/operation/pages/deep-dive/meta-data.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-15774
> NMS-15774: Brief overview of the metadata changes

- features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/BaseThresholdDefConfigWrapper.java
- features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java
- features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSetImpl.java
- features/collection/thresholding/impl/src/test/java/org/opennms/netmgt/threshd/ThresholdExpressionTestCase.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15667
> NMS-15667: Interpolate Mate in threshold label and resource-filters

- ui/src/components/Layout/Search.vue
- ui/src/components/Nodes/hooks/queryStringParser.ts
- ui/src/containers/Nodes.vue
Fix a couple Node Structure issues
- bug in `queryStringParser`
- fix node structure routing when on same page but query string params change
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16197
> NMS-16197: Fix some Node Structure issues

- docs/modules/reference/pages/telemetryd/protocols/bmp/persisting-adapter.adoc
> Update persisting-adapter.adoc format typo

- opennms-container/minion/Dockerfile
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16212
> NMS-16212: Update permission used for creating prom-jmx-exporter folder

- core/grpc/common/src/main/java/org/opennms/core/grpc/common/GrpcClientBuilder.java
- features/openconfig/telemetry-client/src/main/java/org/opennms/features/openconfig/telemetry/GrpcClientInterceptor.java
- features/openconfig/telemetry-client/src/main/java/org/opennms/features/openconfig/telemetry/OpenConfigClientImpl.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16158
> NMS-16158: Add support to pass credentials through metadata for OpenConfig

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/core/containers.adoc
- docs/modules/deployment/pages/core/system-requirements.adoc
> NMS-16108: OpenShift Documentation

- core/upgrade/src/main/java/org/opennms/upgrade/support/Upgrade.java
- debian/opennms-server.postinst
- opennms-assemblies/minion/src/main/filtered/debian/opennms-minion.postinst
- opennms-assemblies/sentinel/src/main/filtered/debian/opennms-sentinel.postinst
- opennms-install/src/main/java/org/opennms/install/Installer.java
- tools/packages/minion/minion.spec
- tools/packages/opennms/opennms.spec
- tools/packages/sentinel/sentinel.spec
Add a note pointing to the participate page and contact email.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16213
> NMS-16213: add pointer to contact page and email

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/service/DefaultSurveillanceViewService.java
- features/vaadin-surveillance-views/src/test/java/org/opennms/features/vaadin/surveillanceviews/service/NMS15448_IT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15448
> NMS-15448: Only show acknowledged alarms in surveillance view

- docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16240
> NMS-16240: Doc update for Minion on Oracle 8

- ui/package.json
- ui/src/components/Layout/BreadCrumbs.vue
- ui/src/components/Nodes/hooks/queryStringParser.ts
- ui/src/components/Nodes/hooks/useNodeExport.ts
- ui/src/components/Nodes/hooks/useNodeQuery.ts
- ui/src/lib/utils.ts
- ui/src/types/index.ts
- ui/tests/components/Nodes/hooks/data/getExportDataResponse.json
- ui/tests/components/Nodes/hooks/data/getExportDataResponseCSV.json
- ui/tests/components/Nodes/hooks/queryStringParser.test.ts
- ui/tests/components/Nodes/hooks/useIpInterfaceQuery.test.ts
- ui/tests/components/Nodes/hooks/useNodeExport.test.ts
- ui/tests/components/Nodes/hooks/useNodeQuery.test.ts
- ui/tests/components/Nodes/hooks/utils.ts
- ui/tests/components/Nodes/utils.test.ts
- ui/tests/configuration.test.ts
- ui/tests/lib/utils.test.ts
- ui/tests/scv.test.ts
- ui/yarn.lock
Unit tests for Structured Node List. Just for the library/processing code, not for Vue components themselves.
Fixed some bugs or other issues as well, got rid of a couple annoying warnings.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16060
> NMS-16060: Structured node list unit tests

- core/cli/src/main/resources/bin/_module_opts.sh
* JIRA: https://opennms.atlassian.net/browse/NMS-16236
> NMS-16236: Fixed VmwareCimMonitor and VmwareCimCollector

- container/features/src/main/resources/features-core.xml
- container/features/src/main/resources/features.xml
- container/karaf/src/main/filtered-resources/etc/custom.properties
- features/container/minion/src/main/filtered-resources/etc/custom.properties
- features/container/sentinel/src/main/filtered-resources/etc/custom.properties
- features/device-config/ssh-scripting/pom.xml
- features/device-config/ssh-scripting/src/test/java/org/opennms/features/deviceconfig/sshscripting/impl/SshScriptingServiceImplIT.java
- pom.xml
- smoke-test/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16131
> NMS-16131: Added ed25519 algorithm

- docs/modules/deployment/pages/core/containers.adoc
…Escalation
NMS-16239: Added information on issue around allowPrivilegeEscalation being set to false, and how to deal with it. …
> NMS-16239: OpenShift: Document the impact of disabling allowPrivilegeEscalation

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/time-series-storage.adoc
Doc: Portal: Remove Appliance and TSaaS - removed references to TSaaS from the core documentation, as we are no longer providing this service.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in …
> CLOUD-3399: Doc: Portal: Remove Appliance and TSaaS

- container/karaf/src/main/filtered-resources/etc/startup.properties
- container/shared/src/main/filtered-resources/etc/startup.properties
- features/reporting/jasper-reports-compiler/pom.xml
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16249
> NMS-16249: update karaf to latest 4.3.x

- docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel9/install-core.adoc
NMS-14777: R-Core fails to install following the Horizon 30 Install Docs - updated documentation to add requirement of enabling PowerTools with R-core package installation.
* **If this code is likely to affect the UI, did you name …
> NMS-14777: R-Core fails to install following the Horizon 30 Install Docs

- docs/antora.yml
- docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel9/install-core.adoc
- docs/modules/deployment/pages/minion/centos-rhel7/install-minion.adoc
- docs/modules/deployment/pages/minion/centos-rhel8/install-minion.adoc
- docs/modules/deployment/pages/minion/centos-rhel9/install-minion.adoc
- docs/modules/deployment/pages/sentinel/runtime/centos-rhel7/install-sentinel.adoc
- docs/modules/deployment/pages/sentinel/runtime/centos-rhel8/install-sentinel.adoc
- docs/modules/deployment/pages/sentinel/runtime/centos-rhel9/install-sentinel.adoc
- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
- docs/modules/reference/pages/performance-data-collection/collectors/nsclient.adoc
- docs/modules/reference/pages/performance-data-collection/collectors/tca.adoc
- docs/modules/reference/pages/provisioning/adapters/ddns.adoc
- docs/modules/reference/pages/provisioning/adapters/hardware-inventory.adoc
- docs/modules/reference/pages/provisioning/adapters/rdns.adoc
- docs/modules/reference/pages/provisioning/adapters/snmp-asset.adoc
- docs/modules/reference/pages/provisioning/adapters/wsman-asset.adoc
- docs/modules/reference/pages/service-assurance/monitors/JCifsMonitor.adoc
- docs/modules/reference/pages/service-assurance/monitors/RadiusAuthMonitor.adoc
- docs/modules/reference/pages/ticketing/ticketer/jira.adoc
- docs/modules/write-the-docs/pages/develop-docs.adoc
> NMS-16164: NMS-16164: Docs: Meridian plugins reference wrong package names

- docs/modules/operation/pages/deep-dive/service-assurance/downtime-model.adoc
NMS-10133: Missing information in downtime model docs - removed "delete" flag and text around this as it is no longer available. Additional questions inline.
* **If this code is likely to affect the UI, did you name your branch …
> NMS-10133: Missing information in downtime model docs

- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
Capturing some additional information that was shared in Mattermost.
https://chat.opennms.com/opennms/pl/mpuax8uzgtnu9m4xa6znubty1a
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-14766
> NMS-14766: Docs: add more info about provisiond threads

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
> Removed redundant null check

- docs/modules/operation/pages/deep-dive/performance-data-collection/shell/collectd-schedule.adoc
> Fix collectd-schedule.adoc typo

- opennms-container/core/container-fs/entrypoint.sh
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16265
> NMS-16265: Update entrypoint.sh `-t` to run `config-tester -a`

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16167
> NMS-16167: Only display data of matching Collectd-package

- opennms-webapp/src/main/webapp/WEB-INF/jsp/element/service.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16167
Manual cherry-pick for release-32.x
> NMS-16167: Cherry-pick to release-32.x

- opennms-webapp/src/main/java/org/opennms/web/controller/alarm/AlarmDetailController.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16162
> NMS-16162: Deny readonly users to modify alarm sticky and journal memos

- docs/modules/development/pages/rest/meta-data.adoc
- docs/modules/operation/pages/deep-dive/meta-data.adoc
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/AbstractDaoRestServiceWithDTO.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeIpInterfacesRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeMonitoredServiceRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NodeRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/MetadataRestIT.java
Manipulation is limited to contexts starting with `X-` and warning about mixing manipulation and requisition has been added. …
> NMS-16259: Metadata manipulation via rest

- docs/modules/operation/pages/deep-dive/performance-data-collection/collectors.adoc
> NMS-13246: Move collectors from Performance Management section to Reference

- features/events/shell-commands/src/main/java/org/opennms/netmgt/events/commands/EventCommand.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15130
> NMS-15130: Added event command

- features/collection/snmp-collector/src/main/java/org/opennms/netmgt/collectd/SnmpPropertyExtenderProcessor.java
* JIRA: https://opennms.atlassian.net/browse/NMS-15743
> NMS-15743: Added debug log statement

- integrations/opennms-snmp-metadata-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpMetadataProvisioningAdapter.java
- opennms-provision/opennms-provision-shell/pom.xml
- opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/SnmpMetadataProvisingAdapterCommand.java
- opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/SnmpMetadataProvisioningAdapterCommand.java
* JIRA: https://opennms.atlassian.net/browse/NMS-13922
> NMS-13922: Added command to trigger SnmpMetadataProvisioningAdapter

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/graphs.adoc
- docs/modules/operation/pages/deep-dive/performance-data-collection/snmp-index.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16258
> NMS-16258: add docs about snmp-graph

- docs/modules/development/pages/rest/meta-data.adoc
> Doc: Fix link on metadata REST page

- docs/modules/deployment/pages/core/getting-started.adoc
Replaces #6954 which targeted the wrong branch.  credit to @billfitzgerald for finding this.
> Fix doc link in install guide

- docs/modules/deployment/pages/core/centos-rhel/initialize-core.adoc
- docs/modules/deployment/pages/core/debian-ubuntu/initialize-core.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16286
> NMS-16286: Docs for monitor database

- opennms-container/core/container-fs/confd/templates/opennms-datasources.xml.tpl
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16287
> NMS-16287: Update confd datasource defaults

- docs/modules/development/nav.adoc
- docs/modules/development/pages/rest/newsfeed.adoc
- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/newsfeed-configuration.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/usage-statistics.adoc
News Feed configuration documentation.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16255
> NMS-16255: News Feed configuration documentation

- docs/modules/development/nav.adoc
- docs/modules/development/pages/rest/newsfeed.adoc
- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/admin/configuration/newsfeed-configuration.adoc
Same as #6978 but targeting `foundation-2023`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16255
> NMS-16255: Newsfeed docs: foundation 2023

- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeed.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeedItem.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/NewsFeedProvider.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/xml/NewsFeedXml.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/newsfeed/xml/package-info.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/NewsFeedRestService.java
- opennms-webapp-rest/src/main/webapp/WEB-INF/applicationContext-cxf-rest-v2.xml
- opennms-webapp/src/main/java/org/opennms/web/controller/newsfeed/NewsFeedController.java
- opennms-webapp/src/main/webapp/WEB-INF/dispatcher-servlet.xml
- opennms-webapp/src/main/webapp/WEB-INF/jsp/newsfeed/newsFeedPanel.jsp
- opennms-webapp/src/main/webapp/index.jsp
Same as #6976 but targeting `foundation-2023`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16282
> NMS-16282: News Feed UI and Rest service, foundation-2023

- core/grpc/common/src/main/java/org/opennms/core/grpc/common/GrpcClientBuilder.java
- core/grpc/osgi/pom.xml
- docs/modules/reference/pages/telemetryd/protocols/openconfig.adoc
- features/openconfig/telemetry-client/src/main/java/org/opennms/features/openconfig/telemetry/OpenConfigClientImpl.java
- features/telemetry/protocols/openconfig/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/openconfig/adapter/OpenConfigAdapter.java
> NMS-16277: Update OpenConfig to use hostname and add a way to skip signature validation

- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16296
> NMS-16296: upgrade commons-compress to 1.25.0

- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16300
> NMS-16300: bump jettison to 1.5.4

- container/features/src/main/resources/features-core.xml
- container/features/src/main/resources/features.xml
- container/karaf/src/main/filtered-resources/etc/overrides.properties
- container/shared/src/main/filtered-resources/etc/overrides.properties
- features/bsm/service/impl/pom.xml
- features/bsm/service/impl/src/main/java/org/opennms/netmgt/bsm/service/internal/DefaultBusinessServiceStateMachine.java
- features/topology-map/org.opennms.features.topology.app/pom.xml
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/AbstractLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/D3TopoLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/FRLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/HierarchyLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/ISOMLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/TopoFRLayout.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/jung/TopoFRLayoutAlgorithm.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/service/DefaultGraph.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/IpLikeHopCriteria.java
- features/topology-map/org.opennms.features.topology.app/src/main/java/org/opennms/features/topology/app/internal/support/LayoutManager.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/D3LayoutTest.java
- features/topology-map/org.opennms.features.topology.app/src/test/java/org/opennms/features/topology/app/internal/jung/FRLayoutTest.java
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16295
> NMS-16295: port to Jung 2.1

- core/web-assets/src/main/assets/js/apps/timeline-resize/index.js
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v1/TimelineRestService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/TimelineRestServiceIT.java
- opennms-webapp/src/main/webapp/includes/interfaceAvailability-box.jsp
- opennms-webapp/src/main/webapp/includes/nodeAvailability-box.jsp
- opennms-webapp/src/main/webapp/includes/serviceAvailability-box.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15850
> NMS-15850: Changed timeline URLs to use serviceId instead of serviceName

- features/api-layer/core/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16272
> NMS-16272: Make jsonStore as mandatory requirement

- core/schema/src/main/liquibase/changelog.xml
- core/schema/src/main/liquibase/foundation-2023/changelog.xml
- opennms-web-api/src/main/java/org/opennms/web/enlinkd/EnLinkdElementFactory.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16199
> NMS-16199: Added unique indices and null-checks

- docs/modules/operation/pages/deep-dive/notifications/concepts.adoc
> NMS-13273: Add docs about var-bind in notifications

- docs/modules/deployment/pages/core/getting-started.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15792
> NMS-15792: Doc: deployment note on DNS lookups

- docs/modules/operation/pages/deep-dive/events/event-translator.adoc
> Docs: add translator note about multiple mapings for a UEI

- opennms-base-assembly/src/main/filtered/etc/datacollection-config.xml
- opennms-base-assembly/src/main/filtered/etc/eventconf.xml
- opennms-base-assembly/src/main/filtered/etc/syslogd-configuration.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16314
> NMS-16314: add comment placeholders to config files

- docs/modules/operation/pages/deep-dive/notifications/configuration.adoc
> Update path outage doc

- opennms-container/minion/container-fs/health.sh
- opennms-container/sentinel/container-fs/health.sh
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16327
> NMS-16327: update health.sh for Minion and Sentinel

- container/features/src/main/resources/features-sentinel.xml
- container/features/src/main/resources/features.xml
- container/karaf/src/main/filtered-resources/etc/overrides.properties
- container/shared/src/main/filtered-resources/etc/overrides.properties
- opennms-full-assembly/pom.xml
- pom.xml
make sure only our version is loaded in karaf
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16209
> NMS-16209: bump zookeeper to latest 3.4.x

- features/events/traps/src/main/java/org/opennms/netmgt/trapd/TrapdConfigBean.java
- features/events/traps/src/main/resources/OSGI-INF/blueprint/blueprint-trapd-listener.xml
- smoke-test/src/main/resources/minion-config/minion-config.yaml
- smoke-test/src/test/java/org/opennms/smoketest/minion/TrapIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16310
> NMS-16310: Include useAddressFromVarbind in config

- docs/modules/operation/pages/deep-dive/events/sources/snmp-traps.adoc
Documentation for NMS-16310 / #7054
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16310
> NMS-16310: Docs for minion trapd

- features/datachoices/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
Enable User Data Collection by default.
Also fixed endpoint URL to `https`.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16324
> NMS-16324: Enable User Data Collection by default; fix endpoint url

- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/AlarmPersisterImpl.java
Handle exception. This doesn't resolve the issue completely
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16208
> NMS-16208: Handle exception when transaction fails

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareImporter.java
- integrations/opennms-vmware/src/test/java/org/opennms/netmgt/provision/service/vmware/VmwareImporterTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16320
> NMS-16320: Setting correct location for VMware import

- features/datachoices/src/main/resources/web/user-data-collection.ftl.html
Update User Data Collection wording.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16352
> NMS-16352: Update User Data Collection wording only

- .vscode/settings.json
- docs/modules/development/nav.adoc
- docs/modules/development/pages/rest/health_rest.adoc
- docs/modules/development/pages/rest/info.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16351
> NMS-16351: Info rest docs

- opennms-provision/opennms-provision-shell/pom.xml
- opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/ImportRequisition.java
- opennms-provision/opennms-provision-shell/src/main/java/org/opennms/netmgt/provision/requisition/command/ShowImport.java
- opennms-provision/opennms-provision-shell/src/test/java/org/opennms/netmgt/provision/requisition/command/ImportEventListenerTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16343
> NMS-16343: Added parameter to wait for events

- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/AbstractForeignSourceRepository.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/NMS16357Test.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16357
> NMS-16357: Hide credentials in requisition URL

- docs/modules/operation/pages/deep-dive/kafka-producer/configure-kafka.adoc
> NMS-16361: Update Kafka Producer docs

- core/mate/api/src/main/java/org/opennms/core/mate/api/EmptyScopeProvider.java
- core/mate/api/src/main/java/org/opennms/core/mate/api/EntityScopeProvider.java
- core/mate/api/src/main/java/org/opennms/core/mate/api/FallBackScopeProvider.java
- core/mate/api/src/main/java/org/opennms/core/mate/api/ScopeProvider.java
- core/mate/api/src/test/java/org/opennms/core/mate/api/MetaDataUtilsTest.java
- core/mate/model/src/test/java/org/opennms/core/mate/model/EntityScopeProviderIT.java
- features/collection/core/src/main/java/org/opennms/netmgt/collection/core/CollectionSpecification.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/CollectableService.java
- opennms-services/src/main/java/org/opennms/netmgt/collectd/Collectd.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdExternalIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/CollectdMoreIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/DuplicatePrimaryAddressIT.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/ThresholdIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16358
> NMS-16358: Fixed meta-data retrieval in Collectd

- integrations/opennms-vmware/src/main/java/org/opennms/netmgt/provision/service/vmware/VmwareRequisitionTool.java
- opennms-base-assembly/src/main/filtered/bin/config-tester
- opennms-base-assembly/src/main/filtered/bin/vmwarereqtool
- opennms-config-tester/src/main/resources/META-INF/opennms/applicationContext-configTester.xml
- opennms-javamail/opennms-javamail-api/src/main/java/org/opennms/javamail/JavaMailerConfig.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16355
> NMS-16355: Fixing scripts

- features/telemetry/protocols/netflow/adapter/pom.xml
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/common/NetflowTelemetryAdapter.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpFixTelemetryAdapter.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpFixTelemetryAdapterFactory.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/Netflow5TelemetryAdapter.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow5/Netflow5TelemetryAdapterFactory.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9TelemetryAdapter.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9TelemetryAdapterFactory.java
- features/telemetry/protocols/netflow/adapter/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/ipfix/IpFixProtobufValidationTest.java
- features/telemetry/protocols/netflow/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/netflow9/Netflow9ProtobufValidationTest.java
- opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/netflow-telemetry.groovy
- opennms-base-assembly/src/main/filtered/etc/telemetryd-configuration.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16378
> NMS-16378: NetFlow scripted data collection adapter

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/flows/scripting-adapter.adoc
- docs/modules/operation/pages/deep-dive/flows/vendor-specific-ies.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-16391
> NMS-16391: Added docs for IPFIX Telemetry

- features/vaadin-dashlets/dashlet-alarms/src/main/java/org/opennms/features/vaadin/dashboard/dashlets/AlarmDetailsDashlet.java
- smoke-test/src/test/java/org/opennms/smoketest/opsboard/OpsBoardAdminPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16387
> NMS-16387: Fixed escaping

- docs/modules/reference/pages/daemons/daemon-config-files/provisiond.adoc
> Removed deprecated provisiond-configuration.xml reference

- opennms-provision/opennms-provisiond/src/main/java/org/opennms/netmgt/provision/service/DefaultProvisionService.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/DefaultProvisionServiceTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16402
> NMS-16402: Fixed category handling

- core/snmp/api/pom.xml
- core/snmp/api/src/main/java/org/opennms/netmgt/snmp/AbstractSnmpValue.java
- core/snmp/api/src/test/java/org/opennms/netmgt/snmp/AbstractSnmpValueTest.java
- core/snmp/impl-joesnmp/pom.xml
- core/snmp/impl-joesnmp/src/main/java/org/opennms/netmgt/snmp/joesnmp/JoeSnmpValue.java
- core/snmp/impl-joesnmp/src/test/java/org/opennms/netmgt/snmp/joesnmp/NMS16395Test.java
- core/snmp/impl-mock/src/main/java/org/opennms/netmgt/snmp/mock/MockSnmpValue.java
- core/snmp/impl-snmp4j/src/main/java/org/opennms/netmgt/snmp/snmp4j/Snmp4JValue.java
- core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/NMS16395Test.java
- core/snmp/integration-tests/src/test/java/org/opennms/netmgt/snmp/mock/SnmpValueTest.java
- core/snmp/joesnmp/pom.xml
- core/snmp/joesnmp/src/main/java/org/opennms/protocols/snmp/SnmpOctetString.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
* JIRA: https://opennms.atlassian.net/browse/NMS-16395?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel
> NMS-16395: Reworked character handling in AbstractSnmpValue

- opennms-base-assembly/src/main/filtered/bin/update-package-permissions
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16423
> NMS-16423: Fix unescaped single quote in update package permission script

- opennms-webapp/src/main/webapp/WEB-INF/web.xml
In order to implement a Single-Page-Application, leveraging the OpenNMS ReST APIs, CORS header must be set accordingly.
In OpenNMS instead of a Page response object, the `Content-Range` header Is defined in the format of `items <start>-<end>/<total>`. 
Clients may use this header to implement pagination support.
However, this header is not exposed by default.
With this change here if the CORS Filter is enabled, that header is exposed as well, allowing Single Page Applications to implement proper pagination support.
Cheers.
2. update the Jira …
> chg: expose content-range headers if cors is enabled

- opennms-provision/opennms-detectorclient-rpc/src/test/java/org/opennms/netmgt/provision/detector/client/rpc/LocationAwareDetectorClientIT.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/AbstractDetector.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16360
> NMS-16360: Adding collection property to detectors

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsNodeTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-provision/opennms-provisiond/src/test/resources/NMS16347-1
- opennms-provision/opennms-provisiond/src/test/resources/NMS16347-2
* JIRA: https://opennms.atlassian.net/browse/NMS-16347
> NMS-16347: Delete old primary interface when changed

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16182
> NMS-16182: Updated hibernate-validator

- features/events/api/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16182
Fixed test
> NMS-16182: Fixed test

- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-model/src/test/java/org/opennms/netmgt/model/OnmsNodeTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-provision/opennms-provisiond/src/test/resources/NMS16347-1
- opennms-provision/opennms-provisiond/src/test/resources/NMS16347-2
* JIRA: https://opennms.atlassian.net/browse/NMS-16347
> NMS-16347: Backport NMS-16347 to release 33.x

- dependencies/spring-security/pom.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16383
> NMS-16383: Fixed CVE-2021-40690

- features/flows/itests/pom.xml
- features/geocoder/google/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16301
> NMS-16301: Upgraded camel's okio dependency

- features/telemetry/itests/src/test/java/org/opennms/netmgt/telemetry/itests/ListenerParserThreadingIT.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ParserBase.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16441
> NMS-16441: Backporting NMS-16243

- dependencies/jradius-extended/pom.xml
- dependencies/spring-security/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16384
> NMS-16384: Addressed CVE-2020-15522

- smoke-test/src/test/java/org/opennms/smoketest/topo/GraphMLTopologyIT.java
Fixing the smoke-test failure in foundation-2023. Feel free to approve & merge.
> Fixing smoke test

- container/features/src/main/resources/features.xml
- dependencies/netty/pom.xml
- features/collection/persistence-tcp/src/test/java/org/opennms/netmgt/collection/persistence/tcp/TcpOutputStrategyTest.java
- opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/AsyncLineOrientedDetectorNettyImpl.java
- opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/AsyncMultilineDetectorNettyImpl.java
- opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/LineOrientedRequestEncoder.java
- opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/LineOrientedResponseDecoder.java
- opennms-provision/opennms-detector-lineoriented/src/main/java/org/opennms/netmgt/provision/detector/simple/support/MultilineOrientedResponseDecoder.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/AsyncBasicDetectorNettyImpl.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/DetectFutureNettyImpl.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/DetectorHandlerNettyImpl.java
- opennms-provision/opennms-provision-api/src/main/java/org/opennms/netmgt/provision/support/TcpDetectorHandlerNettyImpl.java
- protocols/selenium-monitor/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16184
> NMS-16184: Upgrade to netty4 

- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/detail.jsp
- smoke-test/src/test/java/org/opennms/smoketest/AlarmsPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16417
> NMS-16417: Make the refresh work again

- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16445
> NMS-16445: Fixed XSS in Scheduled Outages

- features/vaadin-snmp-events-and-metrics/src/main/java/org/opennms/features/vaadin/mibcompiler/MibConsolePanel.java
- features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/mibcompiler/NMS16444Test.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16444
> NMS-16444: Fixed XSS in MibCompiler

- opennms-webapp/src/main/webapp/WEB-INF/applicationContext-spring-security.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16446
> NMS-16446: Deny access to rest/endpoints for unprivileged users

- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editCategory.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16448
> NMS-16448: Fixed XSS in Quick-Add Node

- opennms-webapp/src/main/webapp/WEB-INF/jsp/admin/editApplication.jsp
- smoke-test/src/test/java/org/opennms/smoketest/AdminPageIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16443
> NMS-16443: Escape locationName in editApplication.jsp

- opennms-base-assembly/src/main/filtered/etc/collectd-configuration.xml
> NMS-16492: Default metadata expression for Prom collector is broken

- container/features/src/main/resources/features.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15169
> NMS-15169: Bumped version for snakeyaml and jackson2

- features/distributed/kv-store/blob/blob-itests/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15169
> NMS-15169: Keeping snakeyaml 1.33 for tests

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16505
> NMS-16505: Bumped CXF version to 3.5.8

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16503
> NMS-16503: Bumped PostgreSQL version to 42.5.5

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16507
> NMS-16507: Bumped kafka version

- dependencies/spring-security/pom.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16504
> Backport NMS-16504 to foundation-2023

- container/features/src/main/resources/features-minion.xml
- core/grpc/osgi/pom.xml
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16180
> NMS-16180: Update grpc version

- opennms-full-assembly/src/assembly/components/osgi.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16514
> NMS-16514: Bumped bouncycastle version to 1.78.1

- opennms-base-assembly/src/main/filtered/etc/examples/scriptd-event-forwarder.bsh
Added to resolve the HTML encoded characters
* [ x] Have you read our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [ x] Have you (electronically) signed the [OpenNMS Contributor Agreement](https://cla-assistant.io/OpenNMS/opennms)?
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16501
> NMS-16501: Update scriptd-event-forwarder.bsh

- container/features/src/main/resources/features-minion.xml
- core/grpc/osgi/pom.xml
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16180
> NMS-16180: Backport grpc client version update

- dependencies/spring-security/pom.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16515
> NMS-16515: Excluding vulnerable esapi version

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16546
> NMS-16546: Bumped swagger-ui version

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16550
> NMS-16550: Bumped CXF version

- opennms-config/src/main/java/org/opennms/netmgt/config/DestinationPathManager.java
- JIRA: https://opennms.atlassian.net/browse/NMS-16435
> NMS-16435 : Fix Usage statistics reporter throws an NPE in the stdout on startup

- features/api-layer/dao-common/src/main/java/org/opennms/features/apilayer/model/mappers/MonitoredServiceMapper.java
- features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/MonitoredServiceMapperTest.java
- pom.xml
Add status.
Consider status is `Up` only if it is in Managed state and there are no outages.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/MPLUG-21
> MPLUG-21:  Add monitored service status

- opennms-full-assembly/src/assembly/components/osgi.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16549
> NMS-16549: Exclude proton-j version 0.26.0

- opennms-model/src/main/java/org/opennms/netmgt/model/NetworkBuilder.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeRestServiceIT.java
- opennms-webapp-rest/src/test/resources/v1/nodes.json
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16571
> NMS-16571 : Include nodeParentId in Rest API V2 returns for Node

- core/test-api/dns/src/main/java/org/opennms/core/test/dns/DNSServer.java
- integrations/opennms-dns-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/DnsProvisioningAdapter.java
- opennms-provision/opennms-requisition-dns/src/main/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionProvider.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16591
> NMS-16591: Fix compatibility with dnsjava update

- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/InvalidPacketException.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ipfix/proto/DataSet.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/ipfix/proto/FieldSpecifier.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/DataSet.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/FieldSpecifier.java
- features/telemetry/protocols/netflow/parser/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/parser/netflow9/proto/ScopeFieldSpecifier.java
…6375### All Contributors
* If …
> NMS-16375: Improve error messages for malformed netflow packets

- container/features/src/main/resources/features.xml
- core/test-api/dns/src/main/java/org/opennms/core/test/dns/DNSServer.java
- opennms-provision/opennms-requisition-dns/src/main/java/org/opennms/netmgt/provision/service/dns/DnsRequisitionProvider.java
Trying to match dnsjava updates from foundation-2023
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16591
> NMS-16591: Dnsjava library updates 

- features/mib-compiler/src/main/java/org/opennms/features/mibcompiler/services/JsmiMibParser.java
Include the failing object name in the log, example:
```
2024-10-22T12:39:15,290 | ERROR | qtp94171951-1380 | JsmiMibParser                    | 383 - org.opennms.features.mib-compiler - 33.0.6 | Graph templates parsing error: An unknown error accured when generating graph templates from the MIB SPAGENT-MIB at config.cfgEMailResendInterval
java.lang.NullPointerException: null
```
...and if the description is null, use a placeholder string rather than NPE and bail out on generating the graphs.
2. update the Jira link at the bottom of this …
> NMS-16595: Fix Mib Compiler graph generation NPE

- ui/src/containers/OpenAPI.vue
- https://opennms.atlassian.net/browse/NMS-16530
> NMS-16530: OpenNMS RESTful API provides incorrect URL in GUI after SSL enablement.

- docs/modules/operation/pages/deep-dive/flows/distributed.adoc
- docs/modules/reference/pages/telemetryd/protocols/bmp/adapter.adoc
- docs/modules/reference/pages/telemetryd/protocols/bmp/peer-status.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-16586
> NMS-16375: Added a few doc entries

- opennms-model/src/main/java/org/opennms/netmgt/model/NetworkBuilder.java
- opennms-model/src/main/java/org/opennms/netmgt/model/OnmsNode.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/AlarmRestServiceIT.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/NodeRestServiceIT.java
- opennms-webapp-rest/src/test/resources/v1/nodes.json
* NMS-16571 : Include nodeParentId in Rest API V2 returns for Node [ci skip]
* NMS-16571 : added changes to /v2/nodes [ci skip]
* NMS-16571 : added changes to /v2/nodes [ci skip]
* NMS-16571 : readonly nodeparentid to /v2/nodes [ci skip]
* NMS-16571 : added xml transient [ci skip]
* NMS-16571 : cicd tests .
* NMS-16571 : added testcase [ci skip]
* NMS-16571 : added testcase in NodeRestServiceIT
* NMS-16571 : assert null check for one parameter.
* NMS-16571 : Removed JUnit temporary db.
* NMS-16571 : added node parent id in json.
* NMS-16571 : added rest call for tests [ci ckip].
* NMS-16571 : dynamic id's,null check  [ci skip].
* NMS-16571 : added rest call for parents tests .
* Please [make an issue in the OpenNMS issue tracker](https://opennms.atlassian.net/) if there isn't one …
> NMS-16571 : Include nodeParentId in Rest API V2 returns for Node (#7459)

- features/newts-repository-converter/src/test/resources/opennms-home/etc/opennms.properties
* JIRA: https://opennms.atlassian.net/browse/NMS-16936
> NMS-16936: Fixed NewtsConverterIT to work another ten years

- opennms-webapp/src/main/web-filtered/WEB-INF/version.properties
- opennms-webapp/src/main/webapp/about/index.jsp
- opennms-webapp/src/main/webapp/includes/help-documentation.jsp
- pom.xml
- https://opennms.atlassian.net/browse/NMS-16482
> NMS-16482: Version in about page points to invalid release notes.

- core/mate/model/src/main/java/org/opennms/core/mate/model/EntityScopeProviderImpl.java
- core/mate/model/src/test/java/org/opennms/core/mate/model/EntityScopeProviderIT.java
- docs/modules/deployment/pages/time-series-storage/timeseries/cortex.adoc
- docs/modules/operation/pages/deep-dive/meta-data.adoc
- features/perspectivepoller/src/test/java/org/opennms/netmgt/perspectivepoller/PerspectivePollerdIT.java
- features/topology-map/plugins/org.opennms.features.topology.plugins.topo.linkd/src/test/java/org/opennms/features/topology/plugins/topo/linkd/internal/EnhancedLinkdMockDataPopulator.java
- opennms-dao/src/main/java/org/opennms/netmgt/dao/DatabasePopulator.java
- opennms-model/src/test/java/org/opennms/netmgt/model/NetworkBuilderTest.java
> NMS-16945: Ensure IfName is available as meta-data

- features/endpoints/grafana/client/pom.xml
- pom.xml
- smoke-test/src/test/java/org/opennms/smoketest/GrafanaEndpointPageIT.java
* Jira (Issue Tracker):  https://opennms.atlassian.net/browse/NMS-16367
> NMS-16367 : Fix grafana reports endpoint failure.

- docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel9/install-core.adoc
We have a regression from NMS-16164 refactoring from an ifeval to an attribute to configure the distribution-dependent package names. I have configured the code blocks to allow variable substitution.
* **If this code is likely to …
> NMS-16490: Fix substitution replacement for package prefix

- protocols/xml/src/main/java/org/opennms/protocols/xml/collector/AbstractXmlCollectionHandler.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16949
> NMS-16949: Fixed test

- docs/modules/reference/pages/performance-data-collection/collectors/jmx.adoc
according to https://github.com/OpenNMS/opennms/blob/b0bf2756b809dfda501b91cff9b3ebc821316017/core/jmx/api/src/main/java/org/opennms/netmgt/jmx/ParameterName.java#L32 the correct key is `friendly-name`
* **If this code is likely …
> fix(doc): Fix typo in JMX collector for friendly name

- opennms-webapp/src/main/java/org/opennms/web/controller/SendEventController.java
> NMS-16485: 500 Server Error when sending events from GUI when OpenNMS has large number of Events configured

- opennms-services/src/main/java/org/opennms/netmgt/poller/Poller.java
The error itself had accidentally been removed in the logging. 
Seeing an error in this place when an node is added and removed with the same IP address, which we want to investigate further. Sadly the error message we need is not logged.
Don't worry if this sounds like a lot, we can help you get things set up …
> Fix error logging in Poller for service scheduling

- smoke-test/src/main/java/org/opennms/smoketest/containers/GrafanaContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/containers/OpenNMSContainer.java
- smoke-test/src/main/java/org/opennms/smoketest/stacks/NetworkProtocol.java
- smoke-test/src/test/java/org/opennms/smoketest/GrafanaEndpointPageIT.java
- smoke-test/src/test/java/org/opennms/smoketest/grafana/endpoint/GrafanaTokenDTO.java
- smoke-test/src/test/java/org/opennms/smoketest/grafana/endpoint/ServiceAccountDTO.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16944
> NMS-16944 : Create a smoke test that validates Grafana connection.

- docs/modules/reference/nav.adoc
- docs/modules/reference/pages/service-assurance/monitors/PtpMonitor.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-16957
> NMS-16957: Added documentation for PTP monitor

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16961
> NMS-16961: Updated fop-core to version 2.10

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16962
> NMS-16962: Updated cxf-core to version 3.6.3

- features/api-layer/dao-common/src/main/java/org/opennms/features/apilayer/model/mappers/MonitoredServiceMapper.java
- features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/MonitoredServiceMapperTest.java
- pom.xml
This is backport of #7464 
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16972
> NMS-16972:  Add monitored service status

- docs/modules/deployment/pages/time-series-storage/timeseries/configuration.adoc
- features/collection/api/src/main/java/org/opennms/netmgt/collection/api/CollectionResource.java
- features/collection/api/src/main/java/org/opennms/netmgt/collection/api/LatencyCollectionResource.java
- features/collection/api/src/main/java/org/opennms/netmgt/collection/dto/CollectionSetDTO.java
- features/collection/api/src/main/java/org/opennms/netmgt/collection/support/AbstractCollectionResource.java
- features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/LatencyTypeResource.java
- features/collection/api/src/main/java/org/opennms/netmgt/collection/support/builder/Resource.java
- features/timeseries/src/main/java/org/opennms/netmgt/timeseries/samplewrite/MetaTagDataLoader.java
- features/timeseries/src/test/java/org/opennms/netmgt/timeseries/samplewrite/TimeseriesRoundtripIT.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/LatencyStoringServiceMonitorAdaptor.java
- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/StatusStoringServiceMonitorAdaptor.java
Add interface/snmpinterface metadata in tags for latency resource
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16946
> NMS-16946: Add interface info in tags for latency resource

- opennms-container/common.mk
- opennms-container/core/Dockerfile
- opennms-container/minion/Dockerfile
- opennms-container/sentinel/Dockerfile
- smoke-test/src/main/java/org/opennms/smoketest/containers/MockCloudContainer.java
Updating the base image to the latest version, this is to pick up the fixes in NMS-16516
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16984
> NMS-16984: DevOps: Update base images in foundation-2024 Add Apps

- core/snmp/impl-joesnmp/src/test/java/org/opennms/netmgt/snmp/joesnmp/NMS16395Test.java
- core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/NMS16395Test.java
- core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java
- features/distributed/coordination/zookeeper/src/test/java/org/opennms/features/distributed/coordination/zookeeper/ZookeeperDomainManagerFactoryTest.java
- features/distributed/coordination/zookeeper/src/test/java/org/opennms/features/distributed/coordination/zookeeper/ZookeeperDomainManagerIT.java
- features/distributed/coordination/zookeeper/src/test/java/org/opennms/features/distributed/coordination/zookeeper/ZookeeperDomainManagerTest.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/NMS16357Test.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v1/ForeignSourceRestServiceIT.java
- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- smoke-test/src/main/java/org/opennms/smoketest/selenium/AbstractOpenNMSSeleniumHelper.java
- smoke-test/src/test/java/org/opennms/smoketest/NodeDetailPageIT.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16995
> NMS-16995: Foundation-2022 Update copyright dates

- core/snmp/impl-joesnmp/src/test/java/org/opennms/netmgt/snmp/joesnmp/NMS16395Test.java
- core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/NMS16395Test.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSetBuilder.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpSetRequestDTO.java
- features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/MonitoredServiceMapperTest.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/NMS16345Test.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PtpMonitor.java
- features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/PtpMonitorTest.java
- features/springframework-security/src/test/java/org/opennms/web/springframework/security/NMS16450Test.java
- features/telemetry/protocols/openconfig/adapter/src/test/resources/openconfig-gnmi-telemetry.groovy
- features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/mibcompiler/NMS16444Test.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/NMS16357Test.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpSetIT.java
- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/index.jsp
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16995
> NMS-16995: Foundation-2024 Update copyright dates

- core/snmp/impl-joesnmp/src/test/java/org/opennms/netmgt/snmp/joesnmp/NMS16395Test.java
- core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/NMS16395Test.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSetBuilder.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpSetRequestDTO.java
- features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/MonitoredServiceMapperTest.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/NMS16345Test.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PtpMonitor.java
- features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/PtpMonitorTest.java
- features/springframework-security/src/test/java/org/opennms/web/springframework/security/NMS16450Test.java
- features/telemetry/protocols/openconfig/adapter/src/test/resources/openconfig-gnmi-telemetry.groovy
- features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/mibcompiler/NMS16444Test.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/NMS16357Test.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpSetIT.java
- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/index.jsp
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16995
> NMS-16995: Release-33.x Update copyright dates

- core/snmp/impl-joesnmp/src/test/java/org/opennms/netmgt/snmp/joesnmp/NMS16395Test.java
- core/snmp/impl-snmp4j/src/test/java/org/opennms/netmgt/snmp/snmp4j/NMS16395Test.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SNMPSetBuilder.java
- core/snmp/proxy-rpc-impl/src/main/java/org/opennms/netmgt/snmp/proxy/common/SnmpSetRequestDTO.java
- features/api-layer/dao-common/src/test/java/org/opennms/features/apilayer/utils/MonitoredServiceMapperTest.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/NMS16345Test.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/PtpMonitor.java
- features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/PtpMonitorTest.java
- features/springframework-security/src/test/java/org/opennms/web/springframework/security/NMS16450Test.java
- features/telemetry/protocols/openconfig/adapter/src/test/resources/openconfig-gnmi-telemetry.groovy
- features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/mibcompiler/NMS16444Test.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/NMS16357Test.java
- opennms-services/src/test/java/org/opennms/netmgt/collectd/SnmpSetIT.java
- opennms-webapp/src/main/webapp/includes/bootstrap-footer.jsp
- opennms-webapp/src/main/webapp/includes/footer.jsp
- opennms-webapp/src/main/webapp/index.jsp
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16995
> NMS-16995: Develop update copyright dates

- smoke-test/src/test/java/org/opennms/smoketest/SystemReportPageIT.java
Fix system report merge issue
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16997
> NMS-16997: Fix system report merge issue

- docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
The current Meridian docs do not describe the correct procedure for configuring newts with org.opennms.newts.config.driver_settings_file or describe the content of the driver file itself.
* **If this code is likely to affect the …
> NMS-16418: Update NewTS docs

- docs/modules/deployment/pages/minion/message-broker/kafka.adoc
- docs/modules/deployment/pages/minion/system-requirements.adoc
NMS-16941 typo in Kafka Karaf shell commands.
NMS-16940 supported distro missing rhel 9 (and el7 is dead; unsupported everywhere) …
> NMS-16940 & NMS-16941 : minor docs updates

- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
- opennms-webapp/src/main/webapp/admin/sched-outages/jsonNodes.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16585
> NMS-16585: Fixed XSS vulnerability

- features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdEntity.java
- features/collection/thresholding/impl/src/main/java/org/opennms/netmgt/threshd/ThresholdingSetImpl.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16966
> NMS-16966: Moved scope creation out of loops

- docs/modules/operation/pages/deep-dive/grpc-exporter/grpc-exporter.adoc
- features/grpc/exporter/src/main/java/org/opennms/features/grpc/exporter/GrpcExporterClient.java
- features/grpc/exporter/src/main/java/org/opennms/features/grpc/exporter/GrpcHeaderInterceptor.java
- features/grpc/exporter/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Also simplify host ( remove port from config)
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17003
> NMS-17003: Add tenant id on grpc exporter 

- container/features/src/main/resources/features-core.xml
- core/lib/src/main/java/org/opennms/core/fileutils/FileUpdateWatcher.java
- features/scv/api/src/main/java/org/opennms/features/scv/api/SecureCredentialsVault.java
- features/scv/jceks-impl/pom.xml
- features/scv/jceks-impl/src/main/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVault.java
- features/scv/jceks-impl/src/main/resources/META-INF/opennms/applicationContext-jceks-scv.xml
- features/scv/jceks-impl/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- features/scv/jceks-impl/src/test/java/org/opennms/features/scv/jceks/JCEKSSecureCredentialsVaultTest.java
Address sync issue between scvcli and OpenNMS
Add a file watcher to reload cache when keystore file gets updated
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-16943
> NMS-16943:  Fix sync issues between OpenNMS and scvcli

- opennms-base-assembly/src/main/filtered/etc/datacollection/mssqlserver-jdbc.xml
- opennms-base-assembly/src/main/filtered/etc/datacollection/oracle-jdbc.xml
- opennms-base-assembly/src/main/filtered/etc/jdbc-datacollection.d/mssqlserver.xml
- opennms-base-assembly/src/main/filtered/etc/jdbc-datacollection.d/mysql.xml
- opennms-base-assembly/src/main/filtered/etc/jdbc-datacollection.d/oracle.xml
- opennms-base-assembly/src/main/filtered/etc/snmp-graph.properties.d/oracle-jdbc-graph.properties
> NMS-17081: Additional JDBC datacollections

- docs/modules/deployment/pages/time-series-storage/newts/newts.adoc
> NMS-17078: add page-size to driver_settings_file example

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-17040
> NMS-17040: Bumped mina version

- features/geocoder/google/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16706
> NMS-16706: Changed gson version for google geocoder

- core/schema/src/main/liquibase/33.0.3/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
- features/kafka/producer/src/test/java/org/opennms/features/kafka/producer/KafkaForwarderIT.java
- opennms-alarms/daemon/src/main/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContext.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/drools/DroolsAlarmContextIT.java
- opennms-alarms/daemon/src/test/java/org/opennms/netmgt/alarmd/examples/DroolsExampleIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16966
> NMS-16966: Added indices for metadata tables

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16724
> NMS-16724: Bumped esapi version

- core/ipc/common/kafka/pom.xml
- core/test-api/kafka/pom.xml
- core/test-api/kafka/src/main/java/org/opennms/core/test/kafka/JUnitKafkaServer.java
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-17059
> NMS-17059: Bumped kafka-metadata version

- core/daemon/pom.xml
- core/daemon/src/main/java/org/opennms/netmgt/vmmgr/Controller.java
- core/daemon/src/test/java/org/opennms/netmgt/vmmgr/ControllerTest.java
- docs/modules/operation/pages/deep-dive/meta-data.adoc
* JIRA: https://opennms.atlassian.net/browse/NMS-16989
> NMS-16989: Support meta-data interpolation for system properties

- features/events/api/src/main/java/org/opennms/netmgt/events/api/EventConstants.java
- features/system-report/pom.xml
- features/system-report/src/main/java/org/opennms/systemreport/AbstractSystemReportPlugin.java
- features/system-report/src/main/java/org/opennms/systemreport/SystemReportPlugin.java
- features/system-report/src/main/java/org/opennms/systemreport/event/CsvUtils.java
- features/system-report/src/main/java/org/opennms/systemreport/event/UserLoginEventListener.java
- features/system-report/src/main/java/org/opennms/systemreport/formatters/CsvSystemReportFormatter.java
- features/system-report/src/main/java/org/opennms/systemreport/formatters/ZipSystemReportFormatter.java
- features/system-report/src/main/java/org/opennms/systemreport/system/UserLoginsReportPlugin.java
- features/system-report/src/main/resources/META-INF/opennms/applicationContext-systemReport.xml
- features/system-report/src/test/java/org/opennms/systemreport/system/ReportPluginITCase.java
- features/system-report/src/test/java/org/opennms/systemreport/system/SystemReportPluginIT.java
- features/system-report/src/test/resources/etc/user_logins.csv
- Jira : https://opennms.atlassian.net/browse/NMS-17079
> NMS-17079 : Add User Logins reports to the system report bundle.

- core/schema/src/main/liquibase/33.0.3/changelog.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-17005
> NMS-17005: Changed userlastmodified data type

- docs/modules/releasenotes/pages/whatsnew.adoc
- opennms-provision/opennms-provision-persistence/src/main/java/org/opennms/netmgt/provision/persist/requisition/Requisition.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/CachingForeignSourceRepositoryIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FastFilesystemForeignSourceRepositoryIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/FilesystemForeignSourceRepositoryIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/MockForeignSourceRepositoryIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/QueueingForeignSourceRepositoryIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/requisition/RequisitionImplementationIT.java
- opennms-provision/opennms-provision-persistence/src/test/java/org/opennms/netmgt/provision/persist/requisition/RequisitionValidationTest.java
- opennms-provision/opennms-provisiond/src/test/java/org/opennms/netmgt/provision/service/ProvisionerIT.java
- opennms-provision/opennms-provisiond/src/test/resources/NMS-5414.xml
- opennms-provision/opennms-provisiond/src/test/resources/SPC-391.xml
- opennms-provision/opennms-provisiond/src/test/resources/requisition_then_scanv6.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-16537
> NMS-16537: Forbid invalid requisition names

- opennms-webapp/src/main/webapp/WEB-INF/jsp/newsfeed/newsFeedPanel.jsp
The front end `newsFeedPanel.jsp`  overwrites the `newsFeedUrl` with the value of the system property `opennms.newsFeedPanel.url`, this is unnecessary and breaks the feed if the systemproperty is set.  Just use the available REST endpoint instead, and let the backend handle the URL content.
Don't worry if this …
> NMS-16373: Fix newsfeed sysprop handling

- opennms-services/src/main/java/org/opennms/netmgt/poller/pollables/PollableService.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16963
> NMS-16963: Changed log level to trace

- docs/modules/reference/pages/service-assurance/monitors/PassiveStatusMonitor.adoc
- docs/modules/releasenotes/pages/whatsnew.adoc
- features/poller/api/src/main/java/org/opennms/netmgt/poller/PollStatus.java
- opennms-services/src/main/java/org/opennms/netmgt/passive/PassiveStatusKeeper.java
- opennms-services/src/test/java/org/opennms/netmgt/poller/monitors/PassiveServiceMonitorIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-14199
> NMS-14199: Change status timestamp if event time is set

- opennms-webapp/src/main/webapp/admin/sched-outages/index.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-15517
> NMS-15517: Use ReST-call to delete scheduled outage

- docs/modules/reference/pages/provisioning/adapters/snmp-metadata.adoc
- docs/modules/releasenotes/pages/whatsnew.adoc
- integrations/opennms-snmp-metadata-provisioning-adapter/src/main/java/org/opennms/netmgt/provision/SnmpMetadataProvisioningAdapter.java
- opennms-base-assembly/src/main/filtered/etc/snmp-metadata-adapter-configuration.xml
- opennms-config-model/src/main/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfig.java
- opennms-config-model/src/main/resources/xsds/snmp-metadata-adapter-configuration.xsd
- opennms-config-model/src/test/java/org/opennms/netmgt/config/snmpmetadata/SnmpMetadataConfigTest.java
* JIRA: https://opennms.atlassian.net/browse/NMS-17721
> NMS-17721: Disable SnmpMetadataProvisioningAdapter by default

- docs/modules/operation/nav.adoc
- docs/modules/operation/pages/deep-dive/zenith-connect/introduction.adoc
Initial documentation for the Zenith Connect feature. showing how the feature can be enabled and configured.
More documentation will be added as the feature is built out.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17754
> NMS-17754: Zenith Connect initial documentation

- opennms-webapp/src/main/java/org/opennms/web/alarm/AlarmQueryServlet.java
- opennms-webapp/src/main/webapp/includes/resultsIndex.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-16421
This fixes the parameter handling of the situation field in the search. The other change prevents the link of current result's page to lead back to the landing page.
> NMS-16421: Fixed handling of parameter 'situation' in search

- docs/modules/reference/pages/service-assurance/monitors/IcmpMonitor.adoc
I think at one time this may have been common knowledge, but it was not documented anywhere and the difference resulted in some confusion.
* **If this code is likely to affect the UI, did you name your branch with `-smoke` in it …
> NMS-17855: Note response time difference for IcmpMonitor

- container/features/src/main/resources/features-core.xml
- features/distributed/coordination/zookeeper/pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-15396
> NMS-15396: Fix apache curator bundle loading

- docs/modules/deployment/pages/core/centos-rhel7/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel8/install-core.adoc
- docs/modules/deployment/pages/core/centos-rhel9/install-core.adoc
- docs/modules/deployment/pages/core/debian/install-core.adoc
- docs/modules/deployment/pages/core/ubuntu/install-core.adoc
> NMS-17856: Remove obsolete R-core install notes

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-17854
> NMS-17854: Updated cxf-core version

- docs/modules/operation/pages/deep-dive/device-config-backup/configuration.adoc
The longer I stared at the original words the more clear the intent became, however, since all modern OpenNMS versions ship with `CAP_NET_BIND_SERVICE` we should make it clearer that yes, you can bind the listener to the IANA default TFTP port and ignore all the non-default / non-privileged port and firewall rule nonsense.  Hopefully this makes things clearer.
4. once you've created this PR, …
> NMS-17755: DCB poller docs improvements

- features/grpc/exporter/src/main/java/org/opennms/features/grpc/exporter/bsm/BsmInventoryExporter.java
- features/grpc/exporter/src/main/java/org/opennms/features/grpc/exporter/spog/InventoryExporter.java
- features/grpc/exporter/src/main/java/org/opennms/features/grpc/exporter/spog/SpogInventoryService.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17857
> NMS-17857: Fix newly added nodes not being exported

- features/vaadin-surveillance-views/src/main/java/org/opennms/features/vaadin/surveillanceviews/ui/SurveillanceViewTable.java
- opennms-webapp/src/main/java/org/opennms/web/controller/notification/NotificationFilterController.java
- opennms-webapp/src/main/java/org/opennms/web/nodelabel/NodeLabelChangeServlet.java
- opennms-webapp/src/main/webapp/WEB-INF/jsp/alarm/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/notification/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/jsp/outage/list.jsp
- opennms-webapp/src/main/webapp/WEB-INF/templates/navbar.ftl
- opennms-webapp/src/main/webapp/admin/nodelabel.jsp
- opennms-webapp/src/main/webapp/element/node.jsp
* JIRA: https://opennms.atlassian.net/browse/NMS-17875
> NMS-17875: Fixed XSS issues

- features/status/api/src/main/java/org/opennms/features/status/api/node/strategy/query/Query.java
- features/status/api/src/test/java/org/opennms/features/status/api/node/strategy/DefaultNodeStatusCalculatorIT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-17876
Unfortunately, it is not possible to pass the columns for the OrderBy-clause in a prepared statement so that they are correctly escaped. This is because they are not string literals or numbers but names of table columns. We only want to allow the columns of the node entity and also the calculated severity. Unfortunately, not all property names in our node entity match the database columns (e.g. label vs. nodeLabel). Therefore, I had to do a little trickery to determine all valid column names programmatically.
> NMS-17876: Limit the columns for orderBy clause

- docs/modules/deployment/pages/opentracing/core.adoc
- docs/modules/deployment/pages/opentracing/minion.adoc
- docs/modules/deployment/pages/opentracing/sentinel.adoc
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17891
> NMS-17891: Update docs for Jaeger Tracing

- docs/modules/reference/pages/daemons/daemon-config-files/trapd.adoc
Surprised this information isn't already in the docs.  This commit adds text to plainly state the supported options for Trapd's `auth-protocol` and `privicy-protocol` .
* **If this code is likely to affect the UI, did you name …
> State the supported options for trapd's snmpv3 auth and priv

- features/grpc/exporter/pom.xml
- features/grpc/exporter/src/test/java/org/opennms/features/grpc/exporter/SpogExporterIT.java
- features/grpc/exporter/src/test/java/org/opennms/features/grpc/exporter/SpogInventoryServiceSyncIT.java
External References
- Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17896
> NMS-17896 : Fix grpc exporter integration test

- features/reporting/availability/src/main/java/org/opennms/reporting/availability/render/HTMLReportRenderer.java
- features/reporting/availability/src/test/java/org/opennms/reporting/availability/render/NMS16414_IT.java
* JIRA: https://opennms.atlassian.net/browse/NMS-16414
> NMS-16414: Reducing the risk of XSLT injection

- .circleci/scripts/postgres.sh
- core/test-api/db/src/main/java/org/opennms/core/test/db/TemporaryDatabase.java
- opennms-provision/opennms-detector-jdbc/src/test/java/org/opennms/netmgt/provision/detector/JDBCDetectorIT.java
- opennms-provision/opennms-detector-jdbc/src/test/java/org/opennms/netmgt/provision/detector/JdbcQueryDetectorIT.java
- opennms-provision/opennms-detector-jdbc/src/test/java/org/opennms/netmgt/provision/detector/JdbcStoredProcedureDetectorIT.java
- pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17951
> NMS-17951: Postgres fails to come up on integration tests (Round 2)

- opennms-webapp/src/main/java/org/opennms/web/admin/notification/DestinationWizardServlet.java
* JIRA: https://opennms.atlassian.net/browse/NMS-17911
> NMS-17911: Fixed mail command

- docs/modules/releasenotes/pages/whatsnew.adoc
- opennms-base-assembly/src/main/filtered/bin/fix-karaf-setup.sh
- opennms-base-assembly/src/main/filtered/bin/install
* JIRA: https://opennms.atlassian.net/browse/NMS-18008
> NMS-18008: Run fix-karaf-setup.sh each time install-sh is executed

- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTO.java
- features/datachoices/src/main/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReporter.java
- features/datachoices/src/test/java/org/opennms/features/datachoices/internal/usagestatistics/UsageStatisticsReportDTOTest.java
Resolved merge conflicts for release33.x
> Resolved merge conflicts for release33.x

- .circleci/main/jobs/publish.yml
- dependencies/oia/pom.xml
- pom.xml
- smoke-test/pom.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18019
> NMS-18019: OSSRH to Central Portal Migration

- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-17996
> NMS-17996: Bumped commons-beanutils version

- core/lib/src/main/java/org/opennms/core/time/CentralizedDateTimeFormat.java
- core/lib/src/main/java/org/opennms/core/time/ExtendedDateOnlyFormat.java
- core/lib/src/main/java/org/opennms/core/time/ExtendedTimeOnlyFormat.java
- core/lib/src/test/java/org/opennms/core/time/ExtendedDateOnlyFormatTest.java
- core/lib/src/test/java/org/opennms/core/time/ExtendedTimeOnlyFormatTest.java
- opennms-base-assembly/src/main/filtered/etc/opennms.properties
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/HttpMenuRequestContext.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProvider.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/MenuProviderLegacy.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/support/menu/model/MainMenu.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/menu/MenuProviderLegacyTest.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/support/menu/MenuProviderTest.java
- ui/src/components/Menu/Menubar.vue
- ui/src/components/Menu/utils.ts
- ui/src/stores/fakeMenuData.ts
- ui/src/types/mainMenu.d.ts
- ui/yarn.lock
Allow separate date and time format customization for the new menu.
(Note: smoke tests are expected to fail, they will be fixed in an upcoming PR.)
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-17992
> NMS-17992: Menu redesign, date and time customization

- features/telemetry/protocols/openconfig/adapter/src/test/java/org/opennms/netmgt/telemetry/protocols/openconfig/adapter/OpenConfigAdapterTest.java
- features/telemetry/protocols/openconfig/adapter/src/test/resources/openconfig-gnmi-telemetry.groovy
- opennms-base-assembly/src/main/filtered/etc/telemetryd-adapters/openconfig-gnmi-telemetry.groovy
Also added a test case to validate this
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18060
> NMS-18060: Update groovy script to parse more metrics

- ui/src/components/Nodes/NodesTable.vue
Move Search Input box to the left
Prompt should be "Search List"
Should have Search icon
Add filter button
For now it will just search the same as the current input.
Separate issue for the Filter functionality.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18043
> NMS-18043: Move Node Search input

- opennms-full-assembly/src/assembly/components/osgi.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-18038
> NMS-18038: Prevent old jetty version from being included

- features/collection/api/src/main/java/org/opennms/netmgt/collection/dto/CollectionSetDTO.java
- features/telemetry/protocols/netflow/adapter/src/main/java/org/opennms/netmgt/telemetry/protocols/netflow/adapter/common/NetflowTelemetryAdapter.java
- features/telemetry/registry/src/main/resources/META-INF/opennms/component-dao.xml
- features/telemetry/registry/src/main/resources/OSGI-INF/blueprint/blueprint.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-18027
> NMS-18027: Added metrics for IPFIX data collection

- docs/modules/development/pages/rest/health_rest.adoc
DOCS DOCS DOCS DOCS!
From chat:
https://chat.opennms.com/opennms/pl/omk95b6qs3ddugscxhe7q9wepa
> Docs: Clarify paths for /rest/health

- docs/modules/deployment/pages/core/admin-password-reset.adoc
Explain how we force people to change their password to something else than admin.
> Update Admin Password Doc

- docs/modules/operation/pages/deep-dive/admin/configuration/scv-configuration.adoc
- docs/modules/releasenotes/pages/whatsnew.adoc
- features/scv/scvcli/pom.xml
- features/scv/scvcli/src/main/filtered/scvcli-filtered.properties
- features/scv/scvcli/src/main/java/org/opennms/features/scv/cli/ScvCli.java
- opennms-base-assembly/src/main/filtered/bin/scvcli
Jira: [https://opennms.atlassian.net/browse/NMS-18131](https://opennms.atlassian.net/browse/NMS-18131)
> NMS-18131 : Fix scvcli issue with scv type

- core/schema/src/main/liquibase/35.0.0/changelog.xml
- core/schema/src/main/liquibase/changelog.xml
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18149
> NMS-18149: Add liquibase schema for event conf

- ui/src/components/Menu/Menubar.vue
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18180
> FE: Move date/time to just to the left of the Notifications control

- docs/modules/releasenotes/pages/whatsnew.adoc
1. Node Cache configuration moved to breaking changes
2. Added scv to whatsnew and removed from breaking changes ( config updates were already present in scv doc)
3. Added Elastic and Flows upgrade in whatsnew
4. Added snmp4j related updates to breaking changes
> Update release notes

- smoke-test/src/test/java/org/opennms/smoketest/rest/SituationRestServicesIT.java
SituationRestIT  have flaky test case issue . Fixed it 
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18205
> NMS-18205:  Fix SituationRestIT  flaky test

- core/tracing/jaeger-osgi/pom.xml
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-18215
> NMS-18215: Excluding vulnerable okio versions

- docs/modules/operation/pages/deep-dive/events/sources/syslog.adoc
> Note about TCP syslog

- opennms-dao/src/main/java/org/opennms/netmgt/dao/hibernate/EventConfSourceDaoHibernate.java
- opennms-dao/src/test/java/org/opennms/netmgt/dao/EventConfSourceDaoIT.java
- opennms-model/src/main/java/org/opennms/netmgt/model/events/EventConfSrcEnableDisablePayload.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventConfPersistenceService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventConfRestService.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/api/EventConfRestApi.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/EventConfPersistenceServiceIT.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/EventConfRestServiceIT.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18233
> NMS:18233: Enable or disable one or more sources (and optionally cascade to their events).

- docs/modules/development/nav.adoc
- docs/modules/development/pages/rest/scv.adoc
DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS DOCS 
Document the `/scv` rest api endpoint
> DOCS: Document the /scv endpoint

- ui/package.json
- ui/src/components/EventConfigurationDetail/Dialog/ChangeEventConfEventStatusDialog.vue
- ui/src/components/EventConfigurationDetail/Dialog/DeleteEventConfigEventDialog.vue
- ui/src/components/EventConfigurationDetail/EventConfigEventTable.vue
- ui/src/services/eventConfigService.ts
- ui/src/stores/eventConfigDetailStore.ts
- ui/src/stores/eventConfigStore.ts
- ui/src/types/eventConfig.d.ts
- ui/yarn.lock
Enable/Disable event under a specific resource
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/${JIRA-ISSUE-NUMBER}
> FE: Enable/Disable event under a specific resource

- ui/package.json
- ui/src/components/EventConfiguration/Dialog/ChangeEventConfSourceStatusDialog.vue
- ui/src/components/EventConfiguration/Dialog/DeleteEventConfigSourceDialog.vue
- ui/src/components/EventConfiguration/Dialog/EventConfigFilesUploadReportDialog.vue
- ui/src/components/EventConfiguration/EventConfigSourceTable.vue
- ui/src/components/EventConfiguration/EventConfigTabContainer.vue
- ui/src/components/EventConfiguration/EventConfigUploadFilesTab.vue
- ui/src/components/EventConfiguration/data.ts
- ui/src/components/EventConfigurationDetail/Dialog/ChangeEventConfEventStatusDialog.vue
- ui/src/components/EventConfigurationDetail/Dialog/ChangeEventConfSourceStatusDialog.vue
- ui/src/components/EventConfigurationDetail/Dialog/DeleteEventConfigEventDialog.vue
- ui/src/components/EventConfigurationDetail/Dialog/DeleteEventConfigSourceDialog.vue
- ui/src/components/EventConfigurationDetail/EventConfigEventTable.vue
- ui/src/containers/EventConfigurationDetails.vue
- ui/src/services/eventConfigService.ts
- ui/src/stores/eventConfigDetailStore.ts
- ui/src/stores/eventConfigStore.ts
- ui/src/types/eventConfig.d.ts
- ui/yarn.lock
Enable/Disable a specific source
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18260
> FE: Enable/Disable a specific source

- docs/modules/reference/pages/service-assurance/monitors/HttpsMonitor.adoc
Background to this: https://github.com/OpenNMS/opennms/pull/7911
> SNI limitations and alternatives

- container/features/src/main/resources/features-core.xml
- container/features/src/main/resources/features-sentinel.xml
- container/shared/src/main/filtered-resources/etc/overrides.properties
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-18225
> NMS-18225: Updated netty version

- docs/modules/reference/pages/service-assurance/monitors/JDBCQueryMonitor.adoc
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JDBCMonitor.java
- features/poller/monitors/core/src/main/java/org/opennms/netmgt/poller/monitors/JDBCQueryMonitor.java
- features/poller/monitors/core/src/test/java/org/opennms/netmgt/poller/monitors/JDBCQueryMonitorTest.java
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18335
> NMS-18335: optionally add query and results to message

- docs/modules/reference/pages/configuration/core-docker.adoc
- opennms-container/core/container-fs/confd/templates/opennms-datasources.xml.tmpl
Only expose configuration parameters we want users be able to change easily. Document the environment variables in the documentation.
I have removed all configuration options we don't want users to change.
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18757
> NMS-18757: Cleanup database configuration using Confd

- ui/package.json
- ui/src/components/EventConfiguration/EventConfigUploadFilesTab.vue
- ui/tests/components/EventConfiguration/EventConfigUploadFilesTab.test.ts
Test coverage for EventConfigUploadFilesTab.vue
* Jira (Issue Tracker): https://opennms.atlassian.net/browse/NMS-18538
> FE: Test coverage for EventConfigUploadFilesTab.vue

- docs/modules/deployment/nav.adoc
- docs/modules/deployment/pages/minion/tuning.adoc
DOCS DOCS DOCS DOCS DOCS
We have no examples or instructions on how to adjust minion heap or open file descriptors.  Add 'em.
> DOCS: basic minion resource tuning

- container/features/src/main/resources/features.xml
- features/topology-map/org.opennms.features.topology.app/osgi.bnd
- features/topology-map/org.opennms.features.topology.app/pom.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-18343
> NMS-18343: Bumped jinjava version

- features/bsm/daemon/src/test/java/org/opennms/netmgt/bsm/daemon/BsmdIT.java
- features/discovery/src/test/java/org/opennms/netmgt/discovery/NewSuspectLocationTest.java
- features/events/collector/src/test/java/org/opennms/netmgt/collection/EventMetricsCollectorIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/JoeSnmpTrapHandlerIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/Snmp4JTrapHandlerIT.java
- features/events/traps/src/test/java/org/opennms/netmgt/trapd/TrapdIT.java
- features/vaadin-snmp-events-and-metrics/src/test/java/org/opennms/features/vaadin/events/EventFormTest.java
- opennms-config/src/main/java/org/opennms/netmgt/config/DefaultEventConfDao.java
- opennms-config/src/main/java/org/opennms/netmgt/config/EventConfUtil.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfDaoReloadTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfDataTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfMatcherTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventConfPriorityTest.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventconfFactoryIT.java
- opennms-config/src/test/java/org/opennms/netmgt/config/EventconfFactorySaveTest.java
- opennms-services/src/test/java/org/opennms/netmgt/mock/OpenNMSITCase.java
- opennms-services/src/test/java/org/opennms/netmgt/notifd/BroadcastEventProcessorIT.java
- opennms-webapp-rest/src/main/java/org/opennms/web/rest/v2/EventConfPersistenceService.java
- opennms-webapp-rest/src/test/java/org/opennms/web/rest/v2/EventConfPersistenceServiceIT.java
- smoke-test/src/test/java/org/opennms/smoketest/IntegrationAPIIT.java
Jira: [https://opennms.atlassian.net/browse/NMS-18295](https://opennms.atlassian.net/browse/NMS-18295)
> NMS-18295 : Disable loading of events from filesystem.
